### ISSUE TITLE
How convert Vp8 to Mp4 (can do it via command line).

### ISSUE THREAD

**Issue by sleski** [bytedeco/javacv#1000]
Hi, how can I do it in java? Via command line it looks like this:

`ffmpeg -fflags +genpts -i in.vp8 -r 24 out.mp4`

In java looks like this:

FFmpegFrameRecorder2 recorder = new FFmpegFrameRecorder2();
			recorder.setVideoCodecName("h264");
			recorder.setAudioCodecName("aac");
			recorder.setFormat("mp4");
			recorder.setFrameRate(grabber.getFrameRate());
			recorder.setOption("movflags", "frag_keyframe+empty_moov");
			recorder.setOption("preset", "ultrafast");
			recorder.setOption("crf", "23");
			recorder.setSampleRate(grabber.getSampleRate());
			recorder.start();
			Frame frame;
			while ((frame = grabber.grabFrame()) != null) {
				recorder.record(frame);
			}
			recorder.stop();
			grabber.stop();

But it does not work. Any advice how put "-fflags +genpts" this as param?

**Comment by saudet** [comment]
You will need to create an instance of `FFmpegFrameGrabber` as well, or it won't work for sure.

It looks like `genpts` maps to `AVFMT_FLAG_GENPTS`, so we can try to set that in the flags of `AVFormatContext`, but we can probably set it as well with
```java
 FFmpegFrameGrabber.setOption("fflags", "genpts");
```
or maybe
```java
FFmpegFrameGrabber.setOption("fflags", "+genpts");
```

FYI, if the only thing you're trying to do can already be done with the `ffmpeg` command, just use that!

**Comment by SlawomirLeski** [comment]
Halo @saudet 
I tried to convert video after your advice but I am still not able to do it.

I found `public static final int AVFMT_FLAG_GENPTS = 1;` in `avformat.AVFormatContext`. I saw that in `org.bytedeco.javacv.FFmpegFrameGrabber` we have `private AVFormatContext oc;` but we can not recreate it with our flag. It is created here:

```
void startUnsafe() throws Exception {
       ...
        oc              = new AVFormatContext(null);
       ...
 }
```
I tried this method in `org.bytedeco.javacv.FFmpegFrameRecorder`

```
public void start(AVFormatContext ifmt_ctx) throws Exception {
		this.ifmt_ctx = ifmt_ctx;
		start();
	}
```

But this does not work. Do you have any advice how to create FFmpegFrameGrabber/FFmpegFrameRecorder with this AVFormatContext? Or any different way to do this convertion?

**Comment by saudet** [comment]
You'll have to modify FFmpegFrameGrabber, but if it didn't work with the options, it's probably not going to do anything different with the flag. We'll have to check in the source code of the ffmpeg program and see what it does exactly to replicate that in FFmpegFrameGrabber.

**Comment by saudet** [comment]
Don't try to overload it, just modify the file and rebuild.

**Comment by SlawomirLeski** [comment]
I modified and rebuild but still error occurred:

> [NULL @ 0x7f3af017be20] [IMGUTILS @ 0x7f3ae1d72cb0] Picture size 41340x33536 is invalid
> [ivf @ 0x7f3af017ada0] Failed to open codec in av_find_stream_info
> [vp8 @ 0x7f3af017be20] Upscaling is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
> [vp8 @ 0x7f3af017be20] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
> Input #0, ivf, from 'java.io.ByteArrayInputStream@102125ee':
>   Duration: 00:00:00.01, start: 0.000000, bitrate: N/A
>     Stream #0:0: Video: vp8 (VP80 / 0x30385056), yuv420p(tv, bt470bg/unknown/unknown), 576x1024, 48k tbr, 48k tbn, 48k tbc
> [mp4 @ 0x7f3af02b1e60] muxer does not support non seekable output
> Output #0, mp4, to '':
>   Metadata:
>     encoder         : Lavf57.56.100
>     Stream #0:0: Video: mpeg4 ( [0][0][0] / 0x0020), yuv420p, 576x1024, q=2-31, 400 kb/s, 48k tbn
> [vp8 @ 0x7f3af02ba1a0] Upscaling is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
> [vp8 @ 0x7f3af02ba1a0] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
> 

Any guide?

**Comment by saudet** [comment]
It looks like you're trying to open an mp4 file with an InputStream. Try to
use a File instead.

**Comment by SlawomirLeski** [comment]
Does not work even with File.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb696f8d58a, pid=12258, tid=0x00007fb5716ba700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x9f58a]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

**Comment by saudet** [comment]
What does you code look like?

**Comment by SlawomirLeski** [comment]
```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputFile);
grabber.start();
ByteArrayOutputStream out = new ByteArrayOutputStream();
FFmpegFrameRecorder2 recorder = new FFmpegFrameRecorder2(out, grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
recorder.setVideoCodecName("h264");
recorder.setAudioCodecName("aac");
recorder.setFormat("mp4");
recorder.setFrameRate(grabber.getFrameRate());
recorder.setOption("r", "23");
recorder.setSampleRate(grabber.getSampleRate());
recorder.start();
Frame frame;
while ((frame = grabber.grabFrame()) != null) {
	recorder.record(frame);
}
recorder.stop();
grabber.stop();
```

And Methos startUnsafe() is changed in FFmpegFrameGrabber:

```
void startUnsafe() throws Exception {
        int ret;
        img_convert_ctx = null;
        oc              = new AVFormatContext(AVFormatContext.AVFMT_FLAG_GENPTS);
       ...
      }
```

**Comment by saudet** [comment]
You need to set the `flags` of `AVFormatContext`.

**Comment by SlawomirLeski** [comment]
Where it should be set?

**Comment by saudet** [comment]
Probably just before this line:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L750

**Comment by SlawomirLeski** [comment]
I analyzed this code from the link, and I do know know how to set this flag. Should I use method `setOption(String key, String value)`? Or how?

**Comment by saudet** [comment]
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/javacpp/avformat.AVFormatContext.html#flags--

**Comment by SlawomirLeski** [comment]
If I understood you correct, I set flags like below:

```
void startUnsafe() throws Exception {
        int ret;
        img_convert_ctx = null;
        AVFormatContext oc = new AVFormatContext(AVFormatContext.AVFMT_FLAG_GENPTS);
        oc.flags(AVFormatContext.AVFMT_FLAG_GENPTS);
        this.oc = oc;
```

And output looks like below:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3608853b3d, pid=26652, tid=0x00007f360a2d8700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libavformat.so.57+0x1abb3d]  avformat_open_input+0x4dd

```

**Comment by saudet** [comment]
You'll need to use the `AVFormatContext` object allocated by FFmpeg.

**Comment by SlawomirLeski** [comment]
But you mean FFmpegFrameGrabber or FFmpegFrameRecorder or different object?

**Comment by saudet** [comment]
Try to call `oc.flags(AVFMT_FLAG_GENPTS)` just before `avformat_open_input()`.

**Comment by saudet** [comment]
BTW, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.

Please give it a try with 1.5-SNAPSHOT before the release: http://bytedeco.org/builds/
