### ISSUE TITLE
Opencv java:Images getting corrupted when grabber.grab is called soon after flush.

### ISSUE THREAD

**Issue by ijasnizamuddin** [bytedeco/javacv#1002]
I am getting corrupted images (attached) at times while using the below code to capture image.

grabber.flush();

Frame frame =grabber.grab();

What is default delay between storing  of two consecutive  frames into the numbuffers?

What is the use of trigger() method.?

**Comment by saudet** [comment]
That all depends on the driver of your camera.

OpenCV doesn't support triggering, so you can ignore that. It will just do
a flush.

**Comment by saudet** [comment]
I am not able to reproduce this issue here, so this is most likely a bug in the driver of your camera.

Please try upgrading your driver or use another camera.
