### ISSUE TITLE
File can't be opened for reading! in function cv::face::FaceRecognizer::read

### ISSUE THREAD

**Issue by devrishal** [bytedeco/javacv#1004]
I am trying to run the program, VideoFaceDetection.java but as per the comments and javadocs present in the file and the below piece of code,
`System.out.println("Two parameters are required to run this program, first parameter is the analized video and second parameter is the trained result for fisher faces.");`

I can understand that one parameter should be video file , but i am not able to get the meaning of second parameter as i passed a csv file of some images but still it is giving me the error.

`String videoFileName = "D://CodingPlayGround//Automated//resource//New folder//Test_faceDetection.mp4";
		String trainedResult = "D://CodingPlayGround//Automated//resource//joker1.csv";
		CascadeClassifier face_cascade = new CascadeClassifier(
				"D:\\thirdPartyApis\\opencv\\sources\\data\\haarcascades\\haarcascade_frontalface_default.xml");
		FaceRecognizer lbphFaceRecognizer = LBPHFaceRecognizer.create();
		lbphFaceRecognizer.read(trainedResult);
`

Error i am getting is below,
`OpenCV(3.4.1) Error: Unspecified error (File can't be opened for reading!) in cv::face::FaceRecognizer::read, file C:\projects\javacpp-presets\opencv\cppbuild\windows-x86\opencv_contrib-3.4.1\modules\face\src\facerec.cpp, line 61
Exception in thread "main" java.lang.RuntimeException: OpenCV(3.4.1) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86\opencv_contrib-3.4.1\modules\face\src\facerec.cpp:61: error: (-2) File can't be opened for reading! in function cv::face::FaceRecognizer::read

	at org.bytedeco.javacpp.opencv_face$FaceRecognizer.read(Native Method)
	at com.rishal.faceRecognition.VideoFaceDetection.main(VideoFaceDetection.java:43)
`

Please suggest what needs to be done here to run this programm.

**Comment by saudet** [comment]
This is all explained in the tutorial: https://docs.opencv.org/3.4.1/da/d60/tutorial_face_main.html
