### ISSUE TITLE
ADD JAVACV IN ADNROID STUDIO BY GRADLE

### ISSUE THREAD

**Issue by Tiny-Monster** [bytedeco/javacv#1005]
HI，I want to add javacv in android studio by gradle,but I encounter a error like bellow.

![1527513200](https://user-images.githubusercontent.com/32605031/40616040-fb33eca4-62bb-11e8-8dc1-d228956e1999.jpg)
Please give my help,Thanks!

**Comment by saudet** [comment]
Duplicate of #353

If you have any further questions, please post them there!
