### ISSUE TITLE
how can i build old version of javacv for ffmpeg  , which run with javaAV

### ISSUE THREAD

**Issue by zchacker** [bytedeco/javacv#1013]
i am using javaAV and it old library and not support for it now, but i need to build javacv + javacpp for it , the ffmpeg version is avcodec-55, can you tell me where to fined this version of javacv to build it in my own ?

**Comment by saudet** [comment]
JavaCV 0.8 with that file is available on the central repository:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.bytedeco%22%20AND%20a%3A%22javacv%22
