### ISSUE TITLE
How to add metadata to h264 stream?

### ISSUE THREAD

**Issue by tahaemara** [bytedeco/javacv#1016]
**Hello,**
I have a system for object detection using yolo, I receive the h264 stream from a camera and I want to make detection on every frame, such that I need to attach the metadata (box coordinations and class) to every frame and then stream it again to the client which can extract every frame with its metadata.
I tried to get a stream from mp4 file and then using  FFmpegFramerecorder to save the file with metadata something like next code block but it failed.
```
FFmpegFrameRecorder recorder = new
                FFmpegFrameRecorder("vid.mp4", 416, 416);
recorder.start();
recorder.setMetadata("box", "2,3");
recorder.setMetadata("class", "person");     
recorder.record(frame);
```
**My question:**
Can this thing be done? if yes, How?

Thanks in advance.

**Comment by tahaemara** [comment]
Thanks saudet,
Sorry for inconvenience, I have not a good experience in streaming, as I understand these metadata are global, not specific to each frame,  Is here any reference or suggestion to start with to do this requirement ?

**Comment by saudet** [comment]
You could use the MJPEG codec and save your metadata in each JPG image with EXIF. FFmpeg also supports streaming well with MJPEG as it's used by a lot of network cameras.

**Comment by saudet** [comment]
It looks like we would have to add support for this `exif_metadata` field here though:
http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=bb4e1b4cf910af0de2bc884c75544603c40010cc

**Comment by b005t3r** [comment]
@saudet has anything changed in the last years? I'm trying to add GPS location metadata to a mp4 file, but I don't see them in the output file. Is this because those tags (```location``` and ```location-eng```) are not supported? Is there any workaround for that?

**Comment by saudet** [comment]
FFmpeg will ignore any tag not supported by the format, yes. You'll need to use a format that does support them.
