### ISSUE TITLE
MD5 are not matching of VideoRecordThread() frame and FFmpegframeGrabber frames. 

### ISSUE THREAD

**Issue by jay-choudhary91** [bytedeco/javacv#1017]
In **VideoRecordThread()** i am implementing code like:- 
Frame filteredFrame = null;
                    try {
                    ByteBuffer buf=((ByteBuffer) recordedFrame.getFrame().image[0].position(0));
                        byte[] arr=buf.array();
                        String md=md5(arr);
                        frameFilter.push(recordedFrame.getFrame());
                        filteredFrame = frameFilter.pull();
                    } catch (FrameFilter.Exception e) {
                        e.printStackTrace();
                    }

In FFmpegFrameGrabber, implemention like:-

**FFmpegFrameGrabber** grabber = new FFmpegFrameGrabber(mVideo.getPath());
        try {
            grabber.start();
            int frame_count = grabber.getLengthInFrames();
            for(int i=0; i<frame_count; i++){
                Frame frame = grabber.grabImage();
                   ByteBuffer buf=((ByteBuffer) frame.image[0].position(0));
                        byte[] arr=buf.array();
                        String md=md5(arr);
              }
        }
        catch (Exception e) {
            e.printStackTrace();
        }

**Frame counts are fine. I have checked videoThread counter and ffmpeg grabber frame length. Issue is only md5 mismatch. Please help me.**

**Comment by saudet** [comment]
You'll want to use a lossless codec. You can try to use the "libx264rgb" codec with quality set to "0" like in this test for an example: https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameGrabberChangingResolutionTest.java#L50

**Comment by jay-choudhary91** [comment]
**Its not working after change codec and quality as suggested**. Please have a look below code.

private void initRecorder() {
        Log.i(LOG_TAG, "init mFrameRecorder");

        String recordedTime = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        mVideo = CameraHelper.getOutputMediaFile(recordedTime, CameraHelper.MEDIA_TYPE_VIDEO);
        Log.i(LOG_TAG, "Output Video: " + mVideo);

        mFrameRecorder = new FFmpegFrameRecorder(mVideo, videoWidth, videoHeight, 2);
        mFrameRecorder.setFormat("mp4");
        mFrameRecorder.setPixelFormat(AV_PIX_FMT_BGR24);
        mFrameRecorder.setVideoCodecName("libx264rgb");
        mFrameRecorder.setVideoQuality(0); // lossless
        mFrameRecorder.setFrameRate(30);

        Log.i(LOG_TAG, "mFrameRecorder initialize success");
    }

**Comment by saudet** [comment]
If your pixel format isn't BGR24, you'll need to try something else.
