### ISSUE TITLE
How to get two video in one window/jframe at the same time

### ISSUE THREAD

**Issue by 55juekun** [bytedeco/javacv#1019]
Hi, I'm a novice. I'd like to get two video in one window/jframe at the same time. But I don't know how to achieve it. I have tried to use multithreading, but it just open two windows and seems not beautiful at all. I have seen [https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/WebcamPanelExample.java](https://github.com/sarxos/webcam-capture/blob/master/webcam-capture/src/example/java/WebcamPanelExample.java). It could add two webcampanel in one jfame to get the result i want. But I also want to record the two vedio meanwhile. Could you help me ? Forgive my poor English.

**Comment by saudet** [comment]
We can do that with Java 2D, for example, follow the tutorial here:
https://docs.oracle.com/javase/tutorial/2d/images/drawimage.html

**Comment by 55juekun** [comment]
thank you! I Did it !
