### ISSUE TITLE
How to take frames in real-time in a RTSP streaming?

### ISSUE THREAD

**Issue by guijob** [bytedeco/javacv#1022]
Hi!

I'm trying to grab frames with no delays using javacv and I'm kind of confusing how to do it and how javacv and other stuff properly work under the hoods.

In my example, I have a RTSP streaming running with following configurations:

> Codec: H.264
> Frame Size: 1280x720
> **Maximum Frame Rate: 60 fps**
> Intra Frame Period: 1/4S
> Bit Rate Control: 40 Mbps

In order to make it happen, I've made a `thread` like following:

``` java
public class TakeFrameFromStreamingThread implements Runnable {
  private CircularFifoQueue<Frame> queue;
  private Camera camera;
  private FFmpegFrameGrabber grabber = null;

  public TakeFrameFromStreamingThread(CircularFifoQueue<Frame> queue, Camera camera) {
    try {
      this.queue = queue;
      this.camera = camera;
      this.initGrabber(camera);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  @Override
  public void run() {
    try {
      while (true) {
        if (grabber == null) {
          initGrabber(camera); // connect
	}

        Frame frame = null;
	frame = grabber.grabImage();

	if (frame != null) {
	  this.queue.add(frame);
	} else { // when frame == null then connection has been lost
	  initGrabber(camera); // reconnect
	}
      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private void initGrabber(Camera camera) throws Exception {
    grabber = new FFmpegFrameGrabber(camera.getURL()); // rtsp url
    grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);
    grabber.setOption("rtsp_transport", "tcp");
    grabber.setFrameRate(60);
    grabber.setImageWidth(camera.getResolution().getWidth());
    grabber.setImageHeight(camera.getResolution().getHeight());
    grabber.start();
  }
}
```

And it seems to work. Anytime I need a frame I `pool `this `queue` from my main `thread`.

I've ended up with this solution solving another issue. I was getting stuck why does calling `grabImage()` every time I need a frame has returned just next frame instead of a real-time frame from streaming. 

By this solution, I'm guessing there is a buffer which javacv (or ffmpeg idk) fills with frames and then `grabImage()` just get a frame from this buffer. So it's my first question:

1) Is that right? Does ffmpeg relies on a buffer to store frames and then `grab()` just get it from there?

Well, if that is a truth, then this buffer must be filled at some rate and, of course, if this rate is greater than my `grabImage()` calls rate, eventually I'll lose my real-time feature and soon I'll be even losing frames once buffer gets completely filled.

In this scenario, my `grabImage()` takes about **50 ms**, which gives me `20 fps`. Hence, I need to make sure ffmpeg is receiving frames at most 20fps. So here's my second question:

2) How to know and change ffmpeg buffer rate? I'm guessing it's getting filled at a same rate of streaming (60 fps) or from property `grabber.setFrameRate()`. At all, I'm not sure if I must use grabber `setters` with same values from source streaming.

Thanks.

**Comment by saudet** [comment]
Your question is about FFmpeg, so you'll probably need to ask the developers of FFmpeg to an answer.

**Comment by guijob** [comment]
Ok, I'll reformute my question in order to let it just a `javacv` question:

_How can I take frames directly from a streaming through FFMpegFrameGrabber?_


Look at consise code below:
```
while(true) {
    Frame frame = grabber.grabImage();
    Thread.sleep(2000);
}
```

Using this approach I'm actually just getting next frame instead of a frame 2s right after. What do you guys suggest for me to take frame 2s after previous one using javacv? Frames within interval I just don't need to.

Thanks

**Comment by saudet** [comment]
There is a flush() method for that. By default, it just grabs all frames and throws them away though...

**Comment by guijob** [comment]
This `flush()` method is somewhat instable taking arbitrary time to process because while it's throwing frames away, ffmpeg keeps creating new ones..

I solved this issue starting this way: https://groups.google.com/d/msg/javacv/T23Ebx_pdbI/KKTKAWeYAwAJ 

But, instead of a circular queue buffer, I'm using a wrapper with synchronized blocks. This circular queue buffer approach must use `Frame.clone()` method for each `FFmpegFrameGrabber.grab()` call, which costs in terms of performance and grab timing overall.

Using this approach worked like a charm!

This is my wrapper:
``` java
public class GrabberWrapper {
	private Java2DFrameConverter converter = new Java2DFrameConverter();
	private FFmpegFrameGrabber grabber;
	private Frame frame;

	public GrabberWrapper(FFmpegFrameGrabber grabber) {
		this.grabber = grabber;
	}

	public synchronized void grabImage() throws Exception {
		this.frame = this.grabber.grabFrame();
	}

	public synchronized BufferedImage getImage() {
		if (this.frame == null) {
			return null;
		}
		return deepCopy(converter.convert(this.frame));
	}
	
	private BufferedImage deepCopy(BufferedImage bi) {
		ColorModel cm = bi.getColorModel();
		boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
		WritableRaster raster = bi.copyData(null);
		return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
	}
}
```

So, a thread with `while(true)` block keeps grabbing n' releasing frames:
```  java
while (true) {
    wrapper.grabImage();
    Thread.sleep(1); // otherwise while(true) doesnt release wrapper lock
}
```

And in my main thread I get actual image by:
``` java
while(true) {
    BufferedImage buffImg = wrapper.getImage();
    Thread.sleep(2000);
}
```

I hope this helps someone. Thank you!

**Comment by saudet** [comment]
Yes, that looks good. Please consider making a sample out of that and send a pull request! Thanks

**Comment by carmuno** [comment]
If you need to capture the RTSP stream from your camera and save it to a specified directory, this small library might be just what you need:

https://github.com/carmuno/HouseSync.git
