### ISSUE TITLE
How to retrieve Mat element data as double[] arrays?

### ISSUE THREAD

**Issue by RobertYCXu** [bytedeco/javacv#1029]
OpenCV java (not JavaCV) provides the function `get(int row, int col)` on the Mat data type which returns a `double[]`. I was wondering how to do the same with a Mat in JavaCV. From the return types of using the `get` function of `DoubleIndexer` (which from my understanding is the only way to retrieve data from a Mat in JavaCV), there doesn't seem to exist `double[]` as a return type.

I need to do this because I am using `Video.calcOpticalFlowFarneback` in order to do dense optical flow on pre-recorded videos on android (thus I need ffmpeg). The function takes in a Mat of type CV_32FC2 and fills it with the flow data (which should be represented as arrays of size 2, first element for x offset and second for y offset). 

Any help with how to get this data (as double[], or another way) is much appreciated!

**Comment by saudet** [comment]
There are many ways to go about this, but since using `double[]` isn't going to be the most efficient way anyway, I guess the easiest way is to call `Mat.createBuffer().get(double[])` with a `double[]` initialized to the size of the buffer. Sounds good?
