### ISSUE TITLE
BOWKMeansTrainer not found

### ISSUE THREAD

**Issue by mongoose54** [bytedeco/javacv#103]
I am trying to use BOWKMeansTrainer like this:

CvTermCriteria termCriteria = cvTermCriteria(CV_TERMCRIT_ITER, 100, 0.001);

BOWKMeansTrainer bowKMeansTrainer = BOWKMeansTrainer(
				100, termCriteria, 1, 2);

Although on Eclispe BOWKMeansTrainer(clusterCount, termcrit, attempts, flags) is given as a suggesion when I type it in it gives me the following error:

"The constructor opencv_features2d.BOWKMeansTrainer(int, opencv_core.CvTermCriteria, int, int) is undefined"

Am I mistyping something here? I am confused.

**Comment by saudet** [comment]
According to the docs here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_features2d.BOWKMeansTrainer.html
We need to provide a `TermCriteria` object, _not_ `CvTermCriteria`. Let me know if you encounter any problems with `TermCriteria` though, thanks!
