### ISSUE TITLE
How do I load an opencv model in Android?

### ISSUE THREAD

**Issue by AgustinCB** [bytedeco/javacv#1031]
For example, in the project, I have haarcascade_frontalface_default.xml stored in the assets folder.

However, when I try to do:

```kotlin
val faceDetection =
            opencv_objdetect.CascadeClassifier("file://android_asset/haarcascade_frontalface_default.xml")
```

And then use that object, I get this error:

```kotlin
Caused by: java.lang.RuntimeException: OpenCV(3.4.1) /home/travis/build/javacpp-presets/opencv/cppbuild/android-x86/opencv-3.4.1/modules/objdetect/src/cascadedetect.cpp:1698: error: (-215) !empty() in function void cv::CascadeClassifier::detectMultiScale(cv::InputArray, std::vector<cv::Rect_<int> >&, double, int, int, cv::Size, cv::Size)
```

Which I'm pretty sure it means it wasn't able to load the xml.

The AssetsManager provides a way to get an InputStream, but the CascadeClassifier (and most other objects), seems to be always expecting a path.

How do I reconcile this? Should I save the asset to storage using the input stream and then pass that path to the CascadeClassifier? That seems rather nasty. Is there a better way?

Thanks for the support!

**Comment by saudet** [comment]
As far as I know, assets are not accessible as files, we have to extract them, but fortunately JavaCPP comes with a handy method for that, Loader.extractResource() as demonstrated in the Demo class of the README.md file:
https://github.com/bytedeco/javacv

**Comment by saudet** [comment]
Actually, assets are apparently accessible as files: 
https://developer.android.com/guide/topics/resources/providing-resources#OriginalFiles
If we provide the full path and it should work.
