### ISSUE TITLE
How to use AVPacket.side_data() / AVPacketSideData？bug？

### ISSUE THREAD

**Issue by lin557** [bytedeco/javacv#1032]
my app:  h264 raw to flv file.
I want to write sps/pps before every idr. see the ffmpeg source code if need set AVPacket.side_data.
java code:
```java
            AVPacket pkt = new AVPacket();
            avcodec.av_init_packet(pkt);
            pkt.flags(avcodec.AV_PKT_FLAG_KEY);
            pkt.pts(ts);
            pkt.dts(ts);
            
            // idr
            byte[] pkt_buf = msg.getIdr();  // 00 00 00 01 65 ...
            BytePointer pkt_data = new BytePointer(pkt_buf);
            pkt.data(pkt_data);
            pkt.size(pkt_buf.length);
            pkt.pos(-1);
            pkt.duration(0);
            pkt.stream_index(0);
            
            // new sps pps sei
            if (msg.hasExtradata()) {
                byte[] extradata = msg.getExtradata(); // 00 00 00 67
                BytePointer bp_extradata = new BytePointer(extradata);
                
                avcodec.AVPacketSideData side_data = new avcodec.AVPacketSideData();
                side_data.data(bp_extradata);
                side_data.type(avcodec.AV_PKT_DATA_NEW_EXTRADATA);
                side_data.size(extradata.length);
                
                pkt.side_data(side_data);
                pkt.side_data_elems(1);
            }
            
            // run to here, the app was dead
            av_interleaved_write_frame(oc, pkt));
```
I don't know how to set side_data in javacv? no side_data is run good.
please help!

**Comment by lin557** [comment]
I try to allocate memory, but the problem is still.
`avcodec.AVPacketSideData side_data = new avcodec.AVPacketSideData(extradata.length);`

in my delphi/pascal code. it run good. 
`   var  psd: TAVPacketSideData;
     if idr then
        begin
          psd.data := @FVTmpBuf[0];
          psd.size := 30;
          psd.type_ := AV_PKT_DATA_NEW_EXTRADATA;
          pkt.side_data := @psd;
          pkt.side_data_elems := 1;
          pkt.data := @FVTmpBuf[30];
          pkt.size := pkt.size - 30;
        end;
        ret := av_interleaved_write_frame(oc, @pkt);`
but in javacv is not good.

**Comment by saudet** [comment]
It might get prematurely deallocated. Try to keep a reference to the AVPacketSideData object in a field somewhere.

**Comment by saudet** [comment]
You could also try to use a `PointerScope` to make sure that doesn't happen:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/
I'm assuming this fixes your issue, but please let me know if you are still having problems! Thanks

**Comment by lin557** [comment]
@saudet 
I updated to version 1.4.2, but it still has the same problem. I don't know if it's a problem with my code or something else. I tried PointerScope but couldn't solve it.
thank you.

**Comment by saudet** [comment]
It doesn't look like your Delphi code is doing the same thing as your Java code. Since you say that your Delphi code works properly, how about trying the same thing in Java?

**Comment by lin557** [comment]
@saudet 
`BytePointer bp_extradata = new BytePointer(extradata);
                
                avcodec.AVPacketSideData side_data = new avcodec.AVPacketSideData();
                side_data.data(bp_extradata);
                side_data.type(avcodec.AV_PKT_DATA_NEW_EXTRADATA);
                side_data.size(extradata.length);
                
                pkt.side_data(side_data);
                pkt.side_data_elems(1);`
change to
`                BytePointer nsd = avcodec.av_packet_new_side_data(pkt, avcodec.AV_PKT_DATA_NEW_EXTRADATA, extradata.length);
                nsd.put(extradata, 0, extradata.length);`
it can work. thanks saudet.
