### ISSUE TITLE
Frame only has 2 channels when using avfoundation

### ISSUE THREAD

**Issue by kaedekai** [bytedeco/javacv#1033]
Hi, 

I am doing screen capture using format: "avfoundation" and device: "Capture Screen"
I notice that the frame are pretty blurry when display on a JFrame.

When I set the pixel format to YUV420P, the frame has no color (just gray)
When I set the pixel format to UYVY422, the frame only has 2 channels and Java2DFrameConverter will fail due to assertion failure.

Any idea how I can capture screen with the properly color?

**Comment by kaedekai** [comment]
Using the following version:
       <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>3.4.2-1.4.1</version>
            <classifier>macosx-x86_64</classifier>
        </dependency>

        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>3.4.2-1.4.1</version>
        </dependency>

**Comment by saudet** [comment]
You'll need to convert your frames to RGB, because Java2D doesn't support YUV. FFmpegFrameGrabber or OpenCVFrameGrabber will convert frames to RGB by default, so just use it as shown in the Demo class of the README.md file: https://github.com/bytedeco/javacv/

**Comment by kaedekai** [comment]
Added code that I use:

// grabber
       grabber = new FFmpegFrameGrabber("Capture screen 0");
       grabber.setFormat("avfoundation");
        grabber.setImageWidth(640);
        grabber.setImageHeight(480);
        grabber.start();

// recorder code
 FFmpegFrameRecorder recorder =
                new FFmpegFrameRecorder("/test/" + "video.mp4", grabber.getImageWidth(), grabber.getImageHeight());

        recorder.setFormat("mp4");
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
        recorder.setVideoOption("preset", "veryfast");
        recorder.setVideoOption("tune", "zerolatency");
        recorder.setVideoOption("intra-refresh", "1");
        recorder.start();

      // not sure if this is the right way to record all frame??
        Frame frame = grabber.grabImage();
        while(frame != null) {
            recorder.record(frame);
            frame = grabber.grabImage();
        }

**Comment by saudet** [comment]
OpenCVFrameConverter doesn't do any conversion of the pixel format. The
Frame you get already are in RGB format.
