### ISSUE TITLE
How can I make a Frame with H264 frame byte[]？

### ISSUE THREAD

**Issue by xwlcn** [bytedeco/javacv#1034]
How can I make a Frame with H264 frame byte[]？

**Comment by saudet** [comment]
Call `Frame.image[0].get(byte[])`.

**Comment by xwlcn** [comment]
@saudet Sorry, your answer can't solve my problem. My mean is how to convert real-time H264 byte[] to a Frame object. All I see, to get a Frame object is call grabber.grab() or grabber.grabFrame(), can't `new Frame(byte[])`?

**Comment by saudet** [comment]
To decode an H.264 stream, try to use FFmpegFrameGrabber.

**Comment by xwlcn** [comment]
@saudet Now I don't use a local file or a camera, but a H264 byte stream that is uploaded on the server - side real-time receiving device. How do I push these byte stream forwarding to the RTMP server? 
Here's the code of my rtpserver:
```
@Override
    protected void channelRead0(ChannelHandlerContext channelHandlerContext, RtpMessage rtpMessage) throws Exception {
        logger.debug(rtpMessage.toString());
        //h264 frame
        byte[] frame = rtpMessage.getBody();
    }
```
How do I convert the byte array of the H264 frames received above to org.bytedeco.javacv.Frame?

**Comment by saudet** [comment]
We can use a `ByteArrayInputStream` to wrap data from a `byte[]`.

**Comment by saudet** [comment]
`PipedInputStream` with `PipedOutputStream` also works, you'll need to call `write()`.

**Comment by xwlcn** [comment]
@saudet No, it doesn't seem to work，like the follow code:
```
PipedInputStream pis = new PipedInputStream();
PipedOutputStream pos = new PipedOutputStream();
pis.connect(pos);
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(pis);
//blocked ?
grabber.start();
```
When called `grabber.start();`, the application blocked because of the PipedInputStream have no data. 
If FFmpegFrameGrabber is built in InputStream, when `start()` is called, it is first to read all of the data in the InputStream, and can not write new byte data by piped stream.

**Comment by saudet** [comment]
Yeah, you need to call `pos.write()` to unblock.

**Comment by xwlcn** [comment]
@saudet Yes, but after that can I write new data to  PipedOutputStream and `Frame frame = grabber.grabImage();` can get the new data?

**Comment by saudet** [comment]
That's correct, then you can call `grabber.grabImage()` to the first image.

**Comment by xwlcn** [comment]
@saudet Thx, I'll try it.

**Comment by silentsugar** [comment]
> @saudet No, it doesn't seem to work，like the follow code:
> 
> ```
> PipedInputStream pis = new PipedInputStream();
> PipedOutputStream pos = new PipedOutputStream();
> pis.connect(pos);
> FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(pis);
> //blocked ?
> grabber.start();
> ```
> 
> When called `grabber.start();`, the application blocked because of the PipedInputStream have no data.
> If FFmpegFrameGrabber is built in InputStream, when `start()` is called, it is first to read all of the data in the InputStream, and can not write new byte data by piped stream.
> What I want to do is using `PipedOutputStream` to write real-time h264 byte[] when grabber called grabImage(). Just like this:
> 
> ```
> PipedInputStream pis = new PipedInputStream();
> PipedOutputStream pos = new PipedOutputStream();
> pis.connect(pos);
>         
> FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(pis);
>         
> grabber.start();    //blocked ?
> 
> FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("rtmp://127.0.0.1/live/test", 1920,1080,0);
> recorder.setInterleaved(true);
> recorder.setVideoOption("crf","28");
> recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); // 28
> recorder.setFormat("flv"); 
> recorder.setFrameRate(25);
> recorder.setPixelFormat(0); // yuv420p
> System.out.println("recorder start");
> recorder.start();
>         
> new Thread() {
>       @Override
>        public void run() {
>            //write real time data
>             pos.write(realTimeData);
>             }
>         }.start();
>         
> while (true) {
>        Frame frame = grabber.grabImage();
>        recorder.record(frame);
>        System.out.println(System.currentTimeMillis());
> }
> ```

Me too，grabber.start() block. How to fix?
