### ISSUE TITLE
Problem with descriptorMatcher

### ISSUE THREAD

**Issue by Relo4ded** [bytedeco/javacv#1036]
Hello,
I'm currently trying to do some feature detection on the nvidea shield, with javacv. I load the library like this, before that I imported all the libs from the javacv and imported module:
static {
        ///System.loadLibrary("native-lib");
        if(!OpenCVLoader.initDebug()){
            Log.i(TAG,"Could not load OpenCV stuff library ");
        }
    }
when I try to create a DescriptorMatcher like this:
(1)detector = FeatureDetector.create(FeatureDetector.ORB);
(2)descriptor = DescriptorExtractor.create(DescriptorExtractor.ORB);
(3)matcher = DescriptorMatcher.create(DescriptorMatcher.BRUTEFORCE_HAMMING);

the code stops running in (3). The output I get is :
Debugger attached to process 20107
Signal: SIGABRT (signal SIGABRT)
Signal: SIGSEGV (signal SIGSEGV: address access protected (fault address: 0x20040aee90))

It´s weird because the code of (1) and (2) look exactly the same as in (3) but I can't debug it cause its native. Any idea how to fix this problem so I can create a featureDescriptor and go on with my work?

**Comment by saudet** [comment]
You should not use OpenCVLoader, could you try to comment that out?

**Comment by saudet** [comment]
I'm assuming that this solved your issue, but please let me know if this isn't the case.
