### ISSUE TITLE
Mat deserialized from FileStorage - NullPointerException Pointer address of argument 1 is NULL

### ISSUE THREAD

**Issue by molina-henrique** [bytedeco/javacv#1037]
Hello folks 
I updated for 1.4.2 and the issue #1012 is working fine.
So  afterwards to READ, I got something wrong:

I copied the sample based on: [https://github.com/bytedeco/javacv/blob/72d9fd9d55e86a32942afb5edd983cd4bb3647bc/samples/OpenCVFeatures2dSerialization.java](https://github.com/bytedeco/javacv/blob/72d9fd9d55e86a32942afb5edd983cd4bb3647bc/samples/OpenCVFeatures2dSerialization.java)

on method *deserialize*  The descriptors created an Mat (imgDescriptors) not working very well.
The point of exception on method **_detect_**: 
 KeyPointVector imageKeypoints= new KeyPointVector();
 AZAKE.detect(**imgDescriptors**, imageKeypoints);

 **Ocurred this Exception**:

>  java.lang.NullPointerException: Pointer address of argument 1 is NULL.
> 	at org.bytedeco.javacpp.opencv_features2d$Feature2D.detect(Native Method)

**File Xml created** : 
```
<?xml version="1.0" encoding="UTF-8"?>
<opencv_storage>
<descriptors type_id="opencv-matrix">
  <rows>11</rows>
  <cols>61</cols>
  <dt>u</dt>
  <data>
    224 237 3 0 0 145 56 ..... </data></descriptors>
</opencv_storage>
```
Would be about `<dt>u</dt>` ? 

Thks !

**Comment by molina-henrique** [comment]
Sorry @Saudet, I fixed the first error create new Object Mat on method **deserializeFile**
 doing it i'm **recover the Mat** Object .

But now the errors changes in the same point:
```
java.lang.RuntimeException: OpenCV(3.4.2) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.4.2\modules\features2d\src\akaze.cpp:172: error: (-215:Assertion failed) ! image.empty() in function 'cv::AKAZE_Impl::detectAndCompute'
at org.bytedeco.javacpp.opencv_features2d$Feature2D.detectAndCompute(Native Method)
```
Look my piece of code  and Attachs the serialize.xml  and images

```
/** Deserialize image only descriptors */
Mat deserializeFile(String file) {
	Mat objectDescriptorsDeserialize= new Mat();
	try (
		 FileStorage fileStorage = new FileStorage(file, FileStorage.READ, StandardCharsets.UTF_8.name());
			FileNode descriptorsFileNode = fileStorage.get("descriptors")
	){
		read(descriptorsFileNode, objectDescriptorsDeserialize);
		fileStorage.release();
	}
	return new Mat(objectDescriptorsDeserialize.rows(), objectDescriptorsDeserialize.cols(), 
					org.bytedeco.javacpp.opencv_core.CV_8UC1, 
					new BytePointer(objectDescriptorsDeserialize.asByteBuffer()));
}
```
```
Mat mat= loadImage(....); // grayScale
String dir= "/Temp/";
String serializeXml= dir+"serialize.xml";
serializeFile(mat, serializeXml); // ITS OK - I take out the  line write(fileStorage, keypoints" 
Mat matDeserialize = deserializeFile(serializeXml); //ITS OK 
KeyPointVector imageKeypoints= new KeyPointVector(); 
Mat imageDescriptors = new Mat(); 

/* point of Exception */
AKAZE.create().detectAndCompute(imageMat, new Mat(), imageKeypoints, imageDescriptors); 

```
[serialize-xml-tests.zip](https://github.com/bytedeco/javacv/files/2236131/serialize-xml-tests.zip)




If you are seeing something wrong in advance, please let me know 
Cheers

**Comment by saudet** [comment]
That just means that we need to pass non-empty images.
