### ISSUE TITLE
why do I  always grab the same picture from a video?

### ISSUE THREAD

**Issue by paulyzheng1** [bytedeco/javacv#1039]
Hi guys, it is still the same thing (I always grab the same picture from a video) after I delete setFrameNumber.

Did I miss import files(*.so,  jar files, ..)? Do I need to use a player to play this video before  I call this function: faceRecongnition_util2?

On android device, I also import 1.4.1 ffmepg.jar  and some relative  ffmepg *.so files.

```java
...
public static final void faceRecongnition_util2(String videoname, String resultname, int algorithm) throws Exception{
    Log.i(TAG, "called faceRecongnition_util2..."+videoname + ":"+resultname);	
    int captureWidth = 1280;
    int captureHeight = 1080;
    int count = 0;
    @SuppressWarnings("resource")
	FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(videoname);
    grabber.setFormat("mp4");
    
 	grabber.setImageWidth(captureWidth);
 	grabber.setImageHeight(captureHeight);
    try {
        AndroidFrameConverter convertToBitmap = new AndroidFrameConverter();
        grabber.start();

        int frame_count = grabber.getLengthInFrames(); 
        
        Log.i(TAG, "getLengthInFrames= " + frame_count );	// frame_count =667
        Log.i(TAG, "getFrameRate= " + grabber.getFrameRate() );	  //30~31    
        
        for (int i=0; i<frame_count; i+=grabber.getFrameRate()) {

            String fileName = GRAB_PICTURE + "Grab_"+ "qq" + "_" + count + ".jpg";
            count ++;            
            //if (i > 0) grabber.setFrameNumber(i);
            Frame frame = grabber.grabImage();         	            
            Bitmap bitmap = convertToBitmap.convert(frame);
            Log.i(TAG, "called faceRecongnition_util2 fileName= " + fileName);	            
            Log.i(TAG, "called faceRecongnition_util2 frame= " + frame);	 
            Log.i(TAG, "called faceRecongnition_util2 bitmap= " + bitmap);	 
            File picfile = new File(fileName);
            if (!picfile.exists()) {
                try {
                    picfile.createNewFile();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            try {

                FileOutputStream out = new FileOutputStream(picfile);
                bitmap.compress(Bitmap.CompressFormat.JPEG, 100, out);
                out.flush();
                out.close();

            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {

            }
        }
      ....
    } finally {

    }
}
```
Could someone help me find out the root cause? Thanks a lot in advance!

~Paul

**Comment by saudet** [comment]
Please try again with 1.4.2.

**Comment by paulyzheng1** [comment]
Today, I update to 1.4.2 (ffmpeg.jar,  javacpp.jar,  javacv.jar,  *.so)  on  17/7/2018, and then merge  3.4.1  opencv sdk *.class files  with 1.4.2 opencv.jar *.class files to make a new jar. I found this problem:
=============================================
01-18 09:34:56.171  1846  1846 I System.out: Loading library avutil
01-18 09:34:56.176  1846  1846 I System.out: Loading library jniavutil
01-18 09:34:56.177  1846  1846 W linker  : /data/app/com.project.facedr-1/lib/arm/libjniavutil.so: unused DT entry: type 0xf arg 0x1c95f
01-18 09:34:56.179  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
01-18 09:34:56.179  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
01-18 09:34:56.179  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
01-18 09:34:56.179  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
01-18 09:34:56.179  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
01-18 09:34:56.179  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
01-18 09:34:56.180  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesConstraints
01-18 09:34:56.180  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.180  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.180  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.180  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.180  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.181  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.181  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.181  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.181  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.181  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.181  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.181  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.182  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.182  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext
01-18 09:34:56.182  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesContext$Free_AVHWFramesContext
01-18 09:34:56.182  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWFramesInternal
01-18 09:34:56.183  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
01-18 09:34:56.183  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
01-18 09:34:56.184  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
01-18 09:34:56.184  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
01-18 09:34:56.184  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
01-18 09:34:56.184  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
01-18 09:34:56.184  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext
01-18 09:34:56.185  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceContext$Free_AVHWDeviceContext
01-18 09:34:56.185  1846  1846 W System.err: Warning: Loader.putMemberOffset(): java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil$AVHWDeviceInternal
01-18 09:34:56.191  1846  1846 E art     : No implementation found for int 

**org.bytedeco.javacpp.avutil.AV_OPT_TYPE_IMAGE_SIZE() (tried Java_org_bytedeco_javacpp_avutil_AV_1OPT_1TYPE_1IMAGE_1SIZE and Java_org_bytedeco_javacpp_avutil_AV_1OPT_1TYPE_1IMAGE_1SIZE__)**

01-18 09:34:56.195  1846  1846 I System.out: Loading class org.bytedeco.javacpp.avutil
01-18 09:34:56.195  1846  1846 I art     : Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
01-18 09:34:56.195  1846  1846 D AndroidRuntime: Shutting down VM
01-18 09:34:56.196  1846  1846 E AndroidRuntime: FATAL EXCEPTION: main
01-18 09:34:56.196  1846  1846 E AndroidRuntime: Process: com.project.facedr, PID: 1846
01-18 09:34:56.196  1846  1846 E AndroidRuntime: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
01-18 09:34:56.196  1846  1846 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
01-18 09:34:56.196  1846  1846 E AndroidRuntime:        at java.lang.Class.forName(Class.java:324)
01-18 09:34:56.196  1846  1846 E AndroidRuntime:        at org.bytedeco.javacpp.Loader.load(Loader.java:940)
01-18 09:34:56.196  1846  1846 E AndroidRuntime:        at org.bytedeco.javacpp.Loader.load(Loader.java:881)
01-18 09:34:56.196  1846  1846 E AndroidRuntime:        at org.bytedeco.javacpp.avformat$Read_packet_Pointer_BytePointer_int.<clinit>(avformat.java:632)
01-18 09:34:56.196  1846  1846 E AndroidRuntime:        at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:296)
.....

**Comment by saudet** [comment]
It won't work with OpenCV 3.4.1, you need OpenCV 3.4.2.

**Comment by paulyzheng1** [comment]
Yes , thanks a lot. I have noticed this , but I can not download OpenCV 3.4.2 sdk for android yesterday. Last night, I finally successfully download it. I will verify it ASAP.

**Comment by saudet** [comment]
You shouldn't use those builds, use the builds that come with JavaCV.

**Comment by paulyzheng1** [comment]
@saudet , thanks a lot. I will make my project only to depend on JavaCV/JavaCPP/FFMepg libraries ASAP. (You know , at first , I use OpenCV to do some study, and nowdays, I still need some  extra functions of OpenCV lib in my project. )
After I update to 3.4.2, it still no work. @saudet , I have a question,  who trigger this video move further when we "open" and start to grab from this video?

**Comment by saudet** [comment]
JavaCV also comes with the official Java API of OpenCV, so you can keep using both together.

Calling `grab()` will move to the next frame. Maybe your video file is corrupted. Does it happen only with one of your files, or all your files?

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming this was a problem with your data, but let me know if this isn't the case! Thanks
