### ISSUE TITLE
Question about android and RTMP

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#104]
Hey. I am looking around for a RTMP library to stream of an Android device and posted a question [on StackOverflow](http://stackoverflow.com/questions/29018606/android-stream-camera-as-rtmp-stream). Your library was suggested and it indeed does look really promising. Can you verify that what [this guy](http://stackoverflow.com/a/29061628/1360853) says can be done?

If it cannot be done, but is just a small step for this library I am willing to help creating it and contribute to the library. 

Cheers!

**Comment by saudet** [comment]
Yes, we can do that. As indicated by the guy and as you found that, try to use a URL with the [`RecordActivity` sample](https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java).
