### ISSUE TITLE
How to use library, classes from "javacv and java-cpp"

### ISSUE THREAD

**Issue by BigFish90** [bytedeco/javacv#1040]
Hello sir,
I'm new in java, so i get problems when i try to import library. It tells me that the file doesn't exist.
May you explain please?
![import issue](https://user-images.githubusercontent.com/40393250/43260837-3b49ae32-90e3-11e8-9af1-66a55e9793a3.jpg)

**Comment by saudet** [comment]
You'll need a more recent version, try 1.4.2.

**Comment by BigFish90** [comment]
Thank you very much Saudet, it works! :)
