### ISSUE TITLE
Unable to create an audio+video file with H264 codec

### ISSUE THREAD

**Issue by avanibhatnagar** [bytedeco/javacv#1043]
I am able to create a video file with H264 codec, but when I add audio to it using this method and then try setting the codec to H264, it just creates an empty file, and keeps on running. 

The vidPath below has a H264 codec video. The audioPath is an aac audio file.
This is my method to add audio to a video:

        FrameGrabber grabber1 = new FFmpegFrameGrabber(vidPath);
        FrameGrabber grabber2 = new FFmpegFrameGrabber(audioPath);
        grabber1.start();
        grabber2.start();
        FrameRecorder recorder = new FFmpegFrameRecorder(outputPath,
                grabber1.getImageWidth(), grabber1.getImageHeight(),
                grabber2.getAudioChannels());
        recorder.setFormat("mp4");
        recorder.setVideoQuality(10);
        recorder.setFrameRate(grabber1.getFrameRate());
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);

        recorder.start();
        while ((frame1 = grabber1.grabFrame()) != null ||
                ((frame2 = grabber2.grabFrame()) != null)) {
            recorder.record(frame1);
            recorder.record(frame2);
        }
        recorder.stop();
        grabber1.stop();
        grabber2.stop();
    }

This above method works without adding this:         recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
and creates a MPEG4 video with audio added to it perfectly. Runs infinitely and creates empty file when codec set to H264 only.

Is there any way I can write a method that converts a MPEG4 codec file (video+audio) to H264 codec or VP8 or VORBIS?

**Comment by saudet** [comment]
This works fine here with JavaCV 1.4.2 on Linux, what is your platform?

Could you also try to call `setVideoOption("threads", "1")`?

**Comment by avanibhatnagar** [comment]
When I call setVideoOption("threads","1"), I get this:
at line 102, i.e.         recorder.record(frame2);

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved video frame.
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:791)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:678)
	at com.VidController.addMP3toMovie(IAmVideoController.java:102)
	at com.creatics.web.IAmVideoController.main(IAmVideoController.java:54)
	... 5 more
Output #0, mp4, to 'C:\Users\Avani Bhatnagar\Documents\ffmpeg trial\ffmpeg java class\VideoRate.mp4':
    Stream #0:0: Video: h264 (libx264), yuv420p, 640x720, q=-1--1, 9 kb/s, 0.34 tbn, 0.34 tbc
[libx264 @ 000000001c42cec0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 000000001c42cec0] profile High 4:4:4 Predictive, level 3.1, 4:2:0 8-bit
[libx264 @ 000000001c42cec0] 264 - core 146 r2538 121396c - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=0 mixed_ref=1 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=0 chroma_qp_offset=0 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=250 keyint_min=1 scenecut=40 intra_refresh=0 rc=cqp mbtree=0 qp=0
[libx264 @ 000000001c42cec0] frame I:4     Avg QP: 0.00  size:183602
[libx264 @ 000000001c42cec0] mb I  I16..4: 51.7%  0.0% 48.3%
[libx264 @ 000000001c42cec0] 8x8 transform intra:0.0%
[libx264 @ 000000001c42cec0] coded y,uvDC,uvAC intra: 95.2% 94.2% 94.0%
[libx264 @ 000000001c42cec0] i16 v,h,dc,p: 53% 46%  1%  0%
[libx264 @ 000000001c42cec0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 40% 39%  2%  3%  4%  3%  4%  3%  2%
[libx264 @ 000000001c42cec0] i8c dc,h,v,p:  6% 50% 45%  0%
[libx264 @ 000000001c42cec0] kb/s:499.40
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Avani Bhatnagar\Documents\ffmpeg trial\ffmpeg java class\output trial\A\VideoRate.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf56.37.100
  Duration: 00:00:11.77, start: 0.000000, bitrate: 183 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 640x720 [SAR 1:1 DAR 8:9], 182 kb/s, 0.34 fps, 0.34 tbr, 17408 tbn, 17 tbc (default)
    Metadata:
      handler_name    : VideoHandler
[aac @ 000000001f695d60] Estimating duration from bitrate, this may be inaccurate
Input #0, aac, from 'C:\Users\Avani Bhatnagar\Documents\ffmpeg trial\ffmpeg java class\Downtown_20SecondVersion_Final.aac':
  Duration: 00:00:19.93, bitrate: 128 kb/s
    Stream #0:0: Audio: aac (LC), 44100 Hz, stereo, fltp, 128 kb/s
Output #0, mp4, to 'C:\Users\Avani Bhatnagar\Documents\ffmpeg trial\ffmpeg java class\output trial\A\Movie\Movie.mp4':
    Stream #0:0: Video: h264 (libx264), yuv420p, 640x720, q=-1--1, 400 kb/s, 0.34 tbn, 0.34 tbc
    Stream #0:1: Audio: aac (libvo_aacenc), 44100 Hz, stereo, s16, 64 kb/s
[libx264 @ 000000001c488be0] -qscale is ignored, -crf is recommended.
[libx264 @ 000000001c488be0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
[libx264 @ 000000001c488be0] profile High, level 3.1
[libx264 @ 000000001c488be0] 264 - core 146 r2538 121396c - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=1 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=10.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[mp4 @ 000000001c459a40] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 102400 >= 0

**Comment by saudet** [comment]
That's caused by passing multiple `null` frames to `record()`. Use `&&` instead of `||` in your loop:
```java
        while ((frame1 = grabber1.grabFrame()) != null &&
                ((frame2 = grabber2.grabFrame()) != null)) {
```

**Comment by avanibhatnagar** [comment]
Ok so changing it to && creates a video but the audio played for less than a second right when I play it and then it stops...

**Comment by saudet** [comment]
You'll need to record all the audio frames to get all of the audio :) They are not equal in time to video frames.

**Comment by avanibhatnagar** [comment]
I see. Thanks a lot! I'm new to FFMPEG. Would setting frame rate help? Is there a sample code I can look at?

**Comment by avanibhatnagar** [comment]
Is there a way I can just convert a MPEG codec movie(audio(aac)+video) to a H264?
Something like this?

File file = new File(filePath); //this file would have the final Codec H265 movie

        FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(outputPath); //this would be the MPEG 4 codec movie
        frameGrabber.start();
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(file,640,720);
        recorder.setFormat("mp4");
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setFrameRate(frameGrabber.getFrameRate());
        //recorder.setSampleFormat(frameGrabber.getSampleFormat());
        recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
        recorder.setVideoQuality(10); 
        recorder.start();
        recorder.stop();

**Comment by avanibhatnagar** [comment]
Any ideas @saudet ?

**Comment by saudet** [comment]
The idea with JavaCV is to process frames, so a loop like this should work:
```java
    while ((frame1 = grabber1.grabFrame()) != null ||
            ((frame2 = grabber2.grabFrame()) != null)) {
        if (frame1 != null) recorder.record(frame1);
        if (frame2 != null) recorder.record(frame2);
    }
```
But if you're only interested in converting video files from one format to the other, I would recommend using the `ffmpeg` command line tool.

**Comment by avanibhatnagar** [comment]
I am doing this over the server, so I will be unable to use FFMPEG command line. I used JAVACV, to convert images to a video using FFMPEG frame recorder and then add audio to it. The video is H264 codec but when I pass it to my method to add audio to it as shown in my method above, it does so perfectly and creates a .mp4 with MPEG 4 codec, but when I use the same to set to H264 codec so that it can be displayed on all browsers, I get avcodec_encode_video2() error -542398533: Could not encode video packet.

**Comment by avanibhatnagar** [comment]
I think it is just like issue #745  https://github.com/bytedeco/javacv/issues/745

**Comment by saudet** [comment]
Calling recorder.record(null) might help, but that's already done on
stop()...

**Comment by saudet** [comment]
In any case, please provide some data to reproduce this, and I'll look into it! Thanks

**Comment by Orcunkazan** [comment]
> I was able to pass a file with the MPEG4 codec and convert it to H264 finally!!
> The only problem now is a few frames in the end get cut, any suggestions?

Did you really do that? Is it possible that a video would use the H264 codec for the audio stream?
