### ISSUE TITLE
 /home/travis/build/javacpp-presets/opencv/cppbuild/linux-x86_64/opencv-3.4.2/modules/videostab/src/frame_source.cpp:71: error: (0:No Error) can't open file:

### ISSUE THREAD

**Issue by glide-the** [bytedeco/javacv#1044]
linux is ok.....\/....\/............
这个是我的打卡方式不对吗，
this here windows No problem
thanks you

**Comment by saudet** [comment]
Could you provide a code snippet to reproduce this issue?

**Comment by glide-the** [comment]
yes

**Comment by glide-the** [comment]
public class VideoUtils {

    /**
     * 获取指定视频的帧并保存为图片至指定目录
     *
     * @param videofile 源视频文件路径
     * @param targetFile 截取帧的图片存放路径
     * @throws Exception
     */
    public static void fetchFrame(File videofile, File targetFile)
            throws Exception {
        long start = System.currentTimeMillis();
        FrameGrabber ff = new FFmpegFrameGrabber(videofile);
        ff.start();
        int lenght = ff.getLengthInFrames();
        int i = 0;
        Frame f = null;
        while (i < lenght) {
            // 过滤前5帧，避免出现全黑的图片，依自己情况而定
            f = ff.grabFrame();
            if ((i > Math.floor(lenght/2)) && (f.image != null)) {
                break;
            }
            i++;
        }
        BufferedImage bufferedImage = FrameToBufferedImage(f);
        ImageIO.write(bufferedImage, "jpg", targetFile);
        //ff.flush();
        ff.stop();
//        System.out.println(System.currentTimeMillis() - start);
    }

    public static float getVideoFileLength(String fileName) {
        File file = new File(fileName);
        if (!file.exists()) {
            return 0;
        }
        float len = 0;
        opencv_videostab.VideoFileSource videoFileSource = new opencv_videostab.VideoFileSource(fileName);
        double fps = videoFileSource.fps();
        int count = videoFileSource.count();
        len = (float) ((float) count / fps);

        return len;
    }

    /**
     * 把Frame转换BufferedImage
     * @param frame
     * @return
     */
    public static BufferedImage FrameToBufferedImage(Frame frame) {
        //创建BufferedImage对象
        Java2DFrameConverter converter = new Java2DFrameConverter();
        BufferedImage bufferedImage = converter.getBufferedImage(frame);
        return bufferedImage;
    }

}

**Comment by glide-the** [comment]
/**
     * 获取指定视频的帧并保存为图片至指定目录
     *
     * @param videofile 源视频文件路径
     * @param targetFile 截取帧的图片存放路径
     * @throws Exception
     */
    public static void fetchFrame(File videofile, File targetFile)
            throws Exception {
        long start = System.currentTimeMillis();
        FrameGrabber ff = new FFmpegFrameGrabber(videofile);
        ff.start();
        int lenght = ff.getLengthInFrames();
        int i = 0;
        Frame f = null;
        while (i < lenght) {
            //
            f = ff.grabFrame();
            if ((i > Math.floor(lenght/2)) && (f.image != null)) {
                break;
            }
            i++;
        }
        BufferedImage bufferedImage = FrameToBufferedImage(f);
        ImageIO.write(bufferedImage, "jpg", targetFile);
        //ff.flush();
        ff.stop();
//        System.out.println(System.currentTimeMillis() - start);
    }
 /**
     * 把Frame转换BufferedImage
     * @param frame
     * @return
     */
    public static BufferedImage FrameToBufferedImage(Frame frame) {
        //创建BufferedImage对象
        Java2DFrameConverter converter = new Java2DFrameConverter();
        BufferedImage bufferedImage = converter.getBufferedImage(frame);
        return bufferedImage;
    }

**Comment by glide-the** [comment]
linux version
[root@localhost tmp]# uname -a
Linux localhost.localdomain 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by glide-the** [comment]
I just have this problem on Linux, I just got into this tool recently, so the others won't work. Do you have any documentation?

**Comment by saudet** [comment]
There is the API docs, but it could use some work:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FFmpegFrameGrabber.html
But there are samples around like this one:
https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java
Let me know if there is anything unclear.

**Comment by glide-the** [comment]
Thank you very much

**Comment by COBSNAN** [comment]
你好 兄台，怎么解决的 我也遇到相应问题了 我看你关闭问题了
