### ISSUE TITLE
How to convert byte[] we get from android preview call back to Mat.

### ISSUE THREAD

**Issue by sivadatta-igt** [bytedeco/javacv#1045]
I've been trying to implement [this example](https://github.com/bytedeco/javacv/blob/master/samples/DeepLearningFaceDetection.java) in an android app. I've created a camera preview class and tried to send the byte[] I got from onPreviewFrame in to the facedetector class I modified so that a Mat object takes in the byte array and do processing on it.
```java
public void processFrame(byte[] frame){
   Mat colorimg = new Mat(frames);
}
```
But when it is given to the detectanddraw() method from the sample it gives out an error saying the mat object is null and I get this error.

> E/cv::error(): OpenCV(3.4.2) Error: Assertion failed (!ssize.empty()) in void cv::resize(cv::InputArray, cv::OutputArray, cv::Size, double, double, int), file /home/travis/build/javacpp-presets/opencv/cppbuild/android-x86/opencv-3.4.2/modules/imgproc/src/resize.cpp, line 4044

I found out that Mat object is being created without any size. So I need a way to convert the byte array I receive byte array to Mat with size equal to the image size.
I've tried the below code as well but still the same error.
```java
colorimg = new Mat(width,height, CvType.CV_8UC3);
colorimg.data().put(frames);
```
But I got this error: 

> java.lang.NullPointerException: Attempt to invoke virtual method 'org.bytedeco.javacpp.BytePointer org.bytedeco.javacpp.BytePointer.put(byte[])' on a null object reference

**Comment by saudet** [comment]
What are the values of "width" and "height"?

**Comment by saudet** [comment]
Right, so can you log them or something and check their values?

**Comment by saudet** [comment]
Also, what does your build file look like?

**Comment by sivadatta-igt** [comment]
> Right, so can you log them or something and check their values?

Yes and I also tried to pass them to the Mat() object to create a Mat object with those sizes as I said in the initial comment.

>Also, what does your build file look like?
```build
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.facerecognition.example.facerecognitionandroid"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0-alpha1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation files('libs/ffmpeg.jar')
}
```
The JARS I've imported to the libs directory:

- ffmpeg

- ffmpeg-android-arm

- ffmpeg-android-arm64

- ffmpeg-android-x86
- ffmpeg-android-x86_64
- javacpp
- javacv
- javacv-platform
- opencv
- opencv-android-arm
- opencv-android-arm64
- opencv-android-x86
- opencv-android-x86_64

**Comment by saudet** [comment]
What are the versions of these dependencies? And are you using any other
dependencies?

**Comment by saudet** [comment]
Ok, can you reproduce the issue on the desktop? Or does it happen only on
Android?

**Comment by sivadatta-igt** [comment]
Only in android. I even made a standalone GUI program using that example and works fine as the mat object takes input directly from the VideoCapture class. So I tried to use it in android by giving the input to Mat object from preview call back method.

**Comment by saudet** [comment]
I mean, could you try to create a Mat using the same arguments and then
call Mat.data() and see what that gives on the desktop?

**Comment by sivadatta-igt** [comment]
No I haven't. I'll try it and post the results.

**Comment by sivadatta-igt** [comment]
So I've tried it on desktop. [Code for it](https://github.com/sivadatta-igt/TestingMat/blob/master/MatTestClass.java) and got the same error.
So I did a imwrite and saw that the Mat object formed was a image with height of 1. is there any work around?

**Comment by saudet** [comment]
`imageMat = new Mat(data);` -> that will give you a row vector, unless we also specify the height and width.

**Comment by sivadatta-igt** [comment]
I tried with width and height.
```java
int width = bImage.getWidth();
int height = bImage.getHeight();
```
And created the mat as follows:
```java
imageMat = new Mat(new Size(width,height), CvType.CV_8UC4);
imageMat.data().put(data);
imwrite("output.png",imageMat);
```
But I got [this](https://github.com/sivadatta-igt/TestingMat/blob/master/output.png) as output.
Am I creating the Mat object wrong? 
[Link to the code](https://github.com/sivadatta-igt/TestingMat/blob/master/MatTestClass.java)

**Comment by saudet** [comment]
Yes, you'll need to use `imdecode()` for JPEG data.

**Comment by sivadatta-igt** [comment]
I tried creating with width and height as [here](https://github.com/sivadatta-igt/TestingMat/blob/master/MatTestClass.java).

and I got the output as [here](https://github.com/sivadatta-igt/TestingMat/blob/master/output.png).

Am I creating the Mat object wrong?

**Comment by sivadatta-igt** [comment]
Ok the Mat Object is getting created properly but I am still getting the null pointer exception at 
```java
net.setInput(blob);
```
[Code](https://github.com/sivadatta-igt/TestingMat/blob/master/MatTestClass.java)

**Comment by saudet** [comment]
"blob" is not an image, we need to call `blobFromImage(image, ...)` on the image to get one.

**Comment by saudet** [comment]
> ```java
>  private static opencv_dnn.Net net = null;
> ```
You'll also need to assign something else than `null` to the `net` variable.

**Comment by saudet** [comment]
You'll need to initialize it with a line like this:
> ```java  
> net = readNetFromCaffe(PROTO_FILE, CAFFE_MODEL_FILE);
> ```
https://github.com/bytedeco/javacv/blob/master/samples/DeepLearningFaceDetection.java#L47

**Comment by sivadatta-igt** [comment]
Thank you. It's working now( on desktop). Mistake on my part. Now I have to try it in android.
