### ISSUE TITLE
How to use mat to represent the collection of points?

### ISSUE THREAD

**Issue by MaruHyl** [bytedeco/javacv#1046]
void convexHull( 
    @ByVal Mat points, 
    @ByVal Mat hull,
    @Cast("bool") boolean clockwise/*=false*/, 
    @Cast("bool") boolean returnPoints/*=true*/ );

**Comment by saudet** [comment]
If you have your points in a Points array, just call new Mat(Points).

**Comment by saudet** [comment]
You could also use an indexer to add them manually in a loop:
http://bytedeco.org/news/2014/12/23/third-release/
