### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#105]
Hey @saudet, I noticed you are quite active around here so I figured i'd ask you.

I put ran the example of ``https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java`` and it shows great. I can see the preview etc. However, once I press the "start" button it crashes.

I get the following exception: ``java.lang.ExceptionInInitializerError`` caused by ``Couldn't load jniopencv_core: findLibrary returned null`` 

Do you have any idea what caused this? In my gradle I put ``compile 'org.bytedeco:javacv:0.10'``

**Comment by lfdversluis** [comment]
Looks like it's similar to this issue: http://stackoverflow.com/questions/10857301/unable-to-link-native-library-in-opencv-android-sample. I also tried including ``compile 'org.bytedeco.javacpp-presets:opencv:2.4.10-0.10'`` but no luck

**Comment by saudet** [comment]
As pointed out in the README file, we might need to add the "android-arm" and/or "android-x86" artifacts manually. Do you still have that issue even after adding those JAR files?

**Comment by lfdversluis** [comment]
Hi I included both ``ffmpeg`` and ``opencv`` arm and x86 jars and the error is gone. I do get a lot of errors such as ``Could not find class 'java.awt.image.BufferedImage', referenced from method org.bytedeco.javacpp.helper.opencv_core$AbstractArray.getBufferedImage``, but I read these are harmless? 

On my old device whenever I press the start button, the activity immediately closes without an error... is this because it might not be ARMv7?

**Comment by lfdversluis** [comment]
Alright it does work on my tablet which is ARMv7. It doesn't on my older device which is ARMv6.

One question about the code. What does the ``RECORD_LENGTH`` variable do? What happens if I set it to 0?

**Comment by saudet** [comment]
If you increase log verbosity and see a `SIGILL` in there, that means you don't have an ARMv7 processor, yes.

Setting `RECORD_LENGTH` to 0 will just disable the continuous recording loop and record everything until the user presses stop, that's all.

**Comment by saudet** [comment]
As for the warning messages concerning the `java.awt` package, I'm doing a bit of refactoring and it won't try to load these classes on Android anymore, among things. But yes, for now, they are harmless.
