### ISSUE TITLE
How to set video codec h264_nvenc for FFmpegFrameRecorder?

### ISSUE THREAD

**Issue by Allenisme** [bytedeco/javacv#1052]
Error message: org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.

**Comment by saudet** [comment]
Try to call `FFmpegFrameRecorder.setVideoCodecName("h264_nvenc")`.

**Comment by Allenisme** [comment]
Thanks for replying! But that's what I did, and the error message is "avcodec_open2() error -22: Could not open video codec". Here's my code: 
                FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("D:/test.flv", 1280, 720, 0);
                recorder.setVideoCodecName("h264_nvenc");
                recorder.setFormat("flv");
                recorder.setFrameRate(25);
                recorder.setGopSize(50);
                recorder.setVideoOption("crf", "28");
                recorder.setVideoOption("tune", "zerolatency");
                recorder.setVideoOption("preset", "ultrafast");
                recorder.start();

**Comment by saudet** [comment]
Remove these options, most of those are not supported by h264_nvenc. You can see the error messages in FFmpeg's log.
