### ISSUE TITLE
Weird Color Recorded From Webcam Using FFmpegFrameRecorder

### ISSUE THREAD

**Issue by ZeyuanXue** [bytedeco/javacv#1053]
The program used webcam-capture API and javacv at the same time. I used webcam-caputure API to grab images(which is normal since I checked the saved bufferred image) and use Java2DFrameConverter to convert the BufferredImage to Frame. Everything works perfectly but the color of the recorded video is weird.
![2018-08-30_18-42-44 1_normal](https://user-images.githubusercontent.com/35473169/44883332-af35cf80-ac84-11e8-92e9-33b740f2f833.png)
![vlcsnap-2018-08-30-18h43m17s372](https://user-images.githubusercontent.com/35473169/44883379-dbe9e700-ac84-11e8-9717-741a44c67deb.png)

**Comment by saudet** [comment]
It looks like your webcam doesn't output the channels in the typical BGR order. We can work around that by setting the `flipChannels` parameter to `true`:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/Java2DFrameConverter.html#getBufferedImage-org.bytedeco.javacv.Frame-double-boolean-java.awt.color.ColorSpace-
Or with other functions like `cvtColor(..., CV_RGB2BGR)` from OpenCV.
