### ISSUE TITLE
BUG keylistener

### ISSUE THREAD

**Issue by makeiteasyforme** [bytedeco/javacv#1054]
i implements  keylistener in my class where i declare and initialize canvasframe, framegrabber and other class for accessing webcam, i use enter key to save the image it works fine until i click the frame using mouse pointer then after that when i pressed the enter key my keylistener didn't work, isn't it because of that threading they call or idk, i tried canvasFrame.setFocusable(true). tell me what should i do or what i did wrong.

**Comment by saudet** [comment]
Swing doesn't work well in that case, try to use CanvasFrame.waitKey()
instead.

**Comment by makeiteasyforme** [comment]
ow ok wer can i get source code?

**Comment by saudet** [comment]
It's here:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/CanvasFrame.java#L280

**Comment by saudet** [comment]
If you're looking for sample code, there is some here, for example:
https://github.com/bytedeco/javacv/blob/master/samples/Square.java#L286
