### ISSUE TITLE
Can't turn off Camera

### ISSUE THREAD

**Issue by fpt-mnes-linhtc1** [bytedeco/javacv#1057]
I use OpenCVFrameGrabber to start camera capture. But when i call methods stop() and release() of OpenCVFrameGrabber class , Camera isn't stop, the camera's light is still bright. Please help me fix this issue. Thanks.

**Comment by saudet** [comment]
Try to use FFmpegFrameGrabber or VideoInputFrameGrabber instead, they
usually work better than OpenCV.

**Comment by saudet** [comment]
If you're on Windows, try as mentioned in issue https://github.com/bytedeco/javacv/issues/947#issuecomment-376810190, for Linux, there's issue https://github.com/bytedeco/javacv/issues/154#issuecomment-104954981 for that, and for Mac, something like `new FFmpegFrameGrabber("Integrated").setFormat("avfoundation")` should work: https://trac.ffmpeg.org/wiki/Capture/Webcam#OSX
