### ISSUE TITLE
Sound and video encrytion 

### ISSUE THREAD

**Issue by ayadiWael** [bytedeco/javacv#106]
BSR,
1)j'ai un erreur "Trying to remove 1024 samples, but the queue is empty"
j'ai pas compris ce problème (code ci dessous)
2) je suis débutant et j'essai de effectuer un xor d'une séquence binaire avec le son  d'un vidéo (samples), Pouvez m'indiquer comment peut-on effectuer ça 
  
 FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth,
				imageHeight, 1);
        recorder.setFormat("mp4");
        recorder.setSampleRate(sampleAudioRateInHz);
		//recorder.setVideoBitrate(videoBitrate);
		recorder.setAudioBitrate(audioBitrate);
		
		recorder.setFrameRate(frameRate);

		recorder.setInterleaved(false);
		recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
		recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
		recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
 try {
                                       IplImage im=cvLoadImage("C:\\Users\\Public\\Pictures\\Sample Pictures\\test4.jpg");
                                       
                                       Mat im1 = new Mat(im,true);
					FrameGrabber grabber = new FFmpegFrameGrabber("C:\\Users\\Public\\Videos\\Sample Videos\\Wildlife.wmv");
					grabber.start();
					recorder.start();
					Frame frame1;
                                        IplImage img;
                                        Mat im2;
                                        Mat im3=new Mat(im1);
					while ((frame1 = grabber.grabFrame())!= null) {
                                            
                                           img=frame1.image;
                                           im2 = new Mat(img,true); 
                                           
                                            if(img!= null)break;
                                              bitwise_xor(im1,im2,im3);
                                              
						recorder.record(im3.asIplImage());
                                               
					
                                        }
					recorder.stop();
					grabber.stop();

					
				} catch (FFmpegFrameRecorder.Exception e) {
					e.printStackTrace();
				} catch (Exception e) {
					e.printStackTrace();
				}
			
			}

**Comment by saudet** [comment]
Since you're not recording any audio samples, please leave the number of `audioChannels` to 0. Do *not* set it to 1.

**Comment by ayadiWael** [comment]
Thx :) 
Pour le son quelle structure de données peut contenir le son s'il vous plais ?

**Comment by saudet** [comment]
Ah, désolé, vous tentez d'enregistrer le son. J'ai mal compris la question. Les données du son se trouvent dans `Frame.samples` et c'est ça qu'il faudrait traiter et enregistrer.

**Comment by ayadiWael** [comment]
Merci, est ce qu'il est possible de mettre ce son dans un tableau ou "ArrayList" ??

**Comment by saudet** [comment]
Avec l'API de java.nio.Buffer, bien sur!
