### ISSUE TITLE
org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_parse_ptr() error -22

### ISSUE THREAD

**Issue by xtsh** [bytedeco/javacv#1070]
filter = new FFmpegFrameFilter(
			"drawtext=fontfile=simhei.ttf:fontcolor=red:x=10:y=10:fontsize=30:text='123'", null,
			grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
		filter.setPixelFormat(grabber.getPixelFormat());
		filter.setSampleFormat(grabber.getSampleFormat());
		filter.start();

The following exception occurs when I try to add a watermark to video using the drawtext filter

org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_parse_ptr() error -22
	at org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe(FFmpegFrameFilter.java:340)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:255)
	at com.laowang.main.AVConvert.convert(AVConvert.java:61)
	at com.laowang.main.AVConvert.main(AVConvert.java:196)

**Comment by saudet** [comment]
Please install JavaCV 1.4.3 and let me know the error messages on the
console. Thanks!

**Comment by xtsh** [comment]
I tried to put the required font file in the project root directory, and the problem was solved.Thanks!

**Comment by srajca** [comment]
Hello, I am having troubles adding a text. Here is my code
`FFmpegFrameFilter subtitleFilter = new FFmpegFrameFilter("drawtext=\"fontfile=Arial:text='Test - awesome test':reload=1\"", frameGrabber.getImageWidth(), frameGrabber.getImageHeight());
        subtitleFilter.start();`

and here is my error
`org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_parse_ptr() error -22
	at org.bytedeco.javacv.FFmpegFrameFilter.startVideoUnsafe(FFmpegFrameFilter.java:341)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:256)`

**Comment by saudet** [comment]
@srajca Could you also please provide the error message in the log on the console?

**Comment by srajca** [comment]
I fixed the error, I was missing the fontfile. However I do not see any drawtext on the video. 
Here is my code again
`FFmpegFrameFilter subtitleFilter = new FFmpegFrameFilter("drawtext=fontfile='C\\:/Windows/Fonts/Arial.ttf':text=Test and another test:reload=1:x=(w-text_w)/2:y=(h-text_h)/2", frameGrabber.getImageWidth(), frameGrabber.getImageHeight());
        subtitleFilter.setPixelFormat(frameGrabber.getPixelFormat());
        subtitleFilter.setSampleFormat(frameGrabber.getSampleFormat());
        subtitleFilter.start();`

**Comment by saudet** [comment]
@srajca What does FFmpeg output to the console?

**Comment by srajca** [comment]
Hmm. I see nothing. Where do I look, before I saw it in output by Netbeans

**Comment by saudet** [comment]
Try to call FFmpegLogCallback.set().

**Comment by srajca** [comment]
This is what I get

`
Error: [h264 @ 000000002d60d040] co located POCs unavailable

Error: [h264 @ 000000002d60d040] co located POCs unavailable

[0x7FFCCB9216A0] ANOMALY: meaningless REX prefix used
[0x7FFCC88737B0] ANOMALY: meaningless REX prefix used
[0x7FFCC8873F20] ANOMALY: meaningless REX prefix used
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\user\Desktop\test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2016-10-04T14:19:32.000000Z
  Duration: 00:17:01.24, start: 0.000000, bitrate: 1259 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1129 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2016-10-04T14:19:32.000000Z
      handler_name    : ISO Media file produced by Google Inc.
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2016-10-04T14:19:32.000000Z
      handler_name    : ISO Media file produced by Google Inc.
[libx264 @ 000000002d686700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 000000002d686700] profile Constrained Baseline, level 3.2
[libx264 @ 000000002d686700] 264 - core 155 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=1 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=8 lookahead_threads=8 sliced_threads=1 slices=8 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=86 keyint_min=44 scenecut=0 intra_refresh=0 rc=abr mbtree=0 bitrate=6500 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Output #0, flv, to 'rtmp://a.rtmp.youtube.com/live2/0000-0000-0000-0000':
  Metadata:
    encoder         : Lavf58.12.100
    Stream #0:0: Video: h264 (Constrained Baseline) ([7][0][0][0] / 0x0007), yuv420p, 1280x720, q=2-31, 6500 kb/s, 1k tbn
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, fltp, 96 kb/s`

**Comment by saudet** [comment]
It doesn't look like any filter is getting executed. Try with another filter to make sure the graph is actually getting executed.

**Comment by srajca** [comment]
I cannot figure how to execute the filter. If I change anything I get an error in Log, but if it is "fixed" nothing changes. If I call this 
`System.out.println("FILTER IS " + subtitleFilter.getFilters());`
 I get the following - 
`FILTER IS drawtext=fontfile='C\:/Windows/Fonts/Arial.ttf':text='Test and another test':x='(w-text_w)/2':y='(h-text_h)/2'`
