### ISSUE TITLE
FFmpegFrameGrabber is slower than ffmpeg

### ISSUE THREAD

**Issue by RobertoUa** [bytedeco/javacv#1072]
in ffmpeg I can use `ffmpeg -ss 300 -i {url} -t 2 -vf fps=fps=24 frames/img_%d.jpg` to extract 2 seconds worth of frames (48 jpg files) from URL starting from 5th minute (seek is really fast in ffmpeg it doesn't matter how big is the video and how large is -ss param, it's always fast).

I can do the same with `FFmpegFrameGrabber` using `setTimestamp` and `grabFrame`.
But `setTimestamp` is really slow (1 sec) (also grabFrame is just 3 ms) (tried with `checkFrames` both `false` and `true`)
I'm able to extact 5 seconds of video (120 frames) in 6 seconds using ffmpeg but it would take 120 seconds for FFmpegFrameGrabber to do the same.

Looks like the problem is somewhere here https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L649-L664

**Comment by saudet** [comment]
@anotherche Would you have any insights?

**Comment by anotherche** [comment]
Is Is possible to reproduce it using local file?

**Comment by saudet** [comment]
No, I think the issue is calling grab() a few times instead of just once, but then the seek isn't accurate...

**Comment by RobertoUa** [comment]
are you saying that calling `grabFrame` will increment timestamp and the next call to `grabFrame` will grab next frame? :) And I need to call `setTimestamp` only once?

so if I want to grab the same frame twice I need to cache it myself?

**Comment by anotherche** [comment]
Exactly!

**Comment by RobertoUa** [comment]
interesting
what if I want to grab every other frame or similar? For instance, I have 30 fps (or any other value) input but I want to extract 24 frames as if the input was 24?

**Comment by saudet** [comment]
That would be frame rate conversion. We can do that with the "fps" filter: https://ffmpeg.org/ffmpeg-filters.html#fps-1
And that should work with FFmpegFrameFilter:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java
