### ISSUE TITLE
h264 bitrate

### ISSUE THREAD

**Issue by Tatsukyo** [bytedeco/javacv#1076]
Hi,

I'm currently trying to make a video from a JFrame.

It works but the quality is poor.
To increase quality, i'm trying to up bitrate, but look like even if u set bit_rate, the codec ignore it and still encode it near 200Kb/s

any idea? why does the bitrate does not change?

**Comment by saudet** [comment]
Try to use the lossless "libx264_rgb" with these 2 lines:
>```java
>             recorder.setVideoCodecName("libx264rgb");
>             recorder.setVideoQuality(0); // lossless
>```
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameGrabberTest.java#L57-L58
