### ISSUE TITLE
Something is fighting between reading frames and Kotlin Sequences - only last image

### ISSUE THREAD

**Issue by salamanders** [bytedeco/javacv#1079]
I **thought** I'd be all cool making a Kotlin sequence from the frames of a video.  But the last image seems to clobber everything.  This is very odd - maybe with how Sequences are evaluated in a lazy fashion, fighting with how internal memory is handled by Frames?  Clearly I'm missing something, I thought that the immediate convert to BufferedImage would side-step any issues.

This example snippet will write the 500th frame out to both first.png and last.png - which is bad.

```kotlin
fun main() {
    val converter: FrameConverter<BufferedImage> = Java2DFrameConverter()
    val grabber = FFmpegFrameGrabber("https://github.com/mediaelement/mediaelement-files/blob/master/big_buck_bunny.mp4?raw=true")
    grabber.start()
    println("Opened video: ${grabber.imageWidth} x ${grabber.imageHeight} ${grabber.pixelFormat}")

    val frames = sequence<BufferedImage> {
        while (true) {
            yield(converter.convert(grabber.grabImage() ?: break))
        }
        grabber.stop()
    }.constrainOnce()

    val first500 = frames.take(500).toList()
    ImageIO.write(first500.first(), "png", File("first.png"))
    ImageIO.write(first500.last(), "png", File("last.png"))
}
```

**Comment by saudet** [comment]
You'll need to clone the BufferedImage, you're just keeping references to the same object here.

**Comment by salamanders** [comment]
But you said in https://github.com/bytedeco/javacv/issues/1077 that immediately converting to BufferedImage kept this from being an issue?

**Comment by saudet** [comment]
It copies the data out of the native buffer, so FFmpeg can reuse it without problem, but the converter reuses the BufferedImage on each call. It wouldn't be efficient otherwise, unless we add some external mechanism, which isn't present right now.

**Comment by salamanders** [comment]
Makes sense, going with deepCopy, thank you!
