### ISSUE TITLE
Issues in video convert time

### ISSUE THREAD

**Issue by vah13** [bytedeco/javacv#108]
Hi dear support. 
Thank you for JavaCV :-)

I have some question. I can record video and save it, but how can convert it - mp4 to webm?
Thank you.

**Comment by ShihabSoft** [comment]
Just try to use.
JavaCV FFmpegFrameRecorder dude.

**Comment by saudet** [comment]
To support the WebM format, we would need to build FFmpeg with the `libvpx` library. Someone would need to update the `cppbuild.sh` file accordingly...

**Comment by saudet** [comment]
Marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/33

**Comment by saudet** [comment]
FYI, support for WebM has been included in version 1.0. Enjoy!
