### ISSUE TITLE
Unable to stop the stream: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by thereye** [bytedeco/javacv#1087]
Unable to stop the stream: Inappropriate ioctl for device. 

error occurs when:
```
VideoCapture videoCapture = new VideoCapture(path);
int nCount = (int)videoCapture.get(CAP_PROP_FRAME_COUNT);
```
What's the problem?  In mac osx is running well, but in ubuntu goes wrong.

**Comment by saudet** [comment]
Try to use FFmpegFrameGrabber instead.

**Comment by saudet** [comment]
This happens because OpenCV isn't currently being linked to FFmpeg. There is little reason to go through OpenCV for this since FFmpegFrameGrabber, FFmpegFrameRecorder, and FFmpegFrameFilter offer greater functionality with less bugs anyway.

In particular, your code would look like this this:
```java
FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(path);
int nCount = frameGrabber.getLengthInFrames();
```
