### ISSUE TITLE
IPCamera MJPEG Stream to Video

### ISSUE THREAD

**Issue by kadircanerergun** [bytedeco/javacv#1088]
I use an ip camera to record video from android phone . This camera gives 40 byte[] data for each second. I try to use FFMPEGFrameRecorder but after saving MP4 video i see only green screen as shown below. I try to get ipcamera image from web browser and could get 640x480 image. Whats wrong for me. What should i check? 
dependencies:  
  ```
compile group: 'org.bytedeco', name: 'javacv', version: '1.4.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv-platform', version: '3.4.3-1.4.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg-platform', version: '4.0.2-1.4.3'
```

<img width="644" alt="screen shot 2018-11-10 at 03 22 30" src="https://user-images.githubusercontent.com/3830772/48294857-1dbeb700-e498-11e8-8f23-16773b5f68f4.png">

**Comment by saudet** [comment]
Try to use FFmpegFrameGrabber to grab images from your camera.

**Comment by kadircanerergun** [comment]
There is already one thread that taking images from camera and preview in imageview. That i try to use this taken byte[].

**Comment by kadircanerergun** [comment]
> It sounds like those are JPEG images, try to save them to files.

Thank you for interest @saudet. Can you explain it ? When i saave all them to jpeg files i think it will cause to performance problem. Is there any way to add bitmaps to mp4

**Comment by saudet** [comment]
Not really not, you'll need to decode the JPEG images before reencoding them into an mp4 file.

**Comment by kadircanerergun** [comment]
> Not really no, you'll need to decode the JPEG images before reencoding them into an mp4 file.

Please can you explain it a bit.  Thats the code that i take the imaage from camera 
`byte[] data = iCameraGetFrame();
						if (data != null) {
							oneFrameData = data;
						}

						if (data == null || data.length <= 0) {
							try {
								Thread.sleep(5);
							} catch (InterruptedException e) {
								// TODO Auto-generated catch block
								e.printStackTrace();
							}
							continue;
						}
						Bitmap bmp = BitmapFactory.decodeByteArray(data, 0, data.length);
`

bmt is the image that i set it to ImageView while recording

**Comment by saudet** [comment]
Ok, then call `FFmpegFrameRecorder.record(AndroidFrameConverter.convert(bmp))` and that should work.

**Comment by kadircanerergun** [comment]
> Ok, then call `FFmpegFrameRecorder.record(AndroidFrameConverter.convert(bmp))` and that should work.

Thanks for help. But sometimes it works properly, sometimes crashes with 
` Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 1066 (Thread-12)`

**Comment by saudet** [comment]
That looks like a null pointer somewhere in your code.

**Comment by kadircanerergun** [comment]
But there is no more crash description. How can i find it?

**Comment by kadircanerergun** [comment]
> https://developer.android.com/studio/debug/

I tried to debug aapplicaation but couldn catch  :((
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 16866`

**Comment by saudet** [comment]
Please post your code here if you can. It might be something simple that I can point out right away.

**Comment by kadircanerergun** [comment]
> Please post your code here if you can. It might be something simple that I can point out right away.

Thank you @saudet you're great person...


This is the thread that takes image from camera stream 

`captureThread = new Thread(new Runnable() {

		@Override
		public void run() {
			// TODO Auto-generated method stub

			isStop = false;
			iCameraServerStart();

			while (!isStop) {
				byte[] data = iCameraGetFrame();
				if (data != null) {
					oneFrameData = data;
				}

				if (data == null || data.length <= 0) {
					try {
						Thread.sleep(5);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					continue;
				}
				Bitmap bmp = BitmapFactory.decodeByteArray(data, 0, data.length);

				if (bmp != null) {
			
					Bundle bundle = new Bundle();
					bundle.putByteArray("imageArray", data);;
					Message message = new Message();
					message.what = 1413;
					message.setData(bundle);
					handler.sendMessage(message);
					if (recording) {
						setRecordData(bmp);
					}
				}
			}
			isStop = true;
			iCameraServerStop();
		}
	});
	captureThread.start();
`

When i click start record 
`public void startRecord() {
	initRecorder();
    try {
        recorder.start();
        startTime = System.currentTimeMillis();
        recording = true;

    } catch (FFmpegFrameRecorder.Exception e) {
        e.printStackTrace();
    }
	handler.sendEmptyMessage(HandlerParams.RECORD_START);
}`

on each loop it reacords with 
`private void setRecordData(Bitmap bmp) {
	if (bmp != null && recording) {
        try {
            long t = 1000 * (System.currentTimeMillis() - startTime);
            if (t > recorder.getTimestamp()) {
                recorder.setTimestamp(t);
            }
            org.bytedeco.javacv.AndroidFrameConverter converter2 = new AndroidFrameConverter();
            Frame frames = converter2.convert(bmp);
			recorder.record(frames);
        } catch (FFmpegFrameRecorder.Exception e) {
            Log.v(LOG_TAG, e.getMessage());
            e.printStackTrace();
        }
	}
}`

When i click stop 

`public void stopRecording() {
	recording = false;
	try {
		recorder.stop();
		recorder.release();
	} catch (FrameRecorder.Exception e) {
		e.printStackTrace();
	}
}`

Thanks for your help!

**Comment by saudet** [comment]
Thanks! Looks alright. So, let's see, what is the format of the Bitmap? What does `bmp.getConfig()` return?

**Comment by 1goresha** [comment]
> Not really no, you'll need to decode the JPEG images before reencoding them into an mp4 file.

is it possible to do this without reencoding, i mean to save jpegs bytes with timestamp?
i know that it will cause huge size of file, but anyway....

**Comment by saudet** [comment]
> > Not really no, you'll need to decode the JPEG images before reencoding them into an mp4 file.
> 
> is it possible to do this without reencoding, i mean to save jpegs bytes with timestamp into an avi, mkv, mp4 ......? i know that it will cause huge size of file, but anyway....

Sure, that's what the grabPacket()/recordPacket() methods are for

**Comment by 1goresha** [comment]
i tried to do like this:

private val recorder: FFmpegFrameRecorder
var startTime: Long = 0

private fun configureRecorder() {
        recorder.format = "avi" // Change the format if needed
        recorder.frameRate = 25.0 // Adjust the frame rate as needed
        recorder.gopSize = 25
        recorder.videoQuality = 1.0
        recorder.isInterleaved = true
        recorder.videoBitrate = width * height * 5 // Adjust the bitrate as needed
        recorder.timestamp = 1000 * (System.currentTimeMillis() - startTime)
        FFmpegLogCallback.set()
        recorder.start()
}

fun muxJpegFrameUsingPacket(jpegBytes: ByteBuffer) {
        try {
            val packet = avcodec.av_packet_alloc()
            avcodec.av_init_packet(packet)

            // Ensure the buffer is ready for reading
            jpegBytes.flip()

            packet.data(BytePointer(jpegBytes))
            packet.size(jpegBytes.remaining())
            val t = 1000 * (System.currentTimeMillis() - startTime)
            if (t > recorder.getTimestamp()) {
                recorder.setTimestamp(t)
            }

            recorder.recordPacket(packet)
            avcodec.av_packet_unref(packet)
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
    
    
    and i got this:
    org.bytedeco.javacv.FFmpegFrameRecorder$Exception: No input format context (Has start(AVFormatContext) been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)
    at org.bytedeco.javacv.FFmpegFrameRecorder.recordPacket(FFmpegFrameRecorder.java:1397)

**Comment by saudet** [comment]
It currently only works with FFmpegFrameGrabber, but contributions are
welcome!

**Comment by 1goresha** [comment]
Can i use FFmpegFrameGrabber for recording JPEG bytes with timestamps into an avi file, if i have callback for receiving MJPEG bytes?

Can you give me an example how, please

**Comment by saudet** [comment]
We can use FFmpegFrameGrabber to read JPEG files, yes.
