### ISSUE TITLE
Null value in DoublePointer after calling cvMinMaxLoc

### ISSUE THREAD

**Issue by Redwinxk** [bytedeco/javacv#1093]
Hi, I apologize if this isn't the correct place to ask this, or if I'm just doing something wrong (likely) but I'm struggling with this issue and thought I'd come to the source.

I'm using javacv 1.4.3, dependency added via maven.

I'm using _cvMatchTemplate_ to search for a template subimage in a larger source image, then passing the resulting _IplImage_ to _cvMinMaxLoc_ to get back the coordinates of the matched area. This works perfectly (and surprisingly quickly) as far as getting the coordinates out, but I also need the actual threshold values, since the images will not always be found, and the location values will return a maximaly matched point even if the match is very low and the subimage was not really on the screen.

I'm fine with that functionality as long as I can set a threshold value to exclude false positives, but I cannot seem to get the min or max threshold back out of the DoublePointer objects I'm creating and passing into _cvMinMaxLoc_.

In the code below, the MaxLoc coordinates come back with the locations set correctly, but max_val.get(0) always says the pointer is null (as does max_val.get() which seems to just default to 0 as well).  Am I just not understanding how to access the value?

```
                DoublePointer min_val = new DoublePointer();
	        DoublePointer max_val = new DoublePointer();
	        CvPoint minLoc = new CvPoint();
	        CvPoint maxLoc = new CvPoint();

	        cvMinMaxLoc(result, min_val, max_val, minLoc, maxLoc, null);

	        System.out.println(maxLoc.x());
	        System.out.println(maxLoc.y());
	        System.out.println(max_val.get(0));
```

I can check the value manually by using _cvGet2D_() on the result image and passing it the maxLoc coordinates  myself, and that seems like a viable workaround, but I don't understand why I can't get the values out of the DoublePointer objects directly.

**Comment by saudet** [comment]
The default constructor doesn't allocate memory (maybe it should?), call `new DoublePointer(1)` instead.

**Comment by Redwinxk** [comment]
Works perfectly, I knew I had to be doing something silly. 

Thank you so much for your (super fast) assistance!
