### ISSUE TITLE
Custom IO and RT(S)P Protocol

### ISSUE THREAD

**Issue by Tatsukyo** [bytedeco/javacv#1095]
Hi @saudet,

With your great work i could do a lot of thing but there is still something i don't get it ...

I know i could decode video using just "avformat_open_input" but for some reasons, i'm decoding using a custom I/O since i receive the video as bytes (often 128).

That works pretty fine but i wish to replay video from an RTSP stream. There again i could just use "avformat_open_input" but i wish to use only 1 way... the custom I/O.

Could you explain me how to do. look like it hang at avformat_open_input (Invalid data input when processing) but if i set the format (h264) it's fine but it hang at avformat_find_stream_info()

I'm pretty sure i'm missing something but i don't know what could u enlighten me

Thanks u in advance for ur great works :)

**Comment by saudet** [comment]
Ok, what happens? What do you get in FFmpeg's log?

**Comment by Tatsukyo** [comment]
On some file i got Couldn't find stream info, on other it take some times before he find stream then the codeccontext have no height no width no frame rate ... 

Moreover avcodec_decode_video return something like -108 000 000

Maybe my pcap file are not perfect ... anyway still working around.

Was wondering if i must set some options since if i don't set format it hang at open .

**Comment by saudet** [comment]
It sounds like the format you're trying to use doesn't support streaming very well, try another format like Matroska (mkv).
