### ISSUE TITLE
Used the recordPacket(AVPacket pkt)methods the FFmpegFrameRecorderin the recordPacket(AVPacket pkt)methods to the dts and pts empty value error

### ISSUE THREAD

**Issue by eguid** [bytedeco/javacv#1096]
Usethe recordPacket(AVPacket pkt)methods the FFmpegFrameRecorderto the dts and pts empty valueerror, and the the view of the view and the view file to the set to the codes to the set to the view.
` pkt.dts(AV_NOPTS_VALUE);
 pkt.pts(AV_NOPTS_VALUE);
 pkt.pos(-1);`
In the input dts, ptsset, is be the the view of the the.and the a view of the.and a view of the source of the Dec of the time of the time,and because of this code, I couldn't specify the correct PTS / DTS value in the package,i commented out the code,it worked.
Thank you for your project.
can I submit this code?
Thanks.

**Comment by saudet** [comment]
Of course, please send a pull request! Thanks

BTW, is this related to issue #818?

**Comment by eguid** [comment]
This is different from the problem of issue #818. The program does not report errors when it runs, but the video files or streams after recordPacket cannot be decoded and played properly because of the absence of pts/dts.

**Comment by eguid** [comment]
Thank you for your reply. 
I have submitted pull request.

**Comment by saudet** [comment]
Your fix is now included in JavaCV 1.4.4. Thanks for the contribution!
