### ISSUE TITLE
Decode and play FFmpegFrameGrabber audio

### ISSUE THREAD

**Issue by patriciocordova** [bytedeco/javacv#110]
Hello. I'm trying to grab a stream (using FFmpegFrameGrabber) from a Wowza server, decode it in AAC and play it on an AudioTrack. I have checked some resources on internet:
http://stackoverflow.com/questions/22760325/playing-javacv-ffmpeg-decoded-audio-in-android-with-audiotrack
https://code.google.com/p/javacv/issues/detail?id=453

But I still don't clearly know how to do it. I'll be thankful if you can point me somewhere I can guide myself.

**Comment by patriciocordova** [comment]
Here is a good post to guide you:

http://revealedtricks4u.blogspot.in/2015/03/play-audio-sample-grabbed-using-javacv.html

**Comment by patriciocordova** [comment]
I tried previous answer, but adds a lot of lag. Is there any other method that can give a better result?

**Comment by ShihabSoft** [comment]
Can u please specify your phone model and specifications.

Because javacv is not so accurate for using it for as a video player as
already said by Sam in my previous post.

So try considering open source powerful video players like VLC.

Hope it helps.

**Comment by patriciocordova** [comment]
I have a Xperia Z, but yes, I'll try to find another option. Thank you.

**Comment by teocci** [comment]
Hello, Patricio did you find a solution to this problem I'm facing the same issue. I hope you have some ideas. Saludos
