### ISSUE TITLE
I have some questions about the JavaCV

### ISSUE THREAD

**Issue by qq827896526** [bytedeco/javacv#1100]
I have a question :

I use FileInputStream or Socket to send H.264 file or stream to my  javacv  program
				in = socket.getInputStream();
				grabber = new FFmpegFrameGrabber(in);
				grabber.start(); 
For running this code , when in only one thread , it is ok. but when in muti-thread , only random one grabber can pass the start() method , others will dead lock in this start() method. And , this pass grabber can grab all frames , not only itself's. I think it is this one grab get all inputstream frame and others can't get start frame.
I can use the synchronized block around the grab and record to pass the start(),and when i use FileInputStream ,start() method is very fast so it can also pass start(), but i still can get all of the frames in one grab.I user the Thread.sleep() to wait after grab ,other pass grabber can run ,but also grab random frame,and will dead lock after a little time.
If i use rtmp to send the data ,it is ok. Is javacv can't suport H264 stream ?Or a bug? I can only use SDK to get camera's H264 Stream,No rtsp servers in the camera,so i am in trouble.
Thanks for you to give me this javacv to solve my problem.

**Comment by saudet** [comment]
Could you try again with JavaCV 1.4.3? There have been fixes around that recently.

**Comment by saudet** [comment]
I'm assuming all works well with JavaCV 1.4.3, but please let me know if this isn't the case. Thanks!
