### ISSUE TITLE
 Interruption of device push video stream

### ISSUE THREAD

**Issue by 3449708385** [bytedeco/javacv#1103]
Can javacv recognize the video stream pushed by the device because of the interruption caused by the network or other reasons? I tried hasVideo ()
Discovered that it can only judge whether this is a video stream, FFmpegFrameGrabber grab () method will be directly blocked after the cut-off, can not continue to run.

**Comment by saudet** [comment]
It's possible to set a timeout for this. See this sample from @d-a-gerashenko:
https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java
