### ISSUE TITLE
Out Of Memory Error 

### ISSUE THREAD

**Issue by qq827896526** [bytedeco/javacv#1105]
socket = new Socket(from, port);
                             sin = socket.getInputStream();
                             grabber = new FFmpegFrameGrabber(sin);

I use socketInputStream to send H264 stream to FFmpegFrameGrabber.For seven camera,one hours later,i got a error and lose a thread:
Out Of Memory Error : InputStream.read().but i only use InputStream in this place.maybe it happend in Readcallback?
I use java1.8's  jvisualvm to see the memory.

A gc after
![o r9xl0pryot yo a p_h](https://user-images.githubusercontent.com/39176774/49908322-f606a880-feb4-11e8-8ea9-42ce2319d3a0.png)
![4pva4t4g k 5rv 7 4c1](https://user-images.githubusercontent.com/39176774/49908380-336b3600-feb5-11e8-8636-03e4fd0ce217.png)

Byte[] is very small  but very big,

I use javacv1.4.3 and new FFmpegRecord and this code to send rtmp stream

                                                AVFormatContext fc = grabber.getFormatContext();
                                                recorder.start(fc);
                                                AVPacket pkt = grabber.grabPacket();
						if(pkt==null||pkt.size()<=0||pkt.data()==null) {
							noDatatime ++;
							continue;
						}
						videoTS = 1000 * (System.currentTimeMillis() - startTime);
						pkt.dts(videoTS);
						pkt.pts(videoTS);
						recorder.recordPacket(pkt); 

I am a new coder and i do not know how to solve this out of memory problem.Can you help me?

**Comment by saudet** [comment]
A memory leak has been fixed recently, see issue #1068. Please try to use 1.4.4-SNAPSHOT instead and this issue should go away: http://bytedeco.org/builds/

But please let me know if you're still seeing have problems with the snapshots though, thanks!

**Comment by saudet** [comment]
Also, use the URLs directly with FFmpegFrameGrabber and FFmpegFrameRecorder. It's a lot more efficient than going through Java.

**Comment by kellyho9021** [comment]
Hi @saudet,
I'm getting the same issue. I want to update to 1.4.4-SNAPSHOT but I'm not sure how. I'm using Netbeans so in order to update the 1.4.4-SNAPSHOT, I just replace  javacv.jar with javacv-1.4.4-20190108.032101-14.jar, is it correct?

**Comment by saudet** [comment]
I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
Please give it a try with the snapshots: http://bytedeco.org/builds/
