### ISSUE TITLE
FFmpegFrameGrabber grabFrame() returns null in certain circumstances.

### ISSUE THREAD

**Issue by Cybergrany** [bytedeco/javacv#1106]
Hi,

I've recently come across what seems to be an issue with FFmpegFrameGrabber on Windows 64Bit.

_**Some Background**_
I am creating a program utilising the [Marvin Framework](http://marvinproject.sourceforge.net/en/index.html), which uses JavaCV to convert images into their own format, [MarvinImage.](https://github.com/gabrielarchanjo/marvinproject/blob/master/marvinproject/dev/MarvinFramework/src/marvin/image/MarvinImage.java)

What I am trying to accomplish is getting a frame of video, then converting it into a MarvinImage, by grabbing a frame and converting it into an Integer Array. Here's how I'm doing that (I have excluded init/misc code for brevity):

**getFrame() method:**

```java

private OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();

		public MarvinImage getFrame() throws MarvinVideoInterfaceException{
			try {
				if (grabber.getFrameNumber() < grabber.getLengthInFrames()-1) {
					int[] arr = convertToIntArray(converter.convert(grabber.grabFrame()));
					MarvinImage i = new MarvinImage();
					i.setIntColorArray(arr);
					return i;
				}
			}catch(Exception e) {
				throw new MarvinVideoInterfaceException("Error Grabbing Frame", e);
			}
			return null;
		}

```
**convertToIntArray() Method**
```java

		private int[] convertToIntArray(IplImage img){
			int arr[] = new int[intArray.length];
			ByteBuffer buffer = img.getByteBuffer();
			for(int ii=0, bi=0; bi<buffer.limit()-3; ii++, bi+=3){
				arr[ii] = 0xFF000000 + (buffer.get(bi+2) << 16) + (buffer.get(bi+1) << 8) + buffer.get(bi);
			}
			return arr;
		}

```

_**The Issue**_

Running this code returns a NullPointerException. It would appear that  when I call `grabber.grabFrame()` nothing is returned, and the null value for `img` in `convertToIntArray` causes the program to crash.

_**Things I have tried**_

I'm only here as a last result, I've spent hours trying to figure out if it's been something I've glossed over in my own code, so to make sure I've deconstructed it and stripped back my usage of `grabFrame()` until it worked.

- Excluding the `convertToIntArray()` method.
My first port of call, maybe the operation didn't sit well with `getFrame()`'s output?  I tried breaking down this operation; `int[] arr = convertToIntArray(converter.convert(grabber.grabFrame()));` and tested only the output of `grabber.grabFrame()` Nope it was definitely `grabber.grabFrame()` that was returning `null`.

- Catching `NullPointerException`
From reading some similar issues it seems as if maybe I was getting some audio frames thrown in, so I tried catching, which simply gave me no frames at all.

- Does `grabFrame()` work elsewhere in my project?
Yes and No. I experimented a bit in my Class's constructor. 

This code worked fine:

```java

do {
	System.out.print("frame number: " + grabber.getFrameNumber());//See if the frames are advancing
}while(grabber.getFrameNumber() < grabber.getLengthInFrames());

```
The output counted steadily upwards until reaching the total frame count of the video, as expected. I then added this to my `do{}` loop

```java
Frame fr = grabber.grabFrame();
System.out.println("width: " + fr.imageWidth);//Quick test to see if grabbed frames have a value
```

Here's a snippet of the output:

```
frame number: 0width: 0
frame number: 0width: 450
frame number: 0width: 0
frame number: 0width: 450
frame number: 1width: 0
frame number: 1width: 0
frame number: 1width: 450
frame number: 3width: 0
frame number: 3width: 450
frame number: 3width: 0
frame number: 3width: 0
frame number: 3width: 450
frame number: 4width: 0
frame number: 4width: 450
frame number: 6width: 0
frame number: 6width: 0
frame number: 6width: 450
frame number: 6width: 0
frame number: 6width: 450
frame number: 7width: 0
frame number: 7width: 450
frame number: 9width: 0
frame number: 9width: 0
frame number: 9width: 450
frame number: 9width: 0
frame number: 9width: 450

```

Ok, so it seems that irregularly, or about every 2/3 loops, `grabFrame()` is `null`, shown by `fr.imageWidth` being `0`. Why even is it looping over the same frame number more than once?? Maybe it's the audio channels?

I try `grabber.setAudioChannels(0);` Same output.

(Grasping at straws here) maybe the processing is happening too fast and needs time to catch up? I try doing `Thread.sleep(50)` at the end of my `do` loop. Same output.

Sorry for the absolute wall of text, but I hope it's helpful in describing what my problem is and what I've done to try and fix it. Maybe it's something I've completely glossed over and I'm an idiot here. Do please call me out if that's the case. Anyway, thanks for taking the time to read this, and looking forward to hearing back from you.

**Comment by saudet** [comment]
It will do that for audio frames, so try to call grabImage() instead.

**Comment by Cybergrany** [comment]
Ah jeez, I knew it was something simple, cheers a lot for the answer and thanks for your hard work on this project.

**Comment by saudet** [comment]
Should it be in the Javadoc comments? If so, please do send a pull request with that! Thanks
