### ISSUE TITLE
The difference between Mat's package

### ISSUE THREAD

**Issue by devishell** [bytedeco/javacv#1107]
The difference between org.bytedeco.javacpp.opencv_core and org.opencv.core of Mat.class?
Which case should i use org.opencv.core.mat ,or i should always use the opencv_core.Mat?

**Comment by saudet** [comment]
One is generated with JavaCPP, the other is not, that's all: http://bytedeco.org/faq/
Use the one that does what you need to do!

**Comment by saudet** [comment]
BTW, it's also easy to convert from one to the other with OpenCVFrameConverter:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.html
So there really isn't anything to worry about which one you choose.
