### ISSUE TITLE
black screen when recorder output rtmp

### ISSUE THREAD

**Issue by HeavenDuke** [bytedeco/javacv#1109]
Hi
I'm using FFmpegFrameRecorder(using JavaCV 1.4.3) to write frames to rtmp stream, but in vlc player I kept getting black frames. 

The code for setting up a recorder is:
```
Java2DFrameConverter converter = new Java2DFrameConverter();
FrameRecorder recorder = FrameRecorder.createDefault("rtmp://localhost:1935/live/stream", 1280, 720);
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setFormat("flv");
recorder.setFrameRate(25D);
recorder.start();
```
The code for recording frames is:
```
// code within looping(msg is a byte array)
InputStream stream = new ByteArrayInputStream(msg);
BufferedImage img = ImageIO.read(stream);
recorder.record(converter.convert(img));
```

I have also tried using the demo provided in README, but the result is the same, while using normal video file as output works totally fine.

Any ideas? Thanks!

**Comment by saudet** [comment]
Be sure to check FFmpeg's log for any suspicious messages.

**Comment by HeavenDuke** [comment]
My bad. Turns out that ffpplay and flv.js can both play the live video smoothly. Sorry for bothering…
