### ISSUE TITLE
Question about playback

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#111]
Can you steam a .flv file from an url somehow? Like ``http://someFancyLink/coolVid.flv`` ?

**Comment by saudet** [comment]
Sure, just call `new FFmpegFrameGrabber("http://someFancyLink/coolVid.flv")` and we should be able to grab the frames as shown in the `Demo` class of the `README.md` file.

**Comment by lfdversluis** [comment]
Ah right, thanks I'll check it out!
