### ISSUE TITLE
Some question about JavaCV  

### ISSUE THREAD

**Issue by qq827896526** [bytedeco/javacv#1111]
Recently I use JavaCV to send H264Stream to RTMPStream.
Firstly ,I used JavaCV 1.4.4-snapshot with SocketInputStream , I can't use 1.4.3 because record dts problem and garber timeout  problem , and if I use SocketInputStream the memory is very very big , ten thread needs 2G memory, my god. so I can only use url to let ffmepg manager the connection ,the memory and gc is ok ! but if i use this way, I can't send any information to the socket , for example stop commad , and can't filter any commad from my socket,and how to solve this problem, with good memory and command manager ?
Secondly It's so slow in avformat_find_stream_info() ,so i copy the new FFmpegFrameGrabber.java and  add oc.probesize(81920) to solvo this problem ,of course it's also a problem if it's not enough frame to get information, of couse in my test I set the codecid ,framerate,and any others information ,it's ok,maybe it's a solve way?
Thirdly ,with ten connection thread, I found the crash in native code after running about seven hours after ,i have changed the oc.probesize(81920) and set the timeout Option. use AVPacket pkt = grabber.grabPacket() to get AVPacket ,but it crash in av_read_frame().now the memory and cpu is ok when errors heppend. I'm tracking this problem. maybe you can know about the problem?

Thanks for you to let us can using Java to solvo the problem. i'm a new Java coder and don't good at Cpp , it is a easy way to devlop.

**Comment by saudet** [comment]
I'm sure we can enhance FFmpegFrameGrabber and FFmpegFrameRecorder in some way to support all this properly. In any case, please send a pull request that includes some of the changes you've already made! Thank you

**Comment by qq827896526** [comment]
And  what means of pull request ? .....

**Comment by saudet** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by saudet** [comment]
I'm pretty sure we can set the "probesize" with `setOption()` as shown in issue https://github.com/bytedeco/javacv/issues/808#issuecomment-429864160.
Please let me know if this isn't the case or if that doesn't solve your issue! Thanks
