### ISSUE TITLE
How to stream on wowza webRTC (H.264, G.7111 codec )from Android?

### ISSUE THREAD

**Issue by Midhun9638** [bytedeco/javacv#1116]
Is this possible to streaming on wowza webRTC using H.264 and G.711 codec ?

**Comment by saudet** [comment]
Probably, are you getting any error messages?

**Comment by saudet** [comment]
There's this sample here:
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java
