### ISSUE TITLE
Error when building an Android Bundle

### ISSUE THREAD

**Issue by slobglob** [bytedeco/javacv#1117]
Hey,

Trying to build an Android bundle and not APKs.
 I get the following error:
`File 'root/lib/arm64-v8a/include/opencv2/core/wimage.hpp' uses reserved file or directory name 'lib'.`

I understand it's using a reserved bundle name probably, any idea how can it be fixed or when?

Thanks !

**Comment by saudet** [comment]
It looks like we'd need to create AAR files in addition to JAR files for this to work:
https://stackoverflow.com/questions/50279346/android-app-bundle-build-fails/50355398
It would add complexity to the build system and probably create hassle for users that are interested in portability to other platforms than Android... In any case, if you're interested in upgrading the build to support the creation of AAR files, please do, contributions are welcome!

**Comment by talregev** [comment]
I have the same issue.    
I am Author of [cv_bridge_javacv][1] library,   
and I use android javacv arm / arm64 versions.   
Can you make AAR files only for android?    

[1]:https://github.com/talregev/android_cv_bridge

**Comment by saudet** [comment]
@talregev Yes, it's possible. Contributions are welcome!

**Comment by marwfair** [comment]
I'm running into a similar issue: `File 'root/lib/arm64-v8a/ffmpeg' uses reserved file or directory name 'lib'.` Has there been any updates to address this?

**Comment by akash2018xD** [comment]
Hi, I am getting a similar issue and am not able to generate bundle file. 
Error :
Execution failed for task ':app:packageMockDebugBundle'.
> 1 exception was raised by workers:
  com.android.tools.build.bundletool.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/lib/arm64-v8a/include/lapacke_config.h' uses reserved file or directory name 'lib'.
.
My dependencies :
implementation 'org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3'
    implementation 'org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-arm'
    implementation 'org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-arm64'
    implementation 'org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-x86'
    implementation 'org.bytedeco.javacpp-presets:openblas:0.3.3-1.4.3:android-x86_64'
. 
If I remove them then the bundle is generated properly but nd4j throws error when being invoked while running the app.
.
I am a newbie, so some help here to fix my issue will be much appreciated,
Thanks!

**Comment by saudet** [comment]
BTW, in case anyone is wondering, we can exclude those files from the build.
They are not necessary at runtime.

**Comment by akash2018xD** [comment]
I'm a new to Android development. Can you explain how to exclude them from
build.
I'm unable to figure it out.
Thanks!

**Comment by saudet** [comment]
@akash2018xD There's some examples of that in issue #353.

**Comment by lisichka999** [comment]
@saudet Excluding file solved the problem, but what does this library do? Don't we need it at all? Thanks

**Comment by saudet** [comment]
@lisichka999 No, it should be made more modular, see issue #1071.

**Comment by phillies** [comment]
I get a similar error:
`File 'root/lib/x86_64/include/opencv2/shape/shape_distance.hpp' uses reserved file or directory name 'lib'.`

with javacv included in my kotlin project
```
    implementation "org.bytedeco:javacv:1.5.3"
    implementation "org.bytedeco:opencv-platform:4.3.0-1.5.3"
```
But I'm unable to fix it by excluding the files as shown above. I tried the example given above
```
packagingOptions {
    pickFirst  'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
    pickFirst  'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
    pickFirst  'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
    pickFirst  'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
}
```
Which obviously did not work because I use opencv-platform not javacv-presets. So I adjusted the paths to what I think should be right
```
    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        pickFirst 'META-INF/maven/org.bytedeco/opencv-platform/pom.properties'
        pickFirst 'META-INF/maven/org.bytedeco/opencv-platform/pom.xml'
    }
```
But the error persists. Any ideas?

**Comment by saudet** [comment]
@phillies You'll need to exclude all the files from `lib/x86_64/include`, etc.

**Comment by vdang** [comment]
@saudet How can we exclude all the files from `lib/x86_64/include` exactly? The link you provided above which you said to have some examples for exclusion seems to point to what @phillies had. I can't find any details on excluding `.h` files.

I tried:
```
packagingOptions {
    exclude '**/lib/arm64-v8a/include/*'
}
```
which didn't help (my error message was ` File 'root/lib/arm64-v8a/include/cvkernels.h' uses reserved file or directory name 'lib'.
` hence `arm64-v8a` in the path)

**Comment by saudet** [comment]
Something like this I guess: https://github.com/bytedeco/javacv/issues/1329#issuecomment-720758804

**Comment by vdang** [comment]
Thanks for the super quick response, @saudet!

Neither `exclude 'META-INF/native-image/**'` nor `exclude 'META-INF/**/root/lib/arm64-v8a/include/cvkernels.h'` worked for me unfortunately. I still get the exact same error message: **File 'root/lib/arm64-v8a/include/cvkernels.h' uses reserved file or directory name 'lib'**.

Any other advice?

**Comment by rgm-22** [comment]
> I'm running into a similar issue: `File 'root/lib/arm64-v8a/ffmpeg' uses reserved file or directory name 'lib'.` Has there been any updates to address this?

Same problem. Did you solved it @marwfair?

**Comment by saudet** [comment]
It looks like we need to move those files from from `/root/lib` into `/lib` instead:
https://developer.android.com/guide/app-bundle/app-bundle-format
I'm not sure how to do that, they are already under `/lib` in the JAR files. For some reason the tool that you are using to create bundles moves them under `/root` instead, so if you figure out why it's doing that, fixing that should make it work.

**Comment by rgm-22** [comment]
Thank you for your quick comment Samuel! 

I succeed💪. I was placing the ffmpeg-android-arm.jar, ffmpeg-android-arm64.jar, ffmpeg-android-x86.jar, and ffmpeg-android-x86_64.jar in the app/libs path instead of placing the image .so files in jniLibs/arm64-v8a and jniLibs/arm64-v7a.

Thank you again for your work! 😊

**Comment by yasserakbbach** [comment]
Hello @rgm-22 I'm having the same issue:

```
Execution failed for task ':app:packageReleaseBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.PackageBundleTask$BundleToolWorkAction
   > File 'root/lib/commons-codec-1.8.jar' uses reserved file or directory name 'lib'.
```

Could you please provide me with more details?

**Comment by rgm-22** [comment]
Hi @yasserakbbach!

Take care where you are placing "commons-codec-1.8.jar".

You need to follow this file structure:

- app/libs -> place the ".jar" libraries

- app\src\main\jniLibs -> place the compiled libraries (".so" files) following the arm64-v8a, armeabi, armeabi-v7a, etc. structure.

I hope to help!

**Comment by yasserakbbach** [comment]
Hi @rgm-22 again,
Thanks for your input, I've just solved the problem by deleting the following dependencies (they were unused anyways)

```
implementation 'commons-codec:commons-codec:1.10'
implementation 'com.google.guava:guava:28.0-android'
implementation 'org.apache.directory.studio:org.apache.commons.codec:1.8'
```

**Comment by rgm-22** [comment]
Hi @yasserakbbach!

I'm glad you succeed 💪😀.

**Comment by lakharasachin-qf** [comment]
Hii @rgm-22 
I am using FFMPEG and placed complied FFMPEG into **resourse/lib/** folder and it's totally working fine in debug mode, But when I am creating release bundle it shows error 
**"File 'root/lib/arm64-v8a/ffmpeg' uses reserved file or directory name 'lib'."**

![Capture](https://user-images.githubusercontent.com/62238022/139794392-6eeb10c9-0cf1-4c06-89b6-b98d2443272c.PNG)
![Capture2](https://user-images.githubusercontent.com/62238022/139794482-fd4516f3-39dd-49e9-9449-684c64ce8472.PNG)

Please help me how can resolve this problem

**Comment by rgm-22** [comment]
Hi @lakharasachin-qf !

Sorry for the late response.

Please, try to follow this structure:

- app/libs -> place the ".jar" libraries

- app/src/main/jniLibs -> place the compiled libraries (".so" files) following the arm64-v8a, armeabi, armeabi-v7a, etc. structure.


![00](https://user-images.githubusercontent.com/68119614/140594521-a4925660-d9ea-4336-a179-335fb6b9aa95.jpg)
-
![01](https://user-images.githubusercontent.com/68119614/140594535-f5190699-0e36-4c75-9200-d20d529f8912.jpg)
-
![02](https://user-images.githubusercontent.com/68119614/140594543-711e6a1e-a366-4396-a7a5-1f3f116dc0fd.jpg)


I hope to help!

**Comment by hamorillo** [comment]
Hi @rgm-22! 

I'm adding the libraries under `app/libs`:
![Screenshot 2021-11-23 at 10 28 45](https://user-images.githubusercontent.com/6974554/142999838-9022a5a4-54bd-4551-bbf0-3ee3a7435cc7.png)

Adding on build.gradle the following:
![Screenshot 2021-11-23 at 10 29 50](https://user-images.githubusercontent.com/6974554/142999975-4d6ac455-a2a0-4cbf-b961-40e74fa08b01.png)

The APK generation works but when I try to generate a bundle for uploading to the Google Play console I always obtain the same error:

`
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
File 'root/lib/arm64-v8a/include/opencv2/imgcodecs/imgcodecs.hpp' uses reserved file or directory name 'lib'.
`

Any idea?

**Comment by rgm-22** [comment]
Hi @hamorillo!

In my case, I didn't add the "-android-arm.jar" "-android-arm64.jar" files in app/libs nither build.gradle.

Remeber to add the compiled libraries (".so" files) to app/src/main/jniLibs, following the arm64-v8a, armeabi, armeabi-v7a, etc. structure.

Please, let me know your results.
I know that this process is frustrating when your app is ready to be uploaded to Google Play ☹

I hope to help!

**Comment by saudet** [comment]
After investigating this thoroughly, it appears that the cleanest solution to this issue is to get Gradle to extract the libraries for us, then tell the plugin for Android to pick them up from that location, and let it do whatever it wants with them. Something like the following in `app/build.gradle` works fine for me:

```groovy
configurations {
    javacpp
}

task javacppExtract(type: Copy) {
    dependsOn configurations.javacpp

    from { configurations.javacpp.collect { zipTree(it) } }
    include "lib/**"
    into "$buildDir/javacpp/"
    android.sourceSets.main.jniLibs.srcDirs += ["$buildDir/javacpp/lib/"]

    tasks.getByName('preBuild').dependsOn javacppExtract
}

dependencies {
    implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.6'
    javacpp group: 'org.bytedeco', name: 'openblas-platform', version: '0.3.17-1.5.6'
    javacpp group: 'org.bytedeco', name: 'opencv-platform', version: '4.5.3-1.5.6'
    javacpp group: 'org.bytedeco', name: 'ffmpeg-platform', version: '4.4-1.5.6'
    ...
}
```

To shorten that a bit further, it should be feasible to add this "javacppExtract" task to [Gradle JavaCPP](https://github.com/bytedeco/gradle-javacpp), but I'm not sure it's worth the trouble. If that snippet works well enough for everyone here, I may just add that to the docs somewhere. What do you all think?

**Comment by saudet** [comment]
I've added that code snippet in commit https://github.com/bytedeco/gradle-javacpp/commit/036a68560074db99d6e8910e185f2b63668f73f1 and also updated the JavaCV-android-example sample project in commit https://github.com/bytedeco/sample-projects/commit/2378afc54a0fe7a96bbc769e46d98fe9cef43f0d, so I think I'll consider this issue solved. If anyone still has any problems with that though, please let me know!

**Comment by NguyenNguyen77** [comment]
Hi All,
I have the same issue, but my issue does not relate to the lib. 
I want to build aab to upload CH Play but it always fails and shows a message: 
`File 'root/res/drawable-hdpi/ic_launcher.png' uses reserved file or directory name 'res'.`

I tried to search ic_launcher.png but my app does not use that name. I don't know how to resolve it.
Please help me resolve this issue. I research for 2 days but was still stuck with it.
Thanks.

**Comment by hilmisatrio16** [comment]
Hi all, 
I have the same problem when build bundle on android studio

Error:
```
Execution failed for task ':app:packageDebugBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.PackageBundleTask$BundleToolWorkAction
   > File 'root/lib/arm64-v8a/include/cvkernels.h' uses reserved file or directory name 'lib'.
``` 

Dependecy

```
    implementation 'org.bytedeco:javacv:1.4.4'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm64'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-x86
```

**Comment by saudet** [comment]
Please try to follow the instructions here:
https://github.com/bytedeco/gradle-javacpp?tab=readme-ov-file#the-platform-plugin
