### ISSUE TITLE
not found libmmal_core.so when I open usb camera in a ubuntu system

### ISSUE THREAD

**Issue by YangAtSz** [bytedeco/javacv#1118]
I am using a linux board named friendlyARM T2, ubuntu 
When I open the usb camera to capture a picutre, I get the error "libmmal_core.so not found"
Did I missed some libs ?

**Comment by saudet** [comment]
That's not a Raspberry Pi? We might be able to work around that by
installing its runtime: https://github.com/raspberrypi/userland

**Comment by saudet** [comment]
Could you try with 1.4.4-SNAPSHOT?
http://bytedeco.org/builds/
This should be fixed now.

**Comment by saudet** [comment]
The fix has been released with JavaCV 1.4.4. Thanks for reporting this issue!

**Comment by YangAtSz** [comment]
thanks a lot
