### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Couldn't load jniavutil: findLibrary returned null

### ISSUE THREAD

**Issue by vah13** [bytedeco/javacv#112]
Hi .
I use Android studio 

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile group: 'org.bytedeco', name: 'javacv', version: '0.10'
    compile group: 'org.bytedeco', name: 'javacpp', version: '0.10'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.9-0.9', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.3-0.9', classifier: 'android-arm'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.google.android.gms:play-services:6.5.87'
}

when I call      public static void tryLoad() throws Exception {
        if (loadingException != null) {
            throw loadingException;
        } else {
            try {
                Loader.load(org.bytedeco.javacpp.avutil.class);
                Loader.load(org.bytedeco.javacpp.swresample.class);
                Loader.load(org.bytedeco.javacpp.avcodec.class);
                Loader.load(org.bytedeco.javacpp.avformat.class);
                Loader.load(org.bytedeco.javacpp.swscale.class);

                /* initialize libavcodec, and register all codecs and formats */
                av_register_all();
                avformat_network_init();
            } catch (Throwable t) {
                if (t instanceof Exception) {
                    throw loadingException = (Exception)t;
                } else {
                    throw loadingException = new Exception("Failed to load " + FFmpegFrameRecorder.class, t);
                }
            }
        }
    }
got exception java.lang.UnsatisfiedLinkError: Couldn't load jniavutil: findLibrary returned null.
please help, how I can fix it?

**Comment by saudet** [comment]
JavaCV 0.10 depends on JavaCPP 0.10, so try again with these versions of the native artifacts:
```groovy
compile group: 'org.bytedeco', name: 'javacv', version: '0.10'
compile group: 'org.bytedeco', name: 'javacpp', version: '0.10'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.10-0.10', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.5.1-0.10', classifier: 'android-arm'
```

**Comment by vah13** [comment]
Ok thank you. All work
