### ISSUE TITLE
avformat_open_input() error -99: Could not open input "rtmp://192.168.100.99/live/1080". (Has setFormat() been called?)

### ISSUE THREAD

**Issue by peterbence3** [bytedeco/javacv#1123]
Hello, I'm using `FFmpegFrameGrabber `in order to play one of the following:

1. rtmp://192.168.100.99/live/1080 (streamed by OBS)
2. rtsp://192.168.100.99:8554/live (streamed by VLC)

**Code:**

```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber (streamUrl);
grabber.setOption("fflags","nobuffer");
grabber.setOption("timeout","10");
grabber.setOption("stimeout","10");
grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);
grabber.start();
...
...
```

The whole thing was running so fine with no errors for tens of time, until suddenly at a random time it started to throw the following exception whenever `grabber.start()` is called and didn't work since then:

`avformat_open_input() error -99: Could not open input "rtmp://192.168.100.99/live/1080". (Has setFormat() been called?)`

Any help would be appreciated thanks!!

**Comment by peterbence3** [comment]
I solved it, **timeout** option was preventing rtmp from starting, where **stimeout** option was preventing both rtsp & rtmp. So i'm now using **timeout** for rtsp but what timeout option could i use for rtmp?

**Comment by saudet** [comment]
According to the documentation at https://ffmpeg.org/ffmpeg-protocols.html it's probably "rw_timeouts".
