### ISSUE TITLE
FFmpegFrameRecorder could not work while generating gif with transparent background

### ISSUE THREAD

**Issue by cfcodefans** [bytedeco/javacv#1137]
I am trying to use ffmpeg to process gif images, (resize, crop, flip, rotate, etc...)
In ffmpeg code, the gif encoder supports following pixel formats:

FFmpeg\libavcodec\gif.c line 495
```c
                        .pix_fmts       = (const enum AVPixelFormat[]){
        AV_PIX_FMT_RGB8, AV_PIX_FMT_BGR8, AV_PIX_FMT_RGB4_BYTE, AV_PIX_FMT_BGR4_BYTE,
        AV_PIX_FMT_GRAY8, AV_PIX_FMT_PAL8, AV_PIX_FMT_NONE
```

among these formats, only AV_PIX_FMT_PAL8 can support transparency

however, AV_PIX_FMT_PAL8 is not supported by sws_getCachedContext used in
org.bytedeco.javacv.FFmpegFrameRecorder, line 924
```java
if (video_c.pix_fmt() != pixelFormat || video_c.width() != width || video_c.height() != height) {
                /* convert to the codec pixel format if needed */
                img_convert_ctx = sws_getCachedContext(img_convert_ctx, width, height, pixelFormat,
                        video_c.width(), video_c.height(), video_c.pix_fmt(),
                        imageScalingFlags != 0 ? imageScalingFlags : SWS_BILINEAR,
                        null, null, (DoublePointer)null);
                if (img_convert_ctx == null) {
                    throw new Exception("sws_getCachedContext() error: Cannot initialize the conversion context.");
                }
```

defined in FFmpeg\libswscale\utils.c
```c
static const FormatEntry format_entries[AV_PIX_FMT_NB] = { //line 98
...
  [AV_PIX_FMT_PAL8]        = { 1, 0 }, //line 110
```

which means resizing can not work with sws_getCachedContext

however ffmpeg cli seems to be working

please leave comments if I missed anything, or there is other way to make it work.
thanks in advance.

**Comment by saudet** [comment]
Actually, this should already work. If we call `FFmpegFrameRecorder.setPixelFormat(AV_PIX_FMT_PAL8)` before `start()` as well as `record(frame, AV_PIX_FMT_PAL8)` for each image, and make sure to set the width and height to the same values as all the the input images, `sws_getCachedContext()` won't get called. Let me know if this doesn't work though, thanks!
