### ISSUE TITLE
Seems like frameGrabber.setOption doesn't work.

### ISSUE THREAD

**Issue by zxdispd** [bytedeco/javacv#1142]
I use FFmpegFrameGrabber grab Image from video.

FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("videoUrl");
frameGrabber.setOption("RW_TIMEOUT".toLowerCase(), "3000000");
frameGrabber.setOption("threads", "1");
frameGrabber.setOption("vf","thumbnail=34");
frameGrabber.setOption("vsync","0");
...

Seems like only the first option work (RW_TIMEOUT),and the other option di

**Comment by saudet** [comment]
Duplicate of #1134
