### ISSUE TITLE
OpenCV "Transparent API" on Android?

### ISSUE THREAD

**Issue by newbie-gk** [bytedeco/javacv#1148]
I tested the "Transparent API" of OpenCV in JavaCV by simply comparing the speed of converting a test image color space using the normal "Mat" vs "UMat" on my windows pc (Intel i5-5300U), and the results were **impressive, it was a 5 times speedup**. 

However, when I tried the test on Android (Xiaomi A2 - Snapdragon 660), it showed no difference... 
Here's what's in the gradle file:
`  implementation group: 'org.bytedeco', name: 'javacv', version: '1.4.4'
  implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-arm'
  implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-arm64'
  implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-x86'
  implementation group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '4.0.1-1.4.4', classifier: 'android-x86_64'`

This leads me to question, whether the "Transparent API" is  implemented in these versions or not ? Additionally, I checked on the [opencv website](https://docs.opencv.org/3.4.0/d7/dbd/tutorial_android_ocl_intro.html) , it states that 
"By default the OpenCL support (T-API) is disabled in OpenCV builds for Android OS (so it's absent in official packages as of version 3.0), but it's possible to rebuild locally OpenCV for Android with OpenCL/T-API enabled: use -DWITH_OPENCL=YES option for CMake."

Does this mean that JavaCv for Android does not support "Transparent API"...
What would need to be done to have JavaCV support "Transparent API" in Android ?

**Comment by saudet** [comment]
You'll need a device that supports OpenCL. Unfortunately, almost no device
does, so you're unlikely to see an improvement on Android.

**Comment by newbie-gk** [comment]
I checked android's OpenCL support by using the "OpenCL-Z" app and it does seem to support OpenCL as the image below.
I've been using OpenCV for a while, but don't quite understand the CMAKE / Build Process to build native libs yet ><
Is it possible that the OpenCV build that was used for making JavaCV for Android didn't have -DWITH_OPENCL=YES option?
![screenshot_20190305-144015](https://user-images.githubusercontent.com/12275844/53788726-252d3300-3f55-11e9-9565-2a044862a5d0.png)

**Comment by saudet** [comment]
No, it's build with OpenCL:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/cppbuild.sh#L53
Maybe try to call `System.load("/system/vendor/lib/libOpenCL.so")` before calling functions from OpenCV?

**Comment by newbie-gk** [comment]
I tried to add System.load("/system/vendor/lib/libOpenCL.so") to my code but it's getting error as below:

java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/vendor/lib/libOpenCL.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"

Here's the block for loading libs:

    System.load("/system/vendor/lib/libOpenCL.so");

    ReLinker.Logger logger = new ReLinker.Logger() {
      @Override
      public void log(String message) {
        Log.v("HODOR", "(hold the door) " + message);
      }
    };
    ReLinker.log(logger).recursively().loadLibrary(this, "jniopencv_core");
    ReLinker.log(logger).recursively().loadLibrary(this, "opencv_core");
    ReLinker.log(logger).recursively().loadLibrary(this, "jniopencv_imgcodecs");
    ReLinker.log(logger).recursively().loadLibrary(this, "opencv_imgcodecs");
    ReLinker.log(logger).recursively().loadLibrary(this, "jniopencv_imgproc");
    ReLinker.log(logger).recursively().loadLibrary(this, "opencv_imgproc");

Loading .so files like this is a first for me too ><" Let me find a way to properly load the .so file and I'll report how it works.

**Comment by saudet** [comment]
You might need to set the API level of your application to less than 23:
https://github.com/ARM-software/ComputeLibrary/issues/135

**Comment by saudet** [comment]
I'm assuming that calling `System.load("/system/vendor/lib/libOpenCL.so")` from an application set to API level 21 works, but let me know if this isn't the case! Thanks

**Comment by tensorbuffer** [comment]
@newbie-gk were you able to get it working? (use OpenCV with OpenCL support on Qualcomm device)?
