### ISSUE TITLE
FFmpegFrameRecorder crash when instantiated with the same outputstream object

### ISSUE THREAD

**Issue by musachyb** [bytedeco/javacv#1149]
Creating a second instance of the recorder with the same outputstream object make it crash the JVM, code:
```
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

FFmpegFrameRecorder recorder0 = new FFmpegFrameRecorder(outputStream, 300, 300);
recorder0.setFormat("matroska");
recorder0.start();

FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new FileInputStream("/tmp/some_file.mkv"));
grabber.start();
Frame frame = grabber.grabImage();

recorder0.record(frame);

recorder0.stop();
    
//will crash here
FFmpegFrameRecorder recorder1 = new FFmpegFrameRecorder(outputStream, 300, 300);
```

Now this is a dumb thing to do, but I ran into it as I cannot find a way to flush the recorder, without calling stop() on it. I am on OSX and using version 1.4.4. Part fo the core dump:

```
Stack: [0x000070000d666000,0x000070000d766000],  sp=0x000070000d7656e0,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libavformat.58.dylib+0x14fbc4]  avformat_new_stream+0x244
j  org.bytedeco.javacpp.avformat.avformat_new_stream(Lorg/bytedeco/javacpp/avformat$AVFormatContext;Lorg/bytedeco/javacpp/avcodec$AVCodec;)Lorg/bytedeco/javacpp/avformat$AVStream;+0
j  org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe()V+740
j  org.bytedeco.javacv.FFmpegFrameRecorder.start()V+1
j  Main.main([Ljava/lang/String;)V+95
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x2f0d1e]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x6ae
V  [libjvm.dylib+0x327cc5]  jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*)+0x1bf
V  [libjvm.dylib+0x320a51]  jni_CallStaticVoidMethod+0x15d
C  [java+0x38c6]  JavaMain+0x9c4
C  [libsystem_pthread.dylib+0x3661]  _pthread_body+0x154
C  [libsystem_pthread.dylib+0x350d]  _pthread_body+0x0
C  [libsystem_pthread.dylib+0x2bf9]  thread_start+0xd
C  0x0000000000000000

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.bytedeco.javacpp.avformat.avformat_new_stream(Lorg/bytedeco/javacpp/avformat$AVFormatContext;Lorg/bytedeco/javacpp/avcodec$AVCodec;)Lorg/bytedeco/javacpp/avformat$AVStream;+0
j  org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe()V+740
j  org.bytedeco.javacv.FFmpegFrameRecorder.start()V+1
j  Main.main([Ljava/lang/String;)V+95
v  ~StubRoutines::call_stub
```

**Comment by saudet** [comment]
Let's add a `FrameRecorder.flush()` method, can you try to do that?

**Comment by musachyb** [comment]
I will try

**Comment by saudet** [comment]
I've added a `flush()` method in commit https://github.com/bytedeco/javacv/commit/cc39f610a1dcd9c8216f015c23fda454cd1573c7.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by musachyb** [comment]
I did try that before and flush worked fine, but it would crash if I tried to write a frame after flushing. the following code:

```java
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        FFmpegFrameRecorder recorder0 = new FFmpegFrameRecorder(outputStream, 300, 300);
        recorder0.setFormat("matroska");
        recorder0.start();

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new FileInputStream("tmp.mkv"));
        grabber.start();

        Frame frame = grabber.grabImage();
        recorder0.record(frame);
        recorder0.flush();

        frame = grabber.grabImage();
        recorder0.record(frame);

        recorder0.stop();
```

Fails with: 
```
[libx264 @ 0x7fb669b79200] lookahead thread is already stopped
Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -542398533: Could not encode video packet.
```

I did some digging before and couldn't figure out how to fix that.

**Comment by saudet** [comment]
It sounds like libx264 doesn't support flushing without terminating encoding. Try to use another codec.

**Comment by saudet** [comment]
You could also try to disable threads for libx264, whose multithreading support is known to be buggy:
https://github.com/bytedeco/javacv/issues/745#issuecomment-336786816

**Comment by saudet** [comment]
But that seems to be a feature of the codec:
https://mailman.videolan.org/pipermail/x264-devel/2015-July/011117.html

**Comment by saudet** [comment]
I've added a couple of properties in commit https://github.com/bytedeco/javacv/commit/a9e36dc3f0ffb1c2c234ad249ada4d0e7aedbe7d with which you should be able to recreate a new instance of `FFmpegFrameRecorder` over the same `OutputStream` by calling `setCloseOutput(false)`.

**Comment by musachyb** [comment]
Confirming that it works. I am able to create a new recorder by using setCloseOutputStream on the previous ones. Thanks a lot for the support!

**Comment by antecessor** [comment]
Hi.
I have the same problem. 
`
  fFmpegFrameRecorder = new FFmpegFrameRecorder(outputStream, rtspConnectionStream.getImageWidth(), rtspConnectionStream.getImageHeight());
        fFmpegFrameRecorder.setFormat("matroska");
        fFmpegFrameRecorder.setVideoOption("threads", "1");
        fFmpegFrameRecorder.setVideoQuality(20); //0=lossless, 23=pretty good
        fFmpegFrameRecorder.setFrameRate(rtspConnectionStream.getFrameRate());
        fFmpegFrameRecorder.setCloseOutputStream(false);
        fFmpegFrameRecorder.setGopSize(4);
        fFmpegFrameRecorder.start();

   Frame frame = rtspConnectionStream.grabImage();
            fFmpegFrameRecorder.record(frame);
          fFmpegFrameRecorder.flush();
          fFmpegFrameRecorder.record(frame);  // Give error
`
When I want to use new instantiate of FFmpegFrameRecorder on same stream, I have to stop previous one and start the new one, which raise MiniDumps failure.

I will be appreciated if you help me with that.

**Comment by saudet** [comment]
It's probably not a good idea to call flush() if you have more data to record().

**Comment by antecessor** [comment]
So, how we can read and write from one file, simultaneously?

**Comment by saudet** [comment]
I don't think that's something FFmpeg supports. You'll need to read and write with memory mapped files probably.
