### ISSUE TITLE
Issues in video convert time

### ISSUE THREAD

**Issue by vah13** [bytedeco/javacv#115]
Hi dear support.
I for rotate video use next code 

OpenCVFrameConverter.ToIplImage converter2 = new OpenCVFrameConverter.ToIplImage(); 
for (int i = firstIndex; i <= lastIndex; i++) {
long t = timestamps[i % timestamps.length] - startTime;
if (t >= 0) {
if (t > recorder.getTimestamp()) {
recorder.setTimestamp(t);
}
Frame g = converter2.convert(rotate(converter2.convertToIplImage(images[i % images.length]),90));
recorder.record(g);
}
}

but after rotation have green lines in video
![green](https://cloud.githubusercontent.com/assets/7976421/6957921/6d464504-d90c-11e4-86ce-65e47a8a0bfb.png)

What I wrong do?

**Comment by saudet** [comment]
If you're trying to read YUV camera data, try to use `AndroidFrameConverter.convert(byte[] data, int width, int height)` first.

**Comment by vah13** [comment]
excuse me, but don't work :(

**Comment by saudet** [comment]
This might be related to this issue here:
https://github.com/bytedeco/javacv/issues/145#issuecomment-101209354
Try to modify the sample as explained in the comment.
