### ISSUE TITLE
How to use ffmpeg Stream copy parameter in Javacv?

### ISSUE THREAD

**Issue by laosijikaichele** [bytedeco/javacv#1150]
how to use ffmpeg copy parameter to the -codec option in Javacv?
As shown in ffmpeg doc: https://ffmpeg.org/ffmpeg.html#Stream-copy

**Comment by saudet** [comment]
It's not an option, we can use `FrameGrabber.grabPacket()` and `FrameRecorder.recordPacket()` for this as shown in this test: https://github.com/bytedeco/javacv/blob/master/samples/PacketRecorderTest.java#L53

**Comment by saudet** [comment]
BTW, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
