### ISSUE TITLE
releasing Frame object

### ISSUE THREAD

**Issue by Hosseinyzr** [bytedeco/javacv#1152]
Hi, Actually I have question.
for some reasons I want to keep an array of Frame objects. I use FFmpegFrameGrabber for extracting gif frames. and I call frame.clone to keep the original Frame.
I want to know when I am done , how can I release that Frame Objects?
is it correct just to assign each element of Frame[] to null ?

**Comment by saudet** [comment]
Yes, there is no way to deallocate them manually. But we should probably
allow users to do that instead of relying on the garbage collector.

**Comment by Hosseinyzr** [comment]
so you mean there is no way to free them?
currently I assign them to null and then call this method:
 public static void freeMemory() {
        System.runFinalization();
        Runtime.getRuntime().gc();
        System.gc();
    }

is this useful?

**Comment by saudet** [comment]
Yes, that should free them, but there are no guarantees and it affects
performance.

**Comment by saudet** [comment]
With the changes in commit https://github.com/bytedeco/javacv/commit/924f1d9ee30e0d35455cd32dbbb6711f94ab3698, we can now control the deallocation of frames using a `PointerScope` as demonstrated on this page: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

Let me know if you encounter any problems with this! Thanks

**Comment by gudduIgn** [comment]
Hey Thnak you so much for resolving this, it was a big relief for me

**Comment by gudduIgn** [comment]
hey i am still facing the memory leak issue, although memoory leak decreased  but i am still facing the issues

**Comment by saudet** [comment]
@gudduIgn You'll need to provide some details about what you're doing if you expect someone to help!

**Comment by saudet** [comment]
The changes have been released as part of JavaCV 1.5. Thanks for reporting and enjoy!

**Comment by saudet** [comment]
BTW, I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
Please give it a try with the snapshots: http://bytedeco.org/builds/
