### ISSUE TITLE
How to use --enable-libfreetype this library of FFmpeg in android/Kotlin

### ISSUE THREAD

**Issue by abdullahNagori** [bytedeco/javacv#1159]
`video_button.setOnClickListener {

            Intent(MediaStore.ACTION_VIDEO_CAPTURE).also { takeVideoIntent ->
                takeVideoIntent.resolveActivity(packageManager)?.also {
                    startActivityForResult(takeVideoIntent, REQUEST_VIDEO_CAPTURE)
                }

here is my simple video capturing code I want to add a drawtext method of FFmpeg in a video please help`

**Comment by saudet** [comment]
Use FFmpegFrameFilter as shown in other issues in this repository:
https://github.com/bytedeco/javacv/search?q=FFmpegFrameFilter+drawtext&unscoped_q=FFmpegFrameFilter+drawtext
