### ISSUE TITLE
FrameGrabber.grab() not grabbing all frames.

### ISSUE THREAD

**Issue by noahl98** [bytedeco/javacv#116]
I just updated JavaCV to 0.11 and my code stoped working. I am grabbing the frames from an mp4 file and displaying them using CanvasFrame.showImage(). This was working in the 0.10 version but is now throwing a NullPointerException. 

    public static void main(String[] args){
        FrameGrabber frameGrabber = new FFmpegFrameGrabber("/path/to/video.mp4");
        CanvasFrame canvasFrame = new CanvasFrame("Test");

        frameGrabber.start();
        for(int i = 0; i<frameGrabber.getLengthInFrames(); i++){
             canvasFrame.showImage(frameGrabber.grab());
        }
        frameGrabber.flush();
        canvasFrame.dispose();
    }

I tried checking to see if `frameGrabber.grab()` was returning `null` by adding this to the for loop.

    if(frameGrabber.grab() == null){
        System.out.println("Frame is null");
    }

But it never printed. Then I noticed in the debugger that `frameGrabber.grab()` returned an object called Frame and it had an `image` value. This is the output from when I printed the image value. 

    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    null
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    [Ljava.nio.Buffer;@38c95fbd
    null
    null
    null
    null
    null
    .......

So what seems to be happening is `frameGrabber.grab()` is only grabbing some of the frames from the video. 

Any clue as to why this is happening or how to fix it?

**Comment by ShihabSoft** [comment]
Before processing the frame,try checking for null values and discard it.

**Comment by saudet** [comment]
`FrameGrabber.grab()` would return `IplImage`, but I removed that to avoid depending on OpenCV just for a simple data type, and replaced it with `Frame`, but that can also hold audio samples, so for those frames, `Frame.image == null`, that's all.

In cases when we're not interested in the audio frames, I guess it would be practical to add a flag (maybe it could simply be `setAudioChannels(0)`?) to avoid decoding them unnecessarily, so I'll mark this as "enhancement". Thanks for reporting! If you implement the necessary functionality, be sure to send a pull request, thanks!

**Comment by Inumanoj** [comment]
I had the same issue where `FFmpegFrameGrabber.grab()` was returning a images for a few frames and null images for a few. 

I noticed that it was returning Audio in the null image frames but the `FFmpegFrameGrabber.FrameNumber` remained the same. Hence I force set the `FrameNumber` with `FFmpegFrameGrabber.setFrameNumber()` and I was able grab all frames without any null.

It might not be the best solution but I thought it might help someone.

**Comment by saudet** [comment]
New `FFmpegFrameGrabber.grabImage()` method that covers this missing functionality is now back in version 1.0. Thanks for reporting!

**Comment by chiragsheta** [comment]
Can you please tell me that how you got some of frames because i am getting null from FFmpegFrameGrabber :(

**Comment by ayeletc** [comment]
What parameter do I need to pass to "new FFmpegFrameGrabber(); " in case I am using it in an Android Studio project to grab frames from my camera device?

**Comment by saudet** [comment]
Unfortunately it doesn't look like FFmpeg supports Android cameras:
https://trac.ffmpeg.org/wiki/Capture/Webcam

**Comment by ayeletc** [comment]
Thank you for your quick response! Do you have any other suggestions? I want to extract frame by frame to create a circular buffer.

**Comment by saudet** [comment]
Yes, just use the Android API: https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by ayeletc** [comment]
I don't understand - this sample uses the FFmpegRecorder.

**Comment by saudet** [comment]
You can ignore the bit about FFmpegRecorder.
