### ISSUE TITLE
What I should do or use to see video from a bunch of frames in a byte[]?

### ISSUE THREAD

**Issue by fearchannel** [bytedeco/javacv#1164]
So, basically I have a videoBuffer (the byte[]) that I'm receiving from my camera. What should I do to get images from this?

thank u!

**Comment by saudet** [comment]
It depends on what's in the buffer. If you receive one buffer per image, it might be raw pixel values, in which case we could, for example, create instances of `Mat` around it using `BytePointer` and the known width and height. If they are images encoded in JPEG format or something, you should be able to use `imdecode()` on those again wrapped in `Mat` and `BytePointer`. If it's a video stream, you should be able to decode it with `FFmpegFrameGrabber(InputStream)` with the buffer wrapped in a `ByteArrayInputStream`. Sounds good?

**Comment by fearchannel** [comment]
I'm receiving a live stream, in this case. But there's no URL, just the Byte[]. It connects based on a protocol from that specific camera.

**Comment by saudet** [comment]
You'll need to provide more details if you expect anyone to help further.

**Comment by fearchannel** [comment]
I don't know what I can say, but anything that you need to help I'm willing to provide.

```
             byte[] frameInfo = new byte[FRAME_INFO_SIZE];
            byte[] videoBuffer = new byte[VIDEO_BUF_SIZE];
            while (true) {
                int[] frameNumber = new int[1];
                int ret = AVAPIs
                        .avRecvFrameData(avIndex, videoBuffer, VIDEO_BUF_SIZE,
                                frameInfo, FRAME_INFO_SIZE, frameNumber);
```

this is where I "get" the frames, or the raw h264. It is stored on "videoBuffer"

**Comment by saudet** [comment]
So try FFmpegFrameGrabber on them.

**Comment by fearchannel** [comment]
Right! Thanks! Any sample on that?

**Comment by saudet** [comment]
I gave you one on the mailing list. Try not to ask similar questions everywhere if you can't keep track of the replies.
