### ISSUE TITLE
How to convert G.711ulaw to aac

### ISSUE THREAD

**Issue by toskeyfine** [bytedeco/javacv#1165]
I have implemented RTSP stream forwarding RTMP stream, but the audio code in RTSP stream is G. 711ulaw, can't be convert to AAC.

**Comment by saudet** [comment]
It looks like the format name for those is "alaw" or "mulaw": 
https://ffmpeg.org/pipermail/libav-user/2016-August/009377.html
And the codec names, "pcm_alaw" or "pcm_mulaw":
https://linux.byexamples.com/archives/295/convert-audio-encoding-format-with-ffmpeg/
Try to use that!
