### ISSUE TITLE
Add audio while recording bitmap as video with FFmpegFrameRecorder

### ISSUE THREAD

**Issue by rajib3hasan** [bytedeco/javacv#1169]
Suppose i have 500 android bitmaps. I have to create a video at 60 frame rate with those bitmaps that means the video will be exactly 8.333 (500/60) seconds in length. I also have to add first 3 seconds of an audio repeatedly which is 10 seconds in length; 
I know how to make the video with FrameRecorder but i don't know how to add the music with FrameGrabber as i mentioned.

**Comment by saudet** [comment]
Just add the audio frames the same way you would add video frames, but set the values in Frame.samples instead of Frame.image.

**Comment by rajib3hasan** [comment]
i have to use like this. how can i actually do it?

for(int i =0;i<500;i++){
                    recorder.record(frameFromBitmap);
                    
                    // it increases the video length
                    // and i have to grab again the first frame if audio frame reaches 3 seconds
                    Frame audioFrame = grabber.grab();
                    recorder.record(audioFrame);
                    
                }

**Comment by saudet** [comment]
We can check the timestamp with `getTimestamp()`.

**Comment by rajib3hasan** [comment]
Thank you very much...

**Comment by rajib3hasan** [comment]
i can add audio now but video length gets increased. How to solve?

**Comment by saudet** [comment]
Make sure getTimestamp() doesn't go over the length you want.

**Comment by rajib3hasan** [comment]
here is the code

for(int i = 1; i<=500; i++){
                    Frame videoFrame = new AndroidFrameConverter().convert(bitmap);
                    videoFrame.samples = frameGrabber.grabSamples().samples;
                    recorder.record(videoFrame);
                    // as i want only 3 seconds of the music repeatedly
                    if(frameGrabber.getTimestamp()/1000 > 3000){
                        frameGrabber.setTimestamp(0);
                    }
                }

video length should be 8.333 seonds but it is alomost 12 seconds. where is the problem?

**Comment by saudet** [comment]
Like I said, make sure getTimestamp() never exceeds 8.333 seconds!

**Comment by rajib3hasan** [comment]
how can i explain you!!!!!!  I have to run the loop 500 times exactly as i want to record all 500 bitmaps. If i stop the loop when grabber.getTimeStamp() exceeds 8.333s then i have to stop at before 500.

**Comment by rajib3hasan** [comment]
I have got the solution. thank you very much.

**Comment by nitinbhanderi35** [comment]
@ZeroOneZeroR Can you please explain the solutions here?
