### ISSUE TITLE
How to maintain the same audio quality when grabbing audio frame with FFmpegFrameGrabber and then recording with FFmpegFrameRecorder

### ISSUE THREAD

**Issue by rajib3hasan** [bytedeco/javacv#1174]
Audio quality is not as good as actual audio when i grab and record.

**Comment by saudet** [comment]
Use at least the same codec and the same bitrate for reencoding.

**Comment by rajib3hasan** [comment]
some times recorder fails with codec which i get by grabber.getAudioCodec()

**Comment by saudet** [comment]
Not all audio codecs are supported, that's normal.

**Comment by rajib3hasan** [comment]
how to check if audio codec is supported or not?

**Comment by saudet** [comment]
We can use `av_codec_iterate()` for that:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/javacpp/avcodec.html#av_codec_iterate-org.bytedeco.javacpp.PointerPointer-

**Comment by rajib3hasan** [comment]
Something lkke this??? what to do then???

PointerPointer pointer = null;
                    avcodec.av_codec_iterate(pointer);

**Comment by saudet** [comment]
No, something like `PointerPointer pointer = new PointerPointer(null)`, and the rest, just as the documentation says.

**Comment by rajib3hasan** [comment]
then how to check with pointer???give an example please...

**Comment by saudet** [comment]
You don't, you read the content of the AVCodec returned.

**Comment by rajib3hasan** [comment]
This gives "Can not resolve constructor PointerPointer(null)"

**Comment by saudet** [comment]
That's a bug in your Java compiler I'm afraid, that constructor clearly exists:
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/PointerPointer.html#PointerPointer-org.bytedeco.javacpp.Pointer-

**Comment by rajib3hasan** [comment]
There is no problem using like below.... is that fine???

Pointer nullPointer = null;
                    PointerPointer pointer = new PointerPointer(nullPointer);

**Comment by saudet** [comment]
Yes, but `PointerPointer pointer = new PointerPointer((Pointer)null)` would do the same as well.
