### ISSUE TITLE
Video duration is not accurate with FFmpegFrameRecorder

### ISSUE THREAD

**Issue by rajib3hasan** [bytedeco/javacv#1179]
I have 264 frames. I have recorded those with FFmpegFrameRecorder at 60 frame rate. The video length should be 4.4(264/60) seconds but the video length is 4.38. what is the problem???

**Comment by rajib3hasan** [comment]
video length is always 0.02seconds less than actual length for all lengths

**Comment by saudet** [comment]
This is a duplicate of issue #1069, please upgrade your version of JavaCV.

But there's probably a similar issue for audio, so let's set that deprecated variable for audio codecs too.

**Comment by rajib3hasan** [comment]
okay....that has been solved... but adding audio with frame grabber increases the video length even though i checked audio grabber time stamp is not greater than reocrder time stamp....

**Comment by saudet** [comment]
You need to check the timestamp of the recorder, not the grabber.

**Comment by rajib3hasan** [comment]
thank you...
