### ISSUE TITLE
So confused by the samples

### ISSUE THREAD

**Issue by haogg** [bytedeco/javacv#118]
First ,thanks for the great works from @saudet  and his 'bro'.
But i  am  so  puzzled  to build a  AS or Eclipse project with   the provided '.java's and jars.
I worked all afternoon for that . I failed.
I think other guys may also come across this problem.
So, @saudet ,** I think it is a better way to provide a complete AS or eclipse project in the directory `sample`**

**Comment by saudet** [comment]
Sure, that could be an enhancement. Please send a pull request when you have something, thanks!

**Comment by saudet** [comment]
I've since added a new https://github.com/bytedeco/sample-projects repository to fulfill this need, so let's have more specific discussions about sample projects there! Thanks for the suggestion and your contribution!
