### ISSUE TITLE
Calling stop() of FFmpegFrameRecorder hangs the thread

### ISSUE THREAD

**Issue by rajib3hasan** [bytedeco/javacv#1181]
If FFmpegFrameRecorder fails to record frame then calling stop() hangs the thread. What is the reason and what to do?

**Comment by saudet** [comment]
Could you give an example?

**Comment by rajib3hasan** [comment]
I am grabbing an audio frame with FFmpeagFrameGrabber, then giving it fade with FFmpegFrameFilter, then recording it after recording a android bitmap frame. But it gives error "avcodec_encode_video2() error -542398533: Could not encode video packet". Then i call recorder.stop() . but no lines of code are executing after calling stop of recorder. but calling stop() and release of grabber and filter seems okay.

**Comment by saudet** [comment]
That sounds like an issue with the codec. Try to call `setOption("thread", "1")` before `start()`.

**Comment by saudet** [comment]
As well as `setVideoOption("threads", "1")`

**Comment by rajib3hasan** [comment]
what does setOption("thread", "1") do??? i am accessing recorder from multiple thread. Will there be any problem???

**Comment by saudet** [comment]
It disables multithreading. Some codecs like libx264 are known to have issues like that with threads.

**Comment by rajib3hasan** [comment]
i am accessing recorder from multiple thread. Will there be any problem???

**Comment by saudet** [comment]
Probably, yes, but make sure to use the latest version: http://bytedeco.org/builds/

**Comment by saudet** [comment]
I mean, it is OK to use multiple recorders on multiple threads as long as you do not let the codecs use multithreading themselves, or use the same recorder from multiple threads.

**Comment by rajib3hasan** [comment]
okay no problem...

**Comment by rajib3hasan** [comment]
Oh man !!!!!!!!!!!!!!!!!!!!!  setOption("thread", "1") and setVideoOption("threads", "1") makes recording processing 3 times slower ..... i am going to use these.... i will not call recorder.stop() if recorder fails to record. I will only release ...
