### ISSUE TITLE
How to cancel audio input in FFmpegFrameGrabber

### ISSUE THREAD

**Issue by cndota123** [bytedeco/javacv#1184]
I found the following exception when the audio input format is none
```
org.bytedeco.javacv.FrameGrabber$Exception: avcodec_find_decoder() error: Unsupported audio format or code not found: 0
```
But I don't need audio input,I tried the following code but it didn't work.
```
grabber.setAudioCodec(avcodec.AV_CODEC_ID_NONE);
grabber.setAudioChannels(0);
```
In addition, the setOption method requires a key-value,is there an implementation method for the parameter -an in FFmpeg?
Thanks.

**Comment by saudet** [comment]
Just calling `grabImage()` instead of `grab()` should work for that.

**Comment by saudet** [comment]
Although I see this fails during `start()`. We can set a non-existing audio stream such as `setAudioStream(Integer.MAX_VALUE)`. That should disable anything related to audio.

**Comment by cndota123** [comment]
He is working correctly, thank you
