### ISSUE TITLE
where is the old builds

### ISSUE THREAD

**Issue by linghushaoxia** [bytedeco/javacv#1187]
Hi，
I found that the old builds in the maven repo, is deleted,Why?

**Comment by saudet** [comment]
Because version 1.5 was released: http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/

**Comment by linghushaoxia** [comment]
Thanks！the new version has many changes.
but if i want to use the old version，where can i find it or build it myself？

**Comment by saudet** [comment]
The old versions are still available on Maven: https://search.maven.org/search?q=bytedeco

**Comment by linghushaoxia** [comment]
well... thanks, the old ones are in  the maven repos, indeed.
There is some intersting errors. Now I really find the old builds; however, about a month ago, I really found nothing beside the 1.5 . May be,  I  was in a dream...
