### ISSUE TITLE
Looks like vaapi is not enabled in ffmpeg build for linux

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1188]
Is there a reason why this is not enabled?

**Comment by saudet** [comment]
Yes, it doesn't work with CentOS 6. EOL is November 30, 2020, so at that point, it will become part of the default builds. In the meantime, contributions for custom builds as a "-gpu" extension as per the presets for Caffe, OpenCV, MXNet, or TensorFlow are welcome.

**Comment by b005t3r** [comment]
OK, understood, thanks for the explanation.

**Comment by saudet** [comment]
It seems like it would be possible to build from source and bundle a recent version of libva:
https://github.com/intel/libva
Would you like to give this a try?

**Comment by b005t3r** [comment]
Maybe I will, at some point, once everything else in my project is ready, but I need to focus on other things right now.

**Comment by saudet** [comment]
FFmpeg is now getting built with CentOS 7, so this gets enabled by default.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
This now gets bundled starting with JavaCV 1.5.7. Enjoy!
