### ISSUE TITLE
Embed Stream in JPanel

### ISSUE THREAD

**Issue by MarcWoodyard** [bytedeco/javacv#1190]
Is there a way to embed an HTTP or RTSP stream in a JPanel?

**Comment by saudet** [comment]
Sure, just display the images in them.

**Comment by saudet** [comment]
There's an example using JavaFX here:
https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java
But we can do the same with Java 2D:
https://docs.oracle.com/javase/tutorial/2d/images/drawimage.html
