### ISSUE TITLE
FFmpegFrameRecorder setVideoOption

### ISSUE THREAD

**Issue by wangpeng1** [bytedeco/javacv#1193]
recorder.setVideoOption("rtbufsize ", "1M");
recorder.setVideoOption("buf_size", "240000");
recorder.setVideoOption("audio_buffer_size", "10");

these params if can use?

**Comment by saudet** [comment]
Maybe, check the options available for the codec you need to use here:
https://ffmpeg.org/ffmpeg-codecs.html

**Comment by saudet** [comment]
BTW, it's also possible to set these format and protocol options with `setOption()`:
https://ffmpeg.org/ffmpeg-formats.html
https://ffmpeg.org/ffmpeg-protocols.html

**Comment by ashishgupta-mca** [comment]
ffmpeg -f dshow -rtbufsize 100M -i ...

How can I ensure that rtbufsize option get set before input? Is setOption work for this?
