### ISSUE TITLE
How to run OpenCVFaceRecognizer.java on Android?

### ISSUE THREAD

**Issue by Inzimam-Tariq** [bytedeco/javacv#1196]
Hi I have configured the JavaCV in Android Studio and run the `FacePreview.java` it worked fine. Now I'm trying to run the `OpenCVFaceRecognizer.java` in my Android project But It doesn't seem to work. When I paste the sample code in `onCreate` method, on every Object Android Studio suggest imports from two packages like for `FaceRecognizer` class it suggest me to import from `org.opencv.face` or from `org.bytedeco.javacpp`. As I'm using JavaCV so I think most relevant is `org.bytedeco.javacpp` But I can not access train & predict method like when I use `faceRecognizer.train(images,labels);` IDE says `Cannot resolve symbol 'train'`. Then I tried to import from other package too. The result is same. Beside the train & predict methods My program also giving error on for loop it says "unexpected token".
I'm using the below in my gradle.build file
`implementation project(':openCVLibrary41')

    implementation 'org.bytedeco:javacv:1.4.4'
    implementation 'org.bytedeco.javacpp-presets:opencv:4.0.1-1.4.4:android-arm64'
    implementation 'org.bytedeco.javacpp-presets:ffmpeg:4.1-1.4.4:android-arm64'

    implementation files('libs/javacpp.jar')
    implementation files('libs/javacv.jar')
    implementation files('libs/opencv.jar')
    implementation files('libs/opencv-android-arm.jar')
    implementation files('libs/opencv-android-x86.jar')
    implementation files('libs/ffmpeg.jar')
    implementation files('libs/ffmpeg-android-arm.jar')
    implementation files('libs/ffmpeg-android-x86.jar')`

I suppose If the `FacePreview.java` worked fine so this should also be. Can you please point out what I'm doing wrong? OR suggest me how to run it in android studio.
Thanks

**Comment by saudet** [comment]
The API has changed a bit and you're using an old version.
Please upgrade to JavaCV 1.5: http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/
