### ISSUE TITLE
how can i use version1.5 in AndroidStudio,

### ISSUE THREAD

**Issue by qfsun** [bytedeco/javacv#1197]
1.4.4 is ok.
use 1.5,in Androidstudio jvm point “ finished with non-zero exit value 1”,but just as java project is running ok.
in a new  project just add this jar file, is on error too.
i tried to user "compileOnly" for jar, also useless.

**Comment by saudet** [comment]
It works fine with Android Studio, just be sure to use the latest version.

**Comment by qfsun** [comment]
I tried to delete jar file "META_INF/versions" the whole directory ,then AndroidStudio works fine. Otherwise jvm build failed.
Are there is necessary for the Jar?

**Comment by saudet** [comment]
No, Android doesn't need them. We can delete them, that's fine.
