### ISSUE TITLE
Build small ffmpeg so files for android

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1199]
Hi 

I want to make the apk file size less, one way is to reduce the ffmpeg so file size. 

So i just build FFMPEG for android platform, then replace the so files?

**Comment by saudet** [comment]
Just rebuild the JAR files, they contain everything.

**Comment by saudet** [comment]
Build instructions are here:
https://github.com/bytedeco/javacpp-presets/#build-instructions
Let me know if you have any issues with that!
