### ISSUE TITLE
AndroidFrameConverter slow

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1201]
As you mentioned in the api doc, AndroidFrameConverter.convert() is slow, is there any recommendation to speed up?  basically i need bitmap from grabFrame(), is it possible to add method grabBitmap(), and internally using libyuv to convert YUV to bitmap?

**Comment by saudet** [comment]
Try to do as mentioned in the docs:
> This class is not optimized for speed. For best performance, convert first your data to and from RGBA with optimized functions from FFmpeg or OpenCV. Further, pixel formats other than grayscale, BGR, and RGBA are not well supported. Their conversions might fail in undefined ways.

http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/AndroidFrameConverter.html

**Comment by xiaos** [comment]
what optimized functions from ffmpeg can do this?

**Comment by saudet** [comment]
Since it sounds like you're using `FFmpegFrameGrabber`, try to call `setPixelFormat(AV_PIX_FMT_RGBA)` before `start()`.

**Comment by xiaos** [comment]
thanks, it's better, but still slower than iplimage.  Is this because that memory copy from avframe to android bitmap? for iplimage, they are shareing the same memory?

**Comment by saudet** [comment]
I'm not sure what you're comparing against, but OpenCV doesn't have
anything to decode a video.

**Comment by xiaos** [comment]
comparing:

1. - convert ffmpeg avfram to android bitmap
2. - convert ffmpeg avframe to opencv iplimage

The 2nd is faster than 1st.

**Comment by saudet** [comment]
That's normal, we can't reuse existing buffers with Bitmap, data needs to
be copied.

**Comment by xiaos** [comment]
understood, and thank you.
