### ISSUE TITLE
FFmpegFrameRecorder records audio to the beginning of the output

### ISSUE THREAD

**Issue by voidedWarranties** [bytedeco/javacv#1204]
In the example of https://gist.github.com/voidedWarranties/7b08ff7b1c2954f52f2337653f690481, the beep which is expected to happen when the circle is present on the screen, the recorder records the beep audio to the beginning of the output video.

I assume this happens because no audio is recorded before the beep is expected to happen.

Example output: https://youtu.be/cw0RoVfpgY8

**Comment by saudet** [comment]
You'll need to record the same amount of time for both audio and video streams, but we can record silence with frames full of zeros, for example, that's fine.

**Comment by voidedWarranties** [comment]
Solution:
`ShortBuffer silence = ShortBuffer.allocate((int)((recorder.getAudioChannels()*recorder.getSampleRate())/recorder.getFrameRate()));`

Create enough silence for one second on each channel, then split it into the correct framerate.

Thanks for your help!
