### ISSUE TITLE
Why FFmpegFrameGrabber.start is synchronized to class org.bytedeco.ffmpeg.global.avcodec.class

### ISSUE THREAD

**Issue by zoyaforever** [bytedeco/javacv#1205]
hi @saudet 
I want to use multiple FFmpegFrameGrabbers simultaneously(for eample: 12) to receive video from network by RTMP protocol. But I find that start method is synchronized to a class which caused I have to start it one by one?

```java
    public void start() throws Exception {
        synchronized (org.bytedeco.ffmpeg.global.avcodec.class) {
            startUnsafe();
        }
    }
```

**Comment by saudet** [comment]
Call startUnsafe() instead of start(), that's what it's for.

**Comment by saudet** [comment]
For more information about that, please refer to the thread at issue #1139.

**Comment by zoyaforever** [comment]
@saudet 
But I can run multiple FFmpegFrameGrabbers with startUnsafe successfully.
Only sometimes I got the error -22. In that case, I stop it, and then restart it.
