### ISSUE TITLE
Could not initialize class org.bytedeco.ffmpeg.global.avutil

### ISSUE THREAD

**Issue by feiyangsuo** [bytedeco/javacv#1206]
I was trying to access to some web video and catch some frames from it, with code below. 
```
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber;
import org.bytedeco.ffmpeg.global.avutil;

public class Main {
    public static void main(String[] args) throws FrameGrabber.Exception {
        String path = "rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov";
        FFmpegFrameGrabber mFrameGrabber = new FFmpegFrameGrabber(path);
        mFrameGrabber.setPixelFormat(avutil.AV_PIX_FMT_RGBA);
        mFrameGrabber.setOption("fflags", "nobuffer"); //Is this essential?
        mFrameGrabber.start();
        Frame mFrame;
        while(true){
            mFrame = mFrameGrabber.grab();
            // process the image
        }
    }
}
```
When I tired to run it, the compiler raised no error, but as the excution reached line 9 "FFmpegFrameGrabber mFrameGrabber = new FFmpegFrameGrabber(path);",  there comes error:
 ```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1006)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:44)
	at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:313)
	at Main.main(Main.java:9)
```
The class avutil does exist in the declared path, I don't know why there's still an error like this. Could any help be offered? Thanks.

**Comment by saudet** [comment]
You'll need to put **all** the JAR files in your class path for this to work.

**Comment by feiyangsuo** [comment]
> You'll need to put **all** the JAR files in your class path for this to work.

Problem solved! Thank you :)

**Comment by SehgalDivij** [comment]
how to do that @saudet  @feiyangsuo? Please help

**Comment by saudet** [comment]
@SehgalDivij It depends on your environment: 
https://github.com/bytedeco/javacv/#manual-installation

**Comment by SehgalDivij** [comment]
yep yep. Got that.
But my build fails now.

**Comment by saudet** [comment]
If you need help putting JAR files in the class path, here is not the place to ask.

**Comment by SehgalDivij** [comment]
JAR Files are in the class path. Back to android after very long time. Zoned out for a bit.

After following directions as stated. I get this error during build.

    package org.bytedeco.opencv.opencv_core does not exist.

```javacv``` and ```javacpp``` are both accessible. Only opencv is not accessible.

**Comment by saudet** [comment]
So you have JAR files missing from the class path. Go check that again, that's the only explanation.

**Comment by SehgalDivij** [comment]
![image](https://user-images.githubusercontent.com/17740040/63496608-d7df5680-c4df-11e9-8c4f-3e7c39071a74.png)
Contents of the libs folder.

**Comment by SehgalDivij** [comment]
I copied everything into the libs folder.

**Comment by SehgalDivij** [comment]
It seems I have a rather old version of javaCV. I'll find a newer version and try to work with it.

**Comment by SehgalDivij** [comment]
Fixed it. Was using an older version.

**Comment by Naco88** [comment]
I am now having this same issue. I am trying to use javacv-platform with Katalon. All Jar files are in the class path and are all up to date so this issue 

`FFmpegFrameGrabber g = new FFmpegFrameGrabber("D:\\test.mp4");`

In my classpath I have the following: (along with a few others) 
```
<classpathentry kind="lib" path="C:/Users/GBPerryA/Katalon Studio/OpenCVTest/Drivers/opencv-4.0.1-1.5.jar"/>
<classpathentry kind="lib" path="C:/Users/GBPerryA/Katalon Studio/OpenCVTest/Drivers/ffmpeg-4.1.3-1.5.jar"/>
<classpathentry kind="lib" path="C:/Users/GBPerryA/Katalon Studio/OpenCVTest/Drivers/javacpp-1.5.jar"/>
<classpathentry kind="lib" path="C:/Users/GBPerryA/Katalon Studio/OpenCVTest/Drivers/javacv-1.5.4.jar"/>
<classpathentry kind="lib" path="C:/Users/GBPerryA/Katalon Studio/OpenCVTest/Drivers/javacv-platform-1.5.jar"/>
```

Issue:
`java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
	at org.bytedeco.javacpp.Loader.load(Loader.java:1006)
	at org.bytedeco.javacpp.Loader.load(Loader.java:947)
	at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:44)
	at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:355)
	at New Test Case.run(New Test Case:34)`

I am fairly new to Java so apologies if I am missing something blatantly obvious. I have tried to fix this for a few hours and seen all the other issues with the same error but had no luck. I can give any more info if needed.

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.4.

**Comment by Noone-No** [comment]
1. Check Pom dependency and version
2. Check you Jdk ,Do not use Zulu JDK or Other JDK , this is very  important
