### ISSUE TITLE
OOM when call convertToIplImage()

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1208]
I am using OpenCVFrameConverter.convertToIplImage() to convert a frame to iplimage.

  public IplImage convertToIplImage(Frame frame) {
        if (frame == null || frame.image == null) {
            return null;
        } else if (frame.opaque instanceof IplImage) {
            return (IplImage)frame.opaque;
        } else if (!isEqual(frame, img)) {
            int depth = getIplImageDepth(frame.imageDepth);
            img = depth < 0 ? null : IplImage.create(frame.imageWidth, frame.imageHeight, depth, frame.imageChannels, new Pointer(frame.image[0].position(0)))
                    .widthStep(frame.imageStride * Math.abs(frame.imageDepth) / 8)
                    .imageSize(frame.image[0].capacity() * Math.abs(frame.imageDepth) / 8);
        }
        return img;
    }

I found some out of memory issue.   the issue happened when call IplImage.create(frame.imageWidth, frame.imageHeight, depth, frame.imageChannels, new Pointer(frame.image[0].position(0)))

**Comment by xiaos** [comment]
Non-fatal Exception: java.lang.OutOfMemoryError
Physical memory usage is too high: physicalBytes (566M) > maxPhysicalBytes (530M)
keyboard_arrow_up
arrow_right
org.bytedeco.javacpp.Pointer.deallocator (Pointer.java:585)
org.bytedeco.javacpp.Pointer.init (Pointer.java:125)
org.bytedeco.opencv.global.opencv_core.cvSize (opencv_core.java)
org.bytedeco.opencv.opencv_core.AbstractIplImage.createHeader
(AbstractIplImage.java:71)
org.bytedeco.opencv.opencv_core.AbstractIplImage.create (AbstractIplImage.java:101)
org.bytedeco.javacv.OpenCVFrameConverter.convertToIplImage
(OpenCVFrameConverter.java:103)

**Comment by saudet** [comment]
Increase the maximum heap size of the JVM with, for example, the `java -Xmx` option.

**Comment by xiaos** [comment]
Is there any momory leak here?

**Comment by saudet** [comment]
If you're on Android, make sure to enable "largeHeap". See issue #1203.

If there is a memory leak, let me know, and we'll fix it.

**Comment by xiaos** [comment]
i am developing android, and it's (largeHeap) enabled already. I saw some cases, it used up to 1024M memory on phones.

**Comment by saudet** [comment]
That's not necessarily a lot of memory for image processing.

**Comment by saudet** [comment]
It's also possible to disable that check by setting the "org.bytedeco.javacpp.maxphysicalbytes" system property to "0".
