### ISSUE TITLE
Draw Contours having IplImage and CvArr conflict issue

### ISSUE THREAD

**Issue by ahsandar** [bytedeco/javacv#121]
Using following code from the examples but the following error is being thrown, any one got any ideas how to solve this ?      
     
    def drawContours(image: IplImage, contours: Seq[CvSeq]): IplImage = {
        contours.foreach(cvDrawContours(image, _, colourRandom, colourRandom, -1, 1, CV_AA, cvPoint(0, 0)))
       image
     }
<br/>

    overloaded method value cvDrawContours with alternatives:
    [error]   (x$1: org.bytedeco.javacpp.helper.opencv_core.CvArr,x$2:    org.bytedeco.javacpp.opencv_core.CvSeq,x$3: org.bytedeco.javacpp.opencv_core.CvScalar,x$4:   org.bytedeco.javacpp.opencv_core.CvScalar,x$5: Int,x$6: Int,x$7: Int,x$8: Array[Int])Unit <and>
    [error]   (x$1: org.bytedeco.javacpp.helper.opencv_core.CvArr,x$2: org.bytedeco.javacpp.opencv_core.CvSeq,x$3: org.bytedeco.javacpp.opencv_core.CvScalar,x$4: org.bytedeco.javacpp.opencv_core.CvScalar,x$5: Int,x$6: Int,x$7: Int,x$8: java.nio.IntBuffer)Unit <and>
    [error]   (x$1: org.bytedeco.javacpp.helper.opencv_core.CvArr,x$2: org.bytedeco.javacpp.opencv_core.CvSeq,x$3: org.bytedeco.javacpp.opencv_core.CvScalar,x$4: org.bytedeco.javacpp.opencv_core.CvScalar,x$5: Int,x$6: Int,x$7: Int,x$8: org.bytedeco.javacpp.opencv_core.CvPoint)Unit
    [error]  cannot be applied to (org.bytedeco.javacpp.opencv_core.IplImage, org.bytedeco.javacpp.opencv_core.CvSeq, org.bytedeco.javacpp.opencv_core.Scalar, org.bytedeco.javacpp.opencv_core.Scalar, Int, Int, Int, org.bytedeco.javacpp.opencv_core.CvPoint)
    [error]       contours.foreach(cvDrawContours(image, _, colourRandom, colourRandom, -1, 1, CV_AA, cvPoint(0, 0)))

**Comment by jpsacha** [comment]
Please see answer to the same question in [javacv-examples issues #2](https://github.com/bytedeco/javacv-examples/issues/2).

**Comment by ahsandar** [comment]
Cheers, this worked
