### ISSUE TITLE
Problem with FFmpegFrameGrabber load RTSP video stream

### ISSUE THREAD

**Issue by arthad1995** [bytedeco/javacv#1210]
Try to test how to load RTSP video stream my code is like this:

`private FFmpegFrameGrabber grabber = null;
  grabber = new FFmpegFrameGrabber("rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"); // rtsp url
        grabber.setFrameRate(30);
        grabber.setImageWidth(240);
        try {
            grabber.start();
            System.out.println(grabber.grabFrame().imageHeight +"***********************");
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }
`
and got error:
`W/System.err: org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov". (Has setFormat() been called?)`

I tried 
`grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);`
`grabber.setFormat("mp4");  //also tried mov`
both of them didn't work
This public server and that is working in my VLC, can anyone help me with this?

**Comment by saudet** [comment]
Try to call setFormat() before start().

**Comment by arthad1995** [comment]
@saudet I tried
`grabber.setFormat("mp4"); //also tried mov`
Maybe I didn't the format right?

**Comment by saudet** [comment]
What's the error it displays in the log on the console?

**Comment by arthad1995** [comment]
> What's the error it displays in the log on the console?

`I/art: Background partial concurrent mark sweep GC freed 271164(15MB) AllocSpace objects, 4(4MB) LOS objects, 28% free, 10MB/14MB, paused 1.278ms total 202.674ms
W/System.err: org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov". (Has setFormat() been called?)
        at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:822)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:758)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:39)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/: HostConnection::get() New Host Connection established 0xa0cd8bc0, tid 11343
D/: HostConnection::get() New Host Connection established 0xaa87ba40, tid 11392
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
`

Those are error, I doubt because this stream is not in the format that FFmepegFrameGrabber like? I can open local file by this code. Could you test this public server see if that works on your side?

**Comment by saudet** [comment]
Since it's not showing up, make sure to call FFmpegLogCallback.set()
somewhere on init.

**Comment by arthad1995** [comment]
> Since it's not showing up, make sure to call FFmpegLogCallback.set() somewhere on init.

what is FFmpegLogCallback.set() doing? I am using my local computer as server, and that works in my Lan. How should I put the address to FFmpegFrameGrabber, the one I used before is taking a string, which is file path, but I am not using file in this case. I doubt I need to give a InputStream, I tried use URL, but URL doesn't know rtsp protocol

**Comment by arthad1995** [comment]
> Since it's not showing up, make sure to call FFmpegLogCallback.set() somewhere on init.

I think this log is important, and I didn't notice that before:

`W/System.err: Error: [tcp @ 0xa0c170a0] Connection to tcp://ipaddress:8554?timeout=0 failed: Permission denied
    Error: [tcp @ 0xa0c170a0] Connection to tcp://ipaddress:8554?timeout=0 failed: Permission denied
    org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -13: Could not open input "rtsp://ipaddress:8554/". (Has setFormat() been called?)`

It keep using tcp instead of rtsp even though I did   `grabber.setOption("rtsp_transport", "tcp");`

**Comment by saudet** [comment]
That's just because you forgot to add some permissions to your application:
https://stackoverflow.com/questions/6586443/android-tcp-permission-denied-error
