### ISSUE TITLE
In WebcamAndMicrophoneCapture Error with audio

### ISSUE THREAD

**Issue by PradeepSimba** [bytedeco/javacv#1211]
I reffered WebcamAndMicrophoneCapture code in this link: https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java

But, I have some errors with this code.

output:
Exception: avio_open2 error() error -5: Could not open 'null'
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:858)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:387)
	at w.WebcamAndMicrophoneCapture.main(WebcamAndMicrophoneCapture.java:100)
BUILD FAILURE

How can I solve this?
help me!!!

**Comment by saudet** [comment]
You'll need to update this line to an existing path or server:
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java#L66

**Comment by PradeepSimba** [comment]
how can i update this lines.
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java#L66
