### ISSUE TITLE
Seeking to specific position of video with android VideoView is not working. 

### ISSUE THREAD

**Issue by rajib3hasan** [bytedeco/javacv#1212]
What is the reason???. Is this key frame related??? how to use key frame of frame...

**Comment by saudet** [comment]
How are you calling setTimestamp()?

**Comment by rajib3hasan** [comment]
i am not calling setTimeStamp(). i just call recorder.record(frame);

**Comment by saudet** [comment]
Are out trying to play a video created with FFmpegFrameRecorder?

**Comment by rajib3hasan** [comment]
yeah.....

**Comment by rajib3hasan** [comment]
how can i make every frame  key frame so that i can seek every position of video...

**Comment by saudet** [comment]
We can set the GOP size to 1 to achieve this, for example, with the `keyint_min` option in the case of libx264: https://ffmpeg.org/ffmpeg-codecs.html#libx264_002c-libx264rgb

**Comment by rajib3hasan** [comment]
okay... but what is the full form of  GOP?

**Comment by rajib3hasan** [comment]
Thank you man.....it is working for now :)

**Comment by saudet** [comment]
Sorry, the correct option is `keyint`, that's what you need to change with `setVideoOption("keyint", "1")`.

**Comment by rajib3hasan** [comment]
but  `recorder.setGopSize(1)` is also working . what is the difference???

**Comment by rajib3hasan** [comment]
`recorder.setGopSize(1)` increases the video size so much...

**Comment by rajib3hasan** [comment]
`setVideoOption("keyint", "1")` is not working...

**Comment by saudet** [comment]
Maybe it's "g", like `setVideoOption("g", "1")`? Anyway `setGopSize()` also works in general, yes :)

**Comment by rajib3hasan** [comment]
`setGopSize(gopSize) ` works but video size increases with gopSize reversly....

**Comment by rajib3hasan** [comment]
`setVideoOption("g", "1")` also works but increase size by 3 times as `setGopSize(gopSize)` . Is there any solution to reduce size???

**Comment by saudet** [comment]
Set the bitrate you're looking for.
