### ISSUE TITLE
Super confusing Scalar constructors

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1224]
There are two, very easily to confuse, constructors in `org.bytedeco.opencv.opencv_core.Scalar`:

```java
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public Scalar(long size) { super((Pointer)null); allocateArray(size); }
```

and

```java
    public Scalar(double v0) { super((Pointer)null); allocate(v0); }
```

I wasted some time yesterday trying to figure out why my code does not draw the right shapes and finally noticed that I was creating white color using `new Scalar(255)` instead of `new Scalar(255.0)`.

I'd suggest making the `public Scalar(long size)` constructor `private` and replacing it with a static factory method to avoid this madness I had to go through.

**Comment by saudet** [comment]
These constructors are now all gone with version 1.5.1. There doesn't appear to be any classes in all the presets that are both meant to be used as part of arrays and have constructors with a single real value. Thanks for the suggestion!
