### ISSUE TITLE
How to perform Frame Interpolation ?

### ISSUE THREAD

**Issue by rajib3hasan** [bytedeco/javacv#1230]
How to perform frame interpolation to make transition smooth at 30 fps?

**Comment by saudet** [comment]
There's probably a filter for that somehow:
https://ffmpeg.org/ffmpeg-filters.html

**Comment by saudet** [comment]
It sounds like what you're looking for is this one:
https://ffmpeg.org/ffmpeg-filters.html#minterpolate

There's a couple of examples on this wiki page:
https://trac.ffmpeg.org/wiki/How%20to%20speed%20up%20/%20slow%20down%20a%20video
