### ISSUE TITLE
Unsupported format or combination of formats

### ISSUE THREAD

**Issue by uy711591** [bytedeco/javacv#1231]
Hello, I am working on a project which consists of the deployment of security devices such as a barrier and an electromagnetic lock to control the access of a facility.

I am looking developing an application and I'm having a problem with the FaceRecognizer class. I am having a hard time trying to add some training data, PGM files I generate using the Open Cv library.
I have the following errors when I train my FaceRecognizer.

(-210:Unsupported format or combination of formats) In the Fisherfaces method, all input samples (training images) must be of equal size! Expected 78400 pixels, but was 0 pixels. in function 'cv::face::Fisherfaces::train'

I am confused because I generate 8-bit grey levels PGM files with a size of 92x112.
Please help me figure out the problem I have.
Thank you !

**Comment by saudet** [comment]
Your issue isn't related to PGM files. Just use code that looks like this and it will work:
https://github.com/bytedeco/javacv/blob/master/samples/OpenCVFaceRecognizer.java
