### ISSUE TITLE
Can't use FFmpegFrameGrabber with video stream

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1232]
I'm streaming locally, like so:

`ffmpeg -stream_loop -1 -i file.mp4 -vcodec copy -acodec copy -f mpegts tcp://127.0.0.1:9090?listen`

And the grabber is configured like so:

```java
            grabber = new FFmpegFrameGrabber("tcp://127.0.0.1:9090");
            grabber.setVideoOption("threads", "0"); // use optimal number of threads for the selected codec
            grabber.setImageWidth(width);
            grabber.setImageHeight(height);
            grabber.setPixelFormat(PIXEL_FORMAT);
            grabber.setImageScalingFlags(SWS_BICUBIC);
            grabber.setFormat("mpegts");
``` 

It works with a file (without `grabber.setFormat("mpegts");`), but when I try to use it with a stream, I get this:

`avformat_open_input() error -61: Could not open input "tcp://127.0.0.1:9090". (Has setFormat() been called?)`

**Comment by saudet** [comment]
You're not using the same URL. You'll need to use the same URL if you
expect it to behave the same.

**Comment by b005t3r** [comment]
URLs are correct, they are basically straight from the ffmpeg examples (https://www.ffmpeg.org/ffmpeg-protocols.html#tcp) and it does work, when I try to connect with `ffplay`, like so:

`ffplay tcp://127.0.0.1:9090`

I you were talking about he `?listen` part it's just a param to make ffmpeg wait and start streaming once a client connects.

FFmpegFrameGrabber also connects just fine (hence the URL is correct), but it crashes after that with the exception I showed.

**Comment by b005t3r** [comment]
OK, I think I found the problem on my side - before calling `start()` on grabber, I call this:

```java
        formatCtx = avformat_alloc_context();
        avformat_open_input(formatCtx, path, null, null);
        avformat_find_stream_info(formatCtx, (AVDictionary) null);
```

to get the stream format. It works fine with files, but I'll have to figure out something different for streams.

**Comment by saudet** [comment]
I see, it should work fine with streams as well. What are the messages it outputs to the log?

**Comment by saudet** [comment]
Since your copying an "mp4" file though, you'll probably need to call `setFormat("mp4")`, not "mpegts".

**Comment by b005t3r** [comment]
I'm actually copying both video and audio streams and wrapping these into mpeg transport stream container, so this is probably the safest way to do things. I tested with a simple app which just decodes and encodes the video and it works with this format just fine (there's actually no need to call anything to set the format, as it can get it from the stream). 

Anyway, the problem is I'm calling `avformat_open_input()` on this stream before starting the grabber, which also at some point calls `avformat_open_input()` and since the stream already started it crashes. I'll have to fix it somehow on my side, so you can close this issue, it was just a false alarm (I was mislead by the exception, as it says to make sure `setFormat()` has been called and I was already doing that).

**Comment by saudet** [comment]
Ah, I see, yes that wouldn't work. Anyway, the `AVFormatContext` object is available after `start()` via the `getFormatContext()` method. Is there something more that you would need?

**Comment by b005t3r** [comment]
No, I'm good. Thanks for the help.
