### ISSUE TITLE
if FFmpegFrameGrabberSimple(inputStream) not use grabber.setFrameNumber(num)

### ISSUE THREAD

**Issue by duck123456** [bytedeco/javacv#1234]
ByteArrayInputStream inputStream= new ByteArrayInputStream(inputBytes);

        FFmpegFrameGrabberSimple grabber=new FFmpegFrameGrabberSimple(inputStream);
        grabber.start();
        log.info("===>>"+grabber.getLengthInTime());  this is 0
        Frame frame=null;
        int index=0;
        AVPacket pkt=null;
        while(true){
        grabber.setFrameNumber(index);
 
            frame=  grabber.grabFrame(false,true,true,false);
  
          index+=38;

        }

Caused by: org.bytedeco.javacv.FrameGrabber$Exception: avformat_seek_file() error -1: Could not seek file to timestamp 2920000.

https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L619

https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L812-L814

if use avformat_alloc_context AND avio_alloc_context to  Allocating memory will not seek frames

thanks

**Comment by saudet** [comment]
setFrameNumber() won't work well for streams with variable frame rates. Try
to use setTimestamp() instead.

**Comment by duck123456** [comment]
> setFrameNumber() won't work well for streams with variable frame rates. Try to use setTimestamp() instead.
The same problem !

**Comment by saudet** [comment]
Well, you'll need to give me something to reproduce this issue if you expect some help.

**Comment by duck123456** [comment]
public static void main(String[] args) throws FileNotFoundException, FrameGrabber.Exception {
        File file=new File("C:\\Users\\x1c\\Desktop\\temp\\49\\pp\\zao_17.ts");
        InputStream inputStream= new FileInputStream(file);
        FFmpegFrameGrabber grabber=new FFmpegFrameGrabber(inputStream);
        grabber.start();
        grabber.setFrameNumber(5);
        Frame frame= grabber.grabFrame(false,true,true,false);
         
    }
this simple demo can reproduce the problem! you can try it ! thanks

**Comment by saudet** [comment]
Ah, that's the problem. `.ts` files don't have an index. You'll need to convert that to something else first.

**Comment by duck123456** [comment]
> Ah, that's the problem. `.ts` files don't have an index. You'll need to convert that to something else first.

good! thanks

**Comment by duck123456** [comment]
public static void main(String[] args) throws FileNotFoundException, FrameGrabber.Exception {
    File file=new File("C:\\Users\\x1c\\Desktop\\temp\\49\\pp\\zao_17.ts");
    FFmpegFrameGrabber grabber=new FFmpegFrameGrabber(file);
    grabber.start();
    grabber.setFrameNumber(5);
    Frame frame= grabber.grabFrame(false,true,true,false);
}

.ts files don't have an index，why InputStream   Instead of File is normal ?

**Comment by saudet** [comment]
Either work the same for me. I'll need something to reproduce that if it doesn't work for you for some reason.

**Comment by duck123456** [comment]
> Either work the same for me. I'll need something to reproduce that if it doesn't work for you for some reason.

.ts file doesn't work,but .mp4  file is normal ! I found that avformat_find_stream_info() doesn't work by .ts file! Either  work the same for me!but it work no same! It's confusing to me

**Comment by saudet** [comment]
You're right, it isn't working the same for MPEG-TS. It feels like there is a bug in FFmpeg somewhere there, and should probably be reported upstream...

**Comment by duck123456** [comment]
> You're right, it isn't working the same for MPEG-TS. It feels like there is a bug in FFmpeg somewhere there, and should probably be reported upstream...

Well,thanks

**Comment by saudet** [comment]
Actually, after implementing `AVSEEK_SIZE`, it appears to work fine!

**Comment by duck123456** [comment]
implementing AVSEEK_SIZE? can see the code?

**Comment by duck123456** [comment]
> Actually, after implementing `AVSEEK_SIZE`, it appears to work fine!

Awesome ！it appears to work fine! that is cool ！Thank you

**Comment by saudet** [comment]
Fix now included in JavaCV 1.5.1. Thanks for reporting!
