### ISSUE TITLE
Adding decklink support

### ISSUE THREAD

**Issue by b005t3r** [bytedeco/javacv#1235]
Do you think it would be possible to add Decklink support to the ffmpeg build you use for JavaCV? I'm currently forced to use it and I have to do a few tricks like buildding a separate version of ffmpeg and streaming things from it to my app just to be able to use BlackMagic Ultra Studio, but it's actually really easy to add it to the build and I think there shouldn't be any licessing issues, since things like homebrew formulae use it.

If this is possible, it would be great if you could add that to future builds, I'm sure it would make things a lot easier for people who have to use BlackMagic devices.

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/pull/543

It's mainly a licensing problem I think, and Blackmagic Design isn't interested in helping.

**Comment by saudet** [comment]
One thing we can do though is update the cppbuild.sh file with all the flags necessary to link with Decklink, to make it easier to rebuild locally each time. Please do send a pull request with the changes you have! Thanks

**Comment by masterav10** [comment]
We are unable to publish FFmpeg with both Decklink Support and open-only codecs such as x264. The SDK agreement's distribution policy is incompatible with GPLv3. As @saudet  said, it's possible to modify the cppBuild.sh script to include the bindings which would allow you to build a copy locally. The pull request I published does thing to some degree.

Internal FFmpeg discussion describing the  [license problem](https://patchwork.ffmpeg.org/project/ffmpeg/patch/201704010120.37843.cehoyos@ag.or.at/) for details.

I'm planning on making bindings directly for the SDK, if that helps.
