### ISSUE TITLE
Setting up AVFrame for encoding

### ISSUE THREAD

**Issue by rvmps** [bytedeco/javacv#1236]
Hello,

I need to encode raw image data from a video source but I'm unable to setup correctly an AVFrame.

I have written a short class (VideoSource, attached) that builds a set of dummy frames (taken from https://www.ffmpeg.org/doxygen/3.4/encode_video_8c-example.html#a8) but I have failed miserably: frame.data(0, array) fails to copy the data.

What I am doing wrong?

Thanks,

Raul
[VideoSource.txt](https://github.com/bytedeco/javacv/files/3325867/VideoSource.txt)

**Comment by saudet** [comment]
Did you check the source code of FFmpegFrameRecorder? It's already doing that kind of thing, so it shouldn't be too hard to learn from that. If you have any specific questions I could help with, let me know.

**Comment by rvmps** [comment]
I'll check, thanks!

Raul

**Comment by rvmps** [comment]
Hello again,

I think I got the dummy source to work, thanks.

Now I have an issue in av_codec_send frame ("Invalid argument"). I'll open another issue for that.

Thanks again for the help!

Raul
