### ISSUE TITLE
Getting below error with building bundle(s) with android studio

### ISSUE THREAD

**Issue by Midhun9638** [bytedeco/javacv#1239]
com.android.tools.build.bundletool.exceptions.BundleFileTypesException$FileUsesReservedNameException: File 'root/lib/x86_64/include/opencv2/bioinspired.hpp' uses reserved file or directory name 'lib'.

**Comment by saudet** [comment]
Duplicate of #1117

**Comment by saudet** [comment]
FYI, you can exclude those files, they are not necessary at runtime.
