### ISSUE TITLE
AVIOInterruptCB callback event.

### ISSUE THREAD

**Issue by hihi0677** [bytedeco/javacv#124]
Hi @saudet 

I want to receive callback using AVIOInterruptCB in FFmpegFrameGrabber.java.

Reference 
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/src/main/java/org/bytedeco/javacpp/avformat.java

below code is mine.

FFmpegFrameGrabber.java
…..
    private AVFormatContext oc;
…..
        AVIOInterruptCB  cb = new AVIOInterruptCB();
        cb.callback(new Callback_Pointer(null) {
      	    public int call(Pointer p) {
          	Log.i(“test”, "grabFrame inturreptCallback");
      		return 0;
      	    }
        });
       oc.interrupt_callback(cb);
…..

but I cannot receive any event. What I wrong do ?
Thank you.^^

**Comment by saudet** [comment]
You need to create your callback object without the `null` argument, so something like should work:
```java
cb.callback(new Callback_Pointer() {
    public int call(Pointer p) {
...
```
Though, let me know if it doesn't, thanks!

**Comment by hihi0677** [comment]
I change Callback_Pointer without null argument and test but it still not callback called.

Thank you for your answer.^^

**Comment by saudet** [comment]
Would you have some reference code in C that we could check out? It should be easy for me to port that code to Java then, thanks!

**Comment by hihi0677** [comment]
Thank you for your reply.

I reference below code. It's working


void* reader_thread(void* arg) {
.....
	int consecutively_stream_conut = 0;
	AVIOInterruptCB int_cb = {interrupt_cb, &consecutively_stream_conut};
.....
	AVFormatContext* context = avformat_alloc_context();
	context->interrupt_callback = int_cb;
.....
}

int interrupt_cb(void *ctx) { 
....
}

**Comment by saudet** [comment]
Let's see, the created callback object might get garbage collected before it's even used. Try to keep it in a field, for example:
```java
static final Callback_Pointer dummy = new Callback_Pointer() { ... };
...
cb.callback(dummy)
```

**Comment by saudet** [comment]
FYI, thanks to @d-a-gerashenko we now have working sample code for this:
https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java
