### ISSUE TITLE
centos 7 use Java2DFrameConverter converter = new Java2DFrameConverter();  generate JVM crash

### ISSUE THREAD

**Issue by duck123456** [bytedeco/javacv#1240]
public BufferedImage doExecuteFrame(Frame frame) {
        Java2DFrameConverter converter = new Java2DFrameConverter();
        BufferedImage bi = converter.getBufferedImage(frame);
       return bi;
    }
log:
Stack: [0x00007fa13f7f8000,0x00007fa13f8f9000],  sp=0x00007fa13f8f74e0,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 7873 C2 org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma(Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIZDZI)V (635 bytes) @ 0x00007fa281cb4a8f [0x00007fa281cb4760+0x32f]
J 10528 C2 org.bytedeco.javacv.Java2DFrameConverter.copy(Lorg/bytedeco/javacv/Frame;Ljava/awt/image/BufferedImage;DZLjava/awt/Rectangle;)V (599 bytes) @ 0x00007fa28172617c [0x00007fa281725f80+0x1fc]
J 10527 C2 org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Lorg/bytedeco/javacv/Frame;DZLjava/awt/color/ColorSpace;)Ljava/awt/image/BufferedImage; (686 bytes) @ 0x00007fa282815f58 [0x00007fa282815e20+0x138]
J 10426 C2 cn.bywin.cbvsp.video.capture.builder.V3.VideoFrameBuilderV3.doHandleFrame(Lorg/bytedeco/javacv/Frame;Ljava/lang/String;Ljava/lang/String;Ljava/util/Date;)V (95 bytes) @ 0x00007fa282e22f4c [0x00007fa282e22ea0+0xac]
J 10994 C2 cn.bywin.cbvsp.video.capture.builder.V3.VideoFrameBuilderV3.seekFrame([BLjava/lang/String;Ljava/lang/String;Ljava/util/Date;)V (392 bytes) @ 0x00007fa282e773b0 [0x00007fa282e75040+0x2370]
J 11218 C2 com.google.common.util.concurrent.TrustedListenableFutureTask.run()V (14 bytes) @ 0x00007fa282ee0104 [0x00007fa282edd5c0+0x2b44]
J 12217% C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007fa2831f30a0 [0x00007fa2831f2dc0+0x2e0]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.so+0x6648eb]
V  [libjvm.so+0x661ec4]
V  [libjvm.so+0x6624a7]
V  [libjvm.so+0x6a56e4]
V  [libjvm.so+0xa12217]
V  [libjvm.so+0xa126dc]
V  [libjvm.so+0x8b7c22]
C  [libpthread.so.0+0x76ba]  start_thread+0xca

**Comment by saudet** [comment]
You'll need to give it a valid Frame object.

**Comment by duck123456** [comment]
> valid Frame
How do you know the valid Frame?  if(frame!=null){
  ...to execute
}

**Comment by saudet** [comment]
It won't crash like that :)

**Comment by duck123456** [comment]
ok,I'll try  ( frame!=null&&frame.image != null)  valid Frame ! thanks
