### ISSUE TITLE
What causes the "Packet mismatch" warning?

### ISSUE THREAD

**Issue by feiyangsuo** [bytedeco/javacv#1241]
I was implementing a video player. After the connection is established, I tried to grab frames from the video stream. And after about ten or twenty success grabs, some module (I can't figure which) print a series of "Packet mismatch" warning, and I can't successfully grab a single frame any more.
```
[flv @ 0x7f20bc002140] Packet mismatch -1970861269 4159267 383848396
[flv @ 0x7f20bc002140] Packet mismatch 447502239 4175908 388024304
[flv @ 0x7f20bc002140] Packet mismatch 1740798905 4065316 392089620
[flv @ 0x7f20bc002140] Packet mismatch 1968789025 4084260 396173880
[flv @ 0x7f20bc002140] Packet mismatch -320107011 3482148 399656028
[flv @ 0x7f20bc002140] Packet mismatch -1537332777 3716133 403372161
[flv @ 0x7f20bc002140] Packet mismatch 104442775 4011813 407383974
[flv @ 0x7f20bc002140] Unable to seek to the next packet
[flv @ 0x7f20bc002140] Packet mismatch 861956044 14566 411011505
[flv @ 0x7f20bc002140] Packet mismatch -1020217167 3815719 414827224
[flv @ 0x7f20bc002140] Packet mismatch -108314075 3927335 418754559
[flv @ 0x7f20bc002140] Packet mismatch -167608911 3405351 422159910
[flv @ 0x7f20bc002140] Packet mismatch 300752719 4274472 426434382
[flv @ 0x7f20bc002140] Packet mismatch -1170705886 3668520 430102902
[flv @ 0x7f20bc002140] Packet mismatch 1036452133 4429352 434532254
```
This issue does not occur so often, but I've encountered it for several times these days. 
What caused this issue? Is the grabber missing some data in a packet, and cannot correctly receive the following packets? And can this issue be fixed by some coding, or I may only rely on my network?
Looking for help. Thanks in advance.

**Comment by saudet** [comment]
Probably just your network dropping packets, yes.

**Comment by feiyangsuo** [comment]
> Probably just your network dropping packets, yes.

Thank you. However if the grabber is repeatedly trying to grab and mismatching packets, the program will be stuck.
Is there any approach to judge wether this problem is happenning, and to stop the grabber?

**Comment by chqaqc** [comment]
I also encountered a similar problem. Have you solved it now？

**Comment by feiyangsuo** [comment]
> I also encountered a similar problem. Have you solved it now？

Actually I didn't solve it. But after my co-worker optimized our network environment this issue has never shown up again.
However, for insurance, we added a watchdog in the frame-grabbing loop, to force the thread finish when problems like this happen.
