### ISSUE TITLE
can to segmentationVideo reset FFmpegFrameRecorder outputStream by FFmpegFrameRecorderPlusV3（outputStream ）

### ISSUE THREAD

**Issue by duck123456** [bytedeco/javacv#1242]
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L176

 The segmentation is achieved by adding this method to reset the video stream.
Whether this method is feasible？  

  public void resetOutStream(OutputStream outputStreamNew){

        if (outputStream != null) {
            try {
                if (closeOutputStream) {
                    outputStream.close();
                }
            } catch (IOException ex) {
                        ex.printStackTrace();
            } finally {
                outputStream = null;
                outputStreams.remove(oc);
            }
        }
        outputStream=outputStreamNew;
        outputStreams.put(oc, outputStream);
    }

**Comment by duck123456** [comment]
Does this method cause memory leaks？

**Comment by saudet** [comment]
What is the issue with just creating a new FFmpegFrameRecorder?

**Comment by duck123456** [comment]
> just creating a new FFmpegFrameRecorder
 Yes,just creating a new FFmpegFrameRecorder

**Comment by duck123456** [comment]
> What is the issue with just creating a new FFmpegFrameRecorder?

Yes,just creating a new FFmpegFrameRecorder

**Comment by duck123456** [comment]
> What is the issue with just creating a new FFmpegFrameRecorder?

Does this method still have resources to release?

**Comment by saudet** [comment]
Not after calling stop(), no.

**Comment by duck123456** [comment]
> Not after calling stop(), no.

The video stream is recorded all the time, unless it is stopped after the abnormal exit, otherwise it will be recorded all the time. Therefore, during this long intermediate process, the video stream will be accumulated all the time without releasing the split video, resulting in memory overflow

**Comment by saudet** [comment]
That depends on the OutputStream you are using. Use an OutputStream that doesn't cache data in memory.

**Comment by duck123456** [comment]
ok，thanks

**Comment by saudet** [comment]
However, if you notice any memory leaks even when not using OutputStream, please let me know. That may an indicate an issue with FFmpegFrameRecorder.

**Comment by duck123456** [comment]
哈哈！okay

**Comment by saudet** [comment]
BTW, I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
Please give it a try with the snapshots: http://bytedeco.org/builds/
