### ISSUE TITLE
Could not initialize class org.bytedeco.ffmpeg.global.avutil, i'm sorry but i don't know right way to put all jar on class path 

### ISSUE THREAD

**Issue by hongphuoc97** [bytedeco/javacv#1243]
Hi bro
    I flow issue 1206 and receive your response "You'll need to put all the JAR files in your class path for this to work."
I try setting build path in eclipse IDE, set CLASS_PATH environment variable and put all dependence into it, but i still get error.
Could you tell me right way to put all the Jar files in class path, thank you very much.

**Comment by saudet** [comment]
Some instructions for that are available in the README.md file here:
https://github.com/bytedeco/javacv#manual-installation
