### ISSUE TITLE
Training cascade classifier without OpenCV binaries

### ISSUE THREAD

**Issue by leoxiong** [bytedeco/javacv#125]
Hi, I am wanting to train a cascade classifier using JavaCV. I am aware of the opencv_traincascade binary, however I would like to write this in Java code using the JavaCV library. Under the hood of [traincascade](https://github.com/Itseez/opencv/blob/master/apps/traincascade/traincascade.cpp), it uses the `train()` method in `CvCascadeClassifier` which is not available through JavaCV. Could this be wrapped/ported?

Thanks.

**Comment by saudet** [comment]
Sure, we can wrap it. That should be posted up for the javacpp-presets though.
