### ISSUE TITLE
Can FFmpegFrameGrabber use hard decoding?

### ISSUE THREAD

**Issue by MrQ-Android** [bytedeco/javacv#1257]
Can FFmpegFrameGrabber use hard decoding?

**Comment by saudet** [comment]
Yes, try to set the one you're interested in with `setVideoCodecName()`.

**Comment by MrQ-Android** [comment]
ffmpegFrameGrabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);
            ffmpegFrameGrabber.setVideoCodecName("");

this is my code ,  my program run in windows pc or linux pc ,  what should i fill , the codec name ? how 
 can i get the codec name?

**Comment by saudet** [comment]
One way is with the `ffmpeg -codecs` command, that we can execute like this:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by MrQ-Android** [comment]
I can not find org.bytedeco.ffmpeg.ffmpeg.class  in javacv 1.4.4 ?

**Comment by MrQ-Android** [comment]
hi bra, i replace javacv version 1.5.1 success , i can get the codecs , thanks 
but , when i replace 1.4.4 to 1.5.1 , 
     frame = ffmpegFrameGrabber.grab();
     OpenCVFrameConverter.ToIplImage converterIpl = new OpenCVFrameConverter.ToIplImage();
     converterIpl.convertToMat(frame);

  Card stuck in this line of code (convertToMat)

**Comment by MrQ-Android** [comment]
i want to convert Frame to Image(JavaFx) , and convert Frame to byte(BGR)  , do you have simple ? very thanks u brother

**Comment by saudet** [comment]
There's JavaFXFrameConverter for that: 
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/JavaFXFrameConverter.html
