### ISSUE TITLE
The problem of FFmpegFrameGrabber(inputStream) 

### ISSUE THREAD

**Issue by duck123456** [bytedeco/javacv#1258]
Hi @saudet I use FFmpegFrameGrabber(url) is normal,but use FFmpegFrameGrabber(inputStream)  memory will grow, I used multithreading and the same video to test the results of both of them. thanks

**Comment by saudet** [comment]
Yes, that's normal. What is the issue?

**Comment by duck123456** [comment]
> Yes, that's normal. What is the issue?

https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L145
this medthod do'not normal,Will cause memory growth

**Comment by saudet** [comment]
Use the other one here with a maximumSize of 0 or something small:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L148
