### ISSUE TITLE
How to convert FFmpegFrameGrabber  grabbed frames into Bitmap

### ISSUE THREAD

**Issue by ahsan44411** [bytedeco/javacv#1259]
I want to get all the frames of a video using FFmpegFrameGrabber  and then convert them into Bitmap for an ImageView. See the code below. Do I also need Frame Recorder to get the frames or just FrameGrabber is enough? and After that how can I convert it into Bitmap
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(videopath);
   try {
     grabber.start();
   } catch (FrameGrabber.Exception e) {
     e.printStackTrace();
   }

Thanks

**Comment by saudet** [comment]
We don't need FFmpegFrameRecorder. Use this on the Frame objects to convert to Bitmap:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/AndroidFrameConverter.html

**Comment by ahsan44411** [comment]
It tells me not to use this for best performance. 
Can you kindly give me code example for my problem. Im new to Android Development.

**Comment by saudet** [comment]
Try something like this: https://github.com/bytedeco/javacv/issues/1201#issuecomment-488237979

**Comment by ahsan44411** [comment]
Am I doing this right?.Kindly help me. 

        FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("android.resource://" + getPackageName() + "/" + R.raw.video);
        frameGrabber.setPixelFormat(AV_PIX_FMT_RGBA);
        Frame frame;
        try {
            frameGrabber.start();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }

        Bitmap image=  AndroidFrameConverter().convert(frame);

**Comment by ahsan44411** [comment]
??
