### ISSUE TITLE
How to make libjniopencv_core.so, libjniopencv_imgproc.so files. 

### ISSUE THREAD

**Issue by hihi0677** [bytedeco/javacv#126]
Hi @saudet 

I'm making Android Application using ffmpeg and openCV.

But fail to find libjniopencv_core.so, libjniopencv_imgproc.so Files.

I'm searching these files but I couldn't find. 

Whrere can I find these .so files or How to make it?

Thank you.^^

**Comment by saudet** [comment]
There are in the `opencv-android-arm.jar` and `opencv-android-x86.jar` files.

**Comment by hihi0677** [comment]
Thank you for your reply.^^

I build OpenCV in Ubunto but opencv-android-arm.jar not created.

I just got some .so files in
javacpp-presets / opencv / cppbuild / android-arm / libs /

build option is
cppbuild install opencv -platform android-arm

Is there any other options I have to add ?

Thank you.^^

**Comment by saudet** [comment]
To rebuild from source, please follow the instructions here:
https://github.com/bytedeco/javacpp-presets/#build-instructions

**Comment by hihi0677** [comment]
Thank you. I miss the mvn build.

I got opencv-android-arm.jar ~!~!
