### ISSUE TITLE
AndroidFrameConverter().convert returns null Bitmap image

### ISSUE THREAD

**Issue by ahsan44411** [bytedeco/javacv#1260]
Trying to get frames from a video but when I convert the frames into Bitmap using AndroidFrameConverter().convert I get null values.

 FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("android.resource://" + getPackageName() + "/" + R.raw.video);
        frameGrabber.setPixelFormat(AV_PIX_FMT_RGBA);
        Frame frame=null;
        try {
            frameGrabber.start();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }
        try {
            frame=frameGrabber.grab();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }
        Bitmap image= new  AndroidFrameConverter().convert(frame);

**Comment by saudet** [comment]
FFmpeg doesn't support Android resources. Use a path to a normal file.

**Comment by ahsan44411** [comment]
Do you mean from the gallery ?

**Comment by saudet** [comment]
Doesn't matter, as long as it's a file.
