### ISSUE TITLE
add Umat 

### ISSUE THREAD

**Issue by peererror** [bytedeco/javacv#1263]
in C++ I can do this how can I do this in java
`cv::add(UMat, double, UMat) `
I have done this in java 
`add(UMat, UMat, UMat)`
 this works but not above

**Comment by saudet** [comment]
> cv::add(UMat, double, UMat) 

I'm not sure which function you're referring to.
Maybe you're referring to scaleAdd()?
Could you provide a link to its declaration?

**Comment by peererror** [comment]
I am trying to port this code 
https://github.com/WL-Amigo/waifu2x-converter-cpp/blob/master/src/modelHandler.cpp#L147

**Comment by saudet** [comment]
I see, it does some magic with `cv::InputArray`. We can achieve the same effect with something like:
```java
add(UMat, new Mat(double).getUMat(), UMat);
```
