### ISSUE TITLE
How do I specify a GPU card to decode if i have two GPU card ?

### ISSUE THREAD

**Issue by yangqx** [bytedeco/javacv#1266]
I konwn ,ffmpeg -hwaccel cuvid -hwaccel_device 0 -c:v h264_cuvid -i demo.flv ...
I want to use FFmpegFrameGrabber .
I've tried, setOption("hwaccel_device", "1"); or setVideoOption("hwaccel_device", "1"); and so on
but it had no effect at all.

**Comment by saudet** [comment]
That sounds like a question about FFmpeg?
You'll probably find the answer in their documentation:
https://ffmpeg.org/documentation.html

**Comment by yangqx** [comment]
I've tried, setOption("hwaccel_device", "1"); or  setVideoOption("hwaccel_device", "1"); and so on
but it had no effect at all. 
I want to use FFmpegFrameGrabber .

**Comment by yangqx** [comment]
> 
> 
> That sounds like a question about FFmpeg?
> You'll probably find the answer in their documentation:
> https://ffmpeg.org/documentation.html
I want to use javaCV，how to set ?  Thank u

**Comment by yaoshuyu** [comment]
> That sounds like a question about FFmpeg?
> You'll probably find the answer in their documentation:
> https://ffmpeg.org/documentation.html

We have already read the #1142, #1134, and read the document on ffmpeg.org, but setOption(“hwaccel_device”，“1”) doesn't work.

**Comment by saudet** [comment]
Maybe we need to set it some other way. Someone will need to figure this out. I don't have this information at the moment.

**Comment by yaoshuyu** [comment]
Please keep an eye on this issue, it's very useful to us. 
And I have another doubt. How does javacv implement instruction mapping and why can some instructions like `setVideoOption("hwaccel", "cuvid")` can be set successfully?

**Comment by saudet** [comment]
The `ffmpeg` program doesn't map directly all the options that way. Maybe something like `setVideoOption("device"，"1")` works, I don't know. The only way to know for sure is to read the source code of the `ffmpeg` program.

**Comment by samegit** [comment]
You can try this
`setVideoCodecName("h264_cuvid");`
`setVideoOption("gpu", "1");`

**Comment by yangqx** [comment]
> 
> 
> You can try this
> `setVideoCodecName("h264_cuvid");`
> `setVideoOption("gpu", "1");`

It is work for me . Thank you very much!

**Comment by yaoshuyu** [comment]
> You can try this
> `setVideoCodecName("h264_cuvid");`
> `setVideoOption("gpu", "1");`

This parameter can be used, you really helped us a lot. Thank you very much!
