### ISSUE TITLE
Problem with javacv-platform used in linux

### ISSUE THREAD

**Issue by 256785** [bytedeco/javacv#1267]
When I use the javacv in linux to capture the viedo , the message is  Unable to stop the stream: Inappropriate ioctl for device  while I can use it in windows.Could you tell me how to solve it ?Thank you

**Comment by saudet** [comment]
Try to use FFmpeg instead of OpenCV, it generally has better support for camera capture.

**Comment by 256785** [comment]
I only need to caputure one frame in the video,the opencv_videoio can make it easy.What should I do to  
configure the environment in linux

**Comment by saudet** [comment]
I told you, don't use OpenCV, use FFmpeg, for example, like this: https://github.com/bytedeco/javacv/issues/154#issuecomment-104954981

OpenCV is known to be buggy and doesn't work well for that. If you really really need to get this working with OpenCV, please report your issue upstream.

**Comment by 256785** [comment]
Thank you for your reply. I have finished it with FFmpegFrameGrabber.
