### ISSUE TITLE
OpenCVFramegrabber options

### ISSUE THREAD

**Issue by matteoformenti** [bytedeco/javacv#1269]
There is no documentation regarding which keys can be specified in OpenCVFramegrabber.setOption.
Should we use the string name like specified [here](https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-set) or the relative index?
Currently, I tried all indexes from 1 to 18 with no success, and same for settings like "CV_CAP_PROP_EXPOSURE".
(Ubuntu 19.04, Java12, javacv 1.5.1, Logitech C920)

**Comment by saudet** [comment]
It's not currently supported, but it shouldn't be too hard to add support for that.

**Comment by saudet** [comment]
Please give it a try with 1.5.2-SNAPSHOT:
http://bytedeco.org/builds/

Thanks for reporting this issue!

**Comment by matteoformenti** [comment]
It's working as intended.
For future references those are the indexes you have to pass as key
0: CAP_PROP_POS_MSEC Current position of the video file in milliseconds or video capture timestamp.
1: CAP_PROP_POS_FRAMES 0-based index of the frame to be decoded/captured next.
2: CAP_PROP_POS_AVI_RATIO Relative position of the video file: 0 - start of the film, 1 - end of the film.
3: CAP_PROP_FRAME_WIDTH Width of the frames in the video stream.
4: CAP_PROP_FRAME_HEIGHT Height of the frames in the video stream.
5: CAP_PROP_FPS Frame rate.
6: CAP_PROP_FOURCC 4-character code of codec.
7: CAP_PROP_FRAME_COUNT Number of frames in the video file.
8: CAP_PROP_FORMAT Format of the Mat objects returned by retrieve() .
9: CAP_PROP_MODE Backend-specific value indicating the current capture mode.
10: CAP_PROP_BRIGHTNESS Brightness of the image (only for cameras).
11: CAP_PROP_CONTRAST Contrast of the image (only for cameras).
12: CAP_PROP_SATURATION Saturation of the image (only for cameras).
13: CAP_PROP_HUE Hue of the image (only for cameras).
14: CAP_PROP_GAIN Gain of the image (only for cameras).
15: CAP_PROP_EXPOSURE Exposure (only for cameras).
16: CAP_PROP_CONVERT_RGB Boolean flags indicating whether images should be converted to RGB.
17: CAP_PROP_WHITE_BALANCE Currently not supported
18: CAP_PROP_RECTIFICATION Rectification flag for stereo cameras (note: only supported by DC1394 v 2.x backend currently)

**Comment by saudet** [comment]
There are other options specific to each backend as well.

**Comment by saudet** [comment]
Included in just released JavaCV 1.5.2! Thanks for reporting this issue and for your contribution.
