### ISSUE TITLE
can not find org.bytedeco.javacpp.opencv_core$Rect in android

### ISSUE THREAD

**Issue by AurimasAnskaitis** [bytedeco/javacv#127]
I'm a happy user of javacv on a desktop machine, thanks to all involved.
Using android and sbt I get the following exception: 
E/AndroidRuntime(20677): java.lang.NoClassDefFoundError: org.bytedeco.javacpp.opencv_core$Rect
Program works fine till I try to access anything from opencv.
Here is my sbt file:

```scala
import android.Keys._

android.Plugin.androidBuild

platformTarget in Android := "android-16"

scalaVersion := "2.11.6"

classpathTypes += "maven-plugin"

libraryDependencies ++= Seq(
  "org.bytedeco"                 % "javacpp"         % "0.11",
  "org.bytedeco"                 % "javacv"          % "0.11",
  "org.bytedeco.javacpp-presets" % "opencv" % ("2.4.11-0.11") classifier "",
  "org.bytedeco.javacpp-presets" % "opencv" % ("2.4.11-0.11") classifier "android-arm"
)

name := "hello-world"

javacOptions in Compile ++= Seq("-source", "1.7", "-target", "1.7")
```
what could be the problem?

**Comment by saudet** [comment]
Try to add the "android-x86" one too. Maybe your device isn't ARM...

**Comment by AurimasAnskaitis** [comment]
I'm sure it is ARM (Checked this morning). Now I even can not install the program on the device. Proguard is barking. Maybe it is because I'm using android-sdk-plugin for sbt on android. (Maybe the problem is with this plugin, not javacv)
I will try the instructions for android studio. Let you know the results.

**Comment by AurimasAnskaitis** [comment]
JavaCV works using instructions for Android Studio. This probably means that the problems are with android-sdk-plugin and not with javacv.

**Comment by dant3** [comment]
This most-likely means that Proguard stripped this class away. Did you used proguard in your Android Studio/Gradle project? sbt plugin is designed for scala projects and thus, enables proguard by default. Most likely you just need to tune proguard rules to make it keep the classes you want.

**Comment by saudet** [comment]
There's issues with ProGuard in general indeed. More info about that here: https://github.com/bytedeco/javacv/issues/79#issuecomment-91237951

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming this is a ProGuard related issue, so marking as duplicate and closing. Let me know if isn't the case though, thanks!
