### ISSUE TITLE
windows use  use Java2DFrameConvertergenerate JVM crash

### ISSUE THREAD

**Issue by 597410004** [bytedeco/javacv#1271]
```
when i use javafx convert mat to image,a later the application will crash

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000398d89f, pid=5552, tid=0x00000000000015a8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 5950 C2 org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma(Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIZDZI)V (635 bytes) @ 0x000000000398d89f [0x000000000398d4e0+0x3bf]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by saudet** [comment]
Be sure to make a copy of the image to make sure it doesn't get deallocated prematurely.

**Comment by 597410004** [comment]
The code I use is as followed:
"Image image = SwingFXUtils.toFXImage(Java2DFrameUtils.toBufferedImage(frame), null);"
frame is a Mat object. Do you mean to clone the Mat data before the calling of the toBufferedImage method?

I also see the the implementation of  the toBufferedImage method:

public synchronized static BufferedImage toBufferedImage(Mat src) {
        return deepCopy(biConv.getBufferedImage(matConv.convert(src).clone()));
    }

There is a clone of the converted Frame object already. Is it duplicated if I also copy the Mat data?

I am testing the program, sometimes it can run 12-13 hours and then crash. Sometimes it just run 1-2 hours and crash with the ACSESS_VIOLATION_EXCEPTION above.

Thanks.

**Comment by saudet** [comment]
That does the cloning yes so no need to do anything else in that case. It's not very efficient though.

**Comment by saudet** [comment]
Try to release all Mat and other native objects as quickly as possible. This will prevent errors from happening in the deallocator thread.

**Comment by 597410004** [comment]
When I release the mat the question is resolved,thanks

**Comment by 597410004** [comment]
Sorry that it was not resolved. After I manually released all the Mat objects, it got better. However after running the program after 25 hours, it just crashed with the same EXCEPTION_ACCESS_VIOLATION error again. 

The problem could be within the following code:
Image image = SwingFXUtils.toFXImage(Java2DFrameUtils.toBufferedImage(frame), null);
Since the error report showed that:
# Problematic frame:
# J 5950 C2 org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma(Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIZDZI)V (635 bytes) @ 0x000000000398d89f [0x000000000398d4e0+0x3bf]
#
Only the toBufferedImage method called org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma method in my program.

The error occured in the video processing thread as shown in the error report, not in the deallocator thread. 

Any help? Thanks.

**Comment by saudet** [comment]
Java2DFrameUtils allocates objects as well, so either try not using it, or try to use PointerScope: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by saudet** [comment]
Java2DFrameUtils is not thread safe. Don't use it with threads.

**Comment by saudet** [comment]
Use one Java2DFrameConverter per thread directly and all should be fine. Let me know if you're still not able to get this working though.

**Comment by 597410004** [comment]
when i change the method the question is resolve,thanks
