### ISSUE TITLE
Can't get -1 predictlabel for unknown faces 

### ISSUE THREAD

**Issue by sudipsadhukhan0295** [bytedeco/javacv#1276]
I am new in javacv. I use LBPHFaceRecognizer to recognize face. It returns proper **predictLabel** when face is present in train images but it can't return -1 value in **predictLabel** when face is unknown. 
Here is my code
`LBPHFaceRecognizer faceRecognizer = LBPHFaceRecognizer.create();

        faceRecognizer.train(images, labels);
        IntPointer label = new IntPointer(1);
        DoublePointer confidence = new DoublePointer(1);
        if (!testImage.empty()) {
            faceRecognizer.predict(testImage, label, confidence);
            int predictedLabel = label.get(0);

            System.out.println("Predicted label: " + predictedLabel);
            System.out.println("confidence label: " + confidence.get(0));
        }`

**Comment by saudet** [comment]
The "confidence" will be very low for "unknown" faces.
