### ISSUE TITLE
OpenCVFrameConverter.start()  error

### ISSUE THREAD

**Issue by YukiDmZhao** [bytedeco/javacv#1282]
code:
String rtspPath = "rtsp://admin:admin12345@192.168.0.210:554/cam/realmonitor?channel=1&subtype=0";
		String rtspPath = "rtmp://58.200.131.2:1935/livetv/hunantv";
		try {
			// TODO Auto-generated method stub
			OpenCVFrameConverter.ToMat converter = new OpenCVFrameConverter.ToMat();
//		FrameGrabber grabber = FrameGrabber.createDefault(rtspPath);
			OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(rtspPath);
			grabber.setImageWidth(1280);
			grabber.setImageHeight(720);
			System.out.println("===11");
			grabber.start(); // 
			System.out.println("===22");
			Mat grabbedImage = converter.convert(grabber.grab());
			int height = grabbedImage.rows();
			int width = grabbedImage.cols();
			System.out.println("height===" + height);
			System.out.println("width===" + width);
		} catch (Exception e) {
			e.printStackTrace();
		}

org.bytedeco.javacv.FrameGrabber$Exception: read() Error: Could not read frame in start().
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:240)
	at com.cu3.faceApi.facehandle.Demo.main(Demo.java:27)

**Comment by YukiDmZhao** [comment]
Try to use  OpenCVFrameGrabber , or  FrameGrabber grabber  , 
error:
Could not read frame in start().

**Comment by saudet** [comment]
Use FFmpegFrameGrabber instead.

**Comment by YukiDmZhao** [comment]
Thanks , FFmpegFrameGrabber is right.
But: Allways display warning :
[swscaler @ 0x7f42e5023f00] deprecated pixel format used, make sure you did set range correctly
frame grabbed at 6852000


I want to know why can not using  OpenCVFrameGrabber?? I want to using video for Face Recognition

**Comment by saudet** [comment]
OpenCV isn't getting linked for license reasons, and there is no advantage
because we can use FFmpeg directly, together OpenCV:
https://github.com/bytedeco/javacv/blob/master/samples/Demo.java

**Comment by YukiDmZhao** [comment]
howt to setting  FFmpegFrameGrabber  format??

**Comment by YukiDmZhao** [comment]
Thank you very much

**Comment by saudet** [comment]
See issue #780. If you would like to fix this, contribution are welcome!
