### ISSUE TITLE
Ffmpegframegrabber can not get clear img from rtsp stream with h265

### ISSUE THREAD

**Issue by huaxne** [bytedeco/javacv#1284]
I use ffmpegframegrabber to capture img from ipcamera rtsp stream. When ipcamera working with h264 ,the img is clear.but when h265 , the img is always gray. How can I capture clear img for h265 camera?

**Comment by huaxne** [comment]
codes：
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(rtspurl)
grabber.setVideoCodec(avcodec.AV_CODEC_ID_H265);
grabber.setPixlFormat(yuv420p);
grabber.setoption(allowedmediatype,video);
......
grabber.start();
....

**Comment by huaxne** [comment]
With javacv 1.5

**Comment by saudet** [comment]
Don't call `setPixelFormat()` and everything will be fine.

**Comment by huaxne** [comment]
I remove setPixelFormat，but it keeps
 same result gray img. Is there any other option should I set?

**Comment by saudet** [comment]
No, but there may be other options for your camera. Make sure to read its
instructions completely.

**Comment by huaxne** [comment]
dear saudet, I got follow error log  would youhelp me to fix it.
[hevc @00022222xxx] PPS id out of range :0
[hevc @00022222xxx] PPS id out of range :0
[hevc @00022222xxx] Error parsing NAL unit #0.

**Comment by saudet** [comment]
There are known bugs in the support for HEVC in FFmpeg: See issue #1227. Please report upstream!

**Comment by huaxne** [comment]
Thank you saudet.
You mean I should report it to FFmpeg,right?

**Comment by saudet** [comment]
Yes, here: https://ffmpeg.org/bugreports.html
Make sure to tell them how to make the errors occur with `ffmpeg` program because they are not Java users.

**Comment by huaxne** [comment]
Thank you. But I don't know how to discribe the call path in javacv. Would you please tell me the key method of ffmpeg which was called by javacv .

**Comment by saudet** [comment]
JavaCV doesn't use the ffmpeg program, but there is information here, for
example: https://trac.ffmpeg.org/wiki/StreamingGuide
