### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/bytedeco/javacv/Java2DFrameConverter

### ISSUE THREAD

**Issue by mustafa220** [bytedeco/javacv#1285]
Hi.

I am making a little program for get frames from video.

In Netbeans, when i run, my program working correctly. But if i build this program, i m getting this error

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/bytedeco/javacv/Java2DFrameConverter

Edit: javacv version is 1.0

**Comment by saudet** [comment]
You'll need to make sure to put all JAR files in your class path:
https://github.com/bytedeco/javacv/#manual-installation

**Comment by mustafa220** [comment]
@saudet i m using with maven. and i added dependency like this

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.0</version>
        </dependency>

**Comment by saudet** [comment]
Try again with JavaCV 1.5.

**Comment by mustafa220** [comment]
@saudet 

when i am try with JAVACV 1.5,

i am getting this error

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil

**Comment by saudet** [comment]
Use `javacv-platform` instead of just `javacv` as per the README.md file:
https://github.com/bytedeco/javacv/#downloads
