### ISSUE TITLE
Im migrating my java application from 1.8 to 11 Im getting Import Errors. 

### ISSUE THREAD

**Issue by AKMANSoft** [bytedeco/javacv#1286]
I'm using eclipse and create module.info file int which added automatically the exports and requires 
requires opencv;
requires org.bytedeco.javacpp;
requires org.bytedeco.javacv;
requires org.bytedeco.opencv;

It is giving me the error

The package org.bytedeco.javacpp is accessible from more than one module: ffmpeg, opencv, org.bytedeco.javacpp

In my pom i have

**Comment by saudet** [comment]
Use version 1.5.1 everywhere: http://bytedeco.org/download/
