### ISSUE TITLE
Capturing from video input

### ISSUE THREAD

**Issue by Adi-18** [bytedeco/javacv#1288]
Is it possible to capture directly from an sdi or hdmi input something like game capture box or any card? According to capturing web cam.

**Comment by saudet** [comment]
Sure, it works the same as a webcam.

**Comment by Adi-18** [comment]
Thank you for your replay.
What do I have to pay attention to when I buying a card?

One is a "AVerMedia Live Gamer 4K" PC-Card and other one is a "Roxio Game Capture HD PRO" Box.

**Comment by saudet** [comment]
As long as it works with the standard API of your OS, there shouldn't be
any issues.

**Comment by saudet** [comment]
Please let me know if you encounter any problems though! Thanks
