### ISSUE TITLE
FFmpegFrameGrabber takes a long time to retrieve frames from url

### ISSUE THREAD

**Issue by leofarage** [bytedeco/javacv#129]
Samuel, 

I'm trying to build a custom VideoView for Android using javaCV. I'm using the FrameGrabber for retrieving the frames and presenting each frame into a SurfaceView. When using a downloaded file it goes really well -- but if I use a URL as the video path in the FrameGrabber it takes a long time to retrieve a single frame.

For example, when playing the downloaded file it takes 3~5 seconds to start presenting the frames at the expected frame rate. But when using the URL it takes 20~30 seconds to present the first frame and almost the same time to show the second and so on -- two seconds worth of frames at 30fps has taken 20 minutes to end.

So, I just wanted to know if this is expected or is it something I'm doing wrong.

Thanks in advance and congratulations on the amazing work.

**Comment by saudet** [comment]
There are apparently some settings for that:
http://comments.gmane.org/gmane.comp.video.ffmpeg.libav.user/3888
They are not currently exposed by `FFmpegFrameGrabber`, but it should be easy enough to modify it for that purpose. There's probably other settings to try as well...

If you do take the time to make modifications please consider sending a pull request! Thanks

**Comment by leofarage** [comment]
Thanks for answering. 
In the javaCV case I need to change the parameters through the java wrapper, right? 

Thanks again :D

**Comment by saudet** [comment]
We don't _need_ to, we can always choose the hard way and do it via the NDK :)

**Comment by saudet** [comment]
BTW, it's possible to set these options through new functionality added in this commit: https://github.com/bytedeco/javacv/commit/70db4a5835e376d5e8b70c26b9668332054b4696

Let me know if that satisfied your needs! Thanks

**Comment by leofarage** [comment]
Thanks for pointing it out. That looks very good! Is this commit available in the current gradle build?

Thanks, and congratulations on your amazing work!

**Comment by saudet** [comment]
It's not on the Central Repository, yet, if that's what you mean, but it's simple enough to build from source if you'd like to try it out!

**Comment by saudet** [comment]
I've just released version 1.1, which should let us set all the options that we want. Is there any combination of them that satisfy your needs? Let us know! Thanks

**Comment by saudet** [comment]
Closing, assuming this is no longer an issue if we specify the right options, but let me know if this is not the case, thanks!
