### ISSUE TITLE
error -22: Could not encode audio packet.

### ISSUE THREAD

**Issue by yuzhimin201** [bytedeco/javacv#1294]
Hi guys!I got a problem here, when i use ffmpegframeRecorder, i input a mp3 audio and output as outputstream, but i will block at recorder.stop()the error is could not encode audio packet

   
    Input #0, mp3, from 'hua.mp3':
Metadata:
encoder : Lavf58.11.101
Duration: 00:02:15.00, start: 0.069063, bitrate: 128 kb/s
Stream #0:0: Audio: mp3, 16000 Hz, mono, fltp, 128 kb/s
[mp3float @ 0x7f49f84b9f80] Could not update timestamps for skipped samples.
Output #0, mp3, to '':
Metadata:
TSSE : Lavf58.20.100
Stream #0:0: Audio: mp3, 16000 Hz, mono, fltp, 64 kb/s
[libmp3lame @ 0x7f49f8f8e280] inadequate AVFrame plane padding
[libmp3lame @ 0x7f49f8f8e280] 4 frames left in the queue on closing
[2019-09-06 17:30:00.321] ERROR [stream-service-1] StreamProcessService.java:131 - avcodec_encode_audio2() error -22: Could not encode audio packet.

The source code is :

 
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputStream, 1);
recorder.setFormat("mp3");
recorder.setFrameRate(grabber.getFrameRate());
recorder.setAudioCodec(avcodec.AV_CODEC_ID_MP3);
recorder.setSampleRate(grabber.getSampleRate());
it will crash when i call recoder.stop()

**Comment by saudet** [comment]
Running that code doesn't result in any error message. You'll need to provide more than that.

**Comment by yuzhimin201** [comment]
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);
grabber.startUnsafe();
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputStream, 1);

 recorder.setFormat("mp3");
 recorder.setFrameRate(grabber.getFrameRate());
recorder.setAudioCodec(avcodec.AV_CODEC_ID_MP3);
 recorder.setSampleRate(grabber.getSampleRate());

 //doAudio, doVideo, doProcessing, keyFrames
frame = grabber.grabFrame(true, false, true, false);
recorder.startUnsafe();
recorder.record(frame);
recorder.stop();

**Comment by saudet** [comment]
Could you upload here a sample file that fails instead of "url"?

**Comment by yuzhimin201** [comment]
[hua.zip](https://github.com/bytedeco/javacv/files/3583830/hua.zip)

**Comment by wyh0919** [comment]
And if we remove: recorder.stop(), it will run.

**Comment by wyh0919** [comment]
so if there is any risk when remove [recorder.stop]? or any other advise?

**Comment by saudet** [comment]
I found the problem and it's now fixed.
Please give it a try with 1.5.2-SNAPSHOT:
http://bytedeco.org/builds/

**Comment by wyh0919** [comment]
Thank you very much! It works!  One more question, when will this version officially work? Then we can use mavenCentral

**Comment by saudet** [comment]
Probably in a month or two...

**Comment by wyh0919** [comment]
Ok! Got it! Thanks.

**Comment by saudet** [comment]
JavaCV 1.5.2 has been released with the fix! Enjoy and thanks for reporting this issue.
