### ISSUE TITLE
NullPointerException in FFmpegFrameRecorder.record(Buffer... samples)

### ISSUE THREAD

**Issue by 3dm1** [bytedeco/javacv#130]
Here's the stacktrace:

    E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-23
        java.lang.NullPointerException
            at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:755)
            at org.bytedeco.javacv.FrameRecorder.record(FrameRecorder.java:280)
            at AudioRecordRunnable.run(FrameProcessingThread.java:281)

and here's the code snippet where this error happens:
```java
    while (runAudioThread) {
        // Reads audio sample from the audio record instance
        bufferReadResult = audioRecord.read(audioData.array(), 0, audioData.capacity());

        // Checks if data read is valid
        if (bufferReadResult > 0 && bufferReadResult < audioData.capacity()) {

        // Limits buffer to correct  size
        audioData.limit(bufferReadResult);

        if (startTime != -1 && frameRecorder != null) {
            try {
                // Adds audio sample to frameRecorder
                frameRecorder.record(audioData);

                } catch (FrameRecorder.Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
```
-------------
EDIT

Starting the audio recording thread after frameRecorder.start() solved the crash

**Comment by saudet** [comment]
Ok, so, problem solved? Great :) Thanks for the feedback!
