### ISSUE TITLE
FrameGrabber setFrameRate function not working

### ISSUE THREAD

**Issue by Arrowa70** [bytedeco/javacv#1302]
I try to grab a local mp4 file using the FFmpegFrameGrabber, and I find it useless calling the setFrameRate before the start function. The grabber still grab as fast as it can.

my code
```java
  val testVideo = "D:\\test_video\\test.mp4"
  val file = new File(testVideo)
  val grabber = new FFmpegFrameGrabber(file)
  grabber.setFrameRate(25)
  grabber.start()
```

And it also happend when I try to grab camera frame using the OpenCVFrameGrabber. setFrameRate still makes no difference. 

I want to know if there is a way to set the framerate of grabbing local video files.

**Comment by saudet** [comment]
Not many codecs or devices support setting the frame rate.
BTW, to convert the frame rate, we can use the `fps` filter:
https://ffmpeg.org/ffmpeg-filters.html#fps-1

**Comment by saudet** [comment]
If you're talking about player-like functionality, we can use `Thread.sleep()` for that or rely on the audio pipeline to synchronize both streams: https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java

**Comment by saudet** [comment]
Duplicate of #1121
