### ISSUE TITLE
avformat_find_stream_info block

### ISSUE THREAD

**Issue by 739988940** [bytedeco/javacv#1304]
hello 
I want Use the following code to start a FFmpegFrameGrabber with inputStream, but it always block at (avformat_find_stream_info) until inputStream is over;

FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputStream);
grabber.start();

but when i Save the inputStream as files and Use the following code ， it works，not block at (avformat_find_stream_info) 

FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new File("save.data"));
grabber.start();

so , How can I use inputStream？

**Comment by saudet** [comment]
What does FFmpeg output to the log on the console?

**Comment by 739988940** [comment]
nothing , i copy the FFmpegFrameGrabber code  and debug find it block at avformat_find_stream_info

**Comment by 739988940** [comment]
`public class ReceivePsStream_local {


    public static void main(String[] args) {
        try {

            FileInputStream fileInputStream = new FileInputStream(new File("1569311181633.data"));

            PipedInputStream pipedInputStream = new PipedInputStream();
            PipedOutputStream pipedOutputStream = new PipedOutputStream();
            pipedInputStream.connect(pipedOutputStream);
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        int audioRecord = 0;//0不录制 1录制
                        test(pipedInputStream, "rtmp://127.0.0.1:1935/live/123", 0);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }).start();
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        int a = 0;
                        while (a != -1) {
                            Thread.sleep(50);
                            byte[] buf = new byte[1024];
                            a = fileInputStream.read(buf);
                            System.out.println("接收到" + a);
                            if (a != -1){
                                pipedOutputStream.write(buf, 0, a);
                            }
                            pipedOutputStream.flush();

                        }
                        System.out.println("结束");
                        pipedOutputStream.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }).start();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static boolean exit = false;

    public static void test(PipedInputStream inputStream, String rtmpPath, int audioRecord) throws Exception {
        int width = 640, height = 480;
        MyFFmpegFrameGrabber grabber = new MyFFmpegFrameGrabber(inputStream);
        grabber.setImageWidth(width);
        grabber.setImageHeight(height);
        grabber.setVideoOption("vcodec", "copy");
        System.out.println("grabber start");
        grabber.start();

        MyFFmpegFrameRecorder recorder = new MyFFmpegFrameRecorder(rtmpPath, width, height, audioRecord);
        recorder.setVideoOption("crf", "28");
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); // 28
        recorder.setFormat("flv"); // rtmp的类型
        recorder.setFrameRate(25);
        recorder.setVideoOption("preset", "ultrafast");
        recorder.setVideoOption("tune", "zerolatency");
        recorder.setPixelFormat(0); // yuv420p

        System.out.println("recorder start");
        recorder.start(grabber.getFormatContext());

        System.out.println("all start!!");
        int count = 0;
        int noframe = 0;
        while (!exit) {
            count++;
            if (noframe > 10) {
                exit = true;
            }
            Frame frame = grabber.grabFrame();
            if (frame == null) {
                System.out.println("null");
                noframe++;
                continue;
            }
            if (count % 100 == 0) {
                System.out.println("count=" + count);
            }
            recorder.record(frame);
        }
        grabber.stop();
        grabber.release();
        recorder.stop();
        recorder.release();
        inputStream.close();
    }
}`
this is my test code

**Comment by 739988940** [comment]
> What does FFmpeg output to the log on the console?

**Comment by saudet** [comment]
Try call setFormat() with some string that might correspond to your data format before calling start()

**Comment by 739988940** [comment]
> setFormat

not work ,
you can use the code above to test with two methods;

**Comment by saudet** [comment]
Set the log level to DEBUG and let's check what that outputs.

**Comment by saudet** [comment]
Your file format might also have information at the end of the stream that FFmpeg is probably trying to read. If that's the case, there is not much we can do other than using another format, more suited to streaming.

**Comment by 739988940** [comment]
> Your file format might also have information at the end of the stream that FFmpeg is probably trying to read. If that's the case, there is not much we can do other than using another format, more suited to streaming.

I set av_log_set_level(AV_LOG_TRACE), but thier no anything debug info.

I tried to receive streaming ,about 200ms later ,This method (avformat_find_stream_info) parsed correct streaming info, but the readCallBack did not read anything,and the streaming is aways send data,

**Comment by 739988940** [comment]
I have found the reason ,
            avio = avio_alloc_context(new BytePointer(av_malloc(1024)), 1024, 0, oc, readCallback, null, seekCallback);
modify:
         avio = avio_alloc_context(new BytePointer(av_malloc(1024)), 1024, 0, oc, readCallback, null, null);

**Comment by saudet** [comment]
We can set the maximumSize to 0 and it should have the same effect. Can you try?

**Comment by 739988940** [comment]
> We can set the maximumSize to 0 and it should have the same effect. Can you try?

I've tried it. if use maximumSize =0 still can't readCallback

**Comment by saudet** [comment]
I guess we could have a special case when maximumSize <= 0 to not use the
seek function. Could you send a pull request to that effect?

**Comment by saudet** [comment]
JavaCV 1.5.2 has been released and includes the new behavior when maximumSize <= 0. 
Thanks for reporting this issue!
