### ISSUE TITLE
Reduce app size

### ISSUE THREAD

**Issue by u136865** [bytedeco/javacv#1308]
In app gralde I have:

android{
    defaultConfig{
         ndk.abiFilters 'armeabi-v7a', 'arm64-v8a'
         ...
    }
    ....
}

dependecies {
    ....
    implementation(group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.1')
}

But this implementation load all architectures of javacv-platform.
Are there any way to reduce the size? 
I tried to add classifiers, like "classifier: 'android-arm'" or "android-arm64" but I was obtain: "Failed to resolve: javacv-platform-android-arm64"

Thks

**Comment by saudet** [comment]
Yes, we can add dependencies only for the platforms and modules we're interested, details here:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

**Comment by saudet** [comment]
There is now a plugin for Gradle to exclude by platform names:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin
If you try it out and find anything missing, please let me know!
