### ISSUE TITLE
Dnn with support GPU CUDA

### ISSUE THREAD

**Issue by decioschmitt** [bytedeco/javacv#1309]
Hi;
I hope that you can help.
I ll like know if javacv can work with darknet model using GPU cuda?

**Comment by saudet** [comment]
Sure, include the relevant "-gpu" modules in your class path: http://bytedeco.org/download/
Let me know if you're having any issues getting this working though!

**Comment by decioschmitt** [comment]
Hello Saudet;

I'll try to use Dnn with gpu if you have  any example of use and you can send me . This help me. Thank you for a lot.

**Comment by decioschmitt** [comment]
> Sure, include the relevant "-gpu" modules in your class path: http://bytedeco.org/download/
> Let me know if you're having any issues getting this working though!

Hello Saudet;

I'll try to use Dnn with gpu if you have any example of use and you can send me . This help me. Thank you for a lot.

**Comment by saudet** [comment]
There is a couple in the samples directory: https://github.com/bytedeco/javacv/tree/master/samples
