### ISSUE TITLE
FFmpegFrameGrabber.start()  failed  in v1.5.1

### ISSUE THREAD

**Issue by yuyihan666** [bytedeco/javacv#1313]
FFmpegFrameGrabber.start()  failed  in  v1.5.1，v1.5  is up and running。

PipedInputStream pis；
grabber = new FFmpegFrameGrabber(pis);
grabber.start();//always waiting

**Comment by saudet** [comment]
Duplicate of #1304 and #1298

**Comment by saudet** [comment]
Try 1.5.2-SNAPSHOT with `FFmpegFrameGrabber(pis, 0)` instead of `FFmpegFrameGrabber(pis)`.
