### ISSUE TITLE
JVM crash when called FFmpegFrameGrabber.restart

### ISSUE THREAD

**Issue by Stephen-sen** [bytedeco/javacv#1314]
here is my code
`avutil.av_log_set_level(avutil.AV_LOG_ERROR);
            grabber = FFmpegFrameGrabber.createDefault(rtspUrl);
            grabber.setOption("rtsp_transport", "tcp");
            grabber.setFrameRate(5);
            grabber.start();`

`Frame frame = grabber.grabImage();
                        if (frame == null) {
                           logger.info("frame is null ");
                            grabber.restart();
                        }`

# below is some error log
 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000744e786f, pid=17940, tid=0x0000000000004834

 JRE version: Java(TM) SE Runtime Environment (8.0_221-b11) (build 1.8.0_221-b11)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.221-b11 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 V  [jvm.dll+0x1e786f]

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

---------------  T H R E A D  ---------------

Current thread (0x00000000557fe800):  JavaThread "thread-call-runner-2" [_thread_in_vm, id=18484, stack(0x00000000355c0000,0x00000000356c0000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x000000005669d080

Registers:
RAX=0x00000000557fe800, RBX=0x00000000557fe800, RCX=0x0000000000000007, RDX=0x00000000356beda0
RSP=0x00000000356becc0, RBP=0x00000000356bed70, RSI=0x0000000000000000, RDI=0x000000005669d080
R8 =0x000000005669d080, R9 =0x000000001ca54150, R10=0x0000000002f91dc4, R11=0x000000007452ce30
R12=0x0000000000000000, R13=0x0000000017670768, R14=0x00000000356beda0, R15=0x00000000557fe800
RIP=0x00000000744e786f, EFLAGS=0x0000000000010246

Top of Stack: (sp=0x00000000356becc0)
0x00000000356becc0:   00000000557fe800 0000000002fa1b3f
0x00000000356becd0:   0000000017813110 0000000017670768
0x00000000356bece0:   0000000011f30000 0000000002f91df0
0x00000000356becf0:   0000000017670768 00000000356bed70
0x00000000356bed00:   0000000000000000 00000000557fe800
0x00000000356bed10:   0000000017813110 00000000557fe800
0x00000000356bed20:   00000000356bee00 0000000017813104
0x00000000356bed30:   00000000356bed30 0000000000000000
0x00000000356bed40:   00000000356beda0 000000001769f4b8
0x00000000356bed50:   0000000000000000 0000000017670768
0x00000000356bed60:   0000000000000000 00000000356bed90
0x00000000356bed70:   00000000356bede8 0000000002f77b00
0x00000000356bed80:   0000000000000000 0000000002f87a4e
0x00000000356bed90:   000000005669d080 00000000f46c6d10
0x00000000356beda0:   000000008000d870 00000000356beda8
0x00000000356bedb0:   0000000017813104 00000000356bee00 

Instructions: (pc=0x00000000744e786f)
0x00000000744e784f:   c8 05 00 c7 83 70 02 00 00 06 00 00 00 8b 0d b6
0x00000000744e785f:   42 5d 00 ff 15 88 ab 3f 00 c6 80 94 02 00 00 01
0x00000000744e786f:   0f b6 2f c6 80 94 02 00 00 00 48 8b 7b 48 48 8b
0x00000000744e787f:   47 10 48 8b 77 08 48 83 38 00 74 15 48 8b 57 28 

Register to memory mapping:

RAX=0x00000000557fe800 is a thread
RBX=0x00000000557fe800 is a thread
RCX=0x0000000000000007 is an unknown value
RDX=0x00000000356beda0 is pointing into the stack for thread: 0x00000000557fe800
RSP=0x00000000356becc0 is pointing into the stack for thread: 0x00000000557fe800
RBP=0x00000000356bed70 is pointing into the stack for thread: 0x00000000557fe800
RSI=0x0000000000000000 is an unknown value
RDI=0x000000005669d080 is an unknown value
R8 =0x000000005669d080 is an unknown value
R9 =0x000000001ca54150 is an unknown value
R10=0x0000000002f91dc4 is at code_begin+1700 in an Interpreter codelet
method entry point (kind = native)  [0x0000000002f91720, 0x0000000002f927e0]  4288 bytes
R11=0x000000007452ce30 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x0000000017670770} 'getByte' '(J)B' in 'sun/misc/Unsafe'
R14=0x00000000356beda0 is pointing into the stack for thread: 0x00000000557fe800
R15=0x00000000557fe800 is a thread

Stack: [0x00000000355c0000,0x00000000356c0000],  sp=0x00000000356becc0,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x1e786f]
C  0x0000000002f91df0

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.misc.Unsafe.getByte(J)B+0
j  java.nio.DirectByteBuffer.get(I)B+12
j  org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma(Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIZDZI)V+513
j  org.bytedeco.javacv.Java2DFrameConverter.copy(Lorg/bytedeco/javacv/Frame;Ljava/awt/image/BufferedImage;DZLjava/awt/Rectangle;)V+246
j  org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Lorg/bytedeco/javacv/Frame;DZLjava/awt/color/ColorSpace;)Ljava/awt/image/BufferedImage;+678
j  org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Lorg/bytedeco/javacv/Frame;D)Ljava/awt/image/BufferedImage;+5
j  com.gome.ghs.fa.repository.util.FileUtil.iplToBufferedImage(Lorg/bytedeco/opencv/opencv_core/IplImage;Ljava/lang/String;Ljava/lang/String;)Ljava/awt/image/BufferedImage;+29
j  com.gome.ghs.fa.repository.FaceDirectAction.lambda$null$0(Lorg/bytedeco/opencv/opencv_core/IplImage;II)V+6
j  com.gome.ghs.fa.repository.FaceDirectAction$$Lambda$377.run()V+16
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

**Comment by saudet** [comment]
It's not crashing in restart(). I don't see anything wrong.

**Comment by Stephen-sen** [comment]
I found is below code cause,when i debug,` paintConverter.convert(frame);` cause crash;
 `public static BufferedImage iplToBufferedImage(Frame frame, String formatName, String savePath) {
		Java2DFrameConverter paintConverter = new Java2DFrameConverter();
		BufferedImage image = null;
		try{
			paintConverter.convert(frame);
			if(null!=savePath){
				ImageIO.write(image, formatName, new File(savePath+System.currentTimeMillis()+"."+formatName));
			}
		}catch (Exception e){
			e.printStackTrace();
		}
		return image;
	}`

**Comment by Stephen-sen** [comment]
but why If I not called grabber.restart(),it not carsh?

**Comment by saudet** [comment]
Does this happen only with an RTSP URL? Or does it also happen with a File?

**Comment by Stephen-sen** [comment]
my current work env is rtsp ,I find if frame is not  null,this time I restart,then skip one frame,it work ok. but if frame is null,if I called restart,jvm will  be crash.-------- 原始邮件 --------主题：Re: [bytedeco/javacv] JVM crash when called FFmpegFrameGrabber.restart (#1314)发件人：Samuel Audet 收件人：bytedeco/javacv 抄送：赵森 <963547234@qq.com>,Author Does this happen only with an RTSP URL? Or does it also happen with a File?

**Comment by Stephen-sen** [comment]
HI，I found the real reason that cause the crash.It's because I use thread handle the frame,when I restart the resource has been closed,but thead still not finished,this time when use frame,it will be crash.so I only need wait a mount,it will be ok.like this`if (frame == null) {
                            logger.info("frame is null ");
                            try {
                                Thread.sleep(5000);
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                            grabber.restart();
                            logger.info("grabber重启成功");
                        }`
