### ISSUE TITLE
Black Sidebars appear on the captured image

### ISSUE THREAD

**Issue by ahmedaomda** [bytedeco/javacv#1321]
I'm using `OpenCVFrameGrabber` to grabbe frames from my USB cam but the grabbed image has black bars appears on each side but when i try Windows Camera app it doesn't have these bars ,Is there is some configs I'm missing ?

    OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(0);
    grabber.setImageWidth(captureWidth);
    grabber.setImageHeight(captureHeight);
    grabber.start();

    Frame capturedFrame = grabber.grab();
    Java2DFrameConverter converter = new Java2DFrameConverter();
    converter.convert(capturedFrame);

**Comment by saudet** [comment]
Could you try `VideoInputFrameGrabber` instead? It usually works better than OpenCV on Windows...

**Comment by ahmedaomda** [comment]
Thank you It's really better solved the problem without modification

**Comment by saudet** [comment]
How did you solve it?

**Comment by ahmedaomda** [comment]
I just replaced the `OpenCVFrameGrabber` with `VideoInputFrameGrabber` and it did the trick I think it handles the aspect ration internally
