### ISSUE TITLE
How to init opencv?

### ISSUE THREAD

**Issue by NiaBie** [bytedeco/javacv#1322]
When I using class `Mat`(which is from `opencv`) in my code, it shows `No implementation found for long org.opencv.core.Mat.n_Mat()`. For `opencv`, it is because not initializing `opencv` before using the class `Mat`, and I can use the code below for initializing:
```
    static {
        if (!OpenCVLoader.initDebug()) {
            ...
        }
    }
```
But for `javacv`, I don't know how to initialize. I can't find the class `OpenCVLoader`. So how to init `opencv`in `javacv`?

**Comment by saudet** [comment]
It's `Loader.load(opencv_java.class)` as mentioned here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by alperdemr** [comment]
i can't initialize with Loader.load(opencv_java.class).

**Comment by saudet** [comment]
> i can't initialize with Loader.load(opencv_java.class).

What error do you get?
