### ISSUE TITLE
"Warning: Version of org.bytedeco:ffmpeg could not be found."

### ISSUE THREAD

**Issue by gaynor** [bytedeco/javacv#1326]
I have the following librarie s imported and the app builds and runs, but I get the warning mentioned above: "Warning: Version of org.bytedeco:ffmpeg could not be found."

![ffmpeg](https://user-images.githubusercontent.com/3429812/68097644-3df43c80-fe86-11e9-94aa-22284aa43fb6.PNG)

**Comment by saudet** [comment]
That's alright, if everything runs fine, you can ignore that.

**Comment by gaynor** [comment]
I was wondering if that had anything to do with how long it was taking for a service to run. Trying to merge audio and image file and the service just keeps running. Anyway to inject ffmpeg commands directly? I have a string array of commands I want to be able to run: cmd = arrayOf(
                    "-y",
                    "-loop",
                    "1",
                    "-r",
                    "1",
                    "-i",
                    File(imageFile).getCanonicalPath(),
                    "-i",
                    File(audioFile).getCanonicalPath(),
                    "-c:a",
                    "copy",
                    "-c:v",
                    "mpeg4",
                    "-s",
                    width.toString() + "x" + width,
                    "-strict",
                    "experimental",
                    "-shortest",
                    "-f",
                    "mp4",
                    "-r",
                    "2",
                    File(outputFile).getCanonicalPath()
                )

**Comment by saudet** [comment]
No, reencoding files takes time, especially on a mobile device, that's normal.

**Comment by gaynor** [comment]
Thanks for the help, greatly appreciated

**Comment by saudet** [comment]
We can use the `ffmpeg` program this way:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by gaynor** [comment]
Just what i was looking for! thank you!
