### ISSUE TITLE
FFmpegFrameRecorder.setTimestamp()

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1328]
In my code, i using the following code to record video:

 recorder.setTimestamp(timestamp);
 recorder.record(converter.convert(mainImage));

But for some video, i got exception: 
//org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -1: Could not encode video packet.

I checked the FFmpegFrameRecorder code: the exception is from this method:
avcodec_encode_video2();
But i cannot find the meaning of error code = -1. 

Can you help?

**Comment by saudet** [comment]
What is the error message that FFmpeg outputs to the console?

**Comment by xiaos** [comment]
hi
i am developing android app, i can only see this:
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -1: Could not encode video packet.

cannot see the ffmpeg error

**Comment by saudet** [comment]
Make sure you've called `FFmpegLogCallback.set()`.

**Comment by xiaos** [comment]
i will try, thanka

**Comment by xiaos** [comment]
Error: [mpeg4 @ 0x769e876b00] Invalid pts (86) <= last (86)
Error: [mpeg4 @ 0x769e876b00] Invalid pts (144) <= last (144)

**Comment by saudet** [comment]
Thanks! That just means you'll need to provide increasing values to `setTimestamp()`. We can't pass the same values twice or smaller values.

**Comment by xiaos** [comment]
Hi @saudet  thank you, but when i call 
recorder.setTimestamp(timestamp);

The timestamp is always increasing!

The exception/error not happened for all videos, it happened for some videos.

-----------------------------------------------------------
float framerate= video's framerate;
float totalTimeInSecond= video's totalTime;

int totalFrames= totalTimeInSecond*framerate;
recorder.setFrameRate((int)framerate);

for (int i = 0; i <= totalFrames; i++) {
    timestamp =  1f * i / totalFrames * totalTimeUs;

   recorder.setTimestamp(timestamp);
   reocrder.record(converter.convert(image));
}

**Comment by saudet** [comment]
Call getTimestamp() before calling setTimestamp() to make sure it never
happens.
