### ISSUE TITLE
Saving streaming frames into a RingBuffer and lately save in a file

### ISSUE THREAD

**Issue by caaiofarias** [bytedeco/javacv#1335]
Hello guys! 

I'm trying to save a streaming video in file. But, before this, i would like to save the frames in a RingBuffer, and after a time(2 mins) recover the frames and save into a file. 

i'm trying to do with a ArrayList first just for teste, but it just recorded only one frame.

It is possible ? 

`public void Record() throws org.bytedeco.javacv.FrameRecorder.Exception, Exception{
	String SOURCE_RTSP = "the_live_http_link";
	Frame frame = null;
	FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(SOURCE_RTSP);
	//CanvasFrame canvasFrame = new CanvasFrame("Camera");
	grabber.start();
	try{
	frame = grabber.grab();
	}catch(Exception e){
		e.printStackTrace();
	}
	//int i = 0;
	int countName = 0;
	boolean start = true;
			
	while(frame !=null){
		frame = grabber.grab();
		
		if (frame == null){
			continue;
		}
		
			
		grabber.getTimestamp();
		//canvasFrame.showImage(frame);
		
		if (start == true && this.list.size() < 100){ 
			this.list.add(frame);
			//System.out.print(frame);
		}
		else{
			
			FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("test"+ countName + ".mp4", 640,480);
			recorder.start();
			
			for (int i = 0; i < this.list.size(); i++ ){
				//Frame buffer = this.list.get(i);
				recorder.record(this.list.get(i));
				}
			
			this.list.clear();
			countName ++;
			recorder.stop();
			}
		}
	}
}`

**Comment by saudet** [comment]
You'll need to copy the frames. There's an example of that in this file with RECORD_LENGTH > 0:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by caaiofarias** [comment]
Thank you for reply! 
But the way you show is possible to copy the frames from a live streaming ? 

My question is because the FFmpegFrameRecorder() create a file, but how i get the Frames ? 

Sorry for asking silly questions, but i can't figure out this problem.

**Comment by caaiofarias** [comment]
Resolved, thanks

**Comment by phuchuynhStrong** [comment]
Hi @caaiofarias. I'm facing the same problem. Can you share how you deal with it ?

**Comment by caaiofarias** [comment]
> Hi @caaiofarias. I'm facing the same problem. Can you share how you deal with it ?

Hello! How are you trying to grab and record the frames ? can you explain more ?
