### ISSUE TITLE
Question: shouldn't all instances of Pointer be deallocated to release native memory?

### ISSUE THREAD

**Issue by netbrain** [bytedeco/javacv#1337]
I see that this is not the case for this line, is this causing a memory leak?

https://github.com/bytedeco/javacv/blob/da3bb9cac7fbcedb69e7a73ccb3579444ac463a3/src/main/java/org/bytedeco/javacv/OpenCVFrameConverter.java#L93

**Comment by netbrain** [comment]
Also i can't seem to find any release of memory for these two lines:
https://github.com/bytedeco/javacv/blob/6cc1da8ade97237defd904b2ba961a9f7b74471d/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L167-L168

Im guessing the releaseUnsafe method should call av_free_packet()?

**Comment by saudet** [comment]
The first one doesn't cause allocation of any native memory, so that's alright.

As for `video_pkt` and `audio_pkt`, the default allocator registers a deallocator for the garbage collector to call at some point after they become unreachable. We could deallocate them explicitly on release, but they won't cause a memory leak.

Are you having any issues with a memory leak somewhere?

**Comment by netbrain** [comment]
Well, im not sure. I think maybe I have fixed it, but needs further testing :) Any hints for how to track down memory leaks in JNI? so far I have tried BCC's memleak utility. but all in all, allocations looks fairly good. I've also tried using AspectJ and instrumenting JavaCPP's Pointer class and spying on set on the address field and using that information to create a summary of allocs & deallocs, not the greatest set of results though.. Haven't tried valgrind yet, but i guess that will be next if i still see crashes due to memory.

**Comment by saudet** [comment]
If we set, for example, the "org.bytedeco.javacpp.logger.debug" system
property to "true", it will display allocations and deallocations on the
console, but yes, we need some other tool to analyze that log. If you
create some Java code for that, please send a pull request to have it
integrated into JavaCPP itself! Thanks

**Comment by saudet** [comment]
BTW, I think I've fixed all the memory leaks occurring in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
PointerBufferPoolMXBean from @matteodg released with JavaCPP 1.5.4 should make it easier to debug.
If you still have issues with this though, please let me know!
