### ISSUE TITLE
FFmpegFrameGrabber not starting in another thread

### ISSUE THREAD

**Issue by caaiofarias** [bytedeco/javacv#1338]
Hello guys! 

i want to grab frames to a streaming video in another Thread. But when i started the thread the FFmpegFrameGrabber doens't start. Any solution ? The streaming can't pause my main thread. 

`public class Producer implements Runnable {
	private CircularQueueImplementation<Frame> buffer = new CircularQueueImplementation<>(100);
	protected static Logger logger = Logger.getLogger("aa.central");
	int maxSize;
	String SOURCE_RTSP = "streaming_link_camera";
	
	public Producer(CircularQueueImplementation<Frame> buffer, int size) {
		this.buffer = buffer;
		this.maxSize = size;
	}

	@Override
	public void run() {
		
		try{
			logger.debug("this logger show");
			avutil.av_log_set_level(avutil.AV_LOG_QUIET);
			FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(SOURCE_RTSP);
			logger.debug("this doesn't");
			//grabber.setImageHeight(480);
			grabber.setFrameRate(15);
			//grabber.setImageWidth(640);
			
			try{
			grabber.start();
			}
			catch(Exception e){
				e.printStackTrace();
			}
			while(true){
				synchronized (this) {
					Frame frame = grabber.grab().clone();
					long timestamp = frame.timestamp;
					//canvas.showImage(frame);
					if(frame == null) continue;
					
					
					buffer.enqueue(frame);
					System.out.println(buffer.getCurrentQueueSize());
					
					}
				}
			}
		catch (Exception e){
			e.printStackTrace();
			}
	}`

**Comment by caaiofarias** [comment]
- Update - 

i wait the application and start to grab frames 6 minutes after i run.

**Comment by saudet** [comment]
Java makes no guarantees that all threads will get any CPU time at all when
they have to synchronize. You'll need to provide some mechanism for that.

**Comment by caaiofarias** [comment]
It's working now, but the grabber its taking 6 minutes to start grabbing frames... Any Idea?

**Comment by saudet** [comment]
Maybe a problem with your network? Check the log!

**Comment by caaiofarias** [comment]
I guess not, because when i start in main thread on a static method it works. But when i create another thread, its take this time. 

`public static void main(String[] args){
 Producer producer = new Producer(buffer);
new Thread t = (producer);
producer.start(); //this works!!

// but when i call this in another thread, takes much time;
}`

**Comment by caaiofarias** [comment]
@saudet  sorry by inconvenience, but the problem is when i build the jar file in ant builder. Do you have any idea ? I'm really stucked on this.

**Comment by saudet** [comment]
Like I said, Java doesn't make any guarantees that a thread is going to get any CPU time at all. You need to provide a mechanism for that.

**Comment by saudet** [comment]
And don't use Ant to build, use Maven.

**Comment by caaiofarias** [comment]
I know that, and i'm using concurrency to solve this. But the problem is before that.  When i generate the jar file and execute it, the Thread(i tested in main too) simply stop in this line and back after a long time: 


`FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://host:passwd@ip/live4.sdp");`

**Comment by saudet** [comment]
What does FFmpeg's log say? Make sure you've called `FFmpegLogCallback.set()` if you don't see anything in the log.

**Comment by saudet** [comment]
Also make sure to set maximumSize to 0 (see issue #1304), for example, this way:
```java
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://host:passwd@ip/live4.sdp", 0);
```

**Comment by caaiofarias** [comment]
The log only start after the time (4 min in media).

**Comment by caaiofarias** [comment]
It is really strange, the delay is when i instantiate the FFmpegGrabber and deploy in ant builder

**Comment by saudet** [comment]
Also make sure to set the "org.bytedeco.javacpp.logger.debug" system property to "true".

**Comment by caaiofarias** [comment]
the error is not in your lib saudet! The delay is because the loading the jars files of libs(ffmpeg, opencv,javacv, etc). 

closed

**Comment by saudet** [comment]
I see, so this is duplicate of https://github.com/bytedeco/javacpp/issues/287. For some reason, loading libraries on Android is really slow in some cases. This doesn't happen here on my devices, so I still don't know what cause is.

**Comment by caaiofarias** [comment]
It is not on Android, but the ant build are copying all jar files on a fat jar, and i guess the delay is when unpack the jars files.

**Comment by saudet** [comment]
In that case we can reduce the amount of files to package:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by saudet** [comment]
The changes in commit https://github.com/bytedeco/javacpp/commit/af0e5131174db1fd8c95261c9f6878cde3bab2c4 should also help with this.

**Comment by caaiofarias** [comment]
Save a lot of time now! Thank you so much man!!!! 

I am having only one problem from loading classes, but i guess this will be fixed when you update the version right ?

**Comment by caaiofarias** [comment]
@saudet , this work in a armv7 too ? now i need put on a armv7 arch. 

If not, any tutorial how work on this ? i not found anything

**Comment by saudet** [comment]
> I am having only one problem from loading classes, but i guess this will be fixed when you update the version right ?

What problem are you referring to? Gradle not working well with snapshots? It doesn't have that issue with released artifacts, yes.

> @saudet , this work in a armv7 too ? now i need put on a armv7 arch.
> 
> If not, any tutorial how work on this ? i not found anything

Sure, binaries are available, something like this: https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

**Comment by caaiofarias** [comment]
It was my mistake. I'm installing the jars manually, and running in a linux, but now i need to run in a arm7 architeture. I'm put all jars with arm but still the error continues 

`java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1174)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1107)
	at org.bytedeco.ffmpeg.avformat.Read_packet_Pointer_BytePointer_int.<clinit>(Read_packet_Pointer_BytePointer_int.java:44)
	at org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.java:340)
	at cameras.recording.Producer.run(Producer.java:29)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by saudet** [comment]
Be sure to use the snapshots: http://bytedeco.org/builds/
The slow loading problem has been fixed in commit https://github.com/bytedeco/javacpp/commit/af0e5131174db1fd8c95261c9f6878cde3bab2c4

**Comment by saudet** [comment]
Please let me know if this latest fix doesn't solve the issue you're describing though. Thanks!

**Comment by caaiofarias** [comment]
Yes! It's much faster now.

Thanks for listening saudet!
