### ISSUE TITLE
How to record with 3 or more cameras 

### ISSUE THREAD

**Issue by Claudio-Espinosa** [bytedeco/javacv#1339]
i´m developing an app to record video, and i need to record with 3 or more cameras, so i try 2 cameras and works good, but with 3, in the console appaer this: 

[ WARN:2] videoio(MSMF): can't grab frame. Error: -2147483638

i´m use the 1.5.2 version of javacv in w10 
the cameras are logitech 920

**Comment by saudet** [comment]
Try to use DSHOW instead of MSMF:
https://answers.opencv.org/question/197480/change-camera-size-fails-on-windows-works-on-linux/

**Comment by saudet** [comment]
Specifically, using 3 or more grabbers like this should work:
```java
grabber1 = new OpenCVFrameGrabber(CAP_DSHOW + 0);
grabber2 = new OpenCVFrameGrabber(CAP_DSHOW + 1);
grabber3 = new OpenCVFrameGrabber(CAP_DSHOW + 2);
...
```
Let me know if you are still having problems with that though.

**Comment by Claudio-Espinosa** [comment]
i tried with the main library of your solution (opencv), but the problem is the same, i tried in java and in python
the version of opencv is 3.3.0 and my cameras are logitech c920, also i try to record with xuggler and works, but the resolution of the output video is low (320x240) and i need more definition to record video.

**Comment by saudet** [comment]
`VideoInputFrameGrabber` usually works better on Windows, so try to use that one instead.

**Comment by Claudio-Espinosa** [comment]
its ok, i'll try. thank you! have a nice day
