### ISSUE TITLE
Change log google code to javacv

### ISSUE THREAD

**Issue by olyjosh** [bytedeco/javacv#134]
I'm new to javacv and the project code I'm laying my hands was writing when javacv was still hosted on google code. So I couldn't get where these classes and packages in the new javacv I just downloaded

import com.googlecode.javacv.cpp.*;
//import org.bytedeco.javacpp.*;
import com.googlecode.javacv.cpp.videoInputLib.*;

import static com.googlecode.javacv.cpp.opencv_core.*;
import static com.googlecode.javacv.cpp.opencv_imgproc.*;
import static com.googlecode.javacv.cpp.opencv_objdetect.*;
import static com.googlecode.javacv.cpp.opencv_highgui.*;
import static com.googlecode.javacv.cpp.avutil.*;

**Comment by saudet** [comment]
There's a summary about all that here: http://bytedeco.org/news/2014/04/28/first-release/

**Comment by olyjosh** [comment]
Thanks for that, but I still can't compile my code as there is no part of the that I can really get these from

import org.bytedeco.javacpp.videoInputLib.*;
  private CvHaarClassifierCascade classifier;
  private CvMemStorage storage;

Any more change log some where

**Comment by saudet** [comment]
That looks alright. Could you provide the error that you get?

**Comment by olyjosh** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniObjdetect in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)Java Result: 1
BUILD SUCCESSFUL (total time: 13 seconds)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)

**Comment by saudet** [comment]
That's probably related to ProGuard. Try to follow the instructions here:
https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV

**Comment by olyjosh** [comment]
I guess proguard is only for androids. I'm actually developing a windows app and not android. 

import org.bytedeco.javacpp.videoInputLib.*;
private CvHaarClassifierCascade classifier;
private CvMemStorage storage;

Most of these line are underlined red in Netbeans IDE - Like those classes doesn't exist in the java cv / open cv ... as the name that I'm using

**Comment by saudet** [comment]
Right, so update the imports. Details here, as previously mentioned:
http://bytedeco.org/news/2014/04/28/first-release/

**Comment by olyjosh** [comment]
Like you earler redirect me to this link and I have done that. But one thing I'm sure of is ther are some changes that are not documented there on that page. 
Take a look at the image where I expanded the library using Netbeans IDE. I'm expecting "org.bytedeco.javacpp.videoInputLib" to be listed here.
![capture](https://cloud.githubusercontent.com/assets/8569844/7782849/66f26054-0123-11e5-8d38-92175435b8b6.JPG)

But it wasn't. Correct me on this if I'm wrong

These were never documented on that link you gave for change logs

**Comment by saudet** [comment]
You're going to need to include in your class path the presets as well:
https://github.com/bytedeco/javacpp-presets/

**Comment by olyjosh** [comment]
Thanks, javacv preset solve most of these. However, I have these lines of code according Dr. Andrew Davison's implementations on http://fivedots.coe.psu.ac.th/~ad/jg/nui08/index.html 

These are not what they use to be 
1.
 private IplImage picGrab(FrameGrabber grabber, int ID)
  {
    IplImage im = null;
    try {
      im = grabber.grab();  // take a snap
    }
    catch(Exception e) 
    {  System.out.println("Problem grabbing image for camera " + ID);  }
    return im;
  }  // end of picGrab()

In this case : grabber.grab(); doesn't return IplImage

2.
public void paintComponent(Graphics g)
  /* Draw the image, the rectangle (and crosshairs) around a detected
     face, and the average ms snap time at the bottom left of the panel. 
     Show the currently recognized face name at the bottom middle.
     This time does NOT include the face detection task.
  */
  { 
    super.paintComponent(g);
    Graphics2D g2 = (Graphics2D) g;

    if (snapIm != null)
      g2.drawImage(snapIm.getBufferedImage(), 0, 0, this);

    drawRect(g2);
    writeStats(g2);
    writeName(g2);
  } // end of paintComponent()

in this case IplImage im doesn't seems to  have a method getBufferedImage() as it is in g2.drawImage(snapIm.getBufferedImage(), 0, 0, this);

Please what are my equivalence

**Comment by saudet** [comment]
This is all explained here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by olyjosh** [comment]
Thanks
