### ISSUE TITLE
OpenCVFrameConverter.convertToIplImage  possible to leak memory?

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1342]
The soruce code below, may i know in which case, it will use frame.opaque is Iplimage? And if isEqual(frame, this.img) is false, it will create a new IplImage, then how about the existing/previous iplimage? nowhere to release the iplimage.

    public IplImage convertToIplImage(Frame frame) {
        if (frame != null && frame.image != null) {
            if (frame.opaque instanceof IplImage) {
                return (IplImage)frame.opaque;
            } else {
                if (!isEqual(frame, this.img)) {
                    int depth = getIplImageDepth(frame.imageDepth);
                    this.img = depth < 0 ? null : IplImage.create(frame.imageWidth, frame.imageHeight, depth, frame.imageChannels, new Pointer(frame.image[0].position(0))).widthStep(frame.imageStride * Math.abs(frame.imageDepth) / 8).imageSize(frame.image[0].capacity() * Math.abs(frame.imageDepth) / 8);
                }

                return this.img;
            }
        } else {
            return null;
        }
    }

**Comment by saudet** [comment]
`frame.opaque` is going to be `IplImage` if it was previously converted from an `IplImage`. Unless managed by a `PointerScope`, the objects are going to get released eventually by the garbage collector: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/
