### ISSUE TITLE
cvLoadImage throw exception

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1343]
Hi 

I am using cvLoadImage to load image, but i got an exception:

OpenCV(4.0.1) /home/travis/build/javacpp-presets/opencv/cppbuild/android-arm64/opencv-4.0.1/modules/core/src/array.cpp:3293: error: (-2:Unspecified error) Unknown object type in function 'cvClone'

Any suggestion? thanks.

**Comment by saudet** [comment]
I think that's been fixed. In any case, please upgrade to a newer version.

**Comment by xiaos** [comment]
@saudet   may i know in which verion it's fixed? i am using 1.5 now.

**Comment by saudet** [comment]
So try 1.5.2.

**Comment by smietek92** [comment]
Hi, 
I have the same problem despite that i am using 1.5.2 version of javacv-platform.
RuntimeException is thrown on `org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage` method. Do you have any advice how i can solve this problem?

**Comment by saudet** [comment]
Please try with OpenCV 4.2.0. I think it's related to issues on Windows that have been fixed.

**Comment by hongshunanhai** [comment]
> Hi,
> I have the same problem despite that i am using 1.5.2 version of javacv-platform.
> RuntimeException is thrown on `org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage` method. Do you have any advice how i can solve this problem?

do you find the method to fix it?

**Comment by hongshunanhai** [comment]
> Hi
> 
> I am using cvLoadImage to load image, but i got an exception:
> 
> OpenCV(4.0.1) /home/travis/build/javacpp-presets/opencv/cppbuild/android-arm64/opencv-4.0.1/modules/core/src/array.cpp:3293: error: (-2:Unspecified error) Unknown object type in function 'cvClone'
> 
> Any suggestion? thanks.

do you find the methond? I have the same question!!

**Comment by GeneralLHW** [comment]
I tried. It's OK to load the pictures on the local disk, but if I access the remote pictures like HTTPS, this problem will occur. I also use opencv (4.1.2), javacv1.5.2

**Comment by saudet** [comment]
@GeneralLHW That's normal, OpenCV doesn't support that.

**Comment by saudet** [comment]
@hongshunanhai Like I said, this has been fixed with OpenCV 4.2.0. Please upgrade to JavaCV 1.5.3.

**Comment by GeneralLHW** [comment]
I upgraded to javacv1.5.3 and opencv 4.3.0, but there are still exceptions. The errors are as follows：
`
java.lang.RuntimeException: OpenCV(4.3.0) /Users/travis/build/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv-4.3.0/modules/core/src/array.cpp:3293: error: (-2:Unspecified error) Unknown object type in function 'cvClone'

	at org.bytedeco.opencv.global.opencv_core.cvClone(Native Method)
	at org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage(opencv_imgcodecs.java:37)
	at org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage(opencv_imgcodecs.java:34)
`

**Comment by saudet** [comment]
@GeneralLHW Please attach an image file here that doesn't work.

**Comment by GeneralLHW** [comment]
@saudet https://b612kaji-sns-prod.oss-cn-beijing.aliyuncs.com/activity/newyear/00141d6d5d094403bfb38fba98cbe6c0/4.jpg
https://b612kaji-sns-prod.oss-cn-beijing.aliyuncs.com/activity/newyear/00141d6d5d094403bfb38fba98cbe6c0/5.jpg

**Comment by saudet** [comment]
You're right. It looks like this hasn't been fixed yet. However, the C API is deprecated, so it's unlikely that anyone will ever fix this. Please consider using `imread()` instead.

**Comment by GeneralLHW** [comment]
When I use imread(), throwing the following exception. If I access the data of the local disk, there is no problem
`
[libx264 @ 0x7f8422201400] -qscale is ignored, -crf is recommended.
[libx264 @ 0x7f8422201400] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f8422201400] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x7f8422201400] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=10.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to '/Users/mac/Desktop/B612/1bc/22356.mp4':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 746x912, q=2-31, 400 kb/s, 25 fps, 12800 tbn, 25 tbc
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 64 kb/s
java.lang.NullPointerException
	at org.bytedeco.opencv.opencv_core.AbstractArray.createBuffer(AbstractArray.java:42)
	at org.bytedeco.opencv.opencv_core.AbstractArray.createBuffer(AbstractArray.java:34)
	at org.bytedeco.javacv.OpenCVFrameConverter.convert(OpenCVFrameConverter.java:166)
`

**Comment by saudet** [comment]
I see, it works fine on Linux, but fails on Windows. This is a bug in OpenCV that appears to have not been fixed yet, see https://github.com/opencv/opencv/issues/4727. Please report your issue upstream to them! Thanks

**Comment by xiaos** [comment]
But for me it's different, I am using  javacv 1.5.3 on Android, now still got this issue. 

javacv/javacv/javacpp-presets/opencv/cppbuild/android-arm64/opencv-4.3.0/modules/core/src/array.cpp:3293: error: (-2:Unspecified error) Unknown object type in function 'cvClone' 

org.bytedeco.opencv.global.opencv_core.cvClone (opencv_core.java)
org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage (opencv_imgcodecs.java:37)
org.bytedeco.opencv.helper.opencv_imgcodecs.cvLoadImage (opencv_imgcodecs.java:34)

**Comment by saudet** [comment]
@xiaos If the same issue probably happens on Android. Make sure to report your findings upstream! Thanks

**Comment by saudet** [comment]
@xiaos Actually, `cvLoadImage()` is no longer available in OpenCV. 
What we need to test is `imread()`. What do you get if you use `imread()`?
