### ISSUE TITLE
avformat_write_header error() error -22: Could not write header to 'null'

### ISSUE THREAD

**Issue by liuji789** [bytedeco/javacv#1347]
when FFmpegFrameRecorder start ，FFmpegFrameGrabber  用的海康的摄像头

**Comment by saudet** [comment]
You'll need to give it a path or a URL that exists and that you have access to.

**Comment by saudet** [comment]
It's also possible that FFmpegFrameGrabber doesn't support your camera. Try to use OpenCVFrameGrabber or VideoInputFrameGrabber and let me know if you still have problems. Thanks
