### ISSUE TITLE
Selecting a Different Video Stream with FFmpegFrameGrabber

### ISSUE THREAD

**Issue by noahl98** [bytedeco/javacv#135]
I'm trying to record frames from an example stream but it seems to be recording at the lowest possible quality/resolution. When I call `frameGrabber.start();` , it prints this:

    Input #0, hls,applehttp, from 'http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8':
      Duration: 00:30:01.00, start: 10.000000, bitrate: 0 kb/s
      Program 0 
        Metadata:
          variant_bitrate : 200000
        Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 22050 Hz, mono, fltp, 1 kb/s
        Metadata:
          variant_bitrate : 200000
        Stream #0:1: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m/smpte170m/bt709), 192x144, 14.99 fps, 14.99 tbr, 90k tbn, 180k tbc
        Metadata:
          variant_bitrate : 200000
      Program 1 
        Metadata:
          variant_bitrate : 311111
        Stream #0:2: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m/smpte170m/bt709), 320x240, 29.97 fps, 29.97 tbr, 90k tbn, 180k tbc
        Metadata:
          variant_bitrate : 311111
        Stream #0:3: Audio: aac (LC) ([15][0][0][0] / 0x000F), 22050 Hz, mono, fltp, 1 kb/s
        Metadata:
          variant_bitrate : 311111
      Program 2 
        Metadata:
          variant_bitrate : 484444
        Stream #0:4: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m/smpte170m/bt709), 480x360, 29.97 fps, 29.97 tbr, 90k tbn, 180k tbc
        Metadata:
          variant_bitrate : 484444
        Stream #0:5: Audio: aac (LC) ([15][0][0][0] / 0x000F), 22050 Hz, mono, fltp, 1 kb/s
        Metadata:
          variant_bitrate : 484444
      Program 3 
        Metadata:
          variant_bitrate : 737777
        Stream #0:6: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p(tv, smpte170m/smpte170m/bt709), 480x360, 29.97 fps, 29.97 tbr, 90k tbn, 180k tbc
        Metadata:
          variant_bitrate : 737777
        Stream #0:7: Audio: aac (LC) ([15][0][0][0] / 0x000F), 22050 Hz, mono, fltp, 1 kb/s
        Metadata:
          variant_bitrate : 737777

As you can see, there are multiple streams with different bitrates, resolutions and frame rates. I was wondering if it was possible to select a different stream rather than default to the first one.

**Comment by saudet** [comment]
That's easy enough to fix. I'll push some changes for that right away. Thanks for the feedback!

**Comment by noahl98** [comment]
Perfect. Thanks so much.

**Comment by noahl98** [comment]
Actually, when I tried building from source, it seems that FFmpegFrameGrabber was not included in the build. Is there a special option i have to add on to `mvn install`?

**Comment by saudet** [comment]
Yes, use the “ffmpeg“ profile, via the -P command line option or in any
other way

**Comment by saudet** [comment]
Methods to get and set the audio and video streams are now part of version 1.0. Enjoy!
