### ISSUE TITLE
Memory leak when I'm using surf or sift to extract image features in linux environment.

### ISSUE THREAD

**Issue by DangerousPrayer** [bytedeco/javacv#1352]
version:
```xml
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.2</version>
        </dependency>
```

Hello,
I use SIFT to extract image features. 
It runs perfectly when i test it at macOS. But when I publish the application to linux environment, the memory raises quickly and never reduces. 
After call about 30 times using single thread, memory（4G） is almost full.

I has tried Ubuntu and Centos, they both have same problem.
I wonder whether there is a problem with my usage or there is a memory leak in the underlying C + + algorithm?

here is my code:
```java
import org.opencv.core.*;
import org.opencv.features2d.BFMatcher;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.xfeatures2d.SIFT;

        Mat mat = bufferedImage2Mat(bufferedImage);
        Mat descriptor = Mat.eye(mat.size(), CvType.CV_32F);
        MatOfKeyPoint keyPoints = new MatOfKeyPoint();
        int nFeatures = 0;
        int nOctaveLayers = 3;
        float contrastThreshold = 0.03f;
        int edgeThreshold = 10;
        float sigma = 1.6f;
        SIFT sift = SIFT.create(nFeatures, nOctaveLayers, contrastThreshold, edgeThreshold, sigma);

        sift.detect(mat, keyPoints);
        sift.compute(mat, keyPoints, descriptor);

//i call every method that might be free memory, but these methods doesn't work.
        sift.clear();
        mat.release();
        keyPoints.release();
```
```java
    public static Mat bufferedImage2Mat(BufferedImage image) {
        try(ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream()){
            ImageIO.write(image, "jpg", byteArrayOutputStream);
            MatOfByte matOfByte = new MatOfByte(byteArrayOutputStream.toByteArray());
            Mat imdecode = Imgcodecs.imdecode(matOfByte, Imgcodecs.IMREAD_UNCHANGED);
            matOfByte.release();
            return imdecode;
        }catch (Exception e){
            log.error(e);
            return null;
        }
    }
```

Remarks：
I dumped java heap memory. It only 100M while the RSS is almost 4G. So I thought it should come from native methods.
Thanks in advance, I can provide more information.

**Comment by saudet** [comment]
Make sure to deallocate all objects as soon as you don't need them. We can do that relatively easily with PointerScope. There is an example of that in this post: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by DangerousPrayer** [comment]
> Make sure to deallocate all objects as soon as you don't need them. We can do that relatively easily with PointerScope. There is an example of that in this post: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

Thank you very much!

But i still have some question.
The objects i use are not the implementation of Pointer interface.
org.opencv.core.Mat and org.opencv.xfeatures2d.SIFT
how could PointerScope manage them?

I found there are 2 classes: 
org.opencv.xfeatures2d.SIFT and org.bytedeco.opencv.opencv_xfeatures2d.SIFT

Should I use the second one?

**Comment by saudet** [comment]
Unfortunately, the official Java API doesn't support something like PointerScope. If you need to use that API, you'll have to hunt down any objects it allocates and make sure to deallocate them all manually.

If you can switch to the C++ API as mapped by JavaCPP, then yes `org.bytedeco.opencv.opencv_xfeatures2d.SIFT` would be the class for SIFT.

**Comment by DangerousPrayer** [comment]
> Unfortunately, the official Java API doesn't support something like PointerScope. If you need to use that API, you'll have to hunt down any objects it allocates and make sure to deallocate them all manually.
> 
> If you can switch to the C++ API as mapped by JavaCPP, then yes `org.bytedeco.opencv.opencv_xfeatures2d.SIFT` would be the class for SIFT.

oh, I see.
Thanks agin!
