### ISSUE TITLE
ffmpegframefilter only works if i do frameGrabber.grabImage

### ISSUE THREAD

**Issue by nbendix** [bytedeco/javacv#1354]
Hi,
on 1.5.2 on android.

I am using framegrapper, framerecorder and framefilter to alter mp4.

If i dont use filter, and simply record my grab, all works fine.

For my filter to work, i have to grabImage. And then loose my audio. (i have tried various combinations of grab(), grabFrame, ... image properties are not set when i debug)

this is my complete method with imagegrab: 
File directory = new File(Environment.getExternalStorageDirectory() + File.separator + "test");
        String outputFilePath = directory.getAbsolutePath() + File.separator + "out.mp4";
        String inputFilePath = directory.getAbsolutePath() + File.separator + "in.mp4";

        FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(inputFilePath);
        frameGrabber.setFormat("mp4");
        frameGrabber.setPixelFormat(AV_PIX_FMT_NV21);

        frameGrabber.start();

        
        if (frameGrabber.getLengthInTime() > 0) {
        
            int width = frameGrabber.getImageWidth();
            int height = frameGrabber.getImageHeight();
            int channels = frameGrabber.getAudioChannels();
            
            FFmpegFrameRecorder frameRecorder = new FFmpegFrameRecorder(outputFilePath, width, height, channels);        
            
            int frameRate = (int) frameGrabber.getFrameRate();
            frameRecorder.setFrameRate(frameRate);
            
            frameRecorder.setSampleRate(frameGrabber.getSampleRate());
            frameRecorder.setAudioBitrate(frameGrabber.getAudioBitrate());
            frameRecorder.setVideoBitrate(frameGrabber.getVideoBitrate());            
            frameRecorder.setPixelFormat(AV_PIX_FMT_YUV420P);
            frameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
            frameRecorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);

            String watermark = "movie=" + directory.getAbsolutePath() + "/img.png[img];[in][img]overlay,format=pix_fmts=bgr24";

            filter = new FFmpegFrameFilter(watermark, width, height);
            filter.setPixelFormat(AV_PIX_FMT_NV21);

            frameRecorder.start();
            while (true) {
                Frame frame = frameGrabber.grabImage();

                if (frame != null) {
                    try {
                        Frame frame2;
                        filter.start();
                        filter.push(frame);
                        while ((frame2 = filter.pull()) != null) {
                            frameRecorder.record(frame2);                            
                        }
                        filter.stop();
                    } catch (FrameFilter.Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    break;
                }
            }
            frameRecorder.setMetadata(frameGrabber.getMetadata());
            // Stops the recorder
            frameRecorder.stop();
            frameRecorder.release();
            // Stops the filter
            //frameFilter.stop();
            filter.close();
            //frameFilter.release();
            // Stops the reader (grabber)
            frameGrabber.stop();
            frameGrabber.release();

        }

I would like a solution where filter and audio works.

Thanks

**Comment by saudet** [comment]
If you don't need to filter your audio frames, don't pass them to the filter, and just record them.

**Comment by nbendix** [comment]
So record filtered video frames and audio separately?

Have tried that. But without luck, do you know of any similar case I can look at?

**Comment by saudet** [comment]
Yes, this works just fine: https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java
