### ISSUE TITLE
Illegal class file: Class module-info is missing a super type - when using in Android

### ISSUE THREAD

**Issue by sAArBu** [bytedeco/javacv#1358]
Hi,
I am trying to use JavaCV in my android app.
I added the following line to my build.gradle file:
```
dependencies {
    compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.2'
}
```

The gradle sync is successful but when I try to build the project (BuildAPK or run the project) I get the following error:
```
Illegal class file: Class module-info is missing a super type.
Message{kind=ERROR, text=Illegal class file: Class module-info is missing a super type., sources=[C:\Users\User\.gradle\caches\modules-2\files-2.1\org.bytedeco\javacv-platform\1.5.2\776b154cb89fe616c142a3f5ce054ac0d34c5216\javacv-platform-1.5.2.jar], tool name=Optional.of(D8)}
```

![image](https://user-images.githubusercontent.com/30981167/71023026-8d2abf80-210a-11ea-9517-e33b85133d89.png)

I tried to clean and rebuild but the issue persists. 
SI also tried the following and got the exact same errors:
* Using `implementation` instead of `compile`:
    ```
    dependencies {
       implementation group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.2'
    }
    ```
*Use version 1.5.1
    ```
    dependencies {
        compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.1'
    }
    ```
* Build only specific libraries for specific platforms:
    ```
    implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.2'
    implementation group: 'org.bytedeco', name: 'javacpp', version: '1.5.2'

    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.2.1-1.5.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco', name: 'ffmpeg', version: '4.2.1-1.5.2', classifier: 'android-arm64'

    implementation group: 'org.bytedeco', name: 'opencv', version: '4.1.2-1.5.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco', name: 'opencv', version: '4.1.2-1.5.2', classifier: 'android-arm64'
    ```
* Added the jars manually as explained in `Manual Installation`

The application is the most simple app (MainActivity and a layout with "hello world" TextView and 2 buttons that do nothing), with no other external libraries 

I am attaching my app build.gradle file and the build stack-trace log.

[build.gradle.txt](https://github.com/bytedeco/javacv/files/3974823/build.gradle.txt)
[stacktrace.txt](https://github.com/bytedeco/javacv/files/3974824/stacktrace.txt)

Any help would be appreciated,
Thanks,
Saar

**Comment by saudet** [comment]
That's just an issue with old versions of Android Studio. Make sure to update to the latest version.

**Comment by sAArBu** [comment]
I am using AndroidStudio 3.5.3 (Windows, 64bit version). 
Its the newest version - https://developer.android.com/studio.

I am really stuck and will appreciate any help,
Saar

**Comment by saudet** [comment]
You might need to upgrade your project files as well. Anyway, those
module-info.class files are not needed so you can just remove them from the
JAR files. It will work fine.

**Comment by sAArBu** [comment]
Upgrading the project file did the trick... 

Thanks again for your help!
