### ISSUE TITLE
Publish video stream to RTMP server

### ISSUE THREAD

**Issue by zouyongdang** [bytedeco/javacv#136]
Hi Samuel. I'm using your library and `RecordActivity` on Android and it works perfectly for recording video to local mp4 file. But I could not get it work for publishing the video stream to RTMP server. Is there anything else I should do except for changing the ffmpeg_link to a rtmp url? 
I tried some other examples like [this one](https://github.com/vanevery/JavaCV-0.5-Stream-Test) and [this one](https://github.com/vanevery/JavaCV_0.3_stream_test), and some others, but all of them are outdated since the upgrading of the JavaCV. Would you give me some tips?
I think the url I used is fine since I could publish video stream with the url through ffmpeg command line.

**Comment by cranehovers** [comment]
I hava change the ffmpeg_link to a rtmp url，and success……

**Comment by saudet** [comment]
If it works on the command line with `ffmpeg`, you should try to use the same settings with `FFmpegFrameRecorder`. The culprit is usually the format. What happens if you try the "mp4" format instead of "flv", for example?

**Comment by zouyongdang** [comment]
@saudet What do you mean by culprit? I checked the output of ffmpeg command line and did not see it. Anyway, this is the command I use in my terminal 
`ffmpeg -re -i ~/Downloads/417-foundation.m4v -acodec copy -vcodec copy -f flv rtmp_url`. 
417-foundation.m4v is just a video I downloaded to my disk. And here is the output:

```
ffmpeg version 2.4.3-tessus Copyright (c) 2000-2014 the FFmpeg developers
  built on Nov  3 2014 23:01:10 with Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
  configuration: --cc=/usr/bin/clang --prefix=/Users/tessus/data/ext/ffmpeg/sw --as=yasm --extra-version=tessus --disable-shared --enable-static --disable-ffplay --enable-gpl --enable-pthreads --enable-postproc --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-libspeex --enable-bzlib --enable-zlib --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libxavs --enable-libsoxr --enable-libwavpack --enable-version3 --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvpx --enable-libgsm --enable-libopus --enable-libmodplug --enable-fontconfig --enable-libfreetype --enable-libass --enable-libbluray --enable-filters --disable-indev=qtkit --disable-indev=x11grab_xcb --enable-runtime-cpudetect
  libavutil      54.  7.100 / 54.  7.100
  libavcodec     56.  1.100 / 56.  1.100
  libavformat    56.  4.101 / 56.  4.101
  libavdevice    56.  0.100 / 56.  0.100
  libavfilter     5.  1.100 /  5.  1.100
  libswscale      3.  0.100 /  3.  0.100
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  0.100 / 53.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/Chris/Downloads/417-foundation.m4v':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2013-06-17 04:22:22
    encoder         : HandBrake 0.9.5 2011010300
  Duration: 00:11:06.11, start: 0.000000, bitrate: 233 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 640x400, 132 kb/s, 9.86 fps, 25 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2013-06-17 04:22:22
      encoder         : JVT/AVC Coding
    Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 98 kb/s (default)
    Metadata:
      creation_time   : 2013-06-17 04:22:22
Output #0, flv, to 'rtmp_url':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    encoder         : Lavf56.4.101
    Stream #0:0(und): Video: h264 ([7][0][0][0] / 0x0007), yuv420p, 640x400, q=2-31, 132 kb/s, 9.86 fps, 1k tbn, 90k tbc (default)
    Metadata:
      creation_time   : 2013-06-17 04:22:22
      encoder         : JVT/AVC Coding
    Stream #0:1(eng): Audio: aac ([10][0][0][0] / 0x000A), 48000 Hz, mono, 98 kb/s (default)
    Metadata:
      creation_time   : 2013-06-17 04:22:22
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
```

Wish this would help.

**Comment by zouyongdang** [comment]
@cranehovers I only have one url for testing and I'm not sure what will happen if several people push to the same url at the same time.

**Comment by saudet** [comment]
So it looks like your server needs H264 and AAC, and everything should work if you add these two lines before `recorder.start()`:
```java
        recorder.setFormat("flv");
        recorder.setVideoCodec(AV_CODEC_ID_H264);
        recorder.setAudioCodec(AV_CODEC_ID_AAC);
```

**Comment by cranehovers** [comment]
recorder.setFormat("flv");
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);

then，there was nothing be pushed

**Comment by cranehovers** [comment]
while add"recorder.setVideoCodec(AV_CODEC_ID_H264); "    before recorder.start(),recorder.start() will breakout.

**Comment by zouyongdang** [comment]
@saudet Tried that, still not working. The url is "rtmp://pub.z1.glb.pili.qiniup.com/zhibodang/553e0ee9d409d2292f000038?key=5b4b103461a67053".
@cranehovers You are welcomed to have a try. Thank you guys in advance.

**Comment by cranehovers** [comment]
That may be the transcoding fails,I tried that，The transcoding performance is very low.
then,you‘ld add like this:

        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);

**Comment by saudet** [comment]
Could you check the error message returned by FFmpeg on the console? You'd have to do it outside Android...

**Comment by zouyongdang** [comment]
It maybe a little late, but for anyone who sees this, I found that I have to change the value of  `RECORD_LENGTH` from 10 to 0, otherwise the record will never get called in the onPreviewFrame method.

**Comment by zouyongdang** [comment]
@saudet It seems in the terminal, it works quite fine. There is no error message.

**Comment by saudet** [comment]
Good to know it's working now. Thanks for letting us know what the problem was!

**Comment by saudet** [comment]
FYI, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
