### ISSUE TITLE
Video rotation and mirror effect

### ISSUE THREAD

**Issue by donrivo** [bytedeco/javacv#1361]
Hi,

i have a problem with a video. If i open the video with a chrome, firefox or safari, the video postition is not the same.

Chrome: Vertical
Firefox: Horizontal
Safaria: Vertical and Mirror effect.

The video was recorded with an apple mobile.

I need save a frame as image, but i don't now de correct position, or if i should rotate the image.

I can get the rotation, getVideoMetadata("rotate"), but which is the parameter that contains mirror effect? displaymatrix: rotation of -90.00 degrees? can i get this parameter?

Video metadata:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './MediaFile_1575446699.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2019-12-04T08:04:41.000000Z
  Duration: 00:00:05.10, start: 0.000000, bitrate: 529 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 63 kb/s (default)
    Metadata:
      creation_time   : 2019-12-04T08:04:41.000000Z
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 568x320, 459 kb/s, 29.99 fps, 29.97 tbr, 600 tbn, 1200 tbc (default)
    Metadata:
      rotate          : 90
      creation_time   : 2019-12-04T08:04:41.000000Z
      handler_name    : Core Media Video
    Side data:
      displaymatrix: rotation of -90.00 degrees

Thanks!

**Comment by saudet** [comment]
There are `AVFrameSideData` and `AVPacketSideData` data structures as part of FFmpeg's API, so it's probably somewhere in there. It shouldn't be too hard to update `FFmpegFrameGrabber` to return that information. Please give it a try and let me know if you encounter any problems! I will be there to help

**Comment by donrivo** [comment]
Hi,

i have checked FFmpegFrameGrabber object methods, but i don't find AV methods to get this information. can i get the "side data" informatión using another object?

thanks!

**Comment by saudet** [comment]
Like I said, it's not currently part of `FFmpegFrameGrabber`. Someone will need to update it for that.

**Comment by saudet** [comment]
I've added `FFmpegFrameGrabber.getDisplayRotation()` in commit https://github.com/bytedeco/javacv/commit/d1b1f4e1d445e764fc542d335ba5235483613bd7.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
This has now been released with JavaCV 1.5.8. Enjoy!

**Comment by haiahaiah** [comment]
> I've added `FFmpegFrameGrabber.getDisplayRotation()` in commit [d1b1f4e](https://github.com/bytedeco/javacv/commit/d1b1f4e1d445e764fc542d335ba5235483613bd7). Please give it a try with the snapshots: http://bytedeco.org/builds/

hi~ thanks for your excellent work. I want to know the meaning of the result returned by this [getDisplayRotation()](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FFmpegFrameGrabber.html#getDisplayRotation--) For example, 90 means should I rotate the frame returned by `FFmpegFrameGrabber ff = new FFmpegFrameGrabber(videoPath); Frame framge=ff.grabImage()` clockwise or counterclockwise 90 degree to get the correct image? Thanks a lot!
