### ISSUE TITLE
FrameConverter returns null when given FFmpegFrameGrabber.grab() as argument

### ISSUE THREAD

**Issue by SchredDev** [bytedeco/javacv#1362]
Hey, it's me again! This one is not going to take as long though, probably. ;)

So I am using a `FFmpegFrameGrabber` to grab frames from a mp4 file containing video and sound. I get frames by calling `grab()`, because I need both. However, there are also instances where the `frame` is needed as a `BufferedImage`, so I tried using a `Java2DFrameConverter` to convert it. That works fine on frames grabbed with `grabImage()`, but on ones gotten using `grab()` it returns null. Why is that?

Code:
```
Java2DFrameConverter converter = new Java2DFrameConverter();
BufferedImage image = converter.convert(grabber.grab()); //grabber is a FFmpegFrameGrabber
```

**Comment by saudet** [comment]
Those are the audio frames. The image is going to be null for those.

**Comment by SchredDev** [comment]
So what do you propose instead?

**Comment by saudet** [comment]
Could you please explain what is it that you do not understand?

**Comment by SchredDev** [comment]
What should I call to get the audio as well as the video in one frame? The problem is that the `image` of the grabbed frame is not set (null) and therefore the rest of the image-related variables probably too.

**Comment by saudet** [comment]
With FFmpeg, a frame will never contain both audio and video data, so don't worry about that.

**Comment by SchredDev** [comment]
Oh, okay. Thanks.
