### ISSUE TITLE
cvRect create instances, auto release?

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1364]
Hi 

I am using cvSetImageROI(mainImage, cvRect(x, y, width,  height)); in a loop, which cause a lot of cvRect objects, right? does it cause memory leak? thanks!

**Comment by saudet** [comment]
`cvRect()` returns by value, so a deallocator gets registered, and everything about them applies as previously mentioned in issue  https://github.com/bytedeco/javacv/issues/1342#issuecomment-559322477.
