### ISSUE TITLE
Video is too long due to different video- and audio frame rates

### ISSUE THREAD

**Issue by SchredDev** [bytedeco/javacv#1365]
I am trying to encode a number of frames to a video with both video and sound. However, the result is longer than expected. For example, 300 frames encoded at 60 fps should result in a 5 second long video, but the output is almost 7 seconds long.

This is **what I believe is happening**: The ```audioFrames``` of the ```FFmpegFrameGrabber``` are longer than 0.01666... seconds, which is how long one frame should be at 60 fps. This causes the audio of the exported video to be longer.

This is **my reasoning**: The ```audioFramerate``` of the grabber is about 45, meaning that one audio frame would be around 0.222... seconds long which, multiplied with 300 (the amount of frames), roughly equates to 7 seconds.

My **attempt to solve this**: Based off of [this issue](https://github.com/bytedeco/javacv/issues/1177#issuecomment-480789741) and [the source](https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java) for ```FFmpegFrameGrabber``` I thought I could figure out a way to alter the ```audioFramerate``` by setting the ```sampleRate```. So I did some maths and set it to 61440, which resulted in a perfect 60 fps ```audioFramerate```. Sadly, this caused the video to now be 9 seconds long and the audio to sound stretched out. Then I went the other way around and set the framerate to 30, which made the video 5 seconds long, but also made the entire 18 second long track finish in less than 300 frames (so does that prove my theory from above wrong?). I am cluesless as what to do now.

**My code** (basically):
```
public static void main(String[] args) throws org.bytedeco.javacv.FrameGrabber.Exception {
	FFmpegFrameGrabber grabber = getAGrabber(); // Returns a slightly modified grabber. Code down below.
	FFmpegFrameRecorder recorder = getARecorder(); // Same thing.

	for (int i = 0; i < 300; i++) {
		BetterFrame frame = getVideoAndAudioFrame(i, grabber);
		frame.videoFrame.samples = frame.audioFrame.samples;
		recorder.record(frame.videoFrame);
	}
}

// BetterFrame is basically just a container for 2 frames.
public static BetterFrame getVideoAndAudioFrame(int framePos, FFmpegFrameGrabber grabber) throws org.bytedeco.javacv.FrameGrabber.Exception {
	grabber.setFrameNumber(framePos);
	final Frame videoFrame = grabber.grabImage().clone();
	grabber.setAudioFrameNumber(framePos);
	final Frame audioFrame = grabber.grab();
	return new BetterFrame(videoFrame, audioFrame);
}

public static FFmpegFrameGrabber getAGrabber() throws Exception {
	FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new File("filename"));
	grabber.restart();
	grabber.setFrameRate(Project.framerate);
	grabber.setSampleRate(61440);
	grabber.setSampleFormat(3);
        return grabber;
}

public static FFmpegFrameRecorder getARecorder() throws org.bytedeco.javacv.FrameRecorder.Exception {
	final FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(new File("destination"), 1920, 1080, 2);
	recorder.setFormat("mp4");
	recorder.setFrameRate(60);
	recorder.setAudioChannels(2);
	recorder.start();
	return recorder;
}
```

If you need an example you can reproduce more easily, tell me.

Does anyone know how to solve this?

**Comment by saudet** [comment]
The last audio frame can have a smaller number of samples than all the other audio frames. We can adjust the length of the audio stream more precisely by removing samples from the last audio frame.

**Comment by SchredDev** [comment]
Okay, but how do I do that?

**Comment by saudet** [comment]
We can set the limit on the buffers containing the samples in each `Frame` with normal Java code.

It should also be possible to use the "segment" format instead of "mp4" with `FFmpegFrameRecorder`:
https://ffmpeg.org/ffmpeg-formats.html#segment_002c-stream_005fsegment_002c-ssegment
But this hasn't been tested, so please let me know if you encounter any issues with that.

**Comment by SchredDev** [comment]
Using the "segment" format results in a FrameRecorder Exception:

> avcodec_find_encoder() error: Video codec not found.
> at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:475)

What value do you suggest for the limit? And should I limit every Buffer in the samples array? (Probably, right?)

**Comment by SchredDev** [comment]
Okay so limiting the last frame to be recorded doesn't help like this:
if(i == 299)
     for(Buffer b : videoFrame.samples)
          b.limit(x));

Or did I misunderstand you?

Limiting each frame's samples just speeds the song up. Also when I said above that the entire song finishes, it were probably just the 7 seconds being played anyways, but sped up.

**Comment by saudet** [comment]
> Using the "segment" format results in a FrameRecorder Exception:
> 
> > avcodec_find_encoder() error: Video codec not found.
> > at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:475)

You'll need to set the codec.
 
> What value do you suggest for the limit? And should I limit every Buffer in the samples array? (Probably, right?)

That depends on the length you're trying to achieve. For example, if you need to keep only half the samples to get the right length, then you can set the limit to half the capacity. That kind of thing.

**Comment by SchredDev** [comment]
> You'll need to set the codec.

Is there a list somewhere that says which number represents which codec? (I tried setting it to "mp4" and "H265" with ```setVideoCodecName```, and the error sill persists.

> That depends on the length you're trying to achieve. For example, if you need to keep only half the samples to get the right length, then you can set the limit to half the capacity. That kind of thing.

Sadly, limiting it speeds it up too much.

**Comment by saudet** [comment]
The list of supported codecs is available in FFmpeg here: https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/src/gen/java/org/bytedeco/ffmpeg/global/avcodec.java#L235

**Comment by SchredDev** [comment]
Okay, thanks. I also had to set the audio codec. However, now I get the following exception:

> org.bytedeco.javacv.FrameRecorder$Exception: avformat_write_header error() error -22: Could not write header to 'null'
> 	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:872)

**Comment by saudet** [comment]
Look at the log messages displayed on the console. It will give you more information than that.

**Comment by SchredDev** [comment]
Oh, right. It says:

> [mp4 @ 0000022055adf740] Invalid segment filename template 'C:\Users\name\desktop\test.mp4'

I don't understand what could be wrong about that filename.

**Comment by saudet** [comment]
We need to give it a filename template instead of a real filename. Please read the documentation.

**Comment by SchredDev** [comment]
I'm sorry, what documentation? I couldn't find anything for JavaCV, FFmpeg or just Java...

**Comment by saudet** [comment]
The one I pointed to you above:
https://ffmpeg.org/ffmpeg-formats.html#segment_002c-stream_005fsegment_002c-ssegment

**Comment by SchredDev** [comment]
I did this;
`recorder.setOption("strftime", "true");`

and there are no more error messages. However, the video is now 2 seconds long and VLC freaks out while playing the video (starts at 4 seconds, but duration is 2).

**Comment by SchredDev** [comment]
Actually, I think I might be done with this... I've been trying to implement exporting audio for far longer than this post exists now, and what I'm currently doing almost works. I kinda just want to move on to different aspects now. I really, really appreciate your help with this one! Thanks!
