### ISSUE TITLE
trojan warning for opencv MacOS dependency

### ISSUE THREAD

**Issue by george-toma** [bytedeco/javacv#1368]
Hi folks,

I raised the following concern on dl4j-java framework triggered by opencv library.

Windows Defender antivirus shows a trojan in one of the transitive dependencies from deeplearning4j-core/examples package/project and to be more specific in opencv for MacOS.

By default when you compile the project all OS dependencies are downloaded from the central Maven repository, so everyone has this trojan in their machines.

In case this is not a false alarm of Windows Defender, you should consider notifying the users of this framework and address this security issue.

Also, maybe a security check step before publication to mvn repository should take place.

Details 
- dl4j version used
```
<dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-beta4</version>
  </dependency>
```

- from where it comes the trojan
    org\bytedeco\opencv\4.0.1-1.5\opencv-4.0.1-1.5-macosx-x86_64.jar
- trojan name - Trojan:MacOS/Lightaidra
- Log from Windows Defender
    file:C:\Users\user.m2\repository\org\bytedeco\opencv\4.0.1-1.5\opencv-4.0.1-1.5-macosx-x86_64.jar->org/bytedeco/opencv/macosx-x86_64/libopencv_dnn.4.0.dylib

Based on Microsoft this trojan is used for DDoS attacks and to establish IRC communication with "villain users".

I had to remove my personal Java projects from this framework.

**Note** I did not check any newer version, but there is a high chance of this being present even on newer versions.

**Comment by saudet** [comment]
Those are usually false alarms, yes. Please report to Microsoft as well!
Thanks

**Comment by george-toma** [comment]
I scanned the file with Avast and Kaspersky and I got no warning.
This seems like a false alarm, as pointed by saudet.

Thanks
