### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1370]
Fatal Exception: java.lang.UnsatisfiedLinkError

dlopen failed: cannot locate symbol "getpagesize" referenced by "libjniopencv_core.so"

Hi may i know why i got this error on Android 4.4? Any suggestion?

**Comment by saudet** [comment]
The distributed binaries are for Android 5.0+.

**Comment by xiaos** [comment]
how do i know the distributed binaries are for which Android version?

**Comment by saudet** [comment]
It written in the README.md file here:
https://github.com/bytedeco/javacpp-presets/#manual-installation

**Comment by xiaos** [comment]
Thanks!

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/562
