### ISSUE TITLE
Is it possible to suppress call to avformat.avformat_find_stream_info ?

### ISSUE THREAD

**Issue by Antoniossss** [bytedeco/javacv#1376]
So in my case in FFmpehframeGrabber#720  which is 
````
  if ((ret = avformat.avformat_find_stream_info(this.oc, (PointerPointer)null)) < 0) {
````
block for several seconds. Is there any way to suppress that call on native level (as in java code shows there is none) by eg providing some stream info before starting capturing? I will be using only single format stream so I can provide as much information beforehand as API allows me.

**Comment by Antoniossss** [comment]
I have copied code for FFmpegFrameGrabber, removed mentioned line and everything works fine without "warmup delay" - however I don't like that and I think there should be an API to allow skip that phase.

**Comment by saudet** [comment]
We could add a parameter to let users skip that if it works fine without it in some cases.

**Comment by saudet** [comment]
Could you please send a pull request with an updated API to allow this? Thanks!

**Comment by saudet** [comment]
`FFmpegFrameGrabber.start()` from JavaCV 1.5.3 now has a parameter for this. Thanks for reporting!

**Comment by banmajio** [comment]
hello:
   Thank you very much for your help! Therefore, setting the interrupt callback function does not work on avformat_ open_ Is the input function?  If so,with the flow of information I know,I can skip avformat_open_input().I mentioned that before.But I don't know what configuration should be made for the flow information grabber.start () normal execution.Can you give me some help? I checked almost all the issues and found no specific code implementation.This problem has been bothering me for a long time. I'm depressed!

**Comment by saudet** [comment]
I don't know more than you do. Please try to ask upstream: https://ffmpeg.org/mailing-list-faq.html
