### ISSUE TITLE
Support for reading other data streams using FFmpegFrameGrabber

### ISSUE THREAD

**Issue by bytes-and-bits** [bytedeco/javacv#1377]
GoPros and some other cameras provide metadata in H.264 streams which are not currently being read out by FFmpegFrameGrabber.  This data is generally in some type of binary format, and for those purposes providing an interface to the raw packet / ByteArray would be sufficient.

**Comment by saudet** [comment]
Is this metadata exposed as "side data", similarly to issue #1361?

**Comment by bytes-and-bits** [comment]
They are completely separate streams within the container:

> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'GOPR0662.MP4':
>   Metadata:
>     major_brand     : mp41
>     minor_version   : 538120216
>     compatible_brands: mp41
>     creation_time   : 2017-06-20T14:02:32.000000Z
>     firmware        : HD5.02.01.50.00
>   Duration: 00:00:16.06, start: 0.000000, bitrate: 60342 kb/s
>     Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709
> ), 3840x2160 [SAR 1:1 DAR 16:9], 60160 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.9
> 5 tbc (default)
>     Metadata:
>       creation_time   : 2017-06-20T14:02:32.000000Z
>       handler_name    :         GoPro AVC
>       encoder         : GoPro AVC encoder
>       timecode        : 14:39:10:09
>     Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, flt
> p, 128 kb/s (default)
>     Metadata:
>       creation_time   : 2017-06-20T14:02:32.000000Z
>       handler_name    :         GoPro AAC
>       timecode        : 14:39:10:09
>     Stream #0:2(eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
>     Metadata:
>       creation_time   : 2017-06-20T14:02:32.000000Z
>       handler_name    :         GoPro TCD
>       timecode        : 14:39:10:09
>     Stream #0:3(eng): Data: bin_data (gpmd / 0x646D7067), 34 kb/s (default)
>     Metadata:
>       creation_time   : 2017-06-20T14:02:32.000000Z
>       handler_name    :         GoPro MET
>     Stream #0:4(eng): Data: none (fdsc / 0x63736466), 9 kb/s (default)
>     Metadata:
>       creation_time   : 2017-06-20T14:02:32.000000Z
>       handler_name    :         GoPro SOS
> Unsupported codec with id 0 for input stream 2
> Unsupported codec with id 100359 for input stream 3
> Unsupported codec with id 0 for input stream 4

**Comment by saudet** [comment]
Ah, data streams, I see. It shouldn't be too difficult to add support for that. Someone just needs to do it.
If you'd like to give it a try, if you have any questions, I'll be here to help. Thanks!

**Comment by bytes-and-bits** [comment]
I have some proto-code which I can eventually turn into a pull request, though I had a question on interface / containers.

After line 1328 in [FFmpegFrameGrabber.java](https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L1328) is where I was able to catch other data streams.  Further up at line 1301 there is a comment about HashMap on Android being slow:

                if (pkt2.size() <= 0) {
                    // HashMap is unacceptably slow on Android
                    // pkt2.put(pkt);
                    BytePointer.memcpy(pkt2, pkt, sizeof_pkt);
                }

Is that still a true statement?  Since the number of streams and the associated indexes can be variable my first inclination is to pack the ByteBuffers into a HashMap with the stream numbers as the keys.  If the preference is to still avoid HashMaps, then self tracking using an array of indexes along with an array of ByteBuffers would work though it is certainly ugly.  Not familiar enough with the Android API to know of alternatives - suggestions welcome!

**Comment by saudet** [comment]
Well, if for n streams, they already have indices 0..n-1, I'd just use arrays, right? Why is this ugly?

**Comment by bytes-and-bits** [comment]
I should have clarified that there will be gaps in the "other streams" array without some bookkeeping - video and audio indexes appear to take the 0 and 1 spots, but depending on the file there might not be an audio stream (or even more than 1).  And I am unsure if there's a good way to get the number of streams in the file, so I have been growing an array of ByteBuffers based on the stream index.  Basically the bit of ugliness is in the bookkeeping code to present a gapless array with the other streams to the user without having to check all the elements for null.  This also allows for easier reuse of the cloneBufferArray() method in Frame.java to clone() the Frame.

**Comment by saudet** [comment]
From what I understand, these arrays would be only internal to FFmpegFrameGrabber, they wouldn't be exposed to users, so there shouldn't be any issues even if they have small gaps. Each `Frame` returned would be from only 1 given data stream, where we'd have an `int` or `String` or something field as the identifier for that stream. Users don't need to deal with hash maps or arrays.

**Comment by bytes-and-bits** [comment]
While I was writing the enhancement I had conflated the modifications necessary for the user to access the data via `Frame` objects with those for FFmpegFrameGrabber.  That is probably where the confusion lies.  Basically, I plan to add a public array of `ByteBuffer` objects to `Frame` that an end user can access, and have FFmpegFrameGrabber fill in the `ByteBuffer` array.  Since there are any number of potential binary formats that can be packed in it seems to make sense to deal with the parsing and such necessary to identify the stream type.

**Comment by saudet** [comment]
Like I said, to make things simple, don't add an array to `Frame`, but just a single `Buffer data`, along with what's needed to identify the type of data, and that's it.

**Comment by bytes-and-bits** [comment]
I used the (audio) `Buffer[] samples` portion of `Frame` as a working example since there could be multiple other data streams associated with a video frame.

The pull request linked above should hopefully show my intent.  (Also, fairly new to Git / GitHub, so wasn't sure how to get the PR linked on the side.)

**Comment by bytes-and-bits** [comment]
Completed in 11016316165f238f6db163be341bb6fe1b2b234c

**Comment by saudet** [comment]
I've added `FFmpegFrameGrabber.getDisplayRotation()` in commit https://github.com/bytedeco/javacv/commit/d1b1f4e1d445e764fc542d335ba5235483613bd7.
Please give it a try with the snapshots: http://bytedeco.org/builds/
