### ISSUE TITLE
cv::Mat(cv::Rect, cv::Mat) counterpart

### ISSUE THREAD

**Issue by robertoandrade** [bytedeco/javacv#138]
I'm trying to extract a subimage off of an `IplImage` and have been seeing [examples](http://stackoverflow.com/questions/8267191/how-to-crop-a-cvmat-in-opencv) on how to do it using OpenCV and was struggling to find the counterparts to the aforementioned constructor in JavaCV land.

Any suggestions?

**Comment by saudet** [comment]
It's exactly the same: [public Mat(Mat m, Rect roi)](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Mat.html#Mat-org.bytedeco.javacpp.opencv_core.Mat-org.bytedeco.javacpp.opencv_core.Rect-).
