### ISSUE TITLE
FFmpegFramerecorder avcodec_encode_video2 error with fast processor

### ISSUE THREAD

**Issue by Freckweb** [bytedeco/javacv#1381]
My IP camera application works fine when using a 'normal' computer but on my Ryzen 7 machine, video recording sometimes fails almost immediately with a 'avcodec_encode_video2 error -1: Could not encode video packet' exception.

At release 1.5.1 this occurred approximately 1 out of 5 recordings. I upgraded to 1.5.2 and it occurs even more frequently.

After much head scratching and investigation I discovered that a short delay between recorder.start() and recorder.record(capturedFrame) resolves this issue. I simply inserted a Thread.sleep(10) between the calls.

**Comment by saudet** [comment]
Please check the messages from the log that get displayed on the console. This should provide us with clues as to what might be happening.

**Comment by Freckweb** [comment]
As stated above, recorder.record(capturedFrame) raises a FrameRecorder.Exception which I print out using System.out.println(ex.getLocalizedMessage()). This displays 'avcodec_encode_video2 error -1: Could not encode video packet' in the console. There is nothing else displayed.

**Comment by saudet** [comment]
If you're not seeing anything, make sure you've called FFmpegLogCallback.set().

**Comment by Freckweb** [comment]
I added FFmpegLogCallback.set() but nothing is output. Adding the call does significantly reduce the occurence of the problem!

**Comment by saudet** [comment]
If you're still not seeing anything, make sure to increase the verbosity of
the log.

**Comment by Freckweb** [comment]
Increasing the verbosity of the log stops the problem from happening.
Monitoring the threads shows that a new thread is started to record the video. When the exception is raised a new thread does not appear to be created.
My guess would be that recorder.record is being called before the record thread is ready (if the machine is fast enough). Loading the processor or adding a delay between recorder.start and recorder.record allows sufficient time to complete the creation of the record thread before recorder.record is called.

**Comment by saudet** [comment]
It's possible that the codec you're using isn't thread-safe, yes, that's quite common for many of them. Make sure to disable multithreading for the encoder if that's the case.

**Comment by Freckweb** [comment]
I prefer my 10ms delay solution :-) I have been running a test script to create a 5 second recording every 10 seconds. It has been running overnight without a single failure.
As the problem is now recorded and is unlikely to affect many people, I will close this issue. If I get a bit of spare time I will have a look at the FFmpeg code and see if there is a better way to resolve it.
Thanks.
