### ISSUE TITLE
opencv_core.Mat has no get method.

### ISSUE THREAD

**Issue by sanyecao2314** [bytedeco/javacv#1384]
Please excuse my noob question.
```
double[] org.opencv.core.Mat.get(int row, int col)
```
opencv_core.Mat has no get method.
The get method in org.opencv.core.Mat mat corresponds to which method in opencv_core.Mat.. Or how to solve it

**Comment by saudet** [comment]
We can use an `Indexer` for that: http://bytedeco.org/news/2014/12/23/third-release/

**Comment by sanyecao2314** [comment]
THX
