### ISSUE TITLE
When does 1.5.3 release?

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1385]
Hi @saudet  May I know when does version 1.5.3 release? In Android Q, we cannot create FFmpegFrameRecorder with external path, I am waiting for the fix for FFmpegFrameRecorder to accept inputstream.

**Comment by saudet** [comment]
If all goes well, some time early next month is the plan.

**Comment by saudet** [comment]
However, snapshots are already available, so please make sure that everything works with those:
http://bytedeco.org/builds/

**Comment by xiaos** [comment]
I tried the snapshot version, but found opencv is still dependent on openblas.

**Comment by saudet** [comment]
Yes, that hasn't been fixed, and may not be fixed soon since not many people care, see issue #1329

**Comment by xiaos** [comment]
thanks @saudet ,  if i dont want use it.  Where shall I start with? how to build the library by myself ? thank you so much for this library.

**Comment by saudet** [comment]
Simply removing all references to OpenBLAS from the files should do the trick.

**Comment by saudet** [comment]
And build instructions are available in the README.md file here: https://github.com/bytedeco/javacpp-presets#build-instructions

**Comment by xiaos** [comment]
may i know how long does it take to build all the libraries on pc?

**Comment by saudet** [comment]
We can refer to the build times on the CI servers here:
https://travis-ci.org/bytedeco/javacpp-presets
https://ci.appveyor.com/project/Bytedeco/javacpp-presets

**Comment by deinhofer** [comment]
Hi,
Actually I would also be interested in removing it as the openblas dependency bloats up the deployment heavily.
e.g. if you want to deploy it for windows, mac and linux (x86, x64, arm) the deployment increases by about **75MB**.

```bash
mad@martin-T480:/media/mad/Daten/dev/AsTeRICS/ARE/services/ComputerVision$ ls -ahl javacv/src/main/resources/lib/native/openblas*.jar
-rwxrwxr-- 1 mad mad 127K Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2.jar
-rwxrwxr-- 1 mad mad 6,6M Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2-linux-arm64.jar
-rwxrwxr-- 1 mad mad 7,6M Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2-linux-armhf.jar
-rwxrwxr-- 1 mad mad  12M Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2-linux-x86_64.jar
-rwxrwxr-- 1 mad mad 9,3M Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2-linux-x86.jar
-rwxrwxr-- 1 mad mad  12M Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2-macosx-x86_64.jar
-rwxrwxr-- 1 mad mad  12M Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2-windows-x86_64.jar
-rwxrwxr-- 1 mad mad 9,3M Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-0.3.7-1.5.2-windows-x86.jar
-rwxrwxr-- 1 mad mad 3,2K Mär 13 22:53 javacv/src/main/resources/lib/native/openblas-platform-0.3.7-1.5.2.jar
```
So would you mind to remove the dependency or do you need it for some internal classes in javacv??

**Comment by xiaos** [comment]
I just start to build, ffmpeg and opencv . But got some error.
@saudet  can you please give some tips? thanks!

![1](https://user-images.githubusercontent.com/2921946/78741870-16515500-798d-11ea-91ce-99179c61a9cf.JPG)

![2](https://user-images.githubusercontent.com/2921946/78741878-1a7d7280-798d-11ea-8245-81dc8e6f8154.JPG)

**Comment by saudet** [comment]
@deinhofer It's OpenCV that depends on OpenBLAS, not JavaCV directly.

@xiaos Please set up your build environment as explained here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by xiaos** [comment]
Hi @saudet   i can build the project now, can you guide me how to remove the openlabs from opencv?

**Comment by saudet** [comment]
Simply removing any reference to it should work.

**Comment by xiaos** [comment]
You mean from opencv source code?

**Comment by saudet** [comment]
No, from the files in the presets.

**Comment by saudet** [comment]
BTW, this has nothing to do with 1.5.3 release. Please post questions about that at #1329.

**Comment by saudet** [comment]
Version 1.5.3 has been released. Let's continue any discussion about OpenBLAS at #1329.
