### ISSUE TITLE
very confuse when to choose MAT from javacv,javacpp or javacpp-presets for android

### ISSUE THREAD

**Issue by reizamv** [bytedeco/javacv#1388]
iam coding android and very confuse with mat type, in another class need Mat from org.bytedeco,javacv another asking org.bytedeco.javacpp Mat another class asking javacpp-presets Mat class
i am sorry iam 14 day to learn this javacv and my productivity just slow down because this error asking another library and collide with another library import. that not yet if asking for Rect or another Type very confuse to choose import from where...

**Comment by saudet** [comment]
There is only one Mat, etc type shared by all libraries. There are no
multiple types of anything. You'll need to clarify what the issue is if you
would like some help.

**Comment by saudet** [comment]
Maybe you're referring to the classes in the `org.opencv` package? That answer is in the FAQ:
http://bytedeco.org/faq/#how-does-it-differ-from-wrappers-in-opencv-tensorflow-etc

**Comment by reizamv** [comment]
if you use convertframe you need MAT javacv, another RECT type use javacpp MAT, or color_RGB it need javacpp MAT that make confuse because i need a new TYPE from another library javacv need javacpp and javacpp-preset to work make facerecognition....can i just use javacv for face recognition?

**Comment by saudet** [comment]
I see what you mean now. You are only missing some dependencies. In your build file, please replace `javacv` with `javacv-platform`. That will grab everything it might need.

**Comment by saudet** [comment]
Also make sure to disable ProGuard. That sometimes removes classes that are actually required.
