### ISSUE TITLE
Using openCV with ActiveAndroid results in a crash

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#139]
If you follow the "getting started" of the ActiveAndroid library [here](https://github.com/pardom/ActiveAndroid/wiki/Getting-started), you have to set the name of the application in the manifest to ``android:name="com.activeandroid.app.Application"``.
If you then launch your app, it crashes with the following exception: ``java.lang.NoClassDefFoundError: org.bytedeco.javacv.CameraDevice$SettingsImplementation``.

If you then try to create the activity itself like this:

```
public class MyApplication extends com.activeandroid.app.Application {
    @Override
    public void onCreate() {
        super.onCreate();
    }
}
```

and set the manifest like this: ``android:name="com.my.package.MyApplication"``` it still crashes with the same error.

The same if you change it to
```
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        ActiveAndroid.initialize(this);
        super.onCreate();
    }
}
```

Any idea why this occurs (besides the obvious that changing the Application does this) and how to fix it?

**Comment by saudet** [comment]
Android doesn't come with an implementation of JavaBeans, so we can't use classes like `CameraDevice` which makes use of JavaBeans... I'm not sure what the question is here. Are you looking into using the `CameraDevice` class on Android? Or you do not care about the `CameraDevice` class?

**Comment by lfdversluis** [comment]
No no, not anything like that.

I have implemented this library in my project (it's awesome by the way!). Now I was searching for a database library to handle database operations and came across that library. 
That library (ActiveAndroid) requires you to implement their class which extends Application. Whenever you do that, this (javacv) library suddenly crashes with the error mentioned above. When you do not initialize that library, it works again.

I have now implemented my database handler myself so I can keep your library working. But it is still a weird crash.

**Comment by saudet** [comment]
So it looks like ActiveAndroid is trying to use the `CameraDevice` class. There must be a way to change its settings to ignore a specific set of classes. In the worst case, it's also possible to remove those problematic classes entirely from `javacv.jar`, manually...
