### ISSUE TITLE
INSTALL_FAILED_INVALID_APK with 1.5.2 

### ISSUE THREAD

**Issue by UpAndDownAgain** [bytedeco/javacv#1391]
Im trying to use FFmpegFrameGrabber in Android but when I try to install i get the INSTALL_FAILED_INVALID_APK error.
I start with empty project then add ffmpeg.jar, ffmpeg-android-arm.jar, javacpp.jar, javacv.jar into app/libs then add those as jar dependencies in project structure

I'm using android studio 3.6.1
Thanks for help

**Comment by saudet** [comment]
There should be more details about why it's "invalid". Please show all the information that it provides.

**Comment by UpAndDownAgain** [comment]
So the error I was getting was caused by failing to extract native libraries which is fixed by adding 

android:extractNativeLibs="true"

into androidManifest.xml into application section. It might be useful to add this into readme in case others run into the same issue

**Comment by saudet** [comment]
I see, thanks for reporting! Please feel free to update appropriate files and pages. The sample projects could also use an update here: https://github.com/bytedeco/sample-projects Contributions welcome!
