### ISSUE TITLE
OpenCVFrameConverter vs AndroidFrameConverter

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1399]
Hi @saudet I am using javacv on Android, to process frame, i have two choices, 1) convert to opencv IplImage, 2) convert to Android bitmap.

So in terms of performance, which one do you think has better perfromance?
1) Convert from frame.
OpenCVFrameConverter.convertToIplImage()   vs   AndroidFrameConverter.convert()
2) Covnert to frame
OpenCVFrameConverter.convert(iplimage)   vs AndroidFrameConverter.convert(bitmap)

From the code, i can see frame to iplimage have better performance, there is no need to copy data.
For Android bitmap, we need copy the data:
            bitmap.copyPixelsToBuffer(this.frame.image[0].position(0));
                this.bitmap.copyPixelsFromBuffer(in.position(0));

**Comment by saudet** [comment]
Probably OpenCVFrameConverter, but that is going to depend on your use case, so I recommend you to perform some benchmarking.
