### ISSUE TITLE
import cvHaarDetectObjects with version 1.5.1

### ISSUE THREAD

**Issue by rilax** [bytedeco/javacv#1407]
Hi!
with version 1.5.1,

> cvHaarDetectObjects(smallImage, classifier, storage, 1.1, 3,
>                             CV_HAAR_FIND_BIGGEST_OBJECT | CV_HAAR_DO_ROUGH_SEARCH);

not able to to found the import for this method. can someone explain me how to import?

**Comment by saudet** [comment]
`cvHaarDetectObjects()` and many other deprecated functions were removed from OpenCV 4.x.
Instead, use `CascadeClassifier` as per the `Demo` sample code:
https://github.com/bytedeco/javacv/blob/master/samples/Demo.java
