### ISSUE TITLE
Migrating from 0.10 to 0.11, how to convert a ShortBuffer ?

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#141]
I am trying to convert my project from version 0.10 to 0.11.

I had this line in my project: 

`` recorder.record(images[i % images.length]);`` and with the aid of  a `` OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();`` I could call ``recorder.record(converter.convert(images[i % images.length]));``.

However, I also have a line where there is a ``ShortBuffer`` is used: `` recorder.record(imageSamples[i % imageSamples.length]);``

Is there a way to convert a ``ShortBuffer`` to a ``Frame`` or ``IplImage`` ? Apparently the ``IplImage.createFrom(...);`` function no longer exists.

**Comment by vah13** [comment]
I have too this issue!

**Comment by vah13** [comment]
try {
            frameGrabber.start();
            opencv_core.IplImage tmp;
            path = new String();
            String file_name = video.substring(video.lastIndexOf("/") + 1).replace(".mp4", "");
            tmp = frameGrabber.grab();
            tmp = rotate(tmp, 90);
            cvSaveImage(Environment.getExternalStorageDirectory().getAbsolutePath() + "/ss/temp/imagePreview.jpg", tmp);
            path = Environment.getExternalStorageDirectory().getAbsolutePath() + "/ss/temp/imagePreview.jpg";

            frameGrabber.stop();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }

Error:(55, 44) error: incompatible types: Frame cannot be converted to IplImage

**Comment by saudet** [comment]
With the addition of `FrameConverter`, we would not be able to distinguish between recording video images or audio samples just with a single `record(Buffer)` function, so it was split in two: 
[public boolean recordImage(int width, int height, int depth, int channels, int stride, int pixelFormat, Buffer... image)](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FFmpegFrameRecorder.html#recordImage-int-int-int-int-int-int-java.nio.Buffer...-) (set the pixelFormat to -1 for the default)
[public boolean recordSamples(int sampleRate, int audioChannels, Buffer... samples)](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FFmpegFrameRecorder.html#recordImage-int-int-int-int-int-int-java.nio.Buffer...-)

We can also create a `new Frame()` and assign the buffer to either the `image[0]` or `samples[0]` field, along with all the other required information, and call `record(Frame)`.

**Comment by saudet** [comment]
@vah13 Create a `converter = new OpenCVFrameConverter.ToIplImage()`, and call `tmp = converter.convert(frameGrabber.grab());`.
