### ISSUE TITLE
javacv can use ffmpeg native commands?

### ISSUE THREAD

**Issue by dunkboy** [bytedeco/javacv#1411]
I want to know that javacv can use ffmpeg commands on the official website of ffmpeg .
Like this：
eg:   ffmpeg -i "concat:input1.mpg|input2.mpg|input3.mpg" -c copy output.mpg.
Please tell me how to use it if javacv can.
Or say If I want to synthesize two videos into one, what should I do?
Thank you anyway！

"http://ffmpeg.org/ guid"

**Comment by saudet** [comment]
Yes, we can use the `ffmpeg` program:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
