### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by rilax** [bytedeco/javacv#1416]
I want to get video from an IP camera.
Wrote a simple program code:
`
import java.util.logging.Level;
import java.util.logging.Logger;
import org.bytedeco.javacv.CanvasFrame;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber;
public class Main {
    public static void main(String[] args) {
        try {
            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://admin:1234577@192.168.1.104:10554/tcp/av0_0");
            grabber.start();
            System.out.println(grabber.getFormat());
            Frame frame = grabber.grab();
            CanvasFrame canvasFrame = new CanvasFrame("IP camera");
            canvasFrame.setCanvasSize(frame.imageWidth, frame.imageHeight);
            
            while (canvasFrame.isVisible() && (frame = grabber.grab()) != null) {
                canvasFrame.showImage(frame);
            }
        } catch (FrameGrabber.Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
`
I get errors:
`
[udp @ 00000000184204c0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[udp @ 00000000186e1ac0] 'circular_buffer_size' option was set but it is not supported on this build (pthread support is required)
[rtsp @ 00000000183b7240] CSeq 5 expected, 0 received.
[rtsp @ 00000000183b7240] CSeq 5 expected, 0 received.
[rtsp @ 00000000183b7240] CSeq 5 expected, 0 received.
[rtsp @ 00000000183b7240] CSeq 5 expected, 0 received.
[rtsp @ 00000000183b7240] CSeq 5 expected, 0 received.
`
Help me please solve my problem!

**Comment by saudet** [comment]
I would recommend using TCP instead of UDP. That usually solves problems when it comes to RTSP.

**Comment by rilax** [comment]
> I would recommend using TCP instead of UDP. That usually solves problems when it comes to RTSP.

Tell me please! What do I need to write for tcp in code?

**Comment by rilax** [comment]
> I would recommend using TCP instead of UDP. That usually solves problems when it comes to RTSP.

`grabber.setOption("rtsp_transport", "tcp");`

Everything is working! Thank!
