### ISSUE TITLE
UnsatisfiedLinkError for videoinput

### ISSUE THREAD

**Issue by osmantoker** [bytedeco/javacv#1417]
Hi,
I downloaded javacv-platform-1.5.3-bin.zip and extracted all jar files. I wrote a short code for web cam and add the jars to the project but i could not run it. I got the error as;
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "linux-x86_64" not supported by class org.bytedeco.videoinput.videoInput`
But i can compile&run Smooter example at the Sample Usage (https://github.com/bytedeco/javacv).
OS : Centos 6.10 
I hope it's a minor problem. Does anyone know the solution?
Osman

**Comment by saudet** [comment]
It's only available for Windows, that's normal... Could you provide more
explanations about what the issue is?

**Comment by osmantoker** [comment]
I'm trying to capture network or device video with FrameGrabber. 
```
    	FrameGrabber grabber = new VideoInputFrameGrabber(0); // 1 for next camera
        OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
        grabber.start();
        while (true) {
            Frame frame = grabber.grab();
            img = converter.convert(frame);
        }
```
Thats all code here. My system is Centos 6.10 and i think that the jar files **x86_64.jar enough to run. I'm working on eclipse and whenever run the project, i got this error log;
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Platform "linux-x86_64" not supported by class org.bytedeco.videoinput.videoInput
	at org.bytedeco.javacpp.Loader.load(Loader.java:1148)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1109)
	at org.bytedeco.videoinput.videoInput.<clinit>(videoInput.java:23)
	at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:107)
	at org.bytedeco.javacv.VideoInputFrameGrabber.start(VideoInputFrameGrabber.java:104)
```

Osman

**Comment by saudet** [comment]
You'll need to use another FrameGrabber like FFmpegFrameGrabber or
OpenCVFrameGrabber.

**Comment by osmantoker** [comment]
Hi Saudet,
Thanks for advice, it works for webcam. Could I use this for streaming video? I created a SDP file for udp rawvideo and I can open the stream with Opencv lib but for FFMpegFrameGrabber, I think I should set the format for whitelist option.
I encountered two errors;
1. `Protocol 'rtp' not on whitelist 'file,crypto'`
2.` avformat_open_input() error, couldn't open input sdp. Has setFormat() been called?`

For the first log, in Python you should set parameters as;
`os.environ['OPENCV_FFMPEG_CAPTURE_OPTIONS'] = 'protocol_whitelist;file,rtp,udp'
`but in Java, I have no idea.

For the second one, how can I use setFormat for sdp or rawvideo stream?

Osman

**Comment by saudet** [comment]
I'm sure we can set options like that with `setOptions()` somehow, but I don't know the details...

**Comment by osmantoker** [comment]
Hi,
saudet, thanks for help, it works with;
```
setOption("protocol_whitelist", "file,udp,rtp");
setVideoOption("strict", "experimental");
```
Osman
