### ISSUE TITLE
 java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#142]
I am getting a `` java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lfdversluis.javacvtest-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libjniPointer.so"`` error whenever I try to run [The recording example](https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java) since I migrated to 0.11.

I also noticed that that example is out of date, currently I use: 
``recorder.record(converter.convert(images[i % images.length]));`` where converter is defined as ``OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();`` and for ByteByffers I use ``recorder.recordSamples(samples[i % samples.length]);``.

Is this correct and what can cause the linker error? 

I have defined the gradle dependency as:
``compile group: 'org.bytedeco', name: 'javacv', version: '0.11'``

<hr/>
Off-topic:
If I figured this error out I could update the example with a pull request if you want.

**Comment by saudet** [comment]
This kind of error is usually caused by ProGuard removing the `@Platform`
annotation.

Could you explain in what the sample is outdated? It works fine here...

**Comment by lfdversluis** [comment]
Lines 328, 342 and 534 make use of the record() function. As per 0.11 these should be changed, right? It works indeed fine in 0.10

**Comment by lfdversluis** [comment]
Also, I have ``-keepattributes *Annotation*`` in my proguard (both in the sdk ``proguard-android.txt`` and the ``proguard-rules.pro`` file in my android project). That should keep annotations... I'll debug further and see if I can find a fix.

**Comment by saudet** [comment]
I don't see any calls to record() on line 342:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java#L342

About the ProGuard issue, let's discuss about that here:
https://github.com/bytedeco/javacv/issues/79#issuecomment-91237951
Or let's create a new (clearer) issue about that. Thanks!
