### ISSUE TITLE
Restream HTTP Video - Error: avio_open2 error() error -111: Could not open 'null'

### ISSUE THREAD

**Issue by MarcWoodyard** [bytedeco/javacv#1422]
So I'm trying to take a video stream (usually using either RTSP or HTTP protocol) from another server and create an HTTP restream that I can play on a website. Here's the error message I keep getting.

`"org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -111: Could not open 'null' `

Error is thrown at: https://github.com/Edge-Route-Networks/Edge-Eye/blob/f41b39f105c9854bfeb17f73205bb21c811e9848/src/main/java/network/edgeroute/camera/threads/FFMPEGBroadcastThread.java#L88

Here's a link to my code: https://github.com/Edge-Route-Networks/Edge-Eye/blob/master/src/main/java/network/edgeroute/camera/threads/FFMPEGBroadcastThread.java

Any advice?

**Comment by saudet** [comment]
Errno 111 is "Connection refused", so that's a network problem. You'll need to figure out why...

**Comment by MarcWoodyard** [comment]
I know that my FFmpegFrameGrabber object can connect to the remote stream. Would it be because I'm trying to connect to a stream on my localhost when one doesn't exist? The code below is basically what I implemented to try to restream an HTTP stream from a remote server.

```java
frameGrabber = new FFmpegFrameGrabber("http://remote-sever/stream.mjpeg");
frameGrabber.setFormat("mjpeg");
frameGrabber.start()

recorder = new FFmpegFrameRecorder("http://localhost/stream.webm");
recorder.setInterleaved(true);
recorder.setVideoOption("tune", "zerolatency");
recorder.setVideoOption("preset", "ultrafast");
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);

recorder.setFormat("webm");
recorder.setFrameRate(10);
recorder.start();

Frame frame = null;

while (true) {
    try {
        frame = this.grabber.grabFrame();

        if (frame != null)
            recorder.record(this.grabber.grab());

        Thread.sleep(100);
    } catch (FrameRecorder.Exception | FrameGrabber.Exception | InterruptedException e) {
        e.printStackTrace();
    }

**Comment by saudet** [comment]
That means "http://localhost/stream.webm" doesn't exist.

**Comment by MarcWoodyard** [comment]
Yes, http://localhost/stream.webm wouldn't exist because that's the URL of the stream I'm trying to create on my local PC. Did I skip a step in my code when creating the FFmpegFrameRecorder, or does the local stream URL need to exist before I create a FFmpegFrameRecorder object?

**Comment by MarcWoodyard** [comment]
I just updated the code above to fix some mistakes that I made when copying it from my source to Github.

**Comment by saudet** [comment]
To start a server with the http protocol, we apparently need to set the "listen" option to 1:
https://ffmpeg.org/ffmpeg-protocols.html#http
But the tcp, udp, or rtp protocols probably work better:
https://trac.ffmpeg.org/wiki/StreamingGuide

**Comment by MarcWoodyard** [comment]
That's exactly what I needed, thanks for the help saudet!

```java
frameGrabber = new FFmpegFrameGrabber("http://remote-sever/stream.mjpeg");
frameGrabber.setFormat("mjpeg");
frameGrabber.start()

recorder = new FFmpegFrameRecorder("http://localhost:2090/stream.webm");

recorder.setOption("listen", "1");

recorder.setInterleaved(true);
recorder.setVideoOption("tune", "zerolatency");
recorder.setVideoOption("preset", "ultrafast");
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setFormat("webm");
recorder.setFrameRate(10);
recorder.start();

Frame frame = null;

while (true) {
    try {
        frame = frameGrabber.grabFrame();

        if (frame != null)
            recorder.record(frame);

        Thread.sleep(100);
    } catch (FrameRecorder.Exception | FrameGrabber.Exception | InterruptedException e) {
        e.printStackTrace();
    }
}
