### ISSUE TITLE
How to use time Mat to create hdr toned map image?

### ISSUE THREAD

**Issue by lalit-gsquad** [bytedeco/javacv#1428]
Hi, 
    I am not posting any issue related this, but I have question. I am trying to create HDR image using this library by following some examples of opencv. But I can not find a way for conversion these line of code of opencv

>    Mat response = new Mat();
        CalibrateDebevec calibrate = Photo.createCalibrateDebevec();
        Mat matTimes = new Mat(times.size(), 1, CvType.CV_32F);
        float[] arrayTimes = new float[(int) (matTimes.total()*matTimes.channels())];
        for (int i = 0; i < times.size(); i++) {
            arrayTimes[i] = times.get(i);
        }
        matTimes.put(0, 0, arrayTimes);
        calibrate.process(images, response, matTimes); 

I tried something using by following line but it is not working

>    val calibrate = createCalibrateDebevec()
        val matTimes = Mat(times.size, 1, CV_32F)
        val arrayTimes =
            FloatArray((matTimes.total() * matTimes.channels()).toInt())
        for (i in times.indices) {
            arrayTimes[i] = times[i]
            matTimes.put(Mat(arrayTimes[i]))
        }
     calibrate.process(images, response, matTimes)

Can you please help me how can I prepare exposure times Mat to solve this.
Thanks

**Comment by saudet** [comment]
Would you have working code in C++?

**Comment by lalit-gsquad** [comment]
> Would you have working code in C++?

No I am working with kotlin.

**Comment by lalit-gsquad** [comment]
Thanks @saudet for quick reply. I just want to convert opencv code to javacv code for the following lines:

> Mat matTimes = new Mat(times.size(), 1, CvType.CV_32F);
float[] arrayTimes = new float[(int) (matTimes.total()*matTimes.channels())];
for (int i = 0; i < times.size(); i++) {
arrayTimes[i] = times.get(i);
}
matTimes.put(0, 0, arrayTimes);

Above lines of code is written by using classes of opencv. Any alternative for this using javacv.

**Comment by saudet** [comment]
You can keep using that as is. The official Java API is available with JavaCV as well.

**Comment by lalit-gsquad** [comment]
> You can keep using that as is. The official Java API is available with JavaCV as well.

Yes I am trying to use same but there is difference for the `matTimes.put(0, 0, arrayTimes);`. javacv using only single parameter method. so I tried by using `Mat(floatValue)`. but not working.

**Comment by saudet** [comment]
The same is available with JavaCV:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/opencv/core/Mat.html#put-int-int-double...-

**Comment by lalit-gsquad** [comment]
> The same is available with JavaCV:
> http://bytedeco.org/javacpp-presets/opencv/apidocs/org/opencv/core/Mat.html#put-int-int-double...-

I am trying to use this but can not find method:
![image](https://user-images.githubusercontent.com/61863347/81805296-38179c00-9538-11ea-9aa9-6e5e0af714a4.png)

**Comment by lalit-gsquad** [comment]
@saudet Thank you for your support. I have resolved the problem using opencv Mat class and other function.
