### ISSUE TITLE
Publishing RTMP stream throws exception

### ISSUE THREAD

**Issue by arvind-das** [bytedeco/javacv#143]
Here is the exception log....

HIGHGUI ERROR: V4L: Property <unknown property string>(9) not supported by device
HIGHGUI ERROR: V4L: Property <unknown property string>(9) not supported by device
HIGHGUI ERROR: V4L: Property <unknown property string>(16) not supported by device
Output #0, flv, to 'rtmp://localhost:1935/recording/yo.flv':
    Stream #0:0: Video: h264 (libx264), yuv420p, 640x380, q=-1--1, 2000 kb/s, 30 tbn, 30 tbc
    Stream #0:1: Audio: aac, 44100 Hz, stereo, fltp, 192 kb/s
[libx264 @ 0x7f77753e9820] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX AVX2 FMA3 LZCNT BMI2
[libx264 @ 0x7f77753e9820] profile Constrained Baseline, level 3.0
[libx264 @ 0x7f77753e9820] 264 - core 142 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=6 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Line unsupported: interface TargetDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian
	at com.sun.media.sound.DirectAudioDevice.getLine(DirectAudioDevice.java:174)
	at com.rrdtech.recording.CustomFFmpegRecorder$1.run(CustomFFmpegRecorder.java:119)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.AbstractMethodError: org.bytedeco.javacv.FrameConverter.convert(Ljava/lang/Object;)Lorg/bytedeco/javacv/Frame;
	at org.bytedeco.javacv.OpenCVFrameGrabber.grab(OpenCVFrameGrabber.java:259)
	at com.rrdtech.recording.CustomFFmpegRecorder.main(CustomFFmpegRecorder.java:184)

Not sure why. Before this grabber.start() was not allowing next code to execute which apparently got solved . What could be the possible reason for above exception?

**Comment by arvind-das** [comment]
I updated some code here

final TargetDataLine line = (TargetDataLine) mixer.getLine(dataLineInfo);

to
final TargetDataLine line = (TargetDataLine)AudioSystem.getLine(dataLineInfo);


and now stream had the audio recorded but not the video. New exception is :
Exception in thread "main" java.lang.AbstractMethodError: org.bytedeco.javacv.FrameConverter.convert(Ljava/lang/Object;)Lorg/bytedeco/javacv/Frame;
	at org.bytedeco.javacv.OpenCVFrameGrabber.grab(OpenCVFrameGrabber.java:259)
	at com.rrdtech.recording.CustomFFmpegRecorder.main(CustomFFmpegRecorder.java:187)

Looking into this!

**Comment by saudet** [comment]
That error just means you're trying to use incompatible versions of libraries together. Use all the ones from the same version, say the latest of 0.11.

**Comment by arvind-das** [comment]
Actually, I only have 0.11 on my system. Checking if I did anything by mistake.

**Comment by saudet** [comment]
If you're using Eclipse, try to recreate your project from scratch. It's known to be pretty buggy.

**Comment by arvind-das** [comment]
Okay

**Comment by arvind-das** [comment]
did not help, still getting
Exception in thread "main" java.lang.AbstractMethodError: org.bytedeco.javacv.FrameConverter.convert(Ljava/lang/Object;)Lorg/bytedeco/javacv/Frame;
	at org.bytedeco.javacv.OpenCVFrameGrabber.grab(OpenCVFrameGrabber.java:259)
	at com.rrdtech.recording.CustomFFmpegRecorder.main(CustomFFmpegRecorder.java:187)

**Comment by saudet** [comment]
Could you try to the same thing on the command line, make sure you get the same error, and then call `java -version` and let me know the output of that? Thanks!

**Comment by arvind-das** [comment]
![recording](https://cloud.githubusercontent.com/assets/1614392/7495255/7946f0b8-f42a-11e4-8e1c-3cbec8c8ff51.png)
Executed with mvn, got almost same error with target invocation eception, attached is the image

**Comment by saudet** [comment]
Ok, this is really strange. This isn't happening here, so I'll need your help to debug this. Can you confirm that you get the same error with the following lines of code?
```java
IplImage image = IplImage.create(640, 480, IPL_DEPTH_8U, 1);
FrameConverter converter = new OpenCVFrameConverter.ToIplImage();
converter.convert(image);
```
But that calling these lines do __not__ result in a crash?
```java
IplImage image = IplImage.create(640, 480, IPL_DEPTH_8U, 1);
FrameConverter converter = new OpenCVFrameConverter.ToIplImage() {
    @Override public Frame convert(IplImage img) { return super.convert(img); }
};
converter.convert(image);
```
Thanks for your cooperation!

**Comment by arvind-das** [comment]
You are correct , results are same as you asked above . Looks like you've found something.

**Comment by saudet** [comment]
Ok, good. Doing an `mvn install -Pffmpeg` on the latest code of the master branch should fix this!

**Comment by arvind-das** [comment]
You Rock Saudet! This fix  WORKED . Thanks a LOT! Never seen someone responsive like this. Keep up the Great Work.

**Comment by arvind-das** [comment]
One more thing before it is closed, 
mixer.getLine(dataLineInfo); does not record audio but AudioSystem.getLine(dataLineInfo); DOES , atleast in my case.

**Comment by saudet** [comment]
Ok, let's update the sample accordingly. Thanks for the feedback!

As for problems with video capture under Linux, instead of `OpenCVFrameGrabber`, you might want to try `FFmpegFrameGrabber("/dev/video?")` (where ? is 0, 1, ...) with `setFormat("video4linux2")`.
