### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat()

### ISSUE THREAD

**Issue by chamecall** [bytedeco/javacv#1430]
I followed the [manual installation](https://github.com/bytedeco/javacv#manual-installation).
My steps are the next:
downloaded last release archive, unzipped it, moved to my `app/libs` folder the following jar-s:
`opencv.jar, opencv-android-arm.jar, javacpp.jar, javacpp-android-arm.jar, javacv.jar.`
And then I launch an app and get the following runtime error:
> java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.

In addition:
I remove the jar-s from `app/libs` dir and to `build.gradle`(:app) the following dependency:

>     compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.3`

and result's the same.

**Comment by saudet** [comment]
Add the JAR files for the other architectures as well.

**Comment by saudet** [comment]
And make sure that `Loader.load(opencv_java.class)` has been called.

**Comment by saudet** [comment]
I'm assuming that calling ` Loader.load(opencv_java.class)` has fixed this as documented:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation
