### ISSUE TITLE
Use java to decode audio and save the raw data in file.

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1433]
I am decoding audio file and save the decoded data into file.  

My code is like below in case of symbol size is 16bits. I can hear the decoded data are all noise, any suggestion ? thanks.

`                if (frame.samples != null) {
                    for (Buffer buffer : frame.samples) {
                        if (buffer instanceof ShortBuffer) {
                            if (byteBuffer == null || byteBuffer.remaining() < buffer.capacity() * 2) {
                                byteBuffer = ByteBuffer.allocate(buffer.capacity() * 2);
                            }
                            byteBuffer.asShortBuffer().put((ShortBuffer) buffer);
                        }

                        writeChannel.write(byteBuffer);
                        byteBuffer.clear();
                    }
                }`

**Comment by saudet** [comment]
Make sure the data actually is 16-bit and not float.

**Comment by xiaos** [comment]
Yes, i do check the buffer type. but still noise. 

`                if (frame.samples != null) {
                    for (Buffer buffer : frame.samples) {
                        if (buffer instanceof ByteBuffer) {
                            byteBuffer = (ByteBuffer) buffer;
                        } else if (buffer instanceof ShortBuffer) {
                            byteBuffer = createBuffer(byteBuffer, buffer, 2);
                            byteBuffer.asShortBuffer().put((ShortBuffer) buffer);
                        } else if (buffer instanceof IntBuffer) {
                            byteBuffer = createBuffer(byteBuffer, buffer, 4);
                            byteBuffer.asIntBuffer().put((IntBuffer) buffer);
                        } else if (buffer instanceof FloatBuffer) {
                            byteBuffer = createBuffer(byteBuffer, buffer, 4);
                            byteBuffer.asFloatBuffer().put((FloatBuffer) buffer);
                        } else if (buffer instanceof DoubleBuffer) {
                            byteBuffer = createBuffer(byteBuffer, buffer, 8);
                            byteBuffer.asDoubleBuffer().put((DoubleBuffer) buffer);
                        }

                        writeChannel.write(byteBuffer);
                        byteBuffer.clear();
                    }
                }`

**Comment by saudet** [comment]
What do you mean by "noise"? You're just saving the data to disk, you can't hear it.

**Comment by xiaos** [comment]
Hi  i play the PCM file..  all noise.  seems the byte order issue?

**Comment by xiaos** [comment]
fixed by set the order:
            byteBuffer.order(ByteOrder.LITTLE_ENDIAN);

**Comment by saudet** [comment]
I'm pretty sure FFmpeg decodes into native order.
