### ISSUE TITLE
Implement callback for FFmpegFrameRecorder

### ISSUE THREAD

**Issue by nik13** [bytedeco/javacv#1444]
Hi Team, 

I'm using FFmpegFrameRecorder to save video frames.

                
```
recorder = new FFmpegFrameRecorder("output.mkv" ,  grabber.getImageWidth(),grabber.getImageHeight());
recorder.setFormat("mkv");
recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
recorder.setFrameRate(30.0);
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); 
recorder.setVideoCodecName("libx264");
recorder.setVideoOption("crf", "37");
recorder.setVideoMetadata("encoder", "Lavf58.29.100");
recorder.start();

```

 I see the writing is not yet complete if I perform the task just after calling recorder.stop();

I need to perform certain tasks on the video file after the saving is complete and FFmpegFrameRecorder is closed completely and has finished writing frames. 

Is there any way to do it?

**Comment by saudet** [comment]
Just call stop(), that's what it does.

**Comment by saudet** [comment]
If you're getting some kind of error message, please provide it.

**Comment by nik13** [comment]
I have been calling stop().

**Comment by nik13** [comment]
I have been calling stop() but it seems like the saving is not yet complete when my next code is processed. I want to make sure the file is fully saved before executing the next line of code.

Also, there is no specific error in writing, but when I try to read it immediately after calling stop. The code works fine if I wait for a bit.

**Comment by saudet** [comment]
That sounds like a problem with your file system...
