### ISSUE TITLE
how to convert  a frame's audio data's samplerate  from 48k to 16k in javacv?

### ISSUE THREAD

**Issue by daxue2017** [bytedeco/javacv#1448]
accord the code   grabber.grabSamples  i get the rtmp's frame, frame.samples is the audio data, but it samplerate is 48k, how can i convert to 16k  by javacv interface or function?

**Comment by saudet** [comment]
Call setSampleRate() before start()

**Comment by daxue2017** [comment]
> Call setSampleRate() before start()

when i Call setSampleRate(16000) before start(),  then get a frame audio buffer  below: 
ShortBuffer buf = (ShortBuffer)frameTmp.samples[0];
int lenBuf  = buf.capacity();
 for(int i = 0;i<lenBuf;i++){
	buf.get(i);
 }


there is java.lang.IndexOutOfBoundsException  when  i = 650, but the lenBuf is 722, is there some wrong code?

**Comment by saudet** [comment]
Yes, there's most likely something wrong with your code, but I can't say if you don't show it to me.

**Comment by daxue2017** [comment]
> Yes, there's most likely something wrong with your code, but I can't say if you don't show it to me.
code below:

`    private static final String AUDIO_PATH = "rtmp://58.200.131.2:1935/livetv/hunantv";
	public static void main(String[] args) throws Exception {
		// TODO Auto-generated method stub
		FFmpegFrameGrabber fg = new FFmpegFrameGrabber(AUDIO_PATH);
		fg.setSampleRate(16000);
		
        fg.start();
        System.out.println("samplerate"+fg.getSampleRate());
        System.out.println("channel"+fg.getAudioChannels());
        System.out.println("audioFrameformat"+fg.getAudioFrameRate());
        System.out.println("audioSampleformat"+fg.getSampleFormat());
        
        Frame frameTmp = null;
        int index = 0;
        try {
            while (true) {
            	
            	frameTmp = fg.grabSamples();
            	//frameTmp.
                //f = fg.grab();
            	
                if(frameTmp == null){
                    fg.stop();
                    System.exit(0);
                }
                
                //System.out.println("get a frame tmp 1");
                System.out.println("get a frame index="+index);
                ShortBuffer buf = (ShortBuffer)frameTmp.samples[0];
                int lenBuf  = buf.capacity();
                ByteBuffer bb = ByteBuffer.allocate(lenBuf * 2);
                for(int i = 0;i<lenBuf;i++){
                	System.out.println("buf index  " + i);
                    buf.get(i);
                }
            }
        }catch (Exception e) {
        	e.printStackTrace();
        }
	}`

**Comment by saudet** [comment]
> ```java
>                 int lenBuf  = buf.capacity();
> ```

Please try to use limit() instead of capacity() here

**Comment by daxue2017** [comment]
> > ```java
> >                 int lenBuf  = buf.capacity();
> > ```
> 
> Please try to use limit() instead of capacity() here

use limit have no that problem.
