### ISSUE TITLE
Code issues：No getterseter method for imageScalingFlags in FFmpegFrameRecorder, but imageScalingFlags has to be converted in the sws-context pixel format conversion process.

### ISSUE THREAD

**Issue by eguid** [bytedeco/javacv#1449]
No getterseter method for imageScalingFlags in FFmpegFrameRecorder, but imageScalingFlags has to be converted in the sws-context pixel format conversion process.Whether the getterseter method of imageScalingFlags should be added and the judgment of adding an imageScalingFlags here in 989 lines of code？Your project is very useful to me，Thanks!
see  989 line code:
`if (video_c.pix_fmt() != pixelFormat || video_c.width() != width || video_c.height() != height) {
/* convert to the codec pixel format if needed */
                img_convert_ctx = sws_getCachedContext(img_convert_ctx, width, height, pixelFormat,
                        video_c.width(), video_c.height(), video_c.pix_fmt(),
                        imageScalingFlags != 0 ? imageScalingFlags : SWS_BILINEAR,
                        null, null, (DoublePointer)null);`

**Comment by saudet** [comment]
I see them just fine here: https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FrameRecorder.java#L189
