### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION  when use FFmpegFrameGrabber.grab

### ISSUE THREAD

**Issue by FrankKangJun** [bytedeco/javacv#1450]
I use javaCv to fetch the rtsp stream and decode the obtained picture and do some subsequent processing.
When the program runs for dozens of minutes, it often crashes.
I removed all other irrelevant code just to stream and grab images, and still crash。

**here is  part of crash log** 

A fatal error has been detected by the Java Runtime Environment:
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe1fed654e, pid=449412, tid=0x000000000006dc38

JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode windows-amd64 compressed oops)
Problematic frame:
C  [swscale-5.dll+0x6654e]

Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x000000005888c000):  JavaThread "pool-1-thread-2" [_thread_in_native, id=449592, stack(0x000000005c4c0000,0x000000005c5c0000)]

siginfo: ExceptionCode=0xc0000005, reading address 0x0000000091a11000

Registers:
RAX=0x0000000000000438, RBX=0x000000010e0a5d00, RCX=0x0000000000000001, RDX=0x000000005c5becb0
RSP=0x000000005c5bebb8, RBP=0xfffffffffffffc40, RSI=0x0000000091a11040, RDI=0x00000000000001b0
R8 =0x000000005c5bec90, R9 =0x0000000000000000, R10=0x000000010e0a3480, R11=0x00000000defc6e28
R12=0xffffffffffffffdc, R13=0x00000000f81891b0, R14=0x000000005c5beca0, R15=0xfffffffffffff880
RIP=0x00007ffe1fed654e, EFLAGS=0x0000000000010282

Top of Stack: (sp=0x000000005c5bebb8)
0x000000005c5bebb8:   0000000000000438 000000005c5becb0
0x000000005c5bebc8:   0000000000000000 00000000f817f480
0x000000005c5bebd8:   000000005c5becd0 0000000111b88080
0x000000005c5bebe8:   000000005c5bedb8 0000000000000000
0x000000005c5bebf8:   00007ffe1fea991b 00000007c00f15f0
0x000000005c5bec08:   0000000000000005 00000005c6450e10
0x000000005c5bec18:   00000000736881d0 0000000000000438
0x000000005c5bec28:   000000005c5becd0 000000005c5beca0
0x000000005c5bec38:   00000007c00f15f0 0000043800000000
0x000000005c5bec48:   000000005888c000 000000005888c000
0x000000005c5bec58:   0000000000000000 0000000000000780
0x000000005c5bec68:   0000000073655359 000000000188c000
0x000000005c5bec78:   0000000000000000 00000007c00b1e68
0x000000005c5bec88:   000000005888c1f8 0000004000000080
0x000000005c5bec98:   0000000000000040 0000000000001680
0x000000005c5beca8:   0000000000000000 0000000091a030c0 

Instructions: (pc=0x00007ffe1fed654e)
0x00007ffe1fed652e:   db 15 a4 82 01 00 0f eb cb 0f eb c6 0f eb cd 0f
0x00007ffe1fed653e:   eb d7 41 0f e7 03 41 0f e7 4b 08 41 0f e7 53 10
0x00007ffe1fed654e:   42 0f 6f 74 66 08 43 0f 6e 4c 22 04 42 0f 6e 44
0x00007ffe1fed655e:   23 04 49 83 c3 18 49 83 c4 04 0f 88 ed fe ff ff 

Register to memory mapping:

RAX=0x0000000000000438 is an unknown value
RBX=0x000000010e0a5d00 is an unknown value
RCX=0x0000000000000001 is an unknown value
RDX=0x000000005c5becb0 is pointing into the stack for thread: 0x000000005888c000
RSP=0x000000005c5bebb8 is pointing into the stack for thread: 0x000000005888c000
RBP=0xfffffffffffffc40 is an unknown value
RSI=0x0000000091a11040 is an unknown value
RDI=0x00000000000001b0 is an unknown value
R8 =0x000000005c5bec90 is pointing into the stack for thread: 0x000000005888c000
R9 =0x0000000000000000 is an unknown value
R10=0x000000010e0a3480 is an unknown value
R11=0x00000000defc6e28 is an unknown value
R12=0xffffffffffffffdc is an unknown value
R13=0x00000000f81891b0 is an unknown value
R14=0x000000005c5beca0 is pointing into the stack for thread: 0x000000005888c000
R15=0xfffffffffffff880 is an unknown value

Stack: [0x000000005c4c0000,0x000000005c5c0000],  sp=0x000000005c5bebb8,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [swscale-5.dll+0x6654e]
C  [swscale-5.dll+0x3991b]
C  0x0000000004100ab9

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 1300  org.bytedeco.ffmpeg.global.swscale.sws_scale(Lorg/bytedeco/ffmpeg/swscale/SwsContext;Lorg/bytedeco/javacpp/PointerPointer;Lorg/bytedeco/javacpp/IntPointer;IILorg/bytedeco/javacpp/PointerPointer;Lorg/bytedeco/javacpp/IntPointer;)I (0 bytes) @ 0x0000000004100a3b [0x0000000004100980+0xbb]
J 1378 C2 org.bytedeco.javacv.FFmpegFrameGrabber.processImage()V (508 bytes) @ 0x000000000416d5d8 [0x000000000416d000+0x5d8]
J 1364 C2 org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame(ZZZZZ)Lorg/bytedeco/javacv/Frame; (966 bytes) @ 0x0000000004147f10 [0x0000000004147a40+0x4d0]
J 1339 C2 test.FVideoGrabber.grab()Lorg/bytedeco/javacv/Frame; (124 bytes) @ 0x000000000412eb4c [0x000000000412ea60+0xec]
J 1355% C1 test.FVideoGrabberExecutor.run()V (53 bytes) @ 0x000000000413303c [0x0000000004132f80+0xbc]
j  java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object;+4
j  java.util.concurrent.FutureTask.run()V+42
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub**

**and here is my text code**
`
public class FVideoGrabber {

    private static int MAX_NO_FRAME_COUNT = 10;
    private FFmpegFrameGrabber grabber;
    private String rtsp;
    private volatile boolean isRunning = false;
    private volatile boolean isFirstTime = true;
    private int noFrameCount = 0;

    public FVideoGrabber( String rtsp) {
        this.rtsp = rtsp;
        this.grabber = initGrabber();
    }

    private FFmpegFrameGrabber initGrabber() {
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(rtsp);
        grabber.setOption("rtsp_transport", "tcp");
        grabber.setOption("stimeout", "5000000");
        grabber.setFrameRate(20);
        return grabber;
    }

    public String getRtsp() {
        return rtsp;
    }

    public void setRtsp(String rtsp) {
        this.rtsp = rtsp;
    }

    public FFmpegFrameGrabber getGrabber() {
        return grabber;
    }

    public Frame grab() {
        if (!isRunning) {
            restart();
        }

        try {
            Frame grab = grabber.grab();
            for (int noFrameCount = 0; !isGrabbed(grab) && noFrameCount < 2; noFrameCount++) {
                grab = grabber.grab();
            }
            if (isGrabbed(grab)) {
                noFrameCount = 0;
            } else {
                noFrameCount++;
                if (noFrameCount > MAX_NO_FRAME_COUNT) {
                    isRunning = false;
                    noFrameCount = 0;
                    log.warn("The number of pull stream continuous errors exceeds[{}]times，Try to restart the streaming service【{}】", MAX_NO_FRAME_COUNT, rtsp);
                }
            }
            return grab;

        } catch (Exception e) {
            isRunning = false;
        }
        return null;

    }

    private boolean isGrabbed(Frame frame) {
        return !(frame == null || frame.image == null);
    }

    private void restart() {
        stop();
        start();
    }

    public void close() {
        if (grabber != null) {
            try {
                grabber.close();
                log.info("grabber closed,cameraInfo:" + rtsp);
            } catch (Exception e) {
                log.error("release the grabber error,CameraInfo:" + rtsp, e);
            }
        }
    }

    private void stop() {
        if (grabber != null && !isFirstTime) {
            try {
                grabber.stop();
                log.info("grabber stopped，CameraInfo" + rtsp);
            } catch (Exception e) {
                log.error("stop the recorder error,CameraInfo:" + rtsp, e);
            }
        }
    }

    private void start() {
        try {
            grabber.start();
            log.info("grabber started，cameraInfo" + rtsp);
        } catch (Exception e) {
            isRunning = false;
            log.error("start the recorder error,CameraInfo:" + rtsp, e);
            return;
        }
        isRunning = true;
        isFirstTime = false;
    }

    public boolean isRunning() {
        return isRunning;
    }
}
`
`
public class FVideoGrabberThread implements Runnable {

    static {
        avutil.av_log_set_level(avutil.AV_LOG_ERROR);
    }

    private static int RECOGNITION_INTERVAL_MS = 1000;
    private String rtsp;
    private FVideoGrabber grabber;
    private volatile boolean isRunning = false;

    public FVideoGrabberExecutor(String rtsp) {
        this.rtsp = rtsp;
        this.grabber = new FVideoGrabber(rtsp);
    }

    public FVideoGrabber getGrabber() {
        return grabber;
    }

    @Override
    public void run() {
        isRunning = true;
        try {
            while (isRunning) {
                try {
                    Frame frame = this.grabber.grab();
                } catch (Exception e) {
                    log.error("Error in grabbing and pushing", e);
                }
            }
        }finally {
            doClose();
        }

    }

    private void doClose() {
        this.grabber.close();
    }

    public void close() {
        isRunning = false;
    }
}

`
`
public class ListenTest {
    public static void main(String[] args) {

        ExecutorService executorService = Executors.newFixedThreadPool(32);
        List<String> list = Lists.newArrayList();
        list.add("rtsp://admin:Admin12345@192.168.61.71:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.94:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.100:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.87:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.83:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.82:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.68:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.99:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.95:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.89:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.70:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.69:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.72:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.85:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.98:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.91:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.93:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.97:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.90:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.92:554/Streaming/Channels/101?transportmode=multicast");
        list.add("rtsp://admin:Admin12345@192.168.61.96:554/Streaming/Channels/101?transportmode=multicast");

        list.forEach(
                address -> executorService.submit(new FVideoGrabberThread(address))
        );
    }
}

`
>

**Comment by saudet** [comment]
Probably caused by corrupted frames. Check the log for any errors or
warnings.

**Comment by FrankKangJun** [comment]
Sometimes there are errors in decoding like this 

[h264 @ 0000000076ddf800] no frame!
[h264 @ 0000000076dddc80] error while decoding MB 87 57, bytestream -8
[h264 @ 0000000076ddb380] Invalid NAL unit 0, skipping.
[h264 @ 0000000076ddb380] Invalid NAL unit 0, skipping.
[h264 @ 0000000076ddb380] Invalid NAL unit 0, skipping.
[h264 @ 00000000bfc40c00] error while decoding MB 35 38, bytestream -5
[rtsp @ 0000000076f08f00] Undefined type (30)
[h264 @ 000000008f477980] Invalid NAL unit 0, skipping.
[h264 @ 000000008f477980] Invalid NAL unit 0, skipping.
[h264 @ 000000008f477980] Invalid NAL unit 0, skipping.
[h264 @ 000000008f477980] error while decoding MB 118 13, bytestream -11
[h264 @ 0000000086227dc0] Invalid NAL unit 8, skipping.
[h264 @ 0000000086227dc0] error while decoding MB 65 29, bytestream -7
[h264 @ 0000000076ddb800] error while decoding MB 52 47, bytestream -15
[h264 @ 000000007df5dc00] error while decoding MB 81 60, bytestream -5
[h264 @ 000000008622b480] Invalid NAL unit 0, skipping.
[h264 @ 000000008622b480] error while decoding MB 65 29, bytestream -7
[h264 @ 0000000086229940] cabac decode of qscale diff failed at 87 17
[h264 @ 0000000086229940] error while decoding MB 87 17, bytestream 753
[h264 @ 000000007df5d780] error while decoding MB 54 37, bytestream -9
[h264 @ 00000000bfc3d540] error while decoding MB 83 57, bytestream -7
[h264 @ 00000000bfc47080] error while decoding MB 9 30, bytestream -5
[NULL @ 00000000bfc387c0] FMO not supported
[h264 @ 00000000bfc42780] Invalid NAL unit 1, skipping.
[h264 @ 000000007df5d300] error while decoding MB 62 61, bytestream -5
[h264 @ 000000008f473e00] error while decoding MB 41 40, bytestream -10

Most of the time is normal

How can I avoid the program crash caused by these corrupted frames

**Comment by FrankKangJun** [comment]
> Probably caused by corrupted frames. Check the log for any errors or warnings.

Sometimes there are errors in decoding like this

[h264 @ 0000000076ddf800] no frame!
[h264 @ 0000000076dddc80] error while decoding MB 87 57, bytestream -8
[h264 @ 0000000076ddb380] Invalid NAL unit 0, skipping.
[h264 @ 0000000076ddb380] Invalid NAL unit 0, skipping.
[h264 @ 0000000076ddb380] Invalid NAL unit 0, skipping.
[h264 @ 00000000bfc40c00] error while decoding MB 35 38, bytestream -5
[rtsp @ 0000000076f08f00] Undefined type (30)
[h264 @ 000000008f477980] Invalid NAL unit 0, skipping.
[h264 @ 000000008f477980] Invalid NAL unit 0, skipping.
[h264 @ 000000008f477980] Invalid NAL unit 0, skipping.
[h264 @ 000000008f477980] error while decoding MB 118 13, bytestream -11
[h264 @ 0000000086227dc0] Invalid NAL unit 8, skipping.
[h264 @ 0000000086227dc0] error while decoding MB 65 29, bytestream -7
[h264 @ 0000000076ddb800] error while decoding MB 52 47, bytestream -15
[h264 @ 000000007df5dc00] error while decoding MB 81 60, bytestream -5
[h264 @ 000000008622b480] Invalid NAL unit 0, skipping.
[h264 @ 000000008622b480] error while decoding MB 65 29, bytestream -7
[h264 @ 0000000086229940] cabac decode of qscale diff failed at 87 17
[h264 @ 0000000086229940] error while decoding MB 87 17, bytestream 753
[h264 @ 000000007df5d780] error while decoding MB 54 37, bytestream -9
[h264 @ 00000000bfc3d540] error while decoding MB 83 57, bytestream -7
[h264 @ 00000000bfc47080] error while decoding MB 9 30, bytestream -5
[NULL @ 00000000bfc387c0] FMO not supported
[h264 @ 00000000bfc42780] Invalid NAL unit 1, skipping.
[h264 @ 000000007df5d300] error while decoding MB 62 61, bytestream -5
[h264 @ 000000008f473e00] error while decoding MB 41 40, bytestream -10

Most of the time is normal

How can I avoid the program crash caused by these corrupted frames

**Comment by saudet** [comment]
There's probably a bug somewhere that someone will need to debug...

**Comment by FrankKangJun** [comment]
I upgraded javaCv from 1.5.3 to 1.5.4 of the snapshot version, and continued to run for more than a day, the crash no longer occurred, it seems to be resolved
