### ISSUE TITLE
java.lang.NullPointerException: This pointer address is NULL.

### ISSUE THREAD

**Issue by swedishdeveloper** [bytedeco/javacv#1455]
Hey!
Thanks for providing FFmpeg, JavaCV and JavaCPP for Android. 
After some tests using the snapshots at https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/ I discovered a problem with the latest JavaCV snapshot for Android. 

When I trying to record Audio with this method:
 try {
            if (frameRecorder != null && audioData != null) {
                frameRecorder.recordSamples(48000, 2, audioData); //record audio!
            }
        } catch (FrameRecorder.Exception e) {
            handleError(e.getMessage()); //handle error!
        }

So get I this error message:
    java.lang.NullPointerException: This pointer address is NULL.
        at org.bytedeco.javacpp.ShortPointer.put(Native Method)
        at org.bytedeco.javacv.FFmpegFrameRecorder.recordSamples(FFmpegFrameRecorder.java:1111)

When I downgraded back to Javacv 1.5.3 everything worked fine without any error messages. So there seems to be a bug on the latest JavaCv snapshots.

Best Regards
Benjamin

**Comment by saudet** [comment]
Thanks for reporting! I've fixed this in the last commit, so please try again with latest snapshots.
