### ISSUE TITLE
The temporary CPU rate is too high use FFmpegFrameGrabber and FFmpegFrameRecorder

### ISSUE THREAD

**Issue by yangqx** [bytedeco/javacv#1461]
I wanted to record some video from the video stream to store, but found the program's temporary CPU was too high (used 40%,i5-8265U@1.80GHz).if i use "Process p = run.exec(cmd); "
I found CPU was very low  (used 1.5%), why  ? How can I reduce CPU usage  use FFmpegFrameGrabber and FFmpegFrameRecorder?

This is my code snippet:

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);
        grabber.setOption("rtsp_transport", "tcp");
        grabber.setOption("c","copy");
        grabber.setFrameRate(24);
        grabber.setPixelFormat(AV_PIX_FMT_YUVJ420P);
        grabber.setOption("stimeout", "10000000");// 10 seconds
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputFile, 3840, 2160,audioChannel);

        recorder.setFormat("flv"); 
        recorder.setFrameRate(25);
        recorder.setPixelFormat(0); // yuv420p
        recorder.setOption("c","copy");
        grabber.start();
        recorder.start();
        Frame frame = null;
        while (status&& (frame = grabber.grabFrame()) != null) {
                recorder.record(frame);
        }

**Comment by saudet** [comment]
To copy packets without reencoding, use grabPacket() and recordPacket() like this:
https://github.com/bytedeco/javacv/blob/master/samples/PacketRecorderTest.java

**Comment by yangqx** [comment]
error: av_write_frame() error -22 while writing video packet.


when i use "PacketRecorderTest.packetRecord(...)"  , I try to set "setTimestamp"  ,don't work. but  i used other carmera to recorder video, can work.
I encountered the following error, What's the problem?

pts=21600, dts=21600
grabberTimestamp=0, recorderTimestamp=0
pts=3600, dts=3600
grabberTimestamp=0, recorderTimestamp=40000
Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -22 while writing video packet.
	at org.bytedeco.javacv.FFmpegFrameRecorder.writePacket(FFmpegFrameRecorder.java:1230)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordPacket(FFmpegFrameRecorder.java:1259)
	at com.tflx.video.grabber.service.PacketRecorderTest.packetRecord(PacketRecorderTest.java:84)
	at com.tflx.video.grabber.service.PacketRecorderTest.main(PacketRecorderTest.java:36)
Input #0, rtsp, from 'rtsp://192.168.10.66:554/h264/ch1/main/av_stream':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.240000, bitrate: N/A
    Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn, 50 tbc
[avi @ 0000000021bcd840] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Output #0, avi, to './videoFile/_packetRecord.avi':
  Metadata:
    ISFT            : Lavf58.20.100
    Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p(progressive), 1920x1080, q=2-31, SAR 1:1 DAR 16:9, 25 fps, 25 tbn, 25 tbc
[avi @ 0000000021bcd840] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 6 >= 1

Process finished with exit code 1

this is my code:
-----------------------------------------------



String inputFile = "rtsp://192.168.10.66:554/h264/ch1/main/av_stream";
String outputFile = "./videoFile/_packetRecord.avi";
PacketRecorderTest.packetRecord(inputFile, outputFile);

public static void packetRecord(String inputFile, String outputFile) throws FrameGrabber.Exception, FrameRecorder.Exception {

        int audioChannel = AUDIO_ENABLED ? 1 : 0;

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputFile);
        grabber.setOption("rtsp_transport", "tcp");
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputFile, 1920, 1080, audioChannel);
        recorder.setFrameRate(grabber.getFrameRate());
        recorder.setFormat(grabber.getFormat());
        grabber.start();
        recorder.start(grabber.getFormatContext());


        AVPacket packet;
        long t1 = System.currentTimeMillis();
        while ((packet = grabber.grabPacket()) != null) {
            System.out.println("pts=" + packet.pts() + ", dts=" + packet.dts());
            System.out.println("grabberTimestamp=" + grabber.getTimestamp() + ", recorderTimestamp=" + recorder.getTimestamp());
            if (grabber.getTimestamp() > recorder.getTimestamp()) {
                recorder.setTimestamp(grabber.getTimestamp());
            }
            recorder.setTimestamp(packet.dts());
            recorder.recordPacket(packet);
            if ((System.currentTimeMillis() - t1) > RECORD_LENGTH) {
                break;
            }
        }

        recorder.stop();
        grabber.stop();

    }

**Comment by saudet** [comment]
There are known issues with grabPacket() and recordPacket(), see issue #818.
