### ISSUE TITLE
Error in `java': corrupted double-linked list

### ISSUE THREAD

**Issue by yangjiechina** [bytedeco/javacv#1468]
[flv @ 0x7f64644dd200] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Output #0, flv, to 'rtmp://192.168.2.194:1935/hls/32068100098107110302_34000000002000000003_Play?ssrc=0200000080':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Baseline) ([7][0][0][0] / 0x0007), yuv420p(progressive), 1280x720, q=2-31, SAR 1:1 DAR 16:9, 25 fps, 1k tbn, 25 tbc
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 8000 Hz, mono, fltp, 48 kb/s
[aac @ 0x7f64644e0400] Qavg: -nan
*** Error in `java': corrupted double-linked list: 0x00007f6464028b50 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x809bf)[0x7f65ebff19bf]
/lib64/libc.so.6(+0x8117e)[0x7f65ebff217e]
/root/.javacpp/cache/ffmpeg-4.2.2-1.5.3-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavutil.so.56(av_buffer_unref+0x39)[0x7f6582cf8809]
/root/.javacpp/cache/ffmpeg-4.2.2-1.5.3-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.58(+0x35e40e)[0x7f653553240e]
/root/.javacpp/cache/ffmpeg-4.2.2-1.5.3-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavcodec.so.58(av_parser_close+0x18)[0x7f6535793ab8]
/root/.javacpp/cache/ffmpeg-4.2.2-1.5.3-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.58(+0x1d6d8b)[0x7f65816ead8b]
/root/.javacpp/cache/ffmpeg-4.2.2-1.5.3-linux-x86_64.jar/org/bytedeco/ffmpeg/linux-x86_64/libavformat.so.58(avformat_free_context+0x77)[0x7f65816f6bb7]
[0x7f65d5018407]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:01 135313614                          /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64/jre/bin/java
00600000-00601000 r--p 00000000 08:01 135313614                          /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64/jre/bin/java
00601000-00602000 rw-p 00001000 08:01 135313614                          /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-7.b13.el7.x86_64/jre/bin/java
01a01000-01a22000 rw-p 00000000 00:00 0                                  [heap]

**Comment by yangjiechina** [comment]
Hello，You encounter this problem when pushing the RTMP stream. Can upgrading FFMPEG be solved

**Comment by saudet** [comment]
Yes, please try with JavaCV 1.5.4-SNAPSHOT: http://bytedeco.org/builds/
