### ISSUE TITLE
Sift.detectandCompute gets killed on Raspberry Pi

### ISSUE THREAD

**Issue by Saibot900** [bytedeco/javacv#1469]
![image](https://user-images.githubusercontent.com/37349846/87760402-ffce5b80-c80f-11ea-807e-a601d8d4b889.png)

When I try to run my builded jar, which detects Keypoints in an Image, the Programm gets killed on the Raspberry Pi with CPU Usage 100%. Is there any alternative or is it an programming error?

![image](https://user-images.githubusercontent.com/37349846/87760914-dcf07700-c810-11ea-8884-6bb2d706860f.png)

**Comment by saudet** [comment]
It might be running out of memory? Have you tried to increase the size of the swap space?

**Comment by Saibot900** [comment]
Thanks, that did it for me🙏
