### ISSUE TITLE
Return type 'explicit' is not supported, skipping the function

### ISSUE THREAD

**Issue by carbotaniuman** [bytedeco/javacv#1470]
//
    // C++:  explicit cv::VideoCapture::VideoCapture(String filename, int apiPreference = CAP_ANY)
    //

    // Return type 'explicit' is not supported, skipping the function

Some important functions in VideoCapture (and probably elsewhere) aren't being generated.

**Comment by saudet** [comment]
Please let me know which ones in particular, and we'll take a look at this. Thanks!

**Comment by saudet** [comment]
As far as I know, all functions for VideoCapture are being generated:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_videoio/VideoCapture.html

But if you need anything else, please let me now.
