### ISSUE TITLE
how to add live camera filter on the video recording ?

### ISSUE THREAD

**Issue by iamkdblue** [bytedeco/javacv#1471]
Thank you all for this great library

I am looking for how to apply a live filter on the video recording, I searched a lot but didn't find any solution.
Help is highly appreciated

Thank You.

**Comment by saudet** [comment]
Try something like this: https://github.com/bytedeco/javacv/blob/master/samples/DeinterlacedVideoPlayer.java

**Comment by saudet** [comment]
There's also some examples here:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java

It is sometimes also easier to use the ffmpeg program:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
