### ISSUE TITLE
How to calculate Homography with SIFT?

### ISSUE THREAD

**Issue by Saibot900** [bytedeco/javacv#1472]
Is there a new way of calculating the homography with SIFT algorithm, since it's not Version 2.4?
Always getting the error: 

'The input arrays should be 2D or 3D point sets in function 'cv::findHomography''

With code:
```java Mat homography = new Mat();
        findHomography(homography,srcImg,refImg,RANSAC,3); 
```
as srcImg and refImg Mat has been loaded with ``` srcImg=imread(new File(srcImgPath).getAbsolutePath(),IMREAD_COLOR);```

I have also tried to calculate it with the KeyPoints, but that also didn't work, as the MatOfPoint2f is no longer available.

```java 
        Mat object = new Mat();
        Mat scene = new Mat();

        for (DMatch dMatch : goodMatchesList) {
            object.put(keyPointsSrc.get()[dMatch.queryIdx()].pt());
            scene.put(keyPointsRef.get()[dMatch.trainIdx()].pt());
        }

        Mat homography = new Mat();
        findHomography(homography,object,scene,RANSAC,3);
```

Same error: ' 'The input arrays should be 2D or 3D point sets in function 'cv::findHomography'' '

**Comment by saudet** [comment]
There's a working example of that here:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/ObjectFinder.java
