### ISSUE TITLE
Iplimage as CvMat

### ISSUE THREAD

**Issue by DHametner** [bytedeco/javacv#1473]
Hi Mr. Audet,
i wanted to execute this code snippet:
```Java
IplImage _srcImg = new IplImage(srcImg);
IplImage _dstImg = new IplImage();
IplImage _direction = new IplImage(direction.getDirection());

cvFilter2D(_srcImg, _dstImg, _direction.asCvMat());
```
and this exception was thrown: ```java.lang.RuntimeException: OpenCV(4.3.0) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.3.0\modules\core\src\array.cpp:2492: error: (-206:Bad flag (parameter or structure field)) Unrecognized or unsupported array type in function 'cvGetMat'```

does the method cvFilter2D work? or should i use the method filter2D instead?
i already tried this:
```Java
filter2D(srcImg, dstImg, srcImg.depth(), direction.getDirection());
```
and it works but i also want that cvFilter2D works?

**Comment by saudet** [comment]
You'll need to allocate `_dstImg` to "the same size and the same number of channels as src". It won't work with an empty image like that: https://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html#filter2d

The C API is deprecated, so yes you should use the C++ API if possible.

**Comment by DHametner** [comment]
> 
> 
> You'll need to allocate `_dstImg` to "the same size and the same number of channels as src". It won't work with an empty image like that: https://docs.opencv.org/2.4/modules/imgproc/doc/filtering.html#filter2d
> 
> The C API is deprecated, so yes you should use the C++ API if possible.

thanks that helped me a lot
