### ISSUE TITLE
org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -110: Could not open 'null'

### ISSUE THREAD

**Issue by NagaHariKrishnaVadisala** [bytedeco/javacv#1479]
Hi, I am facing the following issue:

W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -110: Could not open 'null'
W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:824)
W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:368)

what is the error code -110 returns?

Thanks!!

**Comment by saudet** [comment]
Errno 110 is "Connection timed out": Sounds like a problem with your network.
