### ISSUE TITLE
Package cl.eye does not exists

### ISSUE THREAD

**Issue by kiquetal** [bytedeco/javacv#148]
Downloaded the code, run mvn install, import maven project inside netbeans but, the following class shows error:

PS3EyeFrameGrabber

also de 

test/
FrameConverterTest.java

line:
 frameIdx.putDouble(new int[] {y, x, z}, y + x + z);

java oracle 1.7

Amazing package,!Thanks!

**Comment by saudet** [comment]
Do the same with JavaCPP first to get the latest code. And you can ignore
the error. This is just a small bug in NetBeans.

**Comment by saudet** [comment]
Given the lack of feedback, I'm guessing this has been resolved, but please let me know if you still have issues with this, thanks!
