### ISSUE TITLE
How to open Android camera in javacv

### ISSUE THREAD

**Issue by hongqimei** [bytedeco/javacv#1482]
How to open Android camera in javacv

**Comment by hongqimei** [comment]
org.bytedeco.javacv.FrameGrabber$Exception: read() Error: Could not read frame in start().

**Comment by saudet** [comment]
You do not, you use Android's API for that.

**Comment by hongqimei** [comment]
OK，thank

**Comment by saudet** [comment]
Something like `new FFmpegFrameGrabber("0:0").setFormat("android_camera")` may work though.

**Comment by kshitijgarg2609** [comment]
I am using VideoCapture and open() function and given all the permissions still I can't open camera. I am using android 4.2.1 and extracted all the platforms jars like opencv-androidx86 in jniLibs folder along with ffmpeg and openblas. Please help me to open camera in android
![image](https://user-images.githubusercontent.com/48625716/142001682-0db47b0a-6edc-45ff-8e8b-8b9930c77d06.png)

you can check my menifest file

![image](https://user-images.githubusercontent.com/48625716/142001956-488559db-2460-4e72-9c94-bd431d83ec10.png)
