### ISSUE TITLE
Video playback stutter (JavaCV+JavaFX)

### ISSUE THREAD

**Issue by CountZukula** [bytedeco/javacv#1483]
I'm trying to get a minimal raspberrypi cam feed up and running. 

On the PI, I launch this command: `cvlc --no-audio v4l2:///dev/video0 --v4l2-width 800 --v4l2-height 600 --v4l2-chroma h264 --v4l2-fps 30 --sout '#standard{access=http,mux=ts,dst=:2222/}' -I "dummy"`, hosting the http feed on `localhost:2222`.

Testing this in VLC works flawlessly (smooth framerate, no slowdowns or buffering), through `http://ip:2222`.

Going through JavaCV however shows a choppy framerate. I am not outputting anything to the console and am not doing intensive calculation behind the scenes (timed all calls and they're below 10ms per frame). I'll summarize the flow (check the full, less readable, version here: https://github.com/CountZukula/opencv-speed/blob/master/src/main/kotlin/RxController.kt)

```kotlin
val grabber = FFmpegFrameGrabber(cameraUri)
val grabbedImage = grabber.grabImage()
converterCV.convert(grabbedImage ).copyTo(original.mat)
val bufferedImage: BufferedImage = converter2D.getBufferedImage(converterCV.convert(original.mat))
val r = SwingFXUtils.toFXImage(bufferedImage, null)
canvasFrame.graphicsContext2D.drawImage(r, 0.0, 0.0)
```
I've tried a couple of things to switch things up: 
- went from procedural to rxJava
- converted through `JavaFXFrameConverter` instead of `cvtColor`
- used ImageView and Canvas
- launched within Intellij IDEA and from a built fat jar, no difference

Any clue on where to proceed? Looking online, it seems that I should at least be getting 30 fps. So I guess I'm doing _something_ wrong.

**Comment by saudet** [comment]
Don't use Java 2D, that's slow. See https://github.com/rladstaetter/javacv-webcam for a good example from @rladstaetter.

**Comment by CountZukula** [comment]
Thanks for the suggestion @saudet ! I updated my test code and it now uses the same methodology, however, I'm experiencing the same choppiness. This lead me to see how the source was behaving (the FFmpegGrabber) and I constructed this test:

```kotlin
    val cameraUri = "http://192.168.178.111:2222"
    val grabber = FFmpegFrameGrabber(cameraUri)
    grabber.start()
    val counter = Counter()
    val vertx = Vertx.vertx()
    val int = AtomicInteger()
    vertx.setPeriodic(33) { //repeat every 33 seconds, output and reset the counter
        println("int: ${int.incrementAndGet()} fps: ${counter.perSecond()} counter: ${counter.count} millis: ${counter.millisPassed()}")
        counter.reset()
    }
    while (true) {
        val image = grabber.grab()
        counter.inc()
    }
```
This fetches a frame whenever it is available. The specified counter runs on a separate thread and I would expect it to output +- 1 frame per second (as the input stream is 30fps). That outputs this pattern, which could explain the choppiness:
```
int: 1 fps: 70.01321003963012 counter: 53 millis: 758
int: 2 fps: 0.0 counter: 0 millis: 30
int: 3 fps: 0.0 counter: 0 millis: 30
int: 4 fps: 0.0 counter: 0 millis: 31
int: 5 fps: 0.0 counter: 0 millis: 47
int: 6 fps: 0.0 counter: 0 millis: 31
int: 7 fps: 187.5 counter: 6 millis: 32
int: 8 fps: 0.0 counter: 0 millis: 31
int: 9 fps: 0.0 counter: 0 millis: 30
int: 10 fps: 0.0 counter: 0 millis: 32
int: 11 fps: 0.0 counter: 0 millis: 30
int: 12 fps: 0.0 counter: 0 millis: 46
int: 13 fps: 0.0 counter: 0 millis: 31
int: 14 fps: 225.80645161290323 counter: 7 millis: 31
int: 15 fps: 0.0 counter: 0 millis: 31
int: 16 fps: 0.0 counter: 0 millis: 31
int: 17 fps: 0.0 counter: 0 millis: 31
int: 18 fps: 0.0 counter: 0 millis: 32
int: 19 fps: 0.0 counter: 0 millis: 31
int: 20 fps: 0.0 counter: 0 millis: 31
int: 21 fps: 148.93617021276594 counter: 7 millis: 47
int: 22 fps: 0.0 counter: 0 millis: 30
int: 23 fps: 0.0 counter: 0 millis: 31
int: 24 fps: 0.0 counter: 0 millis: 31
int: 25 fps: 0.0 counter: 0 millis: 31
int: 26 fps: 0.0 counter: 0 millis: 31
int: 27 fps: 31.25 counter: 1 millis: 32
```
You can see that the frames seem to come in bursts. Am I perhaps misconfiguring the FFmpegFrameGrabber?

**Comment by saudet** [comment]
Looks like some issue with your network. You could try to perform some buffering over a second or so to compensate.

**Comment by CountZukula** [comment]
Again thanks for the suggestion @saudet, implemented a crude system so the host can delay processing if necessary, it's running smoothly now.

**Comment by saudet** [comment]
Good! It might be possible increase "buffer_size" or other options from FFmpeg depending on the protocol:
https://ffmpeg.org/ffmpeg-protocols.html
