### ISSUE TITLE
FFmpegFrameGrabber.getLengthInTime() is 0

### ISSUE THREAD

**Issue by chenhl05** [bytedeco/javacv#1491]
Hello, I can't get the duration time of video file.
I use VideoInputFrameGrabber open webcam.
The FFmpegFrameRecorder also call setTimestamp() function.
But FFmpegFrameGrabber.getLengthInTime() can't get duration of video file , which FFmpegFrameRecorder generating.
Could you help me ?

**Comment by saudet** [comment]
Not all video files come with that information, that's normal. To have
FFmpegFrameRecorder write that information, you'll need to call stop().

**Comment by MayZhou** [comment]
> Not all video files come with that information, that's normal. To have FFmpegFrameRecorder write that information, you'll need to call stop().

can I use close() for the same purpose?

**Comment by saudet** [comment]
Yes, it calls stop():
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FrameRecorder.java#L398

**Comment by chenhl05** [comment]
Thanks, it took effect after I changed my code.
