### ISSUE TITLE
if surport play h265 flv?

### ISSUE THREAD

**Issue by wangpeng1** [bytedeco/javacv#1497]

**Comment by saudet** [comment]
Please explain what isn't working.

**Comment by saudet** [comment]
Duplicate of #1496

**Comment by wangpeng1** [comment]
@saudet I have record local video,the format is h265 Flv. if the javacv can play flv with H265.the flv is local video not rtmp.

**Comment by saudet** [comment]
Yes, I'm pretty sure that works. Let me know if it does not work though.

**Comment by saudet** [comment]
No, actually, it looks like it's not supported:
https://trac.ffmpeg.org/ticket/3581
https://trac.ffmpeg.org/ticket/6389

**Comment by wangpeng1** [comment]
@saudet  which  javacv android api can use to play local video，I want to test it

**Comment by saudet** [comment]
JavaCV doesn't come with a player, but we can make one with FFmpegFrameGrabber to get audio and video frames.
