### ISSUE TITLE
Grabber still use old version of API

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1498]
Hi I found the grabber is still using avcodec_decode_video2() to decode video, but this method is deprecated, may i know why not update to the new version of API? Thanks.

**Comment by saudet** [comment]
We just need someone to spend a bit of time working on this. If you can,
please make the upgrade and send a pull request! Contributions are welcome

**Comment by saudet** [comment]
Done in commit https://github.com/bytedeco/javacv/commit/c952a23cc33ace29688ce577ce116d65bb1146b4! Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
JavaCV 1.5.6 now uses the new API. Enjoy!
