### ISSUE TITLE
Error when convert BufferedImage to IplImage !

### ISSUE THREAD

**Issue by henriquem** [bytedeco/javacv#150]
Hi @saudet 
I have found an problem, if you fixed, please let me know Where I can get download again

The Problem is when I convert BufferedImage to IplImage its works fine:

         public static IplImage convertBuffToIplImage(BufferedImage img){
		    Java2DFrameConverter converter1 = new Java2DFrameConverter();
             OpenCVFrameConverter.ToIplImage converter2 = new OpenCVFrameConverter.ToIplImage();
             IplImage iploriginal = converter2.convert(converter1.convert(img));
		     return iploriginal;
	     }

The BufferedImage from parameter has type 3 of Image.
After 2 seconds, When I save the IplImage converted ocurred an error, in order to my application stop

Error StackTrace:

    #Problematic frame:
    # C  [opencv_highgui2411.dll+0xa020]  cvEncodeImage+0x15b0
    #
    # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
    # An error report file with more information is saved as:
    # C:/worspace/test\hs_err_pid9492.log

Openning the file hs_err_pid9492.log:

    tack: [0x08070000,0x080c0000],  sp=0x080be228,  free space=312k
    Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
    C  [opencv_highgui2411.dll+0xa020]  cvEncodeImage+0x15b0
    C  [opencv_highgui2411.dll+0x1e582]  cv::Mat::MStep::operator unsigned int+0x5ba2
    C  [opencv_highgui2411.dll+0x647a]  cv::Mat::create+0x22da
    C  [opencv_highgui2411.dll+0x8948]  cvSaveImage+0x128
    C  [jniopencv_highgui.dll+0xad09]  Java_org_bytedeco_javacpp_opencv_1highgui_cvSaveImage__Ljava_lang_String_2Lorg_bytedeco_javacpp_helper_opencv_1core_00024CvArr_2+0x49
    j  org.bytedeco.javacpp.opencv_highgui.cvSaveImage(Ljava/lang/String;Lorg/bytedeco/javacpp/opencv_core$IplImage;)V+33

**Comment by maxsmirnov92** [comment]
Try to copy BufferedImage data to IplImage that way:

			BufferedImage bufImage = new BufferedImage(320, 240, BufferedImage.TYPE_3BYTE_BGR);

                       // depth and channels number depend on source bufImage.getType() 
			IplImage iplImage = IplImage.create(bufImage.getWidth(), bufImage.getHeight(),
					opencv_core.IPL_DEPTH_8U, 3);
			
			iplImage.copyFrom(bufImage);

btw you can directly use BufferedImage or IplImage byte array:

			byte[] data = new byte[iplImage.getByteBuffer().capacity()];
			
			iplImage.getByteBuffer().get(data);
			
			data =  ((DataBufferByte) bufImage.getRaster().getDataBuffer()).getData();

**Comment by henriquem** [comment]
Hi @maxsmirnov92 , Thanks for respond!

the line bellow, not exists on version "javacpp-presets-opencv-2.4.11-0.11" :

    iplImage.copyFrom(bufImage);

Because it I used Java2DFrameConverter

**Comment by saudet** [comment]
A `FrameConverter` isn't meant to be used that way... Whatever it returns may become invalid as soon as it is garbage collected. If you wish to keep the data from the returned `IplImage` object, either make a clone of it with `IplImage.clone()`, or keep a reference to the `FrameConverter`. I guess I should update the documentation accordingly. Thanks for reporting this issue!

**Comment by saudet** [comment]
Clarified semantics are now part of the docs online:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FrameConverter.html
Thanks for reporting!
