### ISSUE TITLE
[opencv] RuntimeException Native Method on macos

### ISSUE THREAD

**Issue by upccup** [bytedeco/javacv#1503]
hi this is a confuse question when i call the imshow func throw a RuntimeException. please help

this is my code

```java
    public void detect() {
        Loader.load(opencv_core.class);
        Loader.load(opencv_highgui.class);
        String imgPath = "/test.jpg";
        Mat src = imread(imgPath);
        Mat blurred = gaussianBlur(src);
        Mat canny = canny(blurred);
        MatVector contours = new MatVector();
       findContours(canny, contours, new Mat(), RETR_EXTERNAL, CHAIN_APPROX_SIMPLE);

       double cx;
       for(int i =0; i< contours.size(); i++) {
           Mat contour = contours.get(i);
           Moments m = moments(contour);
           if (m.m00() == 0) {
               cx = 0;
           } else {
               cx = m.m10() / m.m00();
           }

           if (cx < sliderLen) {
               continue;
           }

           double area = contourArea(contour);
           double len = opencv_imgproc.arcLength(contour, true);

           double minArea = minArea(sliderLen), maxArea = maxArea(sliderLen);
           double minLen = minLen(sliderLen), maxLen = maxLen(sliderLen);

           if ((minArea < area && area < maxArea) && (minLen < len && len < maxLen)) {
               Rect rect = boundingRect(contour);
               log.info("rect: {}", Rectangle.from(rect));
               rectangle(src, rect, new Scalar(255));
               imshow("res", src);
               return;
           }
       }
       return;
    }

```

and this is exception
![image](https://user-images.githubusercontent.com/13341880/92547220-ff3dc880-f286-11ea-8ccd-93665e952fa1.png)

my pom.xml is 
```xml
      <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>javacv-platform</artifactId>
        <version>1.5.3</version>
      </dependency>
```

system  is macos 10.15.5 (19F101)  with java11

**Comment by saudet** [comment]
That looks like an exception thrown from OpenCV. You're most likely using its API incorrectly.

**Comment by upccup** [comment]
> That looks like an exception thrown from OpenCV. You're most likely using its API incorrectly.

thx for reply. is there has some way to find out the correctly way

**Comment by saudet** [comment]
@wmeddie Did you ever get `imshow()` to work with the JDK?

**Comment by saudet** [comment]
FYI, it looks like the highgui module is not supported with Java on Mac: https://github.com/opencv/opencv/issues/10437

Since we're in Java though, there's no reason to want to use highgui anyway. Just use Swing or JavaFX instead.

/cc @johanvos

**Comment by upccup** [comment]
> FYI, it looks like the highgui module is not supported with Java on Mac: [opencv/opencv#10437](https://github.com/opencv/opencv/issues/10437)
> 
> Since we're in Java though, there's no reason to want to use highgui anyway. Just use Swing or JavaFX instead.
> 

got it and thx again.

**Comment by saudet** [comment]
Duplicate of https://github.com/opencv/opencv/issues/10437
