### ISSUE TITLE
does this version of ffmpeg support vaapi?

### ISSUE THREAD

**Issue by chenjeff622** [bytedeco/javacv#1504]
does this version of ffmpeg support vaapi?

**Comment by saudet** [comment]
Yes, if you build from source, but not yet for the default binaries.

**Comment by saudet** [comment]
Duplicate of #1188

**Comment by saudet** [comment]
FFmpeg is now getting built with CentOS 7, so this gets enabled by default.
Please give it a try with the snapshots: http://bytedeco.org/builds/
