### ISSUE TITLE
My hls time is error,EXTINF not equals hls file's time .

### ISSUE THREAD

**Issue by flowclouds** [bytedeco/javacv#1505]
with my code like this!
![image](https://user-images.githubusercontent.com/40859714/92581502-5ad97780-f2c2-11ea-8dfb-c8dc7238cf21.png)

the result 
![image](https://user-images.githubusercontent.com/40859714/92582345-6f6a3f80-f2c3-11ea-8dc4-8a58fa9f7f7a.png)

**Comment by saudet** [comment]
You'll need to call `recorder.stop()` at the end.
