### ISSUE TITLE
Can't tell which examples are using GPU

### ISSUE THREAD

**Issue by schungzhihuai** [bytedeco/javacv#1508]
Hi, I'm new to this and I have looked through all the examples but am not able to find an example that uses CUDA/GPU. I am trying to build a java application that uses YOLOv3 and CUDA to do object detection.  It would be help if someone could point me to the right sample to on how to implement CUDA/GPU into a dnn :)

**Comment by saudet** [comment]
Most of them will run on GPU automatically. Just make sure to have the
dependencies for GPUs in your class path, for example, like this:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#the-pomxml-build-file

**Comment by schungzhihuai** [comment]
Thank you for your reply! I have currently installed the following libraries manually:

cuda-platform-redist-11.0-8.0-1.5.4.jar
ffmpeg.jar
ffmpeg-windows-x86_64.jar
javaccp.jar
javaccp-1.5.4.jar
javaccp-platform.1.5.4.jar
javaccp-windows-x84_64.jar
javacv.jar
javacv-1.5.4.jar
javacv-platform-1.5.4.jar
mkl-platform-redist-2020.3-1.5.4.jar
numpy-platform-1.19.1-1.5.4.jar
openblas-platform-0.3.10-1.5.4.jar
opencv-4.4.0-1.5.4.jar
opencv-440.jar
opencv-platform-4.4.0-1.5.4.jar
opencv-platform-gpu-4.4.0-1.5.4.jar

I have tried to run the DeepLearningFaceDetection.java from one of the samples and have met an error at line 40:

private static final OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();

Due to company policy i am not able to copy the full error stack trace.
The main error comes from:

Exception in thread "main" java.lang.ExceptionInitializeError
at samples.DeepLearningFaceDetection.<clinit>(DeepLearningFaceDetection.java:40)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
....
....
(I will skip to the last 4 error logs)
at org.bytedeco.javacpp.Loader.checkPlatform(Loader.java:987)
at org.bytedeco.javacpp.Loader.load(Loader.java:1161)
at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
at org.bytedeco.javacv.OpenCVFrameConverter.<clinit> (OpenCVFrameConverter.java:43)
... 1 more

**Comment by schungzhihuai** [comment]
Hi I've installed all the needed presets and the issue has been resolved! No need to look into this. Thank you for the help thus far!

**Comment by saudet** [comment]
That error usually means that some dependencies are missing, yes. It's recommended to use a build tool like Maven instead of trying to do it manually. In any case, happy to hear that it's working well!
