### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by sieme97** [bytedeco/javacv#1510]
Hi, I came across JavaCV api just today. I have the following questions.
1. OpenCv official site also have Java documentation, so which one is the better option JavaCv or Opencv official Java api?
2. I am interested in android development. Can I use all the features of JavaCv on android?
3. Does JavaCv provides GPU support?

**Comment by saudet** [comment]
Please let me know if you have any questions after reading the FAQ: http://bytedeco.org/faq/

**Comment by sieme97** [comment]
Thank you for your reply. Can you comment on last question? I looked into JavaCV api but could not find a way to use gpu on android.

**Comment by saudet** [comment]
You'll need a device that supports OpenCL to use its GPU with OpenCV. See issue #1148 for more information about that.

**Comment by saudet** [comment]
Duplicate of #1148

**Comment by kshitijgarg2609** [comment]
How to include .so jar files in android studio? I have even tried to extract in jniLibs folder but I couldn't open camera.
