### ISSUE TITLE
Speed comparison between Javacv and official opencv java api

### ISSUE THREAD

**Issue by sieme97** [bytedeco/javacv#1511]
I ran some code with javacv and opencv java official api. Javacv run much slower than official api. Why is it so?

**Comment by sieme97** [comment]
Javacv
 Mat img1=opencv_imgcodecs.imread(img1_name);
 Mat img2=opencv_imgcodecs.imread(img2_name);
Opencv
  Mat img=Imgcodecs.imread(img1_name);
  Mat depth=Imgcodecs.imread(img2_name);
The execution time for both the codes is much different (36ms vs 1593ms).

**Comment by saudet** [comment]
You're counting initializing time. Use this to perform proper benchmarks: https://openjdk.java.net/projects/code-tools/jmh/
