### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/native-image/android-x86_64/jnijavacpp/jni-config.json'.

### ISSUE THREAD

**Issue by jasonakon** [bytedeco/javacv#1514]
I been have this issue since trying to import the javacv library into my android project.

(**First Approach**):
- Directly add <compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.4'> into build.gradle dependencies
- Import all the necessary libraries into application activity
- Build Error with:
`More than one file was found with OS independent path 'META-INF/native-image/android-x86_64/jnijavacpp/jni-config.json'.`

(**Second Approach**):
- Look up to https://github.com/bytedeco/javacv/issues/353#issuecomment-461108705
- Include the dependencies this way <implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.4'>
- Oh It works !, Error is gone.
- However, meet this error when launching application : https://github.com/bytedeco/javacv/issues/1301#issue-496678357

(**Third Approach**):
- Follow up with second approach, the author asked to add some implementations in the dependencies as mentioned at https://github.com/bytedeco/javacv/issues/1301#issuecomment-533838326
- Error pops out with the same as First Approach:
`More than one file was found with OS independent path 'META-INF/native-image/android-x86_64/jnijavacpp/jni-config.json'.`

Very Lost, i wish someone could help me on these.

**Comment by saudet** [comment]
Those files are not necessary for Android, you can exclude them.

**Comment by saudet** [comment]
Duplicate of #353

**Comment by jasonakon** [comment]
I understand that, i actually follow your duplicated post. However, i'm keep getting the error with : couldn't find "libjniavutil.so"

Please give me a hint, i have been trying to search around for solution with downloading the snapshot still not working

**Comment by saudet** [comment]
That means you don't have "libjniavutil.so" in your APK! You'll need that file to be there, for example, like this:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies#including-binaries-only-for-mobile-platforms

**Comment by namhkoh** [comment]
Hello, I am currently trying to extract frames from a video taken on an android device. Encountered the same issue as opened above. I've followed the steps suggested but unable to proceed.

**Comment by ProfGram** [comment]
> Hello, I am currently trying to extract frames from a video taken on an android device. Encountered the same issue as opened above. I've followed the steps suggested but unable to proceed.

Did you find any solution?

**Comment by saudet** [comment]
We can exclude those files this way:
```
android {
    packagingOptions {
        exclude 'META-INF/native-image/**'
    }
}
```
https://github.com/bytedeco/sample-projects/blob/master/JavaCV-android-example/app/build.gradle
