### ISSUE TITLE
Where to find the neat opencv java api,or javadocs

### ISSUE THREAD

**Issue by LJWxyz** [bytedeco/javacv#1517]
there's javacv and opencv jars that's in the nicely packaged zip.
I have the github website,can refer sample i also have source code can read it myself.
But i feel like a very sweet thing that generally contains all api is not here...
(sob,sob...)

**Comment by saudet** [comment]
The API documentation is all here: http://bytedeco.org/javacpp-presets/opencv/apidocs/

**Comment by LJWxyz** [comment]
Thank you,that is the full doc right?If so what is the legit way to get a copy of that?
Can you do a pr on the readme maybe?
That way no one will exprience what I had experience ever again.
Or maybe suggest putting the full docs near those future releases.

**Comment by LJWxyz** [comment]
Oh no,I found out the one you gave me still is not the full.
If I am not wrong the full consist of
Javacv-
org_opencv stuff
org_bytedeco_opencv
So I suggest create a small area explaining this all things.or maybe link to official webpage?

**Comment by saudet** [comment]
The links are all already listed here: http://bytedeco.org/
