### ISSUE TITLE
No effect on imgcodec.imread

### ISSUE THREAD

**Issue by LJWxyz** [bytedeco/javacv#1518]
part of my code
___
System.out.println("hello");
		org.opencv.core.Mat amat=org.opencv.imgcodecs.Imgcodecs.imread("Chrysanthemum.jpg");
		System.out.println(amat.toString()+"hey");
_______
console out 
hello
__________
did it read the image i have no idea. I put the code in a try catch statement no exception in console too...

Did i miss something?

**Comment by saudet** [comment]
When using the official Java API, make sure you've called `Loader.load(opencv_java.class)` as documented here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation
