### ISSUE TITLE
How to grab the RGB frame instead the gray one?

### ISSUE THREAD

**Issue by deddygnwn14** [bytedeco/javacv#152]
In FacePreview.java https://code.google.com/p/javacv/source/browse/samples/FacePreview.java
I don't understand at this part : 
protected void processImage(byte[] data, int width, int height) {
        // First, downsample our image and convert it into a grayscale IplImage
        int f = SUBSAMPLING_FACTOR;
        if (grayImage == null || grayImage.width() != width/f || grayImage.height() != height/f) {
            grayImage = IplImage.create(width/f, height/f, IPL_DEPTH_8U, 1);
        }
        int imageWidth  = grayImage.width();
        int imageHeight = grayImage.height();
        int dataStride = f*width;
        int imageStride = grayImage.widthStep();
        ByteBuffer imageBuffer = grayImage.getByteBuffer();
        for (int y = 0; y < imageHeight; y++) {
            int dataLine = y*dataStride;
            int imageLine = y*imageStride;
            for (int x = 0; x < imageWidth; x++) {
                imageBuffer.put(imageLine + x, data[dataLine + f*x]);
            }
        }

        cvClearMemStorage(storage);
        faces = cvHaarDetectObjects(grayImage, classifier, storage, 1.1, 3, CV_HAAR_DO_CANNY_PRUNING);
        postInvalidate();
    }

At this part grayImage = IplImage.create(width/f, height/f, IPL_DEPTH_8U, 1);
can I create it like this rgbImage = IplImage.create(width/f, height/f, IPL_DEPTH_32F, 3); to get an rgb image and later convert it to gray by doing cvCvtColor(rgbImage, grayImage, cv_bgr2gray); and then proceed with haar like this? faces = cvHaarDetectObjects(grayImage, classifier, storage, 1.1, 3, CV_HAAR_DO_CANNY_PRUNING);
        postInvalidate();
    }

Because I want to crop the rgbImage with ROI that created by the result of cvHaarDetectObjects using this rect: CvRect r = new CvRect(cvGetSeqElem(faces, i));
                int x = r.x(), y = r.y(), w = r.width(), h = r.height();

I tried it but it failed and nothing detected.

I'm sorry if I'm asking too much, but thank you for responding.

**Comment by saudet** [comment]
One way to get an RGB (actually BGR) image is by calling 
[AndroidFrameConverter.convert(byte[] data,int width, int height)](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/AndroidFrameConverter.html#convert-byte:A-int-int-)
along with [OpenCVFrameConverter](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.html) to get an `IplImage`.

Let me know if you have any issues with that! Thanks

**Comment by deddygnwn14** [comment]
I did it like this

protected void processImage(byte[] data, int width, int height) {
                int f = SUBSAMPLING_FACTOR;
                if (grayImage == null || grayImage.width() != width/f || grayImage.height() != height/f) {
                    grayImage = IplImage.create(width/f, height/f, IPL_DEPTH_8U, 1);
                }
                bgrFrame = IplImage.create(width/f, height/f, IPL_DEPTH_32F, 3); (already done it without create, the result is the same).
		frameCvt = new AndroidFrameConverter();
		OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
		bgrFrame = converter.convertToIplImage(frameCvt.convert(data, width/f, height/f));


But the apps goes force close. Did I do it wrong?

this the logcat
05-25 01:52:03.045: E/cv::error()(24512): OpenCV Error: Assertion failed (src.depth() == dst.depth() && src.size == dst.size) in void cvCopy(void const*, void*, void const*), file /home/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/android-arm/opencv-2.4.11/modules/core/src/copy.cpp, line 556
05-25 01:52:03.050: D/AndroidRuntime(24512): Shutting down VM
05-25 01:52:03.050: W/dalvikvm(24512): threadid=1: thread exiting with uncaught exception (group=0x41f35700)
05-25 01:52:03.060: E/AndroidRuntime(24512): FATAL EXCEPTION: main
05-25 01:52:03.060: E/AndroidRuntime(24512): java.lang.RuntimeException: /home/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/android-arm/opencv-2.4.11/modules/core/src/copy.cpp:556: error: (-215) src.depth() == dst.depth() && src.size == dst.size in function void cvCopy(void const*, void*, void const*)

**Comment by deddygnwn14** [comment]
protected void processImage(byte[] data, int width, int height) {
int f = SUBSAMPLING_FACTOR;
if (grayImage == null || grayImage.width() != width/f || grayImage.height() != height/f) {
grayImage = IplImage.create(width/f, height/f, IPL_DEPTH_8U, 1);
}
		bgrFrame = IplImage.create(width/f, height/f, IPL_DEPTH_32F, 3);
		frameCvt = new AndroidFrameConverter();
		OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
		bgrFrame = converter.convertToIplImage(frameCvt.convert(dataGambar, width/f, height/f,));

But the result is the image that contained by bgrFrame is like this

![croppedimage_20150525_104526 1](https://cloud.githubusercontent.com/assets/12512366/7791593/03f6b332-02cd-11e5-9be6-422c1071595b.png)
![croppedimage_20150525_104530 1](https://cloud.githubusercontent.com/assets/12512366/7791600/1c967db4-02cd-11e5-8109-8ad0162df360.png)

Did I do it wrong?

**Comment by saudet** [comment]
Call `AndroidFrameConverter.convert()` this way: `convert(data, width, height)`.
