### ISSUE TITLE
FAILED:fs.is_open(). Can not open "goturn.prototext" in function 'cv::dnn::ReadProtoFromTxetFile'

### ISSUE THREAD

**Issue by schungzhihuai** [bytedeco/javacv#1528]
Hi I have used maven to download all the required dependencies, however when i try to do:

tracker.init(frame,rect);

it throws an error:
FAILED:fs.is_open(). Can not open "goturn.prototext" in function 'cv::dnn::ReadProtoFromTxetFile'

I have taken a look at the C++ equivalent of the [issue](https://answers.opencv.org/question/170633/failed-to-open-goturnprototxt/) but am not able to find a solution for javacv.

Could I still be missing dependencies?

**Comment by saudet** [comment]
No, it just sounds like it's not able to open that file. You'll need to make sure the file is accessible in the right place.

**Comment by schungzhihuai** [comment]
You're right, I realise the GOTURN tracker model was not included in the library. It requires us to download and place the files in the same folder as the executable. Thank you!
