### ISSUE TITLE
How to serialize objects of type Mat and MatVector.

### ISSUE THREAD

**Issue by danieldhsd** [bytedeco/javacv#1530]
I need to serialize objects of these types to send them to a server.

**Comment by saudet** [comment]
We can use FileStorage as shown here:
https://docs.opencv.org/master/dd/d74/tutorial_file_input_output_with_xml_yml.html
Is that satisfactory?

**Comment by danieldhsd** [comment]
I was able to solve the problem by converting from type MAT to String.

`private static String mat2String(Mat matrix)  {
	BufferedImage img = Java2DFrameUtils.toBufferedImage(matrix);
	String imgString = imgToBase64String(img, "jpg");
		
	return imgString;
}

public static String imgToBase64String(final RenderedImage img, final String formatName) {
	final ByteArrayOutputStream os = new ByteArrayOutputStream();
	try {
		ImageIO.write(img, formatName, Base64.getEncoder().wrap(os));
		return os.toString(StandardCharsets.ISO_8859_1.name());
	} catch (final IOException ioe) {
		throw new UncheckedIOException(ioe);
	}
}

public static Mat string2Mat(String serialized) {
	BufferedImage img2 = base64StringToImg(serialized);
	Mat newMat = Java2DFrameUtils.toMat(img2);

	return newMat;
}

public static BufferedImage base64StringToImg(final String base64String) {
	try {
		return ImageIO.read(new ByteArrayInputStream(Base64.getDecoder().decode(base64String)));
	} catch (final IOException ioe) {
		throw new UncheckedIOException(ioe);
	}
}
`

**Comment by danieldhsd** [comment]
I was able to solve the problem by converting from type MAT to String.
```java
private static String mat2String(Mat matrix) {
   BufferedImage img = Java2DFrameUtils.toBufferedImage(matrix);
   String imgString = imgToBase64String(img, "jpg");

   return imgString;
}

public static String imgToBase64String(final RenderedImage img, final String formatName) {
   final ByteArrayOutputStream os = new ByteArrayOutputStream();
   try {
      ImageIO.write(img, formatName, Base64.getEncoder().wrap(os));
      return os.toString(StandardCharsets.ISO_8859_1.name());
   } catch (final IOException ioe) {
      throw new UncheckedIOException(ioe);
   }
}

public static Mat string2Mat(String serialized) {
   BufferedImage img2 = base64StringToImg(serialized);
   Mat newMat = Java2DFrameUtils.toMat(img2);

   return newMat;
}

public static BufferedImage base64StringToImg(final String base64String) {
   try {
      return ImageIO.read(new ByteArrayInputStream(Base64.getDecoder().decode(base64String)));
   } catch (final IOException ioe) {
      throw new UncheckedIOException(ioe);
   }
}
```
