### ISSUE TITLE
Imread (opencv_imgcodecs.imread) - OutOfMemoryError

### ISSUE THREAD

**Issue by Alesh17** [bytedeco/javacv#1532]
Physical memory usage is too high: physicalBytes (1067M) > maxPhysicalBytes (1024M).

I try to increase heap by this way: ` android:largeHeap="true"` - but unsuccessfully.

Any advice?

**Comment by saudet** [comment]
You can try to increase the value of "org.bytedeco.javacpp.maxPhysicalBytes".

**Comment by saudet** [comment]
Duplicate of #599
