### ISSUE TITLE
if fps<1 FFmpegFrameRecorder start will stuck 

### ISSUE THREAD

**Issue by jamesh23** [bytedeco/javacv#1534]
![image](https://user-images.githubusercontent.com/37619181/97945787-87da7000-1dc3-11eb-999b-8e5c6f3ba310.png)
since num()/den() ==0 
is it a bug ? may be we should use num()*1.0d/den()?
@saudet

**Comment by saudet** [comment]
It looks like a bug, yes. Please contribute a fix!

**Comment by saudet** [comment]
Thanks for the fix in pull #1535!

**Comment by saudet** [comment]
The fix has been released with JavaCV 1.5.5! Thanks for the contribution
