### ISSUE TITLE
Processing video frame-by-frame while keeping audio by using FFmpegFrameGrabber and FFmpegFrameRecorder

### ISSUE THREAD

**Issue by Seangottarun** [bytedeco/javacv#1536]
Hi, I'm trying to process a saved video by processing each individual frame and then saving those in a modified output video. I've been able to do this by converting the `grabbedFrame` taken from `grabber.grabFrame()`, but the audio gets dropped. 

```kotlin
recorder.record(processedFrame)
```

To get around this, I tried reassigning the `processedFrame`'s image to the original `grabbedFrame` like this:

```kotlin
grabbedFrame?.image = processedFrame?.image
recorder.record(grabbedFrame, AV_PIX_FMT_RGBA)
```

![result](https://user-images.githubusercontent.com/35048935/98459377-38e85e00-2168-11eb-9eba-f29690d09d4f.png)

However, I end up getting frames with weird rows. The very top row actually has the `processedFrame` that I expected to see.

![result3](https://user-images.githubusercontent.com/35048935/98459730-80bcb480-216b-11eb-8427-fc7d71dbd86f.png)

I'm pretty new to Android and Java/Kotlin so I'm assuming this is user error rather than a bug. If possible, I was hoping to have these questions answered:
1. Why doesn't reassigning the `Frame.image` field work? From reading [Frame.java](https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/Frame.java), it seems like `Frame.image` stores image pixels for different channels, so is that what's causing the different rows?
2. What is the proper way to process video frames while keeping audio?
3. If I want to replace the `grabbedFrame` image while keeping the audio, am I supposed to convert my `processedBitmap`  to `IplImage`?

I'd really appreciate any help! Thanks!

### Details
- JavaCV Version: 1.5.4 on Android (manual installation with `*.jar` in `app/libs` and `*.so` in `app/src/main/jnilibs`)
- Bitmap is `ARGB_8888`
- Frames must be converted to bitmap to use an external function that requires bitmaps

### Other sources consulted
1. https://github.com/bytedeco/javacv/issues/482
2. https://groups.google.com/forum/#!topic/javacv/TdppyNYxeFU

### Relevant Code
```kotlin
private fun processVideo(videoFile: File) {
        val grabber = FFmpegFrameGrabber(videoFile.absolutePath)

        val bitmapConverter = AndroidFrameConverter()
        grabber.setPixelFormat(AV_PIX_FMT_RGBA)

        try {
            grabber.start()
        } catch (e: FrameGrabber.Exception) {
            e.printStackTrace()
        }
        var grabbedFrame: Frame? = null

        grabber.setFrameRate(grabber.getFrameRate())
        grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        val recorder = FFmpegFrameRecorder(
            File(context?.filesDir, "result.mp4"),
            grabber.getImageWidth(),
            grabber.getImageHeight()
        )

        recorder.setVideoCodec(grabber.getVideoCodec())
        recorder.setFormat(grabber.getFormat())
        recorder.setAudioChannels(grabber.getAudioChannels())
        recorder.setAudioCodec(grabber.getAudioCodec())
        recorder.setSampleRate(grabber.getSampleRate())
        recorder.setAudioBitrate(grabber.getAudioBitrate())
        recorder.setFrameRate(grabber.getFrameRate())
        recorder.setVideoBitrate(grabber.getVideoBitrate())
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264)

        try {
            recorder.start()
        } catch (e: FrameRecorder.Exception) {
            e.printStackTrace()
        }
        showToast("starting processing video")
        Log.d(TAG, "starting processing video")


        while (grabber.grabFrame().also { grabbedFrame = it } != null) {
            try {
                val bitmap = bitmapConverter.convert(grabbedFrame)
                if (grabbedFrame == null) {
                    Log.e(TAG, "grabbed frame null")
                }
                if (bitmap == null) {
                    Log.e(TAG, "bitmap null")
                    continue
                } else {
                    val mutableBitmap = bitmap.copy(Bitmap.Config.ARGB_8888, true)
                    val processedBitmap = processImage(mutableBitmap) 
                    val processedFrame = bitmapConverter.convert(processedBitmap)
                    grabbedFrame?.image = processedFrame?.image

                    recorder.record(grabbedFrame, AV_PIX_FMT_RGBA)
                }

            } catch (e: FrameRecorder.Exception) {
                Log.e(TAG, e.message!!)
                e.printStackTrace()
            }
        }
```

**Comment by saudet** [comment]
Audio frames are going to show up separately from video frames. Just
process them independently, don't try to process them together

**Comment by Seangottarun** [comment]
Thanks @saudet for such a fast reply! I processed the audio and video frames separately and it worked perfectly. 

```kotlin
while (grabber.grabFrame().also { grabbedFrame = it } != null) {
            try {
                if (grabbedFrame?.image != null) {
                    // This is a video Frame
                    val bitmap = bitmapConverter.convert(grabbedFrame)
                    val mutableBitmap = bitmap.copy(Bitmap.Config.ARGB_8888, true)
                    val processedBitmap = processImage(mutableBitmap)
                    val processedFrame = bitmapConverter.convert(processedBitmap)

                    recorder.record(processedFrame)
                } else {
                    // This is an audio Frame
                    recorder.record(grabbedFrame)
                }

            } catch (e: FrameRecorder.Exception) {
                Log.e(TAG, e.message!!)
                e.printStackTrace()
            }
}
```
