### ISSUE TITLE
Question/Issue : FrameGrabber$Exception: Error: Could not create camera capture.

### ISSUE THREAD

**Issue by arvind-das** [bytedeco/javacv#154]
Hi Samuel

I had a good play with JavaCV and its cool almost finished building my video recording tool with this. Now, I created a recoding jar to place it on some commodity hardware and then execute this runnable jar. Machine is running ubuntu 14.04_x64 and on 1Gig of RAM.

Problem is: until i start cheese on that machine, I will get this error 

com.rrdtech.recorder.javacv.FrameGrabber$Exception: cvCreateCameraCapture() Error: Could not create camera capture.
	at com.rrdtech.recorder.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:177)
	at com.rrdtech.recorder.javacv.CustomFFmpegFileSystemRecorder.startRecord(CustomFFmpegFileSystemRecorder.java:46)
	at com.rrdtech.api.reordingapp.App.main(App.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

But Once cheese is started and closed, my jar will start working fine. Is there anything that is triggered that recording starts happening. I am making my head on the wall for this reason . Can you help me out ?

**Comment by saudet** [comment]
FFmpeg usually works better than OpenCV to grab from a webcam under Linux. Something like this should work:
```java
FrameGrabber grabber = new FFmpegFrameGrabber("/dev/video0"); // for the first camera
grabber.setFormat("video4linux2");
grabber.start();
```
Let me know if you're still having issues though! Thanks

**Comment by arvind-das** [comment]
Sorry for late reply, Actually Still facing issues. Audio is not recorded now. One strange thing I came up with is, the machine I am recording on , does not list capturing devices with arecord -l until I start cheese (ubuntu recording app) and close it, then it lists my attached usb camera. don't know why is that happening.

**Comment by saudet** [comment]
Doesn't sound like an issue related to JavaCV...

**Comment by arvind-das** [comment]
exactly, so following askubuntu and other sites

**Comment by MuthuEphron** [comment]
Please give the sample code for supporting live streaming mp4 videos using javaCV. I use  code from the below url

http://www.walking-productions.com/notslop/2013/01/16/android-live-streaming-courtesy-of-javacv-and-ffmpeg/

**Comment by saudet** [comment]
@MuthuEphron Try out this sample:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by MuthuEphron** [comment]
i don't need to store images on sdcard.. I gave rtmp url to record the video format mp4 videos. please give any suggestion. i use javaCV 0.8 jar . but   i got fatal signal  8 error.  thanks for help
  .

**Comment by saudet** [comment]
@MuthuEphron Try again with JavaCV 1.1

**Comment by MuthuEphron** [comment]
@saudet  please send the download link of Java CV 1.1.

**Comment by MuthuEphron** [comment]
i taken from source code below url
 https://github.com/vanevery/JavaCV_0.3_stream_test

can java cv1.1 support  this code to record mp4 video files
Thanks for help

**Comment by MuthuEphron** [comment]
i take  the source code from below url;

 https://github.com/vanevery/JavaCV_0.3_stream_test

but the source code does not support to record mp4  format.
 
please any one help me.

 Thanks for everyone help

**Comment by MuthuEphron** [comment]
I used java cv 1.1 from this below url( for Source code)

https://github.com/vanevery/JavaCV_0.3_stream_test

but i got  compile time error in two lines

recorder.record(ShortBuffer.wrap(audioData,0,bufferReadResult));

  recorder.record(yuvIplimage);

i declared Iplimage  yuvIplimage;

**Comment by MuthuEphron** [comment]
@saudet  You have to record frame are convert to video.mp4 files. i need rtmp url live streaming videos in mp4 format. but i work in java CV 1.1 . the mp4 and flv video is working. and it can't display(any video format)  in wowza streaming  engine software. thamks

**Comment by saudet** [comment]
@MuthuEphron If you want to grab frames, use FFmpegFrameGrabber. Anyway, this has nothing to do with this issue, so please post your questions on the mailing list. Thanks

**Comment by MuthuEphron** [comment]
@saudet  i record  the video in format of mp4 and flv. but not streaming in wowza media streaming engine software

**Comment by kaleemTorres** [comment]
Hi @MuthuEphron did you get any solution for this issue. I am facing the same issue.Unable to stream video
