### ISSUE TITLE
Why cvPutText is not working?? giving me this strange error ?

### ISSUE THREAD

**Issue by nikkisingh111333** [bytedeco/javacv#1546]
hey i m working on a facial recognization system simple one and i want to put text string as you guess it right the name of a person .almost done everything but cant put it on image frame.
heres my code snippet from opencv_imgproc;
`	opencv_imgproc.rectangle(image,face, new Scalar(255.0,130.0,140.0,0.0));
	CvArr cvmat=new CvArr(image);
	opencv_imgproc.cvPutText(cvmat, pred_name,new CvPoint(face), new CvFont(opencv_imgproc.FONT_HERSHEY_SIMPLEX),new CvScalar(new Scalar(220.0,120.0,130.0,0.0)));
	`
and i m getting this long error seems like a crash 
`Failed to write core dump. Minidumps are not enabled by default on client versions of Windows#`
there was more but i just copied shortest one .
what should i do .? and hows why we are using CvArr instead of Mat  and CvScalar instead of scalar.?

**Comment by saudet** [comment]
It looks like you're mixing the C API with the C++ API. That probably won't work. Try to use only the C++ API.
If you'd like to use the deprecated C API instead, here's an example of cvPutText() that works:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/MarkerDetector.java#L318

**Comment by nikkisingh111333** [comment]
But i want simple stuff how can i put text into image ..using bytedeco Mat
instance version...?

**Comment by saudet** [comment]
Like I said, use putText() instead.

**Comment by nikkisingh111333** [comment]
okk thanks a lot i worked like charm....
