### ISSUE TITLE
VideoCapture read Method will stuck

### ISSUE THREAD

**Issue by abuech2s** [bytedeco/javacv#1547]
Dear guys,

While using the VideoCapture class to load a given mp4 file and use a loop to iterate over frames, the read(frame) method will stuck (without a visible warning / exception). Are there any known issues about that?

The given filename is found; camera.isOpened() returns true. By the way, is there a more simplier way to count the number of given frames of a mp4 file?

I am using V1.5.4, JDK11, Mvn 3.6.3
PS: This effect will happen if i choose "CAP_ANY" or "CAP_MSMF". In all other cases, that camera object will not open.

Thanks a lot
Alex

A minimal example:

    VideoCapture camera = new VideoCapture();
    assertTrue(camera.open(filename, CAP_ANY));
    assertTrue(camera.isOpened());
			
    Mat frame = new Mat();
			
    int cnt = 0;
    while (camera.read(frame)) {
        cnt++;
    }
    System.out.println("Number of frames: " + cnt);

**Comment by saudet** [comment]
Please try to use FFmpegFrameGrabber instead.

**Comment by abuech2s** [comment]
I am not sure, if i use this Grabber correctly, but based on this approach, reading in of all my videos fail:
In all cases frame.image is null. Actually based on the VideoCapture approach, i could reach a better result, because i was able to read in more files.

    FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(filename);
    OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();
    grabber.start();
    Frame frame;
    while ((frame = grabber.grabFrame(false, true, true, false)) != null) {
        if (frame.image == null) {
            System.out.println("IS NULL: " + frame.image);
        }
        Mat mat = converterToMat.convert(frame);
    }
    grabber.stop();
    grabber.close();

**Comment by abuech2s** [comment]
Ok, after a lot of luck, i found the fifth parameter. With this parameter it seems it works.

I have to replace it to: grabber.grabFrame(false, true, true, false, false) //add last "false"

I think the ticket can be closed

**Comment by saudet** [comment]
If you're not interested in audio frames, we can all grabImage(), which is the equivalent of the above, yes.
