### ISSUE TITLE
AndroidFrameConverter and OpenCVFrameConverter

### ISSUE THREAD

**Issue by deddygnwn14** [bytedeco/javacv#155]
Based on my last issue https://github.com/bytedeco/javacv/issues/152#issuecomment-105117742
I learn how to use them from another post and I did it like this

protected void processImage(byte[] data, int width, int height) {
int f = SUBSAMPLING_FACTOR;
if (grayImage == null || grayImage.width() != width/f || grayImage.height() != height/f) {
grayImage = IplImage.create(width/f, height/f, IPL_DEPTH_8U, 1);
}
		bgrFrame = IplImage.create(width/f, height/f, IPL_DEPTH_32F, 3);
		frameCvt = new AndroidFrameConverter();
		OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
		bgrFrame = converter.convertToIplImage(frameCvt.convert(dataGambar, width/f, height/f,));

But the result is the image that contained by bgrFrame is like this

![croppedimage_20150525_104526 1](https://cloud.githubusercontent.com/assets/12512366/7791593/03f6b332-02cd-11e5-9be6-422c1071595b.png)
![croppedimage_20150525_104530 1](https://cloud.githubusercontent.com/assets/12512366/7791600/1c967db4-02cd-11e5-8109-8ad0162df360.png)

Did I do it wrong?

**Comment by saudet** [comment]
Call `AndroidFrameConverter.convert()` this way: `convert(data, width, height)`

**Comment by deddygnwn14** [comment]
It works! thank you for your help :D 
But it become slow because the image is too large. But thanks :+1:

**Comment by saudet** [comment]
We can use OpenCV for faster conversion, something like shown in #156.
