### ISSUE TITLE
Exception Access Violation while showing Mat object

### ISSUE THREAD

**Issue by abuech2s** [bytedeco/javacv#1550]
Hi, 

I have received an "exception access violation" at OpenJDK11 while showing a Mat Object

I have the following code 

	public void findStaticSceneTest() throws Exception {
		String filename = "C:\\test\\100.mp4";
		List<Mat> matList = Mp4FileLoader.loadMP4File(filename);
		Mat staticScene = matList.get((int)(matList.size()/2));
		imshow("StaticScene", staticScene);
            waitKey(0);
        }

The Method loadMP4File uses FFmpegFrameGrabber and OpenCVFrameConverter.ToMat to iterate over a mp4 file and return a List<Mat>. This method in general works fine: The matList contains finally 228 Mat objects.

Eclipse / JDK shows the following error after calling imshow():

 A fatal error has been detected by the Java Runtime Environment:

    EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff147cd759, pid=8464, tid=14368
     JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)# Java VM: OpenJDK 64-Bit Server M AdoptOpenJDK (11.0.8+10, mixed mode, tiered, compressed oops, g1 gc, windows-md64)
    Problematic frame:
    C  [KERNELBASE.dll+0x2d759]
    No core dump will be written. Minidumps are not enabled by default on client versions of Windows
    An error report file with more information is saved as:
    C:\Users\xxxxxxxxxx\hs_err_pid8464.log
    If you would like to submit a bug report, please visit: https://github.com/AdoptOpenJDK/openjdk-support/issues
    The crash happened outside the Java Virtual Machine in native code. See problematic frame for where to report the bug.

The error file is attached.
[hs_err_pid8464.log](https://github.com/bytedeco/javacv/files/5691092/hs_err_pid8464.log)

UPDATE:

I have notived, that while iterating over the mp4 file with grabImage() it is possible to show each image with

    imshow("", mat);
    waitKey(0);

It makes me wonder, why - after returning the list of Mats - it is not possible to call imshow() on a single Mat.

Thanks for any advice.
Alex

**Comment by abuech2s** [comment]
Happens as well with Adopt OpenJDK 11.0.9.1+1

**Comment by saudet** [comment]
You'll need to make a copy of those images.
