### ISSUE TITLE
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open audio codec.

### ISSUE THREAD

**Issue by JSJBDEV** [bytedeco/javacv#1551]
I am using JavaCV to extract the sound from a video my code (found somewhere on the internet) is as follows:
`public void extractAudioFromVedio(String videoPath)
    {

        //audio path
        String extractAudio=FabricLoader.getInstance().getConfigDirectory().getPath()+"/vaudio.ogg";
        try{
            //check the audio file exist or not ,remove it if exist
            File extractAudioFile = new File(extractAudio);
            if (extractAudioFile.exists()) {
                extractAudioFile.delete();
            }
            //audio recorder，extractAudio:audio path，2:channels
            FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(extractAudio, 2);
            recorder.setAudioCodec(avcodec.AV_CODEC_ID_OPUS);
            recorder.setAudioOption("crf", "0");
            recorder.setAudioQuality(0);
            //bit rate
            recorder.setAudioBitrate(192000);
            //sample rate
            recorder.setSampleRate(44100);
            recorder.setAudioChannels(2);
            //encoder

            //start
            recorder.start();
            //load video
            FFmpegFrameGrabber grabber = FFmpegFrameGrabber.createDefault(videoPath);
            grabber.start();
            Frame f=null;
            //get audio sample and record it
            while ((f = grabber.grabSamples()) != null) {
                recorder.record(f);
            }
            // stop to save
            grabber.stop();
            recorder.close();
            //output audio path

        } catch (Exception e) {
           e.printStackTrace();
        }
    }`
I have tried with AV_CODEC_ID_MP3 and AV_CODEC_ID_OPUS (for .mp3 and .ogg) but I always get this error (in the title), am I doing something wrong or am i missing something?

running on a win10 machine, running java 1.8.0.102 and also tested with java 12..0.2

**Comment by saudet** [comment]
Please also provide the error message that is displayed on the console. If you don't see any error message, make sure that FFmpegLogCallback.set() has been call.

**Comment by JSJBDEV** [comment]
[14:06:37] [main/INFO] (Minecraft) [STDERR]: org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open audio codec.
[14:06:37] [main/INFO] (Minecraft) [STDERR]: 	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:819)
[14:06:37] [main/INFO] (Minecraft) [STDERR]: 	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:406)


do you mean this one?

**Comment by saudet** [comment]
No. Did you call FFmpegLogCallback.set()? If not, please call FFmpegLogCallback.set(). I'll say it again just to make sure: Call FFmpegLogCallback.set(). If you don't call FFmpegLogCallback.set() you might not see the error messages on the console.

**Comment by JSJBDEV** [comment]
oh I see
 Error: [libopus @ 000001ee0bd20100] Specified sample rate 44100 is not supported

**Comment by JSJBDEV** [comment]
well that makes more sense, I thought I was missing something, I can try with mp3 as well but I think that pretty much clears that up, can I find these samplerates by just googling the codec or is there ones specific to javacv i should use?

**Comment by JSJBDEV** [comment]
so I tried removing the sample rate but the default is 44100, I then tried 256000 (32kb/s) and it still said it wasnt supported?

**Comment by saudet** [comment]
256000 is not a supported sample rate for sure.

It doesn't look like it's documented anywhere, but the supported sample rates are here in the source code: 
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libopusenc.c#L581

**Comment by JSJBDEV** [comment]
and yup, that solves my problem, thank you for your time!
