### ISSUE TITLE
 Can I use FFmpegFrameGrabber to read pure pcm data

### ISSUE THREAD

**Issue by 281613520** [bytedeco/javacv#1555]
I encountered a scenario of directly processing pcm pure data file during use. Does the software support such use?

**Comment by saudet** [comment]
Sure, the samples contained in Frame objects are PCM encoded.

**Comment by 281613520** [comment]
Okay, I have another question now. I found that the length of time to obtain the aac format file is inaccurate. How can I modify this?

**Comment by saudet** [comment]
That's probably the file that is corrupted. Capture all the frames to compute the length.
