### ISSUE TITLE
Latest and Greatest with Maven

### ISSUE THREAD

**Issue by salamanders** [bytedeco/javacv#1558]
First of all: Great library!  I'd never be able to do the time-lapse videos I'm doing without it, thank you!

I'm on a version of the library that **works** in maven (pom.xml), but is getting old.  I'd like to modernize before anything breaks (and for the hoped-for speed boost!) but every time I try to replace any of the versions with more recent releases, everything breaks.

**Does anyone have a maven/pom.xml that allows for cross-platform mp4 read/write in java 8+, using the latest releases?**

The most recent versions that I've got working:
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.4.3</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>opencv</artifactId>
            <version>3.4.3-1.4.3</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>4.0.2-1.4.3</version>
        </dependency>
```

**Comment by saudet** [comment]
The package names changed. Please read this: http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/

**Comment by saudet** [comment]
As mentioned in the README.md file, this single dependency works fine:
```xml
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.4</version>
        </dependency>
```
