### ISSUE TITLE
no opencv_blass not resolving ?

### ISSUE THREAD

**Issue by nikkisingh111333** [bytedeco/javacv#1560]
hey i m stucking from past 3 days in wierd situation. when i was using java 8 everything was great but when i switch to java 13 i m getting this error on :
`Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [C:\opencv\build\java\x64]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniSmileML in java.library.path: [C:\opencv\build\java\x64]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:806)
	at java.base/java.lang.System.loadLibrary(System.java:1909)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at Gamoneynew.Gamoneywelcomenew.SmileML.main(SmileML.java:76)`
when try to add javacv-platform dependency i got this always:
`Error: Could not find or load main class singh\workspace-sts-3.9.8.RELEASE\Gamoney-welcome-new\target\classes;C:\opencv\build\java\opencv-420.jar;C:\Users\Nikki
Caused by: java.lang.ClassNotFoundException: singh\workspace-sts-3/9/8/RELEASE\Gamoney-welcome-new\target\classes;C:\opencv\build\java\opencv-420/jar;C:\Users\Nikki
`
heres my pom.xml:
`     <dependency>
          <groupId>org.bytedeco</groupId>
          <artifactId>javacpp-platform</artifactId>
          <version>1.5.4</version>
       </dependency>
     <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>opencv-platform</artifactId>
      <version>4.4.0-1.5.4</version>
    </dependency> 
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>flandmark-platform</artifactId>
      <version>1.07-1.5.4</version>
    </dependency> 
   <dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.5.4</version>
</dependency>
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>openblas</artifactId>
    <version>0.2.20-1.4</version>
</dependency> 
 <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>openblas-platform</artifactId>
      <version>0.3.10-1.5.4</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>arpack-ng-platform</artifactId>
      <version>3.7.0-1.5.4</version>
    </dependency> 
`
what am i missing too many dependency confusing. i ve also followed reduced number of dependency section but not helping .
when i add all dependency i got classnotfound and when remove all dependency i got jniopencvnot present error what should i do ?

**Comment by saudet** [comment]
What about Java 11? Does it fail in the same way? In any case, binaries for OpenCV 4.2.0 won't work with presets for OpenCV 4.4.0, so it's normal that it fails. Please don't try to use binaries for OpenCV 4.2.0 with presets for OpenCV 4.4.0.

**Comment by nikkisingh111333** [comment]
so what should i do what is the correct set of dependencies for java 13..in
java 11 still failing .please suggest me ?

**Comment by saudet** [comment]
Use javacv-platform and nothing else, and that will work fine.

**Comment by nikkisingh111333** [comment]
whenever i add 'javacv-platform' dependency i got ClassNotFoundException
always and my whole project get corrupted with just one dependency .
'Error: Could not find or load main class
singh\workspace-sts-3.9.8.RELEASE\Gamoney-welcome-new\target\classes,C:\Users\Nikki
Caused by: java.lang.ClassNotFoundException:
singh\workspace-sts-3/9/8/RELEASE\Gamoney-welcome-new\target\classes;C:\Users\Nikki
' what should i do ?

**Comment by saudet** [comment]
That doesn't look related to JavaCV or JavaCPP...

**Comment by nikkisingh111333** [comment]
so what should i do i can't go back to java 8 coz i ve deleted all jdk jre
8 and currently running java 13 how can i fix this i have rebuild project
dozen times and updated still giving me error..
