### ISSUE TITLE
Can you provide an example of using the method "get_format" on the class AVCodecContext

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1566]
I get the value through the method "pix_fmt" on the class AVCodecHWConfig , but I don't know how to use the get_format method on the class AVCodecContext.

**Comment by saudet** [comment]
There's a `AVCodecContext.get_format` value, but that's a callback function. What would you like to know?

**Comment by 4714407** [comment]
I want to know how to set the callback function and how to pass the callback method implemented by Java

**Comment by saudet** [comment]
Override the `AVCodecContext.Get_format_AVCodecContext_IntPointer.call()` method, and pass an instance of that.

**Comment by 4714407** [comment]
The following code causes the JVM to crash with error: error getting method id of Java / Lang / runtimeException / < init >
video_c.get_format(new AVCodecContext.Get_format_AVCodecContext_IntPointer(){
                    @Override
                    public int call(AVCodecContext s, IntPointer fmt) {
                        return AV_PIX_FMT_NONE;
                    }
                });
Can you help me see what's wrong?

**Comment by saudet** [comment]
We need to keep the instance in a field to make sure it does not get garbage collected:
https://github.com/bytedeco/javacpp#creating-callback-functions

**Comment by 4714407** [comment]
Thank you. The callback is working properly. I see the callback logic in the sample code of [ffmpeg](https://ffmpeg.org/doxygen/4.1/hw__decode_8c_source.html)
`const enum AVPixelFormat *p;`
`  for (p = pix_fmts; *p != -1; p++) {`
    `if (*p == hw_pix_fmt)`
    `            return *p;`
  `     }`
    `fprintf(stderr, "Failed to get HW surface format.\n");`
` return AV_PIX_FMT_NONE;`

How can this logic be implemented in javacv?

**Comment by saudet** [comment]
What do you mean? Pretty much the same way...

**Comment by 4714407** [comment]
I don't quite understand the logic of this callback. I enabled hwaccel dxva2, and the AVPixelFormat supported is AV_PIX_FMT_DXVA2_VLD, what should I write in this callback function? Direct return to AV_PIX_FMT_DXVA2_VLD?

**Comment by saudet** [comment]
This question is about DXVA2? Let's leave that for issue #1565.
