### ISSUE TITLE
Is there any way to detect whether the current system has GPU?

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1569]
Is there any way to detect whether the current system has GPU?

**Comment by saudet** [comment]
Almost no systems come without GPU these days...

**Comment by 4714407** [comment]
Many cloud servers do not have GPU. Is there no way to detect them?

**Comment by saudet** [comment]
If you're talking about whether the display is available or not, then this method is probably going to return that:
https://docs.oracle.com/javase/7/docs/api/java/awt/GraphicsEnvironment.html#isHeadless()
