### ISSUE TITLE
Why is the result of using `FFmpegFrameFilter` different from that of ffmpeg command line? 

### ISSUE THREAD

**Issue by 8613510** [bytedeco/javacv#1570]
Hi @saudet.
I encountered a little problem when using `FFmpegFrameFilter`.
Why is the result of using `FFmpegFrameFilter` different from that of ffmpeg command line? 
Are there some steps missing?

ffmpeg command：

```shell
 .\ffmpeg.exe -i .\1.mp4 -i .\1.mp4  -filter_complex "[0:v]pad=iw*2:ih[a];[a][1:v]overlay=w" out.mp4
```

JavaCode：

```java
	public static void main(String[] args) throws IOException {
		//
		String filterStr = "[0:v]pad=iw*2:ih[a];[a][1:v]overlay=w[v]"; // NOT OK
//		String filterStr = "[0:v][1:v]hstack=inputs=2[v]"; // OK

		FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new File("1.mp4"));
		grabber.start();

		FFmpegFrameFilter filter = new FFmpegFrameFilter(filterStr, grabber.getImageWidth(), grabber.getImageHeight());
		filter.setPixelFormat(grabber.getPixelFormat());
		filter.setVideoInputs(2);
		filter.start();

		FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(new File("out.mp4"), grabber.getImageWidth(),
				grabber.getImageHeight());
		recorder.start();
		
		Frame frame, frame3;
		while ((frame = grabber.grab()) != null) {
			if (frame.image == null) {
				continue;
			}
			filter.push(0, frame);
			filter.push(1, frame);
			while ((frame3 = filter.pull()) != null) {
				if (frame3.image != null) {
					recorder.record(frame3);
				}
			}
		}
		filter.stop();
		filter.release();
		grabber.stop();
		grabber.release();
		recorder.stop();
		recorder.release();
	}
```

**Comment by saudet** [comment]
Maybe, what's the issue exactly?

**Comment by 8613510** [comment]
the result of ffmpeg command
```shell
 .\ffmpeg.exe -i .\1.mp4 -i .\1.mp4  -filter_complex "[0:v]pad=iw*2:ih[a];[a][1:v]overlay=w" out.mp4
```
![ffmpeg](https://user-images.githubusercontent.com/77626468/105038122-e3023180-5a99-11eb-9d66-a001ad2d6dbf.png)

the result of `FFmpegFrameFilter` (filter_graph : `"[0:v]pad=iw*2:ih[a];[a][1:v]overlay=w[v]"`)

![java1](https://user-images.githubusercontent.com/77626468/105038262-0f1db280-5a9a-11eb-8f62-a6d7ca2c46a7.png)

the result of `FFmpegFrameFilter` (filter_graph : `"[0:v][1:v]hstack=inputs=2[v]"`)

![java2](https://user-images.githubusercontent.com/77626468/105038411-3ffde780-5a9a-11eb-8a4c-427a8a1caf44.png)

**Comment by saudet** [comment]
Make sure the input frames are in a pixel format acceptable for the pad and
overlay filters. Usually just normal "rgb" works fine.

**Comment by saudet** [comment]
Also make sure that the output of overlay is in the pixel format that you expect it to be...

**Comment by saudet** [comment]
Ah, I see what's going on. Simply call `recorder.record(filteredFrame, frameFilter.getPixelFormat())` to fix this. See issue #887.

**Comment by 8613510** [comment]
Thanks! it works.
