### ISSUE TITLE
OpenCV - Library not loaded: /usr/local/Cellar/gcc@7/7.5.0_3/lib/gcc/7/libquadmath.0.dylib

### ISSUE THREAD

**Issue by abbasvalliani** [bytedeco/javacv#1572]
Everything works on a windows build, however, on MacOS, the build results in the following exception:

Caused by: java.lang.UnsatisfiedLinkError: /Users/<removed>/.javacpp/cache/openblas-0.3.13-1.5.5-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/openblas/macosx-x86_64/libjniopenblas_nolapack.dylib: dlopen(/Users/<removed>/.javacpp/cache/openblas-0.3.13-1.5.5-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/openblas/macosx-x86_64/libjniopenblas_nolapack.dylib, 1): **_**Library not loaded: /usr/local/Cellar/gcc@7/7.5.0_3/lib/gcc/7/libquadmath.0.dylib****_

  **Referenced from: /Users/<removed>/.javacpp/cache/openblas-0.3.13-1.5.5-SNAPSHOT-macosx-x86_64.jar/org/bytedeco/openblas/macosx-x86_64/libgfortran.4.dylib**

  Reason: image not found
  
  The pom's I am assuming is the following:

  ```
      <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv-platform</artifactId>
            <version>4.5.1-1.5.5-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>numpy-platform</artifactId>
            <version>1.19.5-1.5.5-SNAPSHOT</version>
        </dependency>
```

The following is part of the init method:

```
import org.bytedeco.javacpp.Loader;
import org.bytedeco.opencv.opencv_java;

Loader.load(opencv_java.class);
```

**Comment by saudet** [comment]
That should be fixed now. Please update the snapshots to the latest
version, and try again.

**Comment by saudet** [comment]
The install command for GCC had to be updated. I've fixed that in commit https://github.com/bytedeco/javacpp-presets/commit/aa134b6146dda5829e3e911ab96e1e6d48ade9a6. Thanks for reporting!
