### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.opencv.dnn.Dnn.readNetFromDarknet_0(Ljava/lang/String;Ljava/lang/String;)

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1576]
When I call Dnn.readNetFromDarknet, there is an exception. do I need to do some initialization work?

**Comment by saudet** [comment]
Yes, make sure `Loader.load(opencv_java.class)` has been called:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by 4714407** [comment]
Thank you. It's ready
