### ISSUE TITLE
javacv - 1.5.4 windows server 2008 R2  UnsatisfiedLinkError: no avutil in java.library.path 

### ISSUE THREAD

**Issue by 7743366427** [bytedeco/javacv#1578]
Streaming media is already installed，  But it doesn't work or it reports an error. I installed it, didn't I
where to Install-WindowsFeature Server-Media-Foundation   
Can't find the installation location, can you provide the installation graphics or instructions
thank you！
my  Jdk 1.8   
 window server 2012  window10   no problem， window  server 2008 Not sure

**Comment by 7743366427** [comment]
I remember wrong  ，this  is 
Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in  java.library.path
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil

**Comment by 7743366427** [comment]
I remember wrong  ，this  is 
Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in  java.library.path
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil

**Comment by 7743366427** [comment]
I remember wrong  ，this  is 
Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in  java.library.path
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil

**Comment by saudet** [comment]
That probably just means there are some JAR files missing from the class path.
Make sure to include all the JAR files in your class path.

**Comment by 7743366427** [comment]
but  this in window10 or  window server 20120 is  ok！

**Comment by saudet** [comment]
Some DLLs may already be installed on the system, yes. It's not guaranteed
to work unless all JARs files are in the class path though.

**Comment by saudet** [comment]
BTW, to get more data about what it's trying to load, and what it's not able to load, set the "org.bytedeco.javacpp.logger.debug" system property to "true". This should give us enough information about what is missing what we can do about it.
