### ISSUE TITLE
could not load library "libavcodec.so"

### ISSUE THREAD

**Issue by sutogan4ik** [bytedeco/javacv#158]
Hi, I've tried everything. In my project, there are a few features.
- I Use `multidex` library. because after adding `ffmpeg` I get `Over 65K Methods` during assembly
- My project consists of several submodules

that you would not send me to guide installation

``` Java
dependencies {
    ...
    compile 'com.android.support:multidex:1.0.0'
    compile files('libs/ffmpeg.jar')
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')
    compile files('libs/opencv.jar')
    compile files('libs/ffmpeg-android-arm.jar')
    compile files('libs/opencv-android-arm.jar')
}
```

here is my code snippet

``` Java
recorder = new FFmpegFrameRecorder(getInstance().stream_url, imageWidth, imageHeight, 1);
recorder.setVideoBitrate(80000);
recorder.setFormat("flv"); 
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); 
recorder.setPixelFormat(avutil.PIX_FMT_RGB); 
recorder.setVideoOption("preset", "ultrafast"); 
recorder.setFrameRate(frameRate); 
recorder.setVideoQuality(20.0);
```

here are my logs

``` Java
06-01 15:16:27.789  16459-16459/com.aosc.base E/dalvikvm﹕ dlopen("/data/app-lib/com.aosc.base-2/libjniavcodec.so") failed: dlopen failed: could not load library "libavcodec.so" needed by "libjniavcodec.so"; caused by library "libavcodec.so" not found
06-01 15:16:27.819  16459-16459/com.aosc.base E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.aosc.base, PID: 16459
    java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avcodec
            at org.bytedeco.javacpp.Loader.load(Loader.java:388)
            at org.bytedeco.javacpp.Loader.load(Loader.java:354)
            at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1405)
            at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:147)
```

I want to note that if you add the library into a new project, all works correctly, but the integration in the project does not work
**and yet, the old version of the library in the same project worked**

**Comment by saudet** [comment]
There's most likely a lot of code that your project isn't using that ProGuard should remove for us. Have you tried using ProGuard instead of Multidex?

**Comment by sreekanth-krishnan** [comment]
Have you solved it. I am facing the same problem

**Comment by saudet** [comment]
Does this still occur with version 1.0?

**Comment by sreekanth-krishnan** [comment]
I am using 
```
    compile 'org.bytedeco:javacv:0.10'
    compile 'org.bytedeco.javacpp-presets:opencv:2.4.10-0.10'
    compile 'org.bytedeco.javacpp-presets:opencv:2.4.10-0.10'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:2.5.1-0.10'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:2.5.1-0.10'
```
Had some errors while trying to use latest version

**Comment by sreekanth-krishnan** [comment]
I couldn't upgrade to 1.0 because it breaks an already working code and can't afford to make those compatibility changes right now (in fact I tried and failed). Is there a way I can get 0.10 to work with multidex?

**Comment by olcayertas** [comment]
I have JavaCV 1.1 and multidex enabled. I am gettingfollowing error when I use `System.loadLibrary("jniopencv_core")`

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yceo.anlatbana-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yceo.anlatbana-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjniopencv_core.so"`

**Comment by saudet** [comment]
And it works without multidex?

**Comment by marwfair** [comment]
Any update on this issue? I am facing the same problem after updating from a really old version of JavaCV to 1.1.

I have added ```compile group: 'org.bytedeco', name: 'javacv', version: '1.1'``` to my build.gradle file.
I have even tried extracting all of the .so files from the jars and add them in my jniLibs armeabi folder. Not sure if that is still needed in the new version though.

I am still getting this error:
```failed: Cannot load library: soinfo_link_image(linker.cpp:1635): could not load library "libavcodec.so" needed by "libjniavcodec.so"; caused by load_library(linker.cpp:745): library "libavcodec.so" not found```

I'm not sure if multidex is the problem or not. The older version of JavaCV worked fine with multidex. I reach my 65k limit when disabled.

**Comment by saudet** [comment]
@marwfair Even if the .so files are in the APK doesn't mean your device installs them properly:
https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db

**Comment by saudet** [comment]
I'm assuming using ReLinker solved this issue, but please let me know if this isn't the case! Thanks
