### ISSUE TITLE
cv::OutOfMemoryError 

### ISSUE THREAD

**Issue by abuech2s** [bytedeco/javacv#1583]
Hello,

I am reading in mp4 files as a list of Mat-Objects.  This worked so far without any problems for exactly this video file. Suddenly (i am using still 1.5.5-SNAPSHOT) I have received an cv:OutOfMemoryError while converting a Mat-Object into a GrayScaleImage.

my method StaticScene.find() at line 69 is:

```
	Mat gray2 = new Mat();
	cvtColor(matObjects.get(idx+1), gray2, COLOR_BGR2GRAY); // line 69
```
Hint: matObjects is of type List<Mat>.
The logs are:

```
[...]
[swscaler @ 00000272e63f41c0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 00000272e63f41c0] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 00000272e63f41c0] deprecated pixel format used, make sure you did set range correctly
Exception in thread "main" java.lang.RuntimeException: OpenCV(4.5.1) modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 2073600 bytes in function 'cv::OutOfMemoryError'

        at org.bytedeco.opencv.global.opencv_imgproc.cvtColor(Native Method)
        at myprogram.logic.StaticScene.find(StaticScene.java:69)
        [...]
```

If I take a look into the Taskmanager, I can see a maximum usage of my RAM by roundabout 12GB out of 16GB. So the system limit is never exceeded.

So my question: Is there any possibility to "free memory" or to initiate garbage collection at CV-Side? Or are there any commands to extend/control the memory usage on OpenCV side (memory called by native C methods)?

What makes me wonder is, that this reading in process/iterating over Mats of this video always worked as expected until now. Maybe while using mvn, a new 1.5.5-snapshot version was loaded... Can you verify this? Or do you have any clue why this could happened? If you need any futher opencv-logs, please let me know (and tell me how to activate them)...

Thanks a lot
Alex

**Comment by saudet** [comment]
The only reason it's been working until now is probably luck. Just call gray2.deallocate() when you're done with it, or use PointerScope as shown in this post: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/
