### ISSUE TITLE
CNN basic examples Without Transfer learning ?

### ISSUE THREAD

**Issue by nikkisingh111333** [bytedeco/javacv#1588]
hey i want to use CNN iwith opencv and train my model just for learning but don't want transfer learning for now(i will use transfer learning later using YoLo or Vgg16) but for now how can i use and find examples of CNN in bytedeco opencv ?

**Comment by saudet** [comment]
There are a couple of examples here: https://github.com/bytedeco/javacv/tree/master/samples

**Comment by nikkisingh111333** [comment]
Thankyou I ll check it out

**Comment by saudet** [comment]
There is also sample code for YOLOv3 here at #1249.

/cc @cansik
