### ISSUE TITLE
OpenCV(4.4.0-1.5.4) is compiled without CUDA support？

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1600]
I try to run an [yolo example](https://github.com/bytedeco/javacv/blob/master/samples/YOLONet.java) provided by the official.
Everything is OK in cpu backend.When I deploy the program to a machine with CUDA environment installed, I find that getCudaEnabledDeviceCount returns 0.
Follow the documentation for this method, and return 0 to indicate that opencv is compiled without CUDA support.
my pom.xml As follows:
```
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacv</artifactId>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
      <version>1.5.4</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacpp</artifactId>
      <version>1.5.4</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>ffmpeg-platform</artifactId>
      <version>4.3.1-1.5.4</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>opencv-platform</artifactId>
      <version>4.4.0-1.5.4</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>opencv-platform-gpu</artifactId>
      <version>4.4.0-1.5.4</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>cuda-platform-redist</artifactId>
      <version>11.0-8.0-1.5.4</version>
    </dependency>
```
How can I use CUDA correctly?

**Comment by saudet** [comment]
You'll need to install the right version of CUDA.

**Comment by 4714407** [comment]
Which version do you need to install? When I use FFmpegFrameGrabber, I can use the decoder that uses CUDA normally, and it works well.

**Comment by saudet** [comment]
The one given here:
https://github.com/bytedeco/javacpp-presets/tree/1.5.4/cuda#introduction

**Comment by 4714407** [comment]
I seem to lack a dependency. I'll add it
```
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>cuda-platform</artifactId>
            <version>11.0-8.0-1.5.4</version>
        </dependency>

**Comment by 4714407** [comment]
What is the function of the "opencv-platform-gpu" dependency?Can I remove it?

**Comment by saudet** [comment]
Not if you want CUDA support, no.

**Comment by saudet** [comment]
As long as you install the correct version of CUDA, you do not need the "redist" one.

**Comment by 4714407** [comment]
The dependency "cuda-platform" is added, but it still can't work

The following files are in my lib directory. Is there anything missing?
![image](https://user-images.githubusercontent.com/71766981/108681818-91324880-752a-11eb-859b-15a99882e04d.png)
![image](https://user-images.githubusercontent.com/71766981/108681874-a018fb00-752a-11eb-891f-d88aab390bfd.png)
![image](https://user-images.githubusercontent.com/71766981/108681951-ae671700-752a-11eb-931f-d96d5e35c763.png)

**Comment by saudet** [comment]
Yes, you'll need to install the right version of CUDA.

**Comment by 4714407** [comment]
![image](https://user-images.githubusercontent.com/71766981/108683803-10c11700-752d-11eb-8a05-266d1535418b.png)
Is this version OK?

**Comment by saudet** [comment]
No, see above https://github.com/bytedeco/javacv/issues/1600#issuecomment-783103880

**Comment by 4714407** [comment]
Support only CUDA 11.0.3？

**Comment by 4714407** [comment]
Is the higher version not supported?

**Comment by saudet** [comment]
You can use the snapshots for that: http://bytedeco.org/builds/

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/923

**Comment by 4714407** [comment]
Which version does this support?

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/tree/master/cuda#introduction

**Comment by 4714407** [comment]
CUDA 11.2.1 ,Thank you very much.

**Comment by darekdev** [comment]
Hi!
I know that all issues and questions related to "not built with CUDA backend; switching to CPU" seems be resolved and closed but on jetson nano I can't still run CUDA backend with dnn.

I am working with RPIs and odroids and now want to test face detection model with jetson nano and javacv.

In pom.xml I have javacv-platform and opencv-platform-gpu dependencies. Additionally I try cuda dependencies and different configuration and still no success. 

Has somebody try it on jetson nano?
Thanks for all contributors for your works with javacv. :-)

**Comment by saudet** [comment]
There's no GPU build for OpenCV on linux-arm64, yet. Contributions are welcome though!

**Comment by dmichalskii** [comment]
Maybe I will try, because I use javacv and I would like to add something to support you. Well question: I should first try with manual building javacpp-presets: opencvs modules and add it to dependencies?

**Comment by saudet** [comment]
Yes, the build instructions are here: https://github.com/bytedeco/javacpp-presets#build-instructions
