### ISSUE TITLE
How to convert byte[] to Mat?

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1601]
I want to convert a byte array to a Mat object. It's OK for me to write the following code
```
ByteArrayInputStream in = new ByteArrayInputStream(img);
                        BufferedImage image = ImageIO.read(in);
                        OpenCVFrameConverter.ToMat openCVConverter = new OpenCVFrameConverter.ToMat();
                        Java2DFrameConverter java2DConverter = new Java2DFrameConverter();
                        Mat mat = openCVConverter.convert(java2DConverter.convert(image));
```
But I couldn't succeed with the following code
```
Mat mat = new Mat( height,width, CV_8UC(channel), new BytePointer(img));
```
What's wrong with the second way of writing?

**Comment by saudet** [comment]
Maybe what you're looking for is something like `imdecode()`?

**Comment by 4714407** [comment]
It's OK!
Mat mat=opencv_imgcodecs.imdecode(new Mat(new BytePointer(img)),IMREAD_ANYDEPTH | IMREAD_ANYCOLOR);
Thanks!

**Comment by saudet** [comment]
Duplicate of #384

**Comment by lushangkan** [comment]
> I want to convert a byte array to a Mat object. It's OK for me to write the following code
> 
> ```
> ByteArrayInputStream in = new ByteArrayInputStream(img);
>                         BufferedImage image = ImageIO.read(in);
>                         OpenCVFrameConverter.ToMat openCVConverter = new OpenCVFrameConverter.ToMat();
>                         Java2DFrameConverter java2DConverter = new Java2DFrameConverter();
>                         Mat mat = openCVConverter.convert(java2DConverter.convert(image));
> ```
> 
> But I couldn't succeed with the following code
> 
> ```
> Mat mat = new Mat( height,width, CV_8UC(channel), new BytePointer(img));
> ```
> 
> What's wrong with the second way of writing?

Note that when creating a mat object using new Mat, the first argument is width, not height.
