### ISSUE TITLE
When using method opencv_imgcodecs.imencode, how to set the parameter IMWRITE_JPEG_QUALITY

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1602]
Can you give me a sample code? thank you

**Comment by saudet** [comment]
It should work the same as it does in C++...

**Comment by 4714407** [comment]
```
opencv_imgcodecs.imencode(ext, mat, bp,new IntPointer(Imgcodecs.IMWRITE_JPEG_QUALITY, 70));
```
Is that right?

**Comment by saudet** [comment]
Yes, it looks like that should work: https://github.com/opencv/opencv/blob/master/samples/cpp/ela.cpp
