### ISSUE TITLE
javacv 1.5.4 inputstream block

### ISSUE THREAD

**Issue by chrisliu12345** [bytedeco/javacv#1604]
when upgrade to 1.5.4 version, then block and no log output.
	grabber = new FFmpegFrameGrabber(pis);
	grabber.setFrameRate(25);
	grabber.start();
i tried many times and it didn't work, it worked fine in 1.4.4 version, but 1.4.4 have OutOfMemoryError: Java heap space error.

**Comment by saudet** [comment]
Set the maximumSize to 0.

**Comment by chrisliu12345** [comment]
ok，I try it, thank you for replying quickly

**Comment by chrisliu12345** [comment]
solved it, this is the problem.

**Comment by saudet** [comment]
Duplicate of #1304
