### ISSUE TITLE
Can I convert an Frame object to an GpuMat object?

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1606]
Is this possible? How to do it?

**Comment by saudet** [comment]
Sure, use OpenCVFrameConverter.ToMat to get a Mat, and create a GpuMat from there.

**Comment by 4714407** [comment]
GpuMat gpuMat=new GpuMat(mat);
Is it like this?

**Comment by saudet** [comment]
Yes, that looks like what it does:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/GpuMat.html#GpuMat-org.bytedeco.opencv.opencv_core.Mat-

**Comment by 4714407** [comment]
Thank you very much.
