### ISSUE TITLE
about get range of Mat

### ISSUE THREAD

**Issue by 4714407** [bytedeco/javacv#1607]
I want to use javacv to implement the following C + + code, but I don't know how to write about range. Can you give me some guidance?
```
std::vector<cv::Range> batchRange{ cv::Range(0, 1), cv::Range::all(), cv::Range::all() };
cv::Mat mat1 = outputMat(batchRange).reshape(0, { outputMat.size[1], outputMat.size[2] });
```

**Comment by saudet** [comment]
Which part are you having problems with?

**Comment by 4714407** [comment]
I don't know how to implement outputmat (batchrange)

**Comment by saudet** [comment]
That would be Mat.apply(): http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/Mat.html#apply-org.bytedeco.opencv.opencv_core.Range-

**Comment by 4714407** [comment]
I found that there is a submat method on class org.opencv.core.Mat to implement this transformation, but it seems that there is no submat method on class org.bytedeco.opencv.opencv_core.Mat?

**Comment by 4714407** [comment]
ohh~,Let me have a try!

**Comment by 4714407** [comment]
How to construct a range of three dimensions is similar to the following code:
std::vector<cv::Range> batchRange{ cv::Range(0, 1), cv::Range::all(), cv::Range::all() };

**Comment by saudet** [comment]
We don't need a std::vector, just use an array.

**Comment by 4714407** [comment]
···
Range ranges=new Range();
            ranges.put(new Range(0,1));
            ranges.put(Range.all());
            ranges.put(Range.all());
···
Like this?

**Comment by 4714407** [comment]
How can I generate a range array

**Comment by saudet** [comment]
Almost, something like this: https://github.com/bytedeco/javacpp-presets/issues/824#issuecomment-561927903

For convenience though, I've also added a `RangeVector` in commit https://github.com/bytedeco/javacpp-presets/commit/ce0cecab695ad21461a8bbf433aed170636d7ba9.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by 4714407** [comment]
```
Range ranges=new Range(3);
            ranges.position(0).put(new Range(0,1));
            ranges.position(1).put(Range.all());
            ranges.position(2).put(Range.all());
            Mat m1=mat1.apply(ranges)；
```
Is that right?

**Comment by saudet** [comment]
No, you forgot the last call to position(0).

**Comment by 4714407** [comment]
Thank you. It's working!
