### ISSUE TITLE
OpenCVFrameGrabber grab( ) latency

### ISSUE THREAD

**Issue by SergeLegros** [bytedeco/javacv#1609]
Hello,

I'm using opencvframegrabber to extract frames from a 4k camera but I'm unable to save videos over 20fps because of some latency caused by grab( ). Here's the code causing trouble:

    public Event process(Event context) {

        double begin=System.currentTimeMillis();//

        try {
            Frame frame = grabber.grabFrame();
            if (isEmptyFrame(frame)) {
                grabber.restart();
                System.out.println("CVCamera: The frame is NULL");
                return this.process(context);
            }
            double end=System.currentTimeMillis();//
            System.out.println("grab delay: "+(end-begin));//

            beforeProcessFrame();
            processFrame(frame, converterToMat.convert(frame));
            afterProcessFrame();

            if (this.display) {
                this.displayFrame(this.name, frame);
            }
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }
        return super.process(context);
    }

While it's running I get a grab delay of about 40ms whatever settings I choose:

grab delay: 40.0
delta2 = 40.0 ms
delta1 = 7.0 ms
grab delay: 39.0
delta2 = 39.0 ms
delta1 = 8.0 ms

delta1 corresponds to how long it takes to do recorder.record(frame); and delta2 for how long all of the rest of the code takes.
Delta1+grab delay should be under 33ms if I want a 30 or more fps video. 

Do you see any mistakes or are there any settings I can play with to speed things up? 

Thanks in advance

**Comment by saudet** [comment]
Please try FFmpegFrameGrabber instead. FFmpeg is usually better at video capture than OpenCV.

**Comment by saudet** [comment]
BTW, you should process frames in another thread, and use that thread only to grab, exclusively. That should fix this issue, but let me know if it doesn't.
