### ISSUE TITLE
JavaCV Maven Download Error

### ISSUE THREAD

**Issue by jiseung2007** [bytedeco/javacv#1612]
I was trying to make it work but there was no luck and I couldn't find any more info about my situation So I am reaching out to you and asking for help. Here is my code

I am using Maven and Eclipse for this

`package app.OCV;

import org.opencv.core.Core;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
     System.load(Core.NATIVE_LIBRARY_NAME);
    }
    
}
`

When I run the code it gives me this

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: opencv_java451
	at java.lang.Runtime.load0(Unknown Source)
	at java.lang.System.load(Unknown Source)
	at app.OCV.App.main(App.java:13)
`

Thank you so much! (I am a foreigner so my English is bad sorry)

**Comment by saudet** [comment]
Please run `Loader.load(opencv_java.class)` as documented here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation
