### ISSUE TITLE
ArToolKitPlus examples

### ISSUE THREAD

**Issue by stephnicolas** [bytedeco/javacv#1619]
Are there any artoolkitplus examples with javacv? is it still supported?

**Comment by saudet** [comment]
There is legacy sample code in JavaCV here:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/Marker.java
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/MarkerDetector.java
But ARToolKitPlus itself isn't being maintained. I recommend using the new ArUco module from OpenCV.
