### ISSUE TITLE
How to reduce size of final jar

### ISSUE THREAD

**Issue by NathanJAdams** [bytedeco/javacv#1623]
I'm using this library just to grab video frames and it works well. However when it comes to jarring it up into a fat jar using the shade plugin it takes around 2 minutes to build and results in a massive final jar of around 780MB.

Is there any way of reducing what's included or some tree-shaking that can be done?

**Comment by saudet** [comment]
The information for that is here:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
