### ISSUE TITLE
Cannot use Loader.load(org.bytedeco.ffmpeg.ffmpeg.class); retuen null in android

### ISSUE THREAD

**Issue by s894792409** [bytedeco/javacv#1626]
Loader.load(org.bytedeco.ffmpeg.ffmpeg.class); retuen null,but not exception.I want to  use the ffmpeg program in android

**Comment by saudet** [comment]
Newer APIs of Android don't support executables. Make sure to build for an older version of Android.

**Comment by saudet** [comment]
Duplicate of #1410
