### ISSUE TITLE
How can I read image from network？

### ISSUE THREAD

**Issue by ZhouYixun** [bytedeco/javacv#1628]
When I use 
`Mat myImg = imread("http://www.example.com/thankjavacv.jpg")`
get an error

I know python can use VideoCapture to read image by opencv
but how can I read image from network by javacv？
thank you!

**Comment by saudet** [comment]
We can also use VideoCapture from Java.

**Comment by ZhouYixun** [comment]
> 我们还可以使用Java的VideoCapture。

Thanks for your quick reply!
But I can't use 
`Mat myImg = new VideoCapture("http://www.example.com/thankjavacv.jpg").read;`
it is different from python

**Comment by ZhouYixun** [comment]
I can't transfer curl response to Mat,it is any method in javacv?

**Comment by saudet** [comment]
Please clarify.

**Comment by saudet** [comment]
VideoCapture.read() is the same:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/Mat.html

**Comment by ZhouYixun** [comment]
I use VideoCapture like this
` Mat image = new Mat();`
`new VideoCapture("http://www.example.com/thankjavacv.jpg").read(image);`
but I get 
`OpenCV: Couldn't read video stream from file "http://172.16.51.36/media/uploads/202011141036168452.jpg"`

what is the best way to read image from network?

**Comment by saudet** [comment]
I guess it's FFmpeg that might be doing that, so you could try
FFmpegFrameGrabber.

**Comment by ZhouYixun** [comment]
> I guess it's F

Thanks！it works.
