### ISSUE TITLE
avformat_write_header error() error -40: Could not write header to 'rtmp://192.168.103.227:1985/myapp/6'

### ISSUE THREAD

**Issue by LW-Francis** [bytedeco/javacv#1631]
avformat_write_header error() error -40: Could not write header to 'rtmp://192.168.103.227:1985/myapp/6'

**Comment by saudet** [comment]
Could you also provide the messages that get displayed on the console?

**Comment by LW-Francis** [comment]
i call FFmpegLogCallback.set() and the console output

Warning: [nvenc_hevc @ 000002a9ad3c9ac0] This encoder is deprecated, use 'hevc_nvenc' instead

Error: [flv @ 000002a9ad952000] Video codec hevc not compatible with flv

**Comment by LW-Francis** [comment]
how do i change the encoder

**Comment by saudet** [comment]
You're probably calling `setVideoCodecName("nvenc_hevc")`, so don't call that, and call `setVideoCodecName("hevc_nvenc")` instead. Also don't use flv, use some other format like mp4.

**Comment by saudet** [comment]
Duplicate of #1497.

**Comment by LW-Francis** [comment]
ok,thank you
