### ISSUE TITLE
how to grab frame by timestamp?

### ISSUE THREAD

**Issue by wangxi761** [bytedeco/javacv#1633]
in ffmpeg ,i can use `-re` paramter , read input file by native frame rate.
in javacv how can i make it ?
now ,i use Thread.sleep(1000/frameRate) after i record a frame,
but it  seems no work , the rtmp stream is lagging

**Comment by Wicz3k** [comment]
Try something like this:
`       
        Mat actualImage = new Mat();
        long startTime = System.currentTimeMillis();
        while (videoCapture.read(actualImage)) {
             //process image
            long finishTime = System.currentTimeMillis();
            long sleepTime = Math.max(0, 1000/<your framerate> - (finishTime - startTime));
            if(sleepTime>0) {
                Thread.sleep(sleepTime);
            }
            startTime = finishTime;
        }`
Instead of `<your framerate>` insert your framerate.

**Comment by wangxi761** [comment]
@Wicz3k 
I have not used videoCapture，so i'm not sure is it ok in your sence。
but in my sence , i push a local mp4 video to rtmp stream , This code doesn't work either。
and  in my test  , if framerate is 25 , sleep time should in range 10 to 15 , but The calculated value is around 40

```java
// local mp4 file
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new FileInputStream(file));
grabber.start();
//rtmp url
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(url, grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
try {
	recorder.setFormat("flv");
	recorder.setVideoCodec(grabber.getVideoCodec());
	recorder.setAudioCodec(grabber.getAudioCodec());
	recorder.setVideoBitrate(grabber.getVideoBitrate());
	recorder.setAudioBitrate(grabber.getAudioBitrate());
	recorder.setFrameRate(grabber.getFrameRate());
	recorder.start();
	
	log.info("framerate is:{}", grabber.getFrameRate());
	
	Frame frame = null;
	while ((frame = grabber.grab()) != null) {
		long begin = System.currentTimeMillis();
		recorder.record(frame);
		long end = System.currentTimeMillis();
		long sleep_real = (long) ((1000 / grabber.getFrameRate()) - (end - begin));
		if (sleep_real > 0) {
			Thread.sleep(sleep_real);
		}
	}
} finally {
	recorder.stop();
	recorder.release();
	grabber.stop();
	grabber.release();
}
```

**Comment by Wicz3k** [comment]
Try:
```java
long begin = System.currentTimeMillis();
while ((frame = grabber.grab()) != null) {
        recorder.record(frame);
        long end = System.currentTimeMillis();
        long sleep_real = (long) ((1000 / grabber.getFrameRate()) - (end - begin));
        begin = end;
        if (sleep_real > 0) {
	        Thread.sleep(sleep_real);
        }
}
```
Call grab can take some time and you have to messure this time.

**Comment by wangxi761** [comment]
@Wicz3k       yes  i try it either .  But the delay is obvious both in video and audio

**Comment by wangxi761** [comment]
update my progress：
sleep time = frame timestamp - (current time- begin time)
example code :
```
long begin = System.currentTimeMillis();
Frame frame = null;
while ((frame = grabber.grab()) != null) {
	long delay = frame.timestamp / 1000 - (System.currentTimeMillis() - begin);
	if (delay > 0) {
		Thread.sleep(delay);
	}
	recorder.record(frame);

```
it 's no delay !

**Comment by saudet** [comment]
Duplicate of #1654

**Comment by saudet** [comment]
@Wicz3k @wangxi761 It would be great if you could contribute this code to FFmpegFrameGrabber! Thanks

**Comment by wangxi761** [comment]
@saudet 
it's a good idea , i think we should add a param "-re" to FFmpegFrameGrabber , and grab() delay by timestamp
