### ISSUE TITLE
org.bytedeco.javacv.FFmpegFrameRecorder$Exception: No video output stream

### ISSUE THREAD

**Issue by TFreudi1** [bytedeco/javacv#1636]
Hello
I'm under Android and try to use the Outputstream constructor  of FFmpegFrameRecorder, because i get the final file from a content picker (Android 11) an do not habve a real pathname.
But even if I use a simple file it didnt work. Everything works fine until I call recorder.record(frame); Than I got the error and the videofile ist not been written.

So that works:
savePath =mediaStorageDir.getAbsoluteFile() + File.separator + "VID_" + timeStamp + ".mp4";
recorder = new FFmpegFrameRecorder(savePath, frameWidth, frameHeight, 0);

but that not:
savePath =mediaStorageDir.getAbsoluteFile() + File.separator + "VID_" + timeStamp + ".mp4";
try {
       File f = new File(savePath);
	FileOutputStream fo = new FileOutputStream(f);
	recorder = new FFmpegFrameRecorder( fo, frameWidth, frameHeight, 0);
} catch (FileNotFoundException e) {
		e.printStackTrace();
}

Thomas

**Comment by saudet** [comment]
The "mp4" format doesn't work well with streams. If it doesn't work, please try to use another format such as "mkv".

**Comment by TFreudi1** [comment]
Same with MKV and different codecs that I tried. Looks like something wrong with the OutputStream constructor or I must set some more things. Why do you close it ? And where ist the "duplicate" question ?

**Comment by saudet** [comment]
There are so many duplicate questions about the mp4 format not working with streams, I don't bother anymore.
People don't read the docs, past issues, or anything else before asking questions. I'm not spending time on this.

The mkv format works fine with output streams though, here is a working example in the unit tests:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameGrabberTest.java#L54

**Comment by TFreudi1** [comment]
OK, I will check your sample , I must admit that this is a bit special, because the OutputStream is provided by a content provider.
But in newer versions of Android we are forced to move from regular "linux-paths" to content providers, where the user pick the destination path , or in my case, pick a directory by a system dialog and confirm the write access to that directory. Thats the way that Google wants us to go.

**Comment by saudet** [comment]
I'm aware of how it works on Android, although we can use files with very recent versions too. In any case, it doesn't change the fact that the "mp4" format doesn't work well with output streams: Don't use it!
