### ISSUE TITLE
Problem with FFmpagFrameGarbber class

### ISSUE THREAD

**Issue by YazdanNA** [bytedeco/javacv#1642]
Hello
I want to use FFmpegFrameGrabber to get an array of frames that I can use in different parts of the program, but after stopping FFmpegFrameGrabber and return the array, I have the following problem.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001e38069c11e, pid=7712, tid=2868
#
# JRE version: Java(TM) SE Runtime Environment (14.0.2+12) (build 14.0.2+12-46)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (14.0.2+12-46, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# J 584 c1 jdk.internal.misc.Unsafe.getByte(J)B java.base@14.0.2 (7 bytes) @ 0x000001e38069c11e [0x000001e38069c0a0+0x000000000000007e]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Pishgaman\Documents\NetBeansProjects\WaterMark\hs_err_pid7712.log
Compiled method (c1)    7467  584       3       jdk.internal.misc.Unsafe::getByte (7 bytes)
 total in heap  [0x000001e38069bf10,0x000001e38069c228] = 792
 relocation     [0x000001e38069c070,0x000001e38069c098] = 40
 main code      [0x000001e38069c0a0,0x000001e38069c1a0] = 256
 stub code      [0x000001e38069c1a0,0x000001e38069c1d8] = 56
 metadata       [0x000001e38069c1d8,0x000001e38069c1e0] = 8
 scopes data    [0x000001e38069c1e0,0x000001e38069c1f0] = 16
 scopes pcs     [0x000001e38069c1f0,0x000001e38069c220] = 48
 dependencies   [0x000001e38069c220,0x000001e38069c228] = 8
Compiled method (c1)    7537  584       3       jdk.internal.misc.Unsafe::getByte (7 bytes)
 total in heap  [0x000001e38069bf10,0x000001e38069c228] = 792
 relocation     [0x000001e38069c070,0x000001e38069c098] = 40
 main code      [0x000001e38069c0a0,0x000001e38069c1a0] = 256
 stub code      [0x000001e38069c1a0,0x000001e38069c1d8] = 56
 metadata       [0x000001e38069c1d8,0x000001e38069c1e0] = 8
 scopes data    [0x000001e38069c1e0,0x000001e38069c1f0] = 16
 scopes pcs     [0x000001e38069c1f0,0x000001e38069c220] = 48
 dependencies   [0x000001e38069c220,0x000001e38069c228] = 8
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#

please guide me

**Comment by YazdanNA** [comment]
Is this a bug?

**Comment by saudet** [comment]
No, that probably just means that you'll need to copy the data.

**Comment by YazdanNA** [comment]
How do I do this?
I want to have an array of frames so that I can do the necessary processing by converting it to BufferedImage, then converting it to a frame and converting it to a movie with FFmpegFrameRecorder.
But when I try to do this, I get this error

**Comment by saudet** [comment]
If you convert all frames to BufferedImage, they get copies, so that's fine.

**Comment by YazdanNA** [comment]
Sorry I'm not a professional programmer and I hope you help me
My goal is to create a movie editor. To do this, I want to extract the video frames and apply the user requests to them, and then convert it back to video and put the video audio on it. After some research,  I decided to use this library and I do not know exactly how it works

**Comment by YazdanNA** [comment]
Thanks for help

**Comment by saudet** [comment]
If you can show me your code, I should be able to tell you what is wrong with it.

**Comment by YazdanNA** [comment]
This is my code and I used GerbPacket () because of its high speed. Now that I want to process the images, how do I extract the image and access the audio?
For example, is there a way I can convert it to BufferedImage?
Cut part of the video audio and put it on the video?
Can I put a watermark or subtitle on the video?
And ....
I know these questions may seem very beginner, but the truth is that I am a beginner and if you can guide me to make good use of this complete library, thank you very much.









import org.bytedeco.ffmpeg.avcodec.AVPacket;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Java2DFrameConverter;

public class Test2 {

    private static String input_path = "E:\\Java\\فصل اول مباحث پایه\\1.mp4";
    private static String output_path = "E:\\video1234567890.mp4";


    public static void main(String[] args) {


        final FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(input_path);
        try {
            grabber.start();
            final FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(output_path
                    , grabber.getImageWidth(), grabber.getImageHeight()
                    , grabber.getAudioChannels());

            recorder.start(grabber.getFormatContext());

            System.out.println("Start!");


            while (true) {
                AVPacket packet = grabber.grabPacket();
                if (packet == null) {
                    break;
                } else {
                    recorder.recordPacket(packet);
                }

            }
            System.out.println("Finished!");
            grabber.stop();
            grabber.release();
            recorder.stop();
            recorder.release();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


}

**Comment by saudet** [comment]
> This is my code and I used GerbPacket () because of its high speed. Now that I want to process the images, how do I extract the image and access the audio?

You can't, you'll need to call grab(), not grabPacket().

**Comment by YazdanNA** [comment]
I use this method to have an array of frames, but when I call stop(), when I want to use frames, I get the error I mentioned at the top of the page.
---------------------------------------------------------

 public  Frame[] grabFrame(String videoPath) throws FFmpegFrameGrabber.Exception
    {
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(videoPath);
        grabber.start();
        
       
         Frame[] frames = new Frame[grabber.getLengthInFrames()];
        int flag = 0;
        int index =0;
        Frame frame = null;
        while (flag<frames.length)
        {
             frame = grabber.grab();
            


            if(frame!=null)
            {

                frames[index] = frame;
                index++;

            }

            flag++;
        }
        
        
        grabber.stop();
        grabber.release();
        return frames;
    }

output:

A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001e38069c11e, pid=7712, tid=2868
JRE version: Java(TM) SE Runtime Environment (14.0.2+12) (build 14.0.2+12-46)
Java VM: Java HotSpot(TM) 64-Bit Server VM (14.0.2+12-46, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
Problematic frame:
J 584 c1 jdk.internal.misc.Unsafe.getByte(J)B java.base@14.0.2 (7 bytes) @ 0x000001e38069c11e [0x000001e38069c0a0+0x000000000000007e]
No core dump will be written. Minidumps are not enabled by default on client versions of Windows
An error report file with more information is saved as:
C:\Users\Pishgaman\Documents\NetBeansProjects\WaterMark\hs_err_pid7712.log
Compiled method (c1) 7467 584 3 jdk.internal.misc.Unsafe::getByte (7 bytes)
total in heap [0x000001e38069bf10,0x000001e38069c228] = 792
relocation [0x000001e38069c070,0x000001e38069c098] = 40
main code [0x000001e38069c0a0,0x000001e38069c1a0] = 256
stub code [0x000001e38069c1a0,0x000001e38069c1d8] = 56
metadata [0x000001e38069c1d8,0x000001e38069c1e0] = 8
scopes data [0x000001e38069c1e0,0x000001e38069c1f0] = 16
scopes pcs [0x000001e38069c1f0,0x000001e38069c220] = 48
dependencies [0x000001e38069c220,0x000001e38069c228] = 8
Compiled method (c1) 7537 584 3 jdk.internal.misc.Unsafe::getByte (7 bytes)
total in heap [0x000001e38069bf10,0x000001e38069c228] = 792
relocation [0x000001e38069c070,0x000001e38069c098] = 40
main code [0x000001e38069c0a0,0x000001e38069c1a0] = 256
stub code [0x000001e38069c1a0,0x000001e38069c1d8] = 56
metadata [0x000001e38069c1d8,0x000001e38069c1e0] = 8
scopes data [0x000001e38069c1e0,0x000001e38069c1f0] = 16
scopes pcs [0x000001e38069c1f0,0x000001e38069c220] = 48
dependencies [0x000001e38069c220,0x000001e38069c228] = 8

If you would like to submit a bug report, please visit:
https://bugreport.java.com/bugreport/crash.jsp

**Comment by saudet** [comment]
Like I said, you'll need to make a copy of them. You can call Frame.clone() for that.
