### ISSUE TITLE
metadata information

### ISSUE THREAD

**Issue by Nirvana-feng** [bytedeco/javacv#1644]
Hello, how can javacv get more metadata information, such as video resolution, width, height, duration, etc

**Comment by saudet** [comment]
`FFmpegFrameGrabber.getMetadata()`?

**Comment by Nirvana-feng** [comment]
Thank you. I used this method. However, it can't get the video time rate, video width and height. Duration, etc

**Comment by saudet** [comment]
There's also `getFrameRate()`,` getImageWidth()`, `getImageHeight()`, etc.

**Comment by saudet** [comment]
If there's anything missing though, please let us know.

**Comment by Nirvana-feng** [comment]
Sorry to get back to you now. The problem has been basically solved. Thank you for your patient guidance
