### ISSUE TITLE
Crop filter output is different with ffmpeg command line

### ISSUE THREAD

**Issue by zhangxueyii** [bytedeco/javacv#1648]
The output of the same crop filter using JavaCV is different with the output using ffmpeg command line.

Can anyone help me on this issue? appreciate very much.

Input image size is width=800, height=1067, image file is attached.
Filter: `"crop=800:800:0:ih/2"`
The ffmpeg command line: `./ffmpeg -y -i ./imgs/22.jpeg -filter:v "crop=800:800:0:ih/2" ./may25_1816.mp4`
The java code:

`
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outPath, 800, 800);
        // set encoding
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setFrameRate(frameRate);
        // Set the video data format
        recorder.setFormat("mp4");
        try {
            recorder.start();
            // Record video
            int count = 0;
            Java2DFrameConverter converter = new Java2DFrameConverter();
            BufferedImage bufferedImage = ImageIO.read(img);
            Frame frame = converter.getFrame(bufferedImage);
            String scale = width + "X" + height;

            FFmpegFrameFilter filter = new FFmpegFrameFilter("crop=800:800:0:ih/2", 800, 800);

            filter.setImageWidth(width);
            filter.setImageHeight(height);
            filter.start();
            filter.push(frame, AV_PIX_FMT_BGR24);

            Frame filteredFrame = null;
            while ((filteredFrame = filter.pullImage()) != null) {
                recorder.record(filteredFrame, filter.getPixelFormat());
                count++;
            }
            System.out.println("total frames " + count);
        } catch (
                IOException e) {
            e.printStackTrace();
        } finally {
            // release resources
            recorder.stop();
            recorder.release();
        }
`

The input image:
![image](https://user-images.githubusercontent.com/18297700/119482660-b717f500-bd86-11eb-9d2a-6a809795083f.png)

The output video:
![image](https://user-images.githubusercontent.com/18297700/119482616-ac5d6000-bd86-11eb-8946-a7d0a22f7b80.png)

**Comment by saudet** [comment]
Maybe the origin of images for the ffmpeg program is at the bottom?
If that's the case, you'll need to adjust the cropping coordinates accordingly.

**Comment by zhangxueyii** [comment]
@saudet  the input image for java code and the ffmpeg program is the same one, also the cropping coordinates are the exact same. 

I tested the java code by changing the y argument of crop filter, the output video is exactly same. looks like the y argument does not take effect. meanwhile, I tested the width and height argument take effects when i change them. 

![image](https://user-images.githubusercontent.com/18297700/119607355-be8edb00-be26-11eb-8b84-84b006ea5785.png)

**Comment by zhangxueyii** [comment]
@saudet on the contrary, the y argument effect in ffmpeg command is like this:
![image](https://user-images.githubusercontent.com/18297700/119608179-1da11f80-be28-11eb-9db5-8c8d33f61532.png)

**Comment by saudet** [comment]
Maybe it's a bug in old versions of FFmpeg. Be sure to try with JavaCV 1.5.6-SNAPSHOT: http://bytedeco.org/builds/

**Comment by zhangxueyii** [comment]
@saudet  it's my bad. After I pass the input image's height to the ctor of FFmpegFrameFilter, it works as expected.

`
            FFmpegFrameFilter filter = new FFmpegFrameFilter("crop=800:800:0:300", 800, 1067);
`
