### ISSUE TITLE
fatal error when convert Mat to ByteString(multi-threads)

### ISSUE THREAD

**Issue by whalefa1I** [bytedeco/javacv#1649]
Hi, I need to send some image data into tensorflow serving using JavaCV, after preprocessing a image, a mat(in code:mat2) need to be convert to ByteString type,and some fatal error happend occasionaly when I test the code in multiple threads:
1.code:
```
IplImage currentImage = oriImagCurrent.clone();
            cvSetImageROI(currentImage, cvRect);
            IplImage cropImage = IplImage.create(cvRect.width(), cvRect.height(), currentImage.depth(), currentImage.nChannels());
            cvCopy(currentImage, cropImage);
            resizedImg = IplImage.create(LANDMARK_SIZE, LANDMARK_SIZE, cropImage.depth(), cropImage.nChannels());
            cvResize(cropImage, resizedImg);

            // build & send landmark protobuilder
            Mat landmarkMat = new Mat(resizedImg);
            Mat mat2 = new Mat();
            landmarkMat.convertTo(mat2, CV_32FC1);
// slow
//        TensorProto.Builder lanMarkProto = TensorProto.newBuilder().setDtype(DT_FLOAT).setTensorShape(LANDMARK_PROTO);
//        for (int k = 0; k < 160; k++) {
//            for (int j = 0; j < 160; j++) {
//                CvScalar pixel = cvGet2D(resizedImg, k, j);
//                for (int l = 0; l < 3; l++) {
//                    lanMarkProto.addFloatVal((float) pixel.val(l));
//                }
//            }
//        }
// @deprecated
//        ByteBuffer buffer = mat2.getByteBuffer();//data().asByteBuffer();//getByteBuffer();//
//        //ByteString content = ByteString.copyFrom(buffer);
//        ByteString content = UnsafeByteOperations.unsafeWrap(buffer);
            log.info("fatal error waiting...");
            byte[] data = new byte[mat2.cols() * mat2.rows() * 3 * 4];
            log.info("fatal error waiting...");
            Indexer indexer = mat2.createIndexer();
            log.info("fatal error indexer data:{}",indexer.index(0));
            log.info("fatal error indexer size:{}",indexer.sizes());
            BytePointer bytePointer = mat2.data();
            log.info("fatal error bytePointer data:{}",bytePointer.toString());
            log.info("fatal error bytePointer 1st data:{}",bytePointer.getFloat());
            bytePointer.get(data);
            log.info("fatal error data ready");
            content = ByteString.copyFrom(data);
            data = null;
            bytePointer.deallocate();
            bytePointer= null;
            indexer = null;
            log.info("fatal error content ready !");

            TensorProto.Builder lanMarkProto = TensorProto.newBuilder().setDtype(DT_FLOAT).setTensorShape(LANDMARK_PROTO).setTensorContent(content);
            log.info("no fatal error !");
```
2.server log:
2021-05-27 17:09:35.284 [bd-pica-api] [INFO ] [grpc-executor-4] com.em.api.algo.impl.FaceProcessorSerivceImpl - fatal error waiting...
2021-05-27 17:09:35.284 [bd-pica-api] [INFO ] [grpc-executor-4] com.em.api.algo.impl.FaceProcessorSerivceImpl - fatal error waiting...
2021-05-27 17:09:35.284 [bd-pica-api] [INFO ] [grpc-executor-4] com.em.api.algo.impl.FaceProcessorSerivceImpl - fatal error indexer data:0
2021-05-27 17:09:35.284 [bd-pica-api] [INFO ] [grpc-executor-4] com.em.api.algo.impl.FaceProcessorSerivceImpl - fatal error indexer size:[160, 160, 3]
2021-05-27 17:09:35.270 [bd-pica-api] [INFO ] [grpc-executor-5] com.em.api.face.FaceServer - checkModel received params:
data=<ByteString@1f7d8c64 size=783360 contents="\203\203\203\203\203\203\203\203\203\203\203\203\203\203\204\205\204\204\204\204\204\204\204\204\204\204\205\205\205\205\206\206\205\205\205\205\205\205\205\205\205\205\205\205\205\205\205...">,width=544,height=960
2021-05-27 17:09:35.284 [bd-pica-api] [INFO ] [grpc-executor-4] com.em.api.algo.impl.FaceProcessorSerivceImpl - fatal error bytePointer data:org.bytedeco.javacpp.BytePointer[address=0x7f5fb8677980,position=0,limit=0,capacity=0,deallocator=null]
2021-05-27 17:09:35.284 [bd-pica-api] [INFO ] [grpc-executor-4] com.em.api.algo.impl.FaceProcessorSerivceImpl - fatal error bytePointer 1st data:31.0
(last log )
3.maven:
```
<javacv.version>1.5.4</javacv.version>
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>${javacv.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>${javacv.version}</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>${javacv.version}</version>
        </dependency>
```

**Comment by whalefa1I** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f60c0fb8030, pid=24993, tid=0x00007f60164ef700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x15a030]  __memmove_ssse3_back+0x50
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007f602420b000):  JavaThread "grpc-executor-4" daemon [_thread_in_native, id=27549, stack(0x00007f60163ef000,0x00007f60164f0000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007f5fb8677980

Registers:
RAX=0x00000007a5cbf420, RBX=0x00007f602420b1f8, RCX=0x0000000000000003, RDX=0x000000000004b000
RSP=0x00007f60164ee1d8, RBP=0x0000000000000000, RSI=0x00007f5fb8677980, RDI=0x00000007a5cbf420
R8 =0x0000000000000001, R9 =0x00000000000001af, R10=0x0000000000000000, R11=0x0000000000000206
R12=0x00000007a5cbf420, R13=0x00007f60164ee230, R14=0x000000000004b000, R15=0x00007f60164ee238
RIP=0x00007f60c0fb8030, EFLAGS=0x0000000000010202, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007f60164ee1d8)
0x00007f60164ee1d8:   00007f6015ae2e61 00007f6000000000
0x00007f60164ee1e8:   00007f5fb8677980 00000006c0267228
0x00007f60164ee1f8:   000000000000001c 00007f60164ee270
0x00007f60164ee208:   0000000000000000 00000006c06c5b68
0x00007f60164ee218:   00000000d804cbd6 00007f602420b000
0x00007f60164ee228:   00007f60aa1bf48a 00000007a61bfa90
0x00007f60164ee238:   00000007a5cbf410 00000007a7bd5f00
0x00007f60164ee248:   00000006c0000cc0 00000006c0c0c0e0
0x00007f60164ee258:   00000007a7bd5f18 00000007a7bd3d78
0x00007f60164ee268:   000000070000008e 000000000004b000
0x00007f60164ee278:   00007f60a9dd08d8 00000006c0bb2ae0
0x00007f60164ee288:   00007f60a90fef49 000000000004b000
0x00007f60164ee298:   00007f60aa4431bc 00000007a7b85510
0x00007f60164ee2a8:   00000007a7b85630 00000006c00328a0
0x00007f60164ee2b8:   00000007a7bd4e90 00000007a5cbf410
0x00007f60164ee2c8:   00000007a7bd3de8 00000007a61bfac0
0x00007f60164ee2d8:   00000007a8b82f60 00000007c039eb60
0x00007f60164ee2e8:   00000007a7b87a90 00000007a7b87ae0
0x00007f60164ee2f8:   00000007000000be 00000007a7b86a00
0x00007f60164ee308:   00000006c00328a0 00000007a7b82c30
0x00007f60164ee318:   00000007a7b83b08 00007f60b922f000
0x00007f60164ee328:   00000007a7b849e0 00000007a7db8ef8
0x00007f60164ee338:   00000007a7db91b8 00000007a7dd25e8
0x00007f60164ee348:   00000006c00329bc 0000000000000079
0x00007f60164ee358:   00007f60a9bce194 00000000d8006514
0x00007f60164ee368:   00007f60aa16385c 00000007a8b7f528
0x00007f60164ee378:   00000006c035f0a8 00000007a61bfaf0
0x00007f60164ee388:   00000007d806be15 00000007a8b7f4d0
0x00007f60164ee398:   00000007a8b7f528 00000006c0001128
0x00007f60164ee3a8:   00000006c0de62c8 00000007f4c37fae
0x00007f60164ee3b8:   00007f60a959fb98 00000007a875ad18
0x00007f60164ee3c8:   00000007a8b7f160 00000000f516fe28 

Instructions: (pc=0x00007f60c0fb8030)
0x00007f60c0fb8010:   fa 90 00 00 00 73 19 48 01 d6 48 01 d7 4c 8d 1d
0x00007f60c0fb8020:   ec 46 03 00 49 63 14 93 49 8d 14 13 ff e2 0f 0b
0x00007f60c0fb8030:   f3 0f 6f 06 49 89 f8 48 83 e7 f0 48 83 c7 10 49
0x00007f60c0fb8040:   89 f9 4d 29 c1 4c 29 ca 4c 01 ce 49 89 f1 49 83 

Register to memory mapping:

RAX=0x00000007a5cbf420 is pointing into object: 0x00000007a5cbf410
[B 
 - klass: {type array byte}
 - length: 307200
RBX=0x00007f602420b1f8 is an unknown value
RCX=0x0000000000000003 is an unknown value
RDX=0x000000000004b000 is an unknown value
RSP=0x00007f60164ee1d8 is pointing into the stack for thread: 0x00007f602420b000
RBP=0x0000000000000000 is an unknown value
RSI=0x00007f5fb8677980 is an unknown value
RDI=0x00000007a5cbf420 is pointing into object: 0x00000007a5cbf410
[B 
 - klass: {type array byte}
 - length: 307200
R8 =0x0000000000000001 is an unknown value
R9 =0x00000000000001af is an unknown value
R10=0x0000000000000000 is an unknown value
R11=0x0000000000000206 is an unknown value
R12=0x00000007a5cbf420 is pointing into object: 0x00000007a5cbf410
[B 
 - klass: {type array byte}
 - length: 307200
R13=0x00007f60164ee230 is pointing into the stack for thread: 0x00007f602420b000
R14=0x000000000004b000 is an unknown value
R15=0x00007f60164ee238 is pointing into the stack for thread: 0x00007f602420b000


Stack: [0x00007f60163ef000,0x00007f60164f0000],  sp=0x00007f60164ee1d8,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x15a030]  __memmove_ssse3_back+0x50

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 6403  org.bytedeco.javacpp.BytePointer.get([BII)Lorg/bytedeco/javacpp/BytePointer; (0 bytes) @ 0x00007f60aa1bf40c [0x00007f60aa1bf3c0+0x4c]
J 8791 C2 org.bytedeco.javacpp.BytePointer.get([B)Lorg/bytedeco/javacpp/BytePointer; (9 bytes) @ 0x00007f60a9dd08d8 [0x00007f60a9dd08a0+0x38]
J 7041 C2 com.****.api.algo.impl.FaceProcessorSerivceImpl.getModelInfo(Lcom/*****/api/face/ModelCheckRequest;)Lcom/*****/api/face/ModelCheckResponse; (2203 bytes) @ 0x00007f60aa4431bc [0x00007f60aa43ebc0+0x45fc]
J 8984 C2 io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose()V (82 bytes) @ 0x00007f60aa16385c [0x00007f60aa1632c0+0x59c]
J 9034 C2 io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext()V (73 bytes) @ 0x00007f60a96e90c8 [0x00007f60a96e9040+0x88]
J 6921 C2 io.grpc.internal.ContextRunnable.run()V (35 bytes) @ 0x00007f60aa3e1e90 [0x00007f60aa3e1c80+0x210]
J 7016 C2 io.grpc.internal.SerializingExecutor.run()V (99 bytes) @ 0x00007f60a914ccf0 [0x00007f60a914ca60+0x290]
J 9222% C1 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f60aa3be70c [0x00007f60aa3bd820+0xeec]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x00007f60240ad000 JavaThread "grpc-executor-13" daemon [_thread_blocked, id=20743, stack(0x00007f5ffc8c5000,0x00007f5ffc9c6000)]
  0x00007f6024161800 JavaThread "grpc-executor-12" daemon [_thread_blocked, id=16581, stack(0x00007f5fedcd7000,0x00007f5feddd8000)]
  0x00007f602418e000 JavaThread "grpc-executor-11" daemon [_thread_in_Java, id=31296, stack(0x00007f6040c01000,0x00007f6040d02000)]
  0x00007f602408f800 JavaThread "grpc-default-worker-ELG-3-4" daemon [_thread_in_native, id=27568, stack(0x00007f5ffc9c6000,0x00007f5ffcac7000)]
  0x00007f603c0ed000 JavaThread "grpc-default-worker-ELG-3-3" daemon [_thread_in_native, id=27567, stack(0x00007f5ffcac7000,0x00007f5ffcbc8000)]
  0x00007f6044249000 JavaThread "grpc-default-worker-ELG-3-2" daemon [_thread_in_native, id=27566, stack(0x00007f5ffcbc8000,0x00007f5ffccc9000)]
  0x00007f604800b000 JavaThread "JavaCPP Deallocator" daemon [_thread_blocked, id=27555, stack(0x00007f6014de3000,0x00007f6014ee4000)]
  0x00007f6024247000 JavaThread "grpc-executor-9" daemon [_thread_blocked, id=27554, stack(0x00007f6015cea000,0x00007f6015deb000)]
  0x00007f6024245000 JavaThread "grpc-executor-8" daemon [_thread_blocked, id=27553, stack(0x00007f6015feb000,0x00007f60160ec000)]
  0x00007f6024243000 JavaThread "grpc-executor-7" daemon [_thread_in_Java, id=27552, stack(0x00007f60160ec000,0x00007f60161ed000)]
  0x00007f6024241000 JavaThread "grpc-executor-6" daemon [_thread_blocked, id=27551, stack(0x00007f60161ed000,0x00007f60162ee000)]
  0x00007f6024214000 JavaThread "grpc-executor-5" daemon [_thread_blocked, id=27550, stack(0x00007f60162ee000,0x00007f60163ef000)]
=>0x00007f602420b000 JavaThread "grpc-executor-4" daemon [_thread_in_native, id=27549, stack(0x00007f60163ef000,0x00007f60164f0000)]
  0x00007f60241fe800 JavaThread "grpc-executor-2" daemon [_thread_blocked, id=27547, stack(0x00007f60165f1000,0x00007f60166f2000)]
  0x00007f60241fd000 JavaThread "grpc-executor-1" daemon [_thread_blocked, id=27546, stack(0x00007f60166f2000,0x00007f60167f3000)]
  0x00007f60241f8800 JavaThread "grpc-executor-0" daemon [_thread_blocked, id=27545, stack(0x00007f60167f3000,0x00007f60168f4000)]
  0x00007f6018023800 JavaThread "grpc-default-worker-ELG-3-1" daemon [_thread_in_native, id=27544, stack(0x00007f6016af5000,0x00007f6016bf6000)]
  0x00007f60b9eca000 JavaThread "grpc-default-boss-ELG-1-1" daemon [_thread_in_native, id=25051, stack(0x00007f60400ec000,0x00007f60401ed000)]
  0x00007f60b9d32800 JavaThread "Apollo-RemoteConfigLongPollService-1" daemon [_thread_in_native, id=25048, stack(0x00007f60407fd000,0x00007f60408fe000)]
  0x00007f60b9d30000 JavaThread "Apollo-RemoteConfigRepository-1" daemon [_thread_blocked, id=25047, stack(0x00007f60408fe000,0x00007f60409ff000)]
  0x00007f603400f800 JavaThread "threadDeathWatcher-2-1" daemon [_thread_blocked, id=25046, stack(0x00007f60409ff000,0x00007f6040b00000)]
  0x00007f60b9d1e800 JavaThread "Apollo-ConfigServiceLocator-1" daemon [_thread_blocked, id=25045, stack(0x00007f6040b00000,0x00007f6040c01000)]
  0x00007f60b9d19000 JavaThread "cat-StatusUpdateTask" daemon [_thread_blocked, id=25043, stack(0x00007f6040d02000,0x00007f6040e03000)]
  0x00007f60b9d0d000 JavaThread "cat-merge-atomic-task" daemon [_thread_blocked, id=25042, stack(0x00007f60593ba000,0x00007f60594bb000)]
  0x00007f60b9d0b000 JavaThread "cat-TcpSocketSender-ChannelManager" daemon [_thread_blocked, id=25041, stack(0x00007f60594bb000,0x00007f60595bc000)]
  0x00007f60b9d09800 JavaThread "cat-TcpSocketSender" daemon [_thread_blocked, id=25040, stack(0x00007f60595bc000,0x00007f60596bd000)]
  0x00007f60b9d07800 JavaThread "Thread-2" daemon [_thread_in_native, id=25039, stack(0x00007f6078020000,0x00007f6078121000)]
  0x00007f60b8cc7000 JavaThread "Service Thread" daemon [_thread_blocked, id=25031, stack(0x00007f60790f9000,0x00007f60791fa000)]
  0x00007f60b8cc4000 JavaThread "C1 CompilerThread2" daemon [_thread_blocked, id=25030, stack(0x00007f60791fb000,0x00007f60792fb000)]
  0x00007f60b8cc2000 JavaThread "C2 CompilerThread1" daemon [_thread_blocked, id=25029, stack(0x00007f60792fc000,0x00007f60793fc000)]
  0x00007f60b8cbf800 JavaThread "C2 CompilerThread0" daemon [_thread_blocked, id=25028, stack(0x00007f60793fd000,0x00007f60794fd000)]
  0x00007f60b8cbd800 JavaThread "Signal Dispatcher" daemon [_thread_blocked, id=25027, stack(0x00007f60794fd000,0x00007f60795fe000)]
  0x00007f60b8cbc000 JavaThread "Surrogate Locker Thread (Concurrent GC)" daemon [_thread_blocked, id=25026, stack(0x00007f60795fe000,0x00007f60796ff000)]
  0x00007f60b8c89000 JavaThread "Finalizer" daemon [_thread_blocked, id=25025, stack(0x00007f60796ff000,0x00007f6079800000)]
  0x00007f60b8c84000 JavaThread "Reference Handler" daemon [_thread_blocked, id=25024, stack(0x00007f60a803f000,0x00007f60a8140000)]
  0x00007f60b8012800 JavaThread "main" [_thread_blocked, id=24998, stack(0x00007f60c1976000,0x00007f60c1a76000)]

**Comment by saudet** [comment]
You'll need to make sure that `mat2` doesn't get deallocated before `bytePointer.get(data)` returns, possibly by calling a function like `deallocate()` on it or by using a `PointerScope`: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

**Comment by whalefa1I** [comment]
> You'll need to make sure that `mat2` doesn't get deallocated before `bytePointer.get(data)` returns, possibly by calling a function like `deallocate()` on it or by using a `PointerScope`: http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

so it sould be ? :
```
try (PointerScope scope = new PointerScope()) {
    BytePointer bytePointer = mat2.data();
}
```
so Mat isn't thread-safe?
and do you know the best way to put a Mat data into TensorProto.Builder?
thx for your reply!!!

**Comment by saudet** [comment]
If you use `PointerScope`, it needs to cover its creation at `Mat mat2 = new Mat();`.

`TensorProto.Builder` seems to accept `ByteBuffer`, so you should probably use that instead of copying everything to a `byte[]`.
