### ISSUE TITLE
Could not open Mobotix Stream when a timeout is set

### ISSUE THREAD

**Issue by rpgomes** [bytedeco/javacv#165]
Hello,

I having a strange behavior when testing to get the video Stream of a Mobotix camera, I'm using javaCV 0.11.
When I set a timeout I can't open the stream, the stream only open if I don't set the timeout parameter.

I verified this behavior with javaCV 0.11 and Java CV 0.11 in version 0.9 and 0.8 it works with the timeout. 

My code is the following:

grabber = new FFmpegFrameGrabber("http://IP//control/faststream.jpg?stream=mxg&fps=10");
grabber.setFormat("mxg");
grabber.setVideoOption("timeout", "5000000");
grab.start()

When the stream is open it timeout at 0, the following dump format appears:

nput #0, mxg, from 'http://IP/control/faststream.jpg?str
eam=mxg&fps=10':
 Duration: N/A, start: 1435231794.877011, bitrate: 64 kb/s
   Stream #0:0: Video: mxpeg, yuvj420p(pc, bt470bg), 1024x768, 50.08 tbr, 1000k
tbn, 1000k tbc
   Stream #0:1: Audio: pcm_alaw, 8000 Hz, mono, s16, 64 kb/s

the function av_strerror retruns the following error:
Error number -138 occurred

What can I do to set a timeout to this stream?

**Comment by saudet** [comment]
I don't know, that would something to ask the developers of FFmpeg I guess.

**Comment by rpgomes** [comment]
Wich version of FFmpeg are your project using for version 0.10 and 0.11?
This problem only happens whit that versions.
When I try it the latest build outside javacv it works.

**Comment by saudet** [comment]
So could try to build from the latest source? It will build with the latest version of FFmpeg.

**Comment by rpgomes** [comment]
OK.

Do you have some instructions to windows 32 bit to build the ffmpeg.jar and ffmpeg-windows-x86.jar.

**Comment by rpgomes** [comment]
Hi saudet, sorry for insisting, I never compiled something so complex (@least for me)

If I follow this instructions 
https://github.com/bytedeco/javacpp-presets/wiki/Create-New-Presets

I manage to build the ffmpeg.jar and ffmpeg-windows-x86.jar ?
If I understand what you said when I build the jar it already had the lattest ffmpeg version?
Where can I see the version of the FFMPEG that are in the javaCV builds?

**Comment by saudet** [comment]
Try to follow the instructions here:
https://github.com/bytedeco/javacpp-presets/blob/master/README.md#build-instructions

**Comment by rpgomes** [comment]
OK,

I will try to compile.
Meanwhile do you know at error -138 mean in avformat_open_input

**Comment by saudet** [comment]
Use the [av_strerror()](http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/javacpp/avutil.html#av_strerror-int-org.bytedeco.javacpp.BytePointer-long-) to get a description.

**Comment by rpgomes** [comment]
I try that 
I got this description:
Error number -138 occurred

**Comment by rpgomes** [comment]
I'm getting an error when running mvn install in javacpp project

I never done this, what could possibly be the problem?

Output:
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Not installing Nexus Staging features:
[INFO]  * Preexisting staging related goal bindings found in 1 modules.
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building JavaCPP 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ javacpp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 23 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3:compile (default-compile) @ javacpp ---
[INFO] Compiling 4 source files to C:\test\javacpp\target\classes
[INFO] 
[INFO] --- maven-plugin-plugin:3.2:descriptor (default-descriptor) @ javacpp ---
[INFO] Using 'UTF-8' encoding to read mojo metadata.
[INFO] Applying mojo extractor for language: java-annotations
[INFO] Mojo extractor for language: java-annotations found 0 mojo descriptors.
[INFO] Applying mojo extractor for language: java
[INFO] Mojo extractor for language: java found 1 mojo descriptors.
[INFO] Applying mojo extractor for language: bsh
[INFO] Mojo extractor for language: bsh found 0 mojo descriptors.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ javacpp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\test\javacpp\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3:testCompile (default-testCompile) @ javacpp ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ javacpp ---
[INFO] Surefire report directory: C:\test\javacpp\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.bytedeco.javacpp.IndexerTest
Generating C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\jniIndexerTest.cpp
Compiling C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniIndexerTest.dll
cl "/IC:\Program Files\Java\jdk1.6.0_45\include" "/IC:\Program Files\Java\jdk1.6.0_45\include\win32" C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\jniIndexerTest.cpp /W3 /Oi /O2 /EHsc /Gy /GL /MD /LD /link /OUT:C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniIndexerTest.dll 
jniIndexerTest.cpp
C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\jniIndexerTest.cpp(202) : warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Include\string.h(74) : see declaration of 'strcpy'
C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\jniIndexerTest.cpp(204) : warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\Include\string.h(157) : see declaration of 'strncpy'
C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\jniIndexerTest.cpp(954) : warning C4800: 'jboolean' : forcing value to bool 'true' or 'false' (performance warning)
Microsoft (R) Incremental Linker Version 9.00.21022.08
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:jniIndexerTest.dll 
/ltcg 
/dll 
/implib:jniIndexerTest.lib 
/OUT:C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniIndexerTest.dll 
jniIndexerTest.obj 
   Creating library jniIndexerTest.lib and object jniIndexerTest.exp
Generating code
Finished generating code
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.339 sec <<< FAILURE!
org.bytedeco.javacpp.IndexerTest  Time elapsed: 1.325 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: no jniIndexerTest in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1738)
	at java.lang.Runtime.loadLibrary0(Runtime.java:823)
	at java.lang.System.loadLibrary(System.java:1028)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:540)
	at org.bytedeco.javacpp.Loader.load(Loader.java:415)
	at org.bytedeco.javacpp.IndexerTest.setUpClass(IndexerTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.UnsatisfiedLinkError: C:\test\javacpp\target\test-classes\org\bytedeco\javacpp\windows-x86_64\jniIndexerTest.dll: %1 is not a valid Win32 application
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1807)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1703)
	at java.lang.Runtime.load0(Runtime.java:770)
	at java.lang.System.load(System.java:1003)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:529)
	... 23 more


Results :

Tests in error: 
  org.bytedeco.javacpp.IndexerTest: no jniIndexerTest in java.library.path

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.819 s
[INFO] Finished at: 2015-06-26T16:26:04+01:00
[INFO] Final Memory: 22M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project javacpp: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\test\javacpp\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by saudet** [comment]
It looks like you're trying to use a 32-bit compiler with a 64-bit JDK: This won't work. Please read the README.md file.

**Comment by rpgomes** [comment]
I finally manage to compile a new FFMPEG.jar and the ffmpeg-windows-x86.jar

With the function avformat_version returning 3679332 
I think is FFmpeg 2.7


I'm still getting the same behaviour, with the timeout parameter the stream does not open an return error -138 ( av_strerror() returns Error number -138 occurred)

If I use the FFMPEG.jar and the ffmpeg-windows-x86.jar in Javacv 0.8 release the stream opens.

What can I do to debug?

**Comment by saudet** [comment]
What happens when you use ffplay on the same URL?

**Comment by rpgomes** [comment]
OK, I find out my problem.

With your ffplay tip ;) I was setting the timeout in seconds, but this parameter is to be set in microseconds.

**Comment by saudet** [comment]
Ok, good, so I'm assuming everything works fine then? Thanks for the feedback!
