### ISSUE TITLE
 “grabber.start()“  is block 

### ISSUE THREAD

**Issue by 307509256** [bytedeco/javacv#1651]
if url is invalid stream address， “grabber.start()“  is block 

if url is rtsp： avformat_open_input() error -138
if url is rtmp： no log

I try to “grabber.setOption("stimeout", "10000000");“ rtsp  is effective
I try to “grabber.setOption("rw_timeout", "10000000");“ rtmp  is effective

why?

javacv version：1.5

**Comment by saudet** [comment]
Because the options depend on the protocol you use.
They are documented here: https://ffmpeg.org/ffmpeg-protocols.html

**Comment by 307509256** [comment]
when I use  "FFmpegFrameGrabber.createDefault(SOURCE_RTMP)"， block 
but I use "new FFmpegFrameGrabber(SOURCE_RTMP)"， no block
what is diffrent ?

**Comment by saudet** [comment]
You're using an old version of JavaCV. Please try again with JavaCV 1.5.5.
