### ISSUE TITLE
This pointer address is NULL.

### ISSUE THREAD

**Issue by demonlov** [bytedeco/javacv#1655]
Hello, I use javacv to process RTSP stream and push it to nginx. When the network of the device is unstable, this problem occurs in the re link,
Here's my code snippet
Discover the problem using the development tool idea's debug tool after the network reconnection

Avcodec.of_packet_The attribute deallocator of retpacket is NULL 
after the ref (retpacket, avpacket) method is executed
This property is normal during normal operation

                    grabber = createGrabber(workId, rtspUrl);
                    frameGrabberCache.setGrabber(grabber);
                    if (grabber != null) {

                        log.info("【" + workId + "】创建" + rtspUrl + ": grabber成功");
                    } else {
                        log.warn("【" + workId + "】创建" + rtspUrl + ": grabber失败");
                    }
                }
                // 将所有的rtsp拉流数据装入集合中
                try {
                    avPacket = startCameraPush(frameGrabberCache, java2DFrameConverter,avPacket);

                    if (!frameGrabberCache.getKeepLive()&&frameGrabberCache.getGrabber()!=null) {
                        break;
                    }
                    if (avPacket != null) {
                        // 将解析好的数据装入队列中
                        if (!MediaAssist.waitPullQueue.containsKey(workId)) {
                            MediaAssist.waitPullQueue.put(workId, new LinkedBlockingDeque<>());
                        }
                        AVPacket retPacket = avcodec.av_packet_alloc();
                        avcodec.av_packet_ref(retPacket, avPacket);
                        LinkedBlockingDeque<AVPacket> linkedBlockingDeque = MediaAssist.waitPullQueue.get(workId);
                        boolean offer = linkedBlockingDeque.offer(retPacket, 50, TimeUnit.MILLISECONDS);
                        avcodec.av_packet_unref(avPacket);

                        if (!offer) {
                            log.warn("本轮解析视频数据帧集合数据放入队列失败。。。");
                        }
                    }
                } catch (InterruptedException e) {
                    log.error("解析视频数据帧集合数据放入队列失败异常");
                    log.error("linkedBlockingDeque exception : ", e);
                }
            } catch (RuntimeException  e) {
                log.error("RuntimeException exception : ", e);
            }
        }

**Comment by saudet** [comment]
This sounds like a question about FFmpeg itself. You may want to ask upstream about this: https://ffmpeg.org/contact.html

**Comment by demonlov** [comment]
In addition, when I use avpacket, I can't set the resolution and code rate because it doesn't work

**Comment by demonlov** [comment]
> 这听起来像是一个关于 FFmpeg 本身的问题。您可能想就此向上游询问：[https](https://ffmpeg.org/contact.html) : [//ffmpeg.org/contact.html](https://ffmpeg.org/contact.html)

I'm very sorry to disturb your precious time, I've found a solution
After the recovery of network interruption, ffmpegframerecorder needs to be reinitialized, because I used it
recorder.start(AVFormatContext inputFormatContext); method Otherwise, there will be an exception
