### ISSUE TITLE
is it support srt protocol video stream ? 

### ISSUE THREAD

**Issue by DesenYang** [bytedeco/javacv#1660]
thanks for your contribute and help 👍  
as a newer to javacv , 
any one can tell me that this version of javacv support srt protocol ？

i have try to build ffmpeg with libsrt enable , but you know that it is real hard to build ffmpeg by source , ,(

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1035
