### ISSUE TITLE
ffmpeg issue in AWS M6g series ARM based Graviton processor

### ISSUE THREAD

**Issue by Zaiku1972** [bytedeco/javacv#1665]
Hi,

We are using javacv, javacpp, ffmpeg to capture the first frame of the video and making it as an image and using the image for thumbnail purpose.

However we recently migrated to M6G series in AWS EC2 which ARM based Graviton Processor. **Our code is working in windows 10 64 bit, Amazon linux T-series 64-bit processor.** 

But not working in M6G series in AWS EC2 which ARM based Graviton Processor.

```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.4.1</version>
        </dependency>
         <dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>1.4.1</version>
	</dependency>	
	<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>4.3.2-1.5.5</version>
        </dependency>
```

i have tried by adding **ffmpeg-platform**, adding classifier **linux-armhf**, added **JVM platform.dependencies**.

But none helped me. Anything i am missing?

I get the following error:  `Handler processing failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil`

![image](https://user-images.githubusercontent.com/14780594/123732724-f373cf00-d8b7-11eb-8ab6-7c721f120e9e.png)

An Image for your reference

**Comment by saudet** [comment]
Please use JavaCV 1.5.5, not 1.4.1.

**Comment by Zaiku1972** [comment]
![image](https://user-images.githubusercontent.com/14780594/123739601-8450a780-d8c4-11eb-8d98-1e9c673c180d.png)
 now im facing `Handler processing failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil`

**Comment by saudet** [comment]
Use javacv-platform, ffmpeg-platform, etc, just javacv won't work.

**Comment by Zaiku1972** [comment]
okay thanks, got it. issue got fixed

**Comment by Zaiku1972** [comment]
used javacv version which you suggested and added platform to both javacv and ffmpeg

**Comment by saudet** [comment]
BTW, there's more information about that here:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
