### ISSUE TITLE
frame.data is null in RealSense2FrameGrabber frame

### ISSUE THREAD

**Issue by developersnively** [bytedeco/javacv#1668]
Hello, I am trying to get the Bytebuffer from a frame using RealSense2FrameGrabber but frame.data is null.

final RealSense2FrameGrabber rs2;
        try {
            rs2 = new RealSense2FrameGrabber();
            for (RealSense2FrameGrabber.RealSense2DeviceInfo info : rs2.getDeviceInfos()) {
                System.out.printf("Device: %s %s %s Locked: %b\n",
                        info.getName(),
                        info.getFirmware(),
                        info.getSerialNumber(),
                        info.isLocked());
            }
            rs2.enableDepthStream(WIDTH, HEIGHT, FRAME_RATE);

          while (canvasFrame.isVisible())
            {

                rs2.trigger();
                Frame frame = rs2.grabDepth();

                ByteBuffer byteBuffer = frame.data;

                 grabbedImage = new Mat(HEIGHT, WIDTH, CvType.CV_16UC1);

                canvasFrame.showImage(new OpenCVFrameConverter.ToMat().convert(grabbedImage));
            }

            // close realsense camera
            rs2.stop();
            rs2.release();
            canvasFrame.dispose();

Do you have any hints on how to solve this?

Dev

**Comment by developersnively** [comment]
Thanks for the replay, I tried to use frame.image[0] but it is a shortBuffer. Anyway my goal is to convert the frame in a mat keeping the distance values to the intel. I tried with the OpenCVFrameConverter converter but I have a binary Mat in that case. How can I achieve my goal?
Dev

**Comment by saudet** [comment]
OpenCVFrameConverter works, what do you mean by "a binary Mat"?

/cc @cansik

**Comment by developersnively** [comment]
Hello, yes you are right it works, sorry for the waste of time.
