### ISSUE TITLE
Use FFmpegFrameRecorder to capture the video, the captured video cannot be dragged and played (there is sound but the picture is stuck)

### ISSUE THREAD

**Issue by leisure1211** [bytedeco/javacv#1669]
1.this is my code:
 FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(sourceFile);
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputFile, grabber.getAudioChannels());
        grabber.start();

        grabber.setTimestamp(startTime * 1000000L);

        Map<String, Object> filter = MapUtil.filter(BeanUtil.beanToMap(grabber),
                (Editor<Map.Entry<String, Object>>) stringObjectEntry ->
                        StrUtil.startWithAny(stringObjectEntry.getKey(),
                                "image", "audio", "video") && !stringObjectEntry.getKey().endsWith("Stream")
                                ? stringObjectEntry : null);
        BeanUtil.copyProperties(filter, recorder);

        recorder.start();

        Frame inFrame;
        boolean audioCompleted = false;
        boolean videoCompleted = false;
        while ((inFrame = grabber.grab()) != null) {
            if (inFrame.timestamp >=  endTime * 1000000L) {
                if (AVMEDIA_TYPE_VIDEO == inFrame.streamIndex) {
                    videoCompleted = true;
                } else if (AVMEDIA_TYPE_AUDIO == inFrame.streamIndex) {
                    audioCompleted = true;
                }
                if (audioCompleted && videoCompleted) {
                    break;
                }
            }
            recorder.record(inFrame);
        }

        grabber.close();
        recorder.close();
        return outputFile;
2.Here are some of the situations I analyzed:
    2.1、The capture video can be dragged and played in Google browser, Apple mobile phone, but cannot be dragged and played on the Android mobile phone and Android pad（Jump to the top of the video）
    2.2 、I tried all the setting parameters of this class of FFmpegFrameRecorder, but still cannot be dragged to play (there is sound but the picture is stuck)
    2.3 、Comparing the attributes of the video played normally, it is found that Duration_LastFrame: -7 ms. Is this caused by this?
    2.4、The format of the video is MP4
   
![image](https://user-images.githubusercontent.com/28395786/124866742-7949f580-dfef-11eb-82df-6b65ba72269c.png)

**Comment by saudet** [comment]
What is "outputFile"?

**Comment by leisure1211** [comment]
> What is "outputFile"?
I created a temporary file to receive the captured video

**Comment by saudet** [comment]
The MP4 format doesn't work well with InputStream and OutputStream, don't
use them.

**Comment by saudet** [comment]
If you're not using OutputStream, you'll need to provide me with a self-contained code snippet that I can run here to reproduce this. Otherwise, all I can say is that everything works fine here with JavaCV 1.5.5. I can't fix what isn't broken!

**Comment by leisure1211** [comment]
> If you're not using OutputStream, you'll need to provide me with a self-contained code snippet that I can run here to reproduce this. Otherwise, all I can say is that everything works fine here with JavaCV 1.5.5. I can't fix what isn't broken!

import cn.hutool.core.io.FileUtil;
import java.io.File;
import java.io.IOException;

public class FFMPEGUtilTest {

    @Test
    public void baseTest() throws IOException, InterruptedException {
    		// sourceFileUrl : http://reality-tutor-1251688289.cos.ap-chengdu.myqcloud.com/onlinerecord/gmntekgb8cctsl2u5g3c/c82d1aa35004a5f8b59efe916142c71a.mp4
    		// download the sourceFileUrl to my pc 
            File sourceFile = FileUtil.file("C:\\Users\\Joker\\Desktop\\c82d1aa35004a5f8b59efe916142c71a.mp4");
            // use the hutool createTempFile to receive the captured video 
            File outImgFile = FileUtil.createTempFile("cut", ".mp4", sourceFile.getParentFile(), false);

            FFMPEGUtil.cutVideo(sourceFile,outImgFile,30,670);

    }

public static File cutVideo(File sourceFile, File outputFile, long startTime, long endTime) throws FrameRecorder.Exception, FrameGrabber.Exception {

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(sourceFile);
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputFile, grabber.getAudioChannels());
        grabber.start();

        grabber.setTimestamp(startTime * 1000000L);

        Map<String, Object> filter = MapUtil.filter(BeanUtil.beanToMap(grabber),
                (Editor<Map.Entry<String, Object>>) stringObjectEntry ->
                        StrUtil.startWithAny(stringObjectEntry.getKey(),
                                "image", "audio", "video") && !stringObjectEntry.getKey().endsWith("Stream")
                                ? stringObjectEntry : null);
        BeanUtil.copyProperties(filter, recorder);

        recorder.start();

        Frame inFrame;
        boolean audioCompleted = false;
        boolean videoCompleted = false;
        while ((inFrame = grabber.grab()) != null) {
            if (inFrame.timestamp >=  endTime * 1000000L) {
                if (AVMEDIA_TYPE_VIDEO == inFrame.streamIndex) {
                    videoCompleted = true;
                } else if (AVMEDIA_TYPE_AUDIO == inFrame.streamIndex) {
                    audioCompleted = true;
                }
                if (audioCompleted && videoCompleted) {
                    break;
                }
            }
            recorder.record(inFrame);
        }

        grabber.close();
        recorder.close();
        return outputFile;
    }


}
By the way，I think there is probably a problem with the sourceFile, mabay javacv 1.5.5 can't handle such video files

**Comment by saudet** [comment]
The audio and video streams may end up with different lengths and that
could cause problems. You should make sure that isn't the cause of your
issue here.

BTW, this sounds like something more easily done with the ffmpeg program.
What's the reason why you're not using that instead?
