### ISSUE TITLE
Is there a way to only get the dependencies for these 6 platforms and not the others

### ISSUE THREAD

**Issue by Creeper121-newacc** [bytedeco/javacv#1672]
I've lately been trying out JavaCV but i don't want to compile a huge fat JAR so i've been trying to use the Maven exclusion tag to do this but it's not been working, i've tried using classifier for the 6 platforms but nope the 6 platforms are "windows-x86_64" "macosx-x86_64" "linux-x86_64" "windows-x86" "macosx-x86" "linux-x86"

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by saudet** [comment]
Duplicate of #1308
