### ISSUE TITLE
Version1.5.5 can not find libx264 encoder

### ISSUE THREAD

**Issue by freewings85** [bytedeco/javacv#1674]
I am using javacv under mac os, when  I update javacv from 1.5.3 to 1.5.5, i found libx264 encoder cannot be found, codes are below.
if ((video_codec = avcodec_find_encoder_by_name("libx264")) == null) {
	releaseUnsafe();
	throw new Exception("avcodec_find_encoder() error: Video codec not found.");
}
I need to use avcodec_find_encoder_by_name instead of avcodec_find_encoder because when I use avcodec_find_encoder(AV_CODEC_ID_H264), libopenh264 is returned, but I want libx264 codec
I can run the codes well when i use 1.5.3, I want know how can I fix this?

**Comment by saudet** [comment]
Since libx264 is GPL, you'll need to use artifacts with "-gpl" in their names.

**Comment by freewings85** [comment]
So glad you can answer me so quickly, should I change to avcodec_find_encoder_by_name("libx264-gpl"))?It seems the same error is returned

**Comment by saudet** [comment]
No, do like shown in the README.md file: https://github.com/bytedeco/javacv#sample-usage

**Comment by freewings85** [comment]
Please forgive my pool english, and thank you, it works now!
