### ISSUE TITLE
cv::solve

### ISSUE THREAD

**Issue by waizei** [bytedeco/javacv#1675]
What is the api ‘cv:solve‘ in opencv correspond to in JavaCV

**Comment by saudet** [comment]
We can use the one from OpenCV directly.

**Comment by waizei** [comment]
> We can use the one from OpenCV directly.

How to use opencv directly? Is it possible to call C++ code through JNI？

**Comment by saudet** [comment]
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/global/opencv_core.html#solve-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-int-

**Comment by saudet** [comment]
Let me know if you're having problems using that method!
