### ISSUE TITLE
How to compile the libjnijavacpp.so of ffmpeg replacing the ffmpeg in javacv

### ISSUE THREAD

**Issue by gitzjp** [bytedeco/javacv#1676]
I compiled the dynamic library of ffmpeg myself and don t know how to replace the static library of ffmpeg in javacv.
In the ubuntu environment I compiled libavcodec.so libavutil.so libavformat.so libavfilter.so etc.
Javacv in Java project I introduced via maven. See the org.bytedeco.javacpp. under the maven linux-x86_64linux-x86_64.libjnijavacpp.so is required to put the front. Is the so packaged as a libjnijavacpp.so to replace it?

**Comment by gitzjp** [comment]
I compiled the dynamic library of ffmpeg myself and don t know how to replace the static library of ffmpeg in javacv.
In the ubuntu environment I compiled libavcodec.so libavutil.so libavformat.so libavfilter.so etc.
Javacv in Java project I introduced via maven. See the org.bytedeco.javacpp. under the maven linux-x86_64linux-x86_64.libjnijavacpp.so is required to put the front. Is the so packaged as a libjnijavacpp.so to replace it?

**Comment by saudet** [comment]
It's not usually required, you can leave it out.

**Comment by saudet** [comment]
Please let me know if you encounter other issues though!

**Comment by gitzjp** [comment]
![28f8124023e5a4677c88e71f25998e00_](https://user-images.githubusercontent.com/49774677/129599136-a1eac8ca-adca-493f-a9ac-f0bf1609f8a9.png)
I downloaded the source for ffmpeg myself and I want to compile into a package like this.What should I do?

**Comment by gitzjp** [comment]
Because I need to use  hard decoding and is in the java environment I need to recompile.

**Comment by gitzjp** [comment]
> It's not usually required, you can leave it out.
Because I need to use hard decoding and is in the java environment I need to recompile.

**Comment by saudet** [comment]
To build from source, please try to follow the instructions here:
https://github.com/bytedeco/javacpp-presets#build-instructions
