### ISSUE TITLE
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -1: Could not open video codec

### ISSUE THREAD

**Issue by jeketos** [bytedeco/javacv#168]
Hello. I am trying merge audio (.wav) and video (.mp4) files. But I have some problem.
When I use next code, and trying just disassembled and assembled video file again, video file can not be played:
grabberVideo = new FFmpegFrameGrabber(videoFile);
grabberAudio = new FFmpegFrameGrabber(audioFile);
grabberVideo.start();
rabberAudio.start();
Loader.load(swresample.class); // googled somewhere, but it did not help
recorder = new FFmpegFrameRecorder(outFile,width,height,chanels);
recorder.setFormat("mp4");
recorder.start();
Frame frame1 = null;
while ((frame1 = grabberVideo.grabFrame()) != null) {
       recorder.record(frame1);
}

I add next code before  recorder.start():
    recorder.setFrameRate(grabberVideo.getFrameRate());
    recorder.setVideoCodec(13); //  or avcodec.AV_CODEC_ID_MPEG4
and have next log errors:
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -1: Could not open video codec.
at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:501)
at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:272)

**Comment by alicanalbayrak** [comment]
Hi, why did you closed this issue? Have you found the solution?

**Comment by abhirb1** [comment]
Any update here? I am facing same issue?

**Comment by saudet** [comment]
Does it still happen with version 1.0?

**Comment by abhirb1** [comment]
After i added recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264); 
I got it solved.
but conversion is too much time consuming on Android high end devices too, how can we make it faster with maintaining quality?

**Comment by saudet** [comment]
@abhirb1 We can use MediaRecorder from the Android API, which should use a hardware accelerator when available...
