### ISSUE TITLE
FFmpegFrameRecorder problems with setting video codec in 1.5.5 and 1.5.6

### ISSUE THREAD

**Issue by anotherche** [bytedeco/javacv#1681]
Switching to releases 1.5.5 or 1.5.6 caused various problems with starting recorder with some settings of video codecs. No such problems with releases <=1.5.4.

1. setting `recorder.setVideoCodec(AV_CODEC_ID_H265);`
causes an error after `recorder.start();`

`org.bytedeco.javacv.FFmpegFrameRecorder$Exception: avcodec_open2() error -1: Could not open video codec.`

others codecs work fine (those like AV_CODEC_ID_MPEG4, AV_CODEC_ID_H264, AV_CODEC_ID_MJPEG, V_CODEC_ID_HUFFYUV)
In all these cases following parameters are explicitly set before `recorder.start();`
format - appropriate string, depending on the codec: avi, mp4, mkv, mov
pixelFormat=AV_PIX_FMT_NONE 
frameRate - a double value like 25.0 or 30.0
videoBitrate - an integer value

2. when setting codec with `recorder.setVideoCodecName(vcodecName);` the requested codec name is ignored
whatever is specified as vcodecName - h264, libx264, h265, libx265, hevc - recorder always use the default AV_CODEC_ID_MPEG4.
Again, selecting the codec by its name works in 1.5.4 and earlier

**Comment by saudet** [comment]
Are you sure you're using JAR files with "-gpl" in their names?

**Comment by anotherche** [comment]
Oh, no! I didn't know.
Yes, it works with those -gpl jars.
But how to use all this staff correctly? I have now additional compatibility issue ((
The problem is that recently I wrote some code that allows to download all the necessary .jar dependencies for a given JavaCV version and a given set of components (such as ffmpeg, opencv, etc.). The code uses  maven-resolver package (the former org.eclipse.aether) that automatically detects the minimum set of dependencies and downloads them from the repository. However, I still cannot figure out how to see now that there are some additional (optional) dependencies, like these -gpl.
In addition, it is unclear whether it is necessary (or is it possible) to simultaneously have gpl and non-gpl files in one place?

**Comment by saudet** [comment]
Sure, you can have both sets of JARs in your class path. They are in different packages, so there's no reason why they would conflict. JavaCPP will load in priority the ones with an "extension" (in this case "-gpl") in priority, that's all.

**Comment by anotherche** [comment]
Thank you.

**Comment by saudet** [comment]
Duplicate of #1674
