### ISSUE TITLE
V1.5.6 Missing libx264

### ISSUE THREAD

**Issue by svorlauf** [bytedeco/javacv#1682]
V1.5.6 (release version)
Issue: ffmpeg cant find libx264
We use a processBuilder to call  ffmpeg retrieved by `Loader.load(org.bytedeco.ffmpeg.ffmpeg.class)` 
libx264 can not be used  since version 1.5.5  
ffmpeg -encoders is not listing it anymore
OS: Windows

**Comment by saudet** [comment]
Please make sure that you are using JAR files with "-gpl" in their names.

**Comment by svorlauf** [comment]
Thank you. That was our porblem. I saw the gpl related entry in the changlog but did not fully understand it

**Comment by svorlauf** [comment]
I also just found the javacpp gradle plugin to filter natives jars

**Comment by saudet** [comment]
Duplicate of #1674
