### ISSUE TITLE
Could not open input (mp4)

### ISSUE THREAD

**Issue by Enquisidor** [bytedeco/javacv#1683]
Asking here because I can't seem to find much information after lots of Googling. LMK if this is better asked over at SO.

I am looking into JavaCV (specifically the FFmpeg module) for transcoding mp4 to HLS within a Scala backend. I am running the exact code found at [the following issue from 2017](https://github.com/bytedeco/javacv/issues/660) because it's the best example code I can find for my use case 

The error I'm getting is as follows: 
`avformat_open_input() error -2: Could not open input "/path/to/file.mp4". (Has setFormat() been called?) (For more details, make sure FFmpegLogCallback.set() has been called.)`

I have tried adding both `setFormat` and `FFmpegLogCallback.set` with no luck and am not sure what else to do. The sample video I'm using was downloaded directly from TikTok as an mp4.

I appreciate any support I can get with this issue,
Thanks

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.6.

**Comment by Enquisidor** [comment]
Thanks for the quick reply. Don't know why I was on 1.5.5, but upgrading to 1.5.6 gave me the same result. Here is the relevant section of my `build.sbt` if it's any help

`lazy val platform = "macosx-x86_64"

libraryDependencies ++= Seq(
  "org.bytedeco" % "javacpp" % "1.5.6" classifier platform,
  "org.bytedeco" % "javacv" % "1.5.6",
  "org.bytedeco" % "ffmpeg" % "4.4-1.5.6" classifier "",
  "org.bytedeco" % "ffmpeg" % "4.4-1.5.6" classifier platform
)`

**Comment by saudet** [comment]
If you're trying to do something with HLS, that's probably not going to
work...

**Comment by Enquisidor** [comment]
What aspect of it won't work? Is mp4 -> HLS not working in this repo or should I be using an entirely different example/procedure?

**Comment by saudet** [comment]
I don't know, a lot of people seem to be having problems with it: https://github.com/bytedeco/javacv/search?q=hls&type=issues

BTW, if you can provide more information, it would help diagnose this. What's the error message that you're getting in the log?

**Comment by yangjiheng** [comment]
Tried the code, it's running OK on my mac-air. Only difference been I'm not using maven's JavaCV code,
1. downloaded directly from GitHub's build version 2.5.6
2. Delete maven downloaded bytedeco repo
3. imported the unpacked directory to the project directly

I think library dependency issue is a nightmare in JavaCV, all my tests are done with pre-built libraries and turning out fine most of the time. You should probably give it a shot.


    public static void main(String[] args) {
        try {
            File videoFile = new File("/Users/jihengyang/projects/projects/packages/ffmpeg-4.2.2/stream0.mp4");
            FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(videoFile);

            String name = videoFile.getName().split("\\.")[0];
            File file = new File(Paths.get(videoFile.getParentFile().getPath(), name).toString());
            file.mkdir();
            frameGrabber.start();
            Frame grab;
            FrameRecorder recorder = new FFmpegFrameRecorder(new File(file.getPath() + "/" + name + "index" + ".m3u8"), frameGrabber.getImageWidth(), frameGrabber.getImageHeight(), frameGrabber.getAudioChannels());
            recorder.setAspectRatio(frameGrabber.getAspectRatio());
            recorder.setFrameRate(frameGrabber.getFrameRate());
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
            recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
            recorder.setOption("vf", "setdar=16:9");
            recorder.setOption("hls_time", "3");
            recorder.setOption("start_number", "0");
            recorder.setOption("hls_list_size", "0");
            recorder.setOption("f", "hls");
            recorder.setOption("level", "3.0");
            recorder.setOption("profile:v", "baseline");
            recorder.setOption("strict", "experimental");
            recorder.start();
            while ((grab = frameGrabber.grab()) != null) {
                recorder.record(grab);
            }
            recorder.stop();
            recorder.release();
            frameGrabber.stop();
        } catch (FrameGrabber.Exception | FrameRecorder.Exception ignored) {
            System.out.println(ignored.getMessage());
        }
    }

**Comment by saudet** [comment]
> I think library dependency issue is a nightmare in JavaCV, all my tests are done with pre-built libraries and turning out fine most of the time. You should probably give it a shot.

It's easy with the Platform Plugin of Gradle JavaCPP: 
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by Enquisidor** [comment]
Thanks @yangjiheng but that is a bit too low level for what we are looking for in my project.

@saudet I tried that too but was having issues. Turns out we will basically be running the same command every time with different files so we are going with a command line based solution

**Comment by saudet** [comment]
BTW, it's also easy to execute the ffmpeg program with JavaCPP:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
