### ISSUE TITLE
Blocking Hibernate

### ISSUE THREAD

**Issue by yavuzbalik** [bytedeco/javacv#1685]
1.5.x versions are blocking Hibernate dependencies. there is not ffmpeg.global.avcodec file in 1.4.x. thus can't take audio from video file. 1.4.x not blocking hibernate.

**Comment by saudet** [comment]
JavaCV 1.4.x and 1.5.x are not compatible, so please upgrade everything to 1.5.x.

**Comment by yavuzbalik** [comment]
I'm using 1.5.6 and getting org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path.

**Comment by saudet** [comment]
I have no idea what that means.

**Comment by guilherme-alves-silve** [comment]
This is an error from Spring web framework trying to configure the hibernate orm, It has nothing to do with JavaCV.

**Comment by saudet** [comment]
> This is an error from Spring web framework trying to configure the hibernate orm, It has nothing to do with JavaCV.

Is there something though in JavaCV that's making Spring's life difficult? Or is this pretty normal for Spring?

**Comment by guilherme-alves-silve** [comment]
> 

This is normal for Spring. There's baeldung tutorial teaching How to solve this. For example, this tutorial can help him:

https://www.baeldung.com/hibernate-5-spring
