### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.opencv.dnn.Dnn.readNetFromCaffe_0(Ljava/lang/String;Ljava/lang/String;)J

### ISSUE THREAD

**Issue by liming1010** [bytedeco/javacv#1687]
` Net net = Dnn.readNetFromCaffe(
                "conf/deploy.prototxt",
                "conf/237_2_150x150_tpyface.caffemodel"
        );`

`Exception in thread "main" java.lang.UnsatisfiedLinkError: org.opencv.dnn.Dnn.readNetFromCaffe_0(Ljava/lang/String;Ljava/lang/String;)J
	at org.opencv.dnn.Dnn.readNetFromCaffe_0(Native Method)
	at org.opencv.dnn.Dnn.readNetFromCaffe(Dnn.java:119)`

**Comment by liming1010** [comment]
`<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.6</version>
        </dependency>`

**Comment by saudet** [comment]
The following sample code works fine for me. Could you give that one a try?
https://github.com/bytedeco/javacv/blob/master/samples/CaffeGooglenet.java

**Comment by saudet** [comment]
> `<dependency> <groupId>org.bytedeco</groupId> <artifactId>javacv</artifactId> <version>1.5.6</version> </dependency>`

You'll need to use "javacv-platform", not just "javacv".
