### ISSUE TITLE
How does Mat load images from the network。

### ISSUE THREAD

**Issue by wonderfulLand** [bytedeco/javacv#1688]
How does Mat load images from the network。

**Comment by wonderfulLand** [comment]
Mat back= opencv_imgcodecs.imread("C:\\Users\\John\\Desktop\\1.jpeg");

i want to load image in url.

**Comment by saudet** [comment]
Among other things, we can use FFmpegFrameGrabber that, see issue https://github.com/bytedeco/javacv/issues/1628.

**Comment by saudet** [comment]
Duplicate of #1628
