### ISSUE TITLE
How can javacv open the camera in Android？

### ISSUE THREAD

**Issue by liming1010** [bytedeco/javacv#1692]
hello, I'm an Android Developer， I'm going to use javacv for live broadcast processing， How can javacv open the camera in Android？
In opencv for Android, it is implements camerabridgeviewbase.cvcameraviewlistener2

**Comment by saudet** [comment]
There are currently no "AndroidFrameGrabber", but we can already capture video from Java in that case, for example:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by saudet** [comment]
It looks like FFmpeg supports the Android Camera API now:
https://www.ffmpeg.org/ffmpeg-devices.html#android_005fcamera

So this kind of code should work:
```java
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("");
grabber.setFormat("android_camera");
grabber.start();
```
Please let me know if that doesn't work though! Thanks

**Comment by kshitijgarg2609** [comment]
@saudet  It is giving the exception, Here is the screenshot

![image](https://user-images.githubusercontent.com/48625716/143404412-487c4ba2-d63f-454d-9569-6acb2b0a3297.png)

**Comment by saudet** [comment]
What is the content of the exception? And what does FFmpeg prints out to the log?

**Comment by kshitijgarg2609** [comment]
I/System.out: org.bytedeco.javacv.FFmpegFrameGrabber$Exception: av_find_input_format() error: Could not find input format "android_camera". (For more details, make sure FFmpegLogCallback.set() has been called.)
I/System.out:     at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:880)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:846)
        at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:841)
        at com.example.javacv8test.MainActivity$1.run(MainActivity.java:86)

**Comment by saudet** [comment]
Could you also provide the information that you get when FFmpegLogCallback.set() has been called?

**Comment by saudet** [comment]
I see what the problem is. The Android Camera API that OpenCV and FFmpeg support was introduced first in Android 7.0. Since about 90% of users have Android 7.0 or newer these days, I guess it makes sense to upgrade the minimum requirements. I've done that in commit https://github.com/bytedeco/javacpp-presets/commit/cd288306ebad1139bee53c027b676137478716a4, so it should now work with both FFmpegFrameGrabber and OpenCVFrameGrabber, which just uses VideoCapture. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by kshitijgarg2609** [comment]
I have extracted jar files, do we have to keep include folder which contains .hpp files? Should I send mail you the whole code with file structure?

**Comment by saudet** [comment]
What do you mean? JAR files for snapshots are the same as for releases. Do the same thing as you're used to do.

**Comment by kshitijgarg2609** [comment]
I mean, there are jar file files like ffmpeg, openblas, opencv, javacv and javacpp, I have copied in lib folder where as jar files containing .so files of android platform, I have extracted .so files and copied inside jniLibs folder.

**Comment by kshitijgarg2609** [comment]
I am sharing my android code folder https://drive.google.com/drive/folders/1N3zgCLJD3DOjV_lW_V8COuxMdgahmPc4?usp=sharing. Please do check

**Comment by saudet** [comment]
If you're looking for a working sample project, you can use this one here:
https://github.com/bytedeco/sample-projects/tree/master/JavaCV-android-example

**Comment by kshitijgarg2609** [comment]
@saudet I have already seen this example in which deprecated android.hardware.camera is used. My ques is why can't we use VideoCapture on camera if bytedeco ffmpeg supports android. Please help me out it would be great help. Bytedeco projects really works on desktop amazingly and the project is really really amazing.

**Comment by saudet** [comment]
Yes, VideoCapture should also work now with the snapshots. Please let me
know if it doesn't work though.

**Comment by kshitijgarg2609** [comment]
VideoCapture.open function always returns false

**Comment by saudet** [comment]
Ok, please try FFmpegFrameGrabber instead. It's usually better than OpenCV for video capture anyway.

**Comment by kshitijgarg2609** [comment]
Tried but failed

**Comment by saudet** [comment]
What is the error message that you get in the log?

**Comment by kshitijgarg2609** [comment]
I am getting exception

**Comment by saudet** [comment]
What is the message of that exception?

**Comment by saudet** [comment]
This should be working now with JavaCV 1.5.7, but please let me know if you're still not able to get this working. Thanks!

**Comment by saudet** [comment]
Note: There is a known bug in JavaCV 1.5.7 that prevents this from working smoothly, see issue #1756. We can work around it by calling `FFmpegFrameGrabber.tryLoad()` before anything else.
