### ISSUE TITLE
What if the javacv package used in Android is too large?

### ISSUE THREAD

**Issue by liming1010** [bytedeco/javacv#1699]
`
implementation group: 'org.bytedeco', name: 'javacv-platform', version: '1.5.6'
`

The APK generated by javacv is 600m, which is too large. There are many dependencies on other platforms in the APK. What should I do

**Comment by saudet** [comment]
Please refer to https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
and the Platform Plugin from Gradle JavaCPP: https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by saudet** [comment]
Duplicate of #1308
