### ISSUE TITLE
FFmpegFrameGrabber frame skipping

### ISSUE THREAD

**Issue by chengpengvb** [bytedeco/javacv#1706]
For FFmpegFrameGrabber, setFrameRate is invalid. When grabImage is still decoding, this method can be optimized.

**Comment by chengpengvb** [comment]
> 它并不总是无效的。例如，设置相机的帧速率可能是有效的。

It can be controlled only in the program, instead of modifying the parameters of the camera

**Comment by saudet** [comment]
Duplicate of #1121
