### ISSUE TITLE
The sources contains the function setAspectRatio(), but the build (maven) does not have that

### ISSUE THREAD

**Issue by gouravd** [bytedeco/javacv#171]
I am looking for setting the AspectRatio independent of the surfaceview. Found the required change was pulled in. But the maven repo (even the binary archive  javacv-0.11-bin.zip) does not have that.

**Comment by saudet** [comment]
No, it isn't yet. Making complete builds isn't a simple task, so I am looking for someone to take on the task of getting CI up and running for us. Would you like to take a look into that? It would help a lot.

**Comment by gouravd** [comment]
Sure, as long as I know how to do it. :)

**Comment by saudet** [comment]
Well, try stuff out at https://travis-ci.org/ and let me know if it looks like fun! :) Thanks

**Comment by gouravd** [comment]
Sure, thanks. It will take some time to complete, but I will start working on it. In the meanwhile if someone else does it, I will still be happy coz I got to learn travis.

**Comment by saudet** [comment]
Great! Let me know that goes! Thanks a lot
