### ISSUE TITLE
Javacv memory usage problem

### ISSUE THREAD

**Issue by demonlov** [bytedeco/javacv#1715]
Hello, the javacv version I use is 1.5.3. When the program is running, the memory keeps rising until it takes up all the memory.

**Comment by demonlov** [comment]
I started two threads. One thread is responsible for obtaining camera data and putting it into the linkedblockingqueue, and the other thread is used for consumption

**Comment by demonlov** [comment]
With the running time of the program, the memory is occupied more and more. The memory will not be released until it is killed

**Comment by saudet** [comment]
Please try to deallocate explicitly objects you don't need anymore by calling close() on them.

**Comment by demonlov** [comment]
FFmpegFrameGrabber grabber=....        
if (grabber != null) {
                Frame frame = grabber.grabImage();
                if (frame != null || frame.image != null) {
                    log.info("discard is not empty packet");
                    BufferedImage bufferedImage = java2DFrameConverter.getBufferedImage(frame);
                    if (count.get() == 1) {
		do something                                       
}

       


                    return    bufferedImage             }
                log.info("frame is NULL....");

            }

**Comment by demonlov** [comment]
> 请尝试通过对它们调用 close() 来明确释放不再需要的对象。


            if (grabber != null) {
                Frame frame = grabber.grabImage();
                if (frame != null || frame.image != null) {
                    log.info("discard is not empty packet");
                    BufferedImage bufferedImage = java2DFrameConverter.getBufferedImage(frame);
                    if (count.get() == 1) {
                    do something ...
                    }

                    return  bufferedImage;
                }
                log.info("frame IS NULL....");

            }

**Comment by demonlov** [comment]
byte[] bgr = null;
                        int imageWidth = frame.imageWidth;
                        int imageHeight = frame.imageHeight;
                        ByteBuffer buffer = (ByteBuffer) frame.image[0];
                        if (buffer != null) {
                            buffer.rewind();
                                bgr = new byte[buffer.limit()];
                                buffer.get(bgr);
                             }

**Comment by demonlov** [comment]
> Please try to deallocate explicitly objects you don't need anymore by calling close() on them.

I hope to get some help

**Comment by saudet** [comment]
It just sounds like you're trying to store too many BufferedImage objects in memory. In that case, simply reduce the number of images you are holding in memory.
