### ISSUE TITLE
Consider to add a parameter for specifying the charset of FFmpegFrameGrabber::getMetadata()?

### ISSUE THREAD

**Issue by Konyaco** [bytedeco/javacv#1718]
Some system versions use other charset by default (e.g: GBK for Windows-Simplified-Chinese), but media file saves metadata with UTF-8 charset.
If I encode the parsed String with default charset, then decode it with UTF-8, I will lost last few bytes.
![image](https://user-images.githubusercontent.com/17498623/141688913-28b386b6-69dd-40d3-b17e-aa62fd7fb6cd.png)

**Comment by saudet** [comment]
Sure, it should be pretty easy to add a `FFmpegFrameGrabber.getMetadata(Charset)` overload that calls `BytePointer.getString(Charset)` here:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L576
Could you give that a try and if it works, please a pull request with your changes! Thanks

**Comment by saudet** [comment]
Thanks again for your fix! It's been released with JavaCV 1.5.7.
