### ISSUE TITLE
Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [../lib] MAC

### ISSUE THREAD

**Issue by lixiaojun0226** [bytedeco/javacv#1721]
Hi expert,
i'm using FFmpegFrameGrabber to grabber video frame, but i got error when 
```Java
            FFmpegFrameGrabber fFmpegFrameGrabber = new FFmpegFrameGrabber(videoFile.getAbsolutePath());
            fFmpegFrameGrabber.start();
```
when i debug into FFmpegFrameGrabber.class, it throw error in Loader.load(avutil.java)
```java
 public static void tryLoad() throws Exception {
        if (loadingException != null) {
            throw loadingException;
        } else {
            try {
                Loader.load(avutil.class);
                Loader.load(swresample.class);
                Loader.load(avcodec.class);
                Loader.load(avformat.class);
                Loader.load(swscale.class);
                avcodec.av_jni_set_java_vm(Loader.getJavaVM(), (Pointer)null);
                avcodec.avcodec_register_all();
                avformat.av_register_all();
                avformat.avformat_network_init();
                Loader.load(avdevice.class);
                avdevice.avdevice_register_all();
            } catch (Throwable var1) {
                if (var1 instanceof Exception) {
                    throw loadingException = (Exception)var1;
                } else {
                    throw loadingException = new Exception("Failed to load " + FFmpegFrameGrabber.class, var1);
                }
            }
        }
    }
```
the error is: Could not initialize class org.bytedeco.ffmpeg.global.avutil,
and also has warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [../lib]

my pom.xml:
```xml
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.5.4</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp</artifactId>
			<version>1.5.4</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>1.5.4</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg-platform</artifactId>
			<version>4.3.1-1.5.4</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>4.3.1-1.5.4</version>
		</dependency>
```

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.6.

**Comment by lixiaojun0226** [comment]
same issue with 1.5.6:
pom:
```java
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.5.6</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp</artifactId>
			<version>1.5.6</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>1.5.6</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg-platform</artifactId>
			<version>4.4-1.5.6</version>
		</dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>4.4-1.5.6</version>
		</dependency>
```

**Comment by lixiaojun0226** [comment]
still throw error: Could not initialize class org.bytedeco.ffmpeg.global.avutil, 
but be happy that: no Warning for Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [../lib]

**Comment by saudet** [comment]
Please provide the debug messages as well, for example, by setting the "org.bytedeco.javacpp.logger.debug" to "true" to have them displayed on your console.

**Comment by lixiaojun0226** [comment]
how to set org.bytedeco.javacpp.logger.debug, i'm using ant project.

**Comment by saudet** [comment]
Usually we can set them on the command line this with -D, but we can just set them in Java as well.
Please refer to the tutorial: https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html
Ant isn't going to work with Maven artifacts anyway, please use Maven.

**Comment by lixiaojun0226** [comment]
why you close it. this issue is not solved. :(

**Comment by saudet** [comment]
What is the issue exactly? What do you get if you run the Demo class with
Maven?

**Comment by saudet** [comment]
If you're having the same problem with Maven though, please let me know!

**Comment by lixiaojun0226** [comment]
Hi i debugger into the FFmpegFrameGrabber class, i got this:
![image](https://user-images.githubusercontent.com/10444859/142794751-12e18b1d-d95d-4c3b-ac8d-ae92f019a97e.png)
![image](https://user-images.githubusercontent.com/10444859/142795471-820c3f31-1626-4688-8218-82a30a11f235.png)

my platform is macosx-x86_64, but the javacpp.class only handle windows, is this the root cause? did i miss some dependency,

**Comment by saudet** [comment]
Like I said, start by setting the "org.bytedeco.javacpp.logger.debug" system property to "true". That will output some more information on the console.

**Comment by lixiaojun0226** [comment]
![image](https://user-images.githubusercontent.com/10444859/142808665-bb97f386-82a0-404d-b1d8-2a3df5b78bf4.png)

**Comment by saudet** [comment]
What are you trying to do? Are looking into modifying the source code of JavaCV?

**Comment by lixiaojun0226** [comment]
no, i'm trying to grab the frame from a video.
```java
package test;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.Java2DFrameConverter;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.util.*;
import java.util.List;

/**
 * @Author KeXin
 * @Date 2021/2/1 下午3:07
 **/
public class test {
        public static List<String> fetchPicFromVideo(String fileUrl, Integer stepSecond, Integer count) throws Exception {
            List<String> picBase64List = new ArrayList<>();
            stepSecond = stepSecond == null ? 1200 : stepSecond;

            FFmpegFrameGrabber ff = new FFmpegFrameGrabber(fileUrl);
            ff.start();
            long timeLength = ff.getLengthInTime();
            Frame frame = ff.grabImage();
            long startTime = frame.timestamp;
            long timestamp = 0;
            int second = 0;
            int picNum = 0;
            while (timestamp <= timeLength) {
                timestamp = startTime + second * 1000000L;
                ff.setTimestamp(timestamp);
                frame = ff.grabImage();
                if (frame != null) {
                    if (frame.image != null) {
                        //picBase64List.add(getBase64FromFrame(frame));
                        picNum++;
                        if (count != null && picNum == count) {
                            break;
                        }
                    }
                }
                second += stepSecond;
            }
            ff.stop();
            return picBase64List;
        }


        public static void main(String[] args) {
            try {
                String outputPath = "/Users/i326618/Downloads/video_for_test";
                String videoPath = "/Users/i326618/Downloads/video_for_test/sample_1280x720.mp4";
                List<String> files = fetchPicFromVideo(videoPath, 600, 8);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

}

this is my demo, this is not completely code, but the debug will throw error when new FFmpegFrameGrabber
```

**Comment by lixiaojun0226** [comment]
the jar was download, and it was at my classpath 
![image](https://user-images.githubusercontent.com/10444859/142819805-4f092bd8-6189-4d24-9b75-8cc865b1062c.png)

**Comment by saudet** [comment]
You're missing some JAR files in your class path. Pleas add **all** the JAR files to your class path.

**Comment by lixiaojun0226** [comment]
what is that mean? which jar did i miss, or how to add all JAR files?

**Comment by saudet** [comment]
Please tell me which JARs you have in your class path. I should be able to tell you which ones are missing.

**Comment by lixiaojun0226** [comment]
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>4.4-1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>4.4-1.5.6</version>
        </dependency>

this is all my dependency.

**Comment by saudet** [comment]
If you are using Maven, you do not need to add any JAR files manually to your class path. Please remove all the JAR files you added manually to your class path.

**Comment by lixiaojun0226** [comment]
yes, it will download automatically, but still have same issue.

**Comment by saudet** [comment]
Ok, so please provide more details about how you're trying to run your code.

**Comment by lixiaojun0226** [comment]
i have no more details to upload.
1. my code has been uploaded,
2. pom.xml has been uploaded, 
3. debug info after setting the "org.bytedeco.javacpp.logger.debug" system property to "true" also been uploaded.

what i run is very easy, grabber a frame from a video which exist in my computer.

**Comment by saudet** [comment]
If you're just trying to run come demo code, first try to run it with a simple `mvn clean compile exec:java`.

**Comment by lixiaojun0226** [comment]
i figure out the issue after i manually add 3 macosx-x86_64 related jars.
![image](https://user-images.githubusercontent.com/10444859/142963623-18d882dd-1b72-4f38-8225-97465c1ef711.png)
now it can initially the FFmpegFrameGrabber class.

if using pom it will not import this three 3 macosx-x86_64 related jars

**Comment by lixiaojun0226** [comment]
on my local .m2 it download all the dependencies, including all operating system jars. but it not add it to my classpath automatically.

**Comment by lixiaojun0226** [comment]
so my question is how to add this dependency at pom?

**Comment by lixiaojun0226** [comment]
could it possible like 
```java
		<dependency>
			<groupId>ws.schild</groupId>
			<artifactId>jave-**nativebin-linux64**</artifactId>
			<version>3.1.1</version>
		</dependency>

		<dependency>
			<groupId>ws.schild</groupId>
			<artifactId>jave-**nativebin-win64**</artifactId>
			<version>3.1.1</version>
		</dependency>

		<dependency>
			<groupId>ws.schild</groupId>
			<artifactId>jave-**nativebin-osx64**</artifactId>
			<version>3.1.1</version>
		</dependency>
```

**Comment by saudet** [comment]
Just add javacv-platform as dependency, it will bring everything you need.
If that doesn't work, then that's a bug with IntelliJ IDEA, so please
report upstream!

**Comment by lixiaojun0226** [comment]
any possible that let me explicit declare the javacpp-1.5.6-macosx-x86_64.jar?

**Comment by saudet** [comment]
Sure, you can do that if you want.

**Comment by lixiaojun0226** [comment]
but it can not download because no ffmpeg-macosx-x86_64.4.4-1.5.6.jar can be found in central repository.

**Comment by saudet** [comment]
Then go search for the correct coordinates.

**Comment by saudet** [comment]
As per the README.md file, they are all listed here: https://search.maven.org/search?q=bytedeco
