### ISSUE TITLE
how to implements setpts filter

### ISSUE THREAD

**Issue by LodyWang** [bytedeco/javacv#1724]
**i just want to Increase video playback speed by 4 times**
**my code below：**

> grabber = FFmpegFrameGrabber.createDefault(videoPath);
> grabber.start();
> recorder = new FFmpegFrameRecorder("cop"+startTimeStamp+".mp4",grabber.getImageWidth(),grabber.getImageHeight(),grabber.getAudioChannels());
> 			recorder.setFormat("mp4");
> 			recorder.start();
> 			String vf = "setpts=0.25*PTS";
> 			FFmpegFrameFilter filter = new FFmpegFrameFilter(vf,grabber.getImageWidth(),grabber.getImageHeight());
> 			filter.start();
>                         Frame frame = null;
> 			
> 			while((frame = grabber.grabFrame())!=null) {
> 				filter.push(frame,grabber.getPixelFormat());
> 				frame = filter.pullImage();
> 				recorder.record(frame,grabber.getPixelFormat());
> 			}

but it's not work!
what should i do?

**Comment by saudet** [comment]
Hum, I wonder if this has something to do with the mandatory setpts filter added in FFmpegFrameFilter:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameFilter.java#L351
Could you try to remove that one and see what happens?

**Comment by saudet** [comment]
No, the first `setpts` is on the input, so the second one should override it. However, you'll definitely need to call something like `recorder.setTimestamp(frame.timestamp)` before `recorder.record(frame)`, but let me know if it doesn't work!

**Comment by boenhh** [comment]
> **i just want to Increase video playback speed by 4 times** **my code below：**
> 
> > grabber = FFmpegFrameGrabber.createDefault(videoPath);
> > grabber.start();
> > recorder = new FFmpegFrameRecorder("cop"+startTimeStamp+".mp4",grabber.getImageWidth(),grabber.getImageHeight(),grabber.getAudioChannels());
> > recorder.setFormat("mp4");
> > recorder.start();
> > String vf = "setpts=0.25*PTS";
> > FFmpegFrameFilter filter = new FFmpegFrameFilter(vf,grabber.getImageWidth(),grabber.getImageHeight());
> > filter.start();
> > Frame frame = null;
> > ```
> >   	while((frame = grabber.grabFrame())!=null) {
> >   		filter.push(frame,grabber.getPixelFormat());
> >   		frame = filter.pullImage();
> >   		recorder.record(frame,grabber.getPixelFormat());
> >   	}
> > ```
> 
> but it's not work! what should i do?

I had the same problem ,can you tell me how to resolve this problem ?

**Comment by boenhh** [comment]
> 

i just want to Increase video playback speed by 4 times
but it's not work
can you give me any sample?thanks
