### ISSUE TITLE
FFmpegFrameFilter.pull() gives null frame

### ISSUE THREAD

**Issue by rajib-brain-craft** [bytedeco/javacv#1727]
Working filter: "setpts=N,split[s0][s1];[s0]palettegen=stats_mode=single[p];[s1][p]paletteuse=dither=none:diff_mode=rectangle"
Not working filter: "setpts=N,split[s0][s1];[s0]palettegen=stats_mode=diff[p];[s1][p]paletteuse=dither=none:diff_mode=rectangle"
First filter is working but second filter is not working. The only change is stats_mode=diff.

**Comment by saudet** [comment]
That shouldn't be a problem, just skip them if you don't need them?

**Comment by rajib-brain-craft** [comment]
I have updated the description. Please read and give solution.

**Comment by saudet** [comment]
Did you try to call `push(null)` before calling `pull()`?

**Comment by rajib-brain-craft** [comment]
Yeah this works. Thanks.

**Comment by saudet** [comment]
Duplicate of #287
