### ISSUE TITLE
How to set loop count to gif encoding in FFmpegFrameRecorder

### ISSUE THREAD

**Issue by rajib-brain-craft** [bytedeco/javacv#1728]

**Comment by saudet** [comment]
You already asked those questions in issue #1726. I won't be able to help more unless you provide more information.

**Comment by saudet** [comment]
According to the docs at https://ffmpeg.org/ffmpeg-formats.html#gif-2, something like calling `FFmpegFrameRecorder.setOptions("loop", "10")` before calling `start()` should work. Have you tried that?
