### ISSUE TITLE
How to get Frame Type( I、P、B）by JavaCV

### ISSUE THREAD

**Issue by steeveen** [bytedeco/javacv#1729]
Frame frame=ffmpegGrameGrabber.grabFrame(false,true,true,false,false)；
But all frame.opaque.pict_type()==AV_PICTURE_TYPE_NONE

**Comment by saudet** [comment]
It's not currently copied, but it shouldn't be too hard to fetch that information around this line:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L1402
Contributions are welcome!

**Comment by steeveen** [comment]
I’m not very familiar with its code.... It seems that I should add an attribute like  pictType in Frame Class? and then assign picture.pict_type() to it?

**Comment by saudet** [comment]
Sounds reasonable, yes.

**Comment by steeveen** [comment]
OK， I will have a try

**Comment by steeveen** [comment]
I am adding pictType to Frame class. And adding pkt_dts, pts to it at the same time. which I think it might be useful.
But I met some problem when testing it. Idea tell me some class in the source code doesn't exist. Such as FLYCAPTURE_OK,FlyCaptureInfoEx
I think this maybe caused by maven? or by pulling mistaken branch?(I made the change on master)
Can you give me some help?
Or I can just PR the commit to this repo?After all these changes are very simple

![image](https://user-images.githubusercontent.com/14873464/145402201-542657bc-8047-4b72-aa53-f2da04a6fe0f.png)

**Comment by saudet** [comment]
That file shouldn't get compiled, you can ignore it.

I don't think we should expose dts and pts. AFAIK that's only useful for *packets*, not frames, right?

In any case, a reference to the original AVFrame is in Frame.opaque, so you could access it that way in your code without modifying JavaCV, if that's OK with you?

**Comment by steeveen** [comment]
Yes. Frame.opaque is a good way to access the unused attributes.
But my motivation for adding them is that I find frame.opaque.pts always return Long.MIN_VALUE. As opaque.pkt_dts returning Long.MIN_VALUE. frame.opaque.pict_type returning 0.
Haven't you encountered this problem?

**Comment by saudet** [comment]
Ah, yes, you're right, those fields are not getting set in that `AVFrame`. I've added a call to `av_frame_copy_props()` in commit https://github.com/bytedeco/javacv/commit/33bea56a4cde12021da949cdbeb84b9c51885fa3, that should do it. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by steeveen** [comment]
Hi,saudet.
I have commited the change. [https://github.com/bytedeco/javacv/pull/1730](url)
You can have a look at the PR.
