### ISSUE TITLE
How to record and stream a video simultaneously ? 

### ISSUE THREAD

**Issue by vipulpurohit** [bytedeco/javacv#173]
Hello,
I'm successfully streaming video over RTMP server using JavaCV. I'm wondering if I can record video on SD Card and stream the video at the same time.

Right now I'm using "RecorderActivity" example to stream video on RTMP server.

**Comment by saudet** [comment]
Sure, why not? Does it crash or something when you try?

**Comment by vipulpurohit** [comment]
Actually I don't know what is the correct way to implement recording and streaming at same time using single instance of "FFmpegFrameRecorder".

What I'm doing is creating two different instance of "FFmpegFrameRecorder" one for streaming and one for recording. The difference between these two instance is only the link. The streaming instance have the RTMP link and recording instance have local storage link. 

Its working but it dramatically reduce streaming and recording performance and quality. The video look like as it was streamed at 15 FPS same happen with recorded video. The video quality also suffer.

I think my approach is not correct.

**Comment by saudet** [comment]
We would have to separate the encoding process from the streaming process inside FFmpegFrameRecorder. Other people have expressed an interest in that too: #93 #117 Would you like try and implement this functionality? It would be very much welcome :)

**Comment by vipulpurohit** [comment]
Thanks for your response.
Yes sure, Once I achieve the required functionality I'll publish my work. :)

**Comment by saudet** [comment]
Merging into #93

**Comment by wangpeng1** [comment]
@vipulpurohit  can you solve the problem?
