### ISSUE TITLE
start() was not called successfully!

### ISSUE THREAD

**Issue by mohitsuppal** [bytedeco/javacv#1731]
System.err: Info: Output #0, flv, to 'myfilepath/stream.flv':
 W/System.err: Info:   Metadata:
 W/System.err: Info:     encoder         : 
 W/System.err: Info: Lavf58.76.100
 W/System.err: Info: 
 W/System.err: Info:   Stream #0:0
 W/System.err: Info: : Video: flv1 ([2][0][0][0] / 0x0002), yuv420p, 1200x1600, q=2-31, 400 kb/s
W/System.err: Info: , 
W/System.err: Info: 30 fps, 
 W/System.err: Info: 1k tbn, 
 W/System.err: Info: 30 tbc
 W/System.err: Info: 
 W/System.err: Info:   Stream #0:1
W/System.err: Info: : Audio: aac (LC) ([10][0][0][0] / 0x000A), 44100 Hz, mono, fltp, 64 kb/s
W/System.err: Info: 

System.err: org.bytedeco.javacv.FFmpegFrameFilter$Exception: start() was not called successfully! (For more details, make sure FFmpegLogCallback.set() has been called.)
 W/System.err:     at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:532)
 W/System.err:     at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:525)
W/System.err:     at org.bytedeco.javacv.FFmpegFrameFilter.push(FFmpegFrameFilter.java:522)
 W/System.err:     at 
 W/System.err:     at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1529)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
 W/System.err:     at android.os.Looper.loop(Looper.java:257)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8104)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by saudet** [comment]
It doesn't look like anything is wrong. Please provide the code that you are using.

**Comment by mohitsuppal** [comment]
Which start() is the log talking about

**Comment by saudet** [comment]
FFmpegFrameFilter.start(), did you call it? It
won't work if you don't call it.

**Comment by mohitsuppal** [comment]
public void startRecording() {

    initRecorder();

    try {

      // The filterString  is any ffmpeg filter.
      // Here is the link for a list: https://ffmpeg.org/ffmpeg-filters.html
      filterString = "drawtext=fontfile=/system/fonts/DroidSans-Bold.ttf:text=Car not detected:fontsize=15:fontcolor=white :box=1: boxcolor=red:x=(w-text_w)/2:y=((h-text_h)-15)";
      filter = new FFmpegFrameFilter(filterString, imageWidth, imageHeight);

      //default format on android
      filter.setPixelFormat(avutil.AV_PIX_FMT_NV21);

      recorder.start();
      startTime = System.currentTimeMillis();
      recording = true;
      audioThread.start();
      if (addFilter) {
        filter.start();
      }
    } catch (FFmpegFrameRecorder.Exception | FrameFilter.Exception e) {
      e.printStackTrace();
    }
  }

**Comment by mohitsuppal** [comment]
if (addFilter) {
    filter.start();
  }

I am calling the start method here.....

**Comment by saudet** [comment]
Not when addFilter is false...

**Comment by mohitsuppal** [comment]
addFilter is true always right?

**Comment by mohitsuppal** [comment]
Ok, my issue is resolved , is there any filter which gives padding to drawtext filter.

**Comment by saudet** [comment]
The drawtext filter has a lot of options, so there's probably one of those that does what you need:
https://ffmpeg.org/ffmpeg-filters.html#drawtext-1
