### ISSUE TITLE
process crashed when from video to capture audio frame 

### ISSUE THREAD

**Issue by m5jun** [bytedeco/javacv#1735]
![image](https://user-images.githubusercontent.com/1648064/148006001-4d97780d-a58c-4fc3-b47f-3c0ac1ace880.png)

**Comment by m5jun** [comment]
when recorder.start() execute, process crashed.

**Comment by saudet** [comment]
There's probably some unsupported parameter values in there. If you're not seeing anything on the console, make sure that `FFmpegLogCallback.set()` has been called to get more information in the log.

**Comment by m5jun** [comment]
how to sure FFmpegLogCallback.set() has been called ? there is no document to said. @saudet

**Comment by saudet** [comment]
Just call it yourself before anything else!

**Comment by m5jun** [comment]
there is java has_err_pid20.log，but can't why java process  crash.  @saudet 

![image](https://user-images.githubusercontent.com/1648064/148011186-c5af765d-0bc1-406f-a007-82a6e1c80536.png)

**Comment by saudet** [comment]
It's not crashing on start(), it's crashing on close(). Are you sure you're calling record() at least once? There might be some bug in there that occurs when no frames have been recorded...

**Comment by m5jun** [comment]
this is about ffmpeg code totally: @saudet 
![image](https://user-images.githubusercontent.com/1648064/148013453-379de376-ad61-485d-8817-2ff57032cce9.png)

**Comment by saudet** [comment]
Instead of calling `grabSamples()` and `recordSamples()`, could you try to call `grab()` and `record()`?

**Comment by saudet** [comment]
Also, please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
It looks like you're trying to record in mp4 format to an OutputStream, which the mp4 format doesn't support well.
Please try to either use another format or record to a file.
