### ISSUE TITLE
Unsatisfiedlinkerror on native library load

### ISSUE THREAD

**Issue by oguzd** [bytedeco/javacv#1737]
Hi,

First of all, I have to admit that I'm using a pretty old version of javacv however the issue is strange and interesting enough to be asked here. I'm using javaccv version 0.8 via maven. Project loads and runs on my windows 10 computer with no issue but I'm getting Unsatisfiedlinkerror on the load of jniavcodec.dll file. Both computers are identical in terms of windows version, C++ and .NET runtimes, and JDK version.

When I trace the execution of the application on both computers separately, I noticed that System.loadLibrary() for some of the dll's work just fine except one dll, which fails strangely. Same call works just fine on the other computer. 

Not sure what would be the cause of that problem. 

I appreciate any insight!
Thanks

**Comment by saudet** [comment]
It's probably because some of those Windows machines are missing Media Foundation. Make sure that's installed everywhere or the FFmpeg builds that come with JavaCV may not work indeed.

Other than that, please upgrade to JavaCV 1.5.6!

**Comment by saudet** [comment]
But if you would like to debug this further, please let me know what the Dependencies tool says is missing:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by oguzd** [comment]
Thanks Samuel. I'll check the Media Foundation installation.

I actually took it a bit further;
I managed to pull the sources of javacpp repo and compile it on my local by changing the java.io.tmpdir usage in the Loader class. I used the same directory path instead of creating a new folder with system nano seconds. Then I've uploaded all the dll's required (13 of them) but the result is not changed.  Java System.loadLibrary still fails even though all the required dll files are in the java.library path.

I'll give it a try to Media Foundation installation then try the link you've shared above that doesn't work.

**Comment by oguzd** [comment]
It seems the issue was the missing msvcr100.dll file in the System32 folder. MS C++ 2010 runtime is no longer officially supported and probably not included in new Windows 10 distributions. Everything worked fine after installing that dll from my computer(I couldn't even find the right installer for the runtime in Microsoft's website).
I don't know how I've had that dll on my computer :)

Thank you very much for your help!
