### ISSUE TITLE
Substitute for FFmpegFrameRecorder's record(IplImage)

### ISSUE THREAD

**Issue by marwfair** [bytedeco/javacv#174]
I just updated and it seems that FFmpegFrameRecorder's record(IplImage) has been removed. Is there a replacement for this?

I was creating an IplImage from a jpg:
opencv_core.IplImage iplimage = cvLoadImage("my_image.jpg");

Then recording the image:
ffmpegFrameRecorder.record(iplimage)

but the record method is not found.

Any help would be appreciated! Thanks!

**Comment by saudet** [comment]
Of course, use `OpenCVFrameConverter`. It's all explained here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by marwfair** [comment]
Great! Thank you so much!
