### ISSUE TITLE
How can I use `org.bytedeco.opencv.opencv_core.Mat` to achieve exactly the same input and output as `org.opencv.core.Mat#get(int, int)`?

### ISSUE THREAD

**Issue by dragon-zhang** [bytedeco/javacv#1740]
How can I use `org.bytedeco.opencv.opencv_core.Mat` to achieve exactly the same input and output as `org.opencv.core.Mat#get(int, int)`?

**Comment by saudet** [comment]
We can used indexers for that: http://bytedeco.org/news/2014/12/23/third-release/

**Comment by dragon-zhang** [comment]
Thanks a lot ,it works fine for me : )
