### ISSUE TITLE
Resource release about Frame

### ISSUE THREAD

**Issue by steeveen** [bytedeco/javacv#1742]
Hello. I have run my code with javaCV several weeks. My target is just grab some frames and analysis. But recentlly the code usually run into OOM.  Some of them happened during frameCoped=frame.copy()；
I confirm that the memory allocated to JVM is enough.I'm confused why  it happened. Should I release the frameCoped explicitly everytime It is useless? call frameCoped.close()?

Look forward to your reply

**Comment by saudet** [comment]
Yes, you should free them explicitly as much as possible to avoid situations like that.

**Comment by steeveen** [comment]
How about the GC on some resource in JavaCV? 
I see many developers code like this:
```
while((frame=grabber.grab())!=null){
/*do something*/
}
```
Can GC recycle the old frame object in heap automatically when frame reference is pointed to a new frame object?
or all of these should code like as:
```
while(frame=grabber.grab()){
/*do something*/
frame.close();
}
```
?

**Comment by saudet** [comment]
That Frame is owned by FFmpegFrameGrabber. You'll need to stop it one to deallocate that frame.

**Comment by steeveen** [comment]
Got it. Thank you

**Comment by steeveen** [comment]
Hi, I have read the source code of FFmpegFrameGrabber partly. 
All of resource are released in `releaseUnsafe` method. I find `samples_frames` and `picture`/`picture_rgb` are both released by `av_frame_free`. But the `frame` obj is just set to null. 
Frame extends from  Autocloseable. According to that, should `frame.close()` be called in releaseUnsafe() before set `frame` to `null`? Or frame release operation should be controller by the user/client?

Looking forward to your anwser

**Comment by saudet** [comment]
We could call Frame.close(), but it doesn't own any native memory anyway, so it wouldn't do anything.

Could you explain exactly what isn't working?

**Comment by saudet** [comment]
We could call Frame.close(), but it doesn't own any native memory anyway, so it wouldn't do anything.

Could you explain exactly what isn't working?

**Comment by steeveen** [comment]
Not exactlly. I just refactor my code to reduce the risk of OOM.

**Comment by saudet** [comment]
If you want to be sure, you can still call close() on everything that is AutoCloseable, that's fine.

**Comment by saudet** [comment]
If you're dealing with Pointer objects directly, that's what PointerScope is for:
http://bytedeco.org/news/2018/07/17/bytedeco-as-distribution/

Pointer objects that don't own any allocated memory won't have a deallocator.
