### ISSUE TITLE
【help】How to convert mjpeg stream to h264 stream in real time?

### ISSUE THREAD

**Issue by ZhouYixun** [bytedeco/javacv#1744]
I try to use FFmpegFrameGrabber. 
```
public static void from() throws IOException {
        Socket socket = new Socket("localhost",8999);
        grabber = new FFmpegFrameGrabber(socket.getInputStream(),0);
        grabber.setOption("stimeout", "10000000");
        grabber.start();
        System.out.println("something");
    }
```
localhost:8999 is mjpeg stream.
But stuck in start().

What should I do?

mjpeg stream is Content-type: image/jpg

**Comment by saudet** [comment]
If you don't see anything on the console, make sure that FFmpegLogCallback.set() has been called.

**Comment by ZhouYixun** [comment]
> If you don't see anything on the console, make sure that FFmpegLogCallback.set() has been called.

I'm sorry. I don't know how to use FFmpegLogCallback.set().

```
public static void from() throws IOException {
        Socket socket = new Socket("localhost",8999);
        FFmpegLogCallback.set();
        grabber = new FFmpegFrameGrabber(socket.getInputStream(),0);
        grabber.setOption("stimeout", "10000000");
        grabber.start();
        System.out.println("something");
    }
```
I still can't see anything on the console

**Comment by ZhouYixun** [comment]
stuck in start().

**Comment by saudet** [comment]
Are you use multiple threads? Try to call startUnsafe() instead of start().

**Comment by ZhouYixun** [comment]
> Are you using multiple threads? Try to call startUnsafe() instead of start().

no，form() is main method

**Comment by saudet** [comment]
Since you know you have mjpeg, setFormat("mjpeg") before start().

**Comment by ZhouYixun** [comment]
> Since you know you have mjpeg, setFormat("mjpeg") before start().

okay, I try it tonight, thx!

**Comment by ZhouYixun** [comment]
Still stuck in start(). I am trying to find logs

**Comment by ZhouYixun** [comment]
I have a mjpeg stream , I just want to transfer to h264 and output in real time.( Sorry, My English is too bad )

**Comment by steeveen** [comment]
I think this may be caused by no data in your socket stream.
If you want to get effective help. You can add one line before your code:
```
FFmpegLogCallback.set()
```
the report will tell you something.

**Comment by saudet** [comment]
I'm not sure I understand what you're trying to do, but if the ffmpeg program does what you need, we can easily use it from Java:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
