### ISSUE TITLE
[Help] How can I make hls stream from webcam video (or other video stream).

### ISSUE THREAD

**Issue by Grednoud** [bytedeco/javacv#1745]
I'm trying to make an HLS stream from an input video stream from a webcam. I expect the recorder to create an index.m3u8 file and .ts chunks as frames are saved. But the files are created only after the recorder is closed. 
 Why is this happening? Can you suggest the best way to do this?

Sample scala code to reproduce:
```
import org.bytedeco.javacv._

object Test extends App {
  val grabber = FrameGrabber.createDefault(0)
  grabber.start()
  val recorder = FFmpegFrameRecorder.createDefault("index.m3u8", grabber.getImageWidth(), grabber.getImageHeight())
  recorder.setFormat("hls")
  recorder.setOption("hls_list_size", "4")
  recorder.setOption("hls_time", "5")
  recorder.start()

  for (_ <- 1 to 500) {
    recorder.record(grabber.grab())
  }

  grabber.close()
  recorder.close()

}
```
Thank you for your advice.

**Comment by saudet** [comment]
I guess that format doesn't support streaming. If you need good streaming support, try another format like matroska (mkv).

**Comment by Grednoud** [comment]
> I guess that format doesn't support streaming. If you need good streaming support, try another format like matroska (mkv).

HLS - HTTP Live Striming, it's good for streaming.  When I use ffmpeg directly, the conversion happens quite correctly. 

`.\ffmpeg.exe -y -f vfwcap -r 25 -i 0 -f hls -hls_time 5 -segment_time 5 -hls_list_size 5 index.m3u8`

**Comment by saudet** [comment]
Ok, so you could use the ffmpeg program if it does everything you need. It's quite easy to use it from Java:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by Grednoud** [comment]
> Ok, so you could use the ffmpeg program if it does everything you need. It's quite easy to use it from Java:
> http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

Thanks for the advice.
I try like in the example:
```
val ffmpeg = Loader.load(classOf[org.bytedeco.ffmpeg.ffmpeg])
val pb = new ProcessBuilder(ffmpeg, "-y", "-f", "vfwcap", "-r", "25", "-i", "0", "-f", "hls", "-hls_time", "10", "-hls_delete_threshold", "3", "./index.m3u8")
pb.inheritIO().start().waitFor()
```
In this case, I get nothing in the output, only increasing the memory consumption. My guess is that something is being buffered, but no output files are being created.

**Comment by Grednoud** [comment]
Is there a difference between calling ffmpeg in the console and through the ProcessBuilder?  In the first case, I get a continuous stream of conversion, in the second I see only a growing amount of buffered data.  Is it possible to somehow reduce the buffer or force the data to be saved via flush()?

**Comment by saudet** [comment]
There is no difference. Maybe the bundled version is missing a feature or something. If you know which one it is, we can enable it.

**Comment by Grednoud** [comment]
The problem seems to be the different behavior of ffmpeg 4.4 which comes with java and ffmpeg 5 installed in my path.

**Comment by saudet** [comment]
FFmpeg 5.0 is available in the snapshots: http://bytedeco.org/builds/

**Comment by Grednoud** [comment]
> FFmpeg 5.0 is available in the snapshots: http://bytedeco.org/builds/

Thanks for the help. But why does ffmpeg 5 shipped with javacv, like 4.4, only buffer but not create files in case of hls? Unlike the official release of ffmpeg. 
Official release
![image](https://user-images.githubusercontent.com/20754069/151511976-189244db-7456-4f06-b51c-e95725f55802.png)
ffmpeg 5 shipped with javacv
![image](https://user-images.githubusercontent.com/20754069/151512265-8cc8522f-d332-4a1d-953c-1c22e5c81613.png)

**Comment by saudet** [comment]
You're using libx264. If you want to use libx264 with JavaCV as well, you need to add a dependency on ffmpeg-platform-gpl as shown in the README.md file: https://github.com/bytedeco/javacv/#sample-usage

**Comment by Grednoud** [comment]
Many thanks. This solved the problem.

> You're using libx264. If you want to use libx264 with JavaCV as well, you need to add a dependency on ffmpeg-platform-gpl as shown in the README.md file: https://github.com/bytedeco/javacv/#sample-usage
