### ISSUE TITLE
FFmpegFrameGrabber.grabKeyFrame() doesn't extract all IFrames

### ISSUE THREAD

**Issue by aakkawi** [bytedeco/javacv#175]
Hi,

grapKeyFrame() in the FFmpegFrameGrabber doesn't return all Iframes as the FFMPEG command line tools. 

I checked also previous version of javacv and the same problem. 

In mytest, grapKeyFrame() found 88 Iframes where as FFMPEG  tool returns 100 I Frames.

The following command used to extract the IFRames from a video:

FFMPEG.EXE -i "XX.mp4" -vf "select='eq(pict_type,I)'" -vsync vfr  \tmp\iframes\BFrame\frame%4d.jpg

Is it a bug, or there is something else? 

FFMPEG --version
ffmpeg version 1.2
built on Apr  1 2013 20:31:13 with gcc 4.7.0 (GCC)

**Comment by saudet** [comment]
Maybe it's a bug, maybe FFmpeg considers "key frames" != "I-frames". Did you notice anything in common about the I-frames missing from the set of key frames that could help diagnose this? Also, could you ask the FFmpeg developers if there is a difference between key frames and I-frames? And exactly what that difference is, if there is one?Thanks!

**Comment by saudet** [comment]
Have you figured out anything about the difference between "key frames" and "I-frames"?

**Comment by saudet** [comment]
Issue #875 is very similar, so I'll just mark this issue as a duplicate.
