### ISSUE TITLE
How can i get correct pixel format from image

### ISSUE THREAD

**Issue by GreenhairTurtle** [bytedeco/javacv#1752]
For now, i use FFmpegFrameGrabber to decode gif
```java
        FrameGrabber gifGrabber = new FFmpegFrameGrabber("test.gif");
//        gifGrabber.setPixelFormat(AV_PIX_FMT_BGRA);
        try {
            gifGrabber.start();
        } catch (FFmpegFrameGrabber.Exception e) {
            e.printStackTrace();
        }

        System.out.println(gifGrabber.getPixelFormat());
```
it print 3 which is AV_PIX_FMT_BGR24

but the ffmpeg(may be) output is: 
> Input #0, gif, from 'test.gif':<br>Duration: 00:00:00.96, start: 0.000000, bitrate: 611 kb/s<br>Stream #0:0: Video: gif, bgra, 300x254, 12.50 fps, 12.50 tbr, 100 tbn

the correct pixel format is bgra

My question is: how can i get the correct bgra pixel format ?

I think it might be a simple thing, I just can't find the right way for now.

Thank you

**Comment by saudet** [comment]
Uncomment the call to setPixelFormat() and it will do that

**Comment by GreenhairTurtle** [comment]
Yeah, i know.
I mean is it possible to get the correct pixel format by default, just as ffmpeg output ?

**Comment by saudet** [comment]
If we call setImageMode(RAW), the image data remains in whatever format returned by the decoder.
I guess that is what you're looking for?

**Comment by GreenhairTurtle** [comment]
Well, i will try it.

Thank you for your patience.

**Comment by saudet** [comment]
Let me know if that doesn't work though, in which case it's probably a bug that I'll need to fix. Thanks!

**Comment by GreenhairTurtle** [comment]
> Let me know if that doesn't work though, in which case it's probably a bug that I'll need to fix. Thanks!

When i call setImageMode(RAW), getPixelFormat() return correct value.

Thank you.
