### ISSUE TITLE
video h264 can not seek

### ISSUE THREAD

**Issue by nguyenvancuongit** [bytedeco/javacv#176]
hi,
i meet a strange issue, i've recorded h264 video format by:
- javacv 11
- my setting for recorder:
        recorder = new FFmpegFrameRecorder(ffmpeg_link, w, h, 1);
        recorder.setFormat("mp4");
        recorder.setSampleRate(sampleAudioRateInHz);

        recorder.setFrameRate(30);

        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setVideoQuality(12);
        recorder.setVideoOption("preset", "ultrafast");

(The most is same as RecordActivity.java)

Problem is:
- video out put can not seek: i play video by any Media Player app, when seek to n second position, it's alway go back to 00:00 and play from start
- video output i can not trim with mp4parser, default camera is worked, what's the different?

thanks for any answer
@saudet thanks for take a look here

**Comment by saudet** [comment]
Have you made sure to call `recorder.stop()` at the end?

What happens when you try with the default settings?

BTW, it works fine here with the latest code, so maybe it's a bug in FFmpeg, and it got fixed...

**Comment by saudet** [comment]
So, please try again with version 1.0! Thank you

**Comment by nguyenvancuongit** [comment]
as i checked, problem come from recorder.setVideoQuality
i'll try with 1.0 and let you result, thanks you

**Comment by saudet** [comment]
You need to make sure that stop() gets called at the end of the recording.
Does it get called?

**Comment by nguyenvancuongit** [comment]
i update jar file on lib forder and it's work now, thanks you so much
