### ISSUE TITLE
how to reduce the jar size

### ISSUE THREAD

**Issue by muyline** [bytedeco/javacv#1761]
When import the opencv and ffmpeg, the package size increse to 700Mb from 100Mb，how to reduce the size

**Comment by muyline** [comment]
just mvn clean package -Djavacpp.platform=linux-x86_64

**Comment by saudet** [comment]
There's a few ways we can go about this, please refer to this wiki page:
https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
