### ISSUE TITLE
Build FFmpeg with libfreetype

### ISSUE THREAD

**Issue by alicera** [bytedeco/javacv#1763]
Follow the [issue](https://github.com/bytedeco/javacv/issues/254)

Follow the [installation](https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/#compiling-for-windows ) and add --enable-libfreetype.
I use --extra-cflags and --extra-ldflags to assign the path of libfreetype.
But meet the error ERROR: freetype2 not found using pkg-config and it try to use `pkg-config` to find freetype2 .pc file not `--extra-cflags` and `--extra-ldflags`

[freetype](https://github.com/ubawurinna/freetype-windows-binaries/releases)

**Comment by saudet** [comment]
FreeType gets linked by default now, no need to do anything special.

**Comment by alicera** [comment]
> FreeType gets linked by default now, no need to do anything special.

FreeType is not the default for me. Because I install freetype by downloading the  [freetype-windows-binaries](https://github.com/ubawurinna/freetype-windows-binaries/releases), I don't have any *.pc or other default for freetype.

Due to install freetype by downloading the freetype-windows-binaries, I use --extra-cflags and --extra-ldflags to assign the path of freetype-windows-binaries. 

So I meet the error ERROR: freetype2 not found using pkg-config and it try to use pkg-config to find freetype2 .pc file not --extra-cflags and --extra-ldflags

**Comment by saudet** [comment]
I don't understand what you're trying to do, but it doesn't like something related to JavaCPP or JavaCV...
