### ISSUE TITLE
 FFmpegFrameGrabber is not starting. It got stucked and not giving any exception.

### ISSUE THREAD

**Issue by sumit33** [bytedeco/javacv#1768]
This is my code (mac) `...`

`

            grabber = new FFmpegFrameGrabber("Capture screen 0:none");
            grabber.setFormat("avfoundation");
            grabber.setOption("-capture_cursor", "1");
            grabber.setPixelFormat(AV_PIX_FMT_YUYV422);
            System.out.println("Before");
            grabber.start();
            System.out.println("After");
`
In my console, "Before" is printing but not printing "After". Please Help

**Comment by saudet** [comment]
You'll need to call start().

**Comment by sumit33** [comment]
@saudet Thanks for your reply and sorry for the typing mistake..I actually called start()..

**Comment by saudet** [comment]
According to the docs at https://trac.ffmpeg.org/wiki/Capture/Desktop something like this should work:
```java
  FrameGrabber grabber = new FFmpegFrameGrabber("1");
  grabber.setFormat("avfoundation");
  grabber.setFrameRate(30);
  grabber.start();
```

**Comment by saudet** [comment]
Duplicate of #1756
