### ISSUE TITLE
Can't use vp8 in my javafx application.

### ISSUE THREAD

**Issue by sumit33** [bytedeco/javacv#1769]
I used h264 encoding before that worked fine. But now I want to use vp8 or vp9..I just call "libvpx" library..but it shows error..

` av_guess_format() error: Could not guess output format for "" and vp8 format.`

This is my code.

        grabber = new FFmpegFrameGrabber("desktop");
        grabber.setFormat("gdigrab");
        grabber.setImageWidth((int) rectangleFullScreen.getWidth());
        grabber.setImageHeight((int) rectangleFullScreen.getHeight());
        grabber.setPixelFormat(AV_PIX_FMT_YUV420P);
        grabberPixelFormat = grabber.getPixelFormat();
        grabber.setVideoCodec(AV_CODEC_ID_VP8);

        recorder = new FFmpegFrameRecorder(recorderOutput, roi.width, roi.height, 0);
        recorder.setFrameRate(fps);
        recorder.setFormat("vp8");
        recorder.setVideoCodecName("libvpx");
        recorder.setVideoOption("profile", "baseline");
        recorder.setVideoOption("tune", "zerolatency");
        recorder.setVideoOption("preset", "ultrafast");
        recorder.setVideoOption("maxrate", String.valueOf(1024 * 1024 * maxrateMbits));
        recorder.setVideoOption("bufsize", String.valueOf(1024 * 1024 * maxrateMbits));
        recorder.setVideoOption("crf", String.valueOf(crf));
        recorder.setVideoOption("g", String.valueOf(fps * 10));

        grabber.start();
        recorder.start();

**Comment by saudet** [comment]
I don't think "vp8" is a valid format name. Please check the docs.

**Comment by sumit33** [comment]
@saudet Sorry for the late update. I found out my problem. The jar I used for my application is not enabled with "libvpx" and also facing problems to enabled it. How can I enable "libvpx" in the jar on windows? Or can I get any jar where "libvpx" is already enabled? I'm totally new in this field. Please Help.

**Comment by saudet** [comment]
Please upgrade to JavaCV 1.5.7.

**Comment by sumit33** [comment]
@saudet solved. The problem is for setting the wrong preset and tune for libvpx. Now it's working. What I get after doing that is an encoded byte buffer. How to decode it for saving and playing?

**Comment by saudet** [comment]
You can save to a file, and read back with FFmpegFrameGrabber.
