### ISSUE TITLE
ClassCastException: java.nio.DirectByteBuffer cannot be cast to java.nio.IntBuffer

### ISSUE THREAD

**Issue by sarxos** [bytedeco/javacv#177]
Hi @bytedeco team,

Just FYI, I experienced described exception when doing:

```java
File vfile = new File("/dev/video0");
FrameGrabber grabber = FrameGrabber.createDefault(vfile);
Frame frame = grabber.grab();
BufferedImage bi = new BufferedImage(frame.imageWidth, frame.imageHeight, BufferedImage.TYPE_INT_RGB);
Java2DFrameConverter.copy(frame, bi);
```

The stack trace is:

```plain
Caused by: java.lang.ClassCastException: java.nio.DirectByteBuffer cannot be cast to java.nio.IntBuffer
	at org.bytedeco.javacv.Java2DFrameConverter.copy(Java2DFrameConverter.java:471)
	at org.bytedeco.javacv.Java2DFrameConverter.copy(Java2DFrameConverter.java:437)
	at org.bytedeco.javacv.Java2DFrameConverter.copy(Java2DFrameConverter.java:434)
```

The w/a in my case was to use:

```plain
BufferedImage bi = new Java2DFrameConverter().getBufferedImage(frame);
```

However, I'm wondering in which cases ```copy(Frame, BufferedImage)``` and when ```getBufferedImage(Frame)``` should be used?

**Comment by saudet** [comment]
Which version is that? That should be fixed in 1.0.

**Comment by sarxos** [comment]
Hi Samuel,

I'm using 1.0 from Maven Central:

```xml
<dependency>
	<groupId>org.bytedeco</groupId>
	<artifactId>javacv</artifactId>
	<version>1.0</version>
</dependency>
```

**Comment by saudet** [comment]
Actually, we should use `convert()` unless we need to specify some of the other arguments of `getBufferedImage()`, which is not a really good name, but might as well not change it now I thought.

To use the `copy()`, you're going to need to make sure that the format of the images you pass are compatible. That's the gist of it.

**Comment by sarxos** [comment]
Thank you. I modified my code to use ```convert()``` because detecting image format from ```Frame``` seems to be a little bit overhead for my needs. Take care!
