### ISSUE TITLE
Need some suggestion for real time video compression.

### ISSUE THREAD

**Issue by sumit33** [bytedeco/javacv#1771]
Basically, it is a real-time screen-sharing application. I grabbed the screen(FFmpegFrameGrabber) and record it with FFmpegRecorder encoded with VP8.
    
        grabber = new FFmpegFrameGrabber("desktop");
        grabber.setFormat("gdigrab");
        grabber.setOption("offset_x", String.valueOf(rectangleFullScreen.x));
        grabber.setOption("offset_y", String.valueOf(rectangleFullScreen.y));

        recorder = new FFmpegFrameRecorder("output.mp4", roi.width, roi.height, 0);
        recorder.setFrameRate(fps);
        recorder.setVideoCodec(AV_CODEC_ID_VP8);
        recorder.setFormat("webm");
        recorder.setVideoCodecName("libvpx");
        recorder.setPixelFormat(AV_PIX_FMT_YUV420P);

        recorder.setVideoOption("profile", "0");
        recorder.setVideoOption("sharpness","0");
        recorder.setVideoOption("noise-sensitivity","0");
        recorder.setVideoOption("tune", "psnr");
        recorder.setVideoOption("preset", "ultrafast");
        recorder.setVideoOption("maxrate", String.valueOf(1024 * 1024 * maxrateMbits));
        recorder.setVideoOption("bufsize", String.valueOf(1024 * 1024 * maxrateMbits));
        recorder.setVideoOption("crf", String.valueOf(crf));
        recorder.setVideoOption("g", String.valueOf(fps * 10));

 FFmpegRecorder returns an encoded bytebuffer. Now what I have to do on other client-side to stream it on player. How to decode the encoded byte buffer?

**Comment by saudet** [comment]
We can use FFmpegFrameGrabber to decode it. If you're looking for a different answer, you'll need to modify your question.

**Comment by sumit33** [comment]
How to decode with FFmpegGrabber??

**Comment by saudet** [comment]
There's a lot of example code everywhere for that, for example:
https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java

**Comment by sumit33** [comment]
@saudet Thanks a lot. But this example is for playing a video file. I have to send my encoded buffer to the network and the other side will receive it. After receiving, Receiver has to decode the buffer and play according to the codec.

**Comment by steeveen** [comment]
I think you can record your data to a stream. just like rtmp or hls.
in code, you should
`recorder = new FFmpegFrameRecorder("rtmp://xxx", roi.width, roi.height, 0);`
