### ISSUE TITLE
xfade is not work 

### ISSUE THREAD

**Issue by xiaoxiao-wzj** [bytedeco/javacv#1776]
I want to use xfade to merge two videos into one, but I get an error

![08df3f69d5afe70b892b2adc382ca02](https://user-images.githubusercontent.com/53417819/157832809-26b9faeb-88f9-44b5-a2c9-00308592256e.png)
![a72ebadc7a8ae7e07d5e745298ec272](https://user-images.githubusercontent.com/53417819/157832841-0d8121e0-1992-4994-9f7b-0c15b71ed06f.png)
![1309b129a3fcbc69cf295c0fe89d7af](https://user-images.githubusercontent.com/53417819/157832857-dd19e222-aa9b-4b52-bca0-3f3394eb2428.png)

**Comment by saudet** [comment]
It looks like that filter requires the "frame_rate" parameter to be set. I've done that in commit https://github.com/bytedeco/javacv/commit/c78b0f1d6af8ea6ebe1b484d6a334f81e8c25ddf and it seems to be working fine now. Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
The fix has been released with JavaCV 1.5.8. Thanks for reporting!
