### ISSUE TITLE
Still having some interleaved video frame errors

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#178]
Sometimes when running the recording of the camera, I get the `av_interleaved_write_frame() error -22 while writing interleaved video frame.` error.

If I then restart the activity (navigate away and go back) it sometimes works again (or still errors). Also I noticed that on some occasions, the images streamed are completely black, while the SurfaceView in the app works fine.

Any ideas on how I can tackle this problem?

I looked at the `av_interleaved_write_frame(oc, video_pkt)` call which throws this error, but I am not familiar with the deep depths of javacv.

**Comment by saudet** [comment]
You could first try with `ffmpeg` on the command line to see if you can reproduce that problem or not. If it doesn't work any better, we know we have a problem with either your server or with FFmpeg, and in the latter case you should report that upstream.

**Comment by saudet** [comment]
Does the same thing happen on some other platform (Linux, Mac OS X, Windows)? Or does this happen only on Android?

**Comment by saudet** [comment]
I've released version 1.1. Could you try again and see if it's not something that's been fixed in newer versions of FFmpeg? Thanks!

**Comment by lfdversluis** [comment]
Ok so I ran the example using version 1.1.
In the log the following is spammed:

```
11-08 17:46:26.951 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.021 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.091 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.161 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.231 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.301 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.371 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.441 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
11-08 17:46:27.511 17467-17895/com.lfdversluis.screenrecordsampleproject V/MainActivity3: bufferReadResult: 3072
```

of the audio thread. Until at a given moment the following error occurs: ``11-08 17:46:27.511 17467-17895/com.lfdversluis.screenrecordsampleproject W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -32 while writing interleaved audio frame.``

I noticed that the ``public void onPreviewFrame(byte[] data, Camera camera)`` never triggers so maybe that's causing it. Why it doesn't trigger is something I have yet to figure out.

**Comment by saudet** [comment]
Maybe the audio thread is using all the available CPU time?

**Comment by lfdversluis** [comment]
Unlikely, my galaxy S4 should have enough cpu power to handle that. Besides, the audio runs on a separate thread which should be scheduled on a different CPU by the OS if it requires much computation.

**Comment by lfdversluis** [comment]
Ok I have fixed the issue. Apparently in the onSurfaceChanged, it's better to add the 
``
 mCamera.setPreviewDisplay(holder);

 mCamera.setPreviewCallback(CameraView.this);
`` too.

Running now causes the following exception:
``
11-09 14:42:27.019 2342-2342/com.lfdversluis.screenrecordsampleproject E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.lfdversluis.screenrecordsampleproject, PID: 2342
 java.nio.BufferOverflowException
	 at java.nio.Buffer.checkPutBounds(Buffer.java:183)
	 at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:356)
	 at java.nio.ByteBuffer.put(ByteBuffer.java:721)
	 at com.lfdversluis.screenrecordsampleproject.MainActivity3$CameraView.onPreviewFrame(MainActivity3.java:746)
	 at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1160)
	 at android.os.Handler.dispatchMessage(Handler.java:102)
	 at android.os.Looper.loop(Looper.java:145)
	 at android.app.ActivityThread.main(ActivityThread.java:5942)
	 at java.lang.reflect.Method.invoke(Native Method)
	 at java.lang.reflect.Method.invoke(Method.java:372)
	 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
``

Where line 746 is this line:
``
/* get video data */
if (yuvImage != null && recording) {
    ((ByteBuffer) yuvImage.image[0].position(0)).put(data);
}
``

**Comment by saudet** [comment]
Send a pull request with the fix :) Thanks!

As for the overflow, the width and height of the camera might not be matching up with the width and height of the buffer. I recall someone else having issues with that, and they were not able to find a good solution to that problem on some devices...

**Comment by lfdversluis** [comment]
PR is done. I added ``stopPreview()`` to be safe.

**Comment by lfdversluis** [comment]
@saudet Does the yuvImage need to be initialized with exactly the same width/height as you set in the camera parameters? I might want to compare their sizes if so.

**Comment by saudet** [comment]
Not the ones set, the effective width and height.

**Comment by lfdversluis** [comment]
@saudet Which width and height do we have to take? There are some options here:

1. Our own ``imageWidth`` and ``imageHeight``
2. ``cameraView.getWidth(), cameraView.getHeight()``
3. ``cameraDevice.getParameters().getPreviewSize().width, cameraDevice.getParameters().getPreviewSize().height``

Currently I use option 1 for both creating the ``yuvImage`` and instancing the ``FFmpegFrameRecorder``, but that apprently gives a ``BufferOverflowException``.

Do you know which width/height we should take that works for all devices? I will then implement it, try it out and pull request it back.

**Comment by lfdversluis** [comment]
So browsing through some other stackover flow questions, it seems that we have to set the width and height of option 3 as the size for the ``yuvImage``

**Comment by saudet** [comment]
Yes, that's my impression too, but I think there were issues with that as
well. Let me see if I can find that again...

**Comment by saudet** [comment]
Actually, are you not the one that talked about that in issue #145?

**Comment by lfdversluis** [comment]
I do remember that, but using these settings I still do get interleaved frame errors from time to time (also other people I asked to test). So I was trying (once more) to fix things. Unsuccessful so far :disappointed:

**Comment by saudet** [comment]
Errno 22 is "Invalid argument" and 32 is "Broken pipe", so it just sounds like it's trying to write data to a closed file. Making sure that record() never gets called after stop() or release() should fix this, but please let me know if you still have issues with that. Thanks!
