### ISSUE TITLE
The video frame is inconsistent with the actual

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1781]
I want to merge background and video,but the fianl video frame is inconsistent with the actual.
` 

Mat backGroundMat = imread(backgroundPath);
        cvtColor(backGroundMat, backGroundMat, CV_BGR2BGRA);
        Mat mat = new Mat(), chart = new Mat(), back = new Mat();
        Frame frame, finalFrame = new Frame();
        int index = 0;
        while (index < totalNumber && (frame = grabber.grabImage()) != null) {
            Mat chartMat = converter.convertToMat(frame);
            cvtColor(chartMat, chartMat, CV_BGR2BGRA);
            threshold(chartMat, chart, 200, 255, CV_THRESH_BINARY);
            bitwise_not(chart, back);
            bitwise_and(backGroundMat, chart, mat);
            bitwise_and(chartMat, back, chartMat);
            add(mat, chartMat, mat);
            finalFrame = converter.convert(mat);
            recorder.record(finalFrame);
            index++;
        }
        while (index++ < totalNumber) {
            recorder.record(finalFrame);
        }
        recorder.stop();
        recorder.close();
        recorder.release();

`
this is my code.

**Comment by CJL6015** [comment]
![final](https://user-images.githubusercontent.com/42272971/159199546-b0e65d67-f58e-4ca4-a603-e15ff443c7f0.png)
This is the real picture

**Comment by CJL6015** [comment]
![image](https://user-images.githubusercontent.com/42272971/159199661-e212760b-9f73-49ac-b0ed-1b4accd0ec60.png)
This is the frame in final video, the color is different from the real picture

**Comment by saudet** [comment]
It just looks like FFmpegFrameRecorder isn't guessing the pixel format correctly. You'll need to set it in your call to record().

**Comment by CJL6015** [comment]
![image](https://user-images.githubusercontent.com/42272971/159200147-76f40516-dba6-4a13-8034-08295b32946a.png)
There is no error. How can I fix it?

**Comment by saudet** [comment]
Like I said, use this overload of FFmpegFrameRecorder.record() instead:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FFmpegFrameRecorder.html#record-org.bytedeco.javacv.Frame-int-

**Comment by CJL6015** [comment]
I change my code  to `recorder.record(finalFrame,avutil.AV_PIX_FMT_BGRA64);`, but an error occurred.Is it my formatting error?
![image](https://user-images.githubusercontent.com/42272971/159200769-0fbb3a25-2534-49bb-9cb8-bcc928ac3833.png)

**Comment by saudet** [comment]
It just means that's not the pixel format of your images. You'll need to give it the correct value.

**Comment by CJL6015** [comment]
> It just means that's not the pixel format of your images. You'll need to give it the correct value.

Thank you for your reply. I set the pixel format of avutil.AV_PIX_FMT_BGRA, and it works!
