### ISSUE TITLE
java2DFrameConverter  takes too long to convert frame to bufferedimage

### ISSUE THREAD

**Issue by demonlov** [bytedeco/javacv#1783]
When I use the main method to test, it takes little time, while when I use the spring boot framework, it takes a long time
`BufferedImage image = java2DFrameConverter.convert(frame);`

**Comment by demonlov** [comment]
When I use the springboot framework for integration, the overall efficiency of directly using the main method is higher than that of using the framework. When I use the main method to convert the frame into bufferimage, it only takes 7ms, while it takes 50-60ms to run with the springboot framework

**Comment by demonlov** [comment]
I use bufferedimage for annotation, and then convert it into a Frame and push it to the server

**Comment by saudet** [comment]
It's not doing anything that should be affected by Spring Boot. Are you sure it's not just running low in memory?

**Comment by demonlov** [comment]
> 它没有做任何应该受 Spring Boot 影响的事情。你确定它不仅仅是内存不足吗？

There is no difference in the use of JVM memory

**Comment by demonlov** [comment]
> 它没有做任何应该受 Spring Boot 影响的事情。你确定它不仅仅是内存不足吗？

I'm confused about the difference in time, because it's the same code

**Comment by saudet** [comment]
It's possible it's not using the same compiler as your standalone application. You'll need to check its documentation about that.

**Comment by demonlov** [comment]
> It's possible it's not using the same compiler as your standalone application. You'll need to check its documentation about that.

The separate main method and springboot program are running on my local computer

**Comment by demonlov** [comment]
After my investigation, I didn't find any difference

**Comment by demonlov** [comment]
When I deployed to the server, I found the first java2dframeutils Tobufferedimage takes a long time. There is no such problem in the follow-up

**Comment by saudet** [comment]
Good, it just means that on the server the compiler or its settings are different.
