### ISSUE TITLE
 frame into an RGB byte array. What should I do

### ISSUE THREAD

**Issue by demonlov** [bytedeco/javacv#1787]
Hello, I need to convert the frame into an RGB byte array. What should I do

**Comment by saudet** [comment]
The content of the pixels is in `Frame.buffer[0]`. Do whatever you need with that.

**Comment by demonlov** [comment]
> 像素的内容在`Frame.image[0]`. 做任何你需要的。
I have used frame Image [0] get the image in BGR format, but I don't know how to convert it to RGB format. Is there a conversion method?

**Comment by saudet** [comment]
We can use convert() from OpenCV for that, but this something that is simple enough to do manually using indexers:
http://bytedeco.org/news/2014/12/23/third-release/
