### ISSUE TITLE
error: (-217:Gpu API call) out of memory in function 'cv::cudev::grid_transform_detail::TransformDispatcher<false, Policy>::call'

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1788]
![image](https://user-images.githubusercontent.com/42272971/161370112-c6604f16-6cbc-4f1b-8745-33bdbeb35390.png)

**Comment by saudet** [comment]
cvtColor() probably doesn't support in place conversions like that. Use another object for the output.

**Comment by CJL6015** [comment]
This didn't work. The first few cycles are normal, but the error occurs when the number of cycles increases.

**Comment by saudet** [comment]
You need to deallocated old objects you don't use. It won't do that automatically.

**Comment by CJL6015** [comment]
Thank you for your replay! It works.

**Comment by CJL6015** [comment]
I use GpuMat, the running speed is not faster, even slower than cpu.
