### ISSUE TITLE
There is a problem scaling the picture

### ISSUE THREAD

**Issue by demonlov** [bytedeco/javacv#1794]
There is a problem when I want to get byte [] array data after zooming the image

Here is my code
`      try (Mat mat = new Mat(bgr);
             Mat reshape = mat.reshape(3, imageHeight);
             Mat out = new Mat(reshape.rows(), reshape.cols(), opencv_core.CV_8UC3); Mat resizeMat = new Mat();
            ) {
            cvtColor(reshape, out, COLOR_BGR2RGB);
            resize(out, resizeMat, new Size(1280,720),0,0,INTER_LINEAR);
            BytePointer ptr = resizeMat.ptr();
            ptr.get(bgr);
        }`

**Comment by saudet** [comment]
You probably what both Mat to have the same size...

**Comment by demonlov** [comment]
> 您可能两个 Mat 的尺寸相同...

The original size is 1920 * 1080. I want to change it to 1280 * 720

**Comment by demonlov** [comment]
When the code is executed to BytePointer ptr = resizeMat.ptr(); ptr.get(bgr);  At, an error occurred in the program, causing the virtual machine to exit

**Comment by saudet** [comment]
I mean for cvtColor(). I don't know what it does when the shapes differ.

**Comment by demonlov** [comment]
> I mean for cvtColor(). I don't know what it does when the shapes differ.

Hi, bgr is a byte array of BGR. I create a new mat object, obtain the correct matrix size through the reshape method, and then use cvtcolor() to convert it into an RGB mat object
