### ISSUE TITLE
Visual Studio Code under Manual Installation

### ISSUE THREAD

**Issue by lab596** [bytedeco/javacv#1797]
Hey, I mostly use VS Code for my Java projects and I found it really difficult to get javacv running on the platform. I had to dig through YouTube videos that were super old and it took me a good hour to get it running. I am wondering if it would be possible to add a section under Manual installation for VS Code. I'm not sure how popular the IDE is but I'm sure it would help others like me save a lot of time. (I would love to commit if you think this a worthwhile idea). Cheers.

**Comment by saudet** [comment]
It seems to be pretty easy to use Maven and Gradle. I would recommend to just do that:
https://code.visualstudio.com/docs/java/java-build

**Comment by saudet** [comment]
If you're willing to make a contribution though, yes please do. 
Just open a pull request from here: https://github.com/bytedeco/javacv/pulls
Thanks!

**Comment by lab596** [comment]
Ahh I see what you mean with Maven and Gradle. I have simply created a pull request to provide basic instruction (two steps) to add the JAR files on VS Code.

**Comment by saudet** [comment]
Looks good! Could you do the same for https://github.com/bytedeco/javacpp-presets/blob/master/README.md?

**Comment by lab596** [comment]
I think I have done that now. However it says its not able to pass the checks. Is there anything that I need to fix?

**Comment by saudet** [comment]
Thanks! No, everything is fine, that's obviously an unrelated failure.
