### ISSUE TITLE
How to trim the height of the video

### ISSUE THREAD

**Issue by jeketos** [bytedeco/javacv#180]
Hello. I am trying to crop lower half of video. How can I do that?

**Comment by saudet** [comment]
[Mat.apply(Rect roi)](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Mat.html#apply-org.bytedeco.javacpp.opencv_core.Rect-) will do that just fine!

**Comment by jeketos** [comment]
Can you write some using example? After next code:
            graberVideo = new FFmpegFrameGrabber(videoPath);
            graberVideo.start();
            recorder = new FFmpegFrameRecorder(output,width,height,2);
            recorder.start();
            while ((videoFrame = graberVideo.grabFrame()) != null) {
                    //example
            }

**Comment by saudet** [comment]
Something like this:
```java
OpenCVFrameConverter.ToMat converter = new OpenCVFrameConverter.ToMat();
Mat cropped = converter.convert(videoFrame).apply(new Rect(x, y, width, height));
recorder.record(converter.convert(cropped));
```

**Comment by jeketos** [comment]
I have crush when executing nex code:
Mat cropped = converter.convert(videoFrame).apply(new Rect(x, y, width, height));
rather here(opencv_core.class):
        static {
            Loader.load();
        }
Error: A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000028 (code=1)

**Comment by saudet** [comment]
That might have something to do with issue #179, so please post your device details there, thanks!

**Comment by saudet** [comment]
Also, please try the new 1.0.1-SNAPSHOT binaries, thanks.

**Comment by skatash** [comment]
This is not working for Frame created from bytes of onPreviewFrame. Green devil problem.

**Comment by skatash** [comment]
For those who are trying to get rid of green devil problem using Javacv, its simple:

DO NOT use this to make yuvFrame in android if you want to deal with opencv functions;
((ByteBuffer) yuvFrame.image[0].position(0)).put(frame.getFrameBytesData());

USE THIS WAY: to make yuvframe from byte array:
  AndroidFrameConverter androidFrameConverter = new AndroidFrameConverter();
                    yuvFrame =   androidFrameConverter.convert(frame.getFrameBytesData(),width,height);
