### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by jinl2011** [bytedeco/javacv#1806]
This is an inevitable bug。

    ===============================================314
===============================================315
[GC (Allocation Failure) [PSYoungGen: 212362K->960K(239104K)] 406803K->195464K(785408K), 0.0031857 secs] [Times: user=0.13 sys=0.00, real=0.00 secs] 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000255a46ad3ac, pid=29328, tid=0x00000000000046c4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_321-b07) (build 1.8.0_321-b07)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.321-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 3626 C2 org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma(Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;IIZDZI)V (651 bytes) @ 0x00000255a46ad3ac [0x00000255a46ad060+0x34c]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\code\esn-file-yms\hs_err_pid29328.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by jinl2011** [comment]
This is an inevitable bug。 javacv1.5.7

Make three copies of a video file , Capture the first frame of the video.
main function  while(true) run
finally must EXCEPTION_ACCESS_VIOLATION

**Comment by jinl2011** [comment]
please test yourself.

**Comment by saudet** [comment]
Please provide sample code and data to reproduce this.

**Comment by jinl2011** [comment]
one big video file , Make three copies of a video file , Capture the first frame of the video.
main function while(true) run
finally must EXCEPTION_ACCESS_VIOLATION

video is big, I can not upload it. you can use a mp4 video, you can try it.

**Comment by jinl2011** [comment]
wait a moment, i test it again. i check my code segment, one place i don't invoke close. because i checkout wrong branch, sorry , my bad.

**Comment by jinl2011** [comment]
i am testing, hundreds of times in foreach, code is good.

**Comment by jinl2011** [comment]
but, i hava a question, do you tell me, when i can use javacv, i can ensure direct memory not overflow??

**Comment by jinl2011** [comment]
please delete this issue. thank you
