### ISSUE TITLE
FFmpegFrameRecorder is unstable.

### ISSUE THREAD

**Issue by HenryZhouHB** [bytedeco/javacv#1808]
I use FFmpegFrameRecorder to record webrtc video frames and auido samples to MP4 file. Sometimes I can get a good MP4 file and I can play it with chrome browser, but sometimes I just get a bad one and I fail to play it with chrome browser.I use MediaInfo to get  information about the good MP4 file and the bad one and find the difference as follow.
![image](https://user-images.githubusercontent.com/52985827/167057996-8ad2f99f-c328-46ea-9893-7d2e87808d87.png)

Bad MP4 file:
https://user-images.githubusercontent.com/52985827/167058555-ad607eb7-ca29-48b6-b52d-28430f45ea7c.mp4

Good MP4 file:
https://user-images.githubusercontent.com/52985827/167058559-8d5ea33d-2f62-4ef7-bded-feccc9d4a0b8.mp4

The version is javacv platform 1.4.4, and I find that other versions of javacv have the same problem

**Comment by saudet** [comment]
It looks like you need to use libx264, so have you tried to make sure that it always gets used?

**Comment by HenryZhouHB** [comment]
Yes, I have tried to make sure that libx264 always gets used by set VideoCodec to avcodec.AV_CODEC_ID_H264:
recorder = new FFmpegFrameRecorder(this.fileName, width, height);
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);

The whole code is as follow:
package c.m;

import c.v.media.video.I420Buffer;
import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.avcodec;
import org.bytedeco.javacpp.avutil;

import org.bytedeco.javacv.*;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.ShortBuffer;

import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.CV_YUV420p2RGB;
import static org.bytedeco.javacpp.opencv_imgproc.cvtColor;

public class JavaCVMp4Encoder implements Mp4Encoder {
    private String fileName;
    private FFmpegFrameRecorder recorder;
    private static final double FRAME_RATE = 25.0;
    private static final double MOTION_FACTOR = 1;
    private static OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
    private static final System.Logger LOGGER = System.getLogger(JavaCVMp4Encoder.class.getName());
    static {
        avutil.av_log_set_level(avutil.AV_LOG_INFO);
        FFmpegLogCallback.set();
    }
    public JavaCVMp4Encoder() {
    }

    @Override
    public void make(String fileName) {
        System.out.println("JavaCVMp4Encoder::make");
        this.fileName = fileName;
    }

    @Override
    public void configVideo(int width, int height) {
        System.out.println("JavaCVMp4Encoder::configVideo");
        recorder = new FFmpegFrameRecorder(this.fileName, width, height);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);

        recorder.setFrameRate(FRAME_RATE);
        recorder.setVideoBitrate((int)((width*height*FRAME_RATE)*MOTION_FACTOR*0.07));

        recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
        // Audio
        int sampleRate = 44100;
        int channels = 2;
        recorder.setAudioOption("crf", "0");
        recorder.setAudioQuality(0);
        recorder.setAudioBitrate(192000);
        recorder.setSampleRate(sampleRate);
        recorder.setAudioChannels(channels);
        // AAC
        recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
        recorder.setFormat("mp4");
        try {
            recorder.start();
        } catch (FrameRecorder.Exception e) {
            LOGGER.log(System.Logger.Level.ERROR,"JavaCVMp4Encoder configure video error." + e);
        }
    }

    @Override
    public void encodeFrame(I420Buffer buffer) {
        try {
            int w = buffer.getWidth();
            int h = buffer.getHeight();
            Pointer p = new Pointer(buffer.getDataY());
            Mat videoMat = new Mat(h*3/2, w, CV_8UC1, p);
            Mat videoMatRGB = new Mat(h*3/2, w, CV_8UC3);
            cvtColor(videoMat, videoMatRGB, CV_YUV420p2RGB);
            Frame frame = converter.convert(videoMatRGB);
            recorder.record(frame);
        } catch (FrameRecorder.Exception e) {
            LOGGER.log(System.Logger.Level.ERROR,"JavaCVMp4Encoder encode frame error." + e);
        }
    }

    public void encodeSamples(byte[] data, int bitsPerSample, int sampleRate, int channels, int frames) {
        int nSamplesRead = data.length / 2;
        short[] samples = new short[nSamplesRead];
        ByteBuffer.wrap(data).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(samples);
        ShortBuffer sBuff = ShortBuffer.wrap(samples, 0, nSamplesRead);

        try {
            recorder.recordSamples(sampleRate, channels, sBuff);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void close() {
        if(recorder != null){
            try {
                recorder.stop();
            } catch (FrameRecorder.Exception e) {
                LOGGER.log(System.Logger.Level.ERROR,"JavaCVMp4Encoder stop error." + e);
            }
            try {
                recorder.release();
            } catch (FrameRecorder.Exception e) {
                LOGGER.log(System.Logger.Level.ERROR,"JavaCVMp4Encoder release error." + e);
            }
        }
    }
}

**Comment by saudet** [comment]
Call setVideoCodecName("libx264") instead.

**Comment by HenryZhouHB** [comment]
I have tried to Call setVideoCodecName("libx264") instead.
But it doesn't work.

**Comment by saudet** [comment]
What do you mean by "it doesn't work"?

**Comment by saudet** [comment]
Make sure you don't get any warnings in the log messages. If you don't see the log messages, make sure that FFmpegLogCallback.set() gets called.

**Comment by HenryZhouHB** [comment]
> What do you mean by "it doesn't work"?

This issue is not soveled.

**Comment by HenryZhouHB** [comment]
> Make sure you don't get any warnings in the log messages. If you don't see the log messages, make sure that FFmpegLogCallback.set() gets called.

I got the following error. How to fix it? Thanks a lot.

Warning: [mp4 @ 0000000036dee000] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly

Error: [mp4 @ 0000000036dee000] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 140800 >= NOPTS

org.bytedeco.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -22 while writing interleaved audio packet.
	at org.bytedeco.javacv.FFmpegFrameRecorderEx.writePacket(FFmpegFrameRecorderEx.java:1139)
	at org.bytedeco.javacv.FFmpegFrameRecorderEx.record(FFmpegFrameRecorderEx.java:1124)
	at org.bytedeco.javacv.FFmpegFrameRecorderEx.writeSamples(FFmpegFrameRecorderEx.java:1097)
	at org.bytedeco.javacv.FFmpegFrameRecorderEx.recordSamples(FFmpegFrameRecorderEx.java:1073)
	at c.m.JavaCVMp4Encoder.encodeSamples(JavaCVMp4Encoder.java:110)
	at c.m.Mp4EncoderSingleton.encodeSamples(Mp4EncoderSingleton.java:34)
	at c.v.p.net.PeerConnectionClient.publishSample(PeerConnectionClient.java:711)
	at c.v.p.net.PeerConnectionClient.lambda$new$0(PeerConnectionClient.java:110)
[libx264 @ 0000000036def300] frame I:2     Avg QP:26.34  size:  6810

[libx264 @ 0000000036def300] frame P:74    Avg QP:24.23  size:  2948

[libx264 @ 0000000036def300] frame B:202   Avg QP:24.67  size:  1667

[libx264 @ 0000000036def300] consecutive B-frames:  2.5%  1.4%  1.1% 95.0%

[libx264 @ 0000000036def300] mb I  I16..4: 39.8% 54.3%  5.9%

[libx264 @ 0000000036def300] mb P  I16..4:  1.2%  2.1%  0.0%  P16..4: 58.5%  8.5% 10.5%  0.0%  0.0%    skip:19.2%

[libx264 @ 0000000036def300] mb B  I16..4:  0.2%  0.4%  0.0%  B16..8: 46.0%  2.5%  0.2%  direct: 3.4%  skip:47.2%  L0:53.3% L1:45.8% BI: 0.9%

[libx264 @ 0000000036def300] final ratefactor: 23.24

[libx264 @ 0000000036def300] 8x8 transform intra:61.4% inter:92.8%

[libx264 @ 0000000036def300] coded y,uvDC,uvAC intra: 43.5% 73.6% 51.2% inter: 19.4% 40.8% 2.0%

[libx264 @ 0000000036def300] i16 v,h,dc,p: 30% 17%  9% 44%

[libx264 @ 0000000036def300] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 16%  8% 31%  9%  7%  6%  6%  7% 10%

[libx264 @ 0000000036def300] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 11% 15% 29% 10%  4%  3%  5%  3% 20%

[libx264 @ 0000000036def300] i8c dc,h,v,p: 73% 14% 11%  2%

[libx264 @ 0000000036def300] Weighted P-Frames: Y:23.0% UV:1.4%

[libx264 @ 0000000036def300] ref P L0: 44.0%  6.0% 30.9% 17.0%  2.1%

[libx264 @ 0000000036def300] ref B L0: 61.9% 28.8%  9.3%

[libx264 @ 0000000036def300] ref B L1: 82.0% 18.0%

[libx264 @ 0000000036def300] kb/s:409.07

**Comment by saudet** [comment]
That's been fixed for a while now. Please use a recent version of JavaCV.

**Comment by HenryZhouHB** [comment]
>

**Comment by HenryZhouHB** [comment]
> That's been fixed for a while now. Please use a recent version of JavaCV.

I use the latest version 1.5.7 instead and try again.There are no errors or warnings but I just get a 48bytes MP4 file.
The content is an follow:
0000 0020 6674 7970 6973 6f6d 0000 0200
6973 6f6d 6973 6f32 6176 6331 6d70 3431
0000 0008 6672 6565 0000 0000 6d64 6174

**Comment by saudet** [comment]
It's going to be hard to debug this without any error messages or some way to reproduce this. Please provide more information.
