### ISSUE TITLE
please tell me, I set jvm parameters "-Dorg.bytedeco.javacpp.maxbytes=0G -Dorg.bytedeco.javacpp.maxPhysicalBytes=0G", javacv in jvm will use heap memory , not direct memory ???

### ISSUE THREAD

**Issue by jinl2011** [bytedeco/javacv#1811]
please tell me, I set jvm parameters "-Dorg.bytedeco.javacpp.maxbytes=0G -Dorg.bytedeco.javacpp.maxPhysicalBytes=0G", javacv in jvm will use heap memory , not direct memory ???

**Comment by saudet** [comment]
OpenCV, FFmpeg, etc cannot use Java heap memory, so that has no effect on
this.

**Comment by jinl2011** [comment]
ok, thanks

**Comment by jinl2011** [comment]
in JVM,  can I set a direct memory limit, javacv can't use direct memory beyond the limit. can i do like this?

**Comment by saudet** [comment]
Sure, that's what the "org.bytedeco.javacpp.maxPhysicalBytes" system property is for. Set the value you want there.

**Comment by jinl2011** [comment]
Thank you. You're a good man. Good luck
