### ISSUE TITLE
There is insufficient memory for the Java Runtime Environment to continue

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1812]
![IMG_984](https://user-images.githubusercontent.com/42272971/167816738-1eecfd3d-196f-4673-92cc-a5502762b64e.JPEG)

**Comment by saudet** [comment]
... buy more memory? What do you want to know?

**Comment by CJL6015** [comment]
My memory is 8G. This is my code. I want to do a picture-in-picture composite of two videos. This is my code, but I use the cmd of ffmpeg,this error does not appear.
![IMG_7036](https://user-images.githubusercontent.com/42272971/167835130-b5a9bd1c-8a2b-4d98-88f5-2a389cd1fdcd.JPEG)

**Comment by saudet** [comment]
Ok, please provide some sample code to reproduce this.

**Comment by saudet** [comment]
You're using 3 outer loops, that's why. You'll need to do this in a single outer loop.

**Comment by CJL6015** [comment]
Thanks for your reply,it fixed!
