### ISSUE TITLE
How should I javacv ffmpeg to push rtsp , i know ffmpeg.exe push rtsp command, but i dont konw how to use javacv implement it

### ISSUE THREAD

**Issue by nanxia990105** [bytedeco/javacv#1816]

**Comment by saudet** [comment]
We can call the ffmpeg program this way:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by nanxia990105** [comment]
I mean use ffmpegFrameRecorder push, process I used but not good

**Comment by saudet** [comment]
Duplicate of #723
