### ISSUE TITLE
【V1.5.6】ARM CPU utilization 100% 

### ISSUE THREAD

**Issue by huazaizai666** [bytedeco/javacv#1817]
1、runing at arm mechine
2、after jstack , i  get a stack log like this below ,and other thread is waiting for this locked to release
   java.lang.Thread.State: RUNNABLE
	at org.bytedeco.ffmpeg.global.avcodec.avcodec_free_context(Native Method)
	at org.bytedeco.javacv.FFmpegFrameGrabber.releaseUnsafe(FFmpegFrameGrabber.java:206)
	- locked <0x000000055f400298> (a org.bytedeco.javacv.FFmpegFrameGrabber)
	at org.bytedeco.javacv.FFmpegFrameGrabber.release(FFmpegFrameGrabber.java:164)
	- locked <0x00000003c6a9cec0> (a java.lang.Class for org.bytedeco.ffmpeg.global.avcodec)
	at org.bytedeco.javacv.FFmpegFrameGrabber.stop(FFmpegFrameGrabber.java:1111)
	at org.bytedeco.javacv.FrameGrabber.close(FrameGrabber.java:517)
3、this thread always running and cpu is very high(100%)
4、at this condition :  finally to release grabber , use this  method: FrameGrabber.close()

**Comment by huazaizai666** [comment]
> Please try again with JavaCV 1.5.7.
thank you , i will try this version

**Comment by saudet** [comment]
I'm assuming everything is working well with JavaCV 1.5.7, but please let me know if this isn't the case.

**Comment by huazaizai666** [comment]
> Please try again with JavaCV 1.5.7.
I have meet another cpu utilization question, also at arm mechine.
I want to jstack the stack by thread id, but cant search anything in the jstack log by thread id .
is that native thread , jstack can not print it ?

**Comment by huazaizai666** [comment]
> 
after update to 1.5.7 , it‘s working well at ARM CPU ,thank you！
