### ISSUE TITLE
Compiling errors after upgrade to javacv 1.0

### ISSUE THREAD

**Issue by jason-lau** [bytedeco/javacv#182]
Hello, I have an Androind project using javacv. I recently updated it from javacv 0.10 to javacv 1.0 and got many compiling errors. The following are some examples:

The import org.bytedeco.javacpp.opencv_core.CvFont cannot be resolved
opencv_core.CV_FONT_HERSHEY_PLAIN cannot be resolved
opencv_core.CV_AA cannot be resolved
The method cvRectangle(opencv_core.IplImage, opencv_core.CvPoint, opencv_core.CvPoint, opencv_core.CvScalar, int, int, int) is undefined for the type opencv_core
The method cvGetTextSize(String, opencv_imgproc.CvFont, opencv_core.CvSize, int[]) is undefined for the type opencv_core

Am I doing something wrong to cause these errors?

Thanks for your help.

**Comment by saudet** [comment]
No, with OpenCV 3.0, those have just been moved to the `opencv_imgproc` module, that's all.

**Comment by jason-lau** [comment]
Thanks for the reply. I can now get the project to compile but get an error
when executing the following statement:

CvFont font = new CvFont();

Error: 07-19 17:29:46.407: A/libc(6529): Fatal signal 11 (SIGSEGV) at
0x00000028 (code=1), thread 6545 (Thread-2166)

**Comment by saudet** [comment]
This might be related to issue https://github.com/bytedeco/javacv/issues/179. Please try the new binaries there.

**Comment by jason-lau** [comment]
I installed the new binaries and the error is fixed. Thanks!
