### ISSUE TITLE
It runs on Windows 10, but not Linux.  This question keeps coming up 

### ISSUE THREAD

**Issue by SevenZLL** [bytedeco/javacv#1826]
The key code
![image](https://user-images.githubusercontent.com/28469652/173397911-f9cef912-3b50-4d41-94f2-bda48022885c.png)
error message
![image](https://user-images.githubusercontent.com/28469652/173398158-aaae2a84-28ea-40bf-b607-3da0e3e89259.png)
![image](https://user-images.githubusercontent.com/28469652/173398240-cf65d921-4b36-4085-abab-784ef0ed5a2b.png)
How can I solve it

**Comment by saudet** [comment]
It just means it's looking for the ALSA libraries. Those usually come installed with most distributions, but it looks like that's not the case with yours, so please install them!

**Comment by SevenZLL** [comment]
> It just means it's looking for the ALSA libraries. Those usually come installed with most distributions, but it looks like that's not the case with yours, so please install them!

Now, I don't know where to find the installation way, I'm from ffmpeg are installed on the https://johnvansickle.com/ffmpeg/ website this address
