### ISSUE TITLE
memory leak of FFmpegFrameRecorder

### ISSUE THREAD

**Issue by zachluo** [bytedeco/javacv#1827]
Hi, I meet a memory leak problem when I want to convert images to videos using  FFmpegFrameRecorder. Memory usage grows rapidly until all the memory is consumed. When I comment the following codes, the problem does not exist yet. Thanks.

**The version of javacv-platform is 1.5.7.** 
**I have tried all the close/release/stop methods for all operations.**

if (this.frameVideoBufferQueue.size() >= 20) {
      String name = String.format("%s/%d-%d.mp4", saveFolder, this.thisRandom, this.count);
      recorder = new FFmpegFrameRecorder(name,640,360);
      recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
      recorder.setFormat("mp4");
      recorder.setFrameRate(5);
      recorder.setVideoBitrate(1200);
      recorder.start();
      List<Mat> frameVideoBufferList = (List<Mat>)this.frameVideoBufferQueue;
      for (int i = 0; i < frameVideoBufferList.size(); ++i) {
        Frame iplMat = grabberConverter.convert(frameVideoBufferList.get(i));
        recorder.record(iplMat);
        iplMat.close();
      }
      XxlJobLogger.info("going to stop()");
      recorder.stop();
      XxlJobLogger.info("going to release()");
      recorder.release();
      this.count = this.count + 1;
    }

**Comment by saudet** [comment]
How are you releasing the images from frameVideoBufferList?

**Comment by zachluo** [comment]
@saudet I am doing an experiment where I produce one video per 0.2 seconds. I accumulate the 20 latest Mat objects and release the oldest one ASAP.

 this.frameVideoBufferQueue.offer(frame.clone());
    this.frameIdVideoBufferQueue.offer(frameId);
    if (this.frameIdVideoBufferQueue.size() > 20) {
      int loopCount = this.frameIdVideoBufferQueue.size() - 20;
      for (int i = 0; i < loopCount; ++i) {
        Mat iq = this.frameVideoBufferQueue.poll();
        iq.release();
        this.frameIdVideoBufferQueue.poll();
      }
    }

**Comment by saudet** [comment]
I don't see how that piece of code relates to the previous piece of code. If you want help, you'll need to do a better job at explaining what the problem is.

**Comment by saudet** [comment]
You're obviously not releasing all the Mat objects manually, so you're going to get a "leak" there.

**Comment by zachluo** [comment]
@saudet I found that isCloseOutputStream in recorder always returns false. Does FFmpegFrameRecorder support to start and close many many times in one function?

**Comment by saudet** [comment]
That usually works fine yes, but it's not going to do anything different than creating a new instance.

**Comment by zachluo** [comment]
@saudet I take the codes out of the project and make a simple demo. Then everything goes to be fine. I found that I use threads for each request to save videos using FFmpegFrameRecorder. So I guess this should be the reason why it causes memory leak. Do you have any advice for the case using FFmpegFrameRecorder in threads?

**Comment by zachluo** [comment]
@saudet Just one more question! I found that the convert function in OpenCVFrameConverter would assign a Mat object to frame.opaque while frame.opaque is expected to be an array type. https://github.com/bytedeco/javacv/blob/c952a23cc33ace29688ce577ce116d65bb1146b4/src/main/java/org/bytedeco/javacv/OpenCVFrameConverter.java#L174

Here is the definition.
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/Frame.java#L155

So I think the close function of Frame will not work at all. Am I correct?
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/Frame.java#L370

**Comment by saudet** [comment]
That's correct. The code that created the Mat retains its ownership.

**Comment by saudet** [comment]
However, the data doesn't get copied either, so if you need a standalone Frame, be sure to clone() it.

**Comment by zachluo** [comment]
> 

got it! Thanks.

**Comment by HenryZhouHB** [comment]
> How to releaseall the Mat objects manually?

**Comment by HenryZhouHB** [comment]
> You're obviously not releasing all the Mat objects manually, so you're going to get a "leak" there.

How to release all the Mat objects manually?

**Comment by saudet** [comment]
We can call Mat.release() like you're doing, that's fine, but you need to do it on all of them.
