### ISSUE TITLE
[FFMPEG Frame Grabber] Maximizing Performance of Stream on Low Compute Device

### ISSUE THREAD

**Issue by mihirbala** [bytedeco/javacv#1832]
Hello,

I am currently using FFMPEGFrameGrabber to stream frames from a robot with an RTSP camera link over Wifi to an Android Smartwatch (Galaxy Watch 4 LTE 44m). From there, I am shipping the frames over LTE to a backend server which does some processing and returns a result to the watch. Based on this result, the watch will send actuation commands to the robot. I am trying to maximize performance within these constraints. That is, I want clean, low latency streaming from the RTSP link to the LTE backend. I am willing to sacrifice resolution up to 480p and upstream latency up to 400ms. 

Here is how I am initializing the frame grabber:

        grabber = new FFmpegFrameGrabber("rtsp://192.168.42.1/live"); // rtsp url

        grabber.setOption("rtsp_transport", "udp");

        grabber.setOption("buffer_size", "128000");

        grabber.setImageWidth(width);

        grabber.setImageHeight(height);

        grabber.setImageScalingFlags(SWS_FAST_BILINEAR);

And how I'm using the frame grabber:

        wrapper = new GrabberWrapper(grabber, width, height);

        new Thread(() -> {
            try {
                DataOutputStream daos = new DataOutputStream(socket.getOutputStream());
                while (true) {
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    Bitmap bmp = converter.convert(wrapper.grabImage());
                    bmp.compress(Bitmap.CompressFormat.JPEG, 80, baos);
                    byte[] bytes = baos.toByteArray();
                    daos.writeInt(bytes.length);
                    daos.write(bytes, 0, bytes.length);
                    daos.flush();
                    baos.close();
                }
            } catch (Exception e) {
                Log.d("GrabException", e.getMessage());
            }
        }).start();

I have run this exact code (except without down scaling resolution) on an Android phone (Pixel 4a) and it works flawlessly. The frame quality is clean and I am seeing latency around 200-300ms. When I port it to the watch however, latency is still the same but the frame quality decreases dramatically. Here are some example frames from a stream:

![30](https://user-images.githubusercontent.com/6295919/176465814-e2554484-c1de-4ef9-9561-9b647d36a306.jpg)
![20](https://user-images.githubusercontent.com/6295919/176465719-d09a55cc-06f8-438b-98c1-e0c4e4cffb4b.jpg)

Frames like this are very common, approximately 15-20% of received frames. Because I hope to run CV algorithms on this stream, such a high artifact rate isn't acceptable. Do you have any suggestions on how to improve the frame quality without increasing latency too much? I don't know much about video encoding/decoding so I was experimenting with parameters and found that increasing buffer size leads to cleaner frames but also much higher latency.

For reference, the Galaxy Watch 4 LTE 44m has a dual-core 1.18 GHz processor and 1.5 GB of RAM.

Thank you in advance for your help!

**Comment by saudet** [comment]
For starters, you should try to use "tcp" instead of "udp" for "rtsp_transport". That should take care of the "frame quality". However, if your watch isn't powerful enough to decode all the frames on time, latency is going to suffer. So you'll need to figure out a way to decode frames faster. If the watch has hardware acceleration, this is something that FFmpeg can use, for example, see issue #1828.

**Comment by mihirbala** [comment]
I was trying to use FFMPEG Frame Grabber grabKeyframe() to do this but I don't seem to be getting any frames with this. Curiously, instead of returning null frames, the grabKeyframe() call seems to block and fail to return. Any idea what might be causing this issue? Thanks for your help!

**Comment by saudet** [comment]
Maybe there aren't any "key frames". Check the Frame.keyFrame values and see if any of them are "true".

**Comment by saudet** [comment]
Hum, maybe the `AVFrame.key_frame` field is  deprecated and no longer set by all codecs. Could you try to replace `key_frame() != 0` with `pict_type() == AV_PICTURE_TYPE_I` in FFmpegFrameGrabber and see if that works in your case?

**Comment by mihirbala** [comment]
Sure I can try that. I am a bit inexperienced with building Java packages from source though, do you have any guidance on how to build JavaCV from source for Android Studio? I cloned the repository and made the required edits to FFmpegFrameGrabber.java but I am now unsure how to build the modified repo and incorporate it into the project. Thanks for your continued help!

**Comment by mihirbala** [comment]
One more thing, I was thinking that in order to make this pipeline as performant as possible, it might be a good idea to demux the AV Packets on the watch but then ship them to the server over LTE for decoding. As far as I can tell, decoding causes the largest bottleneck and also is causing some CPU overheating issues on the watch. Would this be possible? If so, would I be able to just send the AV Packets raw over the network along with the AV Format Context or will I need something more than that?

**Comment by saudet** [comment]
> Sure I can try that. I am a bit inexperienced with building Java packages from source though, do you have any guidance on how to build JavaCV from source for Android Studio? I cloned the repository and made the required edits to FFmpegFrameGrabber.java but I am now unsure how to build the modified repo and incorporate it into the project. Thanks for your continued help!

The project uses [Maven](https://maven.apache.org), but it's very easy to build. We just need to call "mvn clean install" in the directory where the pom.xml file is, and then we can use it as a dependency from Android Studio.

> One more thing, I was thinking that in order to make this pipeline as performant as possible, it might be a good idea to demux the AV Packets on the watch but then ship them to the server over LTE for decoding. As far as I can tell, decoding causes the largest bottleneck and also is causing some CPU overheating issues on the watch. Would this be possible? If so, would I be able to just send the AV Packets raw over the network along with the AV Format Context or will I need something more than that?

I'm not sure I understand what you're proposing. Sending and receiving raw images is most like going to consume more energy than the decoding process, but you can try to do that if you want. That's what the "rawvideo" codec is for: https://ffmpeg.org/ffmpeg-formats.html#rawvideo

The only real solution I can think of is hardware acceleration. There's most likely one for decoding certain formats on the watch.

**Comment by mihirbala** [comment]
Thanks for the guidance! I guess what I was asking is whether we can redirect the packets we receive from RTSP over LTE to be decoded on the cloud. I was under the impression that decoding the frames was what was hurting performance so I thought this could alleviate that. If all we are doing is sending the raw data over the LTE link, our bandwidth may be good enough to achieve sub 700-800ms latency which is workable. 

On another note, we tried building JavaCV from source with edits and successfully added it to Android Studio. However, we are having some problems getting it to find FFMPEG now. Here is what our Gradle build file looks like:

~~~ 
implementation group: 'org.bytedeco', name: 'ffmpeg', version: '5.0-1.5.7' 
// implementation files('/home/mbala/Downloads/ffmpeg-5.0.1-1.5.8-20220410.000750-15-android-arm64-gpl.jar')
implementation 'androidx.appcompat:appcompat:1.3.0' 
implementation 'com.google.android.material:material:1.4.0'
implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
implementation 'androidx.wear:wear:1.2.0'
implementation files('/home/mbala/.m2/repository/org/bytedeco/javacv/1.5.8-SNAPSHOT/javacv-1.5.8-SNAPSHOT.jar')
~~~

The Gradle files sync just fine but at runtime, we are seeing a class def not found error for ```ffmpeg.global.avutil``` when the FrameGrabber is initialized. Are we doing something wrong? Everything seemed to work when we pulled directly from Maven. We also tried using an up-to-date snapshot of FFMPEG as a JAR dependency (commented out in the block above) but when we do that, FFMPEG itself is not found. Thanks again for your help!

**Comment by mihirbala** [comment]
We were able to copy FFmpegFrameGrabber into our project and successfully run it. However, even with the change you suggested, we are still not getting any keyframes returning. We thought this issue could be caused by our JavaCV version being out of date (1.4.3 as opposed to 1.5.7) so we attempted to upgrade. Unfortunately, no matter what we try, we cannot get the project to work with the new version. Everything builds just fine but at runtime we get a `java.lang.NoClassDefFoundError: org.bytedeco.ffmpeg.global.avutil` error. Our Gradle file looks like this:
~~~
// JAVACV libs
implementation 'org.bytedeco:javacv:1.5.7'
// https://mvnrepository.com/artifact/org.bytedeco/javacpp
implementation group: 'org.bytedeco', name: 'gradle-javacpp', version: '1.5.7'
// https://mvnrepository.com/artifact/org.bytedeco/ffmpeg
implementation group: 'org.bytedeco', name: 'ffmpeg', version: '5.0-1.5.7'
// https://mvnrepository.com/artifact/org.bytedeco/opencv
implementation group: 'org.bytedeco', name: 'opencv', version: '4.5.5-1.5.7'
~~~

Any suggestions on how to proceed? Thanks for your help!

**Comment by mihirbala** [comment]
Just following up, we think we've found a halfway solution without using GrabKeyframe(). We are using two threads, one to grab the most recent frame and one to send the latest frame over the network. We have identified that the crux of this issue is that grabFrame() does not return the latest frame -- that is, it will always pull the most recent frame in its buffer and not the most recent frame seen. Is there a way to modify this behavior so that grabFrame() pulls only the most recent frame?

**Comment by saudet** [comment]
> Any suggestions on how to proceed? Thanks for your help!

Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information in the log.

**Comment by saudet** [comment]
> ```
> // JAVACV libs
> implementation 'org.bytedeco:javacv:1.5.7'
> // https://mvnrepository.com/artifact/org.bytedeco/javacpp
> implementation group: 'org.bytedeco', name: 'gradle-javacpp', version: '1.5.7'
> // https://mvnrepository.com/artifact/org.bytedeco/ffmpeg
> implementation group: 'org.bytedeco', name: 'ffmpeg', version: '5.0-1.5.7'
> // https://mvnrepository.com/artifact/org.bytedeco/opencv
> implementation group: 'org.bytedeco', name: 'opencv', version: '4.5.5-1.5.7'
> ```

You'll need to add a dependency on either javacv-platform or ffmpeg-platform for this to work. None of those dependencies contain binaries for FFmpeg itself.

**Comment by mihirbala** [comment]
Thanks for your help! We were able to install 1.5.7 and test your changes but keyframes are still not being read. We did some logging and found that this section of code (found on line 1389 of version 1.5.7 of FFmpegFrameGrabber.java) seems to not behave correctly. The packets are read in properly in the initial if statement of the while loop but the `if (!keyFrames || picture.pict_type() == AV_PICTURE_TYPE_I)` statement is never reached nor entered:

~~~
while (!done) {
      ret = avcodec_receive_frame(video_c, picture);
      if (ret == AVERROR_EAGAIN() || ret == AVERROR_EOF()) {
          if (pkt.data() == null && pkt.size() == 0) {
              return null;
          } else {
              readPacket = true;
              break;
          }
      } else if (ret < 0) {
          // Ignore errors to emulate the behavior of the old API
          // throw new Exception("avcodec_receive_frame() error " + ret + ": Error during video decoding.");
          readPacket = true;
          break;
      }

      if (!keyFrames || picture.pict_type() == AV_PICTURE_TYPE_I) {
          long pts = picture.best_effort_timestamp();
          AVRational time_base = video_st.time_base();
          timestamp = 1000000L * pts * time_base.num() / time_base.den();
          // best guess, AVCodecContext.frame_number = number of decoded frames...
          frameNumber = (int)Math.floor(timestamp * getFrameRate() / 1000000L);
          frame.image = image_buf;
          if (doProcessing) {
              processImage();
          }
          /* the picture is allocated by the decoder. no need to
             free it */
          done = true;
          frame.timestamp = timestamp;
          frame.keyFrame = picture.key_frame() != 0;
          frame.pictType = (char)av_get_picture_type_char(picture.pict_type());
          frame.type = Frame.Type.VIDEO;
      }
}
~~~

Any ideas on why this is the case? The only modifications we have made to the file are to replace `key_frame() != 0` with `pict_type() == AV_PICTURE_TYPE_I` at lines 1320 and 1419.

**Comment by mihirbala** [comment]
UPDATE: It seems that the video stream is formatted in such a way that it doesn't produce conventional keyframes. That is why the function is not returning. Since decoding on the watch will likely not work, we are switching our approach to redirect the raw data from the RTSP stream over LTE to the cloud for decoding. Could we do this by copying AVPackets to a socket and sending them before they are decoded? If not, do you know other ways we could do this without using native C++? We are trying to exhaust our options in Java before switching to JNI.

**Comment by mihirbala** [comment]
Hello,

We've done a lot of experimentation and have now come to a few conclusions. We talked to the robot manufacturer and this is what they had to say about how the stream is encoded:

"We are using intra-refresh (and multiple slices) instead of streaming IDR frames. This is done to increase network reliability as it makes the bandwidth more linear, and avoids the big key frames which are more likely to be the one having an error."

This approach has many consequences for us. First, I don't think it is possible for us to grab keyframes from the stream. Second, we most likely will have to read in every packet since some packets can have references which span back several dozen frames.

Our approach now is to drop frames as you suggested, about 1 in every 10, but we are running into some issues. First, we cannot get frames from isolated packets. We have to decode six consecutive frames to get enough data to produce one frame. Second, even though we are dropping 24/30 incoming packets, we still see huge latency drift (6+ seconds latency). This should not be possible if we were truly dropping the packets since if we were, we should be seeing a latency of 2s with no drift. This implies that there is some buffering happening behind the scenes, either by AV or by JavaCV that we are unaware of. Any insight into this would be greatly appreciated. Thanks so much for your help!

**Comment by mihirbala** [comment]
To be clear, the crux of our issue is we are consuming a 720p@30fps stream that we cannot decode fast enough to keep real time. We cannot control the stream parameters. Is there a way to drop packets in a way that doesn't break the frame grabber given the sliced nature of this stream?

**Comment by saudet** [comment]
Well, if you drop packets, the frames are going to get corrupted in some way, but if they did their job right on the encoding side, it might still give acceptable results. As for buffering, there's a few options such as "reorder_queue_size" to control that for the RTSP protocol: https://ffmpeg.org/ffmpeg-protocols.html#rtsp

**Comment by mihirbala** [comment]
We solved our issue :smiley:. Turns out that if we drop three packets then decode two consecutively, we get clean frames and low latency on our device (Samsung Galaxy Watch 4). Your help has been invaluable, thank you so much for your continued support of this great project!
