### ISSUE TITLE
Freezing last seconds when FFmpegRecorder record

### ISSUE THREAD

**Issue by suhakopan** [bytedeco/javacv#1834]
Hello, when trying to shorten a video, the image freezes in the last seconds of the video, but the sound continues.

            try (FrameGrabber grabber = new FFmpegFrameGrabber(file)) {
            grabber.start();
            grabber.setTimestamp(start * 1000000);

            FrameRecorder recorder = new FFmpegFrameRecorder(savedLocation, grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
            recorder.setFrameRate(grabber.getFrameRate());
            recorder.setSampleRate(grabber.getSampleRate());
            recorder.setVideoCodec(grabber.getVideoCodec());
            recorder.setAudioCodec(grabber.getAudioCodec());
            recorder.start();

            Frame frame;
            while ((frame = grabber.grab()) != null && grabber.getTimestamp() < end * 1000000) {
                recorder.record(frame);
            }
            recorder.stop();
            grabber.stop();`

**Comment by saudet** [comment]
The frame rate might not be high enough. Try to increase it?

**Comment by saudet** [comment]
It's also possible you're getting too many audio frames. Make sure that's not happening by checking all their timestamps one by one.

**Comment by suhakopan** [comment]
> It's also possible you're getting too many audio frames. Make sure that's not happening by checking all their timestamps one by one.


When I check the frames one by one, it first sets the audio frames and then the video frames. Yes, also the audio frames are double the video frames. What solution do I need to implement?

**Comment by saudet** [comment]
Actually, FFmpegFrameRecorder currently ignores the timestamps, so what I mean is check the value of those timestamps, and only call record() for the ones you want to output. If the video format you're using supports a variable frame rate, we can also call setTimestamp() to set the time of the next video frame that gets passed to record(). We can't set timestamps for audio frames, so just make sure to skip calling record() for any extra ones you don't want to output!

**Comment by suhakopan** [comment]
I solved the problem by ignoring the extra audio frames. Thank you @saudet 

```
while ((frame = grabber.grab()) != null && recorder.getTimestamp() < end * 1000000) {
                if (frame.type == Frame.Type.AUDIO && frame.timestamp >= (end * 1000000)) {
                    continue;
                }
                recorder.record(frame);
            }
```
