### ISSUE TITLE
The grabber's setFrameRate does not take effect

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1841]
I setFrameRate before start the grabber, but it didn't work.

**Comment by saudet** [comment]
That doesn't do anything for video files, the frame rate is set by the file.

**Comment by saudet** [comment]
Duplicate of #1121

**Comment by CJL6015** [comment]
I am not trying to change the frame rate of the video file. I want to resample the video but it still doesn't work

**Comment by saudet** [comment]
We can use FFmpegFrameFilter with the fps filter for that: https://ffmpeg.org/ffmpeg-filters.html#fps-1

**Comment by saudet** [comment]
BTW, it might be easier for your use case to use the ffmpeg program instead:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by CJL6015** [comment]
Thank you for your reply!
