### ISSUE TITLE
Using FrameGrabber.setTimestamp() breaks the FrameGrabber.grabAtFrameRate()

### ISSUE THREAD

**Issue by Nycrera** [bytedeco/javacv#1844]
If real-time streaming is done using `FrameGrabber.grabAtFrameRate()`,
this completely breaks the ability to seek on the grabber using `FrameGrabber.setTimestamp()`.

This is probably because of the Method `FrameGrabber.waitForTimestamp()`:

```java
public boolean waitForTimestamp(Frame frame) throws InterruptedException {
        if (startTime == 0) {
            startTime = System.nanoTime() / 1000 - frame.timestamp;
        } else {
            long delay = frame.timestamp - (System.nanoTime() / 1000 - startTime);
            if (delay > 0) {
                Thread.sleep(delay / 1000, (int)(delay % 1000) * 1000);
                return true;
            }
        }
        return false;
    }
```
As you can see, this method delays the grabbing by calculating a delay with the `System.nanoTime()` and the ` frame.timestamp`
But  when we seek the video, `frame.timestamp` changes non-monotonically possibly causing this whole logic to break down.

I still haven't got my head around all this. But in my experiments, the grabber quickly grabs without any delay until we catch up with the current system time. And then keeps grabbing at the framerate typically.

**Comment by Nycrera** [comment]
Reseting the timer with`startTime = 0;` whenever we use the  `FrameGrabber.setTimestamp()` seems to somewhat solve the problem.

Maybe this reset assignment should be added to `FrameGrabber.setTimestamp()`, such as:
```java
    public void setTimestamp(long timestamp) throws Exception {
        this.timestamp = timestamp;
        startTime = 0;
    }
```
As well as the method `FrameGrabber.setFrameNumber()` 

But then again as I am not really involved enough with this library I would like some comments on it before going for any pull requests.

**Comment by saudet** [comment]
Please open a pull request with your suggested changes. Then we can have @wangxi761, the author of FrameGrabber.grabAtFrameRate(), look at them. Thank you!
