### ISSUE TITLE
Where can the nonfree packages be downloaded? Or do they have to be built?

### ISSUE THREAD

**Issue by dstieglitz** [bytedeco/javacv#185]
Since 1.0, the nonfree bit of the opencv/javacv libraries have been moved to an external package, but I can't seem to find where to obtain them. Are there instructions available somewhere?

**Comment by jpsacha** [comment]
See issue [javacpp-presets issue #54](https://github.com/bytedeco/javacpp-presets/issues/54). It is not yet integrated into `javacpp-presets`, but you can build it from my branch [xfeatures2d](https://github.com/jpsacha/javacpp-presets/tree/xfeatures2d). Then build `javacv`.

**Comment by saudet** [comment]
@jpsacha Thanks for the reply!

@dstieglitz Let's continue the discussion over there, thanks!

**Comment by dstieglitz** [comment]
Thanks guys!



—
