### ISSUE TITLE
How to perform matrix operations on opencv's Mat?

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1857]
I want to operate on 2 mats, how should I do it?

**Comment by saudet** [comment]
What kind of operations?

**Comment by CJL6015** [comment]
Matrix Subtraction and Cross Product

**Comment by saudet** [comment]
Those look like the functions you're looking for:
- http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/global/opencv_core.html#subtract-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_core.Mat-int-
- http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/opencv_core/Mat.html#cross-org.bytedeco.opencv.opencv_core.Mat-

**Comment by CJL6015** [comment]
Thank you for reply !
