### ISSUE TITLE
Trouble with video streaming(recordering)

### ISSUE THREAD

**Issue by xeon1401** [bytedeco/javacv#186]
Hello. I use javacv lib in my project for streaming video from android device to server. I use RecordActivity sample code and have some troubles. For playing stream i use Android VLC media player and Android Broadcaster app. When I press start button and start streaming i don't see anything  in player. But when I press stop button I can see last 10-15 seconds of stream in player. Tested on Nexus 5 with Android 5.0.1 and Asus Zenfone 5 with Android 4.4.2. Can anybody help me? Thanks

**Comment by saudet** [comment]
That's how it should work. If you want live streaming, set `RECORD_LENGTH = 0` instead.

**Comment by xeon1401** [comment]
Thank you for answer.
