### ISSUE TITLE
Can FFmpegFrameGrabber auto close when inputstream is idle for a while?

### ISSUE THREAD

**Issue by Chamlien** [bytedeco/javacv#1862]
I use PipedInputStream as stream for FFmpegFrameGrabber input，when no data are send to PipedInputStream, FFmpegFrameGrabber.grab() will always is locked， and this code ` while ((frame = grabber.grabAtFrameRate()) != null) {}` can not end loop. so i need help to check  whether stream is idle，and stop the grab automatically for a while.

**Comment by saudet** [comment]
That's going to depend on the implementation of PipedInputStream. If that doesn't support a timeout, you'll need to implement your own version of PipedInputStream, but that includes a timeout.

**Comment by Chamlien** [comment]
> That's going to depend on the implementation of PipedInputStream. If that doesn't support a timeout, you'll need to implement your own version of PipedInputStream, but that includes a timeout.

Thank you for reply. it's difficult to implement PipedInputStream，could you provide some pseudo-code?

**Comment by Chamlien** [comment]
I have solved this problem. But I confused about when grab.close() called, the  grab.grab() still return a frame, why?
Here is implementation of PipeInputStream Code. 
`public class IdlePipeInputStream extends PipedInputStream {

    private boolean received;
    private int idleTimeout = 5000;
    private boolean running = true;
    private final H265Convertor convertor;

    public IdlePipeInputStream(int pipeSize, H265Convertor convertor) {
        super(pipeSize);
        this.convertor = convertor;
        listenIdle();
    }

    private void listenIdle() {
        new Thread(() -> {
            Thread.currentThread().setName("监听空闲线程");
            long startTime = System.currentTimeMillis();
            while (running) {
                try {
                    if (received && available() == 0) {
                        if (System.currentTimeMillis() - startTime > idleTimeout) {
                            System.out.println("here is " + idleTimeout + " prepare to close...");
                            running = false;
                            convertor.release();
                            break;
                        }
                    } else {
                        startTime = System.currentTimeMillis();
                    }
                    Thread.sleep(100);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }

    @Override
    protected synchronized void receive(int b) throws IOException {
        received = true;
        super.receive(b);
    }

    @Override
    public synchronized int read() throws IOException {
        received = true;
        return super.read();
    }

    @Override
    public synchronized int read(byte[] b, int off, int len) throws IOException {
        received = true;
        return super.read(b, off, len);
    }

    @Override
    public void close() throws IOException {
        super.close();
    }

    public void setIdleTimeout(int idleTimeout) {
        this.idleTimeout = idleTimeout;
    }
}`

**Comment by saudet** [comment]
The codec may have a couple of frames buffered, that's normal.
