### ISSUE TITLE
Why checking audioChannels if it's overwritten?

### ISSUE THREAD

**Issue by alexey-pelykh** [bytedeco/javacv#1865]
https://github.com/bytedeco/javacv/blob/32f5fed744c9f679007bc30b73c2da8f934570f6/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L688

**Comment by saudet** [comment]
It's probably pointless indeed. Please open a pull request!

**Comment by saudet** [comment]
Duplicate of #818
