### ISSUE TITLE
Convert mov to mp4 failure!

### ISSUE THREAD

**Issue by angeltping** [bytedeco/javacv#1868]
`	public static void convertVideo2Mp4(InputStream sourceVideo, OutputStream targetVideo) {
		try (FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(sourceVideo)) {
			frameGrabber.start();
			try (FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(targetVideo,
					frameGrabber.getImageWidth(),
					frameGrabber.getImageHeight(),
					frameGrabber.getAudioChannels())) {

				recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
				recorder.setFormat(VIDEO_TYPE_MP4);
				recorder.setFrameRate(frameGrabber.getFrameRate());
				recorder.setVideoBitrate(frameGrabber.getVideoBitrate());
				recorder.setAspectRatio(frameGrabber.getAspectRatio());
				recorder.setAudioOptions(frameGrabber.getAudioOptions());
				recorder.setSampleRate(frameGrabber.getSampleRate());
				recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
				recorder.start();
				Frame frame;
				while (true) {
					frame = frameGrabber.grabFrame();
					if (frame != null) {
						recorder.record(frame);
					} else {
						break;
					}
				}
			} catch (Exception e) {
				throw new BusinessException("convert to mp4 Recorder error!", e);
			}
		} catch (Exception e) {
			throw new BusinessException("convert to mp4 Recorder error!", e);
		}
	}`
error msg:
avformat_write_header error() error -22: Could not write header to 'java.io.FileOutputStream@192d3247' (For more details, make sure FFmpegLogCallback.set() has been called.))

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'java.io.BufferedInputStream@11758f2a':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2012-03-08T11:20:15.000000Z
  Duration: 00:00:20.00, start: 0.000000, bitrate: 64861 kb/s
  Stream #0:0[0x1](eng): Video: mjpeg (Baseline) (jpeg / 0x6765706A), yuvj422p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 72:72 DAR 16:9], 64855 kb/s, 30 fps, 30 tbr, 30 tbn (default)
    Metadata:
      creation_time   : 2012-03-08T11:20:15.000000Z
      handler_name    : Apple Video Media Handler
      vendor_id       : appl
      encoder         : Photo - JPEG
[libopenh264 @ 000000002c40f540] Slice count will be set automatically
[libopenh264 @ 000000002c40f540] [OpenH264] this = 0x000000002d440590, Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
[libopenh264 @ 000000002c40f540] [OpenH264] this = 0x000000002d440590, Warning:Change QP Range from(0,51) to (12,42)
[mp4 @ 000000002c40d600] muxer does not support non seekable output

**Comment by saudet** [comment]
> [mp4 @ 000000002c40d600] muxer does not support non seekable output

The mp4 format doesn't support streams well. Please try another format.

**Comment by SuperChrisliu** [comment]
@saudet 
```
[libopenh264 @ 000000002c40f540] Slice count will be set automatically
[libopenh264 @ 000000002c40f540] [OpenH264] this = 0x000000002d440590, Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
[libopenh264 @ 000000002c40f540] [OpenH264] this = 0x000000002d440590, Warning:Change QP Range from(0,51) to (12,42)
```
hi, the log output decoder use OpenH264, is it possible to choose libx264 decoder?

**Comment by saudet** [comment]
OpenH264 is the encoder, and yes please try libx264 instead.

**Comment by angeltping** [comment]
SeekableByteArrayOutputStream instead OutputStream  solved！

**Comment by ferrymo** [comment]
> SeekableByteArrayOutputStream instead OutputStream solved！SeekableByteArrayOutputStream 而不是 OutputStream 已解决！

That's great

**Comment by ferrymo** [comment]
> SeekableByteArrayOutputStream instead OutputStream solved！SeekableByteArrayOutputStream 而不是 OutputStream 已解决！
The converted video cannot be played
