### ISSUE TITLE
javacv  set ffmpeg parameter -t -to...

### ISSUE THREAD

**Issue by chenmengstudio** [bytedeco/javacv#1869]
Hi,
How to set ffmpeg parameters in javacv？
-t -to etc
for example "ffmpeg -t 60 -i rtsp://127.0.0.1/a -vcodec copy -acodec copy -rtsp_transport tcp -f rtsp rtsp://127.0.0.1/b".
I use the 'grabber.setOption("t", "60");' setting to have no effect。

**Comment by saudet** [comment]
We can use the ffmpeg program directly for this purpose:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
