### ISSUE TITLE
Iphone video get first frame Image orientation is landscape orientation but correct is portrait? And mp4 video not this issue.

### ISSUE THREAD

**Issue by angeltping** [bytedeco/javacv#1870]
`	
       public static BufferedImage getFirstFrame(InputStream videoInput) {
		  try (Java2DFrameConverter converter = new Java2DFrameConverter();
				  FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(videoInput)) {
			  frameGrabber.start();
			  Frame frame = frameGrabber.grabImage();
			  BufferedImage bufferedImage = converter.convert(frame);
			  return bufferedImage;
		  } catch (Exception e) {
			  throw new BusinessException("get first frame image error！", e);
		  }
	  }

        FileInputStream fileInputStream = FileUtil.getFileInputStream("D:\\sz-download\\aaa.mov");
	byte[] bytes = StreamUtils.copyToByteArray(fileInputStream);
	ByteArrayInputStream thumbnailStream = new ByteArrayInputStream(bytes);
	BufferedImage bufferedImage = getFirstFrame(thumbnailStream);
	ImageIO.write(bufferedImage, "jpg", new File("D:\\8.jpg"));
`
is there some params to set ?

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'java.io.ByteArrayInputStream@7cbd213e':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2022-08-16T01:04:52.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 15.614899
    com.apple.quicktime.location.ISO6709: +29.6489+106.5276+439.473/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12
    com.apple.quicktime.software: 15.0
    com.apple.quicktime.creationdate: 2022-06-23T18:46:51+0800
  Duration: 00:00:03.27, start: 0.000000, bitrate: 3035 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 176 kb/s (default)
    Metadata:
      creation_time   : 2022-08-16T01:04:52.000000Z
      handler_name    : Core Media Audio
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720, 2845 kb/s, 29.98 fps, 29.97 tbr, 600 tbn (default)
    Metadata:
      creation_time   : 2022-08-16T01:04:52.000000Z
      handler_name    : Core Media Video
      vendor_id       : [0][0][0][0]
      encoder         : H.264
    Side data:
      **displaymatrix: rotation of -90.00 degrees**

**Comment by saudet** [comment]
We can get that number by calling FFmpegFrameGrabber.setFrameNumber() available in the snapshots: http://bytedeco.org/builds/

**Comment by angeltping** [comment]
> We can get that number by calling　FFmpegFrameGrabber.getDisplayRotation()　available in the snapshots: http://bytedeco.org/builds/

thanks, I use metadata-extractor  get video metadata and get ROTATION value then ratate the image.
when publish 1.5.8 release I will upgrade!

**Comment by saudet** [comment]
Duplicate of #1361
