### ISSUE TITLE
 Physical memory continues to increase due to FFmpegFrameGrabber grabPacket().

### ISSUE THREAD

**Issue by SonMinSang** [bytedeco/javacv#1872]
If I keep receiving packets, the physical memory keeps increasing. There is no significant change in heap memory, but physical memory continues to increase. Is there a way to reduce physical memory other than restarting the program?

``` 
AVPacket packet;
while ((packet = frameGrabber.grabPacket()) != null) {
         
}
```

**Comment by saudet** [comment]
From what I understand, you'll need to call FFmpegFrameRecorder.recordPacket() to release it. @alicanalbayrak Is this correct?

In any case, let me know if that doesn't work!
