### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb43f0b6f5, pid=27056, tid=0x0000000000001c70

### ISSUE THREAD

**Issue by ywagd** [bytedeco/javacv#1873]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb43f0b6f5, pid=27056, tid=0x0000000000001c70
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  0x00007ffb43f0b6f5
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

pom
       <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.7</version>
        </dependency>

code 

public static String waterMark3(String videoPath, String text, Integer x, Integer y, Color color, Integer fontSize) throws Exception {
        FFmpegLogCallback.set();
        String s = videoPath_temp_path + UUID.randomUUID().toString() + ".mp4";
        // 设置源视频、加字幕后的视频文件路径
        FFmpegFrameGrabber grabber = FFmpegFrameGrabber.createDefault(videoPath);
        grabber.start();
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(s,
                grabber.getImageWidth(), grabber.getImageHeight(), grabber.getAudioChannels());
        // 视频相关配置，取原视频配置
        recorder.setSampleRate(grabber.getSampleRate());
        recorder.setFrameRate(grabber.getFrameRate());
        recorder.setTimestamp(grabber.getTimestamp());
        recorder.setVideoBitrate(grabber.getVideoBitrate());
        recorder.setVideoCodec(grabber.getVideoCodec());
        recorder.start();
        final long start = System.currentTimeMillis();
        Java2DFrameConverter converter = new Java2DFrameConverter();
        Frame frame;
        int i = 0;
        while ((frame = grabber.grabFrame()) != null) {
            i++;
            // 从视频帧中获取图片
            if (frame.image != null) {
                BufferedImage bufferedImage = converter.getBufferedImage(frame);
                // 对图片进行文本合入
                bufferedImage = addSubtitle(bufferedImage, text, null);
                // 视频帧赋值，写入输出流
                frame.image = converter.getFrame(bufferedImage).image;
                recorder.record(frame);
            }
            // 音频帧写入输出流
            if (frame.samples != null) {
                recorder.recordSamples(frame.sampleRate,frame.audioChannels,frame.samples);
            }
        }
        System.out.println("推流结束...");
        recorder.flush();
        grabber.stop();
        recorder.stop();
        System.out.println("总共处理的图片数量>>" + i + ",耗时为" + (System.currentTimeMillis() - start));
        return s;
    }

can you fix it? thank you !

**Comment by saudet** [comment]
Could you also attach the hs_err_pidXXX.log file that you get?

**Comment by ywagd** [comment]
I don't know why. But I changed the code and solved it. 
change : 
     frame.image = converter.getFrame(bufferedImage).image; 
to: 
     frame = = converter.getFrame(bufferedImage);

 I hope it will help ！you can close the question!

**Comment by saudet** [comment]
I see, yes, we shouldn't modify the Frame object returned by FFmpegFrameGrabber.
