### ISSUE TITLE
grabber.grabImage() infinite loop

### ISSUE THREAD

**Issue by suhakopan** [bytedeco/javacv#1875]
Hi @saudet ,

I want to create an image from video.  I was using 1.5.7 version, after downgrading 1.5.6 version grabber.grabImage() stuck in infinite loop. The code was working the 1.5.7 version

```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(FILE) 
grabber.start();
Java2DFrameConverter paintConverter = new Java2DFrameConverter();
grabber.setTimestamp(TIMESTAMP);
BufferedImage difImage = paintConverter.getBufferedImage(grabber.grabImage());
```

**Comment by saudet** [comment]
Why not use 1.5.7?

**Comment by suhakopan** [comment]
> Why not use 1.5.7?

In version 1.5.7, there is a vulnerability in the ffmpeg package.

**Comment by saudet** [comment]
Please try with the snapshots: http://bytedeco.org/builds/

**Comment by lironghai** [comment]
Cannot resolve org.bytedeco:leptonica-platform:1.82.0-1.5.8-SNAPSHOT

**Comment by lironghai** [comment]
> 请尝试使用快照：[http ://bytedeco.org/builds/](http://bytedeco.org/builds/)


Cannot resolve org.bytedeco:leptonica-platform:1.82.0-1.5.8-SNAPSHOT

**Comment by saudet** [comment]
I see it here: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/leptonica-platform/1.82.0-1.5.8-SNAPSHOT/

You'll need to figure out how to set your build configuration correctly to look for artifacts from that server.
