### ISSUE TITLE
FFmpegFrameGrabber or FFmpegFrameRecorder an or vn option

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#188]
How can I deactivate video or audio in the FFmpegFrameRecorder.
 I tried with setAudioOption("an","") but it didn't work

**Comment by saudet** [comment]
In FFmpegFrameRecorder, we can do that by setting imageWidth, imageHeight, or audioChannels to 0, before calling start(). With FFmpegFrameGrabber, use grabImage() to skip over audio frames.
