### ISSUE TITLE
Deploy for specific platform

### ISSUE THREAD

**Issue by haumacher** [bytedeco/javacv#1880]
Hi,

is there a way to create a deployment for a specific target platform. Currently, when using the proposed approach with the dependency 

```
  <dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.5.7</version>
  </dependency>
```

a really huge JAR (with all dependencies) is built for all supported target platforms. Is there a way to create a smaller JAR for a specific platform like linux-arm-hf?

**Comment by saudet** [comment]
Yes, please refer to https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
