### ISSUE TITLE
can't sign app for mac os

### ISSUE THREAD

**Issue by joseluiskuuc** [bytedeco/javacv#1889]
this is caused by the following files:

<img width="326" alt="Captura de Pantalla 2022-09-14 a la(s) 13 05 54" src="https://user-images.githubusercontent.com/46909828/190230121-872ef991-a7c9-47a5-a876-bbd5e65688fa.png">
<img width="344" alt="Captura de Pantalla 2022-09-14 a la(s) 13 06 02" src="https://user-images.githubusercontent.com/46909828/190230127-06115b38-bdf0-4f96-bf81-4b04d1fa60b3.png">

**Comment by saudet** [comment]
If your application doesn't need those files, simply remove them.

**Comment by joseluiskuuc** [comment]
@saudet thank you, these files are necessary for the operation of the library? or what exactly are they?

**Comment by saudet** [comment]
If you don't know what they are, you probably don't need them. Just delete
them and it should be fine.

**Comment by joseluiskuuc** [comment]
thank you so much !
