### ISSUE TITLE
FFmpeg on jetson

### ISSUE THREAD

**Issue by MMMMMine** [bytedeco/javacv#1894]
hello, my server is jetson nano
--_jetpack:5.0.1_
--_cuda:11.4.14_
what dependencies do I need to get FFmpegFrameGrabber to work with gpu

i use h264_cuvid/hevc_cuvid, it still worked with cpu, this is my dependencies
` <dependency>`
          `  <groupId>org.bytedeco</groupId>`
       `     <artifactId>javacv</artifactId>`
        `    <version>1.5.7</version>`
       ` </dependency>`
  `      <dependency>`
       `     <groupId>org.bytedeco</groupId>`
       `     <artifactId>ffmpeg-platform</artifactId>`
       `     <version>5.0-1.5.7</version>`
`        </dependency>`

**Comment by saudet** [comment]
Check the log for any warnings.

**Comment by MMMMMine** [comment]
> Check the log for any warnings.

there is no warnings

**Comment by MMMMMine** [comment]
> Check the log for any warnings.

no warnings. it worked normally with cpu , not gpu. 
i use this jar run on x86_64-linux , it worked with gpu.

**Comment by MMMMMine** [comment]
@saudet I installed nvidia ffmpeg on jetson nano and run ffmpeg -c:v hevc_nvv4l2dec <input> -vf fps=1 image_%05d.jpg  
it worked without cpu and outputted image successfully , does FFmpegFrameGrabber support it and how to set option ?

**Comment by saudet** [comment]
Hum, it just looks like CUDA wasn't enabled on that platform.
I've just done that in commit https://github.com/bytedeco/javacpp-presets/commit/58776280dcd0af341c93de4299fb4298ad8e136f.
Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by MMMMMine** [comment]
I tried, but it didn't work.
NVIDIA officially states that jetson ffmpeg uses a separate codec module, does that mean it is not accelerated by CUDA?
![image](https://user-images.githubusercontent.com/20126820/192676032-0dc20fba-4260-4600-b951-9d1a867c2cc0.png)

**Comment by saudet** [comment]
We need a libnvcuvid.so.1 library that supports the GPU, yes. I suppose the version of FFmpeg they provide is a proprietary fork of the original project, and we don't have access to the source code, but if they provide binaries for its libraries as well, we can use those with JavaCV and JavaCPP by setting the "org.bytedeco.javacpp.pathsFirst" system property to "true". They need to be for the same exact version of FFmpeg though. If not, you'll need to build the JavaCPP Presets for FFmpeg from source:
https://github.com/bytedeco/javacpp-presets#build-instructions

**Comment by MMMMMine** [comment]
Thank you for your reply. I will continue to explore. This is difficult for me.
