### ISSUE TITLE
Starting two threads running grabber blocks

### ISSUE THREAD

**Issue by shuaiyu-wang** [bytedeco/javacv#1896]
I started two separate threads running Grabber to send the same data to the Input stream. Grabber may not read the Input stream, causing the writing thread to block.(This is normal when it is a single thread)
`PipedInputStream pis = new PipedInputStream();
PipedOutputStream pos = new PipedOutputStream();
pos.connect(pis);
// write thread
pos.write(data);
//grabber thread
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(pis, 0);
grabber.setOption("probesize", "1024*20");
grabber.setFrameRate(30);
grabber.setVideoBitrate(2000000);
grabber.start();`

**Comment by saudet** [comment]
Yes, that's normal. What are you trying to accomplish?

**Comment by shuaiyu-wang** [comment]
Why does multithreading do this? I now want to convert the raw data to RTSP and RTMP stream output, so I started two threads, one to RTSP stream and one to RTMP stream, but found that writing data was blocked.

**Comment by saudet** [comment]
That's sounds like a problem with your network.

**Comment by shuaiyu-wang** [comment]
@saudet It is normal to push either the RTMP stream or the RTSP stream separately, but both will block.

**Comment by saudet** [comment]
That doesn't sound like something that needs threads. Try with only a single thread, and if that works, just keep doing that.

**Comment by shuaiyu-wang** [comment]
@saudet Thank you, finally I changed two threads to one thread processing success.
