### ISSUE TITLE
1920x1440 or higher video couldn't play on Samsung devices, indicating that the file type is not supported

### ISSUE THREAD

**Issue by s2g090123** [bytedeco/javacv#1899]
I am trying to create video via FFmpegFrameRecorder.
The video size is 1920x1440 but it doesn't play on Samsung devices. 
The file type is not supported.
I have tried 1920x1080 and 1024x768, both work.
Or what codec should I set?

Below is my sample code
```kotlin
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        create()
    }

    private fun create() {
        val file = File(getExternalFilesDir("video"), "test.mp4")
        if (file.exists()) {
            file.delete()
        }
        val recorder = FFmpegFrameRecorder(file, 1920, 1440)
        recorder.format = "mp4"
        val converter = AndroidFrameConverter()
        val bitmap = Bitmap.createBitmap(1920, 1440, Bitmap.Config.ARGB_8888)
        recorder.start()
        recorder.record(converter.convert(bitmap))
        converter.close()
        recorder.stop()
        recorder.release()
    }
}
```

Thank you so much!

**Comment by saudet** [comment]
You may want to try to use the "main" profile instead of "baseline" as pointed out by @vonabe at issue https://github.com/bytedeco/javacv/issues/1885#issuecomment-1241019473.

**Comment by s2g090123** [comment]
Sorry, I didn't understand what you said.

Replace `FF_PROFILE_H264_CONSTRAINED_BASELINE` with `FF_PROFILE_H264_MAIN` in `video_c.profile(AVCodecContext.FF_PROFILE_H264_CONSTRAINED_BASELINE)`?

**Comment by saudet** [comment]
Actually, there is no need to add anything to JavaCV to get this working. I've confirmed that, for example, calling `setVideoOption("profile", "main")` before `start()` does set the profile to "main", see  https://trac.ffmpeg.org/wiki/Encode/H.264#Profile.
