### ISSUE TITLE
Ubuntu: Failed to load dynamic library 'my.so': libva-drm.so.1: cannot open shared object

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#1907]
Hi
I am building a so library based on below pre-built libraries from javacv (ffmpeg-linux-x86_64).  
avutil.so.57
avformat.so.59 
avcodec.so.59
swscale.so.6 
swresample.so.4

But when i load this library, i got the error:
_libva-drm.so.1: cannot open shared object_

I am running on Ubuntu system, which is running on Virtual box, host system is Windows.

Thanks.

**Comment by saudet** [comment]
Please provide the whole error message

**Comment by saudet** [comment]
Also please try with the snapshots: http://bytedeco.org/builds/

**Comment by xiaos** [comment]
hi @saudet  I am using it in Flutter, below is the whole error logs.

Building Linux application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'abc.so': libva-drm.so.1: cannot open shared object file: No such file or directory
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23:12)
#2      FFIBridge.initialize (package:video_collage_flutter/ffi_bridge.dart:23:27)
#3      main (package:video_collage_flutter/main.dart:6:13)
#4      _runMain.<anonymous closure> (dart:ui/hooks.dart:134:23)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by xiaos** [comment]
Just checked the flutter/dart, no idea how to set the system property.

**Comment by xiaos** [comment]
Is it because the lib 'libva-drm.so' not exists in Ubuntu?

**Comment by xiaos** [comment]
@saudet  a quick question, i noticed the 'javacv-platofrm.bin' doens't contain ios build, is it because we can use the same as macosx?

**Comment by saudet** [comment]
It's possible, but I don't think so. As usual, contributions are welcome though!

**Comment by saudet** [comment]
Thanks to @silenium-dev, this has been fixed! Please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by saudet** [comment]
Dupicate of https://github.com/bytedeco/javacpp-presets/issues/1289
