### ISSUE TITLE
What is the current way to disable the verbose logging from this library?

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [bytedeco/javacv#1909]
- I see there is an answer at this link on stackoverflow: https://stackoverflow.com/a/49146007/10252133
- `org.bytedeco.javacpp.avutil` does not seem to exist anymore (I am using library version `1.5.7`)

After receiving an answer here, I will add it to the stackoverflow thread.

**Comment by saudet** [comment]
The packages have moved around a bit since 1.5: http://bytedeco.org/news/2019/04/11/beyond-java-and-cpp/

**Comment by Kalin-Rudnicki** [comment]
@saudet I appreciate the link. After looking through it, Im not exactly seeing mention of `avutil`. Do you know where it is located now, or whatever the equivalent is?

**Comment by saudet** [comment]
It`s here: http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/global/avutil.html
