### ISSUE TITLE
grabber.setTimestamp -> grabber.grabImage() is null

### ISSUE THREAD

**Issue by rcpsync** [bytedeco/javacv#1919]
grabber.setTimestamp(readTime);

frame = grabber.grabFrame(false, true, true, false);

or 

frame = grabber.grabImage();

--timestamp----------------------------output-------------------------------------
1:2147483647>>>> frame is not null : org.bytedeco.javacv.Frame@5a7fe64f
2:4294967294>>>> frame is not null : org.bytedeco.javacv.Frame@5a7fe64f
3:6442450941>>>> frame is not null : org.bytedeco.javacv.Frame@5a7fe64f
4:8590034711----frame is null : null
5:8590134834----frame is null : null
6:8590234957----frame is null : null
7:8590335080----frame is null : null
8:8590435203----frame is null : null
9:8590535326----frame is null : null
10:8590635449----frame is null : null
11:8590735572----frame is null : null
12:8590835695----frame is null : null
13:8590935818----frame is null : null
14:8591035941----frame is null : null
15:8591136064----frame is null : null
16:8591236187----frame is null : null
17:8591336310----frame is null : null
18:8591436433----frame is null : null
19:8591536556----frame is null : null
20:8591636679----frame is null : null
21:8591736802----frame is null : null
22:8591836925----frame is null : null
23:8591937048----frame is null : null
24:8592037171----frame is null : null
25:8592137294----frame is null : null
26:8592237417----frame is null : null
27:8592337540----frame is null : null
28:8592437663----frame is null : null
29:8592537786----frame is null : null
30:8592637909----frame is null : null
31:8592738032----frame is null : null
32:8592838155----frame is null : null
33:8592938278----frame is null : null
34:8593038401----frame is null : null
35:8593138524----frame is null : null
36:8593238647----frame is null : null
37:8593338770----frame is null : null
38:8593438893----frame is null : null
39:8593539016----frame is null : null

frequently returns null and specific media (below)

-------------------------------------------------------------------------
General
Complete name                  : E:\[Movie]\[한국영화]\I.Am.King.2012.HDRip.XviD.AC3-JSB.avi
Format                         : AVI
Format/Info                    : Audio Video Interleave
Format profile                 : OpenDML
File size                      : 1.75 GiB
Duration                       : 2 h 1 min
Overall bit rate               : 2 073 kb/s
Writing application            : PotEncoder

Video
ID                             : 0
Format                         : MPEG-4 Visual
Format profile                 : Simple@L1
Format settings, BVOP          : No
Format settings, QPel          : No
Format settings, GMC           : No warppoints
Format settings, Matrix        : Default (H.263)
Codec ID                       : XVID
Codec ID/Hint                  : XviD
Duration                       : 2 h 1 min
Bit rate                       : 1 423 kb/s
Width                          : 720 pixels
Height                         : 336 pixels
Display aspect ratio           : 2.143
Frame rate                     : 24.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Compression mode               : Lossy
Bits/(Pixel*Frame)             : 0.245
Stream size                    : 1.20 GiB (69%)
Writing library                : Lavc52.108.0

-----------------------------
please check.... thanks

**Comment by saudet** [comment]
8590034711 microseconds is over 2 hours, so that looks normal.

**Comment by rcpsync** [comment]
> 
^^; sorry  I miss...

thanks saudet ㅜㅜ
