### ISSUE TITLE
Is there function Video copy cut  (Quickly codec copy cut)? 

### ISSUE THREAD

**Issue by rcpsync** [bytedeco/javacv#1921]
I want to cut the video quickly.

Is there a function to make simple cuts instead of recording (FFmpegFrameGrabber & FFMpegRecoder)?

I am very satisfied with JavaCV.

but FFMpeg not enough functionality.

Let me know... video codec copy cut ??? (simple and quickly)

**Comment by saudet** [comment]
We can easily use the ffmpeg program, if that's what you're looking to do:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
