### ISSUE TITLE
FFmepgCallback don't generate log file

### ISSUE THREAD

**Issue by ggslayer** [bytedeco/javacv#1928]
Hi, when crash in ffmpeg's c code, it will generate a error log file, But, when no crash, ffmepg api return a error, and java layer will throw a exception, the exception catched by my code, In this situation, no ffmpeg error log file will generate, and no detail additional information will print in console, Is this expected? 

If ffmpeg's c code return error, and I can get more information about this error, which can help me more.

**Comment by saudet** [comment]
Please make sure that `FFmpegLogCallback.set()` has been called.

**Comment by ggslayer** [comment]
FFmpegLogCallback.set()  is called in the first line of program, I'm sure.

**Comment by saudet** [comment]
Try to increase the log's verbosity.

**Comment by ggslayer** [comment]
it works, thank you!
