### ISSUE TITLE
FFMPEG-JavaCV fails to open the stream reporting protocol not found 

### ISSUE THREAD

**Issue by rpgomes** [bytedeco/javacv#193]
Hi, I'm trying to open a RTSP Stream with javaCV.

the javaCV lib reports always protocol not found.

I manage to open the RTSP stream using FFPLAY, that reposts the following information:
Metadata:
   title           : RTSP Session
 Duration: N/A, start: 0.000000, bitrate: N/A
   Stream #0:0: Video: h264 (Baseline), yuv420p, 928x480, 50 tbr, 90k tbn, 180k
tbc
   Stream #0:1: Audio: pcm_alaw, 8000 Hz, 1 channels, s16, 64 kb/s

I try to force the format to h264 but without sucess, also ffplay only works if I set the flag -rtsp_transport tcp, I also set that flag in FFMPEGFRAMEGRABER using av_dict_set(options, "rtsp_transport", "tcp", 0);

In ffplay I also note if I try to force any format the library also returns protocol not found.

What can I do to debug?

**Comment by saudet** [comment]
What gets displayed on the console when FFmpegFrameGrabber fails?

**Comment by rpgomes** [comment]
It reports:

"INFO:
org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -1330794
744: Could not open input "rtps://189.26.152.117:554/user=cm&password=cm1888&cha
nnel=1&stream=0.sdp?real_stream". (Has setFormat() been called?)"

calling av_strerror to -1330794744 reports Protocol not found

**Comment by saudet** [comment]
On the console, not in the log. Android doesn't have a console.

**Comment by rpgomes** [comment]
Sorry I don't understand, I'm using javaCv in windows 32 bits with a tomcat
How do I check the console?

**Comment by saudet** [comment]
Ah, TomCat, looks like it's in `C:\program files\apache software foundation\apache-tomcat{ver}\logs\catalina.out`:
http://stackoverflow.com/a/8362343/523744

**Comment by rpgomes** [comment]
I will try to find it, it's not very easy for me.

Can you test with "rtps://189.26.152.117:554/user=cm&password=cm1888&cha
nnel=1&stream=0.sdp?real_stream", this url is online for now

**Comment by saudet** [comment]
Seems to be working fine here if I change "rtps" for "rtsp". "rtps" is not a protocol that exists.
