### ISSUE TITLE
Frame cannot be converted to IplImage

### ISSUE THREAD

**Issue by raaj5671** [bytedeco/javacv#194]
Currently, I cannot convert my frame to IplImage. I am using the latest version of javacv which is 1.0 and my opencv version is 3.0 . I am still newbie to this javacv commands. 
```java
 private IplImage picGrab(FrameGrabber grabber, int ID)
  {
    IplImage im = null;
    try {
        im = grabber.grab();  // take a snap
    }
    catch(Exception e) 
    {  System.out.println("Problem grabbing image for camera " + ID);  }
    return im;
  }  // end of picGrab()
```

**Comment by saudet** [comment]
Try to use `OpenCVFrameConverter`, details here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
