### ISSUE TITLE
Images obtained from FFmpegFrameGrabber are too bright.

### ISSUE THREAD

**Issue by Gamebuster19901** [bytedeco/javacv#1952]
I'm using this code to display a portion of my desktop into a window. In the image below, you can see the actual color of my desktop compared to what is displayed.

How can I correct this?

```java
public static void main(String args[]) throws Exception {
        int x = 0, y = 0, w = 1024, h = 768;
        FFmpegLogCallback.set();
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(":1.0+" + x + "," + y);
        grabber.setFormat("x11grab");
        grabber.setImageWidth(w);
        grabber.setImageHeight(h);
        grabber.start();

        CanvasFrame frame = new CanvasFrame("Screen Capture");
        while (frame.isVisible()) {
            frame.showImage(grabber.grab());
        }
        frame.dispose();
        grabber.stop();
}
```

![image](https://user-images.githubusercontent.com/7155747/205395391-1c4dc3af-17e0-4945-9cc8-1aea78bc61a6.png)

**Comment by saudet** [comment]
That's CanvasFrame doing gamma correction. If you don't need it, make sure
to set the gamma parameter to 1.0.

**Comment by Gamebuster19901** [comment]
Thank you very much, didn't realize there was a second constructor which took a gamma parameter.
