### ISSUE TITLE
How to implement numpy squeeze in JavaCV (remove dimensions of size 1)

### ISSUE THREAD

**Issue by cansik** [bytedeco/javacv#1954]
Is it possible to implement the [numpy squeeze](https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html) method in JavaCV?

The output of the dnn `forward()` method sometimes includes the batch number and is of shape `[1, nc, nr]`, which means we first have to unpack the first dimension before processing the results. In python there is the nice method called `np.squeeze()` to remove dimension of size `1`. How can we implement that in JavaCV? In python you could also just reshape the array, but this does not work in JavaCV:

### Python

```python
>>> import numpy as np
>>> m = np.zeros((1, 200, 300))
>>> m
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])
>>> np.reshape(m, (200, 300))
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
```

### Java

```java
result = result.reshape(result.size(2), result.size(1));
// Leads to: matrix.cpp:1240: error: (-209:Sizes of input arguments do not match) Requested and source matrices have different count of elements in function 'cv::Mat::reshape'
```

Would be great if someone could give me a hint how to unwrap the result, so I can process it by using cols / rows as usual.

**Comment by saudet** [comment]
Ah, yes, it does have some preliminary support for multiple dimensions, but functions like reshape() don't work. I suppose passing around the data might be the best option.
