### ISSUE TITLE
org.bytedeco.opencv.* missing some packages?

### ISSUE THREAD

**Issue by gingerbraden** [bytedeco/javacv#1959]
I am trying to build an app in Java which uses saliency implementations from OpenCV, but while using bytedeco I've come to some problems:

- _org.bytedeco.opencv.opencv_imgproc_ seems to be missing Imgproc
- _org.bytedeco.opencv.opencv_core_ seems to be missing Core
- the opencv_imgcodecs package seems to be missing alltogether

My dependencies in Gradle are set like this:
`implementation group: 'org.bytedeco', name: 'javacpp', version: '1.5.8'`
`implementation group: 'org.bytedeco', name: 'javacpp-presets', version: '1.5.8'`
`implementation group: 'org.bytedeco', name: 'javacv', version: '1.5.8'`

And the code I'm trying to run is as simple as:

    public static void main(String[] args) {
    
            Mat image = Imgcodecs.imread("image.jpg");
    
            Mat imageHSV = new Mat();
            Imgproc.cvtColor(image, imageHSV, Imgproc.COLOR_BGR2HSV);
    
            StaticSaliencySpectralResidual saliency = StaticSaliencySpectralResidual.create();
    
            Mat saliencyMap = new Mat();
            saliency.computeSaliency(imageHSV, saliencyMap);
    
            Mat outputImage = new Mat();
            Core.addWeighted(image, 0.5, saliencyMap, 0.5, 0.0, outputImage);
    
        }

But I can't get Imgcodecs, Imgproc and Core to work...

**Comment by saudet** [comment]
Why do you say they are missing? We can use them if you want to: 
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by gingerbraden** [comment]
I see that, but I checked the [Java API documentation](http://bytedeco.org/javacpp-presets/opencv/apidocs/) and all three of the classes I mentioned are missing. 

- Imgproc package is there, but the function _cvtColor_ is missing
- Core package is there, but the function _addWeighted_ is missing
- package Imgcodec is missing

**Comment by saudet** [comment]
Those classes are in the org.opencv package, not the org.bytedeco.opencv one.

**Comment by gingerbraden** [comment]
That is true, but I have problems combining them - f.e. passing org.opencv.core.Mat into a org.bytedeco.opencv.opencv_saliency.StaticSaliencySpectralResidual
![image](https://user-images.githubusercontent.com/99813901/209414838-9d71339c-6a19-4fd8-95dc-cac85aa61fb4.png)

**Comment by saudet** [comment]
We can use OpenCVFrameConverter for that.

**Comment by gingerbraden** [comment]
Yes! **That's it, that works like a charm**, thank you so much. Now I have to solve the "No implementation found for org.opencv....."

**Comment by saudet** [comment]
Please make sure that `Loader.load(opencv_java.class)` has been called:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#documentation

**Comment by gingerbraden** [comment]
It has been, and now I'm digging through old issues to solve the _java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopencv_core.so" not found_ error

**Comment by saudet** [comment]
Are you trying this on Android? The plugin doesn't support native libraries in JAR files but we can work around that:
https://github.com/bytedeco/gradle-javacpp#the-platform-plugin

**Comment by gingerbraden** [comment]
Yes, I am trying this on Android.  After adding the code from the Platform Plugin chapter to build.gradle file, I am getting a
_The 'java' plugin has been applied, but it is not compatible with the Android plugins._
error

**Comment by saudet** [comment]
That's correct, the Java plugin doesn't work with Android. That bit isn't for Android. Please read below that.

**Comment by gingerbraden** [comment]
Shoot... So there is no way of using OpenCV's Saliency modules on Android, even with using ByteDeco/JavaCPP ?

**Comment by saudet** [comment]
Yes, it should work fine. If you're looking for an existing sample project to use as template, there's this one:
https://github.com/bytedeco/sample-projects/tree/master/JavaCV-android-example

**Comment by gingerbraden** [comment]
Managed to make it work, all fault was on my side. 
- import org.bytedeco.opencv.opencv_core contains Mat
- after all I don't need the imgproc class, but it also is there.
