### ISSUE TITLE
centos7  org.bytedeco.javacv.FrameGrabber$Exception: read() Error: Could not read frame in start().

### ISSUE THREAD

**Issue by z331235161** [bytedeco/javacv#1964]
Multiple videos are merged into one video
windows10 normal
centos7 x86_64 exception
org.bytedeco.javacv.OpenCVFrameGrabber.start();
![image](https://user-images.githubusercontent.com/29884219/210774599-26f7a066-4e73-4ff1-8213-fed7d2e1d648.png)

Can't read mat
![image](https://user-images.githubusercontent.com/29884219/210774732-53aa2a87-3c30-4ae9-8e75-97c2739685c4.png)

maven 
![image](https://user-images.githubusercontent.com/29884219/210776816-68aca567-2102-4012-9532-83e365d9073e.png)

**Comment by saudet** [comment]
Please try again with version 1.5.8.

**Comment by z331235161** [comment]
unable to run

**Comment by saudet** [comment]
FFmpeg usually works a lot better for video capture than OpenCV. Please try to use FFmpegFrameGrabber instead.

**Comment by saudet** [comment]
Please let me know if you encounter any problems with FFmpegFrameGrabber! Thanks
