### ISSUE TITLE
FFmpegFrameRecorder blocked when no network

### ISSUE THREAD

**Issue by ggslayer** [bytedeco/javacv#1966]
Hi,  when FFmpegFrameRecorder recording av frames,  I disconnect the network, then, the record method blocked and never returned.
Is there some method to set a read/write timeout to the stream? thank you

**Comment by saudet** [comment]
We can set the timeout via options, yes.

**Comment by ggslayer** [comment]
thank you!   fixed~~

**Comment by saudet** [comment]
FYI https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java
