### ISSUE TITLE
Get fatal signal 11 (SIGSEGV) when creating a Mat

### ISSUE THREAD

**Issue by 7bitex** [bytedeco/javacv#197]
I'm using JavaCV with Android and I want to convert a drawable resource to Mat.

```java
Bitmap bitmapRoad = BitmapFactory.decodeResource(this.getResources(), R.drawable.road);
Frame frameRoad = converterBitmapFrame.convert(bitmapRoad);
Mat matRoad = converterFrameMat.convert(frameRoad);
```

However I got an error which says "**Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 15549**". I removed all the code and left just one line `Mat mat = new Mat();`, it also threw the same error. What's the possible reason of this error?

**Comment by saudet** [comment]
Even with the binaries at https://github.com/bytedeco/javacv/issues/179#issuecomment-122510578?

**Comment by 7bitex** [comment]
@saudet wow it works. Thanks!
