### ISSUE TITLE
Some questions about FFmpegFrameGrabber

### ISSUE THREAD

**Issue by kana-cr** [bytedeco/javacv#1978]
grabKeyFrame Does GrabKeyFrame capture I-frames in the video?Leafing through some documents did not see the specific explanation, directly look at the source is not intuitive

**Comment by saudet** [comment]
That's what it's supposed to be doing, yes, but it doesn't work if the video doesn't have any key frames...

**Comment by kana-cr** [comment]
Thanks for your answer!
