### ISSUE TITLE
Rotate horizontal video to vertical when streaming to RTMP using FFmpegFrameRecorder

### ISSUE THREAD

**Issue by bgiori** [bytedeco/javacv#198]
I'm currently using FFmpegFrameRecorder to stream to a RTMP server. The video comes out horizontal when watching the stream even though I set the height and width with appropriate dimensions for vertical video. I was wondering if there was a way to stream the video vertically without using IplImages and rotating each frame (IplImage gives me a segfault when I try to create one, but that is a separate issue). Any insight would be greatly appriciated!

Thanks

**Comment by saudet** [comment]
Duplicate of #164. It would be possible with `avfilter`, would you like to look into this? It would be helpful to a lot of people. :)

**Comment by bgiori** [comment]
I would If I could :( Ive decided to try to rotate the IplImage approach but have been interrupted by #199
