### ISSUE TITLE
When I use the filter to set the video to have multiple paths, the resulting video turned into three identical images of the filter effect

### ISSUE THREAD

**Issue by zxyFalcon** [bytedeco/javacv#1983]
When I use the filter to set the video to have multiple paths, for example "split [main][tmp]; [tmp] crop=iw:ih/2:0:0, vflip[flip]; [main][flip] overlay=0:H/2" or "[0:v]scale=iw/2:ih/2[a];[1:v][a]overlay=30:30[v]", the resulting video turned into three identical images of the filter effect

**Comment by saudet** [comment]
Please try to call `recorder.record(frame, filter.getPixelFormat())` instead of `recorder.record(frame)`.

**Comment by saudet** [comment]
Duplicate of #1984
