### ISSUE TITLE
java.lang.NoClassDefFoundError:org.bytedeco.javacpp.Pointer

### ISSUE THREAD

**Issue by jetamie** [bytedeco/javacv#1988]
> I add these two parameters - Dorg.bytedeco.javacpp.maxbytes=1.5G -Dorg.bytedeco.javacpp.maxphysicalbytes=1.5G, but I get the NoClassDefFoundError exception

**Comment by jetamie** [comment]
javacv version:1.5.8

**Comment by jetamie** [comment]
maven dependence
javacv:1.5.8
ffmpeg-platform-gpl:5.1.2-1.5.8
javacv-platform:1.5.8

**Comment by jetamie** [comment]
I found that converting G to k would work

**Comment by saudet** [comment]
The number needs to be an integer, try 1500MB instead.
