### ISSUE TITLE
 Converting a byte array to a mat for the first time takes a lot more time than subsequent conversions

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#1994]
When I convert the byte array to mat for the first time it takes more than 3 seconds.And the subsequent conversion of the byte array to mat is even less than 1 millisecond.

**Comment by saudet** [comment]
You may want to try GraalVM Native for that use case.

**Comment by saudet** [comment]
There's a sample project for that here: https://github.com/bytedeco/sample-projects/tree/master/opencv-stitching-native

**Comment by CJL6015** [comment]
Tanks for your reply! Does initialization only need to be done once? Or does it need to be reinitialized after a while

**Comment by CJL6015** [comment]
Thanks for your reply! Does initialization only need to be done once? Or does it need to be reinitialized after a while?

**Comment by saudet** [comment]
That's not related to JavaCV. You'll need to ask about that upstream: https://github.com/openjdk/jdk
