### ISSUE TITLE
FFmpeg decoding leads to invalid data when processing input with D3D11VA and DXVA2 hw acceleration

### ISSUE THREAD

**Issue by streamingdv** [bytedeco/javacv#2016]
The last 2 weeks I was trying to figure out why I can't decode some h264 keyframes when using D3D11VA or DXVA2 hw acceleration and I'm still not sure if I'm on the right track but I guess I found the potential issue but not sure.

In my project I use JavaCV 1.5.8 to decode an h264 stream and everything works fine when using sw decoding or cuvid decoding but as soon as I use D3D11VA or DXVA2 hw acceleration some key frames can't be decoded anymore because I will receive an "_invalid data found when processing input_" when calling "**_avcodec_send_packet_**".  I have build a minimal reproducable example which can be downloaed from [here](https://github.com/bytedeco/javacv/files/11368150/Example.zip). Here is a [link](https://github.com/bytedeco/javacv/files/11368144/h264_test_key_frame.txt) to just the h264 keyframe with sps and pps prepended.

To run the project just perform a .\gradlew build and afterwards a .\gradlew run. The test project is trying to decode one h264 keyframe (with sps and pps). If you run the example the last log message shown in the terminal should be "SUCESS with HW decoding". The hardware decoder can be changed via the HW_DEVICE_TYPE variable in the App.java class. To disable hw acceleration just set the USE_HW_ACCEL to false. You can force the decoder to spit out the frame by changing USE_AV_EF_EXPLODE to false.

After countless of hours researching on the internet I think I finally found out what's the issue. On another project here on github I found this issue

https://github.com/wang-bin/QtAV/issues/923

which is exactly the problem I'm experiencing as well. It seems that in [h264dec.h](https://github.com/FFmpeg/FFmpeg/blob/561746591660b456e092324f03d393d6dd9147b1/libavcodec/h264dec.h#L62) there is a variable called MAX_SLICES which is set to 32. This MAX_SLICES value is used here [dxva2_h264.c](https://github.com/FFmpeg/FFmpeg/blob/561746591660b456e092324f03d393d6dd9147b1/libavcodec/dxva2_h264.c#L478). I also found this interesting entry which seems to be related to that issue

https://trac.ffmpeg.org/ticket/9771#no1

I'm not an expert in ffmpeg so my assumptations can be wrong but I think my issue is related to the problems described above. Would it be possible to increase the MAX_SLICES to something higher like 128 or 256 with a patch in general? Or are there any other possibilities? As I get this h264 stream frorm 3rd Party I can't change the format but I don't think it will be possible to use D3D11VA or DXVA2 otherwise with this small max slices support.

**Comment by saudet** [comment]
Sounds like a small enough change. Please do open a pull request with a patch, or actually a call to sedinplace in cppbuild.sh is probably easiest.

**Comment by streamingdv** [comment]
@saudet okay sounds good. I made myself a bit familiar with the cppbuild script and as far as I have understood everything correctly this line should do the trick

`sedinplace 's/#define MAX_SLICES 32/#define MAX_SLICES 256/g' ffmpeg-*/libavcodec/h264dec.h`

Where exactly should I place this line? Below this [line maybe](https://github.com/bytedeco/javacpp-presets/blob/f568ac42d10175de09d73690cc7e0497625b2458/ffmpeg/cppbuild.sh#LL122C1-L122C80)? Are there any preferences?

**Comment by saudet** [comment]
Yes, that's perfect!

**Comment by streamingdv** [comment]
@saudet small pull request available

https://github.com/bytedeco/javacpp-presets/pull/1349

**Comment by streamingdv** [comment]
Is there anything that needs to be done on my side in order to get my small pull request merged? I'm not in a hurry and I totally understand that there are other priorities or maybe fixed times when things are merged. Just want to make sure I did not forget anything :)

**Comment by saudet** [comment]
Nope, it's fine! Thanks. I've just merged, so please give it a try with the snapshots: http://bytedeco.org/builds/

**Comment by streamingdv** [comment]
Problem solved :)
