### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: no jniavdevice in java.library.path

### ISSUE THREAD

**Issue by CJL6015** [bytedeco/javacv#2018]
The program encountered an error while attempting to load ffmpeg.
`Loader.load(org.bytedeco.ffmpeg.ffmpeg.class)`

![image](https://user-images.githubusercontent.com/42272971/236119508-68b043c6-930b-4c29-bba9-307dafded439.png)

**Comment by saudet** [comment]
You'll need to install the required libraries.
