### ISSUE TITLE
Crop frame before saving in recorder 

### ISSUE THREAD

**Issue by skatash** [bytedeco/javacv#202]
Hi Samuel,

Is it possible to crop video frame before saving it in recorder  (in record method) ?
Current code is scaling to it any size very well.

Something like this which we can achieve from ffmpeg using the command:
`crop=in_w-100:in_h-100:100:100`

Can you please guide, is there any way to achieve this in record method ?

**Comment by saudet** [comment]
We will be able to use those kinds of command when `avfilter` is supported. See issue #164 for some ideas about where to get started. Thank you!

We can also use ROIs of OpenCV to achieve the same effect. See issue #180 for an example of that.
