### ISSUE TITLE
<classifier>macosx-x86_64</classifier> is not work for me 

### ISSUE THREAD

**Issue by jurimengs** [bytedeco/javacv#2029]
i learned some issues like [https://github.com/bytedeco/javacv/issues/1493], but it's not work for me 

![image](https://github.com/bytedeco/javacv/assets/10648133/f0bddff9-3db2-492d-8b33-1e9af7f4afc6)

**Comment by saudet** [comment]
Please upgrade to the latest version.

**Comment by jurimengs** [comment]
thank you ..but , it's still not working, 

<img width="1201" alt="image" src="https://github.com/bytedeco/javacv/assets/10648133/0e31eb04-fdae-4ef9-be55-5528588c951f">

**Comment by jurimengs** [comment]
more information , I try to use javacv only , so I import something like :
    <properties>
        <javacv.version>1.5.8</javacv.version>
        <javacpp.version>${javacv.version}</javacpp.version>
    </properties>

<dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>${javacpp.version}</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>openblas</artifactId>
            <version>0.3.21-${javacpp.version}</version>
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>opencv</artifactId>
            <version>4.6.0-${javacpp.version}</version>
            
        </dependency>

        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>${javacv.version}</version>
        </dependency>
        <dependency>

            <groupId>org.bytedeco</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>5.1.2-${javacpp.version}</version>
            
            
        </dependency>
</dependencies>

**Comment by jurimengs** [comment]
key is  : "<classifier>macosx-x86_64</classifier>"

without this classifier it works well like :
<img width="829" alt="image" src="https://github.com/bytedeco/javacv/assets/10648133/00ba0377-247f-43dd-bedc-5c4818b34a3d">

but wrong when I use it like :
![Uploading image.png…]()

IDE show me : "Cannot resolve org.bytedeco:ffmpeg-platform:5.1.2-1.5.8 "

**Comment by jurimengs** [comment]
and I tried remove maven repository many times and reload all  maven projects ,  yet it's still not work

**Comment by jurimengs** [comment]
ok , tks
