### ISSUE TITLE
Error occurred when recording  from flv video stream to mp4

### ISSUE THREAD

**Issue by Snow-Chen** [bytedeco/javacv#2033]
when i use FFmpegFrameRecorder record video from flv, and try to save video as mp4 format, unfortually the mp4 file can not play succeessly
when i run commad "ffmpeg -i hello.mp4", there is error like this:
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000019b4822d740] moov atom not found

![image](https://github.com/bytedeco/javacv/assets/7801122/b4738ceb-620e-4b3a-b9dd-1e68016c5615)

**Comment by saudet** [comment]
You'll need to make sure FFmpegFrameRecoder.stop() gets called.

**Comment by Snow-Chen** [comment]
> You'll need to make sure FFmpegFrameRecoder.stop() gets called.

yes，I do call FFmpegFrameRecorder.stop()
![image](https://github.com/bytedeco/javacv/assets/7801122/a7ca4435-8f91-466c-9c48-0384b87cdc1d)
![image](https://github.com/bytedeco/javacv/assets/7801122/02a4ec99-0d4d-47aa-8d6d-73a478405c16)

There are other possible reasons cause this problem?

**Comment by saudet** [comment]
Make sure you're not using OutputStream, the mp4 format doesn't support streams well.

**Comment by Snow-Chen** [comment]
> Make sure you're not using OutputStream, the mp4 format doesn't support streams well.

almost all the video format except avi can not work，I have tried mp4 wmv flv
I use FFmpegFrameGrabber to grabber frame from flv stream address like "http://xxx.flv”
then try to record frame and save to local mp4 file by FFmpegFrameRecoder

FFmpegFrameRecorder(String filename, int imageWidth, int imageHeight, int audioChannels)

Isn't that supported?

**Comment by Snow-Chen** [comment]
hi saudet, thank you for your help.
I've found out the reason for the failture. It's my mistake.
**FFmpegFrameRecoder.stop() should be called before FFmpegFrameRecoder.release()**
