### ISSUE TITLE
how to  change frame rate and keep duration unchanged

### ISSUE THREAD

**Issue by Snow-Chen** [bytedeco/javacv#2034]
Hi, I use FFmpegFrameGrabber to grabber frame from flv stream address like "[http://xxx.flv”](http://xxx.xn--flv-9o0a/)
then try to record frame and save to local mp4 file by FFmpegFrameRecoder

how can i change the fps from 30/s to 10/s, and keep the duration unchanged at same time
In other words,  i want keep aduio stream and drop 2/3  frames of image stream

I have tried FFmpegFrameRecoder.setFrameRate(10);  however the duration of mp4 is tripled of flv

**Comment by saudet** [comment]
We can use the fps filter with FFmpegFrameFilter for that purpose: https://ffmpeg.org/ffmpeg-filters.html#fps-1

**Comment by saudet** [comment]
You can refer to https://github.com/bytedeco/javacv/issues/1398#issuecomment-613208633 for a working example.
