### ISSUE TITLE
Audio Resampling generates wrong output

### ISSUE THREAD

**Issue by crossmo** [bytedeco/javacv#205]
Hi, I am trying to resample a stereo audio stream into a mono one with the following code

```
		FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("au_0.wav");
		FFmpegFrameRecorder recorder = new FFmpegFrameRecorder("au_0.mp4", 300, 300, 1);
		
		grabber.start();
		recorder.start();
		Frame inFrame = null;
		while((inFrame = grabber.grab()) != null){
			recorder.recordSamples(0, 0, inFrame.samples);
		}
		grabber.stop();
		grabber.release();
		recorder.stop();
		recorder.release();
```

The output file can be played but the audio sounds like an alien talking :). I did check the source code recordSamples in which resampling was implemented, but don't know why the result is not correct.

**Comment by crossmo** [comment]
I made it work by passing the sample rate of the input audio.

**Comment by saudet** [comment]
Simply calling recorder.record(inFrame); should also work.

**Comment by crossmo** [comment]
I tried record(inFrame), it also works. Thanks.
