### ISSUE TITLE
Cannot locate symbol "av_q2intfloat" referenced by "libjniavutil.so"

### ISSUE THREAD

**Issue by 7bitex** [bytedeco/javacv#206]
I created an instance of `FFmpegFrameGrabber` like

```java
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("...");
```

and an error occurred:

```
08-20 02:32:55.621  21569-21569/org.lab413.visualnav E/art: dlopen("/data/app/org.lab413.visualnav-1/lib/x86/libjniavutil.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "av_q2intfloat" referenced by "libjniavutil.so"...
```

I've installed JavaCV correctly following the steps from [Manual Installation](https://github.com/bytedeco/javacv#manual-installation). I'm using JavaCV with

 - Gradle 1.2.3
 - Android SDK version 22
 - Android build tools 22.0.1
 - Android Studio 1.3.1
 - Genymotion with Android 5.1 (x86)

**Comment by 7bitex** [comment]
I tried with a real ARM device running Android 5.0.1 instead of an emulator, and the error didn't occur. But here comes another error:

```
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
```

**Comment by saudet** [comment]
It's an issue with Android Studio's build system...
