### ISSUE TITLE
Video compress and trim

### ISSUE THREAD

**Issue by Theselman** [bytedeco/javacv#2069]
Can I do video compression and trimming with this library without any problems? I searched a bit but couldn't find the information I wanted.

**Comment by saudet** [comment]
It sounds like something we can do with FFmpegFrameGrabber, FFmpegFrameFilter, and FFmpegFrameRecorder, but also potentially more easily with the ffmpeg program: 
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by Theselman** [comment]
thank you for your response. Will you continue to support this library? It's important for me

**Comment by saudet** [comment]
What do you mean by support?

**Comment by Theselman** [comment]
i meant the library will continue to be updated and improved

**Comment by saudet** [comment]
That should happen, yes
