### ISSUE TITLE
FFmpegFrameGrabber cannot open file on Android

### ISSUE THREAD

**Issue by 7bitex** [bytedeco/javacv#207]
I created an instance of `FFmpegFrameGrabber` like

```java
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(mFileUri.getPath());
```

and when I called `grabber.start()`, it threw an exception which says `avformat_open_input() error -13: Could not open input "/storage/emulated/0/DCIM/Camera/VID_20150820_152542.mp4". (Has setFormat() been called?)`.

I found a similar issue [here](https://github.com/bytedeco/javacv/issues/68) but my video file is just 7 MB in size. What's the possible reason for this problem?

**Comment by saudet** [comment]
Sounds like a permission problem. Please make sure your app has access to the "storage" device.

**Comment by 7bitex** [comment]
@saudet You are right... Thanks very much.
