### ISSUE TITLE
Do you have yunet and sface?

### ISSUE THREAD

**Issue by 12341234-yangboran** [bytedeco/javacv#2075]
Do you have yunet and sface?

**Comment by 12341234-yangboran** [comment]
I want to use FaceDetectorYN in javacv，but I can`t find it.

**Comment by saudet** [comment]
This?
https://javadoc.io/static/org.bytedeco/opencv/4.5.5-1.5.7/org/opencv/objdetect/FaceDetectorYN.html

**Comment by saudet** [comment]
Let me know if you're having any issues with that class! Thanks
