### ISSUE TITLE
problem with rtsp_transport = http

### ISSUE THREAD

**Issue by rjtruitt** [bytedeco/javacv#208]
I'm trying to stream rtsp through a ssh tunnel with my code and i'm able to do so with ffplay/ffmpeg using -rtsp_transport=http.  However, if i set this option in the code it appears to ignore it.    Any ideas?  I can add more code if necessary.. 

        FFMpegFrameGrabber cameraFeed;

        cameraFeed = new FFmpegFrameGrabber(this.cameraURL);

        if (protocol.equals("rtsp") && sshTunneled) {
            cameraFeed.setVideoOption("rtsp_transport", "http");
        }

        cameraFeed.start();
        while (isRecording) {
            if (cameraFeed != null) {
                cameraFrame = cameraFeed.grab();

                recordFrame(cameraFrame);
            } else {
                logger.debug("Camera feed is null, exiting recorder");
                stop();
            }
        }

This is what i'm trying to achieve 
ffplay -rtsp_transport http -i "rtsp://localhost:9111/user=admin&password=somerandompassword&channel=1&stream=0.sdp"

the sshtunnel works with my regular piece of garbage foscam over http but can't get it to work with rtsp.  Using Jsch.

            Session sshSession = jsch.getSession(sshUser, sshHost, sshPort);
            sshSession.setPassword(sshPass);
            sshSession.setUserInfo(new SSHUserInfo());
            sshSession.connect();
            sshSession.setPortForwardingL(localPort, endPointHost, endPointPort);

But like i was saying i can create the port forward in the app then use ffplay to get to the stream (while the grabber is still trying to connect) so i know it's not the ssh tunnel code itself.  Is http supported or is it just udp/tcp?

Thanks ahead of time,
Robert Truitt

**Comment by saudet** [comment]
It sounds like rtsp_transport is a format option, so try to call `setOption("rtsp_transport", "http")` instead.

**Comment by rjtruitt** [comment]
Awesome man that worked great! I appreciate the super fast response!  Have a great weekend!
