### ISSUE TITLE
Frames convert to Mats  issue

### ISSUE THREAD

**Issue by Vansonccc** [bytedeco/javacv#2089]
Hi, I am trying to grab the video first frame of every second and then convert to mat to calculate the similarity with OpenCV, but I got the same mat from different frames(I printed the address of Mat). Anyone know what is wrong with this test code?
![image](https://github.com/bytedeco/javacv/assets/110795840/4a757aad-1022-45a5-950d-68417254fb16)
![image](https://github.com/bytedeco/javacv/assets/110795840/38b9112e-f067-4f2b-adb5-570dee030cc9)

**Comment by saudet** [comment]
That's what it should do. What's the issue?

**Comment by Vansonccc** [comment]
> issue

I assume that different Frame should covert to different Mat, but right now I got same Mat from different Frames. How can I get different Mat from Video with FFmpegFrameGrabber( I think grabber has higher performance than VideoCapture )?

I also did i using VideoCapture, and I got different Mat from different timeStamp
![image](https://github.com/bytedeco/javacv/assets/110795840/06c83d35-d024-41a6-8e91-cca67b68f87f)
![image](https://github.com/bytedeco/javacv/assets/110795840/61e810a8-fa63-4f3e-9289-7dfd59953a71)

**Comment by saudet** [comment]
If you prefer the way VideoCapture does it, just keep using that. Either way is fine

**Comment by Vansonccc** [comment]
> If you prefer the way VideoCapture does it, just keep using that. Either way is fine

I prefer using grabber because grabber has higher performance obviously, that's why I want to figure out How to get different Mat from Video with grabber. lol

**Comment by saudet** [comment]
That's most likely the reason why it's faster

**Comment by Vansonccc** [comment]
> If you want to get a different Mat for each frame, you could call something like `mat.clone()` to get a copy.
It works! Thank you so much
