### ISSUE TITLE
Problems capturing videos

### ISSUE THREAD

**Issue by Aurori** [bytedeco/javacv#209]
Hy there

I'm trying to get a video input from an endoscope USB-Camera. From your code exaples I get a video via integrated webcam (of laptop) also a USB-Microscope-Cam is working. Sadly an endoscope USB-Camera wont work. There is no Error-Message just the minimizied Frame. With the endoscope USB-Cam it should be possible also to capture in HD-Format (1280x720) - there are no higher formats implemented by now? May you have any idea if you see the Video Spy-Log-File:
```
VIDEOINPUT SPY MODE!

SETUP: Looking For Capture Devices
SETUP: 0) Endoscope 
SETUP: 1) Integrated Webcam 
SETUP: 2 Device(s) found

***** VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****
SETUP: Setting up device 0
SETUP: Endoscope
SETUP: Couldn't find preview pin using SmartTee
SETUP: Default Format is set to 640 by 480 
SETUP: trying requested format RGB24 @ 640 by 480
SETUP: trying format RGB24 @ 640 by 480
SETUP: trying format RGB32 @ 640 by 480
SETUP: trying format RGB555 @ 640 by 480
SETUP: trying format RGB565 @ 640 by 480
SETUP: trying format YUY2 @ 640 by 480
SETUP: Capture callback set
SETUP: Device is setup and ready to capture.


SETUP: Disconnecting device 0
SETUP: freeing Grabber Callback
SETUP: freeing Grabber
SETUP: freeing Control
SETUP: freeing Media Type
SETUP: removing filter NullRenderer...
SETUP: filter removed NullRenderer
SETUP: removing filter Sample Grabber...
SETUP: filter removed Sample Grabber
SETUP: removing filter AVI Decompressor...
SETUP: filter removed AVI Decompressor
SETUP: removing filter Smart Tee...
SETUP: filter removed Smart Tee
SETUP: removing filter Endoscope...
SETUP: filter removed Endoscope
SETUP: freeing Capture Graph
SETUP: freeing Main Graph
SETUP: Device 0 disconnected and freed
```

**Comment by saudet** [comment]
We can set the resolution by calling setImageWidth() and setImageHeight()
before calling start().

**Comment by Aurori** [comment]
Hmm.. dos not make any change...
But in the Spy-Log, does it looks good or is anything pointing on a issue with the cam?

**Comment by saudet** [comment]
It just looks like your camera doesn't work with the default 640x480
resolution that is used as a workaround for other issues on some webcams...

You could also try OpenCVFrameGrabber or FFmpegFrameGrabber. One of them
might work better in your case.

**Comment by saudet** [comment]
What does the log look like when you try to call setImageWidth() and setImageHeight() before calling VideoInputFrameGrabber.start()?

**Comment by saudet** [comment]
Given the lack of feedback, I'm guessing that calling setImageWidth() and setImageHeight() before start() fixes this issue. Let me know if it still doesn't work though, thanks!
