### ISSUE TITLE
If a frame is Grabbed from an .h264 stream and inserted into a list, it replaces all other list entries before it. 

### ISSUE THREAD

**Issue by PolarityFive** [bytedeco/javacv#2090]
```
try (FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new ByteArrayInputStream(inputStream));
                Java2DFrameConverter converter = new Java2DFrameConverter()) {
            LinkedList<CustomFrame> dummyList = new LinkedList<>();
            grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);
            grabber.start();

            for (CustomFrame customFrame : someList) {
                CustomFrame dummyFrame = new Frame();

                org.bytedeco.javacv.Frame takenFrame = grabber.grabImage();
                dummyFrame.setJavaCVFrame(takenFrame);
                dummyFrame.setBufferedImage(converter.convert(takenFrame));
                dummyList.addLast(dummyFrame);
            }
            grabber.stop();
            return dummyList;
        }
```

Basically the title. 

Code has been modified due to security/privacy reasons. (e.g `someList`.  This loop is correct. Pay no attention to it.)

`DummyFrame` class contains a field to store a JavaCV frame and another field to store the converted `BufferedImage`.
What's happening is that every time a `dummyFrame`is inserted in the `dummyList`, all buffered images in the previous dummyList entries are replaced with the latest one inserted. 

Input stream is correct.
I have verified that grabber.grabImage() does indeed pull a different frame every time. I also store them on disk and have verified I get the expected result. 

The problem only exists when the `BufferedImage` is added in memory. 

Any ideas about what's happening?

**Comment by saudet** [comment]
The image buffers are reused for efficiency. If you need to hold multiple images in memory, you'll have to create copies.

**Comment by PolarityFive** [comment]
> The image buffers are reused for efficiency. If you need to hold multiple images in memory, you'll have to create copies.

Could you please be more specific? 
That was my first assumption so I copied everything in any way I could think of. The custom objects, the `BufferedImage` the `Frame` e.t.c. 

I can't seem to stop everything getting replaced.

**Comment by PolarityFive** [comment]
Managed to figure out a solution. Instead of trying to save the buffered images, I saved the frames by using `.clone()`. 

That led me to have this issue https://github.com/bytedeco/javacv/issues/599 and I solved that by setting 
`System.setProperty("org.bytedeco.javacpp.maxbytes", "0");`
