### ISSUE TITLE
The built-in ffmpeg has issues: Output low-quality video

### ISSUE THREAD

**Issue by veasion** [bytedeco/javacv#2091]
On the Windows, executing video-related commands through the built-in ffmpeg program in javacv results in severe distortion and a decrease in video quality. Using the officially downloaded ffmpeg to execute the same commands does not have the aforementioned issues. Is there a problem with the built-in ffmpeg.exe in javacv ?

```xml
<dependency>
	<groupId>org.bytedeco</groupId>
	<artifactId>javacv-platform</artifactId>
	<version>1.5.9</version>
</dependency>
```

```java
String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);

String cmd = ffmpeg + " -i input.mp4 -r 25 -ss 00:00:00 -an -y output.mp4";

```

The output vcodec of javacv ffmpeg is mpeg4
>> Video: mpeg4 (mp4v / 0x7634706D)

The output vcodec of official ffmpeg is h264
>>  Video: h264 (High) (avc1 / 0x31637661)

**Comment by saudet** [comment]
You'll need to make sure you're using the same codecs.
