### ISSUE TITLE
how can i set -re params in ffmpeg rtmp push command

### ISSUE THREAD

**Issue by xiezichao** [bytedeco/javacv#2094]
I know can set -re params in ffmpeg command to control read speed, but I do not know how to set this readrate param when I use FFmpeg in JavaCv FFmpegFrameRecorder and FFmpegFrameGrabber ,here is my ffmpeg command
"ffmpeg -re -i 1****.flv -c:v libx264 -c:a aac -f flv "rtmp://****""

**Comment by saudet** [comment]
Duplicate of #1633
