### ISSUE TITLE
compile  javacv:   package android.graphics does not exist

### ISSUE THREAD

**Issue by machh** [bytedeco/javacv#2101]
I am compiling and installing javacv from source code on an aarch64 machine. 

When I execute the following command,
`mvn clean install`

 I encounter the following errors：

`
[ERROR] COMPILATION ERROR :
`
[INFO] -------------------------------------------------------------
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[25,24] package android.graphics does not exist
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[26,24] package android.hardware does not exist
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[42,59] cannot find symbol
  symbol: class Bitmap
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[43,5] cannot find symbol
  symbol:   class Bitmap
  location: class org.bytedeco.javacv.AndroidFrameConverter
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[99,36] cannot find symbol
  symbol:   class Bitmap
  location: class org.bytedeco.javacv.AndroidFrameConverter
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[169,22] cannot find symbol
  symbol:   class Bitmap
  location: class org.bytedeco.javacv.AndroidFrameConverter
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[106,18] cannot find symbol
  symbol:   variable ALPHA_8
  location: class org.bytedeco.javacv.AndroidFrameConverter
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[107,18] cannot find symbol
  symbol:   variable RGB_565
  location: class org.bytedeco.javacv.AndroidFrameConverter
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[108,18] cannot find symbol
  symbol:   variable ARGB_4444
  location: class org.bytedeco.javacv.AndroidFrameConverter
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[109,18] cannot find symbol
  symbol:   variable ARGB_8888
  location: class org.bytedeco.javacv.AndroidFrameConverter
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[174,15] package Bitmap does not exist
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[176,36] package Bitmap does not exist
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[179,36] package Bitmap does not exist
[ERROR] /home/javacv-platform-1.5.3/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java:[185,22] cannot find symbol

`
-------------------------------------------------

It seems like these errors are related to Android, but I am not using an Android environment. 

How can I resolve these errors?

**Comment by saudet** [comment]
If you don't need that class you can simply delete that file.

**Comment by machh** [comment]
OK，
