### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacv.FFmpegFrameGrabber

### ISSUE THREAD

**Issue by txwy112** [bytedeco/javacv#2105]
<dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.5.5</version>
        </dependency>

There is no error reported on the x86 system, but why is this error reported on the arm system

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.9.

**Comment by hbcolorful** [comment]
> org.bytedeco javacv-platform 1.5.5
> There is no error reported on the x86 system, but why is this error reported on the arm system

hi~ 
Has the problem been solved?

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.9
