### ISSUE TITLE
cvLoadImage, cvSmooth, not found

### ISSUE THREAD

**Issue by anishthecoder** [bytedeco/javacv#212]
I'm trying to use this through Eclipse and I have the Maven repository dependencies all set up. But whatever I try, I can't seem to statically import (or find in any of the places that the examples show) the `cvLoadImage`, `cvSmooth` functions. I can't seem to run many of the examples because these functions can't be found

**Comment by saudet** [comment]
Have you tried to copy/paste the sample `pom.xml` file and open it in Eclipse?

**Comment by saudet** [comment]
I'm guessing the sample `pom.xml` file did the job, but if not, please let me know, thanks!

**Comment by anishthecoder** [comment]
Yes! thank you.
