### ISSUE TITLE
linker error _libusb_init when building the example from the README

### ISSUE THREAD

**Issue by xuloo** [bytedeco/javacv#213]
Building the example in the README using maven and copying/pasting the pom and code results in the following error.

dyld: lazy symbol binding failed: Symbol not found: _libusb_init
  Referenced from: /private/var/folders/rn/45x232q16n59vk0w9fg0tkkh0000gp/T/javacpp190633412087316/libdc1394.22.dylib
  Expected in: flat namespace

My limited reasoning suggests that something isn't linked from libusb - but not sure what, or how to fix it (DYLD_LIBRARY_PATH entry?)

**Comment by saudet** [comment]
Do you need to use libdc1394? Just ignore that if you don't need it.
