### ISSUE TITLE
CUDA org.bytedeco.opencv.opencv_dnn.Net.forward error: (-217:Gpu API call) invalid device function in function 'make_policy'

### ISSUE THREAD

**Issue by gareth-edwards** [bytedeco/javacv#2132]
I am getting this error:

Error in Main : OpenCV(4.7.0) /__w/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv-4.7.0/modules/dnn/src/cuda/execution.hpp:52: error: (-217:Gpu API call) invalid device function in function 'make_policy'
OpenCV(4.7.0) /__w/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv-4.7.0/modules/dnn/src/cuda/execution.hpp:52: error: (-217:Gpu API call) invalid device function in function 'make_policy'
java.lang.RuntimeException: OpenCV(4.7.0) /__w/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv-4.7.0/modules/dnn/src/cuda/execution.hpp:52: error: (-217:Gpu API call) invalid device function in function 'make_policy'
at org.bytedeco.opencv.opencv_dnn.Net.forward(Native Method)

Hope this is all the detail to help explain/resolve. Many thanks!

pom.xml:

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.5.9</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>opencv-platform-gpu</artifactId>
			<version>4.7.0-1.5.9</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>cuda-platform</artifactId>
			<version>12.1-8.9-1.5.9</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>cuda-platform-redist</artifactId>
			<version>12.1-8.9-1.5.9</version>
		</dependency>

$nvidia-smi -a :

==============NVSMI LOG==============

Timestamp                                 : Fri Nov 24 06:00:43 2023
Driver Version                            : 525.105.17
CUDA Version                              : 12.0

Attached GPUs                             : 1
...

opencv_core.getBuildInformation().getString() :

General configuration for OpenCV 4.7.0 =====================================
  Version control:               ab435e3

  Extra modules:
    Location (extra):            /__w/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv_contrib-4.7.0/modules
    Version control (extra):     ab435e3

  Platform:
    Timestamp:                   2023-06-03T00:01:50Z
    Host:                        Linux 5.15.0-1038-azure x86_64
    CMake:                       3.24.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /opt/rh/devtoolset-9/root/usr/bin/gmake
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (14 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (30 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (5 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                11
    C++ Compiler:                /opt/rh/devtoolset-9/root/usr/bin/g++  -std=c++11 -m64 (ver 9.3.1)
    C++ flags (Release):         -w   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -w   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /opt/rh/devtoolset-9/root/usr/bin/gcc  -m64
    C flags (Release):           -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    Linker flags (Debug):        -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    ccache:                      YES
    Precompiled headers:         NO
    Extra dependencies:          m pthread cudart_static dl rt nppc nppial nppicc nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/lib64
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco barcode bgsegm bioinspired calib3d core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev dnn dnn_superres face features2d flann highgui img_hash imgcodecs imgproc intensity_transform java mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid saliency shape stitching structured_light superres text tracking video videoio videostab wechat_qrcode xfeatures2d ximgproc xphoto
    Disabled:                    ccalib datasets dnn_objdetect dpm freetype fuzzy gapi hfs line_descriptor reg rgbd stereo surface_matching world xobjdetect
    Disabled by dependency:      -
    Unavailable:                 alphamat cvv hdf julia matlab ovis python2 sfm ts viz
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         YES

  GUI:                           GTK2
    GTK+:                        YES (ver 2.24.31)
      GThread :                  YES (ver 2.56.1)
      GtkGlExt:                  NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.13)
    JPEG:                        build-libjpeg-turbo (ver 2.1.3-62)
      SIMD Support Request:      NO
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build Jasper (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Lapack:                      YES (/root/.javacpp/cache/openblas-0.3.23-1.5.9-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libopenblas.so)
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)

  NVIDIA CUDA:                   YES (ver 12.1, CUFFT CUBLAS)
    NVIDIA GPU arch:             50
    NVIDIA PTX archs:            50

  cuDNN:                         YES (ver 8.9.1)

CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX

CUDA enabled devices: 1

Java:

		// load our YOLO object detector trained on COCO dataset
		Net dnnNet = readNetFromDarknet(
			modelFile.getPath(),
			weightsFile.getPath()
		);

		// enable cuda backend if available
	        if (getCudaEnabledDeviceCount() > 0) {
	            Log.d("CUDA available!");
	            dnnNet.setPreferableBackend(opencv_dnn.DNN_BACKEND_CUDA);
	            dnnNet.setPreferableTarget(opencv_dnn.DNN_TARGET_CUDA);
	        } else {
	        	Log.d("CUDA NOT available");
	        }

		Log.d("Loaded Darknet!");

		// setup output layers
		StringVector outputLayers = dnnNet.getUnconnectedOutLayersNames();

		// create an input blob for the dnn from the mat
		Mat inputBlob = opencv_dnn.blobFromImage(
		  img,
		  1 / 255.0,
		  new Size(width_section, height_section),
		  new Scalar(0.0),
		  true,
		  false,
		  opencv_core.CV_32F
		);

		// give the blob to the net
		dnnNet.setInput(inputBlob);

		// make some new outs
		MatVector outs = new MatVector(outputLayers.size());

		// get the results from Yolo!
		dnnNet.forward(outs, outputLayers);

**Comment by saudet** [comment]
Please try again with the snapshots: http://bytedeco.org/builds/

**Comment by gareth-edwards** [comment]
Brilliant! Many thanks for the super-quick response. It's working :)

About 7x faster - I'll try better hardware!

pom.xml : 

	<repositories>
		<repository>
			<id>sonatype-nexus-snapshots</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>sonatype-nexus-snapshots</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</pluginRepository>
	</pluginRepositories>

	<dependencies>

		
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.10</version>
		</dependency>


		

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg-platform</artifactId>
			<version>6.1-1.5.10-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.5.10-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>opencv-platform-gpu</artifactId>
			<version>4.8.1-1.5.10-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>cuda-platform</artifactId>
			<version>12.3-8.9-1.5.10-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>cuda-platform-redist</artifactId>
			<version>12.3-8.9-1.5.10-SNAPSHOT</version>
		</dependency>

	</dependencies>


opencv_core.getBuildInformation().getString() :

General configuration for OpenCV 4.8.1 =====================================
  Version control:               cfcc2d5

  Extra modules:
    Location (extra):            /home/runner/work/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv_contrib-4.8.1/modules
    Version control (extra):     cfcc2d5

  Platform:
    Timestamp:                   2023-11-14T10:30:40Z
    Host:                        Linux 5.15.0-1050-azure x86_64
    CMake:                       3.27.7
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (14 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (7 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (33 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (5 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                11
    C++ Compiler:                /usr/bin/g++  -std=c++11 -m64 (ver 9.4.0)
    C++ flags (Release):         -w   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -w   -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/gcc  -m64
    C flags (Release):           -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    Linker flags (Debug):        -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    ccache:                      YES
    Precompiled headers:         NO
    Extra dependencies:          m pthread cudart_static dl rt nppc nppial nppicc nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev dnn dnn_superres face features2d flann highgui img_hash imgcodecs imgproc intensity_transform java mcc ml objdetect optflow phase_unwrapping photo plot python3 quality rapid saliency shape stitching structured_light superres text tracking video videoio videostab wechat_qrcode xfeatures2d ximgproc xphoto
    Disabled:                    ccalib datasets dnn_objdetect dpm freetype fuzzy gapi hfs line_descriptor reg rgbd stereo surface_matching world xobjdetect
    Disabled by dependency:      -
    Unavailable:                 alphamat cvv hdf julia matlab ovis python2 sfm ts viz
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         YES

  GUI:                           GTK2
    GTK+:                        YES (ver 2.24.32)
      GThread :                  YES (ver 2.64.6)
      GtkGlExt:                  NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.13)
    JPEG:                        build-libjpeg-turbo (ver 2.1.3-62)
      SIMD Support Request:      NO
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build Jasper (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Lapack:                      YES (/home/runner/.javacpp/cache/openblas-0.3.24-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/openblas/linux-x86_64/libopenblas.so)
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)
    Flatbuffers:                 builtin/3rdparty (23.5.9)

  NVIDIA CUDA:                   YES (ver 12.3, CUFFT CUBLAS)
    NVIDIA GPU arch:             50 60 70 80 90
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 8.9.5)

  OpenCL:                        YES (no extra features)
    Include path:                /home/runner/work/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/opencv-4.8.1/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 /home/runner/.javacpp/cache/cpython-3.12.0-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/bin/python3.12 (ver 3.12)
    Libraries:                   /home/runner/.javacpp/cache/cpython-3.12.0-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/cpython/linux-x86_64/lib/python3.12/ (ver 3.12.0)
    numpy:                       /home/runner/.javacpp/cache/numpy-1.26.1-1.5.10-SNAPSHOT-linux-x86_64.jar/org/bytedeco/numpy/linux-x86_64/python/numpy/core/include (ver )
    install path:                /home/runner/work/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu/lib/python3.12/site-packages

  Python (for build):            /usr/bin/python2

  Java:                          
    ant:                         /bin/ant (ver 1.10.7)
    Java:                        NO
    JNI:                         /usr/lib/jvm/java-8-openjdk-amd64/include /usr/lib/jvm/java-8-openjdk-amd64/include/linux /usr/lib/jvm/java-8-openjdk-amd64/include
    Java wrappers:               YES (ANT)
    Java tests:                  NO

  Install to:                    /home/runner/work/javacpp-presets/javacpp-presets/opencv/cppbuild/linux-x86_64-gpu
-----------------------------------------------------------------

�
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX
CUDA enabled devices: 1

**Comment by saudet** [comment]
Please let me know if you're still having any problems with version 1.5.10. Thanks!
