### ISSUE TITLE
this is invalid issue

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2137]
when I use FFmpegFrameFilter process multiple input images， and use FFmpegRecord.record(frame)，how to achieve the same loop input effect in the ffmpeg command line, as like: ffmpeg -loop 1 -t 4 -i a.jpg -loop 1 -t 4 -i b.jpg -r 25 -filter_complex  "[0:v][1:v]xfade=transition=rectcrop:duration=1:offset=4,format=yuv420p" output.mp4 ???
`FFmpegFrameFilter filter = new FFmpegFrameFilter("[0:v][1:v]xfade=transition=rectcrop:duration=1:offset=4,format=yuv420p[v]" , imgWidth, imgHeight);
Frame frame = grabber.grabImage();
filter.push(?, ?);`
above this, how to input filter with the multiple same images as Frame?

**Comment by saudet** [comment]
We can easily use the ffmpeg program from Java like this:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html
