### ISSUE TITLE
AndroidFrameConverter performance

### ISSUE THREAD

**Issue by phajduk** [bytedeco/javacv#214]
Hello.Firstly, javacv is awesome and I hope community will make it even better!

As documentation states `AndroidFrameConverter` is not designed for performance. From docs:
`This class is not optimized for speed. For best performance, convert first your data to and from RGBA with optimized functions from FFmpeg or OpenCV.`

I need to render live stream (I use `FFmpegFrameGrabber`) on Android device. I have low FPS and I believe it's due to AndroidFrameConverter performence as conversion takes >100ms. I would like to implement and contribute faster converter but I need some advice on the very beginning. 

@saudet  could you give me some tips about conversion to and from RGBA using optimized functions from FFmpeg and OpenCV? It's mentioned in documentation but I'm not familiar with whole API and I don't know where to start.

**Comment by saudet** [comment]
`FFmpegFrameGrabber` should already be able to get you data in RGBA. Try to call `setPixelFormat(AV_PIX_FMT_RGBA)` before start.

**Comment by phajduk** [comment]
Thank you. It helped! 

I could prepare pull request with some additional Android example. What do you think?

**Comment by saudet** [comment]
Sure, please do! And if you would also like to contribute examples that include project files for Android Studio, for example, please send your pull request here: https://github.com/bytedeco/sample-projects Thanks!

**Comment by phajduk** [comment]
OK. I will prepare separated pull request. Thanks again for help.
