### ISSUE TITLE
FFmpegFrameRecorder bug with android 5.0.

### ISSUE THREAD

**Issue by DTHeaven** [bytedeco/javacv#215]
When I run the RecordActivity demo(JavaCpp/javacv/samples/RecordActivity.java), the output video seems strange. It seems like crop some pixels from right side and added them to left side.
This bug only happens on android 5.0 and above, it works well on android 4.x.
And I'm sure the raw data is correct either on android 4.x and 5.0.
How to solve this problem? 
Thanks.

**Comment by saudet** [comment]
There's some discussion about that here: https://github.com/bytedeco/javacv/issues/190
If you find how to fix this issue, please let us know! Thank you

My gut feeling is that the old Camera interface is deprecated and you would need to switch to the new API to get a bug free experience. If you come up with this code, please consider making a contribution: https://github.com/bytedeco/javacv/issues/163  Thank you!
