### ISSUE TITLE
A fatal error has been jvm gc.

### ISSUE THREAD

**Issue by hbcolorful** [bytedeco/javacv#2154]
Exception occurs in `videoFrameImage` method:
```java``` 

    public static BufferedImage videoFrameImage(byte[] bytes) throws IOException {
        log.info("[VideoFileUtil#videoFrameImage][开始抽帧]");

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(new ByteArrayInputStream(bytes));
        //设置超时时间为40秒
        grabber.setTimeout(40000000);
        grabber.start();

        int frameCount  = grabber.getLengthInFrames();
        log.info("[VideoFileUtil#videoFrameImage][帧总数:{}}", frameCount);
        // 生成随机帧索引
        int randomFrameIndex = frameCount / 2;
        grabber.setFrameNumber(randomWFrameIndex);
        Java2DFrameConverter converter = new Java2DFrameConverter();
        BufferedImage image = converter.convert(grabber.grabImage());
        grabber.stop();
        return image;
    }
```

```
**when executing `grabber.start()` has been:**
JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
Derivative: IcedTea 3.12.0
Distribution: Custom build (Sat May  4 17:33:35 UTC 2019)
Problematic frame:
C  0x000000000000d1f6
Core dump written. Default location: /opt/core or core.6
An error report file with more information is saved as:
/opt/hs_err_pid6.log
If you would like to submit a bug report, please include
instructions on how to reproduce the bug and visit:
https://icedtea.classpath.org/bugzilla
```

**Comment by hbcolorful** [comment]
**Spring-boot-starter:2.3.7.RELEASE
 OpenJDK1.8**
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg-platform</artifactId>
           <version>1.4.1</version>
        </dependency>
 ```

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.9.

**Comment by hbcolorful** [comment]
> Please try again with JavaCV 1.5.9.

This is my latest dependency.
```
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacpp</artifactId>
    <version>1.5.9</version>
</dependency>
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv</artifactId>
</dependency>
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>ffmpeg-platform</artifactId>
    <version>4.1-1.4.4</version>
</dependency>
```
**An error occurred: java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil**

**Comment by saudet** [comment]
Please try again with JavaCV 1.5.9.

**Comment by hbcolorful** [comment]
> Please try again with JavaCV 1.5.9.
The problem still exists that Could not initialize class org.bytedeco.ffmpeg.global.avutil.
Now in mavem pom:
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.5.9</version>
</dependency>

**Comment by saudet** [comment]
Please install the missing dependencies

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by hbcolorful** [comment]
> Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

Hello! I'm trying to open the debugger and generate some new logs whit `linux_arm64`.
**First**, If i user this `pom.xml`， and will encounter the `memoey leak`.
```
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacpp</artifactId>
    <version>1.5.9</version>
</dependency>
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>ffmpeg</artifactId>
    <version>6.0-1.5.9</version>
    <classifier>linux-arm64</classifier>
</dependency>
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>ffmpeg</artifactId>
    <version>6.0-1.5.9</version>
    <classifier>linux-x86_64</classifier>
</dependency>
```
Memoey leak  debugger record [bytedeco_linux_arm64_ffmpeg_debug.log](https://github.com/bytedeco/javacv/files/13783962/bytedeco_linux_arm64_ffmpeg_debug.log)

**Second**, If i user this `pom.xml`， and will encounter the '`java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.ffmpeg.global.avutil`'.
```
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacpp</artifactId>
    <version>1.5.9</version>
</dependency>
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>ffmpeg</artifactId>
    <version>6.0-1.5.9</version>
    <classifier>linux-arm64</classifier>
</dependency>
```
I'm a little curious which dependency is relatively correct.

**Comment by saudet** [comment]
Please use javacv-platform as dependency

**Comment by hbcolorful** [comment]
> Please use javacv-platform as dependency

I have tried this, but there is also a memory overflow problem.

**Comment by saudet** [comment]
If you don't want memory leaks, you'll need to call close() on both FFmpegFrameGrabber and Java2DFrameConverter
