### ISSUE TITLE
Which jar package needs to be introduced to use the OpenGLFrameConverter and GLFWFrameRenderer class?

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2155]
If I want to use OpenGLFrameConverter and GLFWFrameRenderer class, which jar package needs to be introduced ?

**Comment by saudet** [comment]
The optional ones for JogAmp here: https://github.com/bytedeco/javacv/blob/1.5.9/pom.xml#L154-L165

**Comment by DearTan** [comment]
> The optional ones for JogAmp here: https://github.com/bytedeco/javacv/blob/1.5.9/pom.xml#L154-L165

But  OpenGLFrameConverter and GLFWFrameRenderer class still cannot be found after introducing org.jogamp.gluegen.gluegen-rt-main and org.jogamp.jogl.jogl-all-main ???

**Comment by saudet** [comment]
What is the error message you are getting?

**Comment by DearTan** [comment]
> What is the error message you are getting?

IDEA development tool prompts： Cannot resolve symbol 'OpenGLFrameConverter'
![Uploading error.png…]()

**Comment by saudet** [comment]
That's problem with your IDE, not with JavaCV. Please report upstream

**Comment by saudet** [comment]
Actually, OpenGLFrameConverter doesn't exist. You probably want either OpenCVFrameConverter or GLCanvasFrame
