### ISSUE TITLE
 OpenGLFrameConverter and GLFWFrameRenderer class still cannot be found after introducing org.jogamp.gluegen.gluegen-rt-main and org.jogamp.jogl.jogl-all-main ???

### ISSUE THREAD

**Issue by DearTan** [bytedeco/javacv#2160]
Sorry, I tried. but OpenGLFrameConverter and GLFWFrameRenderer class still cannot be found after introducing org.jogamp.gluegen.gluegen-rt-main and org.jogamp.jogl.jogl-all-main ??? #2155

**Comment by saudet** [comment]
Duplicate of #2155
