### ISSUE TITLE
How should I set up FFmpegFrameRecorder for hardware acceleration？

### ISSUE THREAD

**Issue by sunplusApp** [bytedeco/javacv#2161]
I am using FFmpegFrameRecorder on Android to encode yuv into mp4. The CPU usage is very high, and I want to use hardware acceleration. How should I set up FFmpegFrameRecorder?

**Comment by sunplusApp** [comment]
Use mediacodec or vulkan？

**Comment by saudet** [comment]
You'll need to call something like setVideoCodecName("h264_mediacodec") before start().

**Comment by saudet** [comment]
Duplicate of #2046
