### ISSUE TITLE
Java CV is still adding other plateform jar even classifier  is added.

### ISSUE THREAD

**Issue by AKMANSoft** [bytedeco/javacv#2174]
Im adding the below dependencies of javaCV to my project but add classifier to add only window jar, but still a lot of linux and other plateform jar are adding. 

![image](https://github.com/bytedeco/javacv/assets/21236130/18d2701d-792d-41a2-8dfe-1019f6c54f30)

`		<properties>
			<javacpp.version>1.5.9</javacpp.version>
		</properties>
		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			${javacpp.version}
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>6.0-${javacpp.version}</version>
			<classifier>windows-x86_64</classifier>
		</dependency>

		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp</artifactId>
			<version>${javacpp.version}</version>
			<classifier>windows-x86_64</classifier>
		</dependency>
		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp-platform</artifactId>
			<version>${javacpp.version}</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>flandmark</artifactId>
			<version>1.07-1.5.8</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>opencv</artifactId>
			<classifier>windows-x86_64</classifier>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>opencv-platform-gpu</artifactId>
			<version>4.7.0-1.5.9</version>
		</dependency>

		
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>openblas</artifactId>
			<classifier>windows-x86_64</classifier>
		</dependency>`

**Comment by saudet** [comment]
Please follow the instructions at https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies
