### ISSUE TITLE
How to grab audio frames from a selected audio stream when the video file has multiple audio tracks?

### ISSUE THREAD

**Issue by besidev** [bytedeco/javacv#2185]
The `FFmpegFrameGrabber` doesn't provide a way to grab audio frames from the selected audio stream. We usually have video files with multiple audio tracks in different languages and we want to extract via the JavaCV API only the preferred track.

**Comment by saudet** [comment]
We can call setAudioStream() before start() for that purpose.

**Comment by besidev** [comment]
Thank you the quick reply. Using the `setAudioStream()` function proved successful. However, we encountered an inconsistency: for video files containing several audio tracks, the initial audio stream index was set to `1`. Contrastingly, in all other scenarios, the indexing commenced from `0`. Is it expected behaviour for the API to always start the index of the first audio stream at `0`?

**Comment by saudet** [comment]
If we don't set anything, it uses the default stream, which might not be 0

**Comment by besidev** [comment]
Thanks, we are satisfied with the results. I'm closing this issue.
