### ISSUE TITLE
M3U8 Index File Have No #EXT-X-ENDLIST

### ISSUE THREAD

**Issue by Yeung-Ming** [bytedeco/javacv#2201]
![image](https://github.com/bytedeco/javacv/assets/74055211/a86e38ed-7b4c-4f1b-81ef-1235f494b9d4)

This is JavaCV write ffmpeg command.
I have no set `omit_endlist` but The Index File have no `#EXT-X-ENDLIST` .
JavaCV version: 1.5.10

**Comment by Yeung-Ming** [comment]
JavaCV version: 1.5.10

**Comment by saudet** [comment]
Are you sure we can't set that with `setOption()`?

**Comment by Yeung-Ming** [comment]
I found the problem. I have not stop the recorder
