### ISSUE TITLE
New Errors from compile javacpp-present

### ISSUE THREAD

**Issue by max90727** [bytedeco/javacv#222]
Hi:
I got error from building the javacpp-present. I think it is related to my GCC and arm version. 
Please take a look:
```
In file included from /usr/include/stdio.h:934:0,
                 from /usr/lib/jvm/java-7-openjdk-armhf/include/jni.h:39,
                 from /home/ubuntu/javacpp-presets/opencv/target/classes/org/bytedeco/javacpp/jniopencv_calib3d.cpp:26:
/usr/include/arm-linux-gnueabihf/bits/stdio.h: In function ‘int getchar()’:
/usr/include/arm-linux-gnueabihf/bits/stdio.h:44:14: sorry, unimplemented: Thumb -1 hard-float VFP ABI getchar (void)
```

**Comment by saudet** [comment]
Find what kind of options your compiler needs, and add those to the [`compilerOptions`](http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/BuildMojo.html#compilerOptions) property of the plugin's configuration in the `pom.xml` file!

**Comment by max90727** [comment]
Hello again.
The error still there, and here is the compile command and error from maven:
[INFO] Compiling /media/card/javacpp-presets/opencv/target/classes/org/bytedeco/javacpp/linux-arm/libjniopencv_calib3d.so
[INFO] /usr/bin/arm-linux-gnueabihf-g++-4.8 -I/media/card/javacpp-presets/opencv/cppbuild/linux-arm/include/ -I/usr/lib/jvm/java-7-openjdk-armhf/include 
-I/usr/lib/jvm/java-7-openjdk-armhf/include/linux /media/card/javacpp-presets/opencv/target/classes/org/bytedeco/javacpp/jniopencv_calib3d.cpp -march=armv5te 
-Wl,-rpath,$ORIGIN/ -Wall -O3 -fPIC -shared -s -o /media/card/javacpp-presets/opencv/target/classes/org/bytedeco/javacpp/linux-arm/libjniopencv_calib3d.so 
-L/media/card/javacpp-presets/opencv/cppbuild/linux-arm/lib/ -Wl,-rpath,/media/card/javacpp-presets/opencv/cppbuild/linux-arm/lib/ -lopencv_calib3d 
-lopencv_features2d -lopencv_ml -lopencv_flann -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_imgproc -lopencv_core
In file included from /usr/include/stdio.h:934:0,
                 from /usr/lib/jvm/java-7-openjdk-armhf/include/jni.h:39,
                 from /media/card/javacpp-presets/opencv/target/classes/org/bytedeco/javacpp/jniopencv_calib3d.cpp:26:
/usr/include/arm-linux-gnueabihf/bits/stdio.h: In function ‘int getchar()’:
/usr/include/arm-linux-gnueabihf/bits/stdio.h:44:14: sorry, unimplemented: Thumb-1 hard-float VFP ABI
 getchar (void)

The command is correct, but I still don't understand why the error occurs.

**Comment by saudet** [comment]
I see. Maybe we should be removing the "-march=armv5te" option? Could you try to remove it from the `linux-arm.properties` file and let me know if it works better? Thanks!

**Comment by max90727** [comment]
Thanks for your reply. I found the linux-arm.properties in the javacpp but not in the javacpp-present.

**Comment by max90727** [comment]
I may no need to run the 
mvn install in the javacpp-present
I have changed that file and install the javacpp in the mean time. Will come back to you.

**Comment by max90727** [comment]
Hello Again:
Here is the code I add into the cppbuild.sh in javacpp-present/ffmpeg. I am not sure it can work please check it, I am still waiting for the results form BeagleBone Black.
linux-arm)
		cd $LAME
		echo "-------configure: \"$LAME\"-------"
        ./configure --prefix=$INSTALL_PATH --disable-shared --with-pic --host=arm-linux CFLAGS="-marm"
        make -j4
        make install
        cd ../$SPEEX
		echo "-------configure: \"$SPEEX\"-------"
        ./configure --prefix=$INSTALL_PATH --disable-shared --with-pic --host=arm-linux CFLAGS="-marm"
        make -j4
        make install
        cd ../$OPENCORE_AMR
		echo "-------configure: \"$OPENCORE_AMR\"-------"
        ./configure --prefix=$INSTALL_PATH --disable-shared --with-pic --host=arm-linux CFLAGS="-marm" CXXFLAGS="-marm"
        make -j4
        make install
        cd ../$OPENSSL
        ./Configure linux-armv4 -fPIC --prefix=$INSTALL_PATH
        make
        make install
        cd ../$X264
		echo "-------configure: \"$X264\"-------"
        ./configure --prefix=$INSTALL_PATH --enable-static --enable-pic --disable-opencl --host=arm-linux
        make -j4
        make install
        cd ../$X265
		echo "-------configure: \"$X265\"-------"
        $CMAKE -DENABLE_SHARED=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=.. source
        make -j4
        make install
        cd ../libvpx-$VPX_VERSION
		echo "-------configure: libvpx-\"$VPX_VERSION\"-------"
        ./configure --prefix=$INSTALL_PATH --enable-shared --enable-static --enable-pic --disable-examples --target=armv7-linux-gcc
        make -j4
        make install
        cd ../ffmpeg-$FFMPEG_VERSION
		echo "-------configure: ffmpeg-\"$FFMPEG_VERSION\"-------"
        PKG_CONFIG_PATH=../lib/pkgconfig/ ./configure --prefix=.. --enable-shared --enable-gpl --enable-version3 --enable-nonfree --enable-runtime-cpudetect --disable-iconv --disable-libxcb --disable-opencl --disable-outdev=sdl --enable-x11grab --enable-libmp3lame --enable-libspeex --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-openssl --enable-libx264 --enable-libx265 --enable-libvpx --cc="gcc -marm" --extra-cflags="-I../include/" --extra-ldflags="-L../lib" --extra-libs="-lstdc++ -ldl"
        make -j4
        make install
        ;;

**Comment by saudet** [comment]
I don't have a `linux-arm` platform to test this on unfortunately. If you cannot take the time to make a build though, we can usually use the ones that come with Linux distributions. Here's some instructions for that:
http://alltechanalysis.blogspot.jp/2015/09/installing-opencv-30-and-javacv-on.html

**Comment by max90727** [comment]
Hi:
I tested the cppbuild.sh and I met a problem which I do not have a clue how to fix that.

/usr/bin/ld: ../lib/libx265.a(api.cpp.o): relocation R_ARM_THM_MOVW_ABS_NC against `__stack_chk_guard' can not be used when making a shared object; recompile with -fPIC
../lib/libx265.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Any suggestions?

**Comment by saudet** [comment]
It says to recompile with `-fPIC` so do that, or remove x265 if you're not interested by that codec.

**Comment by saudet** [comment]
Version 1.2 now contains binaries of OpenCV and FFmpeg compiled for `linux-armhf`, thanks to @vb216, so just use those and enjoy!
http://search.maven.org/remotecontent?filepath=org/bytedeco/javacpp-presets/opencv/3.1.0-1.2/opencv-3.1.0-1.2-linux-armhf.jar
http://search.maven.org/remotecontent?filepath=org/bytedeco/javacpp-presets/ffmpeg/3.0.2-1.2/ffmpeg-3.0.2-1.2-linux-armhf.jar
