### ISSUE TITLE
how can i use JavaCV 1.5.9 and ffmpeg 6.1.1?  

### ISSUE THREAD

**Issue by nocarethancare** [bytedeco/javacv#2227]
i wanna use 1.59 and ffmpeg 6.1.1. because our system is Euler and i need codec H265 flv   （ffmpeg6.1.1 can do it）

**Comment by nocarethancare** [comment]
1.5.10 can't be used in Euler and Centos  ；
if i must use centos. how can i do?

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379
