### ISSUE TITLE
FFmpegFrameGrabber不能在docker中初始化,在windows linux下可以

### ISSUE THREAD

**Issue by 354613111** [bytedeco/javacv#2244]
![image](https://github.com/bytedeco/javacv/assets/47909289/03559b0d-b02e-487d-920f-c6cdfaecb61e)

**Comment by saudet** [comment]
Please follow the instructions at https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by saudet** [comment]
I see, this is for Linux in Docker. Please refer to issue https://github.com/bytedeco/javacpp-presets/issues/1379

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacpp-presets/issues/1379
