### ISSUE TITLE
Calculating Magnitude from DFT

### ISSUE THREAD

**Issue by tony-stark1** [bytedeco/javacv#225]
Hi,

I'm having issues with calculating the magnitude from a dft transform of an image. 
I originally asked this question on stackoverflow but was told that I should ask it here instead.

When I call the magnitude function a problem occurs in native code.

The problem frames is listed as:
```
Problematic frame: C [libjniopencv_core.so+0xba953] Java_org_bytedeco_javacpp_opencv_1core_00024Mat_size__+0x63
```
I've made sure that the input mats are of the same size and checked that the input mats are of the correct type.

Heres the code:
```java
public static void main(String[] args) {
    //Read in image
    Mat m = imread("lena.jpeg");

    MatVector v = new MatVector();
    Mat v1, v2;
    Mat dst = new Mat();

    // Convert to grayscale
    cvtColor(m, m, COLOR_BGR2GRAY);

    // Convert to type required for dft
    m.convertTo(m, CV_64FC1);

    //Perform transform
    dft(m, dst);

    // split
    split(dst, v);
    v1 = v.get(0);
    v2 = v.get(1);

    //Both mats must be same size for magnitude
    if (v1.size() == v2.size()) {
        // Mat to store result
        Mat mag = new Mat(v1.size(), v1.type());

        magnitude(v1, v2, mag);

       //Linear to log
         log(mag, mag);
        
       // Display result
        imshow("Magnitude", mag);
        waitKey();
    } else {
        System.out.println("v1 size != v2 size");
    }
}
```

**Comment by saudet** [comment]
Are you trying to port some sample code from C++? Could you provide this code as well? Thanks

**Comment by tony-stark1** [comment]
Yes, I couldn't find any examples of how do use the dft function in javacv so I started with the c++ code from this website: 
http://www.juergenwiki.de/work/wiki/doku.php?id=public:dft_dct_dst

The C++ code is :
: cv::VideoCapture videoCapture; // in case a video media is used, its manager is declared here
videoCapture.open(1);
 
int counter = 0;
while (true)
{
    // Get image from camera
    Mat camimg;
    videoCapture >> camimg;
 
    // Convert that image to grayscale
    Mat img;
    cvtColor(camimg,img,CV_RGB2GRAY);
 
    // Prepare grayscal image <img> for DFT
    int M = getOptimalDFTSize( img.rows );
    int N = getOptimalDFTSize( img.cols );
    Mat padded;    
    copyMakeBorder(img, padded, 0, M - img.rows, 0, N - img.cols, BORDER_REPLICATE, Scalar::all(0));
 
    // Prepare matrix for DFT result: <complexImg>
    Mat planes[] = {Mat_<float>(padded), Mat::zeros(padded.size(), CV_32F)};
    Mat complexImg;
    merge(planes, 2, complexImg);
 
    // DFT
    dft(complexImg, complexImg);
 
    // Get magnitude spectrum from complex result matrix
    // Compute log(1 + sqrt(Re(DFT(img))**2 + Im(DFT(img))**2))
    split(complexImg, planes);
    magnitude(planes[0], planes[1], planes[0]);    
    Mat mag = planes[0];
    mag += Scalar::all(1);
    log(mag, mag);
 
    // Crop the spectrum, if it has an odd number of rows or columns
    mag = mag(Rect(0, 0, mag.cols & -2, mag.rows & -2));
 
    // Rearrange the quadrants of Fourier image
    // so that the origin is at the image center
    int cx = mag.cols/2;
    int cy = mag.rows/2;
    Mat tmp;
    Mat q0(mag, Rect(0, 0, cx, cy));
    Mat q1(mag, Rect(cx, 0, cx, cy));
    Mat q2(mag, Rect(0, cy, cx, cy));
    Mat q3(mag, Rect(cx, cy, cx, cy));    
 
    q0.copyTo(tmp);
    q3.copyTo(q0);
    tmp.copyTo(q3);
 
    q1.copyTo(tmp);
    q2.copyTo(q1);
    tmp.copyTo(q2);
 
    // Get some region about the center of the magnitude spectrum
    int r = 10;
    Mat roi(mag, Rect(mag.cols/2-r, mag.rows/2-r, 2*r,2*r));
    Mat MagPartly;
    roi.copyTo(MagPartly);
 
    // padded is an 8UC1 image with values in the range 0-255
    // Make mag a 8UC1 image with values in that range as well
    // so that we can copy both images to a bigger one
    normalize(mag, mag, 0, 255, CV_MINMAX);
    mag.convertTo(mag, CV_8UC1);
 
    // Separately normalize mag and MagPartly
    normalize(MagPartly, MagPartly, 0, 255, CV_MINMAX);
    MagPartly.convertTo(MagPartly, CV_8UC1);
 
    // Zoom MagPartly
    Mat MagZoomed;
    resize(MagPartly, MagZoomed, Size(padded.cols,padded.rows));
 
    // Prepare one big output image with:
    // | grayscale image |        magnitude spectrum image |
    // |    empty        | zoomed magnitude spectrum image |
    int w = padded.cols * 2;
    int h = padded.rows * 2;
    Mat bigimg(h,w, CV_8UC1);
    Mat roi1(bigimg, Rect(0,0, padded.cols, padded.rows));
    padded.copyTo(roi1);
    Mat roi2(bigimg, Rect(padded.cols,0, padded.cols, padded.rows));
    mag.copyTo(roi2);
    Mat roi3(bigimg, Rect(padded.cols,padded.rows, padded.cols, padded.rows));
    MagZoomed.copyTo(roi3);
 
    // Show images    
    imshow("big img", bigimg);
 
    // Save images
    char fname[500];
    sprintf_s(fname, "W:\\tmp\\dft%05d.png", counter);
    imwrite(fname, bigimg);
    counter++;
 
    waitKey(1);
}

**Comment by saudet** [comment]
Great, thanks! Where is the bit that corresponds to
```java
    //Both mats must be same size for magnitude
    if (v1.size() == v2.size()) {
```
?

**Comment by philipmcshane** [comment]
ITs based on this part:
    magnitude(planes[0], planes[1], planes[0]);    
    Mat mag = planes[0];

It hadn't work when I used v1 as the first and third arguments to magnitude so I had tried creating a larger mat to hold the result to try and solve the issue.  I also looked at the javadoc for the magnitude method which says:

magnitude

public static void magnitude(Mat x,
             Mat y,
             Mat magnitude)

Calculates the magnitude of 2D vectors.

The function magnitude calculates the magnitude of 2D vectors formed from the corresponding elements of x and y arrays:

dst(I) = sqrt(x(I)^2 + y(I)^2)

Parameters:
    x - floating-point array of x-coordinates of the vectors.
    y - floating-point array of y-coordinates of the vectors; it must have the same size as x.
    magnitude - output array of the same size and type as x.

So I then changed it to match the size and type requirements listed in the javadoc. However this did not resolve the issue.

**Comment by tony-stark1** [comment]
It corresponds to this bit 
   magnitude(planes[0], planes[1], planes[0]);    
    Mat mag = planes[0];

Since using the same mat for args 0 and 2 hadn't worked I tried creating a larger mat to see if that would solve the problem. It hadn't and when I looked at the javadoc it give me these requirements for the mats I pass to the function so I changed the code to ensure that it meet the requirements listed in the javadoc. Unfortunately this did not resolve my problem.

Here's the javadoc I'm reffering to

public static void magnitude(Mat x,
             Mat y,
             Mat magnitude)
Calculates the magnitude of 2D vectors.

The function magnitude calculates the magnitude of 2D vectors formed from the corresponding elements of x and y arrays:

dst(I) = sqrt(x(I)^2 + y(I)^2)

Parameters:
x - floating-point array of x-coordinates of the vectors.
y - floating-point array of y-coordinates of the vectors; it must have the same size as x.
magnitude - output array of the same size and type as x.

**Comment by saudet** [comment]
Why does using the same Mat as the first and third argument doesn't work?

**Comment by tony-stark1** [comment]
Doing that results in this error
Problematic frame:
C  [libopencv_core.so.3.0+0x54939]  cv::_InputArray::size(int) const+0x179

**Comment by saudet** [comment]
Ok, could you provide a few lines of code to reproduce that error? Thanks!

**Comment by tony-stark1** [comment]
Heres the code to reproduce the error

public static void main(String[] args) {
		// Read in image
		Mat m = imread("lena.jpeg",0);

		MatVector v = new MatVector();
		Mat v1, v2;
		Mat dst = new Mat();


		// Convert to type required for dft
		m.convertTo(m, CV_64FC1);

		// Perform transform
		dft(m, dst);

		// split
		split(dst, v);

		magnitude(v.get(0), v.get(1), v.get(0));
		Mat mag = v.get(0);

		log(mag, mag);

		// Display result
		imshow("Magnitude", mag);
		waitKey();
	}

**Comment by saudet** [comment]
How is `m` initialized? I've initialized it this way:
```java
    Mat m = new Mat(512, 512, CV_8UC2);
```
And your code works fine. So I still don't understand what the issue is.
