### ISSUE TITLE
When encountering automatic garbage collection in Java, converting Mat from JavaCV to Mat from OpenCV can cause problems and result in process interruption.

### ISSUE THREAD

**Issue by zhang22113** [bytedeco/javacv#2253]
import org.bytedeco.javacv.CanvasFrame;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.Frame;

import org.bytedeco.javacv.OpenCVFrameConverter;
import org.opencv.core.*;
import javax.swing.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;

public class StartTest8 {
    static {
        System.load(System.getProperty("user.dir") + "/libs/opencv_java4100.dll");
    }
    private Mat currentFrame = new org.opencv.core.Mat();
    private OpenCVFrameConverter.ToMat converter = new OpenCVFrameConverter.ToMat();
    public static void main(String[] args) {
        // 增加JVM堆内存大小
        System.setProperty("java.opts", "-Xmx2g");
        new StartTest8().run();
    }

    public void run() {
        try {
            PrintStream err = new PrintStream(new FileOutputStream("error.log"));
            System.setErr(err);

            String rtspUrl = "rtsp://192.168.1.22:9554/live?channel=1&subtype=0";
            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(rtspUrl);
            grabber.setOption("rtsp_transport", "tcp");
            grabber.setOption("threads", "1");
            grabber.setOption("nobuffer", "1");
            grabber.setOption("fflags", "nobuffer");
            grabber.setOption("buffer_size", "204800");
            grabber.setOption("rw_timeout", "5000000");
            grabber.setOption("max_delay", "200");
            grabber.setOption("flags", "low_delay");
            grabber.setOption("max_analyze_duration", "500000");
            grabber.setOption("rw_timeout", "15000000");
            grabber.setOption("probesize", "300000");
            grabber.setOption("analyzeduration", "200000");
            try {
                grabber.start();
                System.out.println("开启拉流器拉流");
            } catch (Exception e) {
                System.out.println("无法打开视频流：" + rtspUrl);
                e.printStackTrace();
                return;
            }

            CanvasFrame canvas = new CanvasFrame("监测物体移动测试", CanvasFrame.getDefaultGamma() / grabber.getGamma());
            canvas.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            canvas.setAlwaysOnTop(true);

            Runtime runtime = Runtime.getRuntime();
            long startTime = System.currentTimeMillis();
            long maxMemory = runtime.maxMemory();
            System.out.println("最大堆内存: " + maxMemory / 1024 / 1024 + " MB");

            while (canvas.isVisible()) {
                try {
                    Frame frame = grabber.grabImage();
                    if (frame == null) {
                        System.out.println("缺帧");
                        break;
                    }
                    Frame result = OpenCV(frame);
                    canvas.showImage(result);
                    // 记录内存使用情况
                    long usedMemory = runtime.totalMemory() - runtime.freeMemory();
                    long elapsedTime = (System.currentTimeMillis() - startTime) / 1000;
                    System.out.println("已用内存: " + usedMemory / 1024 / 1024 + " MB, 运行时间: " + elapsedTime + "秒");
                    //----Used for simulation--------------
                    if (elapsedTime % 6 == 0) {
                        System.gc();
                    }
                } catch (Exception e) {
                    System.out.println("处理帧时发生异常：" + e.getMessage());
                    e.printStackTrace();
                }
            }

            try {
                grabber.stop();
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("停止拉流器时发生异常：" + e.getMessage());
            }
            canvas.dispose();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            System.out.println("日志文件未找到：" + e.getMessage());
        }
    }
    private Frame OpenCV(Frame frame){
        org.bytedeco.opencv.opencv_core.Mat mat = converter.convertToMat(frame);
        System.out.println(mat.address());
        System.out.println("Before operation:" + currentFrame);
        //------
        currentFrame = new org.opencv.core.Mat(mat.address());
        //-----
        System.out.println("After operation：" + currentFrame);
        return frame;
    }
}

When Java's garbage collection mechanism is triggered, JavaCV's Mat is converted to OpenCV's Mat, which leads to process interruption. I tried skipping this OpenCV and using Thread Sleep (1000) or clone storage are useless。

I am running a simulation here, and the waiting time is too long. In fact, the garbage collection mechanism is automatically triggered by Java, and I did not call it.

**Comment by zhang22113** [comment]
4842159376
运行前:Mat [ -1*-1*CV_8UC1, isCont=false, isSubmat=false, nativeObj=0x603d40, dataAddr=0x0 ]
org.bytedeco.opencv.opencv_core.Mat[width=1024,height=768,depth=8,channels=3]
运行后：Mat [ 768*1024*CV_8UC3, isCont=true, isSubmat=false, nativeObj=0x1209d7d10, dataAddr=0x1193fb080 ]
已用内存: 17 MB, 运行时间: 5秒
4842159376
运行前:Mat [ -1*-1*CV_8UC1, isCont=false, isSubmat=false, nativeObj=0x603d40, dataAddr=0x0 ]
org.bytedeco.opencv.opencv_core.Mat[width=1024,height=768,depth=8,channels=3]
运行后：Mat [ 768*1024*CV_8UC3, isCont=true, isSubmat=false, nativeObj=0x1209d7d10, dataAddr=0x1193fb080 ]
已用内存: 17 MB, 运行时间: 5秒
4842159376
运行前:Mat [ -1*-1*CV_8UC1, isCont=false, isSubmat=false, nativeObj=0x603d40, dataAddr=0x0 ]
org.bytedeco.opencv.opencv_core.Mat[width=1024,height=768,depth=8,channels=3]
运行后：Mat [ 768*1024*CV_8UC3, isCont=true, isSubmat=false, nativeObj=0x1209d7d10, dataAddr=0x1193fb080 ]
已用内存: 17 MB, 运行时间: 6秒
4841988832
运行前:Mat [ -1*-1*CV_8UC1, isCont=false, isSubmat=false, nativeObj=0x603d40, dataAddr=0x0 ]
已用内存: 10 MB, 运行时间: 12秒

进程已结束,退出代码-1073740940 (0xC0000374)


It seems that mat.address() has changed, causing currentFrame=new Mat (mat.address()); There's a problem.

**Comment by zhang22113** [comment]
您好，可能是我才疏学浅，我使用PointScope无法解决该问题

**Comment by saudet** [comment]
Please call clone() on the new Mat that you get

**Comment by zhang22113** [comment]
> 请对您获得的新 Mat 调用 clone()
Directly converting the Mat of JavaCV to the Mat of OpenCV, when triggering Java's automatic garbage collection mechanism, will result in the loss of the address of JavaCV's Mat. I tried to directly convert the Frame to OpenCV Mat, so the problem wouldn't occur.
Because my native language is not English, the above was converted using a translator. I don't know if it was expressed clearly.

**Comment by zhang22113** [comment]
Anyway, the problem has been solved
