### ISSUE TITLE
FFmpegFrameGrabber start() failing

### ISSUE THREAD

**Issue by collinpreston** [bytedeco/javacv#226]
I am using Android studio and am having my program fail when it is executing the start() method.  The actual error that I am receiving is: java.lang.RuntimeException: An error occured while executing doInBackground() Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil.  I am using OpenCVLibrary2482 though I have had this error with all other versions.

**Comment by saudet** [comment]
How did you add the librairies to your project?

**Comment by collinpreston** [comment]
The project was incorrectly configured in my workspace.  Approving to close.

**Comment by saudet** [comment]
Ok, good! But please provide details if possible so it may help someone else in the same situation! Thanks

**Comment by dan-damian** [comment]
As I said in another post, I had the same problem, but it was due to the fact that I've been using a 'stock' javacpp.jar, from javacpp-bin.zip. I've solved the problem by building javacpp.jar from sources for the android-arm platform.
