### ISSUE TITLE
reduce size of librairie android

### ISSUE THREAD

**Issue by openmotion** [bytedeco/javacv#2264]
Hello
the android plugin is very big ( 509 mo ) 
is there a way to keep only arm64 version 
i would like to keep only for example ffmpeg and opencv
thanks for your response

**Comment by saudet** [comment]
Please follow the instructions at https://github.com/bytedeco/javacpp-presets/wiki/Reducing-the-Number-of-Dependencies

**Comment by openmotion** [comment]
ok thanks so i followed this link and i applied this gradle :  
implementation("org.bytedeco:javacv-platform:1.5.7")
implementation group: 'org.bytedeco', name: 'javacpp', version: '1.5.7'
implementation group: 'org.bytedeco', name: 'javacpp', version: '1.5.7', classifier: 'android-arm64'
implementation group: 'org.bytedeco', name: 'ffmpeg', version: '5.0-1.5.7'
implementation group: 'org.bytedeco', name: 'ffmpeg', version: '5.0-1.5.7', classifier: 'android-arm64'
