### ISSUE TITLE
libjniavutil.so  failed: dlopen failed: library "libavutil.so.xx" not found

### ISSUE THREAD

**Issue by dan-damian** [bytedeco/javacv#227]
Hello guys, 

Can someone point me in some research direction regarding the problem bellow:
On Android 5.1.1. I get this error:
09-21 08:17:13.600    8803-9758/xyz.mydognewvr E/art﹕ dlopen("/data/app/xyz.mydognewvr-1/lib/arm/libjniavutil.so", RTLD_LAZY) failed: dlopen failed: library "libavutil.so.54" not found
09-21 08:17:13.624    8803-9758/xyz.mydognewvr I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>

That's how my libs folder looks like.
![screenshot from 2015-09-21 08 18 24](https://cloud.githubusercontent.com/assets/3329915/9985687/5f7a3e76-6039-11e5-9a49-1c513425b87c.png)
Where: javacv.jar, javacpp.jar, opencv.jar and opencv-android-arm.jar are extracted directly from javacv-bin.zip (downloaded last version), and ffmpeg.jar and ffmpeg-android-arm.jar were built using javacpp-presets and following the instructions from <a href="https://github.com/bytedeco/javacpp-presets#build-instructions">here </a>. I've built ffmpeg from sources as I wanted to have libvpx support enabled. I'm working on a Ubuntu 14.04 LTS 64 bit versions.

Thanks,
Dan

**Comment by saudet** [comment]
Does the file "/data/app/xyz.mydognewvr-1/lib/arm/libjniavutil.so" exists
on your device?

**Comment by dan-damian** [comment]
We can close this issue. It was a problem aroused from other problems. 
After cloning last version of javacpp-presets (with the correct ffmpeg patches) this error disappeared. 
What happened actually was that in the ffmpeg-android-arm.jar/lib/armeabi/ directory no so file with version appear. Only simple .so.

**Comment by saudet** [comment]
Android doesn't support library versioning, so there shouldn't be any numbers after .so: That's normal. Anyway I guess it was only a sync problem between JavaCPP itself and the Presets.
