### ISSUE TITLE
 FFmpegFrameGrabber on java

### ISSUE THREAD

**Issue by leoq-oliveira** [bytedeco/javacv#2279]
"This isn’t exactly a problem per se, but rather that I couldn't find any external sources.

I'm using the frame grabber to capture a frame and use it as a thumbnail, running it in a thread. However, after its execution, it fills my log with the video information.

I tried adding the options, but I see that this might be impossible for the frame grabber. Is there any way to do this?

`FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(tempFile); `

`grabber.setOption('loglevel', 'quiet'); `

`grabber.start();"`

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacv/discussions/2204
