### ISSUE TITLE
Exception in cvHoughLines2

### ISSUE THREAD

**Issue by Haprst** [bytedeco/javacv#2282]
I've written a program that sends 10,000 test images to cvHoughLines2. Everything works well for 9,998 of these images. The remaining two give a fatal runtime error. Ultimately this program needs to run on millions of images, so I need some way either to avoid these errors or to catch them in a useful way, so that instead of dying my program can simply report that the image could not be processed.

Therefore, I nested the call in a try/catch, which necessitated moving the initialization of CvSeq lines outside the try/catch. But then I get an error message: Cannot invoke "org.bytedeco.opencv.opencv_core.CvSeq.total()" because "lines" is null. OK then, what is the right way to initialize CvSeq lines?

Separately I found an exchange on GitHub around Apr 20, 2013, 6:34:17 PM in which a possibly related problem was associated with memory allocation/deallocation. Other than the initialization problem, it seems likely to me that the actual error is that these images gereate too many CvSeq lines and HoughLines2 is running out of memory.

[BUG.txt](https://github.com/user-attachments/files/16925030/BUG.txt)

**Comment by saudet** [comment]
The C API of OpenCV is deprecated. I would recommend trying with the C++ API, that is cv::HoughLines():
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/global/opencv_imgproc.html#HoughLines-org.bytedeco.opencv.opencv_core.Mat-org.bytedeco.opencv.opencv_imgproc.Vec2fVector-double-double-int-double-double-double-double-

**Comment by Haprst** [comment]
Thank you. Looking at the sample code I realized that the initialization should be simply CvSeq lines = new CvSeq(); and that completely solved my problem. Regarding my use of deprecated code, that's ok since it's just to demo feasibility and will have to be converted to Android and Ios anyhow. In conclusion, I am closing this question.
