### ISSUE TITLE
How to successfully create a dependency for arm-gpu  Java CV? 

### ISSUE THREAD

**Issue by yibinzhang97** [bytedeco/javacv#2290]
How to successfully create a dependency for Java CV? I want to use OpenCV-4.7.0-1.5.9-linux-arm64-gpu. jar, but the official website does not publish it. I have already compiled the SO and related files for OpenCV-4.7-gpu on arm64, but the generated. jar cannot be recognized by GPUs when placed in OpenCV dependencies. How can I generate a dependency for Java CV, OpenCV-4.7.0-1.5.9-linux-arm64-gpu. jar, and make the GPU available?

**Comment by saudet** [comment]
Binaries for that have been release, please try them out:
https://repo1.maven.org/maven2/org/bytedeco/opencv/4.7.0-1.5.9/

**Comment by saudet** [comment]
Right, there's no CUDA binaries for linux-arm64-gpu. What's the error message you're getting?

**Comment by yibinzhang97** [comment]
> Right, there's no CUDA binaries for linux-arm64-gpu. What's the error message you're getting?

I just want to compile a CUDA OpenCV version that can be used with ARM

**Comment by saudet** [comment]
Sure, something like `mvn clean install -Djavacpp.platform=linux-arm64 -Djavacpp.platform.extension=-gpu` should work:
https://github.com/bytedeco/javacpp-presets?tab=readme-ov-file#build-instructions

**Comment by saudet** [comment]
Duplicate of #2292
