### ISSUE TITLE
build linux-arm64-gpu error:  __aarch64_ldadd4_acq_rel

### ISSUE THREAD

**Issue by yibinzhang97** [bytedeco/javacv#2292]
opencv:4.7.0
CUDA:12.2
g++:g++11

/usr/lib/jvm/jdk1.8.0_411/jre/bin/java: symbol lookup error: /root/.javacpp/cache/opencv-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_video.so: undefined symbol: __aarch64_ldadd4_acq_rel

How can I solve this problem?

**Comment by saudet** [comment]
Please don't open duplicate issues

It looks like the answer to your question is available here:
https://github.com/opencv/opencv/issues/24856#issuecomment-1915429405

**Comment by yibinzhang97** [comment]
I have reviewed this issue and made the necessary settings, but it still appears as __aarch64_1dadd4_comc_rel. The difference in this statement is __aarch64_1dadd8_comc_rel, but "__aarch64_1dadd8_comc_rel" has not appeared before

**Comment by saudet** [comment]
In any case, it's something wrong with your compiler. Try a different one, clang vs gcc, different versions, old and new, etc.

**Comment by yibinzhang97** [comment]
I solved this problem by lowering the compiler version

**Comment by bluehatch** [comment]
> I solved this problem by lowering the compiler version

I am having similar error. I am curious what compiler version you used.
Could you please give me an example of your settings.

Environment: javacpp: 1.5.10, opencv: 4.9.0
Error: `java: symbol lookup error: /home/flomon/.javacpp/cache/opencv-linux-arm64-gpu.jar/org/bytedeco/opencv/linux-arm64-gpu/libjniopencv_objdetect.so: undefined symbol: __aarch64_ldadd4_acq_rel`
