### ISSUE TITLE
Ffmpeg can not find drawtext filter on windows

### ISSUE THREAD

**Issue by TnoAlex** [bytedeco/javacv#2309]
Hi, I tried adding text to a video using ffmpeg in javacv on Windows, but it prompts "Error: [AVFilterGraph @ 000000002e299380] No such filter: 'drawtext' " when filter starts. How can i fix it, Thanks

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify FFmpegFrameFilter to load the drawtext filter and ensure it's available for use on Windows platforms. This change adds a check for the drawtext filter and loads it if necessary.

You can review changes in this commit: https://github.com/kkpo4553/bytedeco-javacv-2309/commit/52a655787669c7003896264983ff1c5797d97678.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by saudet** [comment]
Duplicate of #2153

**Comment by saudet** [comment]
Fixed with pull https://github.com/bytedeco/javacpp-presets/pull/1731.
Please try again with the snapshots: https://central.sonatype.com/service/rest/repository/browse/maven-snapshots
