### ISSUE TITLE
Class FFmpegFrameGrabber not found when trying to build the newest version

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#231]
When I try to build the newest version as 1.1-SNAPSHOT the class FFmpegFrameGrabber cannot be found. I get an error and cannot import it either when using the jar. Rest of the classes is still there however.
Did you remove/rename or repackage it or did I do something wrong when building or is it a bug in the build?

**Comment by saudet** [comment]
We need to build with the ffmpeg profile. Check inside the pom.xml file.

**Comment by The-Crocop** [comment]
Thank you it worked !

**Comment by leeking5300** [comment]
Hi. I got the same problem.Here was my operation about install javacv
1.  ENV:ubuntu 14.04
2. JDK1.7
3.  maven 3.3
4. run CMD: mvn install 
5. jar -xvf javacv.jar org

After all this,CD to org path ,and Class FFmpegFrameGrabber  doesn't exist.
 Can U just show me how to fixed this issue?

**Comment by saudet** [comment]
Try running `mvn install -Pffmpeg` instead.

**Comment by leeking5300** [comment]
Just mvn install -Pffmpeg?No needs mvn install before?
