### ISSUE TITLE
output.wav procedued by FFmpegFrameRecorder andFFmpegFrameGrabber is not the same with  FFmpeg cli tool

### ISSUE THREAD

**Issue by tiandiweizun** [bytedeco/javacv#2310]
- FFmpeg cli tool version: ffmpeg version N-113005-g419145c11b-20231217 Copyright (c) 2000-2023 the FFmpeg developers
 built with gcc 13.2.0 (crosstool-NG 1.25.0.232_c175b21)
- system: windows 10
- org.bytedeco.javacv: 1.5.10
- org.bytedeco.ffmpeg:6.1.1-1.5.10

When I convert a mp3 file to wav file, the wav file  procedued by FFmpegFrameRecorder andFFmpegFrameGrabber is not the same with  FFmpeg cli tool

 FFmpeg cli command: `ffmpeg  -i C:\Users\Administrator\Desktop\asr_demo.mp3  -acodec pcm_s16le  -ar 16000 asr_demo.wav`
Java code:
```
 public static void convert() throws Exception {
        String fileName = "C:\\Users\\Administrator\\Desktop\\asr_demo.mp3";

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(fileName);
        grabber.start();
        FrameRecorder recorder = new FFmpegFrameRecorder("C:\\Users\\Administrator\\Desktop\\asr_demo1.wav", grabber.getAudioChannels());
        recorder.setSampleRate(16000);
        recorder.setAudioCodec(avcodec.AV_CODEC_ID_PCM_S16LE);
        recorder.setAudioQuality(0);
        recorder.setAudioOption("crf", "0");
        recorder.setAudioOption("aq", "10");
        recorder.start();

        Frame frame;
        while ((frame = grabber.grabFrame()) != null) {
            recorder.record(frame);
        }
        grabber.stop();
        recorder.stop();
    }
```
The length of file procedued  by FFmpeg  cli tool : 28606080
The length of file procedued  by org.bytedeco.javacv : 28606016
Threre is a 64-element length difference between two file , the original mp3 file is two channels,and sample rate of wav file is 16000, so there is a 2ms time difference。

Assuming the difference  is in the end , the diff max value is 0.088686764
```
    public static void diff() throws Exception {
        Audio audio = FFmpegAudioFactory.newInstance().fromFile(new File("C:\\Users\\Administrator\\Desktop\\asr_demo.wav").toPath());
        Audio audio1 = FFmpegAudioFactory.newInstance().fromFile(new File("C:\\Users\\Administrator\\Desktop\\asr_demo1.wav").toPath());
        assert audio1.getSampleRate() == audio.getSampleRate();
        assert audio1.getChannels() == audio.getChannels();
        int min = Math.min(audio1.getData().length, audio.getData().length);
        float max = 0;
        for (int i = 0; i < min; i++) {
            float v = Math.abs(audio1.getData()[i] - audio.getData()[i]);
            max = Math.max(v, max);
        }
        System.out.println(max);
    }
```

**Comment by saudet** [comment]
We can easily accomplish this with the ffmpeg program:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

**Comment by tiandiweizun** [comment]
> We can easily accomplish this with the ffmpeg program: http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/ffmpeg/ffmpeg.html

Thank you for your advice
