### ISSUE TITLE
After the end of the frame extraction task, the memory usage of the project has not decreased, resulting in the restart of the project.

### ISSUE THREAD

**Issue by yy73** [bytedeco/javacv#2312]
Code configuration：
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(url);
        Frame frame = null;
        try {
            // 设置读取的最大数据，单位字节
            grabber.setOption("probesize", "10000");
            // 设置分析的最长时间，单位微秒
            grabber.setOption("analyzeduration", "10000");
            // 超时时间
            grabber.setOption("timeout", "5*1000*1000");
            // "nokey"  表示FFmpeg将跳过所有没有关键帧的帧。
            grabber.setVideoOption("skip_frame", "nokey");
            //  "nobuffer"  表示不缓冲输出
            grabber.setVideoOption("fflags", "nobuffer");
            grabber.setVideoOption("rtsp_transport", "tcp");
            grabber.setOption("rtsp_flags", "prefer_tcp");
            avutil.av_log_set_level(avutil.AV_LOG_ERROR);
            grabber.start();
            frame = grabber.grabImage();
            if (frame == null) {
                new ServerException(ErrorCodeConstants.FRAME_URL_VALID);
            }
            String path = saveFrameImage(imageToBufferedImage(frame));

<img width="177" alt="image" src="https://github.com/user-attachments/assets/ba3a90eb-772a-4e30-b1dc-6c4322471e08" />

**Comment by saudet** [comment]
Please call close()
