### ISSUE TITLE
Video color is strange when use FFmpegFrameFilter to add watermark  

### ISSUE THREAD

**Issue by ongakuer** [bytedeco/javacv#232]
Hello,Samuel. Thanks for your this powerful project. 
I try to use ```FFmpegFrameFilter``` to add watermark.
```java
new FFmpegFrameFilter("movie=image.png [logo];[in][logo]overlay=0:0:1[out]",WIDTH, HEIGHT);
```

But the video color is strange.  Can you give me some advice?

I think I can convert Frame to IplImage or Mat by import OpenCV to add watermark.  But I would like to just use FFmpeg.

![screenshot_2015-09-25-17-06-13](https://cloud.githubusercontent.com/assets/1284428/10097072/082f3c48-63a9-11e5-9f67-fd9ebd26a765.png)

**Comment by saudet** [comment]
Looks like you're going to need to convert that to BGR if you want to use the result with OpenCV.

**Comment by ongakuer** [comment]
I wonder why the video color is strange when I use FFmpegFrameFilter ?

**Comment by saudet** [comment]
The messages display on the console might tell us more about what might be happening...

**Comment by Iqra786** [comment]
I had same problem. Getting error 
No accelerated colorspace conversion found from yuv420p to bgr24.
How can I convert to BGR24. Any hint?

**Comment by Iqra786** [comment]
Try following filter:- It works fine. Took one day to figureout.

new FFmpegFrameFilter("movie=image.png [logo];[in][logo]overlay=0:0:1:format=rgb [out]",WIDTH, HEIGHT);

**Comment by ongakuer** [comment]
@Iqra786 
Good job! Thanks!

**Comment by fpv999** [comment]
new FFmpegFrameFilter("movie=image.png [logo];[in][logo]overlay=0:0:1:format=rgb [out]",WIDTH, HEIGHT);
This is not working anymore in current version. I see no logo at all.

**Comment by saudet** [comment]
@fpv999 This has been fixed with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a. Please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/
