### ISSUE TITLE
Display Mat image

### ISSUE THREAD

**Issue by sbakiu** [bytedeco/javacv#233]
I have a `opencv_core.Mat` image and i want to display it somehow. Is there anything available like `Imgcodecs.imwrite` in OpenCV?

**Comment by saudet** [comment]
imwrite() is there.

**Comment by sbakiu** [comment]
Thank you for the answer. But i am really struggling can I convert the FloatImage (or ByteImage) to IplImage?

**Comment by saudet** [comment]
What is a FloatImage (or a ByteImage)?

**Comment by sbakiu** [comment]
Sorry my bad.
