### ISSUE TITLE
How to set fixed HLS segment duration in FFmpegFrameRecorder implementation.

### ISSUE THREAD

**Issue by pallab-gain** [bytedeco/javacv#234]
Hi,
I am using FFmpegFrameRecorder to record hls video in android. To this this, I changed input file name to **sample_file_name.ts**, and recording format to **hls** using ```recorder_instance.setFormat("hls")```. 

With this default settings, I am getting variable length ts segment for different sessions. I want my ts segment length to be always 10 second for any session. How can I achieve this with javacv ?

I though, I could achieve this using C code as
```av_opt_set_int(outputFormatContext->priv_data, "hls_time", hlsSegmentDurationSec, 0)``` where 
outputFormatContext is of type AVFormatContext.

So, I tried to call ```av_opt_set_int(this.oc.priv_data(), "hls_time",10,0);``` before 
```avformat_write_header(oc.metadata(metadata), options)``` in https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L653 this code. But, this doesn't work. Can you please tell where I am doing wrong, and how can I always achieve fixed(10 second, or 5 second or x second) length ts file  ? 

Regards,
Pallab

**Comment by saudet** [comment]
Have you tried using setOption()?

**Comment by pallab-gain** [comment]
Thank you for quick suggestion. I am sorry, but I could not understand how, and where to call setOption. So, I called ```setOption("hls_time","10")``` just above https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L653. This doesn't work.
So, I also tried to call ```setOption("hls_time","10")``` above this line https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L514, and it didn't work too.

I also tried to call ```this.oc.max_chunk_duration(10)``` just above line 514 without any luck. I am so sorry if my approaches sound desperate, this is my first day with opencv. Can you please suggest what else I can do to implement fixed length ts file ?

**Comment by pallab-gain** [comment]
I think, I now understand how ```setOption``` work, and I again added ```hls_time``` equal to 10 in ```av_dict_set``` using ```setOption``` method. But, it still doesn't make fixed 10 second chunk. I can see default hls_time is always set to 2.0 by using 
```String param_name = oformat.priv_class().option().position(1).name().getString()```
```double default_value = oformat.priv_class().option().position(1).default_val_dbl()```

**Comment by saudet** [comment]
Why not just call `av_opt_set_int()` exactly the same way in Java than in C? There is no reason this would not work.

**Comment by pallab-gain** [comment]
Hi!
Thanks again for your help, and suggestions. I just achieved this with  ```setGopSize``` method of ```FrameRecorder``` class. Setting hls_time had no effect unless I set I-frame request according. So, it worked as expected after I set desired GopSize. 

Regards,
Pallab

**Comment by saudet** [comment]
Are you saying that `setGopSize(someLargeValue)` + `setOption("hls_time","10")` gives the desired result?
