### ISSUE TITLE
 no-video (-vn) option not working

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#235]
In https://github.com/bytedeco/javacv/issues/188 you said that the vn option from ffmpeg could be emulated by setting width and image heighhht to 0 before calling start().

However that does not work for me. When I do that I get the error message "is image width  and image height 0 and has start() been called?" . So what is the right way to only extract and restream the audio part of a stream?

**Comment by saudet** [comment]
Maybe you were talking about the `grabImage()` method as explained in issue https://github.com/bytedeco/javacv/issues/116?

**Comment by The-Crocop** [comment]
No grabImage works. I want to only grab the audio (-vn option in ffmpeg). In the #188  post you suggested setting width and height to 0 in the FFmpegFrameRecorder. However that does not work, I get the following error. I tried with grabber.grabFrame(false, true, false). But that doesnt work either. I get:

org.bytedeco.javacv.FrameRecorder$Exception: No video output stream (Is imageWidth > 0 && imageHeight > 0 and has start() been called?)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:697)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:686)
	at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:679)

Any suggestions how I can achieve this? (extracting only the audio from a stream)

**Comment by saudet** [comment]
Ah, I see, it's easy enough to add a new `grabSamples()` method.
Here, I've added one in this commit: https://github.com/bytedeco/javacv/commit/cc420a8d7b88006ed52f314c55f87f0e84227e1f

**Comment by The-Crocop** [comment]
Awsome man. Thank you! Works like a charm :)
