### ISSUE TITLE
FFmpegFrameGrabber Issue: setFrameNumber and then grabImage, "bad src image pointers"

### ISSUE THREAD

**Issue by chuangtsing** [bytedeco/javacv#236]
Hi, 

I am trying to grab some specific frames (e.g., one frame per second) from a mp4 video file using FFmpegFrameGrabber as in the code snippet.

Most of the times, the frames I got were black (blank), and when I grabbed each frame I got the warning of "bad src image pointers". I note that when I set the frame number first and then grab an image, it seems FFmpegFrameGrabber will return the buffered image produced during the setting of frame number (or timestamp). I do not know what is the reason of these black frames or do I miss something here? If I am wrong, what is the right way to grab specific frames from a video. Thanks. 

            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("/sdcard/Download/test.mp4");
            try {
                OpenCVFrameConverter.ToIplImage converterToIplImage = new OpenCVFrameConverter.ToIplImage();
                grabber.start();
                int frame_count = grabber.getLengthInFrames();
                for(int i=0; i<frame_count; i+=grabber.getFrameRate()){
                    grabber.setFrameNumber(i);
                    Frame frame = grabber.grabImage();
                    if(frame == null) break;
                    if(frame.image == null) continue;
                    IplImage image = converterToIplImage.convert(frame);
                    String img_path = "/sdcard/Download/" + "frame-" + String.valueOf(i) +".jpg";
                    cvSaveImage(img_path, image);
                }
            }
            catch (Exception e) {
                e.printStackTrace();
            }

**Comment by saudet** [comment]
Sure, it's not very robust functionality, so it probably doesn't work well on all formats and files. If you could look into this and figure out a way to make it better, send a pull request, and I will gladly accept it. Thank you!

**Comment by chuangtsing** [comment]
I found that if I did not set the frame number at the first place (i.e., when i = 0), the frames were grabbed correctly using the following code. I do not know the reason of that, but I will dig if I get time. 

        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("/sdcard/Download/test.mp4");
        try {
            OpenCVFrameConverter.ToIplImage converterToIplImage = new OpenCVFrameConverter.ToIplImage();
            grabber.start();
            int frame_count = grabber.getLengthInFrames();
            for(int i=0; i<frame_count; i+=grabber.getFrameRate()){
                if (i > 0) grabber.setFrameNumber(i);
                Frame frame = grabber.grabImage();
                if(frame == null) break;
                if(frame.image == null) continue;
                IplImage image = converterToIplImage.convert(frame);
                String img_path = "/sdcard/Download/" + "frame-" + String.valueOf(i) +".jpg";
                cvSaveImage(img_path, image);
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }

**Comment by saudet** [comment]
Thanks!! So, is it just grabImage() after setTimestamp() that is broken?

**Comment by chuangtsing** [comment]
It seems that you have to grab a frame before the first time of calling setTimestamp(). By doing so, it works properly.

**Comment by chuangtsing** [comment]
Saudet, 

I noticed you have fixed the problem. I tried to compile javacv for android by my own, but without success. I was wondering whether you could publish an updated opencv.jar with the problem fixed. Thanks.

**Comment by saudet** [comment]
Fix included in version 1.1. Thanks for reporting!

**Comment by taozhiheng** [comment]
I am trying to grab frames from rtmp stream.I use the method what chuangtsing writes:

```
grabStep = frameRate*2;
...
expectNumber += grabStep;
grabber.setFrameNumber(expectNumber);
...
```

when the process works for several hours, it throws Exception:
org.bytedeco.javacv.FrameGrabber$Exception: avformat_seek_file() error -38: Could not seek file to timestamp 446491980000.
	at org.bytedeco.javacv.FFmpegFrameGrabber.setTimestamp(FFmpegFrameGrabber.java:340)
	at org.bytedeco.javacv.FFmpegFrameGrabber.setFrameNumber(FFmpegFrameGrabber.java:326)
	at com.persist.GrabThread.grab(GrabThread.java:167)
	at com.persist.GrabThread.run(GrabThread.java:106)


I don't know why.Is the expectNumber too large?How to deal with Exception so  that the process can continue to grab new frames?
Thanks!!!
(I am not good at English, please forgive me.~_~)

**Comment by saudet** [comment]
@taozhiheng Your stream doesn't support seeking, that's all.

**Comment by taozhiheng** [comment]
Sometimes, FFmpegFrameGrabber.grabImage() never returns when it is invoked to grab frames from some video files in Java child process.
I don't what happended.
How can I resolve it?

**Comment by gkozyryatskyy** [comment]
Seems like this bug it still there.
Im using javacv 1.3.3 and when Im doing this:
```
    public static void test() throws Exception {
        long startTime = 0l;
        long endTime = 1000l;
        File out = new File("out.mp4");

        try (FFmpegFrameGrabber video = new FFmpegFrameGrabber(
                new File("/Users/gleb.kozyryatskyy/Downloads/Celebrity Beauty and Lifestyle David Laport.mp4"))) {
            video.start();
            try (FFmpegFrameRecorder rec = new FFmpegFrameRecorder(out, video.getImageWidth(), video.getImageHeight(),
                    video.getAudioChannels())) {
                rec.start();
                Frame frame;
                video.setTimestamp(TimeUnit.MILLISECONDS.toMicros(startTime));
                while (video.getTimestamp() <= TimeUnit.MILLISECONDS.toMicros(endTime)
                        && (frame = video.grab()) != null) {
                    rec.record(frame);
                }
            }
        }
    }
```
I got `[swscaler @ 0x7fa264302400] bad src image pointers` and first frame is black.
but if I initing frame as `Frame frame = video.grab();` like this 
```
    public static void test() throws Exception {
        long startTime = 0l;
        long endTime = 1000l;
        File out = new File("out.mp4");

        try (FFmpegFrameGrabber video = new FFmpegFrameGrabber(
                new File("/Users/gleb.kozyryatskyy/Downloads/Celebrity Beauty and Lifestyle David Laport.mp4"))) {
            video.start();
            try (FFmpegFrameRecorder rec = new FFmpegFrameRecorder(out, video.getImageWidth(), video.getImageHeight(),
                    video.getAudioChannels())) {
                rec.start();
                Frame frame = video.grab();
                video.setTimestamp(TimeUnit.MILLISECONDS.toMicros(startTime));
                while (video.getTimestamp() <= TimeUnit.MILLISECONDS.toMicros(endTime)
                        && (frame = video.grab()) != null) {
                    rec.record(frame);
                }
            }
        }
    }
```
Seems like everything is fine!

**Comment by gkozyryatskyy** [comment]
Ok. Seems like that was the problem with exactly `video.setTimestamp(0l)`

Also I found that `video.getFormatContext().start_time()` can be < 0 and then `setTimestamp` method will skip all the video frames with (part of setTimestamp method code)
```
while (this.timestamp > timestamp + 1 && grabFrame(false, true, false, false) != null) {
// flush frames if seeking backwards
}
```

should it be fixed somehow? @saudet

**Comment by saudet** [comment]
@gkozyryatskyy If timestamps move forward, I'm not sure how this is a problem? In any case, please send a pull request, or if you don't have a fix to recommend, please open another issue. This one has been fixed. Thanks!

**Comment by gkozyryatskyy** [comment]
Here it is https://github.com/bytedeco/javacv/issues/841
