### ISSUE TITLE
setVideoCodec with AV_CODEC_ID_H264 have no effect

### ISSUE THREAD

**Issue by phajduk** [bytedeco/javacv#237]
Hi, I'm using `FFmpegFrameRecorder` on Android. Here's my snippet:

``` java
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(file, 640, 360);
recorder.setFormat("mp4");
recorder.setVideoOption("preset", "ultrafast");
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setFrameRate(30);
recorder.start();
```

Later in code, I just call `recorder.record(frame)` to save grabbed frames. It seems like `AV_CODEC_ID_H264` have problems as recorded file in such way is broken. When I remove line with `setVideoCodec` then recorded file can opened in VLC but codec is MPEG-4 visual. @saudet do you have any ideas what could go wrong?

I've also tried `setVideoCodecName("h264")` which has been fixed in recent commits but still no effect. Recorded file use MPEG-4 visual codec.

Thanks!

**Comment by saudet** [comment]
Make sure to call recorder.stop() when done recording.

**Comment by phajduk** [comment]
Yes, I'm calling it. It seems like `AV_CODEC_ID_H264` have some impact as without 
````java
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
``` 

video file is OK.

**Comment by saudet** [comment]
Do you get the same behavior on other platforms like Linux or Windows?

**Comment by The-Crocop** [comment]
for setVideoCodecName you should use setVideoCodecName("libx264") that works for me

**Comment by phajduk** [comment]
@saudet I didn't port this solution to console app. Is it possible that I have JavaCV without h264 codec?

@The-Crocop: are you using Android? 

I tried libx264 but then I see
`avcodec_open2() error -22: Could not open video codec.`

Seems like `FFmpegFrameRecorder` throw it here:
```java
/* open the codec */
            if ((ret = avcodec_open2(video_c, video_codec, options)) < 0) {
                release();
                throw new Exception("avcodec_open2() error " + ret + ": Could not open video codec.");
            }
```

**Comment by The-Crocop** [comment]
No Im using it on linux

**Comment by saudet** [comment]
@phajduk I'd like to know if this something that happens only with Android or not, so if you could please try on another platform, it would help a lot, thank you.

**Comment by phajduk** [comment]
@saudet 
I've ported my solution to the console app. When I set 
`grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);`
then console app generates such file
```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
```

in Android with same options it generates following:
```
Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format profile                           : Simple@L1
Format settings, BVOP                    : No
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : 20
```

**Comment by saudet** [comment]
I see, so we need to see FFmpeg's log on Android, but I'm not sure how to
do that...

**Comment by phajduk** [comment]
I would like to help with that. In Android we can put log data into logcat (it's terminal based log which is Android-specific). However, I'm not sure how it should be done in JavaCV. Do we need it in Java or native code?

**Comment by saudet** [comment]
I've taken some time to hack FFmpeg's log functions and redirect them to Java (or Android's log). There's a new `FFmpegLogCallback` class in JavaCV. Call the static `set()` method somewhere during init and let me know what shows up in the log. Incidentally, I've the switched the H.264 encoder from x264 to OpenH264, so that should change the behavior as well. Let me know what you get with that! Thanks

**Comment by phajduk** [comment]
@saudet thanks for changes! I would like to use this new features to provide log with info why setting codec is not working.

Is it possible to release new version of libs including these changes? I met problems with compiling JavaCV (more precisely JavaCPP-Presets dependency) so I rely on maven central.

**Comment by saudet** [comment]
I've added a new wiki page that should help you with that:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by saudet** [comment]
I've just released version 1.1. Could you try the new binaries and let me know if this issue still occurs? Thanks!

**Comment by ytarek** [comment]
@saudet just a quick question ,how is it possible to use libx264 to encode on android now since you have " switched the H.264 encoder from x264 to OpenH264" . thanks

**Comment by saudet** [comment]
@ytarek I didn't have to switch after all. libx264 still gets used by default.

**Comment by saudet** [comment]
Version 1.2 has just been released! Could you try again with that version and show me the log your get? Thanks!

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming this is working with JavaCV 1.2 (or 1.3), but let me know if this is not the case! Thanks
