### ISSUE TITLE
I am taking 1280*720 video from camera using javacv with usual process given in sample ,it is hanging while recording video,video not hanging below<=480 ,how can i take hd video without hanging

### ISSUE THREAD

**Issue by justflyhard** [bytedeco/javacv#240]

**Comment by saudet** [comment]
What messages do you get in the log file?

**Comment by justflyhard** [comment]
no messages in log 
cpu processing slow for 1280*720 (hangs means processing slow ) 
10-15 frames per second ,recorder taking too much time to record 
but in case of <=480 it survives

**Comment by justflyhard** [comment]
@saudet  when button clicked video recording started.
progressbar not moving smooth ...video hangs and when you click stop button recorder stop after 25-30 seconds which is not correct.recorder has to stop immediately 
all these performance issues in 1280*720 not for <=480

**Comment by saudet** [comment]
Sounds like pretty normal behavior for mobile devices to me...

**Comment by saudet** [comment]
BTW, you might be able to get better performance by rebuilding FFmpeg with NEON instructions, or in 64-bit mode if you have a 64-bit CPU.
