### ISSUE TITLE
POM error about Maven Dependency Plugin

### ISSUE THREAD

**Issue by alicanalbayrak** [bytedeco/javacv#242]
When I checkout project to the eclipse there is an error which it says: 

"Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:2.3:properties (execution: properties, phase: initialize)"

       <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.3</version>
        <executions>
          <execution>
          <phase></phase>  <---------- I Added This
            <id>properties</id>
            <goals>
              <goal>properties</goal>
            </goals>
          </execution>
          <execution>
          <phase></phase> <---------- I Added This
            <id>copy-dependencies</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}</outputDirectory>
              <stripVersion>true</stripVersion>
            </configuration>
          </execution>
        </executions>
      </plugin>

As you can see above, after addition of <phase> tag, error disappeared. Do you know why ?

**Comment by saudet** [comment]
I've just updated all the Maven plugins used to their latest versions in the latest commits of javacpp, javacpp-presets, and javacv, so pull all the latest changes and try it again. It should work now.

**Comment by saudet** [comment]
This should be fixed in version 1.1. Let me know if you still get the error though, thanks!

**Comment by garzy** [comment]
[ERROR] Failed to execute goal on project javacv: Could not resolve dependencies for project org.bytedeco:javacv:jar:1.2-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco:javacpp:jar:1.2-SNAPSHOT, org.bytedeco.javacpp-presets:opencv:jar:3.1.0-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:ffmpeg:jar:2.8.4-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:flycapture:jar:2.8.3.1-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:libdc1394:jar:2.2.3-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:libfreenect:jar:0.5.3-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:videoinput:jar:0.200-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:artoolkitplus:jar:2.3.1-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:flandmark:jar:1.07-1.2-SNAPSHOT: Could not find artifact org.bytedeco:javacpp:jar:1.2-SNAPSHOT -> [Help 1]

**Comment by saudet** [comment]
@garzy You also need to install `javacpp` and `javacpp-presets`...
