### ISSUE TITLE
newer haarcascade_frontalface_alt.xml not work

### ISSUE THREAD

**Issue by leyewen** [bytedeco/javacv#246]
I use newer version haarcascade_frontalface_alt.xml replace demo's:
```java
URL url = new URL("https://raw.github.com/Itseez/opencv/2.4.0/data/haarcascades/haarcascade_frontalface_alt.xml");
```
just like, replace with:
```java
URL url = new URL("https://raw.githubusercontent.com/Itseez/opencv/master/data/haarcascades/haarcascade_frontalface_alt.xml");
```
but it not work, throw exception:
```
 OpenCV Error: Unspecified error (The node does not represent a user object (unknown type?)) in cvRead, file src\persistence.cpp, line 4976
 Exception in thread "main" java.lang.RuntimeException: src\persistence.cpp:4976: error: (-2) The node does not represent a user object (unknown type?) in function cvRead
 at org.bytedeco.javacpp.opencv_core.cvLoad(Native Method)
```

how to slove this error?

**Comment by saudet** [comment]
The old C API does not support the newer haarcascade format. Please try again with the C++ API.

**Comment by MarcoVCiotola** [comment]
Hey Saudet, I know this issue is closed, but could you be so kind and explain how to use the C++ API to load the newers haarcascade formats?

Thanks  a lot in advance.

**Comment by saudet** [comment]
https://github.com/Itseez/opencv/blob/3.0.0/samples/cpp/facedetect.cpp

If you have any issues porting that to Java, please let me know. And please consider making a contribution by providing a ported version of that sample. Thank you!
