### ISSUE TITLE
Are there any methods to reduce the "libavcodec.so" file's size? It has 13.2m.

### ISSUE THREAD

**Issue by szitguy** [bytedeco/javacv#247]

**Comment by saudet** [comment]
Sure, just remove the codecs you're not going to use, and rebuild!

**Comment by szitguy** [comment]
@saudet Thank you for your reply. But do you mean using javacpp-presets to rebuild?

**Comment by saudet** [comment]
Yes, modify the cppbuild.sh file to suit your needs, and use that to
rebuild.

**Comment by szitguy** [comment]
@saudet Thank you! I tried to rebuild ffmpeg by using the javacpp-presets yesterday, but i got some problems.

1.On Mac OSX 10.10, when execute cppbuild.sh,i got this:
checking how to run the C preprocessor... /lib/cpp
configure: error: C preprocessor "/lib/cpp" fails sanity check

i checked issue 45 in javacpp-presets but still not work.

2.On Ubuntu12.04, I build .so files successfully, but then i execute mvn install ..., i got this:
javacpp-presets/ffmpeg/target/classes/org/bytedeco/javacpp/jniavcodec.cpp:46:21: fatal error: exception: No such file or directory #include exception

Finally, i failed to rebuild ffmpeg.

**Comment by saudet** [comment]
As mentioned in the README.md file, JavaCPP requires a C++ compiler. On Mac OS X we can get one by installing Xcode, and on Ubuntu, please install GCC.

**Comment by szitguy** [comment]
@saudet Both on Mac and Ubuntu I had installed them, but it still failed.

**Comment by saudet** [comment]
Ok, if you figure out what makes it work on your system, please let us know, thanks!

**Comment by szitguy** [comment]
@saudet 
javacpp-presets/ffmpeg/target/classes/org/bytedeco/javacpp/jniavcodec.cpp:46:21: fatal error: exception: No such file or directory #include exception
it seems like can't find gnustl_static, if config this at a Application.mk file i can fix it. but where should i place the file?

**Comment by szitguy** [comment]
@saudet I fix the problem:
javacpp-presets/ffmpeg/target/classes/org/bytedeco/javacpp/jniavcodec.cpp:46:21: fatal error: exception: No such file or directory #include exception

it is because the stl path setting error
andoroid ndk r10e doesn't have the 4.6 dir but the 4.8 and 4.9.
I don't know where to set the path,so i change my ndk dir /Users/apple/Desktop/android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/ to /Users/apple/Desktop/android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.6/libs/armeabi/

Can you tell me where to set the stl path?

**Comment by saudet** [comment]
That's already been fixed in this commit: https://github.com/bytedeco/javacpp-presets/commit/12466f8995bc8836a83cac6acd904b32626f1888
Please use the latest version of the source code. Thank you

**Comment by szitguy** [comment]
OK，I will try it later.

**Comment by saudet** [comment]
I've added a new wiki page that should help you with that:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by szitguy** [comment]
@saudet Thank you very much!
