### ISSUE TITLE
cannot locate symbol "av_get_pix_fmt_loss" referenced by "libjniavutil.so" && ClassNotFoundException: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by DelayDan** [bytedeco/javacv#248]
I'm using android studio 1.3. Downloaded javacv-1.0-bin.zip. I put ffmpeg.jar,ffmpeg-android-lib.jar,javacpp.jar,javacv.jar into app/libs folder. For most phones it worked. But for some phone it will report two problems.
1. cannot locate symbol "av_get_pix_fmt_loss" referenced by "libjniavutil.so" 
this happens on   ffmpegframerecorder.tryLoad().  
2. ClassNotFoundException: org.bytedeco.javacpp.avutil
This happens on new FFmpegFrameReocrder(..)

I also run the sample project, same issues. Pls help me, I've been researching for days but still cannot make it work. Thanks a million.

Log 1:
```
10-09 10:57:41.674  23114-23114/com.xxx.xxx E/dalvikvm﹕ dlopen("/data/app-lib/com.xxx.xx-1/libjniavutil.so") failed: dlopen failed: cannot locate symbol "av_get_pix_fmt_loss" referenced by "libjniavutil.so"...
10-09 10:57:41.674  23114-23114/com.xxx.xxx W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lorg/bytedeco/javacpp/avutil;
10-09 10:57:41.674  23114-23114/com.xxx.xxx I/com.xxx.xxx.MainApplication﹕ load in advance failure
```

Log 2:
```
 Process: org.bytedeco.javacv_android_example, PID: 3580
    java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
            at org.bytedeco.javacpp.Loader.load(Loader.java:392)
            at org.bytedeco.javacpp.Loader.load(Loader.java:358)
            at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1407)
            at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:149)
            at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:129)
            at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:153)
            at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:171)
            at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:221)
            at android.view.View.performClick(View.java:4558)
            at android.view.View$PerformClick.run(View.java:19006)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5054)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by boybeak** [comment]
try to add ffmpeg.jar to you lib

**Comment by DelayDan** [comment]
@boybeak thanks, I did add ffmepg.jar.  Check the screenshot.
![Uploading Screen Shot 2015-10-10 at 9.32.08 AM.png…]()

**Comment by DelayDan** [comment]
@boybeak I did add ffmpegjar. 
![screen shot 2015-10-10 at 9 32 18 am](https://cloud.githubusercontent.com/assets/15043165/10408519/ec1d954c-6f31-11e5-9b07-44c30598f6ec.png)

**Comment by saudet** [comment]
There have been some changes since version 1.0 in that regard, so would it possible to try with the latest source code and let me know if this still happens? Thanks!

**Comment by DelayDan** [comment]
@saudet Thanks. I tried that. But I only have android studio and the sources cannot be compiled due to lack of some packages like awt which is not available in android IDE. I guess a different environment may be needed to set up. With no luck, it is out of my knowledge to solve.   I think I shall wait for the new version.

**Comment by saudet** [comment]
Please refer to the README.md files for instructions on how to rebuild.
Thank you

**Comment by saudet** [comment]
I've just added a new wiki page that should help you with that:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments

**Comment by DelayDan** [comment]
@saudet Thanks a log. I don't have linux pc setup. So instead I use my Mac. I got some errors when rebuilding, does that mean linux is a must?
the Logs:
/Users/dan/Documents/library/ndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: ../libmp3lame/.libs/libmp3lame.a: no archive symbol table (run ranlib)
lame_main.o:lame_main.c:function init_files: error: undefined reference to 'lame_get_decode_only'
lame_main.o:lame_main.c:function printInputFormat: error: undefined reference to 'lame_get_version'
lame_main.o:lame_main.c:function printInputFormat: error: undefined reference to 'lame_get_out_samplerate'
lame_main.o:lame_main.c:function lame_decoder: error: undefined reference to 'lame_get_num_channels'
lame_main.o:lame_main.c:function lame_decoder: error: undefined reference to 'lame_get_in_samplerate'
lame_main.o:lame_main.c:function lame_decoder: error: undefined reference to 'lame_get_num_samples'
lame_main.o:lame_main.c:function lame_decoder: error: undefined reference to 'lame_get_num_samples'
lame_main.o:lame_main.c:function lame_decoder: error: undefined reference to 'lame_get_in_samplerate'
lame_main.o:lame_main.c:function lame_decoder: error: undefined reference to 'lame_get_in_samplerate'
lame_main.o:lame_main.c:function lame_decoder: error: undefined reference to 'lame_get_in_samplerate'

**Comment by saudet** [comment]
Well, I've heard other people having problem with LAME on Mac OS X, but if you're not concerned with MP3 encoding, just removing anything that has to do with LAME from the script file, and try again. It might just work :)

**Comment by saudet** [comment]
I've release version 1.1. Could you check if this still happens? Thanks!

**Comment by saudet** [comment]
Given the lack of feed back, I am assuming that issue has been resolved, so I am closing this, but if not, please let me know!
