### ISSUE TITLE
RTSP encryptation support

### ISSUE THREAD

**Issue by rpgomes** [bytedeco/javacv#251]
Hello,

I have an recorder that support rtsp encryptation (AES)
javaCV support encryptation ?
if yes, which function I need to call?

**Comment by saudet** [comment]
It's built-in, it should just work. What error do you get?

**Comment by rpgomes** [comment]
Hi,

I'm not getting any error, I just want to know wich function should I call to stream a rtsp with encryptation and if it's possible using javaCV

**Comment by saudet** [comment]
FFmpeg supports it, so it should be possible with `FFmpegFrameRecorder`, but I don't know how...

**Comment by saudet** [comment]
Any updates? Have you figured out anything for this issue?

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming it works without problems, but please let me know if this isn't the case.
