### ISSUE TITLE
non-strictly-monotonic PTS

### ISSUE THREAD

**Issue by crossmo** [bytedeco/javacv#253]
Hi, I am trying to use JavaCV to create a video from images and a given audio file on both Android and Java SE with the following code

```
public class JavaMovieStreamWriter implements MovieStreamWriter {
	final private FFmpegFrameRecorder recorder;
	final private Java2DFrameConverter frameConverter = new Java2DFrameConverter();

	public JavaMovieStreamWriter(Parameters params) throws Exception {
		this.recorder = new FFmpegFrameRecorder(params.getOutMovieFile(), params.getWidth(), params.getHeight(), params.getChannels());
		recorder.setImageWidth(params.getWidth());
		recorder.setImageHeight(params.getHeight());
		recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
		recorder.setVideoOption("preset", "veryfast");
		recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
		recorder.setAudioChannels(1);
		recorder.setSampleRate(8000);
		recorder.start();
	}


	@Override public long writeAudio(String file) throws Exception {
		FFmpegFrameGrabber audioInput = new FFmpegFrameGrabber(file);
		audioInput.start();
		long audioTimeInLength = audioInput.getLengthInTime();
		Frame audioFrame = null;
		while ((audioFrame = audioInput.grab()) != null) {
			recorder.record(audioFrame);
		}
		audioInput.stop();
		audioInput.release();
		return audioTimeInLength;
	}

	@Override public void writeFrame(long timestamp, Image cover) throws Exception {
		recorder.setTimestamp(timestamp);
		recorder.record(frameConverter.convert(((JavaImage) cover).bufferedImage()));
	}

	@Override public void stop() throws Exception {
		recorder.stop();
	}

	@Override public void close() throws Exception {
		recorder.release();
	}

}
```

The Android code is slightly different with the above in using different FrameConverter there. On JavaSE, 'non-strictly-monotonic PTS' warning was given after encoding every image. On Android, it crashes when encoding uncertain frame with interleaved... 

I am using JavaCV1.0. Do you have any suggestions about that?

Thanks.

**Comment by crossmo** [comment]
I use non-monotonic timestamps for images, may be this is the reason causing the warning, is it?

If it's, what options should I pass to the recorder? I am really a newbie for this.

Thanks

**Comment by crossmo** [comment]
I worked out the reason causing that. The timestamps for two consecutive frames sometimes are too close so that FFmpegFrameRecorder.setTimestamp will result in the same frame number.

**Comment by saudet** [comment]
Right, FFmpeg doesn't support non-monotonic timestamp. You'll need to order your frames properly before recording them.
