### ISSUE TITLE
 Android: Add overlay while recording it

### ISSUE THREAD

**Issue by Iqra786** [bytedeco/javacv#257]
Is there any possibility to *add overlay* on video while recording? 
I knew we can apply filter during recording. I am successfully cropping and  rotating these frames while I am recording through filter that was explained by @saudet  in issue #164. I want to add overlay on the video during recording with filters. I have checked the documentation (https://ffmpeg.org/ffmpeg-filters.html#overlay-1) and it is not very clear. Try to add these filter but it raised exception when I start the filters. (Some time it raised parsing exception or sometime avfilter_graph_config())

I went through few examples but all examples are for command line where it getting input as file and generate new file. (http://www.digitalwhores.net/ffmpeg/ffmpeg-watermark-positions/)

Regards,

**Comment by saudet** [comment]
Sure, what isn't working when using the filters specified on that site with `FFmpegFrameFilter`?

**Comment by Iqra786** [comment]
Thanks @saudet 
In the following line I am adding only overlay. But it raised  avfilter_graph_config(). 

1- filter = new FFmpegFrameFilter("overlay=main_w-overlay_w-10:main_h-overlay_h-10", imageWidth, imageHeight); (Exception avfilter_graph_config());

In the following line I am trying to add image but getting Exception avfilter_graph_parse_ptr();

filter = new FFmpegFrameFilter("ffmpeg -i [in] -i landroid.resource://com.example.filters.myapplication/drawable/images.png -filter_complex 'overlay=10:main_h-overlay_h-10' output", imageWidth, imageHeight); (Exception avfilter_graph_parse_ptr())

I am finding it hard how to apply these different filters in Android using wrapper . Can you explain a little the following command that I have copied from the documentation. what is input and output here and how handle the white spaces in the line. log is file path that is I am getting from android resources,.android.resource://com.example.filters.myapplication/drawable/images.png 

ffmpeg -i input -i logo -filter_complex 'overlay=10:main_h-overlay_h-10' output

if I want to apply above filter how I have to write this filter. I have trying from last three days but not getting anywhere.

Thanks in advance.

**Comment by saudet** [comment]
Native code can't access Java resources. We need to extract them to a
temporary file in something like Context.getCacheDir().

**Comment by Iqra786** [comment]
Thanks @saudet,
In the following line 
- filter = new FFmpegFrameFilter("overlay=main_w-overlay_w-10:main_h-overlay_h-10", imageWidth, imageHeight); (Exception avfilter_graph_config());

I am not accessing any java resources. I am just adding blank overlay but still filter raised Exception avfilter_graph_config()).

**Comment by saudet** [comment]
Can you call `FFmpegLogCallback.set()` during init and let me know what you get in Android's log? Thanks

**Comment by Iqra786** [comment]
Thanks @saudet  here is log.

 Error: Output pad "default" with type video of the filter instance "in" of buffer not connected to any destination
for following filter.
filter = new FFmpegFrameFilter("overlay=main_w-overlay_w-10:main_h-overlay_h-10", imageWidth, imageHeight); (Exception avfilter_graph_config()); thanks

**Comment by saudet** [comment]
I just tried this on the command line:
```
ffmpeg -i test.mp4 -vf "overlay=main_w-overlay_w-10:main_h-overlay_h-10" out.mp4
```
And I get the same kind of error:
```
Simple filtergraph 'overlay=main_w-overlay_w-10:main_h-overlay_h-10' does not have exactly one input and output.
```
So I don't think this is a valid filter command. Please try to use a valid filter command. It should work. If it doesn't, let me know, thanks.

**Comment by Iqra786** [comment]
Thanks @saudet , it does support the overlay during recording.FFmpegLogCallbacl.set() was very helpful. Only issue I am facing When I use these frames after adding overlay in
 YuvImage image = new YuvImage(data, ImageFormat.NV21,320, 320, null); OR
AndroidFrameConverter converterToBitmap = new AndroidFrameConverter(); 
to convert into bitmap. New bitmap mix all the color. But it works fine when I am using Corp and rotate filter. When I add overlay filter color mixing issue start. Could you guide me what I am doing wrong.

**Comment by saudet** [comment]
Maybe there is a bug in FFmpeg with overlay and the NV21 pixel format. What
happens with RGB24?

Samuel

**Comment by y4nnick** [comment]
@Iqra786 Have you manged to add an overlay? Could you please provide a full code example?

**Comment by saudet** [comment]
Marking as duplicate of #887 

Fix included in latest release!

**Comment by saudet** [comment]
Another workaround is given at https://github.com/bytedeco/javacv/issues/232#issuecomment-162601656
