### ISSUE TITLE
javacv/samples/OpticalFlowDense.java uses deprecated getFloatBuffer

### ISSUE THREAD

**Issue by salamanders** [bytedeco/javacv#258]
Unsure what to use instead to read/write directly from/to a org.bytedeco.javacpp.opencv_core.Mat

**Comment by saudet** [comment]
The answer is in the docs:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/helper/opencv_core.AbstractArray.html#getFloatBuffer%28%29
```
See Also:
    createBuffer()
```
Could you send a pull request with the fix? Thanks!

**Comment by salamanders** [comment]
https://github.com/bytedeco/javacv/pull/259

**Comment by saudet** [comment]
Thanks for the pull request! After you've fixed the formatting, I'll merge it in. Thanks!
