### ISSUE TITLE
How can I use JavaCV classifier ?

### ISSUE THREAD

**Issue by Djabx** [bytedeco/javacv#260]
Hi,

I'm building a multi-platform application in java with maven.

If I use directly `opencv` I specify the platform I want with the classifier, like this:

```xml
<dependency>
  <groupId>org.bytedeco.javacpp-presets</groupId>
  <artifactId>opencv</artifactId>
  <version>3.0.0-1.1</version>
  <classifier>linux-x86_64</classifier>
</dependency>
```

But when I do:

```xml
<dependency>
  <groupId>org.bytedeco</groupId>
  <artifactId>javacv</artifactId>
  <version>1.1</version>
</dependency>
```

Only the platform I'm building is linked.
But I would like to build every platform (linux / window / x86 and x86_64) from the same machine.

How can I do something like this with `JavaCV` in my pom ?

**Comment by saudet** [comment]
As mentioned in the `README.md` file, just set the `platform.dependencies` system property to `true`, and you'll get the dependencies for all platforms!
