### ISSUE TITLE
How to put overlay with transparent backgroudn to another image?

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#263]
I am coping a small overlay image to another image, the small overlay is with transparent background, but after merge, i find the overlay background is black. The code is like this:

  opencv_core.cvSetImageROI(bgImage, opencv_core.cvRect(left, top, width, height));
            opencv_core.cvCopy(overlayImage, bgImage);
            opencv_core.cvResetImageROI(bgImage);

So javacv not support PNG?

**Comment by saudet** [comment]
To load the alpha channel of a PNG file, according to OpenCV's documentation, we need to load using a flag < 0:
http://docs.opencv.org/3.0-beta/modules/imgcodecs/doc/reading_and_writing_images.html#imread
If that doesn't work, please report the bug upstream here:
http://code.opencv.org/projects/opencv/issues
Thank you!
