### ISSUE TITLE
android record video using FFmpegFrameRecorder with H.264 type data

### ISSUE THREAD

**Issue by s8871404** [bytedeco/javacv#266]
I'm using FFmpegFrameRecorder to record video, however, the function record(); 
only accept IPlimage which only can format YUV type data,
But I got H.264 type data from MediaCodec.getOutPutBuffer() and I want to record video using H.264 data , how can I do this?

**Comment by saudet** [comment]
We would need to add support for raw packets, something that's already been asked many times, see #93. If you would like to make a contribution, it would be very welcome! Thank you
