### ISSUE TITLE
Proguard issues

### ISSUE THREAD

**Issue by crossmo** [bytedeco/javacv#268]
Hi, I am trying to build an Android project with Proguard and get two issues:

1. Duplicated ../META-INFO/maven/ errors This can be resolved by adding packing options to filter them out. 

2. Lint warning as seen as below
```
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: java.awt.color. Referenced from org.bytedeco.javacv.CanvasFrame.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: java.awt.event. Referenced from org.bytedeco.javacv.CanvasFrame.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: java.awt.image. Referenced from org.bytedeco.javacv.CanvasFrame.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: java.awt. Referenced from org.bytedeco.javacv.CanvasFrame.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: java.beans.beancontext. Referenced from org.bytedeco.javacv.BaseChildSettings.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: javax.imageio. Referenced from org.bytedeco.javacv.IPCameraFrameGrabber.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: javax.media.opengl.awt. Referenced from org.bytedeco.javacv.GLCanvasFrame.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: javax.media.opengl.glu. Referenced from org.bytedeco.javacv.GNImageAlignerCL.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: javax.media.opengl. Referenced from org.bytedeco.javacv.GLCanvasFrame.
../../src/main/libs/javacv-1.0.jar: Invalid package reference in library; not included in Android: javax.swing. Referenced from org.bytedeco.javacv.CanvasFrame.
```
It looks that there is no real affects on our app since they are not used. But It's better organize Android or Desktop related code into specific artifacts.

**Comment by saudet** [comment]
AFAIK, these warnings are not related to ProGuard. Actually, if you were using it, it would remove these classes that you are not using, and shouldn't get those messages.

**Comment by lfdversluis** [comment]
java.awt is not in android, that's why those messages show. Apparently neither is javax and those others shown.

**Comment by saudet** [comment]
@lfdversluis Right, I understand that, but shouldn't ProGuard get us rid of classes we don't use, whatever they may be using or not themselves? Oh, wait a minute, your instructions remove `org.bytedeco.javacv.**` from being considered by ProGuard. I don't think we need that. Just making it ignore `org.bytedeco.javacpp.**` should be enough.

**Comment by lfdversluis** [comment]
@saudet Ignore may work better indeed. May want to test that yup!

**Comment by saudet** [comment]
I'm assuming this isn't an issue anymore, but please let me know if it is! Thanks for the tips @lfdversluis
