### ISSUE TITLE
Pull Maven Dependencies for Linux

### ISSUE THREAD

**Issue by cgeo7** [bytedeco/javacv#270]
I have the following dependency in my pom. Apparently though only the windows-x86 are downloaded, which incidentally is my development environment. However I am running the application in both environments (well mostly on Linux), and I also need those native cpp libraries. Is there any way to fix this?

```
<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>1.1</version>
</dependency>
```

**Comment by saudet** [comment]
Sure, just set the `platform.dependencies` system property to `true` for the build process of your application, and that will bring in all platform dependencies.

**Comment by cgeo7** [comment]
this will bring be dependencies for all platforms, android, macos, arm. How can I exclude them?

**Comment by saudet** [comment]
We can include just the artifacts we want, like for any other dependencies
out there, if that's what you're looking for... so I'm not sure what the
question is, could you clarify?
