### ISSUE TITLE
FFmpegFrameRecorder timed out

### ISSUE THREAD

**Issue by tomerhatav** [bytedeco/javacv#274]
Hello,
Any idea why this error is happening occasionally?

Fatal Exception: java.util.concurrent.TimeoutException: org.bytedeco.javacv.FFmpegFrameRecorder.finalize() timed out after 10 seconds

**Comment by saudet** [comment]
It probably means you forgot to call `stop()` after you no longer need the `FFmpegFrameRecorder`...

**Comment by saudet** [comment]
So, I'm assuming this issue has been resolved, but let us know if this is still happening!
