### ISSUE TITLE
How to get and modify the pixel of Mat in color image

### ISSUE THREAD

**Issue by GPrathap** [bytedeco/javacv#276]
I need to modify each pixel values of given image. Right now I have no idea how to do this. I am thinking about convert Mat or IplImage into  CvMat. 

OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
IplImage loadedImage = loadImage(new File("resources/Lenna.png"));
CvMat img = loadedImage.asCvMat();

But CvMat has been deprecated. I am using javacv 1.1. Can you suggest a way to achieve this?

**Comment by saudet** [comment]
The answer is `createIndexer()`:
http://bytedeco.org/news/2014/12/23/third-release/
Enjoy!

**Comment by GPrathap** [comment]
Thank you so much You save my day :) I would have asked this a little bit earlier. I spent more than 4 hours to figure out what the hell is this.

:+1:
