### ISSUE TITLE
JavaCV-FFmpeg-GIF-codec avcodec_open2() error -22

### ISSUE THREAD

**Issue by zhengxuzeng** [bytedeco/javacv#278]
Hi
I want to use the **GIF codec** of javacv/FFmpeg to run on my Android device.
so,here is what I have done:
1. get javacv/samples/RecordActivity.java , build it on AndroidStudio 1.4.1, Windows 7, and run on my Android mobile phone, output the stream.flv file successfully.
2. It seems that FFmpegFrameRecorder.java does not support GIF codec, So I make **a copy of FFmpegFrameRecorder.java** named **myRecorder.java** on my project,then make some change: 
  - remove all the code about audio.(I don't need it on my GIFs)
  - at method **startUnsafe()**, I added code : 

    ```java
    if (imageWidth > 0 && imageHeight > 0) {
            if (videoCodec != AV_CODEC_ID_NONE) {
            {
                //copy of FFmpegFrameRecorder.java, other format names...
            } else if ("gif".equals(format_name)){
                oformat.video_codec(AV_CODEC_ID_GIF);
            }   
    //...
    if (pixelFormat != AV_PIX_FMT_NONE) {
      video_c.pix_fmt(pixelFormat);
    } //copy of else if...
    else if(video_c.codec_id() == AV_CODEC_ID_GIF){ // branch I added.
      video_c.pix_fmt(AV_PIX_FMT_RGB32);//I guess the format from GIF-89a specification, also I try other fomat like AV_PIX_FMT_YUV420P etc, but they lead to the same result.
    } else {
      video_c.pix_fmt(AV_PIX_FMT_YUV420P); // lossy, but works with about everything
    }
    ```

3.Finally, I run the app on my Android mobile phone, by **myRecorder.java**, my app output the **stream.flv without sound successfully** ,then I change the format from "flv" to "gif", and the filename from "/mnt/sdcard/stream.flv" to "/mnt/sdcard/stream.gif",however, **it doesn't work**:
  ```
  W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
  ```

**Is there anything wrong with my program?**
**Hope you can help me.Thanks a lot.**

Tips: 
- I'm sure that FFmpeg supports GIF encoder:
```
ffmpeg -codecs
Codecs:
 D..... = Decoding supported
 .E.... = Encoding supported
 ..V... = Video codec
 ..A... = Audio codec
 ..S... = Subtitle codec
 ...I.. = Intra frame-only codec
 ....L. = Lossy compression
 .....S = Lossless compression
//hide other codecs...
DEV..S gif                  GIF (Graphics Interchange Format)
```

- I try to open the GIF decoder on my program, and it works:

```java
public void debug(){
        int ret;
        avcodec_register_all();
        AVCodec codec = avcodec_find_decoder(AV_CODEC_ID_GIF);
        if(codec == null){
            Log.i(LOG_TAG,"can't find codec.");
        }
        AVCodecContext context = avcodec_alloc_context3(codec);
        if(context == null){
            Log.i(LOG_TAG,"alloc context failed.");
        }
        if ((ret = avcodec_open2(context, codec, (AVDictionary)null)) < 0){
            Log.i(LOG_TAG,"avcodec_open2() failed. open state is: "+ret);
        } else {
            Log.i(LOG_TAG,"GIF decoder avcodec_open2() successfully.");
        }
    }
```

**Comment by saudet** [comment]
Try to call FFmpegLogCallback.set() and see if anything interesting shows
up in the log, thanks!

**Comment by zhengxuzeng** [comment]
How to use FFmpegLogCallback.set()?
I call the it at **startUnsafe()**, but there is too much log,I can't find the log. Does the log have any tag?

**Comment by saudet** [comment]
Great!! Enjoy :)
