### ISSUE TITLE
NPE in BackgroundSubtractorMOG2

### ISSUE THREAD

**Issue by moea** [bytedeco/javacv#279]
Calling any method on `org.bytedeco.javacpp.opencv_video.BackgroundSubtractorMOG2` (instantiated with the zero-arg constructor) results in (in this example I'm calling getDetectShadows - same w/ apply, etc.):

```java
17:47:58.205 [ERROR] [system.err] Exception in thread "main" java.lang.NullPointerException: This pointer address is NULL.
17:47:58.205 [ERROR] [system.err]       at org.bytedeco.javacpp.opencv_video$BackgroundSubtractorMOG2.getDetectShadows(Native Method)
```

This is with version 1.1 on Linux, against javacv-presets:opencv 3.0.0-1.1, using converted frames from `FFmpegFrameGrabber` - not that I think things are getting that far.  I can't find a public repository or sample which is using this version of the API - how should I be constructing this object?  Same issue with the KNN subtractor, FWIW.

**Comment by saudet** [comment]
`BackgroundSubtractorMOG2` doesn't have a default constructor. Try the `createBackgroundSubtractorMOG2()` factory method instead.
