### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path

### ISSUE THREAD

**Issue by NSF1** [bytedeco/javacv#282]
Running Ubuntu 14.04, NetBeans 8.0.2, under Maven, with 64 bit machine and am getting the below error, while attempting :

FrameGrabber grabber = new FFmpegFrameGrabber(p.getFilename());

java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886) at java.lang.Runtime.loadLibrary0(Runtime.java:849) at java.lang.System.loadLibrary(System.java:1088)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535) at org.bytedeco.javacpp.Loader.load(Loader.java:410)
>
>                  at org.bytedeco.javacpp.Loader.load(Loader.java:353)
>
>                  at 
> org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
>
>                  at java.lang.Class.forName0(Native Method)
>
>                  at java.lang.Class.forName(Class.java:270)
>
>                  at org.bytedeco.javacpp.Loader.load(Loader.java:385)
>
>                  at org.bytedeco.javacpp.Loader.load(Loader.java:353)
>
>                  at 
> org.bytedeco.javacpp.avcodec.<clinit>(avcodec.java:12)
>
>                  at
> org.bytedeco.javacv.FFmpegFrameGrabber.<clinit>(FFmpegFrameGrabber.jav
> a:103)
>
>                  at
> com.thefriedlandgroup.jvd.PicModService.onReceive(PicModService.java:8
> 6)
>
>                  at
> akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.sc
> ala:167)
>
>                  at 
> akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
>
>                  at akka.actor.ActorCell.invoke(ActorCell.scala:456)
>
>                  at 
> akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
>
>                  at akka.dispatch.Mailbox.run(Mailbox.scala:219)
>
>                  at
> akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abstr
> actDispatcher.scala:385)
>
>                  at
> scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>
>                  at
> scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.
> java:1339)
>
>                  at
> scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:197
> 9)
>
>                  at
> scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThrea
> d.java:107)
>
> Caused by: java.lang.UnsatisfiedLinkError:
> /tmp/javacpp861473060694300/libjniavutil.so: libavutil.so.54: cannot 
> open shared object file: No such file or directory
>
> The Maven file includes these dependencies:
>
>          <dependency>
>
>              <groupId>org.bytedeco</groupId>
>
>              <artifactId>javacv</artifactId>
>
>              <version>1.1</version>
>
>          </dependency>
>
>          <dependency>
>
>              <groupId>org.bytedeco.javacpp-presets</groupId>
>
>              <artifactId>ffmpeg</artifactId>
>
>              <version>2.8.1-1.1</version>
>
>              <classifier>linux-x86_64</classifier>
>
>          </dependency>
>
> I have seen similar issues here:
>
> https://github.com/bytedeco/javacpp-presets/issues/22
>
> But have not found any solutions yet.
>
> Can you please shoot me a pointer?
>

**Comment by saudet** [comment]
Could you check if libavutil.so.54 can be found in that tmp directory or not? If it's not there, then we'll need to figure out why it's not there.

**Comment by NSF1** [comment]
That directory is not there...
I did not run a manual cpp install, rather used Maven to import the necessary files, so perhaps I am missing a step here...

**Comment by saudet** [comment]
It's only a temporary directory. It gets deleted once your Java application exits, so make sure you do not exit from your Java applications before checking the directory.

**Comment by NSF1** [comment]
OK, I launched the program and checked the /tmp directory for any cpp sub dirs created today, and found none.

**Comment by saudet** [comment]
Well, that's a problem. Could you try to run the small samples found in the README.md file from JavaCPP on the command line and see if those works? Thanks

**Comment by NSF1** [comment]
OK, ran the framegrabber example and that works and creates the cpp dir.

**Comment by saudet** [comment]
So, you've resolved your problem? Everything is fine?

**Comment by NSF1** [comment]
No, it works on the small case, but not on the app. What triggers the /tmp file creation?

**Comment by saudet** [comment]
Have you tried to just use the same exact `pom.xml` file that works instead of creating your own?

**Comment by NSF1** [comment]
will take a look

**Comment by salamanders** [comment]
I was able to repro this when I was missing:

    
    <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>javacv-platform</artifactId>
        <version>1.4.3</version>
    </dependency>
