### ISSUE TITLE
BackgroundSubtractorMOG2 usage

### ISSUE THREAD

**Issue by Connor-F** [bytedeco/javacv#283]
I'm trying to check for movement in a series of frames grabbed from my web cam. I'm using `OpenCVFrameGrabber` to get each frame and I'm then converting them to a `Mat` to be used with the `BackgroundSubtractorMOG2` `apply(Mat m1, Mat m2)` function.

The problem is I don't understand how to actually use the `apply` function to see if any movement was detected. I've read the documentation but it didn't help. Any advice?

Currently I'm passing `apply` the current frame (as a `Mat`) and another empty `Mat` for the "mask". I'm not sure what the "mask" is doing here.

Very basic code:

        OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(0);
        grabber.start();
        OpenCVFrameConverter.ToMat toMat = new OpenCVFrameConverter.ToMat();
        opencv_core.Mat prevMat = new opencv_core.Mat();
        opencv_core.Mat currentMat = convertToMat.convert(grabber.grab());

        opencv_core.Mat maskMat = new opencv_core.Mat();

        opencv_video.BackgroundSubtractorMOG2 subtractor = new opencv_video.BackgroundSubtractorMOG2();
        
        CanvasFrame canvas = new CanvasFrame("oo");
        while(true)
        {
            prevMat = currentMat;
            currentMat = toMat.convert(webcamGrabber.grab());

            subtractor.apply(prevMat, maskMat);
            subtractor.getBackgroundImage(maskMat);

            Frame converted = toMat.convert(maskMat);
            canvas.showImage(converted);
        }

Running this gives me the exception: Exception in thread "main" java.lang.NullPointerException: This pointer address is NULL.
	at org.bytedeco.javacpp.opencv_video$BackgroundSubtractor.apply(Native Method)

**Comment by saudet** [comment]
Please ask on the mailing list of OpenCV, thanks.

**Comment by saudet** [comment]
`BackgroundSubtractorMOG2` doesn't have a default constructor. Try to call `createBackgroundSubtractorMOG2()` instead.
