### ISSUE TITLE
Can I merge two videos and put overlay.

### ISSUE THREAD

**Issue by Iqra786** [bytedeco/javacv#286]
Is any way to merge two videos and put water mark overlay without command line.

**Comment by saudet** [comment]
Sure, use FFmpegFrameFilter.

**Comment by Iqra786** [comment]
@saudet  So I don't need FrameRecorder. 
can I  achieve with following and it will create out put for me.
filter = new FFmpegFrameFilter(applyFilter, imageWidth, imageHeight);
filter.setPixelFormat(avutil.AV_PIX_FMT_NV21);
filter.start();

**Comment by saudet** [comment]
We also need FrameRecorder for output of course.

**Comment by Iqra786** [comment]
Thanks. How can I decode input stream to frames. The files are stored on the disk.

**Comment by saudet** [comment]
Using FFmpegFrameGrabber, check the Demo class in the README.md file for an example. Or does that not work?

**Comment by Iqra786** [comment]
@saudet , Can I set three inputs in one FrameGrabber That run after one first complete. There is a method called createArray (of FrameGrabber) but it runs only first one.

**Comment by saudet** [comment]
The array thing in FrameGrabber is to grab frames simultaneously. If you want to simply string them, what is the issue with just doing it normally by starting one FrameGrabber after the other?

**Comment by Iqra786** [comment]
Thanks, There is no issue. Only looking for efficient way to merge videos with water mark. I thought it works like  MediaPlayer.SetNextMediaPlayer where next one starts automatically.

**Comment by saudet** [comment]
Sure, we could add a `setNextFrameGrabber()` method or something. If you make the necessary modifications, please send a PR! Thanks :)
