### ISSUE TITLE
Class java.lang.AutoCloseable not found - continuing with a stub

### ISSUE THREAD

**Issue by stianSjoli** [bytedeco/javacv#288]
I am trying to test the sample usage smoother with Scala, and with the following code:

import org.bytedeco.javacpp.opencv_core._
import org.bytedeco.javacpp.opencv_imgproc._
import org.bytedeco.javacpp.opencv_imgcodecs._

object Face{

	def main(args: Array[String]){
		val image = cvLoadImage("test.jpg")
		if(image == null){ 
			println("hello")
		}
	}

}
I get this error: Class java.lang.AutoCloseable not found - continuing with a stub. Why is that?

**Comment by saudet** [comment]
That class comes with Java SE 7, so to fix this error, please upgrade the version of your JDK to 7 or 8.
