### ISSUE TITLE
FFMPEG record to inputstream or  outputstream

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#290]
Hi all, 
I have an external library that takes  an  InputStream as Argument. You Are supposed  to write pcm 16 bit Packets in there. I was wondering if the FFmpegFramegrabber  also transcodes  the streams and if/how I can Utililize javacv to achieve that task. The base task is to take an rtmp stream,extract and transcode the audio and pass it to the library. Can we use the Grab Samples function for that? I have been  using xuggler  but since  it is outdated I wanted to update to javacv

Any Help would be much  appreciated

**Comment by saudet** [comment]
Sure, it's a feature that's been asked by a lot of other people for a while now. See #95. If you would like to make a contribution, it would be very much appreciated! Let me know, thank you.
