### ISSUE TITLE
Can't create longer video from images than 2 min 30 sec.

### ISSUE THREAD

**Issue by mastep20** [bytedeco/javacv#294]
Hi! I want to create video from images and merge this video with audio file using javacv. Finally, I've done this. But I have a little problem. 
Below I added my code:

    package com.example.mateusz.javacv1;

    import android.app.Activity;
    import android.app.ProgressDialog;
    import android.content.Context;
    import android.graphics.Bitmap;
    import android.graphics.BitmapFactory;
    import android.os.AsyncTask;
    import android.os.Environment;
    import android.util.Log;
    import android.widget.ImageView;
    import android.widget.Toast;

    import org.bytedeco.javacpp.avcodec;
    import org.bytedeco.javacpp.opencv_core;
    import org.bytedeco.javacv.FFmpegFrameGrabber;
    import org.bytedeco.javacv.FFmpegFrameRecorder;
    import org.bytedeco.javacv.Frame;
    import org.bytedeco.javacv.FrameGrabber;
    import org.bytedeco.javacv.FrameRecorder;
    import org.bytedeco.javacv.OpenCVFrameConverter;
    
    import java.io.File;
    import java.io.IOException;
    
    import static org.bytedeco.javacpp.opencv_imgcodecs.cvLoadImage;
    
    public class MovieCreator extends AsyncTask<String, Integer, String> {
        private ProgressDialog progressDialog;
        private Context context;

    public MovieCreator(Context context) {
        this.context = context;
    }

    protected void onPreExecute() {
        progressDialog = new ProgressDialog(context);
        progressDialog.setTitle("Processing...");
        //progressDialog.setMessage("Please wait.");
        progressDialog.setCancelable(false);
        progressDialog.setIndeterminate(true);
        progressDialog.show();
    }

    protected String doInBackground(String... params) {
        return createMovie();
    }

    protected void onProgressUpdate(Integer... progress) {
        progressDialog.setMessage("Dotychczasowy postęp: " + progress[0] + "%");
    }

    protected void onPostExecute(String result) {
        if(result != null) {
            ImageView mImage = (ImageView)
                    ((Activity) context).findViewById(R.id.imageView);
            File folder = Environment
                    .getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM);
            String path = folder.getAbsolutePath();
            Bitmap bmp = BitmapFactory.decodeFile(path + "/Camera/image1.jpg");
            mImage.setImageBitmap(bmp);
            if (progressDialog != null) {
                progressDialog.dismiss();
            }
        }
        else {
            Toast.makeText(context,"Nie można utworzyć filmu.", Toast.LENGTH_LONG).show();
        }

    }

    private String createMovie() {

        File folder = Environment
                .getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM);
        String path = folder.getAbsolutePath();
        String videoFilePath = path + "/movie6.mp4";
        String audioFilePath = path + "/music.mp3";
        String finalVideoPath = path + "/film.mp4";

        //File file_folder = new File(path + "/Camera");
        //File[] files = file_folder.listFiles();

        try {

            FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(videoFilePath, 1280, 720);
            OpenCVFrameConverter converter = new OpenCVFrameConverter() {
                @Override
                public Frame convert(Object o) {
                    return null;
                }

                @Override
                public Object convert(Frame frame) {
                    return null;
                }
            };

            //recorder.setAudioCodec(avcodec.AV_CODEC_ID_AMR_NB);
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);

            recorder.setVideoBitrate(10 * 1024 * 1024);
            recorder.setFrameRate(1);
            recorder.setVideoQuality(0);
            //recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
            recorder.setFormat("mp4");

            recorder.start();
            publishProgress(0);
            int time = 25;
            int number_images = 3;
            for (int i = 0; i < number_images; i++) {
                for (int j = 0; j < time; j++) {
                    opencv_core.IplImage image = cvLoadImage(path + "/Camera/image" + i + ".jpg");
                    Frame frame = converter.convert(image);
                    recorder.record(frame);
                    publishProgress(25*(i+1));
                }
            }

            recorder.stop();
            publishProgress(76);
            mergeAudioAndVideo(videoFilePath, audioFilePath, finalVideoPath);
            publishProgress(100);

        } catch (Exception e) {
            Log.e("problem", "problem", e);
        }
        return /*videoFilePath;*/finalVideoPath;
    }

    private boolean mergeAudioAndVideo(String videoPath, String audioPath, String outPut)
            throws Exception {
        boolean isCreated = true;
        File file = new File(videoPath);
        if (!file.exists()) {
            return false;
        }
        try {
            FrameGrabber grabber1 = new FFmpegFrameGrabber(videoPath);
            FrameGrabber grabber2 = new FFmpegFrameGrabber(audioPath);

            grabber1.start();
            grabber2.start();

            //Log.e("WIDTH",grabber2.getSampleRate()+"");

            FrameRecorder recorder = new FFmpegFrameRecorder(outPut,
                    grabber1.getImageWidth(), grabber1.getImageHeight(),
                    grabber2.getAudioChannels());

            recorder.setFormat("mp4");
            recorder.setFrameRate(grabber1.getFrameRate());
            //recorder.setSampleFormat(grabber2.getSampleFormat());
            recorder.setSampleRate(grabber2.getSampleRate());
            //recorder.setAudioCodec(avcodec.AV_CODEC_ID_MP3);
            //recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
            recorder.start();

            Frame frame1, frame2 = null;

            while ((frame1 = grabber1.grabFrame()) != null ||
                    (frame2 = grabber2.grabFrame()) != null) {

                recorder.record(frame1);
                recorder.record(frame2);

            }

            recorder.stop();
            grabber1.stop();
            grabber2.stop();

            //Log.e(LOG_TAG, "recorder initialize success");

        } catch (Exception e) {
            e.printStackTrace();
        }

        return isCreated;

    }

    }

In method <i>createMovie()</i> I create movie from 3 images and then I merge this video with audio by <i>mergeAudioAndVideo</i>. Everything is fine but when I set <i>time</i> > 50, for example:

    int time = 100;

the video movie6.mp4 doesn't create in full. The app crashes.
After many failures I've come to the conlusion that app crashes when
number_images * time > 150 . If number_images * time = 150 and FrameRate = 1 than duration of movie6.mp4 is 2 min 30 sec and I want to create longer movies. How to fix it?

Generally I just want to display every image the same amount of time in video. For example, my audio file duration is 4 minutes and I want to create video from 10 images so every image must be displayed for 24 seconds. Is that any way to set image duration in video?

**Comment by saudet** [comment]
Sure, call `setTimestamp()` to indicate the number of microseconds in the stream when the next frame starts. The previous frame will show for the duration until that time.

**Comment by zainriaz** [comment]
I want to create video from images and marge audio with video  i used the code of #mastep20 but no success can any one help me
