### ISSUE TITLE
The setTimestamp() in FFmpegFrameRecorder doesn't work properly.

### ISSUE THREAD

**Issue by mastep20** [bytedeco/javacv#295]
Hello. I have a little problem with my app. When I try to set image duration (50 sec) in my video by calling setTimestamp() method in my FFmpegFrameRecorder, my app doesn't work and I get following error:

    12-29 17:16:51.628 17504-17599/com.example.mateusz.javacv1 E/problem: problem
                                                             org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -1: Could not encode video packet.
                                                                 at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:774)
                                                                 at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:686)
                                                                 at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:679)
                                                                 at com.example.mateusz.javacv1.MovieCreator.createMovie(MovieCreator.java:122)
                                                                 at com.example.mateusz.javacv1.MovieCreator.doInBackground(MovieCreator.java:46)
                                                                 at com.example.mateusz.javacv1.MovieCreator.doInBackground(MovieCreator.java:28)
                                                                 at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                 at java.lang.Thread.run(Thread.java:841)

I try looking in the internet how to resolve this problem but I couldn't find something useful. Below I paste method which create video:

    private String createMovie() {

        File folder = Environment
                .getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM);
        String path = folder.getAbsolutePath();
        String videoFilePath = path + "/movie6.mp4";
        String audioFilePath = path + "/music.mp3";
        String finalVideoPath = path + "/film.mp4";

        //File file_folder = new File(path + "/Camera");
        //File[] files = file_folder.listFiles();

        try {

            FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(videoFilePath, 1280, 720);
            OpenCVFrameConverter converter = new OpenCVFrameConverter() {
                @Override
                public Frame convert(Object o) {
                    return null;
                }

                @Override
                public Object convert(Frame frame) {
                    return null;
                }
            };

            //recorder.setAudioCodec(avcodec.AV_CODEC_ID_AMR_NB);
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);

            recorder.setVideoBitrate(10 * 1024 * 1024);
            recorder.setFrameRate(1);
            recorder.setVideoQuality(0);
            //recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
            recorder.setFormat("mp4");

            recorder.start();
            publishProgress(0);
            int number_images = 3;
            long time = 50000000;
            for (int i = 0; i < number_images; i++) {
                opencv_core.IplImage image = cvLoadImage(path + "/Camera/image" + i + ".jpg");
                Frame frame = converter.convert(image);
                recorder.setTimestamp(time);
                recorder.record(frame);
                publishProgress(25*(i+1));
            }

            recorder.stop();
            publishProgress(76);
            mergeAudioAndVideo(videoFilePath, audioFilePath, finalVideoPath);
            publishProgress(100);

        } catch (Exception e) {
            Log.e("problem", "problem", e);
        }
        return /*videoFilePath;*/finalVideoPath;
    }

    private boolean mergeAudioAndVideo(String videoPath, String audioPath, String outPut)
            throws Exception {
        boolean isCreated = true;
        File file = new File(videoPath);
        if (!file.exists()) {
            return false;
        }
        try {
            FrameGrabber grabber1 = new FFmpegFrameGrabber(videoPath);
            FrameGrabber grabber2 = new FFmpegFrameGrabber(audioPath);

            grabber1.start();
            grabber2.start();

            //Log.e("WIDTH",grabber2.getSampleRate()+"");

            FrameRecorder recorder = new FFmpegFrameRecorder(outPut,
                    grabber1.getImageWidth(), grabber1.getImageHeight(),
                    grabber2.getAudioChannels());

            recorder.setFormat("mp4");
            recorder.setFrameRate(grabber1.getFrameRate());
            //recorder.setSampleFormat(grabber2.getSampleFormat());
            recorder.setSampleRate(grabber2.getSampleRate());
            //recorder.setAudioCodec(avcodec.AV_CODEC_ID_MP3);
            //recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
            recorder.start();

            Frame frame1, frame2 = null;

            while ((frame1 = grabber1.grabFrame()) != null ||
                    (frame2 = grabber2.grabFrame()) != null) {

                recorder.record(frame1);
                recorder.record(frame2);

            }

            recorder.stop();
            grabber1.stop();
            grabber2.stop();

            //Log.e(LOG_TAG, "recorder initialize success");

        } catch (Exception e) {
            e.printStackTrace();
        }

        return isCreated;

    }

I don't know what am I doing wrong. To build app I use Android Studio 1.5.1 and JavaCV 1.1 . My app I test on Xperia T3. Please, help.

**Comment by saudet** [comment]
The timestamp has to be monotically increasing by at least 1/frame_rate
between two frames. Print out the values to make sure.

**Comment by mastep20** [comment]
Sorry, but I'm new in programming in JAVA. What do you mean by timestamp has to be monotically increasing by at least 1/frame_rate between two frames? You mean something like that:

    try {
                    long t = 1000 * (System.currentTimeMillis() - startTime);
                    if (t > recorder.getTimestamp()) {
                        recorder.setTimestamp(t);
                    }
                    recorder.record(yuvIplimage);
                } catch (FFmpegFrameRecorder.Exception e) {
                    Log.v(LOG_TAG,e.getMessage());
                    e.printStackTrace();
                }

**Comment by saudet** [comment]
Yes, that code checks for that with getTimestamp(), which gets increased to
the next minimum value most formats support after recording a frame.

**Comment by mastep20** [comment]
Ok. Now my video is creating with any errors. But duration of each image in video is wrong. First two images display for few seconds and third image display to the end of video. This is my code:

    private String createMovie() {

        File folder = Environment
                .getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM);
        String path = folder.getAbsolutePath();
        String videoFilePath = path + "/movie6.mp4";
        String audioFilePath = path + "/music.mp3";
        String finalVideoPath = path + "/film.mp4";

        //File file_folder = new File(path + "/Camera");
        //File[] files = file_folder.listFiles();

        try {

            FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(videoFilePath, 1280, 720);
            OpenCVFrameConverter converter = new OpenCVFrameConverter() {
                @Override
                public Frame convert(Object o) {
                    return null;
                }

                @Override
                public Object convert(Frame frame) {
                    return null;
                }
            };

            //recorder.setAudioCodec(avcodec.AV_CODEC_ID_AMR_NB);
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);

            recorder.setVideoBitrate(10 * 1024 * 1024);
            recorder.setFrameRate(1);
            recorder.setVideoQuality(0);
            //recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
            recorder.setFormat("mp4");

            recorder.start();
            publishProgress(0);
            //int time = 25;
            int number_images = 3;
            long imageTime = 50000000;
            long startTime = System.currentTimeMillis();
            for (int i = 0; i < number_images; i++) {
                opencv_core.IplImage image = cvLoadImage(path + "/Camera/image" + i + ".jpg");
                Frame frame = converter.convert(image);
                try {
                    long time = System.currentTimeMillis() - startTime + imageTime;
                    if (time > recorder.getTimestamp()) {
                        recorder.setTimestamp(time);
                    }
                    recorder.record(frame);
                } catch (FFmpegFrameRecorder.Exception e) {
                    //Log.v(LOG_TAG,e.getMessage());
                    e.printStackTrace();
                }
                publishProgress(25*(i+1));
            }

            recorder.stop();
            publishProgress(76);
            mergeAudioAndVideo(videoFilePath, audioFilePath, finalVideoPath);
            publishProgress(100);

        } catch (Exception e) {
            Log.e("problem", "problem", e);
        }
        return finalVideoPath;
    } 

I don't know where is a problem in that code. I just need to display every image for 50 seconds (imageTime = 50000000 ms).

**Comment by mastep20** [comment]
I have tried to modify a little my code. Below I past changed fragment of my code:

            recorder.start();
            publishProgress(0);
            //int time = 25;
            int number_images = 3;
            long imageTime = 50000000;
            for (int i = 0; i < number_images; i++) {
                opencv_core.IplImage image = cvLoadImage(path + "/Camera/image" + i + ".jpg");
                Frame frame = converter.convert(image);
                try {
                    long time = (i+1) * imageTime;
                    if (time > recorder.getTimestamp()) {
                        recorder.setTimestamp(time);
                        recorder.record(frame);
                        publishProgress(25*(i+1));
                    }
                    //recorder.record(frame);
                } catch (FFmpegFrameRecorder.Exception e) {
                    //Log.v(LOG_TAG,e.getMessage());
                    e.printStackTrace();
                }
            }

As a result of this code I get film.mp4 which has 2:48 instead 2:30. First and second images display for 66 seconds instead 50 seconds and third image display to the end of video. Besides created video doesn't play correctly on my device only on computer. What am I doing wrong?

**Comment by saudet** [comment]
Try a different format that might support that better. 1 FPS isn't commonly
used by video files.

**Comment by mastep20** [comment]
Do you know what is the best format and video codec to using in video setTimestamp() ? I've tried different combinations but nothing works properly. In my <i>movie6</i> every image always display ok exept the last one. Last image display only 1 second. I don't know where is wrong in my code. I call setTimestamp() also for last image so it should display for 50 seconds. But it doesn't.

**Comment by saudet** [comment]
I don't have a lot of experience with that, but mkv tends to be an overall
better format than mp4...

**Comment by mastep20** [comment]
Hi, again. I've tried with mkv format but still in my <i>movie6.mkv</i> only last image display only 1 second, not as it should. It seems like <i>setTimestamp</i> doesn't works for last image. Is there any way to fix it?

**Comment by saudet** [comment]
Maybe try to record the last image twice?
