### ISSUE TITLE
IPCameraFrameGrabber.stop doesn't check for null so restart null pointers

### ISSUE THREAD

**Issue by JLLeitschuh** [bytedeco/javacv#299]
https://github.com/bytedeco/javacv/blob/cc420a8d7b88006ed52f314c55f87f0e84227e1f/src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java#L99

All of the other frame grabbers ensure that calling stop while fields are null won't cause a null pointer exception.
This class should do the same.

**Comment by saudet** [comment]
Sure, could you send that over as a pull request so I can merge this in? Thanks!!
