### ISSUE TITLE
`FrameGrabber.createDefault()` returns null?

### ISSUE THREAD

**Issue by Nackloose** [bytedeco/javacv#30]
I have updated my code.
It now reads:

```

        // Preload the opencv_objdetect module to work around a known bug.
        Loader.load(opencv_objdetect.class);
        Loader.load(swresample.class); // We can "cast" Pointer objects by instantiating a new object of the desired class.
        CvHaarClassifierCascade classifier = new CvHaarClassifierCascade(cvLoad(classifierName));
        if (classifier.isNull()) {
            System.err.println("Error loading classifier file \"" + classifierName + "\".");
            System.exit(1);
        }

        // The available FrameGrabber classes include OpenCVFrameGrabber (opencv_highgui),
        // DC1394FrameGrabber, FlyCaptureFrameGrabber, OpenKinectFrameGrabber,
        // PS3EyeFrameGrabber, VideoInputFrameGrabber, and FFmpegFrameGrabber.
        FrameGrabber grabber = FFmpegFrameGrabber.createDefault(0);
        grabber.start();
```

But .createDefault() is appearing to always return null now without throwing any form of error.
Which to my understanding shouldn't be happeneing based on the code in 

```
 public static FrameGrabber create(Class<? extends FrameGrabber> c, Class p, Object o)
```

My error being:

```
Exception in thread "main" java.lang.NullPointerException
    at com.nackloose.util.robot.JavaCVDemo.main(JavaCVDemo.java:38)
Java Result: 1
```

Line 38 being: grabber.start();
EDIT:
If you'd like more info I can attempt to run it from source as a project.

**Comment by Nitinvermaa1** [comment]
Hi,
I come across below error when i am trying to access OEM device (EasyCap) to grab frame form Set top box
Code:
FFmpegFrameGrabber grabber =new FFmpegFrameGrabber("video=\"OEM Device\":audio=\"OEM Device\"");

    grabber.setFormat("dshow");
    grabber.setImageWidth(640);
    grabber.setImageHeight(480);
    grabber.start();

    CanvasFrame frame = new CanvasFrame("Screen Capture");
    while (frame.isVisible()) {
        frame.showImage(grabber.grab());
    }
    frame.dispose();
    grabber.stop();
Error:
Exception in thread "main" org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "video="OEM Device":audio="OEM Device"". (Has setFormat() been called?)
at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:429)
at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:377)
at stbTesting.FFmpegEasyCap.main(FFmpegEasyCap.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
[dshow @ 000000000050c760] Could not find video device with name ["OEM Device"] among source devices of type video.
[dshow @ 000000000050c760] Could not find video device with name ["OEM Device"] among source devices of type video.

Please help me out to resolve the above issue
From command line using ffmpeg i am able to play as well as record the Set top box video using easycap

For Direct Play:

ffplay -f dshow -crossbar_video_input_pin_number 1 -crossbar_audio_input_pin_number 2 -rtbufsize 500000k -framerate 29.97 -i video="OEM Device":audio="OEM Device"

For Recording:

ffmpeg -f dshow -crossbar_video_input_pin_number 1 -crossbar_audio_input_pin_number 2 -rtbufsize 500000k -framerate 29.97 -i video="OEM Device":audio="OEM Device" C:\stbtestVideo\Test.avi
