### ISSUE TITLE
Video open/start problem

### ISSUE THREAD

**Issue by marjanSterjev** [bytedeco/javacv#302]
The following code works just fine with JavaCV 0.11 (OpenCV 2.4.11):
```java
OpenCVFrameGrabber grabber=OpenCVFrameGrabber.createDefault(new File("D:/Video.MOV"));
grabber.start();
```
However it fails with JavaCV 1.1 (1.0 also) (OpenCV 3.0).

With JavaCV 1.1 VideoCapture does not open too.

Operating system is Windows 8.1 Pro, 64 bit.

In the same time, the "native" OpenCV 3 Java code works well:
```java
VideoCapture videoCapture=new VideoCapture("D:/Video.MOV");
Mat image=new Mat();
videoCapture.read(image);
Imgcodecs.imwrite("image.png", image);
videoCapture.release();
```
Any idea what is going on?

**Comment by saudet** [comment]
Just use `FFmpegFrameGrabber` instead of `OpenCVFrameGrabber`. It's more portable that way anyway. Let me know if you have any issues with `FFmpegFrameGrabber`, thanks!
