### ISSUE TITLE
HLS No trailing CRLF found in HTTP Header

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#304]
Hi Im trying to transcoder a m3u8 hls stream with FFMPegFrameGrabber and FFmpegFrame Recorder. But I get the error:
```
[http @ 0x7f8304487200] No trailing CRLF found in HTTP header
```
every few seconds and the transcoding doesn work.
However when I do the same thing directly in FFmpeg it works flawlessly.
Any Ideas how that can be fixed?

Im using ubuntu 14

**Comment by saudet** [comment]
Could you provide the code you wrote for that? Thanks

**Comment by The-Crocop** [comment]
Code is super basic:
grabber = new FFmpegFrameGrabber("http://url/of/hlsstream/playlist.m3u8");
grabber.start();
int width = grabber.getImageWidth()))
int height =grabber.getImageHeight()))
recorder = FFmpegFrameRecorder.createDefault("rtmp://my/transcodinng/target/url",width,height)
recorder.setFormat("flv")
recorder.setAudioCodec(grabber.getAudioCodec());//is libaac in this case
recorder.setVideoCodec(grabber.getVideoCodec())// libx264
recorder.start();
Frame capturedFrame= null;
while( (capturedFrame = grabber.grabFrame(audio,video, true, false)) != null && keepRunning){	
				recorder.record(capturedFrame);
			}
recorder.stop();
grabber.stop();

**Comment by saudet** [comment]
Does this also happen without `FFmpegFrameRecorder`?

**Comment by The-Crocop** [comment]
Maybe its important to mention that Im using the 1.1 Version
sorry for the late answer. Had a lot going on. 
I just tested it. Same thing when only grabbing.

maybe related to this:
https://trac.ffmpeg.org/ticket/3268
http://thread.gmane.org/gmane.comp.video.ffmpeg.devel/189500 
https://gist.github.com/caorong/11fff22f7fd279c59a9d

**Comment by saudet** [comment]
Looks like that fix is in FFmpeg 2.8.4, so yeah you should try to build JavaCV 1.2-SNAPSHOT from the latest sources and try it out.

**Comment by The-Crocop** [comment]
hmmm didnt help. I built the new snapshot 
and Im still getting that error

**Comment by saudet** [comment]
Would you have some data that I could try out here?

**Comment by The-Crocop** [comment]
Hi samuel I have send you an  email with a test link

**Comment by saudet** [comment]
I'm running ffplay on your link, and I am getting
```
[http @ 0x7f55a80143c0] No trailing CRLF found in HTTP header.
```
messages every few seconds, so it doesn't look like there is anything wrong with JavaCV. You'll need to report that upstream I'm afraid.

**Comment by The-Crocop** [comment]
OK thank you alot for the support :). I will try to do that.

**Comment by saudet** [comment]
If you've reported this upstream, please provide a link here for reference! Thanks

**Comment by AndCycle** [comment]
https://trac.ffmpeg.org/ticket/3268

this issue is aged and nobody wanna take care of it.
