### ISSUE TITLE
Avio open error trying to stream to azure rtmp channel

### ISSUE THREAD

**Issue by antoniogiordano** [bytedeco/javacv#305]
Hi everybody,

i'm trying to stream to an Azure Media Services Channel, i set up my FFmpegFrameRecorder in this way:
```java
        recorder = new FFmpegFrameRecorder(rtmpURI, w, h);
        // H264
        recorder.setVideoCodec(28);
        recorder.setFormat("mp4");
        recorder.setFrameRate(frameRate); // 30
        // frameRate * 2; Azure needs GOP or key frame interval of 2 seconds
        recorder.setVideoOption("keyint_min", "60");
        recorder.start();
```
But i receive the following error:

avio_open error() error -5: Could not open 'rtmp://******'

I'm pretty sure my azure channel is working because i can stream to it with wirecast...

Any suggestions?

**Comment by saudet** [comment]
What do you get in the log of FFmpeg?

**Comment by antoniogiordano** [comment]
Where can i see it on an Android application?

**Comment by saudet** [comment]
Call FFmpegLogCallback.set() on init to get it in the logs of Android.

**Comment by antoniogiordano** [comment]
Thanks, this is the output:

01-07 19:32:31.485 25785-25785/com.example.android.camera2basic W/System.err: Error: [tcp @ 0xde4c7000] Failed to resolve hostname chn1-ubiatarms.channel.mediaservices.windows.net: No address associated with hostname
01-07 19:32:31.486 25785-25785/com.example.android.camera2basic W/System.err: Error: [rtmp @ 0xf3e3d2a0] Cannot open connection tcp://**.channel.mediaservices.windows.net:1935
01-07 19:32:31.487 25785-25785/com.example.android.camera2basic I/System.out: [libx264 @ 0xe8eff800] final ratefactor: 41.15
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -5: Could not open 'rtmp://**.channel.mediaservices.windows.net:1935/live/**'
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:639)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:288)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at com.example.android.camera2basic.FfmpegRTMPManager.openStreamChannel(FfmpegRTMPManager.java:29)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at com.example.android.camera2basic.Camera2BasicFragment.onClick(Camera2BasicFragment.java:922)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at android.view.View.performClick(View.java:5198)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at android.view.View$PerformClick.run(View.java:21147)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at android.os.Looper.loop(Looper.java:148)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
01-07 19:32:31.489 25785-25785/com.example.android.camera2basic W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by antoniogiordano** [comment]
It looks like a network problem, thanks.
