### ISSUE TITLE
How can i convert this ffmpeg command line with FFmpegFrameRecorder?

### ISSUE THREAD

**Issue by antoniogiordano** [bytedeco/javacv#307]
Hi everybody, i have this ffmpeg line command parameters i have to replicate with javacv library.
How can i do?

```
-strict -2 -c:a aac -b:a 128k -ar 44100 -r 30 -g 60 -keyint_min 60 -b:v 400000 -c:v libx264 -preset medium -bufsize 400k -maxrate 400k -f flv
```

Actually i have:

```
        // H264
        recorder.setVideoCodec(28);
        recorder.setFormat("mp4");
        recorder.setFrameRate(frameRate);
        // frameRate * 2; Azure needs GOP or key frame interval of 2 seconds
        recorder.setVideoOption("keyint_min", "60");
        recorder.setSampleRate(sampleAudioRateInHz);
```

How can i complete?

**Comment by Iqra786** [comment]
for codec u can add following line
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);

**Comment by alicanalbayrak** [comment]
I need help with similar issue. I'm trying to implement following command with FFMpegFrameRecorder.

```sh
ffmpeg -i rtsp://10.0.5.1:554/live.sdp -vcodec copy ./vid.mp4
```

And my recorder settings like below:

```java
frameRecorder = new FFmpegFrameRecorder(fout, frameGrabber.getVideoWidth(), frameGrabber.getVideoHeight());
	    frameRecorder.setFormat("mp4"); 
	    frameRecorder.setFrameRate(frameRate);
//	    frameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
	    frameRecorder.setVideoCodecName("H264");
	    frameRecorder.setVideoQuality(0);
```

It works when I use `frameRecorder.setVideoCodecName("H264");` but fails when `frameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);` used. It says:

```java
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:529)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:288)
```

Also records are not smooth as expected. (Looking like some areas' pixels enlarging and marshalling neighbors pixels) Here is [ffprobe output of my stream](https://gist.github.com/alicanalbayrak/10e7d4837bf55aefb008)

**Comment by saudet** [comment]
@alicanalbayrak Have you tried with the latest code from the repository (1.2-SNAPSHOT)?

**Comment by alicanalbayrak** [comment]
No Saudet, I did not. I tried it with javacv version 1,1. I could not build javacpp-presets 1.2-SNAPSHOT locally. Because, I'm using CentOS 7 and Flycapture SDK does not support any other linux machine except linux. Any ways, I tried to pass  ```-vcodec copy``` parameter to recorder by using ``` frameRecorder.setVideoOption("vcodec", "copy")``` but still throws ``` avcodec_open2() error -22: Could not open video codec. ```

**Comment by saudet** [comment]
The `ffmpeg` module doesn't depend on `flycapture`, so you don't need to build that.

There is no codec named `copy`. That is just a special name used by the `ffmpeg` command line program. You're going to need to specify something valid there.

If you're looking for the something equivalent to the `copy` feature, that's what packets are for: issue #93. Please consider making a contribution. It's a feature requested by a lot of people, so it wouldn't be useful only to you! Thanks

**Comment by saudet** [comment]
JavaCV 1.4 has just been released. Is this working any better these days?

**Comment by saudet** [comment]
With commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 the `ffmpeg` program itself now gets bundled, so we can use it easily from Java. For this case, we could do something like the following:
```java
   String ffmpeg = Loader.load(org.bytedeco.ffmpeg.ffmpeg.class);
   ProcessBuilder pb = new ProcessBuilder(ffmpeg, "-strict", "-2", "-c:a", "aac", "-b:a", "128k", "-ar", "44100", "-r", "30", "-g", "60", "-keyint_min", "60", "-b:v", "400000", "-c:v", "libx264", "-preset", "medium", "-bufsize", "400k", "-maxrate", "400k", "-f", "flv", ...);
   pb.inheritIO().start().waitFor();
```
Please give it a try with 1.5-SNAPSHOT before the release: http://bytedeco.org/builds/

**Comment by saudet** [comment]
The ffmpeg program is now being bundled starting with JavaCV 1.5. Enjoy!
