### ISSUE TITLE
DependencyResolutionException

### ISSUE THREAD

**Issue by sivachirravuri** [bytedeco/javacv#311]
I am trying to build javacv project for android from basics. 

I have installed javacpp and javacpp-presets using cpbuild.sh and mvn install. I used the following command to build the arm specific  jars
" mvn install -Pandroid-arm -Dplatform.root=~/android-ndk-r10e/"

I can find the  all the javacpp-preset jars (ffmpeg-2.8.4-1.2-SNAPSHOT-android-arm.jar, ffmpeg-2.8.4-1.2-SNAPSHOT.jar  etc..) in the ~/.m2/repository/org/bytedeco/javacpp-presets/ffmpeg/2.8.4-1.2-SNAPSHOT folders..

Building  javacv project with the same command as above,giving the following error.

"
The requested profile "android-arm" could not be activated because it does not exist.

Failed to execute goal on project javacv: Could not resolve dependencies for project org.bytedeco:javacv:jar:1.2-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco.javacpp-presets:opencv:jar:linux-x86_64:3.1.0-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:ffmpeg:jar:linux-x86_64:2.8.4-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:flycapture:jar:linux-x86_64:2.8.3.1-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:libdc1394:jar:linux-x86_64:2.2.3-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:libfreenect:jar:linux-x86_64:0.5.3-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:videoinput:jar:linux-x86_64:0.200-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:artoolkitplus:jar:linux-x86_64:2.3.1-1.2-SNAPSHOT, org.bytedeco.javacpp-presets:flandmark:jar:linux-x86_64:1.07-1.2-SNAPSHOT: Could not find artifact org.bytedeco.javacpp-presets:opencv:jar:linux-x86_64:3.1.0-1.2-SNAPSHOT -> [Help 1]
" 

How to resolve these dependencies ?

Why does it look for "presets:ffmpeg:jar:linux-x86_64:2.8.4-1.2-SNAPSHOT " when I am using 
mvn install  -Pandroid-arm ??

Please help me..

Siva

**Comment by saudet** [comment]
Try `mvn install -Dplatform=android-arm` instead.
