### ISSUE TITLE
IPCameraFrameGrabber throws null pointer if read returns null

### ISSUE THREAD

**Issue by JLLeitschuh** [bytedeco/javacv#312]
Returning null here: 
https://github.com/bytedeco/javacv/blob/fc30fc8b5f1415d957727fb55fe549b248b29552/src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java#L174

Causes a null pointer in the `grab` method.

https://github.com/bytedeco/javacv/blob/fc30fc8b5f1415d957727fb55fe549b248b29552/src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java#L123

Would this be better handled by throwing an exception instead of returning null?

**Comment by saudet** [comment]
What do you think @supertick?

**Comment by JLLeitschuh** [comment]
We have our own copy of the IPCameraFrameGrabber in our source code because we were running out of memory on an ARM Chip because the IPCameraFrameGrabber creates a 4096 element byte array on each grab.
https://github.com/bytedeco/javacv/blob/fc30fc8b5f1415d957727fb55fe549b248b29552/src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java#L139

This was causing the JVM to run out of memory.

If you are curious you can see our modifications here: 
https://github.com/WPIRoboticsProjects/GRIP/blob/37e7aeb5f2fadf9a3e5f7f8fd83ec8dc7de44808/core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java

Anyways, I'm going to simply change it so that instead of returning null we throw an exception.
I'm happy to make a PR with the same change in your version.

**Comment by supertick** [comment]
Sure, it seems reasonable.  Many containers will increase capacity by 2.
And the throw seems like a good idea too.

You probably don't need this line though, unless I'm missing something ..
https://github.com/WPIRoboticsProjects/GRIP/blob/37e7aeb5f2fadf9a3e5f7f8fd83ec8dc7de44808/core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java#L193 

Nice work

**Comment by JLLeitschuh** [comment]
Those changes were actually done by @ThomasJClark
Are you actually interested in the byte allocation changes that we made to the IPCamera as well?

The only thing that worried us about doing that was that it would mean that each frame would be written into the same buffer meaning that you could have issues if you were storing the images given that they would all stored in the same backing array. Or am I interpreting the code wrong?

**Comment by supertick** [comment]
I was comparing the last two references you gave, I guess we are bouncing between topics...

I don't see the diff of throwing vs not throwing, but I would agree you - throwing is probably more appropriate.

Since I have not looked at this code for year(s), It would be helpful if I had 2 url references to compare:

Both files of your last reference have 

       if (c0 < 0) {
            //log.info("no content length returning null");
            return null;
        }

**Comment by saudet** [comment]
BTW, right now in FFmpegFrameGrabber, grab() returns null to indicate the
end of a stream, so we should do the same in IPCameraFrameGrabber, unless
it's not supposed to have an end of stream...?

**Comment by JLLeitschuh** [comment]
Okay, null pointer is settled. I'll add a PR to fix that.

--- 

On the other topic of reusing the same data structure.
We allocate one array for every instance of the class instead of for every grab.
https://github.com/WPIRoboticsProjects/GRIP/blob/37e7aeb5f2fadf9a3e5f7f8fd83ec8dc7de44808/core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java#L76


`cvMat` does not allocate a new mat, it uses the same data.
https://github.com/WPIRoboticsProjects/GRIP/blob/37e7aeb5f2fadf9a3e5f7f8fd83ec8dc7de44808/core/src/main/java/edu/wpi/grip/core/sources/IPCameraFrameGrabber.java#L137

It would be good if there was a version of grab that would take a mat as a parameter that the data would be read into. That way if you didn't want to have a new array allocated each time you called grab you could reuse the same memory space. The default `grab` would return a newly allocated mat with new memory.

Does that make sense?

Our application is multithreaded so the first thing we do with the frame we get from `grab` is copy it into another `Mat` so we don't have race conditions and don't have problems with native memory scoping between threads.

**Comment by JLLeitschuh** [comment]
So on the point about the null pointer sill. Wouldn't it just be better to throw an EOFException?

The user was expecting the stream to still be there to grab the next image but clearly it wasn't so wouldn't that be the expected exception?

https://docs.oracle.com/javase/7/docs/api/java/io/EOFException.html

**Comment by saudet** [comment]
Well, OpenCV does it that way (returning null) and `InputStream.read()` returns `-1` when reaching the end of a stream, so it doesn't feel too strange to return null. Do you have a use case in mind where an exception would be more desirable?

**Comment by JLLeitschuh** [comment]
I like this sort of mentality.
https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained

Also, as seen in the issue that prompted me to open this issue:
https://github.com/WPIRoboticsProjects/GRIP/issues/390
it leads to coding where you expect that values will be returned correctly.

In the current implementation by having the `readImage` simply return null you introduce a null pointer exception into the libraries method call.

By failing fast, you expose that a problem has occurred.
In our application we display the exceptions so we can get more feedback when problems occur.

![Exception Example](https://dl.dropbox.com/s/rk9wgz13i8y282n/Screenshot%202016-01-29%2020.28.20.png)

**Comment by saudet** [comment]
Sure, throwing `EOFException` makes sense when it's unexpected. So, like I said, are there any cases when an EOF is expected with `IPCameraFrameGrabber`? If not, feel free to throw an exception.

With files, the EOF is expected, so throwing an exception doesn't really make sense. We could have a method like `haveFrame()`, à la `java.util.Scanner`, but underlying libraries like FFmpeg don't have that functionality, so we would be forced to cache results, just because we don't want to return `null`. Not sure that's worth it.
