### ISSUE TITLE
Throwing Away The Interrupt Flag by catching the InterruptedException

### ISSUE THREAD

**Issue by JLLeitschuh** [bytedeco/javacv#315]
There are at least 5 locations where this library simply catches an InterruptedException and does nothing with it.
https://github.com/bytedeco/javacv/search?utf8=%E2%9C%93&q=InterruptedException

http://www.ibm.com/developerworks/library/j-jtp05236/
How an InterruptedException should be handled in is detailed in the link above. In a nutshell, the InterruptedException should never be simply tossed away. You should always either propigate the exception or reset the threads interrupted flag.

**Comment by saudet** [comment]
Thanks, I'll look at that, eventually, but is there anything that isn't working because of that for you application?

**Comment by JLLeitschuh** [comment]
We are running the framegrabber in its own thread at present. When we want to stop the thread we expect that anything that may be blocking will respond correctly to an InterruptedException by either rethrowing it or by "preserving state" and allowing the interrupt flag to propigate.

This may have been causing our thread to deadlock in our application when trying to stop it because the interrupt flag was being eaten.

We have been a slew of various problems with cameras and I'm trying to figure out all of the potential deadlock locations.

**Comment by saudet** [comment]
I see, so calling `Thread.currentThread().interrupt()` be a satisfactory fix?

**Comment by JLLeitschuh** [comment]
Yes. I mean more ideal is passing the InterruptedException is better practice.

> Well-behaved blocking library methods should be responsive to interruption and throw InterruptedException so they can be used within cancelable activities without compromising responsiveness.
> [Brian Goetz](http://www.ibm.com/developerworks/library/j-jtp05236/)

But if you are trying to not break your API then yes. This is fine.

**Comment by saudet** [comment]
Sure, I rethrow the exception when it makes sense, but `Thread.sleep()` is mostly called to work around temporary failures that occur frequently, by retrying the operations. IMO, it's not something that should be exposed more than we have too. It's something the upstream libraries should fix, and then we wouldn't need to use `Thread.sleep()` in the first place.

**Comment by saudet** [comment]
Let me know if the commits above are alright! Thanks

**Comment by JLLeitschuh** [comment]
The only one that I'm worried about is this one: https://github.com/bytedeco/javacv/commit/6875b0eb08bafaf16559555c6fc19aeecba912ea#diff-a47e0edeb3dfdcb531fe9fa18e016ef6R210

By calling start the frame grabber is fulfilling a promise that when the method returns without an exception then the grabber will be working.
Because by returning without an exception you are basically telling the thread and the user that the frame grabber has been started successfully when it really hasn't.

Thoughts?

**Comment by saudet** [comment]
Well, it probably doesn't work either if we exceed 100 counts either...

**Comment by JLLeitschuh** [comment]
So both cases should throw an exception probably. But just make sure you preserve the interrupt flag like you have.

**Comment by saudet** [comment]
Yeah, that sounds good. I've updated that in the latest commit above.

**Comment by JLLeitschuh** [comment]
That works. Cool!! Thanks for taking care of this. You guys are doing a great job with this library.
