### ISSUE TITLE
is there an easy way to initiate Mat with IplImage?

### ISSUE THREAD

**Issue by wei-hai** [bytedeco/javacv#317]
I tried to initiate a Mat variable with IplImage object like this:
```java
Mat mat = new Mat(imageObj);
```
and when printing mat.cols() it says 0 and the data inside is NULL. I am wondering if there is an easy way to do it.

**Comment by saudet** [comment]
Try cvarrToMat().

**Comment by saudet** [comment]
Fixed in version 1.2. Thanks for reporting!
