### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#321]
Hi Im having the problem that when I try to transcode a live stream into another live stream audio and video are out of sync. Any ideas why that is and how it can be fixed?

Its happening for many different input streams.

My version is 1.1

code is default  im using FFMpegFrameGrabber and FFmpegFrameRecorder

**Comment by saudet** [comment]
Make sure to call `FFmpegFrameRecorder.setTimestamp(FFMpegFrameGrabber.getTimestamp())`, before calling `FFmpegFrameRecorder.record(Frame)`

**Comment by The-Crocop** [comment]
Im doing this:

`recorder.start();
   Frame capturedFrame= null;
                while( keepRunning && (capturedFrame = grabber.grabFrame(audio,video, true, false)) != null ){
              
					recorder.setTimestamp(grabber.getTimestamp())
                     recorder.record(capturedFrame);
                `
and getting errors like:
 av_interleaved_write_frame() error -22 while writing interleaved video frame.

and 

 pts (600) < dts (767) in stream 0

**Comment by saudet** [comment]
That probably means you're trying to use a different frame rate. If you need to convert the frame rate, try to use `FFmpegFrameFilter` for that.

**Comment by The-Crocop** [comment]
How do I use FFmpegFrameFilter for that case?

**Comment by saudet** [comment]
Try to use it as shown in issue https://github.com/bytedeco/javacv/issues/164#issuecomment-134609198 but with the `fps` filter.

**Comment by The-Crocop** [comment]
is this correct?
` fpsFilter = new FFmpegFrameFilter("fps=fps=25",width,height)//fps=fps=25)
                recorder.start()
	        fpsFilter.start()
                Frame capturedFrame= null;
        
            while( keepRunning && (capturedFrame = grabber.grabFrame(audio,video, true, false)) != null ){
             
                    fpsFilter.push(capturedFrame)
                    capturedFrame = fpsFilter.pull()
                recorder.setTimestamp(grabber.getTimestamp())
                recorder.record(capturedFrame);
            }`

**Comment by saudet** [comment]
You're missing a loop in there, and we'll need to pass the timestamps to
FFmpegFrameFilter as well, somehow... I didn't think about that...

**Comment by The-Crocop** [comment]
`
   fpsFilter = new FFmpegFrameFilter("fps=fps=25",width,height)

                recorder.start()
			    fpsFilter.start()
                Frame capturedFrame= null;

                    while( keepRunning && (capturedFrame = grabber.grabFrame(audio,video, true, false)) != null ){

                fpsFilter.push(capturedFrame) //--> before this we should be calling fpsFilter.setTimestamp(grabber.getTimestamp)?

                Frame frame = null

                while ((frame = fpsFilter.pull())!= null){
                    recorder.setTimestamp(grabber.getTimestamp())// <- so here we would need fpsFilter.getTimestamp?

                    recorder.record(frame);
                }
`

So currently there is no way to synchronize audio and video or is there another option?
[Parsed_fps_0 @ 000000003a657560] Discarding initial frame(s) with no timestamp

**Comment by saudet** [comment]
You could simply drop the frame when `recorder.getTimestamp() > grabber.getTimestamp()`.

**Comment by The-Crocop** [comment]
Ok so I keep fpsFilter, and instead of:
` recorder.setTimestamp(grabber.getTimestamp())`
I do if(recorder.getTimestamp() <= grabber.getTimestamp())recorder.setTimestamp(grabber.getTimestamp())
?

or do you mean I should remove fps Filter completely?

**Comment by saudet** [comment]
Do something like that without the fps filter, yes.

**Comment by The-Crocop** [comment]
Ok thanks alot will try that

**Comment by The-Crocop** [comment]
`  while( keepRunning && (capturedFrame = grabber.grabFrame(audio,video, true, false)) != null ){
					if(!(recorder.getTimestamp() > grabber.getTimestamp())){
						recorder.setTimestamp(grabber.getTimestamp())
						recorder.record(capturedFrame)
					}else log.info("drop Frame!")
            }`

I did that now all video Frames are being dropped :/ but sound is getting through

**Comment by saudet** [comment]
Well, do you see anything in FFmpeg's log that might indicate problems with the timestamps?

**Comment by The-Crocop** [comment]
No Messages at all. If I leave out the setTimestamp(grabTimestamp) it works for same framerate

**Comment by saudet** [comment]
So it looks like a problem with variable frame rates. Try to use different formats and codecs.
