### ISSUE TITLE
imencode issue

### ISSUE THREAD

**Issue by paolobolettieri** [bytedeco/javacv#324]
I'm triyng to encode a Mat as JPEG into a byte array, but it doesn't work, the byte array doesn't change its own values.

Below an example code:

String imagePath = "path of my jpeg image";
Mat img = imread(imagePath);
byte[] byteArray = new byte[1];
imencode(".jpg", img, byteArray);

byteArray value remains [0].
Is this a JavaCV issue, or is there anything wrong in my code?

**Comment by saudet** [comment]
Try with BytePointer instead of byte[].

**Comment by paolobolettieri** [comment]
It works! Thank you.

**Comment by saudet** [comment]
Good! It should also work if you provide a large enough `byte[]`.

**Comment by paolobolettieri** [comment]
I also tried with a big array of one million elements 
byte[] byteArray = new byte[1000000];
but it doesn't work.

**Comment by saudet** [comment]
That's probably fixed if you try the latest code: https://github.com/bytedeco/javacpp-presets/issues/109

**Comment by robertoandrade** [comment]
Building a BytePointer out of an existing byte[] doesn't seem to work either. Is there a javacpp-presets release that includes fixes for this and using a ByteBuffer also?

**Comment by saudet** [comment]
No release yet, no.
