### ISSUE TITLE
class file not found

### ISSUE THREAD

**Issue by Cheerfultrout** [bytedeco/javacv#328]
So I was trying to compile a program, but I got this error:
"ExampleTest.java:88: error: cannot access avutil
                    recorder.record(grabFrame);
                            ^
  class file for org.bytedeco.javacpp.avutil not found"
(recorder is a FFmpegFrameRecorder object by the way)
here are my import statements:
import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;
import static org.bytedeco.javacpp.opencv_highgui.*;
import java.io.File;
import org.bytedeco.javacpp.opencv_core.IplImage;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;

Am I missing a necessary import? Did I forget to add a jar file to my classpath? Is the class file just missing from the jar file? Does anyone know whats going wrong here?

UPDATE:
looked into it a bit more and found issues 133 and 79 are similar to mine, I'm going to attempt the fixes that are posted there. I'm using a different compiler than those two were though, so if anyone is making a list of compilers with the issue, add jGRASP to it.

UPDATE:
I added all of the precompiled jar files to the folder containing the jar files I had added to my classpath.
After doing that (without adding anything to my classpath) the issue was fixed. I got the idea after a whole bunch of stuff couldn't be found after removing some of the unused jars. I don't really know what this means, but I'm sure it could help with fixing this issue.

**Comment by saudet** [comment]
Adding all the JAR files to the class path, yes, that's what is says in the README.md file.
