### ISSUE TITLE
Could not open 'rtmp://my-streaming-server/app_name_here/instance_name/stream_name

### ISSUE THREAD

**Issue by Punching** [bytedeco/javacv#329]
I tryed this Code-Example: [https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java](url) and the Problem is that I getting this Error: 

`Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -1313558101: Could not open 'rtmp://my-streaming-server/app_name_here/instance_name/stream_name'
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:639)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:288)
	at javatestjavacv.JavaTestJavaCV.main(JavaTestJavaCV.java:59)
Java Result: 1` 
On line 59 I have this: 
"recorder.start()" 

How can I solve this Problem?

**Comment by saudet** [comment]
Have you solved this issue?

**Comment by Punching** [comment]
Sure, often I should read the manuel much better... 

But now the Problem is, that the Frame ist just black... Audio capturing works, I can hear my voise but i the video is unfortunaly black too. `public static final String FILENAME = "output.flv";
    final private static int FRAME_RATE = 30;
    final private static int GOP_LENGTH_IN_FRAMES = 60;

    final private static int WEBCAM_DEVICE_INDEX = 0;
    final private static int AUDIO_DEVICE_INDEX = 6;

    private static long startTime = 0;
    private static long videoTS = 0;


    public static void main(String[] args) throws Exception {

        int captureWidth = 1920;
        int captureHeight = 1080;

        OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(WEBCAM_DEVICE_INDEX);
        grabber.setImageWidth(captureWidth);
        grabber.setImageHeight(captureHeight);
        grabber.start();

        final FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(FILENAME, captureWidth, captureHeight, 2);
        recorder.setInterleaved(true);

        recorder.setVideoOption("tune", "zerolatency");
        recorder.setVideoOption("crf", "28");

        recorder.setVideoBitrate(2000000);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);

        recorder.setFormat("flv");
        recorder.setFrameRate(FRAME_RATE);
        recorder.setGopSize(GOP_LENGTH_IN_FRAMES);

        recorder.setAudioOption("crf", "0");
        recorder.setAudioQuality(0);
        recorder.setAudioBitrate(192000);
        recorder.setSampleRate(44100);
        recorder.setAudioChannels(2);
        recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);

        recorder.start(); 

        CanvasFrame cFrame = new CanvasFrame("Capture Preview", CanvasFrame.getDefaultGamma() / grabber.getGamma());
        cFrame.setVisible(true);
        Frame capturedFrame = null;

        while ((capturedFrame = grabber.grab()) != null) {

            if (cFrame.isVisible()) {
                cFrame.showImage(capturedFrame);
            }
            if (startTime == 0) {
                startTime = System.currentTimeMillis();
            }
            videoTS = 1000 * (System.currentTimeMillis() - startTime);
            if (videoTS > recorder.getTimestamp()) {
                recorder.setTimestamp(videoTS);
            }
            recorder.record(capturedFrame);
        }
        cFrame.dispose();
        recorder.stop();
        grabber.stop();
    }`

I hope you can help me, because I am not a profi :( 

thx, 
Punching

**Comment by saudet** [comment]
Try this sample instead:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by Punching** [comment]
Well, isn't there any different between android apps and Windows?

**Comment by saudet** [comment]
Yes, which one are you trying to do?

**Comment by Punching** [comment]
I want to do an Windows Application, where you can press an Button, and then the webcam should capture in the background.

**Comment by saudet** [comment]
Ok, so try to use `VideoInputFrameGrabber` instead of `OpenCVFrameGrabber`.

**Comment by Punching** [comment]
You are my hero! 

When I delete following lines: 
`if (cFrame.isVisible()) {
                cFrame.showImage(capturedFrame);
            }`
But then I got following output: 
`Output #0, flv, to 'output.flv':
***** VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****

    Stream #0:0: Video: h264 (libx264), yuv420p, 1920x1080, q=-1--1, 2000 kb/s, 30 tbn, 30 tbc
SETUP: Setting up device 0
SETUP: Microsoft� LifeCam Studio(TM)
    Stream #0:1: Audio: aac (libvo_aacenc), 44100 Hz, stereo, s16, 64 kb/s
SETUP: Couldn't find preview pin using SmartTee
SETUP: Default Format is set to 640 by 480 
[libx264 @ 000000000d350f60] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
SETUP: trying requested format RGB24 @ 1920 by 1080
[libx264 @ 000000000d350f60] profile High, level 4.0
SETUP: trying format RGB24 @ 1920 by 1080
SETUP: trying format RGB32 @ 1920 by 1080
SETUP: trying format RGB555 @ 1920 by 1080
SETUP: trying format RGB565 @ 1920 by 1080
SETUP: trying format YUY2 @ 1920 by 1080
SETUP: trying format YVYU @ 1920 by 1080
SETUP: trying format YUYV @ 1920 by 1080
[libx264 @ 000000000d350f60] 264 - core 148 r2638 7599210 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
SETUP: trying format IYUV @ 1920 by 1080
SETUP: trying format UYVY @ 1920 by 1080
SETUP: trying format YV12 @ 1920 by 1080
[libvo_aacenc @ 000000000d351d00] Trying to remove 1024 samples, but the queue is empty
SETUP: trying format YVU9 @ 1920 by 1080
[flv @ 000000000d350220] Encoder did not produce proper pts, making some up.
SETUP: trying format Y411 @ 1920 by 1080
SETUP: trying format Y41P @ 1920 by 1080
[libvo_aacenc @ 000000000d351d00] Trying to remove 1024 samples, but the queue is empty
SETUP: trying format Y211 @ 1920 by 1080
[libx264 @ 000000000d350f60] frame I:2     Avg QP:22.64  size: 41157
SETUP: trying format AYUV @ 1920 by 1080
SETUP: trying format Y800 @ 1920 by 1080
[libx264 @ 000000000d350f60] frame P:345   Avg QP:29.80  size: 13537
SETUP: trying format Y8 @ 1920 by 1080
[libx264 @ 000000000d350f60] mb I  I16..4: 18.9% 77.6%  3.5%
SETUP: trying format GREY @ 1920 by 1080
SETUP: trying format OTHER @ 1920 by 1080
[libx264 @ 000000000d350f60] mb P  I16..4:  0.7%  2.0%  0.0%  P16..4: 50.2%  2.8%  3.2%  0.0%  0.0%    skip:41.0%
SETUP: couldn't find requested size - searching for closest matching size
SETUP: closest supported size is YUY2 @ 1920 1080
[libx264 @ 000000000d350f60] 8x8 transform intra:73.2% inter:97.0%
SETUP: Capture callback set
[libx264 @ 000000000d350f60] coded y,uvDC,uvAC intra: 38.4% 56.0% 16.7% inter: 9.7% 31.9% 0.2%
SETUP: Device is setup and ready to capture.

[libx264 @ 000000000d350f60] i16 v,h,dc,p: 15% 25%  7% 54%

SETUP: Disconnecting device 0
[libx264 @ 000000000d350f60] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 18% 22%  5%  8%  6% 10%  6%  7%
SETUP: freeing Grabber Callback
SETUP: freeing Grabber  
[libx264 @ 000000000d350f60] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 25% 16%  4%  9%  6% 10%  4%  3%
SETUP: freeing Control   
[libx264 @ 000000000d350f60] i8c dc,h,v,p: 67% 16% 12%  6%
SETUP: freeing Media Type  
[libx264 @ 000000000d350f60] Weighted P-Frames: Y:1.7% UV:1.2%
SETUP: removing filter NullRenderer...
[libx264 @ 000000000d350f60] ref P L0: 52.1% 13.7% 22.1% 11.9%  0.2%
SETUP: filter removed NullRenderer  
[libx264 @ 000000000d350f60] kb/s:3287.04
SETUP: removing filter Sample Grabber...
SETUP: filter removed Sample Grabber  
SETUP: removing filter AVI Decompressor...
SETUP: filter removed AVI Decompressor  
SETUP: removing filter Smart Tee...
SETUP: filter removed Smart Tee  
SETUP: removing filter Microsoft� LifeCam Studio(TM)...
SETUP: filter removed Microsoft� LifeCam Studio(TM)  
SETUP: freeing Capture Graph 
SETUP: freeing Main Graph 
SETUP: Device 0 disconnected and freed

BUILD SUCCESSFUL (total time: 16 seconds)`

I mean "BUILD SUCCESSFUL" seems to be right but I wondering why there is all that output.

**Comment by saudet** [comment]
It's just debug information. It looks fine, you can ignore it.

**Comment by Punching** [comment]
Very nice. You are my Hero :D 
Is there any possiblity to reconize faces, and focus it?

**Comment by saudet** [comment]
Try this sample:
https://github.com/bytedeco/javacv/blob/master/samples/OpenCVFaceRecognizer.java

**Comment by Punching** [comment]
Well up to now Everything work well, but the sound isn't in sync. Is there any posibillty to fix this?

**Comment by saudet** [comment]
If the processing is too slow, your camera driver might be buffering frames. Try to reduce the frame rate of the camera by calling FrameGrabber.setFrameRate() before start().
