### ISSUE TITLE
javacv (sample for opencv and flandmark)

### ISSUE THREAD

**Issue by AmlFawzy** [bytedeco/javacv#330]
hi 
i'm new in javacv  i can't know how to use it is it like opencv ?
i want to use it with flandmark to detect landmarks can anyone help me
please help
thanks

**Comment by saudet** [comment]
There is a demo for flandmark here:
https://github.com/bytedeco/javacv-examples/tree/master/flandmark-demo
Do you have anything else @jpsacha ?

**Comment by AmlFawzy** [comment]
i visit this link 
and i downloaded javacv library and add javacv ,javacpp,flandmark jar files to my project 
then i copy example1 and paste it to class 
but i found alot of error 
the error on IplImage  and cvPoint and cvSize(0,0); and i can't solve it 
please help

**Comment by AmlFawzy** [comment]
hi 
i visit this link and downloaded javacv library and add javacv ,javacpp and flandmark jar files to my project and then i copy example1 to class but i found alot of error 
on cvpoint ,cvSize(0,0) and IplImage and i can't solve it 
please help @saudet

**Comment by jpsacha** [comment]
@AmlFawzy Did you try to run examples as they are provided, without modification? 

Additional example is in the [README for flandmark preset](https://github.com/bytedeco/javacpp-presets/tree/master/flandmark).

**Comment by AmlFawzy** [comment]
i run it without any modification @jpsacha

**Comment by jpsacha** [comment]
Can you describe in more details what exactly you are doing? How are you compiling and running the code? What errors are you getting?

**Comment by AmlFawzy** [comment]
i want to use fland mark in side java as i want land marks on eye corner and nose and mouth 
so  i download javacv from githup then i add j javacv ,,javacpp and flandmark jar files to my project and then i copy example1 to class then  i found error i can take snapshot  for code and send it to you if you agree  @jpsacha

**Comment by AmlFawzy** [comment]
i will till you also 
the errors in this lines because the class IplImage  don't exist i think so 

in this line the error is in cvsize 
 cvLoadHaarClassifierCascade(file.getCanonicalPath(), cvSize(0, 0));

the error is in ipllimage and IPL_DEPTH_8U
 public static IplImage loadImage(File file) throws IOException {
    IplImage image = cvLoadImage(file.getAbsolutePath());
public static void show(final IplImage image, final String title) {
        final IplImage image1 = cvCreateImage(cvGetSize(image), IPL_DEPTH_8U, image.nChannels())

in this lines the error in CvRect and  cvPoint
CvRect rect = new CvRect(elem);

cvPoint((int) model.bb().get(0), (int) model.bb().get(1)),
                        cvPoint((int) model.bb().get(2), (int) model.bb().get(3)), CV_RGB(0, 0, 255));

**Comment by AmlFawzy** [comment]
![qtpg8uavhyj4](https://cloud.githubusercontent.com/assets/15948173/13036541/d3f522d2-d372-11e5-8653-5ad922199ab7.jpg)

**Comment by jpsacha** [comment]
The errors indicate missing dependency on opencv preset. You need to add it to you project. 

You can attach your project here, so it is easier to diagnose.

**Comment by AmlFawzy** [comment]
where i can find opencv preset please?

**Comment by AmlFawzy** [comment]
i solved the error  but when i try to run code there is an error which is 
failed to load flandmarkmodel 
where i can find it?

**Comment by AmlFawzy** [comment]
hi, i solved the error and now code running with me but i want to ask that 
is every image should have .dat file in order to find land marks on it ?
as when i try to run code to my image it dosn't put land marks on itif yes what should i do to make this program detect land marks on any image please help?
      من: jarek <notifications@github.com>
 إلى: bytedeco/javacv <javacv@noreply.github.com> 
نسخة كربونية: AmlFawzy <amlfawzy945@yahoo.com>
 تاريخ الإرسال: الإثنين 15 فبراير، 2016‏ 2:07 ص
 الموضوع: Re: [javacv] javacv (sample for opencv and flandmark) (#330)
   
The errors indicate missing dependency on opencv preset. You need to add it to you project. You can attach your project here, so it is easier to diagnose.—

**Comment by jpsacha** [comment]
Please direct question regarding FLandmark operation to the [FLandmak project](https://github.com/uricamic/flandmark) itself. They have better understanding how that code operates and what can be done with it.

**Comment by AmlFawzy** [comment]
hi @jpsacha
can i detect iris using javacv ?

**Comment by saudet** [comment]
Sure, there's a few approaches we can try with OpenCV:
http://answers.opencv.org/question/12034/face-eyes-and-iris-detection/
http://stackoverflow.com/questions/12844479/opencv-iris-detection-c

**Comment by DwayneTek** [comment]
hi @AmlFawzy did you get to detect the the eyebrow ? can you provide codes tnx in advance ! )
