### ISSUE TITLE
MultiDex, javacv error on Android

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#334]
Hi Samuel,

I'm trying to include javacv in a rather large project. When I include it I get the 65k codelines error and to solve it use multidex. However when running multidex the FfmpegRecorder throws an error avutil NoClassDef found error. My code works perfect when I only take the javacv part and use it in a separate activity.
 Do you have an idea how that can be solved? I tried stuff with proguard and tried to copy the .so files to jniFolder but that didn't help either.Best regards and thanks for this awesome project

**Comment by saudet** [comment]
Duplicate of #335
