### ISSUE TITLE
MultiDex, javacv error on Android

### ISSUE THREAD

**Issue by The-Crocop** [bytedeco/javacv#335]
Hi Samuel,

I'm trying to include javacv in a rather large project. When I include it I get the 65k codelines error and to solve it use multidex. However when running multidex the FfmpegRecorder throws an error avutil NoClassDef found error. My code works perfect when I only take the javacv part and use it in a separate activity.
 Do you have an idea how that can be solved? I tried stuff with proguard and tried to copy the .so files to jniFolder but that didn't help either.Best regards and thanks for this awesome project.
In my build gradle I am using
Javacv
And ffmpeg and opencv with android-arm specifier

**Comment by The-Crocop** [comment]
Ok seems like it wasnt an issue with multidex. After removing a lot of libraries and disabling multidex the problem still persisted.
The reason for the üroblem was I had libvlc in there too and they were somehow conflicting. Probably because some shared classes from ffmpeg.

**Comment by saudet** [comment]
I see, yes Android isn't very good for that. It loads all the symbols from all libraries globally, so you had better make sure two libraries don't define the same symbol. :)

**Comment by The-Crocop** [comment]
By the way. Can I also play videos easily with javacv on Android? Then I could throw away libvlc?

**Comment by saudet** [comment]
@The-Crocop There's no player currently included, but if you'd like to make a contribution, it would be welcome :) I'm sure we can easily integrate some existing code, like the one from here: https://github.com/google/grafika

**Comment by The-Crocop** [comment]
Sure I will do that. Just need a little time.

**Comment by MuhammadUmair12** [comment]
Hi all, i am getting this error:Caused by: java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avcodec on nexus 5 or marshmallow only.How to resolve it.

**Comment by saudet** [comment]
@MuhammadUmair12 see #245

**Comment by MuhammadUmair12** [comment]
Thanks alot for your quick reply. I resolved this by decreasing my target sdk to 22 from 23.But why is it not working for 23 sdk version.
