### ISSUE TITLE
FFmpegFrameRecorder creates video with duration less than last frame timestamp

### ISSUE THREAD

**Issue by Denis1986** [bytedeco/javacv#337]
I use FFmpegFrameRecorder (javaCV 1.1) to create video fragments with max duration of 30 seconds from screenshots, which I get from MediaProjection on Android. In each video fragment first frame has timestamp 0.
I have the following recorder settings: 

```
FFmpegFrameRecorder mRecorder;
//...
mRecorder.setFormat("mp4");
mRecorder.setFrameRate(30);
mRecorder.setVideoCodec(AvCodecConstants.CODEC_ID_H264);
mRecorder.setGopSize(10);
```

MediaProjection gives me next screenshot only when there are changes on the screen, so frames are recorded irregularly. When it is time to close current video fragment, usually the last recorded frame has timestamp smaller than 30 seconds. I found only one way to get video fragment of exactly 30 seconds – I record last real frame several times. As I understand, if first frame has timestamp 0, video duration must be equal to last frame timestamp + last frame duration. For example, if last real frame has timestamp 27.5 sec, I record this frame with timestamps 28.5 sec, 29.5 sec, 29.966 sec. This approach works perfectly with mpeg4 codec, but with H264 codec result video duration is much smaller than last frame timestamp. For example, for one of video fragments video duration (determined by exiftool and mp4parser) is 28.7 sec and last frame has timestamp 29.966 sec and pkt_duration_time = 0.033333 sec (determined by ffprobe). 
So I can’t create video of specified duration using FFmpegFrameRecorder with H264 codec. Is it a bug in FFmpegFrameRecorder (when using H264 codec) or am I missing something? May be, there is a way to set duration for last frame instead of recording the last real frame with different timestamps?

**Comment by saudet** [comment]
Maybe there is a bug, but the mp4 format isn't known to be easy to work with anyway. I'd suggest trying the Matroska (mkv) format, if that's an option.

**Comment by saudet** [comment]
Is this still happening with JavaCV 1.2?

**Comment by Denis1986** [comment]
Sorry for the delay. Now we use MediaCodec instead of ffmpeg in our project.
I have tried to use JavaCV 1.2 in the old version of our project today: 
```
compile 'org.bytedeco:javacv:1.2'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.2-1.2', classifier: 'android-x86'
```
But I get the following error:
"Error:A problem occurred configuring project ':app'.
> A problem occurred configuring project ':library'.
   > Could not find javacpp-presets-Windows 7-amd64.jar (org.bytedeco:javacpp-presets:1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Windows 7-amd64.jar"
I have Intel processor, so it it strange for me, that gradle searches for amd64 version.

**Comment by saudet** [comment]
Thanks for checking! That's a known issue with Gradle: https://github.com/bytedeco/javacv/issues/395#issuecomment-220213783

Let me know if that's enough to get it working, thanks!

**Comment by saudet** [comment]
Any updates on this? JavaCV 1.3 has just been released. Maybe this got fixed in new versions of FFmpeg...

**Comment by saudet** [comment]
I'm guessing you simply forgot to call `stop()`. Calling `release()` won't flush the buffers.
