### ISSUE TITLE
Help!cvCreateFileCapture("output.avi")" to get a CvCapture, but "cvCreateFileCapture("output.avi")" always returns "NULL"

### ISSUE THREAD

**Issue by chunlz** [bytedeco/javacv#338]
Dear Sir,
I am making a java-app with jdk8u74+netbeans8.1+javacv1.1. I used that "cvCreateFileCapture("output.avi")" to get a CvCapture, but "cvCreateFileCapture("output.avi")" always returns "NULL".I have checked the path of the "output.avi" with "new File("output.avi").exits()" and it return true.So I am sure the file is in the same folder as the java-app file. What is the problem?The following is my codes.

public l class VideoFileLength {
    public static void main(String[] argus) {
        float len = getVideoFileLength("output.avi");
        System.out.println("Video length: " + len + " s");
    }

    public static float getVideoFileLength(String fileName) {
        File file = new File(fileName);
        if (!file.exists()) {
            System.out.println("incorrect filename");
            return 0;
        }

        float len = 0;

        CvCapture capture = cvCreateFileCapture(fileName);
        if (capture == null) {
            System.out.println("could not open the video");
            len = -1;
        } else {
            try {
                long frameCount = (long) cvGetCaptureProperty(capture, CV_CAP_PROP_FRAME_COUNT);
                long fps = (long) cvGetCaptureProperty(capture, CV_CAP_PROP_FPS);

                len = (float) frameCount / fps;
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                cvReleaseCapture(capture);
            }
        }
        return len;
    }
}

Otherwise the "output.avi" was created with the following codes which aslo using k8u74+netbeans8.1+javacv1.1. So the video codes of "output.avi" should be right.

public class Demo3 {

    public static void main(String[] args) throws Exception {

        FrameGrabber grabber = FrameGrabber.createDefault(0);
        grabber.start();

        Frame grabframe = grabber.grab();

        int width = grabframe.imageWidth;
        int height = grabframe.imageHeight;
        
        FrameRecorder recorder = FrameRecorder.createDefault("output.avi", width, height);
        recorder.setFrameRate(25);
        recorder.start();

        CanvasFrame canvasframe = new CanvasFrame("capture@mipuchun", CanvasFrame.getDefaultGamma() / grabber.getGamma());

        while (canvasframe.isVisible() && (grabframe = grabber.grab()) != null) {

            canvasframe.showImage(grabframe);
            recorder.record(grabframe);

        }
        canvasframe.dispose();

        recorder.stop();
        grabber.stop();
    }
}

**Comment by chunlz** [comment]
I have installed jdk8u74+netbeans8.1+javacv1.1 in windows8.The opencv was not install.

**Comment by saudet** [comment]
Please use `FFmpegFrameGrabber` instead.
