### ISSUE TITLE
FFmpegFrameGrabber and FFmpegFrameRecorder are very slow on Android

### ISSUE THREAD

**Issue by Rakatan** [bytedeco/javacv#340]
Hello,

I am trying to build a video processing app, which grabs frames from a video at certain times, processes them on the GPU and writes them to a new video file.

My problem is that actually grabbing the frames and recording them take a lot of time. I have profiled my app using the Android Device Monitor and have come up with the following numbers on a Nexus 5X:

FFmpegFrameGrabber.setFrameNumber() -- Cpu Time / Call: 21.859 ; Real Time / Call: 152.642
FFmpegFrameGrabber.grabImage() -- Cpu Time / Call: 14.735 ; Real Time / Call: 17.013
FFmpegFrameRecorder.record() -- Cpu Time / Call: 80.469 ; Real Time / Call: 82.779

I am not sure if these times are normal or not, or if i am doing something wrong here.
I would greatly appreciate any guidance or input regarding this matter, as this is a huge bottle neck in my application.

I will update with any requested details.

Thank you in advance.

**Comment by saudet** [comment]
Unfortunately, FFmpeg doesn't support hardware acceleration in any meaningful way, so try the "ultrafast" preset: #54
