### ISSUE TITLE
Is ffmpeg support animation when making video using recorder? 

### ISSUE THREAD

**Issue by hychanbb** [bytedeco/javacv#343]
I can now combined images into video and add an audio into it, however i think this video is still boring, so i want to add more effects on frame and more animations between frames. For the  animation part, anything i can do with javacv@@?

**Comment by saudet** [comment]
Check out FFmpegFrameFilter?

**Comment by hychanbb** [comment]
Ya, I should start with it. So, i can do animation with FFmpegFrameFilteronly with javacv right?

**Comment by saudet** [comment]
I'm afraid I don't understand the question. What do you mean by animation?

**Comment by hychanbb** [comment]
just basic zoom in zoom out and fade in fade out. Finally i found there is no relation with FFmpegFrameFilter. And i finish it with Mat operation. Thanks for help

**Comment by saudet** [comment]
Ok, good! FYI, FFmpeg filters also have that kind of functionality:
    https://ffmpeg.org/ffmpeg-filters.html
But it's easier to use functions from OpenCV, yes.
