### ISSUE TITLE
how to show IplImage on CanvasFrame?

### ISSUE THREAD

**Issue by sify21** [bytedeco/javacv#344]
Hello, I'm new to Javacv. I have a problem.
The code below:

IplImage image = cvLoadImage( "img_name" );
CanvasFrame canvas = new CanvasFrame( "Example" );
canvas.showImage( image );

should be equivalent to its C++ version:

IplImage* img = cvLoadImage( "img_name" );
cvNamedWindow( "Example" );
cvShowImage( "Example", img );

But it doesn't work because canvas.showimage needs type Frame or Image. How do I convert IplImage to Image? And by the way, does "Image" means "org.bytedeco.javacpp.FlyCapture2.Image"?

**Comment by saudet** [comment]
Try to use an `OpenCVFrameConverter`:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
