### ISSUE TITLE
How to convert IplImage to BufferedImage?

### ISSUE THREAD

**Issue by wuze455192247** [bytedeco/javacv#347]
How to convert IplImage to BufferedImage?

**Comment by saudet** [comment]
By using [`OpenCVFrameConverter.IplImage`](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.ToIplImage.html) with [`Java2DFrameConverter`](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/Java2DFrameConverter.html):
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by wuze455192247** [comment]
thank you, I solved it
