### ISSUE TITLE
How do you set a threshold for matchtemplates

### ISSUE THREAD

**Issue by cminion** [bytedeco/javacv#348]
I am working on something that needs a very high probability for the match to be correct. is there any way to set this threshhold?

**Comment by saudet** [comment]
Which function are you referring to?

**Comment by cminion** [comment]
Sorry a little more awake now, and I will try to be clearer.

I was trying to use the Template Matching function to find the co-ordinates of a sub image in an image.

What I am finding is if the sub image that i am searching for is not on the screen it goes to the next most likely choice. However I want an as exact and distinct match as possible

**Comment by saudet** [comment]
So you could put a threshold on the minimal acceptable error.

**Comment by cminion** [comment]
Is there an example for this? I'm using scala.

**Comment by cminion** [comment]
Here is the code I have so far

`		    val image1 = OpenCVUtils.loadOrExit(new File(imagePath))
				val image2 = OpenCVUtils.loadOrExit(new File("full.png"))
				val target = new Mat(image1, new Rect(0, 0, image1.cols(), image1.rows()))
				val roi = new Mat(image2, new Rect(x,y,w.asInstanceOf[Int],h.asInstanceOf[Int]))

				// perform template matching
				val result = new Mat()
		    imgproc.threshold(result, result, 255 * 1, 255, THRESH_BINARY)
				matchTemplate(
						roi, // search region
						target, // template
						result, 0)
				// similarity measure
        
				// find most similar location
				val minVal = new Array[Double](1)
				val maxVal = new Array[Double](1)
				val minPt = new Point()
				val maxPt = new Point()
				minMaxLoc(result, minVal, maxVal, minPt, maxPt, null`

**Comment by cminion** [comment]
OK im an idiot

Solved it with a simple

if (minVal(0) < 10000000) {

**Comment by saudet** [comment]
No problem :) Thanks for posting your solution. I'm sure it'll help out a few others!

**Comment by costimasca** [comment]
The max_val is dependent on the area of the template image. You can get a pseudo-accuracy measure using the ratio max_value/template_area. It will sometimes be larger than 1, but it is a good indicator for how likely it is that the template is actually there.

**Comment by o21x** [comment]
4.0 return null
==========================================
matchTemplate(sourceGrey, template, result, TM_CCORR_NORMED);

		DoublePointer minVal = new DoublePointer();
		DoublePointer maxVal = new DoublePointer();
		Point min = new Point();
		Point max = new Point();
		minMaxLoc(result, minVal, maxVal, min, max, null);



================================
Exception in thread "main" java.lang.NullPointerException: This pointer address is NULL.
	at org.bytedeco.javacpp.DoublePointer.get(Native Method)
	at org.bytedeco.javacpp.DoublePointer.get(DoublePointer.java:101)

**Comment by saudet** [comment]
@o21x Try this:
```java
	DoublePointer minVal = new DoublePointer(1);
	DoublePointer maxVal = new DoublePointer(1);
	Point min = new Point(1);
	Point max = new Point(1);
	minMaxLoc(result, minVal, maxVal, min, max, null);
```

**Comment by o21x** [comment]
@saudet     thanks  buddy!   it works!

minMaxLoc  says pass null if not use ,  comment should be edit   ^_^

**Comment by saudet** [comment]
The problem isn't with the call to `minMaxLoc()`, it's with the code that comes after that.
