### ISSUE TITLE
sluggish video on ffmpegFrameRecorder

### ISSUE THREAD

**Issue by asafbennatan** [bytedeco/javacv#354]
Hi ,
i have modified the RecorderActivity example to stream video as it records in the following way,
removed all frame holders and buffers the activity had (i e images field) and now i am creating a frame every time onPreviewFrame is called and then recording it (also slimier change was made for the audio recording thread - recording the buffer right after i read it using the recorder).
every thing works fine for lower resolutions but for 720i and above the video is very sluggish ,my guess is that i'm doing something wrong,
video settings:
```
  private int sampleAudioRateInHz = 44100;
    private int imageWidth = 1080;
    private int imageHeight = 720;
    private int frameRate = 30;
    private String format="mpegts";
also when initializing the recorder :
 recorder.setVideoQuality(0);
      recorder.setVideoOption("preset", "ultrafast");
```
please help ,
Thanks.

**Comment by saudet** [comment]
Make sure to use the x264 codec by calling `recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264)`.

Other than that, I'm assuming you are on an Android device, so you'll need to use hardware encoder via the Android API. FFmpeg doesn't support that.

Duplicate #54, #55, #340
