### ISSUE TITLE
Infinite loop when seeking Apple HLS stream with FFmpegFrameGrabber

### ISSUE THREAD

**Issue by danielsabinasz** [bytedeco/javacv#364]
Hello everyone,

I'm using the latest GitHub version of JavaCV.

I want to grab arbitrary frames from an Apple HLS stream. I use the following code:
```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("http://localhost:1935/ARD/myStream/playlist.m3u8?DVR");
grabber.start();

grabber.setTimestamp(6000000);
grabber.grab();

grabber.setTimestamp(7000000);
grabber.grab();
```

On the second setTimestamp call, this causes the loop in line 357 of FFmpegFrameGrabber.java to run infinitely.

I added some debug output like so:
```
while (this.timestamp > timestamp + 1 && grabFrame(false, true, false, false) != null) {
    System.out.println("while " + this.timestamp + " > " + (timestamp + 1));
    // flush frames if seeking backwards
}
```

The problem is that this.timestamp keeps increasing on each grabFrame call, even though the loop condition expects it to decrease:
```
while 7781000 > 7000001
while 7821000 > 7000001
while 7861000 > 7000001
while 7901000 > 7000001
while 7941000 > 7000001
while 7981000 > 7000001
...
```

Also, I don't quite understand why this.timestamp starts at 7781000, even though the call before requested 6000000.

Any thoughts?

Kind regards,
Daniel

**Comment by saudet** [comment]
It just looks like your stream doesn't support seeking very well. Do you know of some other application that has no trouble seeking? How does VLC fare?

**Comment by saudet** [comment]
I'm assuming VLC doesn't work better, and that this is an issue with your server, but please let me know if this isn't the case.
