### ISSUE TITLE
Can't run OpenCV 3.1.0 on 64bit android devices

### ISSUE THREAD

**Issue by sherlock917** [bytedeco/javacv#365]
Hi!

I am trying to write a face recognition app for android using FaceRecognizer in OpenCV. But I am having the same trouble as #250 (my testing device is 64bit). I am not sure if this problem has been solved yet. I've searched a lot but still getting nowhere. If there's a possible way to solve this problem, could you please give me some instructions? 

As far as I know, OpenCV 3.1.0 does support 64bit android devices and it contains libs for arm64. However it seems 3.+ versions of OpenCV has removed the "contrib" library where the FaceRecognizer class is in. I am not sure if this is relevant but I am really confused.

Many thanks!

**Comment by saudet** [comment]
We can use 32-bit binaries on 64-bit devices, so just try them!

**Comment by sherlock917** [comment]
I somehow got it working!!! I manually put the jar files into my project and add `packagingOptions` into my `build.gradle` (thx to #353 ) and it worked perfectly. Thank you so very much and what a cool library for us newbies to use OpenCV on android!

**Comment by filipkeanu** [comment]
I've faced exactly the same issue while trying to use JavaCV 3.1.0 on 64-bit Samsung device. @sherlock917 can you please do me/others a favor and paste the part of build.gradle that made it to work for you (and please also mention which jar version you have used). I've spent hours trying everything out and I am getting desperate to make it work. Apparently I am much more of a newbie than you are :)

**Comment by saudet** [comment]
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
