### ISSUE TITLE
how to get feature vektor from javaCV createFisherFaceRecognizer ????

### ISSUE THREAD

**Issue by trianindiaputra** [bytedeco/javacv#371]
hi, @saudet can u help me to solve this problem

**Comment by saudet** [comment]
What is the problem?

**Comment by trianindiaputra** [comment]
i want to using another predict method in faceRecognizer usiing canberra distance, how to modify this method (predict method)? n i want to view result the feature vector after createFisherfaceRecognizer already finished. can u help me @saudet

**Comment by saudet** [comment]
Ok, so what prevents you from doing it the same way people do it in C++?

**Comment by trianindiaputra** [comment]
I do not know what to do because I was newbie, may you give me advice for this problem??? how to view feature vector after createFisherfaceRecognizer finished ??? thanks @saudet

**Comment by trianindiaputra** [comment]
hi @saudet where is location for file "Fisherfaces in OpenCV"
http://docs.opencv.org/ref/master/da/d60/tutorial_face_main.html#gsc.tab=0
or https://github.com/bytefish/libfacerec/tree/master/samples in java cv? 
i want to get value from 
Mat reconstruction = LDA::subspaceReconstruct(ev, mean, projection);
        // Normalize the result:
        reconstruction = norm_0_255(reconstruction.reshape(1, images[0].rows));
        // Display or save:
        if(argc == 2) {
            imshow(format("fisherface_reconstruction_%d", num_component), reconstruction);
        } else {
            imwrite(format("%s/fisherface_reconstruction_%d.png", output_folder.c_str(), num_component), reconstruction);
        }
 thx for help.....

**Comment by saudet** [comment]
We can call use class from Java:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.LDA.html
Just call it the same way, something like this should work:
```java
Mat reconstruction = LDA.subspaceReconstruct(ev, mean, projection);
// Normalize the result:
reconstruction = norm_0_255(reconstruction.reshape(1, images[0].rows()));
// Display or save:
if(args.length == 1) {
    imshow(String.format("fisherface_reconstruction_%d", num_component), reconstruction);
} else {
    imwrite(String.format("%s/fisherface_reconstruction_%d.png", output_folder, num_component), reconstruction);
}
```

**Comment by trianindiaputra** [comment]
hi @saudet 
if i using OpenCVFaceRecognizer.java example... how to get the value? cause if i using your code this source cant detect. how to make this source code already detect in your example?
```
Mat reconstruction = LDA.subspaceReconstruct(ev, mean, projection);
// Normalize the result:
reconstruction = norm_0_255(reconstruction.reshape(1, images[0].rows()));
// Display or save:
if(args.length == 1) {
    imshow(String.format("fisherface_reconstruction_%d", num_component), reconstruction);
} else {
    imwrite(String.format("%s/fisherface_reconstruction_%d.png", output_folder, num_component), reconstruction);
}
```

**Comment by saudet** [comment]
I'm sorry, but I don't understand your question. If you have sample C++ code that does what you want, try to do the same thing in Java. If you have problems understanding how to translate the code to Java, please let me know.

**Comment by trianindiaputra** [comment]
hi @saudet 
im using your example source code, but i dont know how to get the result after using createfisherface(), the result i mean, value matrix after function createfisherface() already finish 
```
public class OpenCVFaceRecognizer {
    public static void main(String[] args, Mat ev, Mat mean) {
        String trainingDir = "Dtrain";
        Mat testImage = imread("1.jpg", CV_LOAD_IMAGE_GRAYSCALE);

        File root = new File(trainingDir);

        FilenameFilter imgFilter = new FilenameFilter() {
            public boolean accept(File dir, String name) {
                name = name.toLowerCase();
                return name.endsWith(".jpg") || name.endsWith(".pgm") || name.endsWith(".png");
            }
        };

        File[] imageFiles = root.listFiles(imgFilter);

        MatVector images = new MatVector(imageFiles.length);

        Mat labels = new Mat(imageFiles.length, 1, CV_32SC1);
        IntBuffer labelsBuf = labels.getIntBuffer();

        int counter = 0;

        for (File image : imageFiles) {
            Mat img = imread(image.getAbsolutePath(), CV_LOAD_IMAGE_GRAYSCALE);

            int label = Integer.parseInt(image.getName().split("\\.")[0]);

            images.put(counter, img);

            labelsBuf.put(counter, label);

            counter++;
        }

        FaceRecognizer faceRecognizer = createFisherFaceRecognizer();
        // FaceRecognizer faceRecognizer = createEigenFaceRecognizer();
        // FaceRecognizer faceRecognizer = createLBPHFaceRecognizer()

        faceRecognizer.train(images, labels);

        int predictedLabel = faceRecognizer.predict(testImage);

        System.out.println("Predicted label: " + predictedLabel);


    }
}
```
thx saude for help

**Comment by saudet** [comment]
What kind of result are you looking to get? Maybe the answer is somewhere in this guide:
http://docs.opencv.org/2.4/modules/contrib/doc/facerec/facerec_tutorial.html

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming you figured out what to do from the tutorial, but please let me know if this isn't the case! Thanks
