### ISSUE TITLE
OpenSSL Problem Google play Notification

### ISSUE THREAD

**Issue by Sennikpro** [bytedeco/javacv#374]
I got email from them 
Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK.    and I am using JavaCv and JavaCpp jars inside my app. is this jars using Openssl inside of them and if it is using can you upgrade their openssl versions?

**Comment by Sennikpro** [comment]
And also using ffmgep.jar Thank you very much.

**Comment by saudet** [comment]
There are SNAPSHOT binaries built with OpenSSL 1.0.2f here that you could use:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp/1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.0-1.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacv/1.2-SNAPSHOT/

**Comment by patelanil2007** [comment]
@Sennikpro i got same mail from google play store. have u solve it?? let me know if any ides about openssl.

**Comment by Sennikpro** [comment]
Hello Dear Patelanil

Yes. Notification is due to Jar files that use JAVACV, JAVACPP and FFMGEP. Because those jar files have OpenSSL lib inside as a module which its version is lower than 1.0.2f. You have to change immediatelly Jar files and also .So files with newer versions. Dear Saudet has shared it above as link. 
In addition to that, if notification does not disappear, then you should check other ads libs. maybe they have some Openssl modules inside to set up communication with their servers. Please let me know if you could solve this problem.

**Comment by patelanil2007** [comment]
thanx@Sennikpro 
please send me JAVACV, JAVACPP , FFMGEP and OPENCV and also ARMEABI folder of .so file. i downloaded it from above link but app crashes.

**Comment by Sennikpro** [comment]
Sure you can contact by my developer SKYPE account. its id sennik_fatih@hotmail.com. Pm for the time and I will there today.

**Comment by Sennikpro** [comment]
Send also Google play link to my skype so that I can better understand.

**Comment by patelanil2007** [comment]
@Sennikpro i sent  request in SKYPE

**Comment by patelanil2007** [comment]
@Sennikpro please send me all files in anil@creativeglance.com. Thanx in advance

**Comment by akhilc1** [comment]
@saudet The snapshot binaries links are broken, could you please check.

**Comment by saudet** [comment]
@akhilc1 Upgrade to version 1.2

**Comment by akhilc1** [comment]
I tried, but it says something like 'could not find code for mac machine..!' Is there anything I can do in Gradle file to resolve this?

**Comment by akhilc1** [comment]
I find that this ll work 👍

**Comment by ihassantariq** [comment]
Is this issue fixed after converting to 1.2 version of openCV?
