### ISSUE TITLE
why I use av_interleaved_write_frame to write avpacket ,but screen showed blurred 

### ISSUE THREAD

**Issue by wooden1985** [bytedeco/javacv#377]
I use  " avcodec_encode_audio2(audio_c, audio_cache_pack, frame, got_audio_packet) " to get some avpackets,and add to a list. when I do it again, I delete the avpackets from the list,and I use  " avcodec_encode_audio2(audio_c, audio_cache_pack, frame, got_audio_packet) " to get some avpackets again,add to a list,at the end,I use " synchronized (oc) {
            if (interleaved && video_st != null) {
                if ((ret = av_interleaved_write_frame(oc, audio_pkt)) < 0) {
                    throw new Exception("av_interleaved_write_frame() error " + ret + " while writing interleaved audio frame.");
                }
            } else {
                if ((ret = av_write_frame(oc, audio_pkt)) < 0) {
                    throw new Exception("av_write_frame() error " + ret + " while writing audio frame.");
                }
            }
        } ",it can get a video file,but when I play it,the screen showed blurred.why?

 Please forgive my bad  English

**Comment by saudet** [comment]
Please try to use FFmpegFrameRecorder instead. It's a much higher level, easier to use API.

**Comment by mifritscher** [comment]
For me, the  synchronized (org.bytedeco.javacpp.avcodec.class) in the commit https://github.com/bytedeco/javacv/commit/31e4015a2349905bbe877fb7c57e68a9a5c7b61d is a big hazard.

The problem is that this lock is held during the initial connect as well. So if I've e.g. a UDP receiver (on which the data can come in any time) further actions are blocked (e.g. (re)connecting to cameras) as well.

If I set the timeout option, this problem gets away. But it seems that the socket is not properly closed with FFmpegFrameGrabber.stop - at least a start afterwards fails with socket error -10048 (Port is already open). I'm using the current 1.3.3 version.

**Comment by saudet** [comment]
Is this a problem with FFmpeg or FFmpegFrameGrabber?

**Comment by mifritscher** [comment]
It depends ;)
Do you know why this locking is needed? Are there any functions in ffmpeg itself which are not threadsafe? The big question is: Why was this lock introduced?

I think(!!!) that it would be sufficient if the lock locks not AVCodec, but "this".

I grabbed the sledgehammer and tried

```
Method method = FFmpegFrameGrabber.class.getDeclaredMethod("startUnsafe");
method.setAccessible(true);
method.invoke(videoReader);
```

Which seems(!!!) to work fine. It's a hack, a brutal one.

**Comment by saudet** [comment]
Yes, it's not thread safe in FFmpeg to start multiple streams
simultaneously.

**Comment by mifritscher** [comment]
Do you know which functions are the problem? or the main open call itself?

**Comment by mifritscher** [comment]
Ok, I digged a bit and found avcodec_open2 is the abstacle. I think the best solution seems to be using  av_lockmgr_register ( https://www.ffmpeg.org/doxygen/3.2/group__lavc__misc.html - https://www.ffmpeg.org/doxygen/3.2/group__lavc__misc.html ) . Then only the minimal needed locking will be performed. 

Additionally, I found the line
`if (codec->caps_internal & FF_CODEC_CAP_INIT_THREADSAFE || !codec->init) `

in av_lock_avcodec.

from internal.h:
```
/**
 * The codec does not modify any global variables in the init function,
 * allowing to call the init function without locking any global mutexes.
 */
#define FF_CODEC_CAP_INIT_THREADSAFE        (1 << 0)
```

And grepping this most of the codecs are indeed threadsafe - or don't need to be inited!

The best thing: this happens _after_ the call to avformat_open_input, which is the function which can last a _long_ time in my case (recieving on UDP socket)!

To, on the ffmpeg side all is good :-)

I see following solutions:
  * Use the av_lockmgr_register() function to register a mutex. The most elegant solution. I saw that you somewhere do av_*_register_* at a static "constructor" - I think that would be a good place. You have its function declaration already in avcodec.java. Main question: Which java version are you targeting? If Java 5 is ok I would just use a ReentrantLock on the Java side.
  * Only do a locking around avcodec_open2 and friends.
  * Ignore this problem completely - avcodec_open2 will then spit out a error about not sufficient locking.

What do you think? I think I try to make a patch for the first solution ;-)

**Comment by saudet** [comment]
Yes, that sounds good. You can use anything that's available in Java 7 and
Android 4. Thanks for looking into this :)

**Comment by mifritscher** [comment]
Ok, somehow I seem to be too dumb for this it seems...

It seems that there is some "magic" on the pointers. If I start Java via Debug-Option in Eclipse it crashes, a normal run seems to work fine.

Output of a debug run:

> 	Line 3: Command: 0 number: 1 37810208 3523376
> 	Line 6: Command: 0 number: 2 37810216 3523408
> 	Line 11: Command: 1 number: 1 8790300043328 3523376
> 	Line 14: Command: 2 number: 1 8790300043328 3523376
> 	Line 49: Command: 1 number: 1 8790300043328 3523376
> 	Line 52: Command: 2 number: 1 8790300043328 3523376
> 	Line 57: Command: 1 number: 563403104 8790300043328 3523376

"Crash".  Something seems to have destroy my saved number. Big question: What?

Output of a normal run:

> 	Line 3: Command: 0 number: 1 35583152 4652352
> 	Line 6: Command: 0 number: 2 35583160 4652384
> 	Line 11: Command: 1 number: 1 8790337792064 4652352
> 	Line 14: Command: 2 number: 1 8790337792064 4652352
> 	Line 49: Command: 1 number: 1 8790337792064 4652352
> 	Line 52: Command: 2 number: 1 8790337792064 4652352
> 	Line 55: Command: 1 number: 1 8790337792064 4652352
> 	Line 58: Command: 2 number: 1 8790337792064 4652352
> 	Line 61: Command: 1 number: 1 8790337792064 4652352
> 	Line 64: Command: 2 number: 1 8790337792064 4652352


My try:
Temp.java:
```
import java.io.IOException;

import org.bytedeco.javacv.FFmpegFrameFilter;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameFilter;
import org.bytedeco.javacv.FrameGrabber;
import org.bytedeco.javacv.FrameRecorder;

public class Temp {

	public static void main(String[] args) throws IOException {
		Libr.init();

		FrameGrabber fg = new FFmpegFrameGrabber("video=Integrated Webcam");
		fg.setFormat("dshow");

		FrameFilter ff = new FFmpegFrameFilter(Test2.getTimestampOption("test", 10, 10, 480, "test2", "%"), 640, 480);
		FrameRecorder fr = new FFmpegFrameRecorder("C:\\temp\\blabb.avi", 0);
		fr.setVideoCodecName("mpeg2video");
		fr.setFormat("mpegts");
		fr.setImageWidth(640);
		fr.setImageHeight(448);
		fr.setVideoBitrate(8000000);

		fr.setFrameRate(30);

		fg.start();
		ff.start();
		fr.start();

		try {
			while (true) {
				System.out.println(fg.getFrameNumber() + " " + fg.getTimestamp() + " " + fg.getFrameRate() + " "
						+ fg.getImageWidth() + "x" + fg.getImageHeight() + " " + fg.getVideoCodec() + " "
						+ fg.getVideoBitrate());
				Frame source = fg.grabFrame();
				ff.push(source);
				Frame target = ff.pull();
				fr.record(target);
			}
		} catch (Exception e) {
			e.printStackTrace();
			fg.close();
			ff.close();
			fr.close();
		}
	}

	public static String getTimestampOption(final String prefix, final int x, final int y, final int pictureHeight,
			final String text, final String percent) {
		int fontSize = 36 * pictureHeight / 1000;
		if (fontSize < 4) {
			fontSize = 4;
		}

		final String ffmpegString;

		ffmpegString = "'" + prefix + " '" + percent + "{localtime}  " + percent + "{n} " + text;

		return "drawtext=fontfile=CourierCode-Bold.ttf: text=" + ffmpegString + ":\\x=" + x + "*w/1000: y=" + y
				+ "*h/1000: fontsize=" + fontSize + ": fontcolor=white@1.0: box=1: boxcolor=black@1.0";
	}
}

```

Libr.java:

```
package de.zft.maintelrob.ffmpegPacket.test;

import static org.bytedeco.javacpp.avcodec.av_lockmgr_register;
import static org.bytedeco.javacpp.avcodec.avcodec_register_all;
import static org.bytedeco.javacpp.avdevice.avdevice_register_all;
import static org.bytedeco.javacpp.avfilter.avfilter_register_all;
import static org.bytedeco.javacpp.avformat.av_register_all;
import static org.bytedeco.javacpp.avformat.avformat_network_init;
import static org.bytedeco.javacpp.avutil.av_log_format_line2;
import static org.bytedeco.javacpp.avutil.av_log_set_callback;

import java.util.HashMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import java.util.logging.Level;

import org.bytedeco.javacpp.LongPointer;
import org.bytedeco.javacpp.Pointer;
import org.bytedeco.javacpp.PointerPointer;
import org.bytedeco.javacpp.avcodec;
import org.bytedeco.javacpp.annotation.Cast;
import org.bytedeco.javacpp.avcodec.Cb_PointerPointer_int;
import org.bytedeco.javacpp.avutil.Callback_Pointer_int_String_Pointer;

public class Libr {
	private static Callback_Pointer_int_String_Pointer callback = new Callback_Pointer_int_String_Pointer() {
		@Override
		public void call(Pointer ptr, int level, String fmt, Pointer vl) {
			if (level > org.bytedeco.javacpp.avutil.AV_LOG_INFO || level < 0) {
				return;
			}
			byte line[] = new byte[1024];
			int[] print_prefix = new int[1];
			print_prefix[0] = 1;
			av_log_format_line2(ptr, level, fmt, vl, line, line.length, print_prefix);
			Level level2;
			if (level == org.bytedeco.javacpp.avutil.AV_LOG_INFO) {
				level2 = Level.INFO;
			} else {
				level2 = Level.WARNING;
			}
			String logString = new String(line).trim();
			if (logString.contains("deprecated pixel format used, make sure you did set range correctly")) {
				return;
			}
			if (logString.contains("Changing frame properties on the fly is not supported by all filters.")) {
				return;
			}
			System.out.println(level2.toString() + " " + "FROM libav: " + level + " " + logString);
		}
	};

	private static AtomicLong lockCounter = new AtomicLong(0);
	private static HashMap<Long, Lock> lockArray = new HashMap<>();
	private static Cb_PointerPointer_int lockCallback = new Cb_PointerPointer_int() {
		@Override
		public int call(@SuppressWarnings("rawtypes") @Cast("void**") PointerPointer mutex, @Cast("AVLockOp") int op) {
			LongPointer myMutex;
			Long number;
			Lock l;
			System.out.println("Locking: " + op);
			switch (op) {
			case avcodec.AV_LOCK_CREATE:
				myMutex = new LongPointer(1);
				number = lockCounter.incrementAndGet();
				System.out.println(
						"Command: " + op + " number: " + number + " " + mutex.address() + " " + myMutex.address());
				myMutex.put(0, number);
				mutex.put(myMutex);
				lockArray.put(number, new ReentrantLock());
				return 0;
			case avcodec.AV_LOCK_OBTAIN:
				myMutex = new LongPointer(mutex.get(0));
				number = myMutex.get(0);
				System.out.println(
						"Command: " + op + " number: " + number + " " + mutex.address() + " " + myMutex.address());
				l = lockArray.get(number);
				if (l == null) {
					System.err.println("Lock not found!");
					return -1;
				}
				l.lock();
				return 0;
			case avcodec.AV_LOCK_RELEASE:
				myMutex = new LongPointer(mutex.get(0));
				number = myMutex.get(0);
				System.out.println(
						"Command: " + op + " number: " + number + " " + mutex.address() + " " + myMutex.address());
				l = lockArray.get(number);
				if (l == null) {
					System.err.println("Lock not found!");
					return -1;
				}
				l.unlock();
				return 0;
			case avcodec.AV_LOCK_DESTROY:
				myMutex = new LongPointer(mutex.get(0));
				number = myMutex.get(0);
				System.out.println(
						"Command: " + op + " number: " + number + " " + mutex.address() + " " + myMutex.address());
				lockArray.remove(number);
				myMutex.deallocate();
				mutex.put(0, null);
				return 0;
			default:
				return -1;
			}
		}
	};

	public static void init() {
		// Register all formats and codecs
		av_register_all();
		avcodec_register_all();
		// Init network
		avformat_network_init();
		// Fuer ddshow etc.
		avdevice_register_all();
		// Fuer Filter
		avfilter_register_all();

		// Locking mechanismus
		av_lockmgr_register(lockCallback);
		 av_log_set_callback(callback);

	}

}

```


Seems to have something to do with the logging-callback - if I remove the setup of the callback it works.

**Comment by mifritscher** [comment]
The silly thing: even a completely empty log callback causes this! If I remove the av_log_set_callback, it works.

**Comment by saudet** [comment]
So, your callback FunctionPointer object is probably getting garbage
collected. You'll need to make sure that doesn't happen.

**Comment by mifritscher** [comment]
hmm, if I replace

`myMutex = new LongPointer(1);`

with

```
Pointer p = Pointer.malloc(8);
myMutex = new LongPointer(p);
```


and

`myMutex.deallocate();`

with

`Pointer.free(myMutex);`

it seems to work! I better don't as why *g* Does allocate use a special heap - or even the stack (which I don't hope)?

**Comment by saudet** [comment]
Then that's what getp garbage collected. Make sure the Java reference
doesn't become unreachable.

**Comment by saudet** [comment]
Please send a pull request when you get the mutex working! Thanks
