### ISSUE TITLE
add some way of memory debugging

### ISSUE THREAD

**Issue by pfn** [bytedeco/javacv#380]
This is particularly for android and a pretty big ask, I think.

I am making use of javacv now, and process live frames from the camera preview. After running for 5-10 minutes, the application crashes with an out of memory error in javacv code.

I have run through every single location in my sample that performs a `new` on any javacv object and have paired it with a corresponding `release()` or `deallocate()`. It still continues to crash.

Taking the standard android heap dumps is fruitless as it does not include any accounting for JNI-allocated memory.

OOMs look something like this:

```
 I  (11885) art     : Alloc partial concurrent mark sweep GC freed 1090(43KB) AllocSpace objects, 4(9MB) LOS objects, 40% free, 9MB/15MB, paused 468us total 68.078ms
 W  (11885) GraphicBufferMapper: lock(...) failed -12 (Out of memory)
 E  (11885) CpuConsumer: [ImageReader-1472x1104f23m30-11885-0] Unable to lock YCbCr buffer for CPU reading: Out of memory (-12)
```

Sometimes the OOM occurs in camera, sometimes in a javacv Mat allocation, etc.

**Comment by saudet** [comment]
If you call `System.gc()` periodically, does the problem go away? Of course performance will suffer, but it would confirm that it's a garbage collector related problem...

**Comment by saudet** [comment]
BTW, there already are facilities in JavaCPP for debugging memory issues. Please read this blog post:
http://bytedeco.org/news/2015/10/25/moving-to-java-se-7/
