### ISSUE TITLE
How do I find out the number of bytes produced by imencode()?

### ISSUE THREAD

**Issue by MC-2016** [bytedeco/javacv#383]
I am trying to use imencode(String, Mat, ByteBuffer, IntBuffer) to generate JPEG files with non-default quality level. After the method returns, both position and limit of the ByteBuffer object remain unchanged. I have verified that the data does get written to the buffer: I can save the buffer to a file (the entire thing, up to the buffer's capacity) and the result is a viewable JPEG file of the appropriate quality level.

How do I find out the number of bytes in the buffer?

**Comment by saudet** [comment]
We could use ByteBuffer this way if we allocate enough bytes beforehand, but we don't always know how much we need. It doesn't provide a way to return a newly allocated block of memory, or how much bytes we need if it's not enough. Just use the `BytePointer` overload instead.
