### ISSUE TITLE
rotate Frame while recording in onpreviewFrame

### ISSUE THREAD

**Issue by satyamub** [bytedeco/javacv#387]
Hi,

I want to rotate the frame when user tilt the screen, I am trying to search for the issues however found that most of the answers are related to **IplImage** however I got the sample, where it has org.bytedeco.javacv.Frame and its instance is given to record. can anyone suggest?

**Comment by saudet** [comment]
Just use FFmpegFrameFilter:
https://github.com/bytedeco/javacv/issues/164#issuecomment-134609198

**Comment by satyamub** [comment]
@saudet ...Not working

Two issue happened one is its stretching the image frames and it also flips the image view. What I actually wants that I can stream in portrait view as well because in the sample, only landscape view only available. can't i make that the preview view and actual image frame in portrait

**Comment by saudet** [comment]
If you don't want it to stretch, you have to specify the right output width and height.

**Comment by satyamub** [comment]
I am sorry to disturb you however how would i get the appropriate width and height? and this code flipping the image in landscape mode too...so not working properly

This is my code for onPreviewFrame

@Override
        public void onPreviewFrame(byte[] data, Camera camera) {
            if (audioRecord == null || audioRecord.getRecordingState() != AudioRecord.RECORDSTATE_RECORDING) {
                startTime = System.currentTimeMillis();
                return;
            }
            if (RECORD_LENGTH > 0) {
                int i = imagesIndex++ % images.length;
                yuvImage = images[i];
                timestamps[i] = 1000 * (System.currentTimeMillis() - startTime);
            }
            / get video data /
            if (yuvImage != null && recording) {
                ((ByteBuffer)yuvImage.image[0].position(0)).put(data);

                if (RECORD_LENGTH <= 0)
                    try {
                    Log.v(LOG_TAG, "Writing Frame");
                    long t = 1000 * (System.currentTimeMillis() - startTime);
                    if (t > recorder.getTimestamp()) {
                        recorder.setTimestamp(t);
                    }
                       
                    try {
                        filter.push(yuvImage);

                    Frame frame;
                    while ((frame = filter.pull()) != null) {
                        recorder.record(frame);
                    }
                    } catch (FrameFilter.Exception e) {
                        e.printStackTrace();
                    }
                   // recorder.record(yuvImage);
                } catch (FFmpegFrameRecorder.Exception e) {
                    Log.v(LOG_TAG, e.getMessage());
                    e.printStackTrace();
                }
            }
        }
    }

**Comment by satyamub** [comment]
As if its rotating the screen 270 degree when shooting in Landscape mode!!

**Comment by satyamub** [comment]
@saudet can you show me how to get IplImage from Frame so that I can rotate !!

**Comment by saudet** [comment]
With [OpenCVFrameConverter](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.html) as explained here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by satyamub** [comment]
@saudet Hi I can rotate the Iplimage however when I present that image to FFMPegRecorder, it does not accept it as, it accepts only, Frame... Can you please suggest how to do this rotation and support both portrait and landscape preview and image sending to RTMP!!

**Comment by saudet** [comment]
Like I said, use [OpenCVFrameConverter](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/OpenCVFrameConverter.html) as explained here:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
