### ISSUE TITLE
chromakey filter

### ISSUE THREAD

**Issue by FanSerg2** [bytedeco/javacv#388]
I have video with green background. I can use ffmpeg with chromakey filter in command line on Windows.
`ffmpeg -i video.mp4 -i punch_green.mp4 -filter_complex "[1:v]chromakey=0x12da11:0.2:0.2[chromakey_res];[0:v][chromakey_res]overlay=eof_action=pass[out]" -map "[out]" out.mp4`
This example gets second video, removes green background and then overlays it on first video.

How can I do this with FFmpegFrameFilter?

When do I try execute this code
`FFmpegFrameFilter filter = new FFmpegFrameFilter("chromakey=0x12da11:0.2:0.2", grabberEffect.getImageWidth(), grabberEffect.getImageHeight());`
I take next error 
`Error: No such filter: 'chromakey'`

**Comment by saudet** [comment]
This works just fine here. I get no errors.

**Comment by FanSerg2** [comment]
I downloaded and installed javacpp-presets module with gradle:

`compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'`

Am I using the latest version ffmpeg (3.0.1)?

If I write
`compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.0.1-1.1', classifier: 'android-arm'`
I am getting an error:
`Failed to resolve: org.bytedeco.javacpp-presets:ffmpeg:3.0.1-1.1`

How I can see the version ffmpeg in my project?

**Comment by saudet** [comment]
Try to install it manually: https://github.com/bytedeco/javacpp-presets/#manual-installation

**Comment by FanSerg2** [comment]
I added next files:
```
    compile files('libs/ffmpeg-android-arm.jar')
    compile files('libs/ffmpeg.jar')
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')

```
and get this error :
```
04-19 11:46:33.119 8096-8096/? W/System.err: org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_parse_ptr()
04-19 11:46:33.134 8096-8096/? W/System.err:     at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:232)
04-19 11:46:33.134 8096-8096/? W/System.err:     at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)
.......
04-19 11:46:33.134 8096-8096/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)

```

**Comment by FanSerg2** [comment]
chromakey filter was added in ffmpeg version 3.0
https://github.com/FFmpeg/FFmpeg/blob/master/Changelog

**Comment by saudet** [comment]
JavaCV 1.2 uses FFmpeg 3.0 so this should now work. Enjoy!
