### ISSUE TITLE
Compile and import to Android Studio

### ISSUE THREAD

**Issue by taprm** [bytedeco/javacv#392]
Hello!
I find sample for streaming by rtmp with JavaCV and FFMpeg, but sample is deprecated and use older version JavaCV.
How i create new Android Studio project and import all required libraries and files (for beginners as I'm)?
I found many posts where using *.so files. How i get *.so files for last version required libs.

Regards.

**Comment by saudet** [comment]
This one still works fine with the latest version of JavaCV:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java
