### ISSUE TITLE
imread function not found

### ISSUE THREAD

**Issue by k3170makan** [bytedeco/javacv#397]
Hi Guys,

Been tinkering with the Face Recognition example included here https://github.com/bytedeco/javacv/blob/master/samples/OpenCVFaceRecognizer.java . It references the imread function but I can't seem to find it in the binaries included in the javacv project.

Where do I get this function? and alternatively how do I convert a raw JPEG buffer to a JavaCV Mat object? 

Kind Regards

**Comment by saudet** [comment]
I found it here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_imgcodecs.html#imread%28org.bytedeco.javacpp.BytePointer,%20int%29
