### ISSUE TITLE
How to solve this problem? http://stackoverflow.com/questions/28775931/muxing-android-mediacodec-encoded-h264-packets-into-rtmp

### ISSUE THREAD

**Issue by wooden1985** [bytedeco/javacv#398]

**Comment by saudet** [comment]
There's already a `recordPacket()` method for that, so please try to use that: https://github.com/bytedeco/javacv/pull/372

**Comment by wooden1985** [comment]
recordPacket()? how can i get it?

**Comment by saudet** [comment]
It's on the master branch.

**Comment by saudet** [comment]
BTW, FFmpeg 6.0 now supports hardware accelerated encoding using MediaCodec, so we don't need to use its API directly anymore. Please give it a try with the snapshots: http://bytedeco.org/builds/
