### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x2f0015 in tid 18380, Face Recognizer

### ISSUE THREAD

**Issue by nikoskoutr** [bytedeco/javacv#400]
I am using javacv with android studio, everything is working good, except for the Face Recognizer.
I get the above error when i declare a FaceRecognizer and when i try to get a Eigen/Fisher/LBPH recognizer.

**Comment by saudet** [comment]
Could you provide a bit more details? Which platform, version, etc

**Comment by nikoskoutr** [comment]
Excuse me for the lack of information!
So i am using javacv 1.1 with android studio 2.0. I used gradle to import and compile javacv from maven central and i put all the .so files in a directory called jniLib in my app directory because i had unsatisfied link error.
Everything i use from the javacv library (Mat, normalize function etc) works fine, but when i use anything from the opencv_face it gives the error i put on the title.
I use: 
gradle 2.0 
sdk tools 25.1.1 
sdk platform tools 23.1
sdk build tools 23.0.3

Thanks for your response and for your help!

**Comment by nikoskoutr** [comment]
Update as i examined the logs better i get these messages also:
libjniopencv_core.so: unused DT entry: type 0x1d arg 0x4f533
libjniopencv_imgproc.so: unused DT entry: type 0x1d arg 0x248c8
libjniopencv_imgcodecs.so: unused DT entry: type 0x1d arg 0x3b34

**Comment by saudet** [comment]
Does the same thing happen, for example, on the Android emulator? Or is it a problem only with your device?

**Comment by nikoskoutr** [comment]
I have tried it on two different devices, i get the error on both of them.

**Comment by saudet** [comment]
Right, but what about the emulator?

**Comment by nikoskoutr** [comment]
I get the same problem from the emulator too and on another device.
When I tried to get a fisherface recognizer I got an error that there should be two classes for it to work. So I guess it begins to work. When I provide the two classes, I get the error again.

**Comment by saudet** [comment]
Does the same thing happen with the most recent update to 1.2-SNAPSHOT?

**Comment by nikoskoutr** [comment]
I had some computer issues, sorry for the late reply.
Is there a place i can download 1.2-SNAPSHOT? Or should i build it from source?
And if so, is there a guide for doing so? I'm currently trying to build it from source but i am running into many errors which i'm trying to resolve.

**Comment by saudet** [comment]
Please try to build from source. What errors are you getting?

**Comment by nikoskoutr** [comment]
Most of my errors are from my inexperience with the build process.
I got through most of them but the last one i get is while building javacv and i get this:

`Tests in error: 
  testOpenCVFrameConverter(org.bytedeco.javacv.FrameConverterTest): no jniopencv_core in java.library.path
  testAndroidFrameConverter(org.bytedeco.javacv.FrameConverterTest): org.bytedeco.javacpp.helper.opencv_core$AbstractArray`

Is there a known solution to this ?

**Comment by saudet** [comment]
Make sure to follow the guide here:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#android-arm-and-x86

**Comment by saudet** [comment]
@nikoskoutr Also, the tests won't run if you specify Android as the platform, so either specify another platform, or skip the tests with `-Dmaven.test.skip`.

**Comment by nikoskoutr** [comment]
After a lot of learning, i managed to build 1.2 for android!
I still get the same error though:
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 17254 (AsyncTask #5)`

**Comment by saudet** [comment]
Probably a problem with OpenCV though... Could you report that upstream and
see what they say?

**Comment by nikoskoutr** [comment]
I will talk with them!
Thanks a lot for your help!

**Comment by saudet** [comment]
Please post a link to the upstream bug report if you report it, for reference, thanks!

**Comment by p-tricky** [comment]
Did you guys ever figure out what the issue was?  I get sigsegv when I train my lbph face recognizer, but it's been pretty hard to debug because it only happens occasionally.

**Comment by saudet** [comment]
@p-tricky Would help to have some code to look at

**Comment by p-tricky** [comment]
@saudet Sorry I think it was an issue in my code.  I probably should have waited to comment.  Thanks so much for providing these resources.  They've been super helpful!

**Comment by saudet** [comment]
JavaCV 1.3 has just been released. Could you guys give it a try and let me know if it works? Thanks!

**Comment by nikoskoutr** [comment]
I am sorry i did not answer earlier, i have tried it with javacv 1.3 and it is working without any problem! Thank you a lot. Although after all that time, it is also working with previous versions too. So i think i may have done something wrong with my code. Thank you for trying to help me and sorry for the inconvenience.

**Comment by saudet** [comment]
Awesome! Thanks for the feedback.
