### ISSUE TITLE
Best way to resize a Frame (IplImage )

### ISSUE THREAD

**Issue by rpgomes** [bytedeco/javacv#402]
Hello,

I need some help.
I'm capturing an rtsp stream gram an axis camera in CIF and I need to resize the image to 4CIF.

What is the best way to do that? and What function should I call?

IplImage frame = grabber.grab();
IplImage imagetmp = IplImage.create(width, height, frame.depth(), frame.nChannels());

//resize frame to 4CIF

present imagetmp

**Comment by saudet** [comment]
cvResize() should do the trick. Looks good?

**Comment by rpgomes** [comment]
I making some tests ans it appears that it consumes a lot of CPU.

with a intel Xeon CPU E5.2630 v3 @2.4GHz, 
capturing an rtsp input signal from an axis cam @ 320x180, 20 fps

I'm grabing the frame like that:
IplImage frame = grabber.grab();

and resizing it to 1920x1080
if I use 

IplImage imagetmp = IplImage.create(1920, 1080, frame.depth(), frame.nChannels());
imagetmp.copyFrom(frame.getBufferedImage());

I get consumption of 60% of CPU
if I get the buffered image from the Frame and use xuggler to rescale the consumption drops to 30%.

converter = ConverterFactory.createConverter(tmp, IPixelFormat.Type.YUV420P);
IVideoPicture tmpPic = converter.toPicture(frame.getbufferedImage(), frameTime.getTime()*1000);
videoResampler = IVideoResampler.make(width, height, IPixelFormat.Type.YUV420P, tmpPic.getWidth(), tmpPic.getHeight(), IPixelFormat.Type.YUV420P);
videoResampler.resample(sharedImage, tmpPic);

How can I improve the CPU consumption using only javaCv?

**Comment by saudet** [comment]
If you're looking for something fast, just use OpenGL: That's what it's for.

**Comment by saudet** [comment]
FYI, Xuggler uses FFmpeg, so if you use `FFmpegFrameFilter`, you should get the same performance with JavaCV as well. As you found out yourself though, it's not exactly fast either.

**Comment by rpgomes** [comment]
Can you show me an example of the usage of FFmpegFrameFilter?

**Comment by saudet** [comment]
Sure: https://github.com/bytedeco/javacv/issues/164#issuecomment-134609198  If you're like to contribute some documentation, sample, etc for that, it would be very welcome.
