### ISSUE TITLE
Expected speed for grabber.grab()? It's taking 30 ms...

### ISSUE THREAD

**Issue by jimmyryan15** [bytedeco/javacv#408]
Windows 10, 64 bit, 8 core box with high end webcam, capturing at 640 x 480 (changing image size doesn't improve the performance by much)

Getting a frame is taking approx 30 ms. I'm using FrameGrabber.createDefault, it's returning me a VideoInputFrameGrabber.

The code is super minimal. A simple loop. grabber.grab() with System.currentTimeMillis() before and after.

If this is normal so be it. I was just surprised because after adding some basic processing you get to the 50 to 100ms range (yes I am processing the images in a different thread, I mean the overall delay in which the real-time processing can occur) which ultimately yields as bad as 10 frames per second of processing.

Thanks for any insight.

**Comment by saudet** [comment]
Yeah, cameras usually do 30 FPS, which means we have to wait about 33 ms for each frame. That's perfectly normal.
