### ISSUE TITLE
FFmpegFrameRecorder setFormat H265/HEVC

### ISSUE THREAD

**Issue by peter9870** [bytedeco/javacv#41]
I'd like to change the video codec to H265 (AV_CODEC_ID_H265) instead of (AV_CODEC_ID_MPEG4) for large resolution videos. The following gives me avcodec_find_encoder() error, Video codec not found. How can I add this video codec? 

recorder.setVideoCodec(org.bytedeco.javacpp.avcodec.AV_CODEC_ID_H265);
recorder.setFormat("mp4");
							recorder.setPixelFormat(org.bytedeco.javacpp.avutil.AV_PIX_FMT_YUV420P); 
							recorder.setFrameRate(24);
							recorder.setVideoQuality(0);

**Comment by saudet** [comment]
FYI, work started for x265 support here: https://github.com/bytedeco/javacpp-presets/commit/778d34b5b16832085fb3a417e8d1315ca92f6000

**Comment by peter9870** [comment]
Thanks Sam, I started work on this too but lost track.  I'll try and have a look again.

**Comment by saudet** [comment]
x265 is now included in version 0.11. Thanks for your effort, it helped a lot!! Let me know if you see anything wrong with the current build.

**Comment by peter9870** [comment]
Hi Sam, 

Just compiled latest version 0.11 and when calling `recorder.setVideoCodec(org.bytedeco.javacpp.avcodec.AV_CODEC_ID_HEVC);` I get the dreaded  org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.

I'm having a look into it.

**Comment by saudet** [comment]
Ok, thanks! Let me know what you find out.

**Comment by godzillad** [comment]
Hi Peter, did you find the solution. I am facing the same issue. I am using version 0.11 on Nexus 5 with lollipop.

**Comment by saudet** [comment]
Could you guys try on Linux or Mac OS X and let me know if it works or not? It would help, thanks

**Comment by godzillad** [comment]
I dont have access to any Macs, I will try on Linux and let you know.

**Comment by peter9870** [comment]
I didn't find a solution but the codecs (encoder & decoder) were definitely there. But it still would not load. 

I'm away at the moment but didn't try on Linux. Only android.

**Comment by godzillad** [comment]
I tried on Linux (ubuntu 14.04 LTS). I converted a h264 video to HEVC using FFmpegFrameGrabber and FrameFrameRecorder and it works.

**Comment by saudet** [comment]
So it works on Linux, but not on Android? Strange...

**Comment by ShihabSoft** [comment]
A bit of strangeness is remaining.
As android considered as a flavor of UNIX.

Let me check it out on Mac.

**Comment by saudet** [comment]
Does the same thing happen with FFmpeg 2.7 and x265 1.5 recently updated in the presets?

**Comment by peter9870** [comment]
Latest git downloaded and built.

This does not work
`recorder.setVideoCodec(avcodec.AV_CODEC_ID_HEVC);`

But this appears to. Very odd.
`recorder.setVideoCodecName("H265");`

**Comment by saudet** [comment]
Sounds like a bug to report upstream :)

**Comment by gordonpro** [comment]
Is HEVC encoder supported?
