### ISSUE TITLE
FFMPEGFrameGrabber example

### ISSUE THREAD

**Issue by rpgomes** [bytedeco/javacv#410]
Hello,

I'm experiment to use FFMPEGFrameGrabber to record the stream that I capture to a file,
the requirement is to make a mjpeg file,
but when I try to start the recording I get an 
```
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
```
my code:
```java
FFmpegFrameRecorder ffr = new FFmpegFrameRecorder("myFile.mp4",dim.getWidth(),dim.getHeight(), 0);
			ffr.setFormat("mjpeg");
			ffr.setVideoCodec(8);//MJPEG I think
			try {
				ffr.start();
			} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
```
What I'm doing wrong, can someone give me some parametrization pointers?

**Comment by saudet** [comment]
I don't think there is such a thing as the "mjpeg" format. It's not in the list returned by `ffmpeg -formats` anyway, so call `av_oformat_next()` in a loop to make sure it's in the list.

**Comment by saudet** [comment]
Oh, actually it's in the list. I get this error message in the log:
```
Error: [mjpeg @ 0x7f56980ac200] Specified pixel format yuv420p is invalid or not supported
```
So simply call `setPixelFormat()` with a supported pixel format such as `AV_PIX_FMT_YUVJ420P` before `start()`.

**Comment by rpgomes** [comment]
Ok,

with the setPixelFormat(avutil.AV_PIX_FMT_YUVJ420P);
I managed to start.

I'm making some mjpeg experiemnts, and I configured an FFserver and test with success with the ffmpeg directly:
ffmpeg -rtsp_transport tcp -i "rtsp://root:pass@IP/axis-media/media.amp" -vcodec mjpeg http://ffserverIP:8090/feed1.ffm
and managed to play in an html< IMG> tag


I'm trying to do the same with FfmpegFrameRecorder:
my code:

ffr = new FFmpegFrameRecorder("http://" + "FFSERVER_IP"  + ":" + 8090 + "/feed1.ffm",dim.getWidth(),dim.getHeight(), 0);
			ffr.setFormat("mjpeg");
			ffr.setVideoCodec(8);//MJPEG
			ffr.setPixelFormat(avutil.AV_PIX_FMT_YUVJ420P);
			
			try {
				ffr.start();
			} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

this return this output:
Output #0, mjpeg, to 'http://192.168.0.69:8090/feed1.ffm':
    Stream #0:0: Video: mjpeg, yuvj420p, 352x288, q=2-31, 400 kb/s, 5 tbn, 5 tbc

but when I record the frame:
try {
							ffr.record(f);
						} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
I get this exception:
org.bytedeco.javacv.FrameRecorder$Exception: av_write_frame() error -10054 while
 writing video frame.
        at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecord
er.java:800)
        at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.ja
va:686)
        at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.ja
va:679)

Did I need to make more configuration in FFMPEGFrameRecorder?

**Comment by saudet** [comment]
Check the log, it's going to contain more information.

**Comment by saudet** [comment]
BTW, issue https://github.com/bytedeco/javacv/issues/267 might be related.

**Comment by rpgomes** [comment]
Sorry I didn't understand what log should I check ? and where is it?
the log I post was from the JVM

**Comment by saudet** [comment]
What do you get as output instead of the following?
```
Output #0, mjpeg, to 'http://192.168.0.69:8090/feed1.ffm':
    Stream #0:0: Video: mjpeg, yuvj420p, 352x288, q=2-31, 400 kb/s, 5 tbn, 5 tbc
```

**Comment by rpgomes** [comment]
That is all I'm getting as output from javacv when I making the ffmpeframerecorder.start().

Then I get the error on recording the frame.

usin ffmpeg directly I get this output:
Output #0, ffm, to 'http://192.168.0.69:8090/feed1.ffm':
  Metadata:
    title           : Media Presentation
    creation_time   : 2016-05-19 12:25:39
    encoder         : Lavf57.3.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 352x288 [SAR 16:11 DAR 16:9], q=2-3
1, 64 kb/s, 25 fps, 1000k tbn, 5 tbc
    Metadata:
      encoder         : Lavc57.5.100 mjpeg
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))

**Comment by saudet** [comment]
So, you want to use the ffm format, right? You're not going to get that if you call  `setFormat("mjpeg")`...

**Comment by rpgomes** [comment]
yep that make the trick, 
you're the best :)

Thanks

**Comment by saudet** [comment]
FYI, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
