### ISSUE TITLE
Asking about the performance of grabImage() in Android

### ISSUE THREAD

**Issue by vxhviet** [bytedeco/javacv#414]
Hi everyone,

Currently I still haven't managed to make javaCV running for Android however I would like to ask about the performance of grabImage() as in:

```
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(mVideoPath);

        try {
            grabber.start();
            grabber.setFrameNumber((int) (currentVideoPosition * grabber.getFrameRate() / 1000)); //get current frame base on framerate
            Frame frame = grabber.grabImage();
            AndroidFrameConverter androidFrameConverter = new AndroidFrameConverter();
            Bitmap bitmap = androidFrameConverter.convert(frame);

            return  bitmap;
        }
        catch (Exception e) {
            e.printStackTrace();
        }finally {
            try {
                grabber.stop();
            } catch (FrameGrabber.Exception e) {
                e.printStackTrace();
            }
        }
```

Due to my specific requirement I would like to have  this process:

```
Frame frame = grabber.grabImage();
AndroidFrameConverter androidFrameConverter = new AndroidFrameConverter();
Bitmap bitmap = androidFrameConverter.convert(frame);
```

finish in 20 milliseconds or less. If anyone happens to have javaCV running in Android could quickly test this and reply I would be very much appreciated.

One side question, @saudet would you mind telling which FFmpeg version coming with this lib?

Thank you so much for your time.

**Comment by vxhviet** [comment]
For anyone curious, about 300-400 milliseconds.

**Comment by saudet** [comment]
There's some hint about what you can do on this page:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/AndroidFrameConverter.html

**Comment by vxhviet** [comment]
Thank you @saudet,

Can you elaborate more about:

> For best performance, convert first your data to and from RGBA with optimized functions from FFmpeg or OpenCV.

The goal is to display the `Bitmap` in Java side so I would assume even whatever optimized function in FFmpeg we can call then we still need to convert it to `Bitmap`, correct?

**Comment by saudet** [comment]
No, you could use OpenGL ES for display.

**Comment by vxhviet** [comment]
Thanks you so much for your reply. So I would need to use OpenGL ES to display the `byte[]` and can I do in the Java side or would I need to use NDK for that?

Thanks again for your help.

**Comment by saudet** [comment]
https://developer.android.com/training/graphics/opengl/index.html

**Comment by vxhviet** [comment]
Hi @saudet , thank you so much for your instruction. One of the advise I've been received regarding this matter is:

> it would be more efficient to decode video frames directly to a Surface created from the TextureView's SurfaceTexture, but I don't know if JavaCV supports that. 

Looking at JavaCV's package summary, I found the `CanvasFrame` and `GLCanvasFrame` seem to be the most relevant. However they seem to be used for normal Java as they directly extended from the `awt` which is not available in Android.

So I would like to ask is there a quick way to decode the frame directly to a `Surface` in JavaCV?

Btw: as long as this problem get solved, I would like to contribute a small wiki article on this matter. Currently, it's very hard to find any resource on this for both JavaCV as well as OpenGL ES.

Thank you again for your time.

**Comment by vxhviet** [comment]
Hi @saudet, I have a quick question I would like to ask. Do we need to allocate the content of the `ByteBuffer` in the `Frame` retrieved by `FFmpegFrameGrabber ` to a new `ByteBuffer` before we can use it?

```java
Frame frame = mGrabber.grabImage();
ByteBuffer bb = (ByteBuffer)frame.image[0]; //I suppose this will return the ByteBuffer containing the image data
Log.d(TAG, "byteBuffer: get:" + bb.get(3840)); //3840 is the stride of the image
```

The above operation always return error. 

I see in your `AndroidFrameConverter` you allocate the content of the `ByteBuffer` to a new one before copying it into a `Bitmap`

```java
public Bitmap convert(Frame frame) {
        ....
            ByteBuffer in = (ByteBuffer)frame.image[0];
            int width = frame.imageWidth;
            int height = frame.imageHeight;
            int stride = frame.imageStride;
            int rowBytes = this.bitmap.getRowBytes();
            int y;
            int x;
            byte B;
            if(frame.imageChannels == 1) {
                if(this.buffer == null || this.buffer.capacity() < height * rowBytes) {
                    this.buffer = ByteBuffer.allocate(height * rowBytes);
                }

                for(y = 0; y < height; ++y) {
                    for(x = 0; x < width; ++x) {
                        B = in.get(y * stride + x);
                        this.buffer.put(y * rowBytes + 4 * x, B);
                        this.buffer.put(y * rowBytes + 4 * x + 1, B);
                        this.buffer.put(y * rowBytes + 4 * x + 2, B);
                        this.buffer.put(y * rowBytes + 4 * x + 3, (byte)-1);
                    }
                }

                this.bitmap.copyPixelsFromBuffer(this.buffer.position(0));
            } else if(frame.imageChannels == 3) {
                if(this.buffer == null || this.buffer.capacity() < height * rowBytes) {
                    this.buffer = ByteBuffer.allocate(height * rowBytes);
                }

                for(y = 0; y < height; ++y) {
                    for(x = 0; x < width; ++x) {
                        B = in.get(y * stride + 3 * x);
                        byte G = in.get(y * stride + 3 * x + 1);
                        byte R = in.get(y * stride + 3 * x + 2);
                        this.buffer.put(y * rowBytes + 4 * x, R);
                        this.buffer.put(y * rowBytes + 4 * x + 1, G);
                        this.buffer.put(y * rowBytes + 4 * x + 2, B);
                        this.buffer.put(y * rowBytes + 4 * x + 3, (byte)-1);
                    }
                }

                this.bitmap.copyPixelsFromBuffer(this.buffer.position(0));
            } else {
                this.bitmap.copyPixelsFromBuffer(in.position(0));
            }

            return this.bitmap;
        ...
```

So my question is very simple. Is the `ByteBuffer` retrieved from the `Frame` via this:

`ByteBuffer bb = (ByteBuffer)frame.image[0];` 

already content the image data? I need to pass this `ByteBuffer` into Open GL ES to convert it into a texture.

Thank you so much for your time.

**Comment by saudet** [comment]
Yes, that's what we need to use as a texture for OpenGL ES.

**Comment by vxhviet** [comment]
Hi @saudet, thanks alot for your response. I won't bother you with the OpenGL stuff but could you take a minute to see if the way I'm passing this `ByteBuffer` into my renderer is correct.

In my `VideoActivity` where I repeatedly extract video's `Frame` and then send this to my `MyGLRenderer2` to be converted to OpenGLES's texture: 

```java
...
mGLSurfaceView = (GLSurfaceView)findViewById(R.id.gl_surface_view);
mGLSurfaceView.setEGLContextClientVersion(2);
mRenderer = new MyGLRenderer2(this);
mGLSurfaceView.setRenderer(mRenderer);
mGLSurfaceView.setRenderMode(GLSurfaceView.RENDERMODE_CONTINUOUSLY);
...

private void grabCurrentFrame(final long currentPosition){
    if(mCanSeek){
        new AsyncTask(){

            @Override
            protected void onPreExecute() {
                super.onPreExecute();
                mCanSeek = false;
            }

            @Override
            protected Object doInBackground(Object[] params) {
                try {
                    Frame frame = mGrabber.grabImage();
                    setCurrentFrame((ByteBuffer)frame.image[0]);
                }
                catch (Exception e) {
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            protected void onPostExecute(Object o) {
                super.onPostExecute(o);
                mCanSeek = true;
                }
            }
        }.execute();
    }
}

private void setCurrentFrame(ByteBuffer buffer){
    mRenderer.setTexture(buffer); //is this one correct?
}
```

And in `MyGLRenderer2` I receive it like this:

```java
private ByteBuffer mCurrentBuffer;

public void setTexture(ByteBuffer buffer){
    mCurrentBuffer = buffer.duplicate();
    mCurrentBuffer.position(0);
}
``` 

Thank you so much for your time.
