### ISSUE TITLE
avformat_open_input() error -13, Has setFormat() been called?

### ISSUE THREAD

**Issue by vxhviet** [bytedeco/javacv#416]
Hi @saudet,

Sorry for troubling you again. Finally I've been able to set up JavaCV in Android Studio (version 1.1) using the add `.jar` method so my *build.gradle* looks like this:

```groovy
compile files('libs/javacpp.jar')
compile files('libs/javacv.jar')
compile files('libs/ffmpeg.jar')
compile files('libs/ffmpeg-android-arm.jar')
```

I'm trying to use the `FFmpegFrameGrabber` as below:

```java
        String path = "/storage/emulated/0/DCIM/Camera/VID_20160422_173902.mp4";
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(path);
        grabber.setFormat("mp4");

        try {
            grabber.start();
            grabber.setFrameNumber((int) (1000 * grabber.getFrameRate() / 1000)); //get current frame based on framerate
            Frame frame = grabber.grabImage();
            AndroidFrameConverter androidFrameConverter = new AndroidFrameConverter();
            Bitmap bitmap = androidFrameConverter.convert(frame);
            imgView.setImageBitmap(bitmap);
        }
        catch (Exception e) {
            e.printStackTrace();
        }finally {
            try {
                grabber.stop();
            } catch (FrameGrabber.Exception e) {
                e.printStackTrace();
            }
        }
```

However I got hit with this error at `grabber.start()`:

```
org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -13: Could not open input "/storage/emulated/0/DCIM/Camera/VID_20160422_173902.mp4". (Has setFormat() been called?)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:432)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:380)
	at co.example.test.MainActivity.onCreate(MainActivity.java:27)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

I've even tried to use the *ffmpeg-android-arm.jar* and *ffmpeg.jar* from JavaCV 1.2 but it just crash with another stack trace. I've read this #68, but my video file is neither big or long (18.37mb, 720p, 12 seconds). 

What would possibly the solution for my issue? Thank you so much for your time.

**Note:** for anyone still having trouble setting JavaCV up in Android Studio, I've created a [Gist]  (https://gist.github.com/vxhviet/cd39621ae768be07dca30e399c36c034) providing step by step instruction.

**Comment by vxhviet** [comment]
Sorry this issue has been resolved, nothing related to FFmpeg at all, thank you for your time.

**Comment by Nitinvermaa1** [comment]
@vxhviet .
Hope you are doing good.

I come across below error when i am trying to access OEM device (EasyCap) to grab frame form Set top box
Code:
FFmpegFrameGrabber grabber =new FFmpegFrameGrabber("video=\"OEM Device\":audio=\"OEM Device\"");

    grabber.setFormat("dshow");
    grabber.setImageWidth(640);
    grabber.setImageHeight(480);
    grabber.start();

    CanvasFrame frame = new CanvasFrame("Screen Capture");
    while (frame.isVisible()) {
        frame.showImage(grabber.grab());
    }
    frame.dispose();
    grabber.stop();
Error:
Exception in thread "main" org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -5: Could not open input "video="OEM Device":audio="OEM Device"". (Has setFormat() been called?)
at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:429)
at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:377)
at stbTesting.FFmpegEasyCap.main(FFmpegEasyCap.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
[dshow @ 000000000050c760] Could not find video device with name ["OEM Device"] among source devices of type video.
[dshow @ 000000000050c760] Could not find video device with name ["OEM Device"] among source devices of type video.

Please help me out to resolve the above issue
From command line using ffmpeg i am able to play as well as record the Set top box video using easycap

For Direct Play:

ffplay -f dshow -crossbar_video_input_pin_number 1 -crossbar_audio_input_pin_number 2 -rtbufsize 500000k -framerate 29.97 -i video="OEM Device":audio="OEM Device"

For Recording:

ffmpeg -f dshow -crossbar_video_input_pin_number 1 -crossbar_audio_input_pin_number 2 -rtbufsize 500000k -framerate 29.97 -i video="OEM Device":audio="OEM Device" C:\stbtestVideo\Test.avi

**Comment by vxhviet** [comment]
Sorry, I moved away from Java CV along time ago. If you just need simple frame extraction, then I recommend you use [FFmpegMediaMetadataRetriever](https://github.com/wseemann/FFmpegMediaMetadataRetriever) or if you prefer using FFmpeg command line, then use [ffmpeg-android-java](http://writingminds.github.io/ffmpeg-android-java/) instead.

In my case, my requirement is quite strict so I have to work directly with Android's native `MediaCodec`.

Hope this is helpful.

**Comment by chan1600** [comment]
I also faced with the same problem, and just for reference if anyone has the same issue. This is my solution.
Please check     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>  has set in AndroidManifest.xml
and also you can add in onCreate
        if (ActivityCompat.checkSelfPermission(this,
                Manifest.permission.READ_EXTERNAL_STORAGE)
                != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE
            }, 10);
        }

**Comment by KamranB** [comment]
@chan1600 Thanks for reminding me that I am an idiot. Thanks btw (on a serious note also)

**Comment by ajay-java** [comment]
I'm trying to start video Streaming on two cameras Simultaneously but some times I'm facing below issue.

org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -1482175992: Could not open input "<rtsp_link>". (Has setFormat() been called?)

Sometimes streaming get's started on both the cameras and then Application gets stopped suddenly.

#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
h264 (Constrained Baseline), yuv420p, 240x160, q=2-31, 800 kb/s, 24 fps, 90k tbn, 24 tbc
[libx264 @ 0000022388bc5480] -qscale is ignored, -crf is recommended.
[libx264 @ 0000022388bc5480] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000022388bc5480] profile High, level 1.2, 4:2:0, 8-bit
[libx264 @ 0000022388bc5480] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=2 sliced_threads=1 slices=2 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=49.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[hls @ 0000022388f05080] Opening '/tmp/CCTV2/240p/CCTV2_2400.ts' for writing
Output #0, hls, to '/tmp/CCTV2/240p/CCTV2_240.m3u8':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 240x160, q=2-31, 800 kb/s, 24 fps, 90k tbn, 24 tbc
[libx264 @ 0000022388bbf940] -qscale is ignored, -crf is recommended.
[libx264 @ 0000022388bbf940] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000022388bbf940] profile High, level 1.2, 4:2:0, 8-bit
[libx264 @ 0000022388bbf940] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=2 sliced_threads=1 slices=2 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=49.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[hls @ 0000022388f06380] Opening '/tmp/CCTV1/240p/CCTV1_2400.ts' for writing
Output #0, hls, to '/tmp/CCTV1/240p/CCTV1_240.m3u8':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 240x160, q=2-31, 800 kb/s, 24 fps, 90k tbn, 24 tbc
[libx264 @ 0000022388bc0280] -qscale is ignored, -crf is recommended.
[libx264 @ 0000022388bc0280] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000022388bc0280] profile High, level 1.2, 4:2:0, 8-bit
[libx264 @ 0000022388bc0280] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=2 sliced_threads=1 slices=2 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc=crf mbtree=0 crf=35.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[hls @ 0000022388f069c0] Opening '/tmp/CCTV1/360p/CCTV1_3600.ts' for writing
Output #0, hls, to '/tmp/CCTV1/360p/CCTV1_360.m3u8':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 240x160, q=2-31, 800 kb/s, 24 fps, 90k tbn, 24 tbc
[hls @ 0000022388f06380] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 3750 >= 3750
[hls @ 0000022388f06380] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 11250 >= 11250

Can anyone please help me in this??


I'm Using Java openJDK 11 version with spring boot 2.x version.
