### ISSUE TITLE
Can I combine two videos in pip mode?

### ISSUE THREAD

**Issue by shiweige** [bytedeco/javacv#418]
What I want is to add one small video overlay another background video, and they should play together.
Can I use javacv to achieve it? I can't find any doc to implement it.
Thanks.

**Comment by saudet** [comment]
Should be possible with [FFmpegFrameFilter](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FFmpegFrameFilter.html)

**Comment by saudet** [comment]
Actually, not yet. We need to add support for more than one input: https://github.com/bytedeco/javacv/issues/389

Marking as a duplicate, but contributions are welcome! Let me know you are interested in implementing this feature and let me know if you run into any problems! Thanks

**Comment by shiweige** [comment]
@saudet Thanks for the response and I'm sorry to hear it.
I'm not familiar with FFmpeg and afraid it is hard for me to implement this feature.
Do you have any schedule to support it?

**Comment by saudet** [comment]
FYI, we can use the `movie` filter for that, and it should now work as expected with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/
