### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lorg/bytedeco/javacpp/opencv_imgcodecs

### ISSUE THREAD

**Issue by anita248** [bytedeco/javacv#425]
Hi,
right now I´m developing an android app where I want to use javacv. I followed the manual installation, but I get the following exception:

> 06-01 11:52:03.185: E/AndroidRuntime(27526): FATAL EXCEPTION: main
> 06-01 11:52:03.185: E/AndroidRuntime(27526): Process: com.example.sample, PID: 27526
> 06-01 11:52:03.185: E/AndroidRuntime(27526): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/bytedeco/javacpp/opencv_imgcodecs;
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at com.example.sample.MainActivity.smooth(MainActivity.java:45)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at com.example.sample.MainActivity.onCreate(MainActivity.java:21)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.app.Activity.performCreate(Activity.java:6285)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.app.ActivityThread.access$900(ActivityThread.java:154)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.os.Handler.dispatchMessage(Handler.java:102)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.os.Looper.loop(Looper.java:224)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at android.app.ActivityThread.main(ActivityThread.java:5526)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at java.lang.reflect.Method.invoke(Native Method)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> 06-01 11:52:03.185: E/AndroidRuntime(27526): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.bytedeco.javacpp.opencv_imgcodecs" on path: DexPathList[[zip file "/data/app/com.example.sample-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.sample-2/lib/arm, /data/app/com.example.sample-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    ... 14 more
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    Suppressed: java.lang.ClassNotFoundException: org.bytedeco.javacpp.opencv_imgcodecs
> 06-01 11:52:03.185: E/AndroidRuntime(27526):        at java.lang.Class.classForName(Native Method)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
> 06-01 11:52:03.185: E/AndroidRuntime(27526):        ... 15 more
> 06-01 11:52:03.185: E/AndroidRuntime(27526):    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

I inserted the sample code from your readme. I am using eclipse and opencv 3.1.0. The old googlecode was working, but I would like to use functions supported by the newer version. I also tried to extract the .so-Files from the android jar files to the matching libs folder (armeabi & x86), but the exception stays the same.
Maybe someone can help me? What am I doing wrong?

**Comment by saudet** [comment]
It says you didn't include the "org.bytedeco.javacpp.opencv_imgcodecs" class, so try to include it.

**Comment by anita248** [comment]
Thank you for your fast answer! Where do I have to add the class file? Also in the libs folder?

**Comment by saudet** [comment]
Yes, please try to follow the instructions in the README.md file.

**Comment by anita248** [comment]
I looked for this class in the javacpp.jar file, but I can´t find it. Do you know where it is located? Do I need to download the src files of javacv and add the java classes?

The read me only says for Eclipse (Java SE 7 or newer):
Navigate to Project > Properties > Java Build Path > Libraries and click "Add External JARs...".
Locate the JAR files, select them, and click OK.

I did this, eclipse recognizes the classes but I can´t run it on my phone.

**Comment by saudet** [comment]
Just try to add all the JAR files please.

**Comment by anita248** [comment]
I added all jar files in my libs folder, but then I get the following error (I don´t know why he locates the files at "lib" and not "libs"):

> [2016-06-06 16:54:05 - Sample] The library 'ffmpeg-android-arm.jar' contains native libraries that will not run on the device.
[2016-06-06 16:54:05 - Sample] Additionally some of those libraries will interfer with the installation of the application because of their location in lib/
[2016-06-06 16:54:05 - Sample] lib/ is reserved for NDK libraries.
[2016-06-06 16:54:05 - Sample] The following libraries were found:
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libavcodec.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libavdevice.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libavfilter.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libavformat.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libavutil.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjniavcodec.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjniavdevice.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjniavfilter.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjniavformat.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjniavutil.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjnipostproc.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjniswresample.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libjniswscale.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libpostproc.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libswresample.so
[2016-06-06 16:54:05 - Sample]  - lib/armeabi/libswscale.so

**Comment by saudet** [comment]
You did not follow the instructions in the README.md file. Please try again with Android Studio. Eclipse is no longer supported by Google for Android.
