### ISSUE TITLE
FfmpegFrameGrabber.grab gets stuck

### ISSUE THREAD

**Issue by guylevin** [bytedeco/javacv#430]
FfmpegFrameGrabber.grab / grabFrame / grabImage / grabKeyFrame

Gets stuck when stream is lost and does not recover when it is returned

FfmpegFrameGrabber Timeout doesn't work for this matter

**Comment by saudet** [comment]
It's a feature that is needed, yes. Would you like to make a contribution? FYI, there's already been some discussions about that in the past : https://github.com/bytedeco/javacv/issues/165 https://github.com/bytedeco/javacv/issues/170

**Comment by yngvesl** [comment]
I'm having the same problem. At the moment my only option is to check whether consumption has stopped and recreate another grabber thread...which will fill the JVM and lead to an out of memory error in the long run, as far as I can see.

**Comment by saudet** [comment]
It turns that we only need to set the "timeout", "rw_timeout" or "stimeout" option, depending on the protocol. Thanks to @d-a-gerashenko we now have working sample code for this:
https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java

**Comment by frankbsd** [comment]
> eGrabber Timeout doesn't work for this matter

then how to solve this problem? Thanks a lot!

**Comment by frankbsd** [comment]
> FfmpegFrameGrabber.grab / grabFrame / grabImage / grabKeyFrame
> 
> Gets stuck when stream is lost and does not recover when it is returned
> 
> FfmpegFrameGrabber Timeout doesn't work for this matter

and how can we  solve this problem? Thanks a lot
