### ISSUE TITLE
Cannot build with gradle 

### ISSUE THREAD

**Issue by Maleandr** [bytedeco/javacv#432]
I cannot build version 1.2 with gradle. When I try this:

`compile group: 'org.bytedeco', name: 'javacv', version: '1.2'`

or

`compile 'org.bytedeco:javacv:1.2'`

I get always this error:

`Could not find javacpp-presets-Mac OS X-x86_64.jar (org.bytedeco:javacpp-presets:1.2).
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/1.2/javacpp-presets-1.2-Mac OS X-x86_64.jar`

I can build version 1.1 without problems. I checked documentation from javacpp-presets as suggested from readme, but nothing worked. I understand that in version 1.2 is used custom property "javacpp.platform", which cannot be added via gradle. I tried:
`compile group: 'org.bytedeco', name: 'javacv', version: '1.2', classifier: 'macosx-x86_64'`

and get:

` Could not find javacv-macosx-x86_64.jar (org.bytedeco:javacv:1.2).
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/bytedeco/javacv/1.2/javacv-1.2-macosx-x86_64.jar`

I tested gradle build also on Linux, got same error with just different platform (Linux-amd64). So is gradle build broken, or i'm missing something?

**Comment by saudet** [comment]
That's a known issue with Gradle trying to include dependencies it shouldn't: https://github.com/bytedeco/javacv/issues/395#issuecomment-220213783

**Comment by saudet** [comment]
Basically, for now, include this in the `build.gradle` file:
```groovy
configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}
```

**Comment by Maleandr** [comment]
Thank you for info. Sorry for duplicate reports.
