### ISSUE TITLE
NullPointerException from camera on arm device platform

### ISSUE THREAD

**Issue by Aurusd** [bytedeco/javacv#433]
Good day for everyone. Need help in next problem.
I use Odroid PC board http://www.hardkernel.com/main/products/prdt_info.php?g_code=G143452239825
System: Ubuntu 15.04, java 1.8.91 i586, bytedeco javacv library
I have used next code
public class VideoAndAudioFromWebCamApplication {
    final private static int WEBCAM_DEVICE_INDEX = 0;
    final private static int AUDIO_DEVICE_INDEX = 4;

    final private static int FRAME_RATE = 30;
    final private static int GOP_LENGTH_IN_FRAMES = 60;
    public static final String FILE_PATH = "output.mp4";

    private static long startTime = 0;
    private static long videoTS = 0;

    private static ScheduledThreadPoolExecutor scheduledThreadPoolExecutor;
    private static ScheduledThreadPoolExecutor mainExecutor;

    public static void main(String[] args) throws Exception {

        OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();

        int captureWidth = 1280;
        int captureHeight = 720;

        // The available FrameGrabber classes include OpenCVFrameGrabber (opencv_videoio),
        // DC1394FrameGrabber, FlyCaptureFrameGrabber, OpenKinectFrameGrabber,
        // PS3EyeFrameGrabber, VideoInputFrameGrabber, and FFmpegFrameGrabber.
        //OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(WEBCAM_DEVICE_INDEX);
        FrameGrabber grabber = FrameGrabber.createDefault(WEBCAM_DEVICE_INDEX);
//        grabber.setImageWidth(captureWidth);
//        grabber.setImageHeight(captureHeight);
        
        
//        OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
        grabber.start();

The result is 
Exception in thread "main" java.lang.NullPointerException
 at org.bytedeco.javacv.FrameGrabber.create(FrameGrabber.java:95)
 at org.bytedeco.javacv.FrameGrabber.createDefault(FrameGrabber.java:118)
 at com.mpsdevelopment.drones.hardware.camera.VideoAndAudioFromWebCamApplication.main(VideoAndAudioFromWebCamApplication.java:59)
When i change line to FrameGrabber grabber = FrameGrabber.createDefault("/dev/video0"); (because OS is linux).. havу the same exception.
What i am doing wrong?

**Comment by saudet** [comment]
Looks like you just have missing JARs in your class path. Please make sure to includ *all* the JAR files.

**Comment by Aurusd** [comment]
On Windows platform this code work, but on linux arm not. Maybe need jar's for especially linux-arm? I saw in issues some information about that there is not build bytedeco javacv for linux-arm posted by 2015. Today find this page https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments.. but i dont know how it help

**Comment by saudet** [comment]
Yes, it works fine on Windows. But we are *not* talking about Windows. So please try to add **all** the JAR files *manually* into your class path because there are binaries at least for OpenCV and FFmpeg with version 1.2, but than again maybe it's not detecting your platform properly: https://github.com/bytedeco/javacpp/issues/105

**Comment by Aurusd** [comment]
I added all jar's (javacv 1.2, javacpp-presets:ffmpeg..) manually as you said before, but if i used 
 FrameGrabber grabber = FrameGrabber.createDefault(WEBCAM_DEVICE_INDEX);
The result was
Exception in thread "main" java.lang.NullPointerException
at org.bytedeco.javacv.FrameGrabber.create(FrameGrabber.java:95)
at org.bytedeco.javacv.FrameGrabber.createDefault(FrameGrabber.java:118)
if i used 
OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(WEBCAM_DEVICE_INDEX);
The result was
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
But there is one moment. When i run my project in IDEA, like maven project maven said that javacv, and javacpp-presets.ffmpeg dependencies with prefix "linux-arm" can't be resolve. And i think maybe there is exactly bytedeco version with linux-arm platform. Or second reason can be that i can't install (use) java jdk linux arm 64 bit, because on windows it were the same problem's if i used java jdk 32 bit.

**Comment by saudet** [comment]
Ok, so like I said, maybe JavaCPP isn't detecting your platform properly. What does `Loader.getPlatform()` return?

**Comment by Aurusd** [comment]
linux-armhf

**Comment by saudet** [comment]
Ok that's cool, so that means you only do not have the `opencv-linux-armhf.jar` in your class path. Maven won't get you that no so let's mark this issue as "enhancement". Like I said, simply put all the JAR files in the class path and it will work.

**Comment by Aurusd** [comment]
I have added opencv-linux-armhf.jar from http://central.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.1.0-1.2/ (but arm opencv not provide import org.bytedeco.javacpp.opencv_core;
import org.bytedeco.javacpp.opencv_core.IplImage;)
And also added javacv-1.2.jar, javacpp-1.2.1.jar, ffmpeg-3.0.2-1.2, but had still the same
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
 at java.lang.Runtime.loadLibrary0(Runtime.java:870)
 at java.lang.System.loadLibrary(System.java:1122)
 at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:702)
 at org.bytedeco.javacpp.Loader.load(Loader.java:500)
 at org.bytedeco.javacpp.Loader.load(Loader.java:417)
 at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
 at java.lang.Class.forName0(Native Method)
 at java.lang.Class.forName(Class.java:348)
 at org.bytedeco.javacpp.Loader.load(Loader.java:472)
 at org.bytedeco.javacpp.Loader.load(Loader.java:417)
 at org.bytedeco.javacpp.opencv_videoio$VideoCapture.<clinit>(opencv_videoio.java:957)
 at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:175)
 at com.mpsdevelopment.drones.hardware.camera.VideoAndAudioFromWebCamApplication.main(VideoAndAudioFromWebCamApplication.java:66)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path
```

**Comment by saudet** [comment]
What does it say if you set the "org.bytedeco.javacpp.logger.debug" system property to "true"?

**Comment by Aurusd** [comment]
sorry for long answer. I dont know what mean "org.bytedeco.javacpp.logger.debug" system property to "true". For now code works if i add via IDEA to javacpp-1.2.1 Native library Location (*.so files from opencv-linux-armhf.jar). And so main question is how to show *.so files to javaб especially when create build.

**Comment by saudet** [comment]
Like I said, the opencv-linux-armhf.jar does not seem to be in your class path. Please try to call System.setProperty("org.bytedeco.javacpp.logger.debug" , "true") to make sure it actually gets loaded.

**Comment by Aurusd** [comment]
I have added this line
`System.setProperty("org.bytedeco.javacpp.logger.debug" , "true");` property set to true without any exception. But in whole present 
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path`

**Comment by saudet** [comment]
You will get messages in the console though. Please copy/paste the messages you get.

**Comment by Aurusd** [comment]
Loading class org.bytedeco.javacpp.opencv_core
Loading class org.bytedeco.javacpp.opencv_core
Loading library opencv_core
Failed to load for opencv_core@.3.1: java.lang.UnsatisfiedLinkError: no opencv_core in java.library.path
Loading library opencv_imgproc
Failed to load for opencv_imgproc@.3.1: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path
Loading library jniopencv_core
Failed to load for jniopencv_core: java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

**Comment by saudet** [comment]
That means `opencv-linux-armhf.jar` is definitely *not* in your class path. Like I've told you a few times already, just put `opencv-linux-armhf.jar` in your class path and it will work. I will not repeat again.

**Comment by Aurusd** [comment]
I hear you very clearly, but opencv-linux-armhf.jar already added to the project all this time
http://clip2net.com/s/3zqlxNX

**Comment by Aurusd** [comment]
Only if i manually add *.so file to javaccp-1.2.1 like Native Library location get next
```
Loading class org.bytedeco.javacpp.opencv_core
Loading class org.bytedeco.javacpp.opencv_core
Loading /home/odroid/Downloads/opencv-3.1.0-1.2-linux-armhf/org/bytedeco/javacpp/linux-armhf/libopencv_core.so.3.1
Loading /home/odroid/Downloads/opencv-3.1.0-1.2-linux-armhf/org/bytedeco/javacpp/linux-armhf/libopencv_imgproc.so.3.1
Loading /home/odroid/Downloads/opencv-3.1.0-1.2-linux-armhf/org/bytedeco/javacpp/linux-armhf/libjniopencv_core.so
Loading class org.bytedeco.javacpp.opencv_core
Registering org.bytedeco.javacpp.opencv_core$CvSlice[address=0xa239df28,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0xa239df28,deallocatorAddress=0xa1b70a50]]
Registering org.bytedeco.javacpp.opencv_core$CvSlice[address=0xa23bba28,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0xa23bba28,deallocatorAddress=0xa1b70a50]]
Loading class org.bytedeco.javacpp.opencv_imgproc
Loading class org.bytedeco.javacpp.opencv_core
Loading class org.bytedeco.javacpp.opencv_imgproc
Loading /home/odroid/Downloads/opencv-3.1.0-1.2-linux-armhf/org/bytedeco/javacpp/linux-armhf/libjniopencv_imgproc.so
Loading class org.bytedeco.javacpp.opencv_imgcodecs
Loading class org.bytedeco.javacpp.opencv_core
Loading class org.bytedeco.javacpp.opencv_imgproc
Loading class org.bytedeco.javacpp.opencv_imgcodecs
Loading /home/odroid/Downloads/opencv-3.1.0-1.2-linux-armhf/org/bytedeco/javacpp/linux-armhf/libopencv_imgcodecs.so.3.1
Loading /home/odroid/Downloads/opencv-3.1.0-1.2-linux-armhf/org/bytedeco/javacpp/linux-armhf/libjniopencv_imgcodecs.so
Loading class org.bytedeco.javacpp.opencv_videoio
Loading class org.bytedeco.javacpp.opencv_core
Loading class org.bytedeco.javacpp.opencv_imgproc
Loading class org.bytedeco.javacpp.opencv_imgcodecs
Loading class org.bytedeco.javacpp.opencv_videoio
Loading /home/odroid/Downloads/opencv-3.1.0-1.2-linux-armhf/org/bytedeco/javacpp/linux-armhf/libopencv_videoio.so.3.1
Loading
```

**Comment by saudet** [comment]
Ok, so you got it loading, great!

**Comment by saudet** [comment]
Adding a JAR file to your project doesn't mean it makes it part of the class path. Please read the documentation of your IDE to figure out how to add a JAR file in the class path. I cannot help you with! It's unrelated to JavaCV.

**Comment by Aurusd** [comment]
If i understand correct, for my IDE, add jar for module dependencies means that they are in class path.
opencv-linux-armhf.jar include only *.so files, and if i add it to project will get not resolved problem import org.bytedeco.javacpp.opencv_core; cause opencv-linux-armhf.jar there isn't opencv_core class.  Adding both two opencv jar's (arm and simple opencv)  
`Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path`
I think in this situation we need point for javacpp where is native library's (opencv arm)

**Comment by saudet** [comment]
Like I said, it's probably an issue with your IDE. If you try it on the command line, I am certain it will work. So please file an issue with the author of your IDE.

**Comment by Aurusd** [comment]
With the help of `System.setProperty("java.library.path", System.getProperty("user.dir") + "/nativelib/");`
(with *.so files) in IDE it works. But if i make build jar (in eclipse in windows) with my test code and then run it on linux arm in terminal java -cp testcode.jar com.*.myclass have next
```
Loading class org.bytedeco.javacpp.opencv_core
Loading class org.bytedeco.javacpp.opencv_core
Loading library opencv_core
Failed to load for opencv_core@.3.0: java.lang.UnsatisfiedLinkError: no opencv_core in java.library.path
Loading library opencv_imgproc
Failed to load for opencv_imgproc@.3.0: java.lang.UnsatisfiedLinkError: no opencv_imgproc in java.library.path
Extracting file:/home/odroid/Downloads/boardApplication-bin/nativelib/libjniopencv_core.so
Loading /tmp/javacpp8776957506087/libjniopencv_core.so
Failed to load /tmp/javacpp8776957506087/libjniopencv_core.so: java.lang.UnsatisfiedLinkError: /tmp/javacpp8776957506087/libjniopencv_core.so: libopencv_imgproc.so.3.1: cannot open shared object file: No such file or directory
Loading /tmp/javacpp8776957506087/libjniopencv_core.so
Failed to load /tmp/javacpp8776957506087/libjniopencv_core.so: java.lang.UnsatisfiedLinkError: /tmp/javacpp8776957506087/libjniopencv_core.so: libopencv_imgproc.so.3.1: cannot open shared object file: No such file or directory
Loading /tmp/javacpp8776957506087/libjniopencv_core.so
Failed to load /tmp/javacpp8776957506087/libjniopencv_core.so: java.lang.UnsatisfiedLinkError: /tmp/javacpp8776957506087/libjniopencv_core.so: libopencv_imgproc.so.3.1: cannot open shared object file: No such file or directory
Loading library jniopencv_core
Failed to load for jniopencv_core: java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
 at java.lang.Runtime.loadLibrary0(Runtime.java:870)
 at java.lang.System.loadLibrary(System.java:1122)
 at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
 at org.bytedeco.javacpp.Loader.load(Loader.java:492)
 at org.bytedeco.javacpp.Loader.load(Loader.java:409)
 at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
 at java.lang.Class.forName0(Native Method)
 at java.lang.
```

**Comment by saudet** [comment]
So file a bug report for your IDE. It's not working as it's supposed to.

**Comment by saudet** [comment]
And like I tried to say, if you do *everything* on the command line, if you build everything and run everything, from the command line, without using your IDE **at all**, it will work. There is most likely a problem with your IDE.

**Comment by Aurusd** [comment]
Ok, thanks saudet. I think easiest way for me is on windows where i do my build add to project opencv-linux-armhf.jar from http://central.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.1.0-1.2/, cause by default maven take to build jar opencv-3.1.0-1.2-windows-x86_64.jar and therefore it is not work on linux. But i dont know how to add to pom.xml opencv-linux-armhf.jar from central.maven.org/maven2 instead windows-x86_64 version

**Comment by saudet** [comment]
Something like this:
```xml
  <dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>opencv</artifactId>
    <version>3.1.0-1.2</version>
    <classifier>linux-armhf</classifier>
  </dependency>
```

**Comment by Aurusd** [comment]
It's good decision sauget. It helps, but is correct next ?
```
<dependency>
			<groupId>org.bytedeco.javacpp-presets</groupId>
			<artifactId>ffmpeg</artifactId>
			<version>3.0.2-1.2</version>
			<classifier>linux-armhf</classifier> 																														
</dependency>
```
because IDE says that missing artifact

**Comment by saudet** [comment]
Like I said, your IDE isn't working properly. Please try on the command line.

**Comment by Aurusd** [comment]
I mean this dependence resolve
 ```
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>opencv</artifactId>
    <version>3.1.0-1.2</version>
    <classifier>linux-armhf</classifier>
  </dependency>
```
and this not resolve
```
<dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg</artifactId>
            <version>3.0.2-1.2</version>
            <classifier>linux-armhf</classifier>                                                                                                                        
</dependency>
```
