### ISSUE TITLE
Null Pointer exception in javaCV mat.createIndexer() function

### ISSUE THREAD

**Issue by PatrickPenguinTurtle** [bytedeco/javacv#437]
While trying to get an indexer for an org.bytedeco.javacpp.opencv_core.Mat a null pointer exception occurs. 
<img width="1145" alt="screen shot 2016-06-21 at 2 00 33 pm" src="https://cloud.githubusercontent.com/assets/16124010/16240747/8dab80f0-37b8-11e6-93ff-c1d015814cef.png">
A simplified (irrelevant lines of code removed) version of the code is: 
<img width="634" alt="screen shot 2016-06-21 at 2 04 05 pm" src="https://cloud.githubusercontent.com/assets/16124010/16240844/1065f110-37b9-11e6-8fde-ea4ad9e8716e.png">

System details Mac osx 10.11.5 with the most recent version of the library downloaded using gradle from the maven repository today, Tuesday June 21st 2016 at 2pm. 

I need to look at all channels of each pixel, one pixel at a time and know the location of that pixel (row,col). Speed is not particularly important and this was the simpler version of using an indexer that I saw.

**Comment by PatrickPenguinTurtle** [comment]
It also occurs in 
`ByteBuffer buf = input.<ByteBuffer>createBuffer();`

<img width="1137" alt="screen shot 2016-06-21 at 4 15 42 pm" src="https://cloud.githubusercontent.com/assets/16124010/16244725/6e805dd2-37cb-11e6-8436-eadd412b8130.png">

**Comment by PatrickPenguinTurtle** [comment]
Solved the issue. It turns out that if the image is empty, then this throws a null pointer exception.
No longer a problem, however it would be better if an error relating to the actual issue was thrown instead of a null pointer exception.

**Comment by saudet** [comment]
If the data pointer is null, we get a NPE. Sounds OK to me. We could point
this out in the doc of Indexable though. Would you mind sending a pull
request for that?
