### ISSUE TITLE
JavaCV 1.2 Broken video on OS X

### ISSUE THREAD

**Issue by meonlineonmess** [bytedeco/javacv#439]
Hello,

I am having an issue with the latest version of JavaCV 1.2 from Bytedeco on OSX El Capitan.

I am trying to record frames from my usb webcam in a file with the ".avi" extension. While recording, the frames also get displayed on a window container.

The issue I am facing is that with version 1.2 of JavaCV(Bytedeco) I always get a thread exception in the console and the thread stops which makes the streaming from the webcam freeze, however the recording goes on but with some frame drops.

The exception is "unrecognized selector sent to instance javacv"

However with version 1.0 of JavaCV(Bytedeco) I do not get the thread exception but the recorded .avi file is broken and it looks like this(the issue starts at 0:02) -> 
https://www.dropbox.com/s/wc4p21tyuhu7uls/Untitled.avi?dl=0

My code is here:
For webCam Viewer:
"public void initWebCam(int portNumber) throws Exception {
		Java2DFrameConverter converter = new Java2DFrameConverter();
		grabber = new OpenCVFrameGrabber(portNumber);
		grabber.setImageHeight(Constants.VIDEO_FRAME_HEIGHT);
		grabber.setImageWidth(Constants.VIDEO_FRAME_WIDTH);
		try {
			grabber.start();
		} catch (Exception e) {
			Platform.runLater(new Runnable() {
				@Override
				public void run() {
					ProjectUtils.showConnectionError("WebCam Information", "Connection Issue:",
							"Could not initialize camera");
				}
			});
		}

		Frame img = grabber.grab();
		if (img != null) {

			stage.setWidth(img.imageWidth);
			stage.setHeight(img.imageHeight);
			webCamIsOn();
		}

		while (frameGrabberFlag) {

			img = grabber.grab();
			if (img != null) {

				viewWebCamController
						.setImageOnWebCamImageView(SwingFXUtils.toFXImage(converter.getBufferedImage(img), null));

			}

		}
		grabber.flush();
		grabber.stop();

	}"

For frame recorder:
"Thread t = null;
		try {
			t = new Thread(new Runnable() {

				Float progress = 0f;
				org.bytedeco.javacv.FrameRecorder recorder = org.bytedeco.javacv.FrameRecorder
						.createDefault(savePath + ".avi", Constants.VIDEO_FRAME_WIDTH, Constants.VIDEO_FRAME_HEIGHT);

				public void run() {
					try {
						recorder.start();
					} catch (org.bytedeco.javacv.FrameRecorder.Exception e1) {
						e1.printStackTrace();
					}

					Frame frame = null;
					for (int i = 0; i < 360; i++) {
						try {
							frame = webCam.getGrabber().grab();
							recorder.record(frame);
							arduino.incrementStepper();
						} catch (Exception | SerialPortException | InterruptedException e) {
							e.printStackTrace();
						} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
							e.printStackTrace();
						}
						progress = progress + Constants.INCREMENT_FOR_PROGRESS_VALUE;
						incrementProgressBar(progressBar, progress);
					}
					try {
						recorder.stop();
					} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
						e.printStackTrace();
					}
				}
			});
			t.start();
		} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
			e.printStackTrace();
		}"

I have the ability to turn on the webcam and keep it on while the recorder stores the frames into the .avi file.

I have no ideea where to go next, how to solve the broken video in JavaCV 1.0 from Bytedeco

**Comment by saudet** [comment]
JavaFX isn't thread safe. You're going to need to make your "viewWebCamController" thread safe. This isn't related to JavaCV.
