### ISSUE TITLE
CvMat release causes segfault

### ISSUE THREAD

**Issue by ben-manes** [bytedeco/javacv#444]
Ran into an issue on Linux (x86_64) but this worked fine on OS X with javacv 1.2 and opencv 3.1.0. The first version of the Java code failed and the second version using `opencv_imgproc.warpPerspective` appears to work reliably. The snippets show only the javacv code and any missing functions are simple Java code.

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.bytedeco.javacpp.opencv_core.cvReleaseMat(Lorg/bytedeco/javacpp/opencv_core$CvMat;)V+0
j  org.bytedeco.javacpp.helper.opencv_core$AbstractCvMat$ReleaseDeallocator.deallocate()V+1
j  org.bytedeco.javacpp.Pointer$DeallocatorReference.clear()V+49
j  org.bytedeco.javacpp.Pointer.deallocateReferences()V+21
j  org.bytedeco.javacpp.Pointer.deallocator(Lorg/bytedeco/javacpp/Pointer$Deallocator;)Lorg/bytedeco/javacpp/Pointer;+55
j  org.bytedeco.javacpp.Pointer.init(JJJJ)V+47
v  ~StubRoutines::call_stub
j  org.bytedeco.javacpp.opencv_core.cvarrToMat(Lorg/bytedeco/javacpp/helper/opencv_core$CvArr;)Lorg/bytedeco/javacpp/opencv_core$Mat;+0
j  org.bytedeco.javacpp.opencv_core$Mat.<init>(Lorg/bytedeco/javacpp/helper/opencv_core$CvArr;)V+2
j  topDownView
```

```java
/**
 * Transforms an image to obtain the top-down, "birds eye view" based on the supplied reference
 * points.
 *
 * @param input the file path to the source image
 * @param output the file path to the destination image
 * @param contour the rectangular reference points to warp
 */
public static void topDownView(Path input, Path output, Contour contour) {
  Stopwatch stopwatch = Stopwatch.createStarted();

  // http://www.pyimagesearch.com/2014/08/25/4-point-opencv-getperspective-transform-example
  int maxWidth = maxWidth(contour);
  int maxHeight = maxHeight(contour);
  try (IplImage image = cvLoadImage(input.toString());
      Mat imageMat = new Mat(image);
      MatExpr matrixExpr = Mat.eye(3, 3, CV_32F);
      Mat matrix = matrixExpr.asMat();
      CvMat M = new CvMat(matrix);
      Mat warpedMat = new Mat(4, 1, CV_32F);
      Size size = new Size(maxWidth, maxHeight)) {
    double[] corners = getCorners(contour);
    double[] dimensions = getDimensions(maxWidth, maxHeight);
    JavaCV.getPerspectiveTransform(corners, dimensions, M);
    warpPerspective(imageMat, warpedMat, matrix, size);
    imwrite(output.toString(), warpedMat);
  }
  logger.info("Warped image {} in {}", output.getFileName(), stopwatch);
}
```

```java
public static void topDownView(Path input, Path output, Contour contour) {
  Stopwatch stopwatch = Stopwatch.createStarted();

  // http://www.pyimagesearch.com/2014/08/25/4-point-opencv-getperspective-transform-example
  int maxWidth = maxWidth(contour);
  int maxHeight = maxHeight(contour);
  Mat imageMat = imread(input.toString(), IMREAD_COLOR);
  Mat warpedMat = imageMat.clone();
  Point2f srcPts = getCorners(contour);
  Point2f dstPts = getDestination(maxWidth, maxHeight);
  Size size = new Size(maxWidth, maxHeight);
  Mat perspectiveTransform = getPerspectiveTransform(srcPts.position(0), dstPts.position(0));
  warpPerspective(imageMat, warpedMat, perspectiveTransform, size);
  imwrite(output.toString(), warpedMat);
  logger.info("Warped image {} in {}", output.getFileName(), stopwatch);
}

private static Point2f getCorners(Contour contour) {
  Point2f srcPts = new Point2f(4);
  srcPts.position(0).x(contour.getTopLeftX()).y(contour.getTopLeftY());
  srcPts.position(1).x(contour.getTopRightX()).y(contour.getTopRightY());
  srcPts.position(2).x(contour.getBottomRightX()).y(contour.getBottomRightY());
  srcPts.position(3).x(contour.getBottomLeftX()).y(contour.getBottomLeftY());
  return srcPts;
}

private static Point2f getDestination(int maxWidth, int maxHeight) {
  Point2f dstPts = new Point2f(4);
  dstPts.position(0).x(0).y(0);
  dstPts.position(1).x(maxWidth - 1).y(0);
  dstPts.position(2).x(maxWidth - 1).y(maxHeight - 1);
  dstPts.position(3).x(0).y(maxHeight - 1);
  return dstPts;
}
```

**Comment by saudet** [comment]
This can't happen if you're not calling `CvMat.create()`. Could you also include the part when your code calls `CvMat.create()`?

**Comment by ben-manes** [comment]
That was the fully relevant code. This is the only class that uses javacv as I added it a few days ago. See the [entire gist](https://gist.github.com/ben-manes/4bfa34c6c3f2f1902ee91bf8eb7f44d2) for the full code. You'll see that there isn't much extra except for a few helper functions.

**Comment by saudet** [comment]
Well, try to use opencv_imgproc.getPerspectiveTransform() instead of JavaCV.getPerspectiveTransform(). Then you don't need to use CvMat at all.

**Comment by ben-manes** [comment]
Yes, you'll see that was the fix I showed in the second code snippet. In that version I didn't eagerly close resources as I saw you use phantom references and when debugging wasn't sure about reentrancy.

**Comment by saudet** [comment]
The `JavaCV.getPerspectiveTransform(corners, dimensions, M)` line is still in your gist

**Comment by ben-manes** [comment]
Yes, I thought you were wanting the full code that broke and I was showing no `CvMat.create()` was called. The second snippet in my original post shows my workaround, which as described in the preceding paragraph uses `opencv_imgproc.warpPerspective`.

**Comment by saudet** [comment]
Ah, I see. That's not just a workaround, that's the way it should be done. The CvMat and IplImage API from OpenCV is deprecated.. Since there is no way ReleaseDeallocator can get there, there is probably memory corruption happening here. We have to be careful with native code.

**Comment by ben-manes** [comment]
Can you mark the method as deprecated and hint to the user the alternative? Basically the API should help users avoid production incidents because the user discovers the wrong method first.

**Comment by saudet** [comment]
You mean JavaCV.getPerspectiveTransform()? Sure, but CvMat is already marked as deprecated via OpenCV...

**Comment by saudet** [comment]
But then again, getPlaneParameters() isn't something that is part of OpenCV, so can't really mark all of those as deprecated. The issue is with CvMat and IplImage and trying to share memory with Mat, ended up corrupting something somewhere, not with the methods in the JavaCV class.

**Comment by ben-manes** [comment]
That's fine, the methods should be deprecated when appropriate and the class doesn't need to be. It was surprising to see `CvMat` deprecated but only finding `JavaCV.getPerspectiveTransform()` when [searching the github repository](https://github.com/bytedeco/javacv/search?utf8=%E2%9C%93&q=getPerspectiveTransform&type=Code). I assume now that `opencv_imgproc` is code generated, but finding the JavaCV version first led me down the wrong path. I was confused by CvMat being deprecated but not being aware of an alternative method. Hence a simple deprecation and documentation pointing to the correct method would have made yesterday a lot more pleasant. :-)

**Comment by saudet** [comment]
Ok, how's the update from the latest commit (link above)? Thanks for the feedback :)

**Comment by ben-manes** [comment]
looks good, thanks
