### ISSUE TITLE
when the rtsp server return failure response, jvm would crash and produce dump core file

### ISSUE THREAD

**Issue by jingyuzhu** [bytedeco/javacv#446]
i try to push the rtsp stream to my rtsp server.during pushing ,when the server return failure response  e.g.  4XX, the jvm would crash.

the console :
# 
# A fatal error has been detected by the Java Runtime Environment:
# 
# EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000057f93dbb, pid=3992, tid=12356
# 
# JRE version: Java(TM) SE Runtime Environment (7.0_79-b15) (build 1.7.0_79-b15)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [avformat-56.dll+0xb3dbb]
# 
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
# 
# An error report file with more information is saved as:
# D:hs_err_pid3992.log
# 
# If you would like to submit a bug report, please visit:
# http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
# 

VIDEOINPUT SPY MODE!

SETUP: Looking For Capture Devices
SETUP: 0) USB2.0 Camera 
SETUP: 1 Device(s) found

****\* VIDEOINPUT LIBRARY - 0.2000 - TFW2013 *****

SETUP: Setting up device 0
SETUP: USB2.0 Camera
SETUP: Couldn't find preview pin using SmartTee
SETUP: Default Format is set to 640 by 480 
SETUP: trying requested format RGB24 @ 600 by 480
SETUP: trying format RGB24 @ 600 by 480
SETUP: trying format RGB32 @ 600 by 480
SETUP: trying format RGB555 @ 600 by 480
SETUP: trying format RGB565 @ 600 by 480
SETUP: trying format YUY2 @ 600 by 480
SETUP: trying format YVYU @ 600 by 480
SETUP: trying format YUYV @ 600 by 480
SETUP: trying format IYUV @ 600 by 480
SETUP: trying format UYVY @ 600 by 480
SETUP: trying format YV12 @ 600 by 480
SETUP: trying format YVU9 @ 600 by 480
SETUP: trying format Y411 @ 600 by 480
SETUP: trying format Y41P @ 600 by 480
SETUP: trying format Y211 @ 600 by 480
SETUP: trying format AYUV @ 600 by 480
SETUP: trying format Y800 @ 600 by 480
SETUP: trying format Y8 @ 600 by 480
SETUP: trying format GREY @ 600 by 480
SETUP: trying format OTHER @ 600 by 480
SETUP: couldn't find requested size - searching for closest matching size
SETUP: closest supported size is YUY2 @ 640 480
SETUP: Capture callback set
SETUP: Device is setup and ready to capture.

Output #0, rtsp, to 'rtsp://51poc.cn:1554/1.sdp':
    Stream #0:0: Video: h264 (libx264), yuv420p, 608x480, q=-1--1, 200 kb/s, 25 tbn, 25 tbc
    Stream #0:1: Audio: aac (libvo_aacenc), 44100 Hz, stereo, s16, 64 kb/s
[libx264 @ 0000000000399ea0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 0000000000399ea0] profile Constrained Baseline, level 3.0
[libx264 @ 0000000000399ea0] 264 - core 148 r2638 7599210 - H.264/MPEG-4 AVC codec - Copyleft 2003-2015 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=4 lookahead_threads=4 sliced_threads=1 slices=4 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=25 keyint_min=2 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
[rtsp @ 0000000000399580] method SETUP failed: 412 Precondition Failed

[hs_err_pid3992.zip](https://github.com/bytedeco/javacv/files/343285/hs_err_pid3992.zip)

this case ,why not  to throw a exception ?

**Comment by saudet** [comment]
FFmpeg crashes before we can send an exception. Please report the bug
upstream so they can fix it, thank you.
