### ISSUE TITLE
How to switch to fullscreen mode using a CanvasFrame ?

### ISSUE THREAD

**Issue by toribiosilva** [bytedeco/javacv#449]
Hi, i would like to to make a simple app that just displays the webcam in full screen and save the output video. My problem is that calling CanvasFrame with setUndecorated(true) the windows appears empty. Im using java in eclipse and a Windows PC.
If anyone could help me I´ll appreciate it.

My code is:

`import java.awt.Canvas;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.Frame;
import java.awt.GraphicsConfiguration;
import java.awt.Toolkit;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Window;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.net.URL;

import javax.swing.JFrame;
import javax.swing.JRootPane;

import org.bytedeco.javacv.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.indexer.*;
import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;
import static org.bytedeco.javacpp.opencv_calib3d.*;
import static org.bytedeco.javacpp.opencv_objdetect.*;

public class Demo  {
	
    public static void main(String[] args) throws Exception {    

    	// Obtenemos las dimensiones de la pantalla
    	int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    	int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    	

        FrameGrabber grabber = FrameGrabber.createDefault(0);
        grabber.start();
        FrameRecorder recorder = FrameRecorder.createDefault("output.avi", ancho, alto);
        recorder.start();

        

        // CanvasFrame is a JFrame containing a Canvas component, which is hardware accelerated.
        // It can also switch into full-screen mode when called with a screenNumber.
        // We should also specify the relative monitor/camera response for proper gamma correction.
        CanvasFrame frame = new CanvasFrame("Prueba Webcam", CanvasFrame.getDefaultGamma()/grabber.getGamma());        
        
        for (Window w : Window.getWindows()) {
            GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().setFullScreenWindow(w);
        }
        
       DisplayMode displaymode = frame.getDisplayMode(1);
       System.out.println("Displaymode es " + displaymode);

        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE); 
        frame.setCanvasSize(ancho, alto); 
        //gd.setFullScreenWindow(frame);        
        frame.setLocationRelativeTo(null); 
        frame.setVisible(true);      
        frame.validate();
        
        while (frame.isVisible() ) {  
        	       	
            frame.showImage(grabber.grab());
            recorder.record(grabber.grab());
        }
        frame.dispose();
       recorder.stop();
        grabber.stop();
    }
}`

**Comment by saudet** [comment]
Specify a `screenNumber` along with an optional `displayMode` and `gamma` during construction and it will show up on that display full screen:
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/CanvasFrame.html#CanvasFrame-java.lang.String-int-java.awt.DisplayMode-

**Comment by saudet** [comment]
It is used here for example:
https://github.com/bytedeco/javacv/blob/f0bd4b55f2e7f013beadf034fcf1273e19672d2f/src/main/java/org/bytedeco/javacv/ProjectorDevice.java#L298

**Comment by toribiosilva** [comment]
Ok thank you very much !

**Comment by saudet** [comment]
Call `CanvasFrame.getScreenDescriptions()` for a description of each devices, and use the number that corresponds to the one you want to use.
