### ISSUE TITLE
FFmpegFrameFilter org.bytedeco.javacv.FrameFilter$Exception

### ISSUE THREAD

**Issue by sekhar4233** [bytedeco/javacv#452]
I am trying to add video in video using JavaCV, but i am getting below error.

org.bytedeco.javacv.FrameFilter$Exception: avfilter_graph_parse_ptr()
	at org.bytedeco.javacv.FFmpegFrameFilter.startUnsafe(FFmpegFrameFilter.java:232)
	at org.bytedeco.javacv.FFmpegFrameFilter.start(FFmpegFrameFilter.java:154)
	at WebcamAndMicrophoneCapture.WebcamAndMicrophoneCapture.start(WebcamAndMicrophoneCapture.java:89)
	at org.mactores.UI$1$1.run(UI.java:51)
	at java.lang.Thread.run(Unknown Source)

I want to stream WebCam video and PC screen shots both at a time in a single stream to RTMP server. Is the FFmpegFrameFilter approach is right ????

**Comment by saudet** [comment]
No, we need to use FFmpegFrameRecorder for that.

**Comment by sekhar4233** [comment]
I am using the same class FFmpegFrameRecorder only. But how can i stitch both videos and stream as single video to RTMP server.

**Comment by saudet** [comment]
FFmpegFrameFilter would be one way of doing that, but we would need to add support for more than input to the graph: https://github.com/bytedeco/javacv/issues/389

**Comment by sekhar4233** [comment]
Thanks for quick reply, Is not implemented yet in FFmpegFrameFilter ??

Do you have any idea of  JAVA libraries which can do this work.

**Comment by saudet** [comment]
FYI, we can use the `movie` filter for that, and it should now work as expected with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/
