### ISSUE TITLE
Issues using FaceRecognizer with pretrained model file on Android

### ISSUE THREAD

**Issue by manav95** [bytedeco/javacv#455]
I am having an issue using the FaceRecognizer class and loading a pretrained model on Android. This model has 5 components and was trained with the FisherFacesRecognizer class. It used the Python version and was serialized to a XML file called emotion_detection_model.xml. Here is what I have for the file:

`<?xml version="1.0"?>
<opencv_storage>
<num_components>5</num_components>
<mean type_id="opencv-matrix">
  <rows>1</rows>
  <cols>122500</cols>
  <dt>d</dt>
  <data>
    8.6326259946949591e+01 8.5212201591511928e+01 8.4159151193633946e+01
    8.3074270557029180e+01 8.1912466843501321e+01 8.0774535809018559e+01
    7.9657824933686996e+01 7.8305039787798407e+01 7.6769230769230759e+01
    7.4962864721485403e+01 7.3013262599469499e+01 7.1389920424403186e+01
    70. 6.8599469496021214e+01 6.7233421750663126e+01
    6.5893899204244022e+01 6.4575596816976130e+01 6.3185676392572944e+01
    6.1960212201591510e+01 6.0877984084880630e+01 5.9748010610079575e+01
    5.8734748010610076e+01 5.7496021220159150e+01 5.6018567639257292e+01
    5.4673740053050395e+01 5.3201591511936336e+01 5.1748010610079575e+01
    5.0461538461538460e+01 4.9172413793103445e+01 4.8127320954907162e+01
    4.7312997347480106e+01 4.6482758620689651e+01 4.5564986737400531e+01
    4.4641909814323604e+01 4.3912466843501321e+01 4.3281167108753316e+01
    4.2564986737400531e+01 4.1962864721485410e+01 4.1183023872679044e+01
    4.0469496021220159e+01 3.9909814323607428e+01 3.9503978779840850e+01
    3.9148541114058354e+01 3.8875331564986737e+01 3.8721485411140584e+01
    3.8527851458885941e+01 3.8312997347480106e+01 3.7928381962864719e+01
    3.7681697612732094e+01 3.7618037135278513e+01 3.7371352785145888e+01
    3.7259946949602117e+01 3.7206896551724135e+01 3.7273209549071616e+01
........
<labels type_id="opencv-matrix">
  <rows>377</rows>
  <cols>1</cols>
  <dt>i</dt>
  <data>
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
    2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
    2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
    3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
    3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5
    5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
    5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
    5 5 5</data></labels>
`
Yet when I run the following:
`opencv_core.FileStorage storage = new opencv_core.FileStorage(emotion_detection_model.xml,opencv_core.FileStorage.READ);
faceRecognizer.predict(mat, label, confidence);` 

I get this error:
`OpenCV Error: Bad argument (This FisherFaces model is not computed yet. Did you call the train method?)`

Im not sure what to do. I am using FileStorage to wrap the file and then send it, but with no luck. When I output from FileStorage, I get a bunch of 0s, indicating its not reading it properly. How do I fix this so it is reading the model file properly?

**Comment by saudet** [comment]
I'm guessing your application probably just doesn't have permission to read the "emotion_detection_model.xml" file...

**Comment by manav95** [comment]
It does have permission to read the file.

**Comment by saudet** [comment]
Good. Could you also post the code that connects FileStorage with FaceRecognizer?

**Comment by saudet** [comment]
I'm guessing you simply forgot to load your model, but if this is not the case, please post your code! Thanks
