### ISSUE TITLE
rtmp broadcasting huge delay

### ISSUE THREAD

**Issue by ywj7931** [bytedeco/javacv#456]
Now I normally have around 20s delay,
Is there any way to decrease rtmp stream? 
video bit rate?encode format?
It should not be the problem of Internet.
Anyone has an idea?

**Comment by ywj7931** [comment]
I searched it seemed FFmpeg does not use of any 
hardware acceleration... 

Is there any way to use hardware acceleration?

**Comment by saudet** [comment]
Duplicate of https://github.com/bytedeco/javacv/issues/55: FFmpeg doesn't support hardware acceleration. You'll need to use Android's API to get that.

**Comment by y4nnick** [comment]
@ywj7931 Could you please share your code with me, i am currently struggling with streaming to facebook, (see https://github.com/bytedeco/javacv/issues/491)
