### ISSUE TITLE
FFmpegFrameRecorder audio desynchronising when sample rate is converted

### ISSUE THREAD

**Issue by jamesmmchugh** [bytedeco/javacv#458]
I am obtaining audio and video from a source with an audio sample rate of 44100Hz, I setup an FFmpegFrameRecorder to record the same audio and video but at an audio sample rate of 22050Hz (half of the original). I record the audio using:

```
recorder.recordSamples(22050, 2, audioSamples)
```

After some time of streaming video (1 hour plus) the audio and video start to noticeably desynchronise, and eventually the video stream starts to become unstable (stuttering video and audio etc.).

However, if I call:

```
recorder.recordSamples(44100, 2, audioSamples)
```

I.e. at the original sample rate, then it works perfectly and does no desynchronise. I am guessing this is to do with some rounding error that is getting propagated between calls, causing a slow desynchronisation.

**Comment by saudet** [comment]
Might be a bug in FFmpeg itself. Does the same thing occur when using the ffmpeg tool on the command line? Or only with JavaCV?

**Comment by jamesmmchugh** [comment]
Its not a simple scenario to setup and I'm not massively familiar with FFmpeg; because its a separate source for audio and video and I need to loop the sources indefinitely (because I don't have any resources locally that would play long enough for the desync to become noticeable).

I will try but haven't had much luck yet.

**Comment by saudet** [comment]
JavaCV 1.3 has just been released and it uses a newer version of FFmpeg. If you give it a try, please let me know of the results! Thanks

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming this has been fixed in newer versions of FFmpeg, but please let me know if this isn't the case! Thanks
