### ISSUE TITLE
how to stop av_read_frame() when the connection lost

### ISSUE THREAD

**Issue by NacyLiu** [bytedeco/javacv#462]
I want to stop the av_read_frame() when the connection lost, i found avioInterruptCB can do this, but there is no explanation about it, can you give me an example?

**Comment by saudet** [comment]
There's some info here:
https://github.com/bytedeco/javacv/issues/170
https://github.com/bytedeco/javacv/issues/97

**Comment by saudet** [comment]
Marking as duplicate of https://github.com/bytedeco/javacv/issues/430

**Comment by saudet** [comment]
FYI, it turns out that we only need to set the "timeout", "rw_timeout" or "stimeout" option, depending on the protocol. Thanks to @d-a-gerashenko we now have working sample code for this:
https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java
