### ISSUE TITLE
How to transform Buffer[] from Frame to byte[] and how to play Buffer[] sample?

### ISSUE THREAD

**Issue by Jassarpc** [bytedeco/javacv#464]
Hi,
I have a problem to convert Buffer[] to byte[] and how to playing Buffer[] sample ?

Can someone gives me ideas how to do this?

Thanks !!!

**Comment by saudet** [comment]
If it's a `ByteBuffer`, just cast `samples[0]` to `ByteBuffer` and call `get(byte[])`

**Comment by Jassarpc** [comment]
Thanks ! Yes it's done, but now i would like to play audio from this Buffer[], can you give me ideas using java sound API???

**Comment by saudet** [comment]
Good! Info about Java Sound is here: https://docs.oracle.com/javase/tutorial/sound/

**Comment by saudet** [comment]
There's also this sample: https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java
