### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "ibswresample.so" is 32-bit instead of 64-bit 

### ISSUE THREAD

**Issue by elyonsaber** [bytedeco/javacv#467]
After using ReLinker, I was able to install and run JavaCv 1.2 on some devices in project A.
But for the devices that failed to run JavaCv 1.1 before, 1.2 still doesn't work well. I got error like this
![huawei](https://cloud.githubusercontent.com/assets/15250710/17173106/62f16cb4-542b-11e6-948d-55c26329cfed.png)
CPU info of devices that reports error:
![huaweicpu](https://cloud.githubusercontent.com/assets/15250710/17173246/32a5419c-542c-11e6-8f55-7a0d811ae85d.png)
![minotecpu](https://cloud.githubusercontent.com/assets/15250710/17173248/353912f8-542c-11e6-9c6e-9d79dc1f28ad.jpg)
JavaCPP is updated to 1.2.2 version.

Further more, I am confused that I have another project B also uses JavaCv 1.2, and it could works well on every device including XM Note and HuaWei that was unable to use JavaCv in project A .
build.gradle of project A:
![gradlenotwork](https://cloud.githubusercontent.com/assets/15250710/17174011/db591274-5430-11e6-985c-8e80c745f9df.png)
build.gradle of project B:
![gradlework](https://cloud.githubusercontent.com/assets/15250710/17174009/d9ab640e-5430-11e6-8567-40b155d1ff04.png)
So does it matter with different sdkVersion in different project? Thanks!

**Comment by saudet** [comment]
Ah, so you have devices that don't support 32-bit binaries. We'll need to build 64-bit binaries for those: https://github.com/bytedeco/javacpp-presets/issues/52

**Comment by elyonsaber** [comment]
I checked all dependencies in my project, and the issue is occurred by  [Fresco](https://github.com/facebook/fresco). Fresco has library built for 64 bit architecture, and then the system will look for a 64 bit version of each other library. Since JavaCv don't have 64 bit binaries, the system will report error. I think it is similar to [this](https://github.com/facebook/fresco/issues/361). Hope it will help others!

**Comment by saudet** [comment]
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
