### ISSUE TITLE
greenish shade on the frames after converting from YUV NV21 to BGR format

### ISSUE THREAD

**Issue by YinaZ** [bytedeco/javacv#468]
Hello, 
I'm trying to add some code to RecordActivity.java so that it can do simple face detection. After using cvtColor to convert Mat from YUV NV21 format to BGR format, there appears a greenish shade on every frame of the video. Could anyone give some ideas about how I am doing wrong? Below is the code for the FaceDetector and the screenshot of the video. Thank you very much.

P.S when I trying to convert the NV21 format to GRAY format, all the frames just went black, so if I need it in GRAY format I need to convert it to BGR first and then to GRAY. Any thoughts for this?

![screenshot](https://cloud.githubusercontent.com/assets/20526571/17197140/d89d2758-541e-11e6-8b2b-d25290a617c4.jpg)

```java
private int imageWidth = 320;
private int imageHeight = 240;
private OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();
private CascadeClassifier faceDetector;
yuvImage = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 2);

// ...
FaceDetector(yuvImage);
// ...

public Mat FaceDetector (Frame frame) throws Exception {
  Mat image = converterToMat.convert(frame);
  cvtColor(image, image, COLOR_YUV2BGR_NV21);
 //  cvtColor(image, image, COLOR_RGB2GRAY);
 //  equalizeHist(image, image);
  RectVector faces = new RectVector();
  faceDetector.detectMultiScale(image, faces);
  for (int i = 0; i < faces.size(); i++) {
    Rect face_i = faces.get(i);
    rectangle(image, face_i, new Scalar(0, 255, 0, 255));
  }
  return image;
}
```

**Comment by saudet** [comment]
You're not doing the conversions properly. Try to create your Frame this way instead:
```java
yuvImage = new Frame(imageWidth, imageHeight * 3 / 2, Frame.DEPTH_UBYTE, 2);
```
