### ISSUE TITLE
Apk Size very Large

### ISSUE THREAD

**Issue by vihangptl** [bytedeco/javacv#472]
Hello,
Can any one help me?
My apk size is more than 30 mb after using below three dependencies.
```
compile group: 'org.bytedeco', name: 'javacv', version: '1.1'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.11-0.11', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.6.1-0.11', classifier: 'android-arm'
```
If I remove above dependencies  my apk size hardly reached to 8 mb.
Please help me.

**Comment by saudet** [comment]
Try to add manually only the libraries your code is using.

**Comment by vihangptl** [comment]
manually, you mean .so files?
I have tried using .so file still apk size is more than 30 mb

**Comment by saudet** [comment]
So I guess you will need to make a custom build.

**Comment by saudet** [comment]
Instructions to build from source are here:
https://github.com/bytedeco/javacpp-presets/#build-instructions
