### ISSUE TITLE
** Error in `/home/nisp/autoDeploy/software/jdk-oracle-1.7.0_64//jre/bin/java': munmap_chunk(): invalid pointer: 0x00007f6ee0667200 ***

### ISSUE THREAD

**Issue by NacyLiu** [bytedeco/javacv#473]
@saudet 
i use the ffmpegGrabber to grab the video frame from a online url, here is the code:

FFmpegFrameGrabber grabber = null;
grabber = FFmpegFrameGrabber.createDefault(url);
grabber.start();
while(true) {
      Frame videoFrame  = grabber.grabImage();
      if (videoFrame == null){
              break;
      }
}
grabber.stop();

i got an error like this:
Input #0, flv, from 'rtmp://x.smartcamera.163.com/qingguo-public/163011411000894?wsHost=x.smartcamera.163.com':
  Metadata:
    hasKeyframes    : true
    aacaot          : 1
    hasAudio        : true
    hasVideo        : true
  Duration: N/A, start: 0.048000, bitrate: 570 kb/s
    Stream #0:0: Video: h264 (Main), yuv420p, 1280x720, 524 kb/s, 25 tbr, 1k tbn, 2k tbc
    Stream #0:1: Audio: aac (LC), 16000 Hz, stereo, fltp, 46 kb/s
[flv @ 0x7f6f0400b820] subtitle stream discovered after head already parsed
[h264 @ 0x7f6ef00cc3c0] concealing 25 DC, 25 AC, 25 MV errors in P frame
[h264 @ 0x7f6e9c3da760] concealing 96 DC, 96 AC, 96 MV errors in P frame
[rtmp @ 0x7f6e9c0d63a0] Too short chunk size change packet (0)
[flv @ 0x7f6e9c0d5d80] Packet mismatch 1904564116 11
[rtmp @ 0x7f6ee0001940] Too short chunk size change packet (0)
[h264 @ 0x7f6ee0372260] concealing 121 DC, 121 AC, 121 MV errors in P frame
[flv @ 0x7f6ee00010a0] Packet mismatch 1955776487 11
[h264 @ 0x7f6e982f9d20] concealing 32 DC, 32 AC, 32 MV errors in P frame
[rtmp @ 0x7f6e98001d00] Too short chunk size change packet (0)
[flv @ 0x7f6ef0008660] audio stream discovered after head already parsed
[flv @ 0x7f6ef0008660] Audio codec  is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[flv @ 0x7f6ef0008660] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[flv @ 0x7f6ef0008660] Audio codec  is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[flv @ 0x7f6ef0008660] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[rtmp @ 0x7f6f10001800] Too short chunk size change packet (0)
[h264 @ 0x7f6f1059ab80] error while decoding MB 35 44, bytestream -7
[h264 @ 0x7f6f1059ab80] concealing 94 DC, 94 AC, 94 MV errors in P frame
*** Error in `/home/nisp/autoDeploy/software/jdk-oracle-1.7.0_64//jre/bin/java': munmap_chunk(): invalid pointer: 0x00007f6ee0667200 ***

i am not clear how it raised, and have no idea about how to fix it ...

**Comment by saudet** [comment]
It says right in the error message what you should do:
```
[flv @ 0x7f6ef0008660] Audio codec is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[flv @ 0x7f6ef0008660] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
```
Please try to build FFmpeg from source with all the required codec, and if the problems still happens, then please report the problem upstream.

**Comment by NacyLiu** [comment]
but how this "*** Error in `/home/nisp/autoDeploy/software/jdk-oracle-1.7.0_64//jre/bin/java': munmap_chunk(): invalid pointer: 0x00007f6ee0667200 ***" raised ?

**Comment by saudet** [comment]
Probably some bug in FFmpeg...

**Comment by saudet** [comment]
If you want to be sure, try to use the `ffmpeg` or `ffplay` tool on the command line with the same URL. If you get the same error, it's a bug in FFmpeg. If it works fine, then maybe it's been fixed and we will need to update JavaCV to the latest release of FFmpeg and try it out. Then, if it still doesn't work, then we'll know that it's a problem with Java or JavaCV somewhere.
