### ISSUE TITLE
make an ROI on Mat

### ISSUE THREAD

**Issue by jupitergao** [bytedeco/javacv#475]
I am trying to add overlay on a video . I've got the Mat srcMat from grabber and converter
when in c++, I used

Mat logoMat = imread....;
Mat destMat;
srcMat.copyTo(destMat);
Rect destRC = Rect(0, 0, 70, 70);
Mat destROI = destMat(destRC);
logoMat.copyTo(destROI);

how can i make an ROI with javacv like "Mat destROI = destMat(destRC);"

thank you! thank you! thank you!

**Comment by saudet** [comment]
That's a question about OpenCV, but the answer is easy enough: 
Call `destROI = destMat.apply(destRC)`.
