### ISSUE TITLE
FFmpegFrameRecorder.grabPacket() throws NullPointerException

### ISSUE THREAD

**Issue by markuswilke** [bytedeco/javacv#476]
I'm using FFmpegFrameGrabber and FFmpegFrameRecorder (javacv 1.2) to trim a video.
While recording the first packet, a NullPointerException is thrown in FFmpegFrameRecorder.grabPacket() because ifmt_ctx never got initialized.

My code:

FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(sourceVideo);
FFmpegFrameRecorder recorder =
                        new FFmpegFrameRecorder(targetVideo, 0);
try {
  grabber.start();
  recorder.start();
  avcodec.AVPacket avPacket;
  int grabbedPackets = 0;
  int recordedPackets = 1;
  while (grabbedPackets <= newLastFrame && (avPacket = grabber.grabPacket()) != null) {
   if (newFirstFrame <= grabbedPackets) {
     recorder.recordPacket(avPacket);
   }
   grabbedPackets++;
 }
} catch (Exception e) {
}

**Comment by saudet** [comment]
So initialize by calling the appropriate start() call as shown here:
https://github.com/bytedeco/javacv/blob/master/samples/PacketRecorderTest.java#L61

**Comment by markuswilke** [comment]
Thanks for your comment Samuel,
"recorder.start(grabber.getFormatContext());" did the trick.
Markus
