### ISSUE TITLE
Set UDP port for receiving streaming over RTSP using FFmpegFrameGrabber

### ISSUE THREAD

**Issue by guerinorodella** [bytedeco/javacv#477]
I'm using javacv to capture DVRs image over RTSP/RTP requests and it's working very well on local DVR, the problem is requesting for remote devices. I'm pretty sure the problem is the UDP ports the javacv is opening to receive the streams it's not open to remote access on my machine. Since it's a server machine which will be used over production means, I cannot open all ports. So, **how can I set the proper UDP port the library will open ?**

Here follows my code which I found an example on a StackOverflow:

```
    public static void main(String[] args) throws IOException, FrameGrabber.Exception {
        
        FFmpegFrameGrabber streamGrabber = new FFmpegFrameGrabber( "rtsp://192.168.0.237:554//user=admin&password=123456&channel=3&stream=0.sdp" );
        streamGrabber.start();

        Frame frame = streamGrabber.grabImage();
        BufferedImage img = new Java2DFrameConverter().convert( frame );
        ImageIO.write(img, "jpeg", new File("C://temp//snapshot_hoje.jpeg"));
            
        
    }
```

I would like to do something like:

```
        FFmpegFrameGrabber streamGrabber = new FFmpegFrameGrabber( "rtsp://192.168.0.237:554//user=admin&password=123456&channel=3&stream=0.sdp" );
        streamGrabber.setUdpPort( 5000 );
        streamGrabber.start();
```

Is it possible? Or should I use other class to do this kind of thing?

Also I'm posting my console log errors when trying to do on remote devices.

[rtsp @ 003ff600] UDP timeout, retrying with TCP
[rtsp @ 003ff600] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=1&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1d3ac020] UDP timeout, retrying with TCP
[rtsp @ 1d3ac020] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=2&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1e7749c0] UDP timeout, retrying with TCP
[rtsp @ 1e7749c0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=3&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1e90d640] UDP timeout, retrying with TCP
[rtsp @ 1e90d640] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=4&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1e8b2740] UDP timeout, retrying with TCP
[rtsp @ 1e8b2740] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=5&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1d3aaee0] UDP timeout, retrying with TCP
[rtsp @ 1d3aaee0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=6&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1e92f2a0] UDP timeout, retrying with TCP
[rtsp @ 1e92f2a0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=1&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1d3271c0] UDP timeout, retrying with TCP
[rtsp @ 1d3271c0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.0.237:554//user=admin&password=123456&channel=2&stream=0.sdp':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, none, 90k tbr, 90k tbn
[IMGUTILS @ 1575f440] Picture size 0x0 is invalid
[IMGUTILS @ 1575f404] Picture size 0x0 is invalid
[rtsp @ 1ec32440] UDP timeout, retrying with TCP
[rtsp @ 1ec32440] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options

If I misunderstood my log errors and UDP/TCP closed port being not the problem, please explain me what's going on.
**Notes:** I replaced remote IP address for local ones for security reasons :) 

# UPDATE

I think the problem is not related to UDP port open, the problem might be related to encoding format. I'm saying that because using ffmpeg tool on Linux console, I'm able to capture a snapshot using same RTSP URL on above device.

Here follows the code used to capture the snapshot on ffmpeg tool:
```
#!/bin/sh
ffmpeg -loglevel debug -i 'rtsp://192.168.0.237:554/user=admin&password=123456&channel=1&stream=1.sdp' -vframes 1 -r 1 /root/screen_shot.jpeg
```
I notice it use some param like `-vframe 1` and `-r 1`. Checking [ffmpeg docs](https://ffmpeg.org/ffmpeg.html#Video-Options), those param are respectively for frame numbers and frame rates.

> -vframes number (output)
> Set the number of video frames to output. This is an alias for -frames:v.
> 
> -r[:stream_specifier] fps (input/output,per-stream)
> Set frame rate (Hz value, fraction or abbreviation).
> 
> As an input option, ignore any timestamps stored in the file and instead generate timestamps assuming constant frame rate fps. This is not the same as the -framerate option used for some input formats like image2 or v4l2 (it used to be the same in older versions of FFmpeg). If in doubt use -framerate instead of the input option -r.
> 
> As an output option, duplicate or drop input frames to achieve constant output frame rate fps.

So, I update my code setting those param like this:

```
            streamGrabber = new FFmpegFrameGrabber( "rtsp://192.168.0.237:554//user=admin&password=123456&channel=1&stream=0.sdp" );
            streamGrabber.setFrameNumber( 1 ); 
            streamGrabber.setFrameRate( 1 ); 
            streamGrabber.start();
```
I also changed ffmpeg script removing -vframe and -r parameters and it worked as well.
Also set same codec, frames and resolution settings on my local and remote device but it doesn't works on Javacv.

**Comment by saudet** [comment]
How does one specify that port on the command line with the `ffmpeg` tool?

**Comment by guerinorodella** [comment]
You got me! I'll search it.

Does Javacv is a wrapper for a C/C++ library using jni or jna to interpret C code or does it call ffmpeg on a Java Process like in command line?

**Comment by saudet** [comment]
Well according to FFmpeg's documentation, we can add min_port and max_port to the URL: 
https://www.ffmpeg.org/ffmpeg-protocols.html#rtsp
I'm guessing this is what you are looking for, but if not, please ask the developers of FFmpeg.

**Comment by saudet** [comment]
And no, JavaCV doesn't use the `ffmpeg` command line tool.

**Comment by guerinorodella** [comment]
According to your link ( https://www.ffmpeg.org/ffmpeg-protocols.html#rtsp ), I can `set min_port` and `max_port` as an RTSP option. In Javacv is the following the equivalent: 

```
streamGrabber = new FFmpegFrameGrabber( "rtsp://192.168.0.237:554//user=admin&password=123456&channel=1&stream=0.sdp" );
            streamGrabber.setOption(  "min_port", "5000" );
            streamGrabber.setOption(  "max_port", "5001" );
            streamGrabber.start();
```
If so, there are constants values defined for those options key? Like `avcodec` class?

**Comment by saudet** [comment]
Yes that looks alright, but like I said, if it doesn't work, please contact
the authors of FFmpeg.
