### ISSUE TITLE
CUDA openCV 3.1 Object Detection code unavailable in JavaCV 1.2 

### ISSUE THREAD

**Issue by noahf19** [bytedeco/javacv#481]
Hi!

The CUDA object detection code for opencv 3.1 is not currently available in JavaCV 1.2. I was wondering if there was a near term plan to add that in.

**Comment by fjank** [comment]
I am currently beginning to work go get (at least part of) the cuda module available in javacv. When I have something that works (for the couple of methods I need), I will make sure to add a pull request. Estimate that I have something basic ready in January 2017.

**Comment by noahf19** [comment]
Thanks for the heads up. It will be interesting if the detection is significantly accelerated vs a multi-core implementation. I've seen several papers argue the latter is faster. 

Noah

**Comment by archenroot** [comment]
Can you share such papers?

[Look for example here](http://queue.acm.org/detail.cfm?id=2206309)

**Comment by fjank** [comment]
I have something that works now, will create a pull request as soon as i have cleaned it up a bit. For the one method i have tried with (calcOpticalFlowPyrLK) the performance on my system was slightly worse. That method was quite fast with my parameters already (4.5ms), while with the cpu to gpu copy and back again, multicore cpu, and a rather slow mobile gpu, the performance went a bit down to about 6ms. But i can parallellize my code path using gpu with another cpu intensive function, so for me the 4.5ms will disappear. 
Dense optical flow has also been tested: before about 450ms pr frame, with gpu about 30-40 ms pr frame.

**Comment by archenroot** [comment]
Question: How is this project related to [OpenPNP-OpenCV](https://github.com/openpnp/opencv)? I have now little chaos why there are 2 bindings available, or this is related project?

Thanks for explanation.

**Comment by saudet** [comment]
It's not related. They are not creating bindings for Java.

**Comment by archenroot** [comment]
Ok, then why they say on the site (citation):

> OpenCV 3.2.0 (packaged by OpenPnP)
> 
> OpenCV Java bindings packaged with native libraries, seamlessly delivered as a turn-key Maven dependency.

**Comment by saudet** [comment]
They are just using the bindings for Java that come with OpenCV.

**Comment by archenroot** [comment]
I got it, on my Gentoo system I installed the opencv with java support, so in lib path it generated additional jar file to linux so library. But this Java binding is very similar or same. I mean **what is the key difference** between javacpp way and opencv java implementations?

**Comment by saudet** [comment]
Answer is here: http://bytedeco.org/faq/

**Comment by saudet** [comment]
As per the commit above, I've enabled CUDA builds, and will soon be merging bytedeco/javacpp-presets#416.

**Comment by saudet** [comment]
Thanks to @SamCarlberg, it is now available in the newly released version 1.4. Enjoy!
