### ISSUE TITLE
FFmpegFrameGrabber audio missing during grabframe()

### ISSUE THREAD

**Issue by chiragsheta** [bytedeco/javacv#482]
I am adding text in video by adding text in frame,

`Frame frame = mFFmpegFrameGrabber.grabFrame(true, true, true, false);`

I am accessing frame by using above line and also i have added text on image, but i am not getting audio from frame. I have checked `FFmpegFrameGrabber.grabFrame(true, true, true, false)` and i found that if i am requesting for audio and video then it only return video because of it's in `elseif` condition.

[L676: Check for video `doVideo` and in L699: Check for Audio `doAudio` in else if](https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameGrabber.java#L676)

This will only return either Audio or Video. How can i get both audio and video in one frame?

Thanks

**Comment by saudet** [comment]
No, that returns both audio and video frames.

**Comment by chiragsheta** [comment]
I am trying to get Audio buffer by `Buffer[] b = frame.samples;` after grab frame but it always return's null;

**Comment by chiragsheta** [comment]
Here is my code for simple record video from grabber but still not getting audio.

```
FFmpegFrameGrabber mFFmpegFrameGrabber = new FFmpegFrameGrabber(ffmpeg_input);
mFFmpegFrameGrabber.setFormat("mp4");

try {
                mFFmpegFrameGrabber.start();
                FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(ffmpeg_op, mFFmpegFrameGrabber.getImageWidth(), mFFmpegFrameGrabber.getImageHeight(), mFFmpegFrameGrabber.getAudioChannels());
               
                /*Video total frame no*/
                int noFrames = mFFmpegFrameGrabber.getLengthInFrames();

                 recorder.setFormat("mp4");
                 recorder.setVideoBitrate(mFFmpegFrameGrabber.getVideoBitrate());
                 recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
                 recorder.setFrameRate(mFFmpegFrameGrabber.getFrameRate());

                    
                 recorder.setAudioBitrate(mFFmpegFrameGrabber.getAudioBitrate());
                 recorder.setSampleRate(mFFmpegFrameGrabber.getSampleRate());
                 recorder.setAudioChannels(mFFmpegFrameGrabber.getAudioChannels());
                 recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);

                 recorder.start();


                    for (int i = 1; i < noFrames; i++) {
                             mFFmpegFrameGrabber.setFrameNumber(i);
                             Frame frame = mFFmpegFrameGrabber.grabFrame(true, true, true, false);
                  
                             recorder.record(frame);
                   }
recorder.stop();
} catch (Exception e) {
           e.printStackTrace();
}




```

**Comment by saudet** [comment]
Don't call setFrameNumber(), that will solve this issue.

**Comment by chiragsheta** [comment]
Thanks @saudet 
Problem is now solved. you are the one who can solve any problem.
Thanks again
