### ISSUE TITLE
FFmpegFrameGrabber getImageWidth() & getImageHeight() returns always 0

### ISSUE THREAD

**Issue by Luonic** [bytedeco/javacv#484]
![2016-08-20](https://cloud.githubusercontent.com/assets/13236173/17833255/a1909ca8-6720-11e6-937c-a89c729252ec.jpg)
I use width and height variables for creating recorder later.
FrameGrabber always returns zero values but it works and returns frames.
What am I doing wrong?

**Comment by saudet** [comment]
We need to call `start()` to have it actually open the file and read those values.

**Comment by Luonic** [comment]
@saudet thanks
