### ISSUE TITLE
Can someone give me a best way to play audio with a minimum noise?

### ISSUE THREAD

**Issue by Jassarpc** [bytedeco/javacv#485]
Hi,
I've try to play audio sample grabbed from FFmpegGragger grab()
i'hear the song, the song is there but it comes with a lot of noise.

Here is my code

`try {
            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("D:\\goodbye.mp4");
         
            grabber.start();
            grabber.getImageWidth();
            OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
            
            Frame f;
            while((f = grabber.grab())!= null)
            {
                try 
               {
                IplImage ipl = converter.convertToIplImage(f);
                BufferedImage buff = IplImageToBufferedImage(ipl);
                Graphics graf = jPanel1.getGraphics();
                Buffer[] b = f.image;
                Buffer[] audioBuffer = null;
                if(f.samples!=null)
                {
                audioBuffer = f.samples;
                
                if(audioBuffer[0] instanceof FloatBuffer) 
                  {
                    Buffer flBuf = audioBuffer[0];
                    FloatBuffer fBuff = (FloatBuffer)flBuf;
                    int len = fBuff.capacity();
                    ShortBuffer sBuff = ShortBuffer.allocate(len*2);
                    ByteBuffer bBuff = ByteBuffer.allocate(len*4);
                    bBuff.asFloatBuffer().put(fBuff);
                    byte[] byteArr = bBuff.array();
                    SourceDataLine playLine = AudioSystem.getSourceDataLine(new   AudioFormat(AudioFormat.Encoding.PCM_SIGNED,grabber.getSampleRate(),16,2,4,grabber.getSampleRate(),true));
                    
                    
                    playLine.open();
                    playLine.start();
                    playLine.write(byteArr, 0, byteArr.length);
                    fBuff.clear();
                  }                    
                }
                
                byte[] imageInByte ;
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(buff, "jpg", baos);
		baos.flush();
		imageInByte = baos.toByteArray();
                InputStream in = new ByteArrayInputStream(imageInByte);
		BufferedImage bImageFromConvert = ImageIO.read(in);
                
               
                   graf.drawImage(buff,0,0,getWidth(), getHeight(),0,0,buff.getWidth(),buff.getHeight(),null);
                   
               
               }catch(Exception e){
               
               System.out.println(e.getMessage());
               continue;
               }
               Thread.sleep(1000/180);
                
            }
            }catch (InterruptedException | FrameGrabber.Exception ex) {
            Logger.getLogger(jave.class.getName()).log(Level.SEVERE, null, ex);
        }`

If possible give your comments about my code and the right to way to done this fine!
Many thanks!!!

**Comment by saudet** [comment]
Since you have float data, you're going to need to use `AudioFormat.Encoding.PCM_FLOAT`.

**Comment by Jassarpc** [comment]
When i try to use PCM_FLOAT it say
Error
line with format pcm_float .... not supported
How to solve this?

**Comment by saudet** [comment]
If your version of Java doesn't suppose `float` samples, you're going to need to convert them to `short` first. This is something that we can do with FFmpeg and it's already on the to-do list: https://github.com/bytedeco/javacv/issues/18 If you would like to make a contribution it would be very welcome!

**Comment by Jassarpc** [comment]
I  would like to make a contribution!

**Comment by saudet** [comment]
Ok, that's cool. There's some code in `FFmpegFrameRecorder.java` that already does resampling by calling `swr_convert()`. We would simply need to do something similar in `FFmpegFrameGrabber.java`. Could you start looking at that and let me know if you have any questions?
