### ISSUE TITLE
CvScalar Not able to set Alpha

### ISSUE THREAD

**Issue by chiragsheta** [bytedeco/javacv#489]
I am trying to add text on frame for that i used
`cvPutText((org.bytedeco.javacpp.helper.opencv_core.CvArr) iplImage, str, cvPoint, cvFont, cvScalar);`

text adding with proper color but `cvScalar` not able to set alpha to add text with transparency.
I have tried below but no one is working to set transparency to text.

`CvScalar cvScalar = new CvScalar(10, 16, 197, 0.3);` 

`CvScalar cvScalar = CvScalar.ONEHALF;`

```
cvScalar.setVal(0, 10);
cvScalar.setVal(1, 16);
cvScalar.setVal(2, 197);
cvScalar.setVal(3, 0.3);
```

and insted of `0.3` tried between `0 - 255` but not working.
Is there problem with native lib?

Thanks

**Comment by saudet** [comment]
OpenCV doesn't support alpha blending. Use Java 2D for that.
