### ISSUE TITLE
Issue with Maven and OS X UnsatisfiedLinkError org.bytedeco.javacpp.opencv_core

### ISSUE THREAD

**Issue by hfjn** [bytedeco/javacv#49]
Hi. I'm trying to use JavaCV for an easy Jetty Server. It builds just fine, but when initializing the Class that uses JavaCV the first time the whole thing crashes with:

`java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1764)
    at java.lang.Runtime.loadLibrary0(Runtime.java:823)
    at java.lang.System.loadLibrary(System.java:1044)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:535)
    at org.bytedeco.javacpp.Loader.load(Loader.java:410)
    at org.bytedeco.javacpp.Loader.load(Loader.java:353)
    at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at org.bytedeco.javacpp.Loader.load(Loader.java:385)
    at org.bytedeco.javacpp.Loader.load(Loader.java:353)
    at org.bytedeco.javacpp.opencv_core$Algorithm.<clinit>(opencv_core.java:8797)
    at uos.jhoffjann.server.logic.OCV.<init>(OCV.java:22)`

I got the JavaCV libraries as described [here](http://bytedeco.org/download/). Am I just missing the `platform.dependecies`part? I wasn't able to find a Maven property which is called like that, so I couldn't activate it.

This is the relevant part in my pom.xml:

```
<dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>javacpp</artifactId>
        <version>0.9</version>
    </dependency>
     <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>opencv</artifactId>
        <version>2.4.9-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>ffmpeg</artifactId>
        <version>2.3-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>flycapture</artifactId>
        <version>2.6.3.4-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>libdc1394</artifactId>
        <version>2.2.2-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>libfreenect</artifactId>
        <version>0.5-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>videoinput</artifactId>
        <version>0.200-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>artoolkitplus</artifactId>
        <version>2.3.0-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>flandmark</artifactId>
        <version>1.07-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>fftw</artifactId>
        <version>3.3.4-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>gsl</artifactId>
        <version>1.16-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>llvm</artifactId>
        <version>3.4.2-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>leptonica</artifactId>
        <version>1.71-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco.javacpp-presets</groupId>
        <artifactId>tesseract</artifactId>
        <version>3.03-rc1-0.9</version>
    </dependency>
    <dependency>
        <groupId>org.bytedeco</groupId>
        <artifactId>javacv</artifactId>
        <version>0.9</version>
    </dependency>
```

`
I would be extremely glad for any help.

**Comment by gaurav-chawla** [comment]
Add opencv-*os*.jar   in your class path.Copy os related jar i.e. for mac opencv-macosx-x86_64.jar inside /System/Library/Java/Extensions/

**Comment by SaleemKhair** [comment]
@jhoffjann can you please provide what exactly you did, 
I am facing the same issue 
thanks.

**Comment by jhoffjann** [comment]
@SaleemKhair I ran into other problems later in the project. I eventually switched to OpenCV and got my project running with that. Back then I did it like that: http://aufeinwort.org/2014/10/get-opencv-up-and-running-with-intellij-and-mac-os-x/

**Comment by namannigam** [comment]
@hfjn The last link seems to be broken. We want to switch to using openCv as well, jsut curious to see what changes did you bring.

**Comment by hfjn** [comment]
@namannigam [You can find it here](https://jannikhoffjann.de/2014/10/get-opencv-up-and-running-with-intellij-and-mac-os-x/)
