### ISSUE TITLE
indexer.get just waits for nothing

### ISSUE THREAD

**Issue by Luonic** [bytedeco/javacv#490]
Hello!
Today I benchmarked my code and saw a strange thing
I have following loop in my code:

```java
Mat weights1 = new Mat(height, width, CV_32F);
        Mat weights2 = new Mat(height, width, CV_32F);
        FloatBufferIndexer weights1Indexer = weights1.createIndexer();
        FloatBufferIndexer weights2Indexer = weights2.createIndexer();
        float weight;
        float flowX, flowY;
        int s = width * height;
        for (int i = 0; i < s; i++) {
            flowX = opticalFlowIndexer.get(i * 2);
            flowY = opticalFlowIndexer.get(i * 2 + 1);
            weight = Math.min((float) Math.sqrt(flowX * flowX + flowY * flowY), 1.0f);
            weights1Indexer.put(i, weight);
            weights2Indexer.put(i, 1 - weight);
        }
```
And in benchmark I saw this:
![2016-08-29](https://cloud.githubusercontent.com/assets/13236173/18036930/4eb76a00-6d80-11e6-9c0b-c251db40ea52.jpg)
Nexus 5, Android 6.0.1
May it be benchmarking overhead? Or this is javacv problem?
This loop runs in several threads, one thread per core. Threads fully independent.
Thanks.

**Comment by saudet** [comment]
Might be a pause for the garbage collector. Are you sure it is not executing during the loop?
