### ISSUE TITLE
mixing 2 audio with javacv

### ISSUE THREAD

**Issue by sajadmartiny** [bytedeco/javacv#492]
hi, i tried recording but return the error org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -13: Could not open '/storage/emulated/0/stream.mp4' 
i use this [https://github.com/bytedeco/sample-projects/blob/master/JavaCV-android-example/app/src/main/java/org/bytedeco/javacv_android_example/record/RecordActivity.java](url)

and another question , i wanna know , can i recording voice when playing music with javacv?

**Comment by saudet** [comment]
Please also provide the error message that shows up on the console.

**Comment by sajadmartiny** [comment]
`	08-31 15:57:57.947 9097-9097/com.javactest W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -13: Could not open '/storage/emulated/0/stream.mp4'
	08-31 15:57:57.947 9097-9097/com.javactest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:700)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:294)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at com.javactest.RecordActivity.startRecording(RecordActivity.java:237)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at com.javactest.RecordActivity.onClick(RecordActivity.java:316)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at android.view.View.performClick(View.java:4466)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at android.view.View$PerformClick.run(View.java:18537)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.os.Looper.loop(Looper.java:136)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5102)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
	08-31 15:57:57.950 9097-9097/com.javactest W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	08-31 15:57:57.950 9097-9097/com.javactest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	08-31 15:57:57.951 9097-9097/com.javactest W/System.err:     at dalvik.system.NativeStart.main(Native Method)	08-31 15:57:57.947 9097-9097/com.javactest W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -13: Could not open '/storage/emulated/0/stream.mp4'
	08-31 15:57:57.947 9097-9097/com.javactest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:700)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:294)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at com.javactest.RecordActivity.startRecording(RecordActivity.java:237)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at com.javactest.RecordActivity.onClick(RecordActivity.java:316)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at android.view.View.performClick(View.java:4466)
	08-31 15:57:57.948 9097-9097/com.javactest W/System.err:     at android.view.View$PerformClick.run(View.java:18537)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.os.Looper.loop(Looper.java:136)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5102)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
	08-31 15:57:57.949 9097-9097/com.javactest W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
	08-31 15:57:57.950 9097-9097/com.javactest W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	08-31 15:57:57.950 9097-9097/com.javactest W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	08-31 15:57:57.951 9097-9097/com.javactest W/System.err:     at dalvik.system.NativeStart.main(Native Method)`

**Comment by sajadmartiny** [comment]
`		org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -13: Could not open '/storage/emulated/0/stream.mp4'
	     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:700)
	     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:294)
	     at com.javactest.RecordActivity.startRecording(RecordActivity.java:237)
	     at com.javactest.RecordActivity.onClick(RecordActivity.java:316)
	     at android.view.View.performClick(View.java:4466)
	     at android.view.View$PerformClick.run(View.java:18537)
	     at android.os.Handler.handleCallback(Handler.java:733)
	     at android.os.Handler.dispatchMessage(Handler.java:95)
	     at android.os.Looper.loop(Looper.java:136)
	     at android.app.ActivityThread.main(ActivityThread.java:5102)
	     at java.lang.reflect.Method.invokeNative(Native Method)
	     at java.lang.reflect.Method.invoke(Method.java:515)
	     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	     at dalvik.system.NativeStart.main(Native Method)`

**Comment by saudet** [comment]
I said *on the console*, but you're using Android here, so please call `FFmpegLogCallback.set()` and check the error messages that appear in the Android log.

**Comment by sajadmartiny** [comment]
sorry man ,  
`09-01 12:47:44.726 17298-17298/com.javactest I/System.out: Output #0, mp4, to '/storage/emulated/0/stream.mp4':
09-01 12:47:44.727 17298-17298/com.javactest I/System.out: Output #0, mp4, to '/storage/emulated/0/stream.mp4':
09-01 12:47:44.730 17298-17298/com.javactest I/System.out:     Stream #0:0
09-01 12:47:44.730 17298-17298/com.javactest I/System.out:     Stream #0:0
09-01 12:47:44.730 17298-17298/com.javactest I/System.out: : Unknown: none (mpeg4)
09-01 12:47:44.730 17298-17298/com.javactest I/System.out: : Unknown: none (mpeg4)
09-01 12:47:44.731 17298-17298/com.javactest I/System.out:     Stream #0:1
09-01 12:47:44.731 17298-17298/com.javactest I/System.out:     Stream #0:1
09-01 12:47:44.731 17298-17298/com.javactest I/System.out: : Unknown: none (aac)
09-01 12:47:44.731 17298-17298/com.javactest I/System.out: : Unknown: none (aac)
09-01 12:47:44.813 17298-17298/com.javactest I/System.out: [aac @ 0x550f3b80] Qavg: NaN
09-01 12:47:44.813 17298-17298/com.javactest I/System.out: [aac @ 0x550f3b80] Qavg: NaN`

**Comment by sajadmartiny** [comment]
sorry for mistake 
`I/System.out: Output #0, mp4, to '/storage/emulated/0/stream.mp4':
I/System.out: Output #0, mp4, to '/storage/emulated/0/stream.mp4':
I/System.out:     Stream #0:0
I/System.out:     Stream #0:0
I/System.out: : Unknown: none (mpeg4)
I/System.out: : Unknown: none (mpeg4)
I/System.out:     Stream #0:1
I/System.out:     Stream #0:1
I/System.out: : Unknown: none (aac)
I/System.out: : Unknown: none (aac)
I/System.out: [aac @ 0x54fb8920] Qavg: NaN
I/System.out: [aac @ 0x54fb8920] Qavg: NaN`

**Comment by saudet** [comment]
It just looks like your app doesn't have write access to the storage...

**Comment by sajadmartiny** [comment]
i set permission in run time and fix it ,another question , i can mixing 2 audio with javacv ? 
Thank for answer

**Comment by saudet** [comment]
We could easily do that with FFmpegFrameFilter, but we first need to add support for audio frames. Please consider making a contribution

**Comment by saudet** [comment]
Support for audio frames has been added so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/ 

We can use [amovie](https://ffmpeg.org/ffmpeg-filters.html#amovie) with the [amix](https://ffmpeg.org/ffmpeg-filters.html#amix) filter to mix 2 audio streams.

**Comment by huunhan18pro** [comment]
Hi @saudet , Do you have an FFmpegFrameFilter sample to add additional audio to a video?
`FFmpegFrameFilter("movie=" + video.mp4 + " + ???", outPutWith, outPutHeight);`
Thank you :)

**Comment by saudet** [comment]
@huunhan18pro If `amovie` doesn't work because you need to input multiple frames from some other source, that's something that still needs to be done, see issue #955.

**Comment by huunhan18pro** [comment]
I found a command to add background music to a video but I don't know how to do like that by this library. :(

` String cmd = "-i " + video + " -i " + audio + " -filter_complex [0:a]volume=1[a0];[1:a]volume=1[a1];[a0][a1]amix=inputs=2[a] -map 0:v -map [a] -c:v copy -c:a aac";`

**Comment by saudet** [comment]
@huunhan18pro `filter_complex` -> Again, this is issue #955.

**Comment by saudet** [comment]
I've implemented support for multiple inputs in commit https://github.com/bytedeco/javacv/commit/3c92eef6e3aa21eca170fc8022fd41254cfcc452, so we can now use a filter graph like `[0:a][1:a]amix=inputs=2[a]`, which should do the same thing as `amerge` as used in this sample code: https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L163

Please give it a try with the snapshots: http://bytedeco.org/builds/ Thanks!
