### ISSUE TITLE
UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by XSparter** [bytedeco/javacv#496]
Hi, i have this classic problem. Internet can't help me i don't know why, I have finded a command line "-Dplatform.dependencies=true", but i don't know where is this terminal.
Comeon can help me? I use Windows 10 x64 
javacv is installed with maven.
It's not the first time this library give me a lot of problem.

**Comment by saudet** [comment]
Since you're on Windows, please let me know what you get when running this:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by XSparter** [comment]
Loader cannot be resolved
	jniopencv_core cannot be resolved to a type
	Loader cannot be resolved

**Comment by saudet** [comment]
http://bytedeco.org/javacpp/apidocs/

**Comment by XSparter** [comment]
thanks, i try and updae you. Now i'm at work, but thanks for you super-fast reply :)

**Comment by mitesh019** [comment]
plz help me i have same project but in marvin framework program how can i solve that problem

**Comment by saudet** [comment]
@mitesh019 What does Dependency Walker say in your case?

**Comment by mitesh019** [comment]
how to solve this type of error

no jniopencv_core in java.library.path

plz help me

**Comment by saudet** [comment]
Guys, please refer to https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows
