### ISSUE TITLE
Compilation error when building javacv on Raspberry Pi

### ISSUE THREAD

**Issue by mpatronska** [bytedeco/javacv#497]
Getting the following error when building javacv on Raspberry Pi. Can you please advise how it can be resolved? I checked that it's on the 'dot' - UByteIndexer.create((byte[])array, sizes, strides)**.**indexable(this) in Frame.java

> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[137,93] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.UByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[138,98] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.UByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[139,122] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.UByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[141,92] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.ByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[142,97] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.ByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[143,121] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.ByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[145,95] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.UShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[146,100] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.UShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[147,125] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.UShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[149,94] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.ShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[150,99] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.ShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[151,124] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.ShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[153,90] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.IntIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[154,95] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.IntIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[155,118] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.IntIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[157,92] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.LongIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[158,97] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.LongIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[159,121] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.LongIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[161,94] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.FloatIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[162,99] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.FloatIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[163,124] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.FloatIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[165,96] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.DoubleIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[166,101] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.DoubleIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[167,127] cannot find symbol
> symbol: method indexable(org.bytedeco.javacv.Frame)
> location: class org.bytedeco.javacpp.indexer.DoubleIndexer
> [INFO] 24 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:18 min
> [INFO] Finished at: 2016-09-04T15:40:35+00:00
> [INFO] Final Memory: 24M/94M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project javacv: Compilation failure: Compilation failure:
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[137,93] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.UByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[138,98] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.UByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[139,122] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.UByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[141,92] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.ByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[142,97] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.ByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[143,121] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.ByteIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[145,95] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.UShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[146,100] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.UShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[147,125] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.UShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[149,94] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.ShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[150,99] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.ShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[151,124] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.ShortIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[153,90] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.IntIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[154,95] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.IntIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[155,118] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.IntIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[157,92] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.LongIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[158,97] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.LongIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[159,121] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.LongIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[161,94] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.FloatIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[162,99] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.FloatIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[163,124] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.FloatIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[165,96] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.DoubleIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[166,101] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.DoubleIndexer
> [ERROR] /home/pi/opencv-3.1.0/release/javacv/src/main/java/org/bytedeco/javacv/Frame.java:[167,127] cannot find symbol
> [ERROR] symbol: method indexable(org.bytedeco.javacv.Frame)
> [ERROR] location: class org.bytedeco.javacpp.indexer.DoubleIndexer
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by saudet** [comment]
The versions in the pom.file don't match right now. Sorry about that.

Please don't open duplicate issues on purpose.
