### ISSUE TITLE
User defined key-value meta data per frame in mp4

### ISSUE THREAD

**Issue by miketrab** [bytedeco/javacv#500]
Hi,

I'm looking to add custom key-value meta data per frame whilst recording screen captures of an application. The output would be a mp4 movie (H264). Using FFmpegFrameRecorder.

How is this feasible using javacv?  

Thanks!
Michael

**Comment by saudet** [comment]
Sure, just call `FrameRecordet.setMetadata()`

**Comment by miketrab** [comment]
Hi Samuel,

Thanks. The idea would be to attach separate meta-data for every frame. Would the setMetadata() do this? 

Also how can a grabber(?) be used to retrieve this per frame meta-data?

Thanks,
Michael

**Comment by saudet** [comment]
Metadata doesn't work on a per frame basis. I'm sure there are some formats that support something like that, but nothing that's really standard that I know of.

**Comment by miketrab** [comment]
That's what I understood after while. So I tried to do it 'virtually'. Please see #502
