### ISSUE TITLE
User defined key-value meta data in mp4 not working

### ISSUE THREAD

**Issue by miketrab** [bytedeco/javacv#502]
Hi,

Whilst trying the code below, I'm not getting the hoped for output of:
test1
test2

The keys are really user-defined strings. Adding one meta data with key 'title' works.

Any ideas? Thanks.
Michael

       try {

            FFmpegFrameRecorder recorder = new
                    FFmpegFrameRecorder("test2.mp4", 640, 480);
            recorder.start();
            //first frame metadata
            recorder.setMetadata(1+"mykey", "test1");
            recorder.record(new Frame(640, 480, 8, 1));

            //second frame metadata
            recorder.setMetadata(2+"mykey", "test2");
            recorder.record(new Frame(640, 480, 8, 1));
            recorder.stop();

            FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("test2.mp4");
            grabber.start();
            System.out.println(grabber.getMetadata(1+"mykey"));
            System.out.println(grabber.getMetadata(2+"mykey"));
        }
        catch (Exception ex){
            ex.printStackTrace();
        }

**Comment by saudet** [comment]
I don't think the mp4 format supports custom metadata. If you want to be sure, you should check the documentation of FFmpeg and/or ask the developers.

**Comment by miketrab** [comment]
In the end something like this https://trac.ffmpeg.org/ticket/2579  or this https://ffmpeg.org/pipermail/ffmpeg-devel/2016-January/187345.html (both the encoding and decoding) would be relevant for my case. It's not about drones for me.

**Comment by saudet** [comment]
You probably would need to use the MPEGTS format though, and not MP4. In any case, we would also need to add an appropriate API to FFmpegFrameGrabber and FFmpegFrameRecorder, just like for subtitles.

**Comment by miketrab** [comment]
First of all, many thanks for your quick and patient responses. As indicated, I'm quite a layman on matters of video processing. The JavaCV libraries are just great, also as educational tool. I'm trying to connect this field with the geospatial realm.

Indeed, for both cases, the API would need something equivalent to record Frame/Audio and grab Frame/Audio.
