### ISSUE TITLE
[Question] HOGDescriptor.detectMultiScale does not use multi-core?

### ISSUE THREAD

**Issue by JieZou1** [bytedeco/javacv#506]
Hi, 

I have made HOGDescriptor.detectMultiScale working. Many thanks for the excellent library. I am using version 3.1.0-1.2, grabbed from Maven, running on Windows 7.

Everything looks good, except that inside the function, the algorithm doesn't seem running in parallel. Is there a way that I could tell the function to run in parallel mode, such that all the cores available could be used? BTW, the original OpenCV, by default, runs the detection in parallel.

Best Regards
Jie

**Comment by saudet** [comment]
It should run in parallel yes. Do you have some sample code that isn't working that I could try here to fix this issue?

**Comment by JieZou1** [comment]
Below are my code segments related to HOGDescriptor.detectMultiScale. The svmModel is a large float[], which I have attached as a ZIP file
[svm_model.zip](https://github.com/bytedeco/javacv/files/470549/svm_model.zip)
. If you want to use this svmModel, the img needs to be in size of 64x64.


1. Define and initialize hog with svm_model:

        opencv_core.Size winSize_64 = new opencv_core.Size(64, 64);
        opencv_core.Size blockSize = new opencv_core.Size(16, 16);
        opencv_core.Size blockStride = new opencv_core.Size(8, 8);
        opencv_core.Size cellSize = new opencv_core.Size(8, 8);
        int nbins = 9;

        hog = new HOGDescriptor(winSize_64, blockSize, blockStride, cellSize, nbins);
        hog.setSVMDetector(new opencv_core.Mat(new FloatPointer(svmModel)));

2. Then, call detectMultiScale function

        double hitThreshold = 0;	//Threshold for the distance between features and SVM classifying plane.
        opencv_core.Size winStride = new opencv_core.Size(8, 8); //Sliding window step, It must be a multiple of block stride
        opencv_core.Size padding = new opencv_core.Size(0, 0);	//Adds a certain amount of extra pixels on each side of the input image
        double scale0 = 1.05;			//Coefficient of the detection window increase
        int groupThreshold = 2;
        boolean useMeanShiftGrouping = false;

        opencv_core.RectVector rectVector = new opencv_core.RectVector();			
        DoublePointer dp = new DoublePointer();
        hog.detectMultiScale(img, rectVector, dp, hitThreshold, winStride, padding, scale0, groupThreshold, useMeanShiftGrouping);

**Comment by saudet** [comment]
64x64 seems to too small. When I pass it 512x512 images, my CPU usage jumps to 100%, so I think it's working as it should. If you think it isn't, then please file an issue at https://github.com/opencv/opencv/issues Thanks!

**Comment by JieZou1** [comment]
@saudet  

Just to make it clear, it is the svm model which is trained with 64x64 patches. Images with any size can be used for calling the detectMultiScale function.

Parallel processing is on the input images with any size, not on the 64x64 training patches. So, with larger sized input images, we should be able to see  100% CPU usage, right? But, it seems that I don't see that on my machine. In any case, thanks for your information.

**Comment by saudet** [comment]
Like I said, it uses 100% of my CPU with 512x512 images on my machine (Windows 10). I am not doing anything special. Maybe you are doing something wrong setting up your pom.xml file, I don't know. You have not shown me the content of your pom.xml file, neither have you explained how you are running your application, or on what kind of data you are using it. Basically, you have not provided a self-contained example to reproduce the issue. I cannot fix something that you are not willing to show me!

**Comment by JieZou1** [comment]
I am sorry, it certainly is not a secret project, but the codes related to the HOGDescriptor.detectMultiScale are buried in this larger project. I will check it again. If I do still have the problem, I will show you a self-contained example. Many thanks for the quick responses.

**Comment by JieZou1** [comment]
Okay, I have tested again, and you are right, the function does behave as expected. I am not sure why my first observation is not the case and I can't reproduce it now. Sorry for the incorrect reporting.

**Comment by JieZou1** [comment]
Okay, I have tested again, and you are right, the function does behave as expected. I am not sure why my first observation is not the case and I can't reproduce it now. Sorry for the incorrect reporting.

**Comment by JieZou1** [comment]
Okay, I have tested again, and you are right, the function does behave as expected. I am not sure why my first observation is not the case and I can't reproduce it now. Sorry for the incorrect reporting.

**Comment by JieZou1** [comment]
Okay, I have tested again, and you are right, the function does behave as expected. I am not sure why my first observation is not the case and I can't reproduce it now. Sorry for the incorrect reporting.

**Comment by saudet** [comment]
No problem! Glad to hear it works as expected :)

**Comment by JieZou1** [comment]
I think I understand what happens in my experiments.

When I just start, the SVM model for detectMultiScale is not well-trained yet. I do see the function takes longer time to return, and the parallelism is not obvious.

After several iterations of bootstrapping, the SVM model is better and better. Then, I do see the function returns faster and faster. The CPU usage is also more and more approaching 100%.

It seems to me that the parallelism is related to the SVM model quality. This is very interesting and I do not completely understand it. Could anyone explain this? Many thanks.

**Comment by saudet** [comment]
FYI, sounds like a question for http://answers.opencv.org/questions/
