### ISSUE TITLE
Watermark on livestream in Android Recorder

### ISSUE THREAD

**Issue by y4nnick** [bytedeco/javacv#507]
I am using the Android Record Activity to stream to Facebook live.
I now wanna add simple image overlays (and text in the future).

I already tried with an FFmpegFrameFilter:

Start up code (path is ` Environment.getExternalStorageDirectory().getAbsolutePath()` :
`   filter = new FFmpegFrameFilter("movie="+path+"/image.png [logo];[in][logo]overlay=0:0:1:format=rgb [out]",imageWidth, imageHeight);
            filter.start();`

On every frame:

  ((ByteBuffer)yuvImage.image[0].position(0)).put(data);
               
try{
                    filter.push(yuvImage);
                }catch (FrameFilter.Exception ex){
                    ex.printStackTrace();
                    Log.e(CLASS_LABEL,"Error while pushing filter: "+ex.getMessage());
                }

I have the code from: https://github.com/bytedeco/javacv/issues/232

I don't get any error, but the image doesn't show up.

In the Issue 232, the author is also talking about following "I think I can convert Frame to IplImage or Mat by import OpenCV to add watermark.". As an alternative could someone provide some example code how i can achieve this with the Android Record Activity?

You can see me full code at https://github.com/y4nnick/android_streaming/blob/master/app/src/main/java/com/example/yannick/olay1/RecordActivity.java

Thanks for you help and your great work on this. Sorry for bad code formatting, i just can't get it right.

**Comment by aresa7796** [comment]
`filter = new MyFFmpegFilter("movie="+logoPath+" [logo];[in][logo]overlay=0:0:1:format=rgb [out]",getHeight(),getWidth());`
`        try {
            filter.setPixelFormat(AV_PIX_FMT_NV12);
            filter.start();
        } catch (FrameFilter.Exception e) {
            e.printStackTrace();
        }
`

but,long time recording can cause OutOfMemory, because there is an asBuffer () in Filter

**Comment by MhtSuthar** [comment]
@y4nnick @aresa7796 I am also not getting any errors, but image not displaying. Anything to make it work please let me know.

**Comment by y4nnick** [comment]
@MhtSuthar  You have to make sure that you use the right pixel format on all components (camera output, frameFilter and frameRecorder).
In my stackoverflow question you can find the steps which you should make:
 http://stackoverflow.com/questions/39479205/javacv-android-strange-colors-on-overlay-while-streaming-to-rtmp-server

Let my know if you have any questions.

I will add my application to the example repo when i am finished with it. You can have a look at it here: https://github.com/y4nnick/android_streaming/blob/master/app/src/main/java/com/example/yannick/olay1/RecordActivity.java

**Comment by saudet** [comment]
@y4nnick So, were you able to resolve your original issue?

**Comment by MhtSuthar** [comment]
I am using wowza stream engine and i found that it also supports watermark itself using transcoder. So, i am now using this as a solution. Thanks @y4nnick for support.

**Comment by y4nnick** [comment]
@MhtSuthar can you stream to Facebook with the wowza stream engine or only to wowza servers? In case of facebook live streaming i would be very happy if you could share your code with me :). 

@saudet : Yes the orginal issue is resolved. The answer and howto is in the SO question linked above.

**Comment by saudet** [comment]
FYI, this has actually been fixed with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a so if anyone is still have problems with this, please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/
