### ISSUE TITLE
Purple and green shade on frames after using FFmpegFrameFilter to rotate them

### ISSUE THREAD

**Issue by YinaZ** [bytedeco/javacv#509]
Hello, 
I'm trying to add some code to RecordActivity.java so that it can do simple face detection. Thanks to Samuel in issue #468 I can convert Mat from YUV NV21 format to BGR format successfully and I can do face detection in landscape mode now. 
Now I want to rotate the image when under portrait mode so that I can also detect faces in portrait mode. I added code about FFmpegFrameFilter and there appears a green & purple blur on every frame of the video. It would be nice if someone can help me find out what is wrong here...
Below is the code for the FaceDetector and the screenshot of the video. Thank you very much.
<img width="356" alt="screenshot" src="https://cloud.githubusercontent.com/assets/20526571/18692963/e01654f0-7f52-11e6-876f-70d4b8b380f0.png">

I actually want it to rotate clockwise instead of cclock_flip, but if I use "clock" in the code instead of "cclock_flip", the video is distorted like this:
<img width="372" alt="screenshot2" src="https://cloud.githubusercontent.com/assets/20526571/18693221/ed4e0666-7f54-11e6-9e7c-9af006c2be4e.png">

```java
private int imageWidth = 320;
private int imageHeight = 240;
private OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();
private CascadeClassifier faceDetector;
yuvImage = new Frame(imageWidth, imageHeight * 3/2, Frame.DEPTH_UBYTE, 1);
private FFmpegFrameFilter filter = new FFmpegFrameFilter("transpose=cclock_flip", imageWidth, imageHeight);



// ...
filter.setPixelFormat(avutil.AV_PIX_FMT_NV21);
try{
  filter.start();
} catch (FFmpegFrameFilter.Exception e) {
  e.printStackTrace();
}
FaceDetector(yuvImage);
// ...

public Mat FaceDetector (Frame frame) throws Exception {
  // rotate YUV image
  try {
    filter.push(frame);
    Frame newframe;
    while ((newframe = filter.pull()) != null) {
      frame =  newframe;
    }
  } catch (FFmpegFrameFilter.Exception e) {
    e.printStackTrace();
  }
  Mat image = converterToMat.convert(frame);
  // convert YUV image to BGR
  cvtColor(image, image, COLOR_YUV2BGR_NV21);
  cvtColor(image, image, COLOR_YUV2GRAY_NV21);
  equalizeHist(image, image);
  RectVector faces = new RectVector();
  faceDetector.detectMultiScale(image, faces);
  for (int i = 0; i < faces.size(); i++) {
    Rect face_i = faces.get(i);
    rectangle(image, face_i, new Scalar(0, 255, 0, 255));
  }
  return image;
}
```

**Comment by saudet** [comment]
Some FFmpeg filters don't work well with some image formats, so try to use the convert filter to change them to rgb or something before using those filters.

**Comment by saudet** [comment]
So, for example, if your frames format is `AV_PIX_FMT_NV21`, you probably want to call `push(frame, AV_PIX_FMT_NV21)`, **without** calling `setPixelFormat(AV_PIX_FMT_NV21)`

**Comment by YinaZ** [comment]
I tried calling `push(frame, AV_PIX_FMT_NV21)`, which resulted in a blank video with only black frames. Did you mean that I can try converting YUV image to RGB image first and use FFmpegFrameFilter to rotate it?

**Comment by saudet** [comment]
I said **without** calling `setPixelFormat(AV_PIX_FMT_NV21)`...

**Comment by saudet** [comment]
This is probably a duplicate of #887. Make sure to call `record(filteredFrame, frameFilter.getPixelFormat())`.

**Comment by ritesh94** [comment]
@saudet 
None of the below is working:
record(filteredFrame,avutil.AV_PIX_FMT_YUV420P);
record(filteredFrame,avutil.AV_PIX_FMT_NV21);
record(filteredFrame,frameFilter.getPixelFormat());

**Comment by saudet** [comment]
Something like this: https://github.com/bytedeco/javacv/issues/945#issuecomment-376142199
