### ISSUE TITLE
cvtColor destination Mat has null data (source is grabbed from a recorded video by FFmpegFrameGrabber)

### ISSUE THREAD

**Issue by YinaZ** [bytedeco/javacv#512]
Hi Samuel, I have a question about videoGrabber and cvtColor. I want to load recorded video and use FFmpegFrameGrabber to grab the frames out of the video to use again. I'm pretty sure the color format for each Mat (converted from each Frame) is BGR mode since I specifically used cvtColor to transfer every Frame to BGR mode when I recorded the video in the first place. But when I tried to grab frames from the video again and use cvtColor with code BGR2GRAY to convert each Mat I get into GRAY mode, the data of the destination Mat is just null. And if I convert it back to Frame, the frame ended up being null. Am I not suppose to assume that each Frame would turn into BGR Mat even if I knew they were BGR mode when I record them? Thank you very much! 
Below is code I'm using.
```java
public void readVideo() {
        FrameGrabber videoGrabber = new FFmpegFrameGrabber(input_link);
        recorder = new FFmpegFrameRecorder(output_link, imageHeight, imageWidth, 1);
        recorder.setFormat("mp4");
        recorder.setSampleRate(sampleAudioRateInHz);
        recorder.setFrameRate(frameRate);
        try {
            videoGrabber.setFormat("mp4");
            videoGrabber.start();
        } catch (org.bytedeco.javacv.FrameGrabber.Exception e){
            Log.e("javacv", "Failed to start grabber" + e);
        }
        try
        {
            recorder.start();
        } catch (org.bytedeco.javacv.FFmpegFrameRecorder.Exception e){
            Log.e("javacv", "Failed to start recorder" + e);
        }
        Frame vFrame = null;
        do{
            try{
                vFrame = videoGrabber.grabFrame();
                if(vFrame != null){
                    try{
                        Frame newFrame = null;
                        if (vFrame.image != null) {
                            newFrame = ProcessVideo(vFrame);
                        }
                        recorder.setTimestamp(videoGrabber.getTimestamp());
                        recorder.record(newFrame);
                    } catch (Exception e) {
                        Log.e("javacv", "video record frame failed: "+ e);
                    }
                }
            } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
                Log.e("javacv", "video grabFrame failed: "+ e);
            }
        } while(vFrame != null);

        try {
            videoGrabber.stop();
        } catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
            Log.e("javacv", "failed to stop video grabber", e);
        }
        try {
            recorder.stop();
            recorder.release();
        } catch (org.bytedeco.javacv.FrameRecorder.Exception e) {

            Log.e("javacv", "failed to stop video recorder", e);
        }
    } 

public Frame ProcessVideo (Frame frame) throws Exception {
        Mat videoMatGray = new Mat();
        Mat image = converterToMat.convert(frame);
        cvtColor(image, videoMatGray, COLOR_BGR2GRAY);
        equalizeHist(videoMatGray, videoMatGray);
        // ……
}

**Comment by saudet** [comment]
If your data is BGR, why are you using `COLOR_BGRA2GRAY`?

**Comment by YinaZ** [comment]
I was using BGR2GRAY originally and found that the Mat data is null so I tried other codes as well. I didn't noticed that I put the wrong version of code here... Sorry for the inconvenience, I meant BGR2GRAY. Thanks

**Comment by saudet** [comment]
Ok, could you print out what `image.toString()` returns?

**Comment by YinaZ** [comment]
`image.toString():
org.bytedeco.javacpp.opencv_core$Mat[width=288,height=352,depth=8,channels=3]
videoMatGray.toString():
org.bytedeco.javacpp.opencv_core$Mat[width=288,height=352,depth=8,channels=1]`

**Comment by saudet** [comment]
So that looks fine. Your issue lies in the "// ..." code, so if you cannot post that part, I'm afraid I won't be able to help you.

**Comment by YinaZ** [comment]
But when I print `videoMatGray.toString()`, `videoMatGray.data` is already null, which is right after the cvtColor line. I don't see why the issue lies in the "// ..." code.

**Comment by YinaZ** [comment]
I just updated the "//..." part in case you need it. Thanks

**Comment by saudet** [comment]
If the `rows`, `cols`, `channels` fields are not 0, but `data` is null, it's probably a bug in OpenCV. You could try to work around that by preallocating `videoMatGray` with the right size and data type.

**Comment by rezangit** [comment]
I have the same problem, did you find any workaround?

**Comment by saudet** [comment]
BTW, the `Mat.data` field is private and is usually null, regardless of the content of the object. What you want is probably the `Mat.data()` method, which is public.
