### ISSUE TITLE
Can't read VideoCapture

### ISSUE THREAD

**Issue by LuxLang** [bytedeco/javacv#515]
Hi.

I'm trying to read a video frame-by-frame to process it with OpenCV, but when using VideoCapture, both "isOpened" and "read" return false, even though the path to the video file is correct.

I'm trying with a .mp4 video, but I also tried with a .avi video and got the same result.

Also, I'm using version javacv 1.2

**Comment by saudet** [comment]
Please use FFmpegFrameGrabber.

**Comment by LuxLang** [comment]
I want to use the frames with HOGDescriptor to do pedestrian detection, but detectMultiScale requires Mat and a few other low-level OpenCV objects, whereas FFmpegFrameGrabber just returns a Frame.

Is there a way to convert a Frame into a Mat?

**Comment by LuxLang** [comment]
I found the OpenCVFrameConverter class.
I'll try with that.

**Comment by saudet** [comment]
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
