### ISSUE TITLE
Image color problem with x86

### ISSUE THREAD

**Issue by pedroSG94** [bytedeco/javacv#523]
Hi,
I'm doing streaming with a device x86 but the image look like this:

![captura de pantalla de 2016-10-03 12 12 32](https://cloud.githubusercontent.com/assets/17556876/19034282/f2f51a60-8962-11e6-9f4a-8391ecebb044.png)

The code work fine in arm with API 19 and API 23 tested with ffmpeg 3.0.2 and ffmpeg 3.1.2, javacpp 1.2.4 and javacv 1.2.
Device x86: Google glass 2 (API 19)

**Comment by saudet** [comment]
Looks like you're using FFmpegFrameFilter?

**Comment by pedroSG94** [comment]
No, only FFmpegFrameRecorder:

`recorder = new FFmpegFrameRecorder(rtmpUrl, dataConfig.getResolutionWidth(), dataConfig.getResolutionHeight(), 1);
    recorder.setTimestamp(4);
    recorder.setGopSize(48);
    recorder.setVideoBitrate(1500000);
    recorder.setVideoOption("preset", "ultrafast"); // or ultrafast or fast, etc.
    recorder.setFormat("flv");
    recorder.setSampleRate(dataConfig.getAudioRateInHz());
    recorder.setFrameRate(24);`

**Comment by saudet** [comment]
Ok, you're probably not providing the correct pixel format to the record() call then.

**Comment by pedroSG94** [comment]
I have solved my problem!
The problem was a glass bug and bad resolution in Frame class:
http://stackoverflow.com/questions/25933409/strange-camera-bug-with-google-glass-and-zxing
i set FpsRange to 5000 - 30000 (glass 2 only support it)

**Comment by saudet** [comment]
Great! Thanks for the feedback
