### ISSUE TITLE
How to get the rho and alpha vector from CvSVM use javacv

### ISSUE THREAD

**Issue by MUYOUHUIYAO** [bytedeco/javacv#528]
I was training an Hog detector use the CvSVM class follow an C++ example. In the example, he inherit the CvSVM class to get the protected attribute "decision_func" to get rho and alpha vector, but in JavaCv, I cannot get the protected attribute, and I didn't find a function to get the attribute. So how can I get the attribute to make the detector for HogDescriptor?

**Comment by saudet** [comment]
I don't think CvSVM exists with OpenCV 3.x anymore. You'll need to find an updated example and use the API of OpenCV 3.x.

**Comment by MUYOUHUIYAO** [comment]
But I was using opencv 2.x, it may be uneasy to convert to OpenCv 3.x

**Comment by saudet** [comment]
It's always possible to modify old versions of the JavaCPP Presets, but it's not something I will do personally.

**Comment by MUYOUHUIYAO** [comment]
I was thinking there is some method to get the attribute with some javacpp api, I solved the problem with reading them from the xml file. But I cannot get any detected rect when I use the HogDescriptor to dectect the sample image.
