### ISSUE TITLE
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by huang7855196** [bytedeco/javacv#529]
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
what should i do?

**Comment by rebaomi** [comment]
you can read this reference:https://github.com/bytedeco/javacv/issues/133

**Comment by saudet** [comment]
Please read the README.md file and try to follow the instructions:
https://github.com/bytedeco/javacv
