### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/lib/x86_64/libavutil.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by coralinejones1985** [bytedeco/javacv#530]
Hi, I've already asked a question about using 32-bit libs for 64-bit devices. I was told that 32-bit libs can work on 64-bit devices, but it appeared to fail :( I wonder, if there are some binaries for 64-bit system?

**Comment by saudet** [comment]
No, there aren't. Marking as duplicate of https://github.com/bytedeco/javacpp-presets/issues/52

**Comment by saudet** [comment]
64-bit builds for Android (as the "android-arm64" and "android-x86_64" platforms) are now available, so please give it a try! Binaries for 1.4.1-SNAPSHOT can be downloaded from the snapshot repository: http://bytedeco.org/builds/
