### ISSUE TITLE
Detect face and Record video at same time

### ISSUE THREAD

**Issue by AwesomePeople** [bytedeco/javacv#531]
Hi.
Is it possible to process both detect face and record video at the same time with RecordActivity?

**Comment by saudet** [comment]
Yes, why not? What issue are you having?

**Comment by AwesomePeople** [comment]
Oh, thank for your quickly reply. 
Can you show me how to do that, i don't know that. THank you!

**Comment by saudet** [comment]
Just do like shown in the Demo class in the README.md file:
https://github.com/bytedeco/javacv#sample-usage
