### ISSUE TITLE
Zero framerate

### ISSUE THREAD

**Issue by Maleandr** [bytedeco/javacv#532]
Hi,

We are using FFmpegFrameGrabber to process some video streams from youtube,twitch,rtmp,etc..

Sometimes we are getting zero framerate and frame grabber doesn't grab anything. When we restart it, it helps but again only sometimes.

We use this function:
`grabber.getFrameRate();`

**Comment by saudet** [comment]
Sounds like a problem with the server. Anyway, could you provide a way to reproduce this? Thank you.

**Comment by Maleandr** [comment]
It doesn't happen every time, that's the problem. We observed that it happens more often, when we stream screen via obs (https://obsproject.com/) in full hd. We use this nginx module to as relay (https://github.com/arut/nginx-rtmp-module).

**Comment by saudet** [comment]
Does it happen with other clients, such as VLC? If it does, then it's a problem with the servers.

**Comment by Maleandr** [comment]
Nope it doesn't. VLC isn't playing stream smoothly, but it can open it.

**Comment by saudet** [comment]
What about `ffplay`? Have you tried version 3.1.2 or some other version?

**Comment by Maleandr** [comment]
Hmm nope i haven't tried it. I will. Generally do you have any idea why this is happening?

**Comment by saudet** [comment]
Well, it the same thing happens with `ffplay`, then please file a ticket upstream. If it happens with an old version of `ffplay`, but not with a newer version of `ffplay`, then using that same version with JavaCV will also fix the issue. So, please an old version of `ffplay` and a recent version of `ffplay`, and report bugs accordingly.

**Comment by Maleandr** [comment]
Oki i will.

**Comment by Maleandr** [comment]
I tested it with actual version of ffplay and it opened stream without any issues. I will test old one.

**Comment by saudet** [comment]
So, does an old version of ffplay works or not?

**Comment by Maleandr** [comment]
It doesn't work for us. We stayed with newer version, but still has sometimes issues with grabbing frame rate. Not sure if it is the problem, but we noticed in log, that it first grab audio stream and then video stream after few seconds. Maybe getFrameRate() is called only on audio stream and thus it is returning 0 frame rate.

**Comment by saudet** [comment]
Ah, I see, yes if we only have audio data it might return 0, so keep calling it until doesn't return 0, then use that value.
