### ISSUE TITLE
FFmpegFrameRecorder doesn't allow videos with even widths that aren't multiples of 16

### ISSUE THREAD

**Issue by amosyuen** [bytedeco/javacv#535]
FFmpegFrameRecorder  automatically rounds the video width to the nearest multiple of 16. A comment specifies that even width is required, and 16 is sometimes required.

I created a copy of FFmpegFrameRecorder and tested it with even, non 16 multiples, and it worked fine with the H264 codec as well as Mpeg 4.

I think the FFmpegFrameRecorder should allow non multiple of 16 widths. And when rounding the width, probably should also change the height to maintain the aspect ratio.

**Comment by saudet** [comment]
Sure, if it works fine with recent codecs, we can just remove that bit. Could you send a pull request? Thanks!

**Comment by amosyuen** [comment]
https://github.com/bytedeco/javacv/pull/536

**Comment by saudet** [comment]
Changes included in JavaCV 1.3. Thanks for the contribution!
