### ISSUE TITLE
How to use Mat add overlay on roi?

### ISSUE THREAD

**Issue by aresa7796** [bytedeco/javacv#539]
```
@Override
    public void writeVideoFrame(SavedFrames frame) throws Exception{
        long start = System.currentTimeMillis();
        getRecorder().setTimestamp(frame.getTimeStamp());
        ((ByteBuffer)videoFrame.image[0].position(0)).put(frame.getFrameBytesData());

        Mat image = matConverter.convert(videoFrame);
        Mat logoMat = cvarrToMat(logo2);
        Mat logoMask = cvarrToMat(mask2);
        Mat roi = image.apply(new Rect(0,0,100,100));
        logoMat.copyTo(roi,logoMask);
        
        getRecorder().record(matConverter.convert(image));
        ((ByteBuffer)videoFrame.image[0].position(0)).clear();
        Log.d(TAG,"writeVideoFrame time = " + (System.currentTimeMillis() - start));
    }
```

finaly,no watermark on the image.

@saudet help me,please.

**Comment by saudet** [comment]
Do you need alpha blending, yes or no? If you need alpha blending, OpenCV is the wrong tool for this.

**Comment by aresa7796** [comment]
I dont't need alpha blending

**Comment by saudet** [comment]
So get rid of `logoMask` and it should work just fine.

**Comment by aresa7796** [comment]
Still no watermark on the image

**Comment by aresa7796** [comment]
@saudet

**Comment by saudet** [comment]
What happens if you try `imwrite(image, "temp.png")`? Does "temp.png" look alright?

**Comment by aresa7796** [comment]
` OpenCV Error: Assertion failed (image.channels() == 1 || image.channels() == 3 || image.channels() == 4) in bool cv::imwrite_(const cv::String&, const cv::Mat&, const std::vector<int>&, bool), file /home/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/android-arm/opencv-3.0.0/modules/imgcodecs/src/loadsave.cpp, line 435`


it throws Exception.
@saudet

**Comment by saudet** [comment]
So you don't have images.
