### ISSUE TITLE
h264 is too slow

### ISSUE THREAD

**Issue by IgeNiaI** [bytedeco/javacv#54]
I am streaming video from camera to RTMP server, encoding with h264, but it is too slow. On my galaxy S2 there are only 10 frames per second with resolution 640x480.
I discovered that the slowest method is avcodec_encode_video2().
Also, I tryied to encode with FLV1. It is a lot faster, but quality is too bad.
I know that this is ffmpeg issue, but is there a way to make it faster or another encoding with proper quality?

**Comment by dpyinjie** [comment]
thanks，It also works to me !!
