### ISSUE TITLE
Archive ffmpeg-3.0.2-1.2.jar does not exist.

### ISSUE THREAD

**Issue by niclasschult** [bytedeco/javacv#540]
Hi everyone,
I am trying to use JavaCV 1.2 (in order to use the FFMpegFrameRecorder) and for this I downlaoded the JavaCV binaries and added all included jars to my Eclipse project. When I now try to start the example "PacketRecorderTest.java" the application won't start and I get the error message "Archive ffmpeg-3.0.2-1.2.jar which is referenced by the classpath, does not exist." (A jar named ffmpeg.jar is included in the zip; the classpath defined in the manifest file of the javaCV jar seems to use both, ffmpeg-3.0.2-1.2.jar and ffmpeg.jar) Do I need to download any other dependencies? I could not find any information in the "required software" section from https://github.com/bytedeco/javacv 

Thanks very much in advance!

**Comment by niclasschult** [comment]
Never mind, I found the jar somewhere in the forum. I'm still confused, though, why it isnt part of the official javaCv archive.

**Comment by saudet** [comment]
It is, but you should be using ffmpeg-3.1.2-1.2.jar anyway.
