### ISSUE TITLE
H264 Codec Support for VideoCapture does not apply

### ISSUE THREAD

**Issue by AlexanderWolz** [bytedeco/javacv#541]
I am currently evaluating the video grab times of the Java wrappers by OpenCV compared to JavaCV.
As I have a Logitech c920 that supports pre-encoded H264, I want to save CPU usage using it.
(My target device is a Raspberry Pi 3+)

in fact, if I set the FOURCC to H264 in the OpenCV Java wrapper VideoCapture, my grab times decrease enormously compared to the VideoCapture without setting that mode.

Unfortunately, if I set the FOURCC to the JavaCV VideoCapture, the grab times are pretty equal to those of the JavaCV Videocapture without the H264 mode. 

Is there a bug in the framework or what am I missing to get H264 running with JavaCV?

Here the results of my performance test:

```
 JavaCV vs OpenCV Java - Performance Test -> LINUX [ARM]
 -----------------------
 OpenCv
   -> Total Grabs:   599
   -> Grab Mean:     165ms
   -> Grab Median:   165ms
   -> Grab Lowest:   139ms
   -> Grab Max:      326ms
   -> Grab Variance: 198ms
   -> Grab StdDev:   14ms
   -> CPU Mean:      200%
   -> CPU Median:    200%
   -> CPU Lowest:    104%
   -> CPU Max:       243%
   -> CPU Variance:  142
   -> CPU StdDev:    11
 -----------------------
 OpenCv + H264
   -> Total Grabs:   599
   -> Grab Mean:     40ms
   -> Grab Median:   36ms
   -> Grab Lowest:   32ms
   -> Grab Max:      79ms
   -> Grab Variance: 105ms
   -> Grab StdDev:   10ms
   -> CPU Mean:      112%
   -> CPU Median:    111%
   -> CPU Lowest:    62%
   -> CPU Max:       151%
   -> CPU Variance:  196
   -> CPU StdDev:    14
 -----------------------
 JavaCV
   -> Total Grabs:   599
   -> Grab Mean:     234ms
   -> Grab Median:   232ms
   -> Grab Lowest:   210ms
   -> Grab Max:      318ms
   -> Grab Variance: 225ms
   -> Grab StdDev:   15ms
   -> CPU Mean:      176%
   -> CPU Median:    177%
   -> CPU Lowest:    150%
   -> CPU Max:       220%
   -> CPU Variance:  62
   -> CPU StdDev:    7
 -----------------------
 JavaCV + H264
   -> Total Grabs:   599
   -> Grab Mean:     231ms
   -> Grab Median:   231ms
   -> Grab Lowest:   210ms
   -> Grab Max:      289ms
   -> Grab Variance: 153ms
   -> Grab StdDev:   12ms
   -> CPU Mean:      176%
   -> CPU Median:    176%
   -> CPU Lowest:    154%
   -> CPU Max:       198%
   -> CPU Variance:  52
   -> CPU StdDev:    7
```

**Comment by saudet** [comment]
OpenCV probably needs to be built with FFmpeg to support that.
FFmpegFrameGrabber usually works better than OpenCV's VideoCapture anyway,
so try to use that.

**Comment by AlexanderWolz** [comment]
Actually I have compiled OpenCV with FFmpeg.
Can you give me a hint how to capture my webcam using the FFmpegFrameGrabber?
According to the API it wants a Filename string and not a device path.

**Comment by saudet** [comment]
https://trac.ffmpeg.org/wiki/Capture/Webcam

**Comment by saudet** [comment]
I'm guessing using FFmpegFrameGrabber solved your issue. For reference, some code sample here:
https://github.com/bytedeco/javacv/issues/154#issuecomment-104954981
