### ISSUE TITLE
flandmark.jar and opencv.jar, android 6.0.1, LG v10: Fatal signal 11 (SIGSEGV), code 1

### ISSUE THREAD

**Issue by astroluj** [bytedeco/javacv#542]
flandmark.jar and opencv.jar, android 6.0.1, LG v10: Fatal signal 11 (SIGSEGV), code 1
 Please, I need help.
I used java-presets-1.2 version

how get 1.2.x version?
 Does flandmark work fine on 6.0 as ffmpeg does?

**Comment by saudet** [comment]
Could you provide a bit more details?

**Comment by astroluj** [comment]
I use flandmark, javacpp and opencv(armeabi or armeabi-v71) which is included in java-presets-1.2. and all tests are fine on android version 4.0 to 5.1.x but 6.0. It shows above fatal error. [https://github.com/bytedeco/javacv/issues/412](#412)This error happens when 'ffmpeg' is used and it's resolved from changing java-presets version to 1.2.1. However I don't use ffmpeg so, I'm not sure if this problem will be solved with the same solution. and I don't know if it will then where can I download 1.2.x version of flandmark and opencv. If you have any idea, lead me to right way please. 
The error occurred on LG V10(F600) API23 and android v.6.

**Comment by saudet** [comment]
Yes, it's the same issue as https://github.com/bytedeco/javacv/issues/412. Just use JavaCPP 1.2.x.

**Comment by saudet** [comment]
Download from here: https://github.com/bytedeco/javacpp#downloads

**Comment by astroluj** [comment]
thanks X 100
Problem clear
