### ISSUE TITLE
ffmpeg SIGSEGV on Asynktask Android Studio

### ISSUE THREAD

**Issue by sasanian** [bytedeco/javacv#545]
Devices Samsung galaxy tab A 6.0.1, Motorolla G3 5.1.1.
Android studio 2.2, WIN 10 64 bit.
JavaCPP 1.2.4
JavaCV, ffpmpeg-arm, ffmpeg, openCV-arm, openCV 1.2

What happens is I load the Fragment containing the camera and everything loads up fine (FFmpegFrameRecorder, OpenCVFramerConverter, etc.). As soon as I hit the record button the app crashes. I have an asynctask which records the frame in the doInBackground method. I suspect that's where the crash occurs.

```
10-24 13:36:11.293 30365-30365/com.sasanian.shiftobd2 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
10-24 13:36:11.403 30365-30365/com.sasanian.shiftobd2 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
10-24 13:36:11.813 30365-30365/com.sasanian.shiftobd2 D/SensorManager: unregisterListener ::   
10-24 13:36:12.213 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:12.223 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:12.223 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:12.223 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:12.223 30365-30365/com.sasanian.shiftobd2 D/SensorManager: registerListener :: 0, K2HH Acceleration , 20000, 0,  
10-24 13:36:16.833 30365-30365/com.sasanian.shiftobd2 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
10-24 13:36:16.993 30365-30365/com.sasanian.shiftobd2 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
10-24 13:36:18.093 30365-30365/com.sasanian.shiftobd2 D/ViewRootImpl: ViewPostImeInputStage processPointer 0
10-24 13:36:18.173 30365-30365/com.sasanian.shiftobd2 D/ViewRootImpl: ViewPostImeInputStage processPointer 1
10-24 13:36:18.303 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:18.333 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:18.333 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:18.413 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:18.413 30365-30365/com.sasanian.shiftobd2 E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)
10-24 13:36:18.543 30365-32750/com.sasanian.shiftobd2 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x428c0000 in tid 32750 (Thread-23132)
```

```
dependencies {
   compile files('libs/ffmpeg-android-arm.jar')
   compile files('libs/ffmpeg.jar')
   compile files('libs/javacpp.jar')
   compile files('libs/javacv.jar')
   compile files('libs/opencv-android-arm.jar')
   compile files('libs/opencv.jar')
}
```
I have tried previous Javacpp files 1.2, 1.2.1, 1.2.2 to no avail. I'm only experiencing this issue with 1.2 library. I' ve also noticed the error `No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() ` after updating to javacpp 1.2.4

**Comment by saudet** [comment]
Please try again with `ffmpeg-3.1.2-1.2-android-arm`.

**Comment by sasanian** [comment]
Thanks for the quick response but unfortunately it didn't work.
`10-25 00:01:11.615 1741-3871/com.sasanian.shiftobd2 A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3871 (Thread-28182)`

**Comment by saudet** [comment]
Does the same thing happen with RecordActivity? If RecordActivity works fine, then it's probably a bug in your application.

**Comment by sasanian** [comment]
Thanks Sam. The error was on my end. I was running a thread and an asynctask at the same time to record frames. Quick question: I'm trying to capture bitmaps generated from from onSurfaceTextureUpdated method. I use 
```
bmp.copyPixelsToBuffer(yuvIplImage.getByteBuffer());
frame = converterToIplImage.convert(yuvIplImage);
```
which uses `OpenCVFrameConverter.ToIplImage();`
I've also noticed there the option of using  `OpenCVFrameConverter.ToMat();`
Which one should I be using to create the frame for `recorder.record(frame)`?
thanks

**Comment by saudet** [comment]
Good!

You can use either one, but it's also possible to copy the same directly to a `Frame` object.

**Comment by sasanian** [comment]
I take it you mean this method? `((ByteBuffer)frame.image[0].position(0)).put(yuvIplImage.getByteBuffer());`
Is there any advantage of doing it this way?

**Comment by saudet** [comment]
Something like that, yes, but without yuvIplImage.

**Comment by sasanian** [comment]
Can you please provide an example? I've tried the following but there is no video, only a black screen.
```
int size = bitmap.getRowBytes() * bitmap.getHeight();
ByteBuffer buffer = ByteBuffer.allocate(size); //Create a new buffer
bmp.copyPixelsToBuffer(buffer);
((ByteBuffer)frame.image[0].position(0)).put(buffer);
```

**Comment by saudet** [comment]
What is `bitmap`?

**Comment by sasanian** [comment]
oops. That's supposed to be `bmp`  obtained from `mTextureView.getBitmap(bmp);`
I then create a canvas `Canvas c = new Canvas(bmp);` and draw some things onto the `bmp` and finally want to send it to `FFmpegFrameRecorder`
I hope that helps,
thanks

**Comment by saudet** [comment]
Right ok, so have you tried to use `AndroidFrameConverter` instead?
http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/AndroidFrameConverter.html

**Comment by sasanian** [comment]
That works! 
It also got rid of screen tearing that was occurring when using `IPLImage` and also reduced the APK size since I won't be needing openCV library anymore.
Thanks.
