### ISSUE TITLE
FaceRecognizer.train not using labels

### ISSUE THREAD

**Issue by marcosbontempo** [bytedeco/javacv#546]
Hello, 

I'm having some doubts about the use of the "labels" variable in the FaceRecognizer.java class (https://github.com/bytedeco/javacv/blob/master/samples/OpenCVFaceRecognizer.java). This object is only created as a Mat and then it isn't referenced anymore. Is that right? I checked similar implementations in Python and C++ and they insert the name of the image in it.

```
        Mat labels = new Mat(imageFiles.length, 1, CV_32SC1);
        IntBuffer labelsBuf = labels.createBuffer();
        int counter = 0;
        for (File image : imageFiles) {
            Mat img = imread(image.getAbsolutePath(), CV_LOAD_IMAGE_GRAYSCALE);
            int label = Integer.parseInt(image.getName().split("\\-")[0]);
            images.put(counter, img);
            labelsBuf.put(counter, label);
            counter++;
       }
        FaceRecognizer faceRecognizer = createFisherFaceRecognizer();
        // FaceRecognizer faceRecognizer = createEigenFaceRecognizer();
        // FaceRecognizer faceRecognizer = createLBPHFaceRecognizer()
        faceRecognizer.train(images, labels);
```
Any tip will be very helpful,

Thanks

**Comment by saudet** [comment]
This is a question about the `opencv_facerec` module. The answer is probably somewhere in this tutorial: http://docs.opencv.org/2.4/modules/contrib/doc/facerec/facerec_tutorial.html
