### ISSUE TITLE
No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes()

### ISSUE THREAD

**Issue by lfdversluis** [bytedeco/javacv#548]
Hi, I sometimes get `E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)`

And my app crashes with `Framerecorder exception org.bytedeco.a.c$a: av_interleaved_write_frame() error -22 while writing interleaved video packet.` on `recorder.record(yuvImage);` (not sure if it's related).

I am using the following versions in my gradle:

```
compile group: 'org.bytedeco', name: 'javacpp', version: '1.2.4'
    compile 'org.bytedeco:javacv:1.2'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-x86'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.1.2-1.2', classifier: 'android-x86'
```

What could be going wrong?

**Comment by saudet** [comment]
That's alright, you can ignore that.

**Comment by FanSerg2** [comment]
Hello, I try to overlay the image on the video and getting the same error:
`E/art: No implementation found for long org.bytedeco.javacpp.Pointer.physicalBytes() (tried Java_org_bytedeco_javacpp_Pointer_physicalBytes and Java_org_bytedeco_javacpp_Pointer_physicalBytes__)`

It worked fine on ffmpeg version 2.8.1-1.1. But now I have updated library to version 3.1.2-1.2 and after executed filter i get video without image.

This is first parameter of my FFmpegFrameFilter:
`“movie=/storage/emulated/0/image.png [effect];[in][effect]overlay=x=(main_w-overlay_w)/2:y=(main_h-overlay_h)/2:format=rgb [out]”`

**Comment by FanSerg2** [comment]
Today I have updated library version to 3.2.1-1.3 and error has disappeared. But filter "overlay" still doesn't work. In result I have a video without overlay image.
Filters "transpose" and "rotate" work perfect.
Why does filter "overlay" not work?

**Comment by saudet** [comment]
Yes, the new set of binaries built with JavaCPP 1.3 solve these warning messages.

@FanSerg2 It probably has nothing to do with JavaCPP or FFmpeg. Did you make sure that your application has permission to read the "/storage/emulated/0/image.png" file?

**Comment by FanSerg2** [comment]
Application has permission to read storage ("/storage/emulated/0/image.png").
If I only change from 

```
compile group: 'org.bytedeco', name: 'javacv', version: '1.3'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3', classifier: 'android-arm'
```

to

```
compile group: 'org.bytedeco', name: 'javacv', version: '1.1'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'
```

application is working correctly.
But I need to use latest version because version 2.8.1-1.1 has old version OpenSSL certificates and Google Play Store blocks these applications.

**Comment by saudet** [comment]
So it's a bug in FFmpeg? If so, please file a ticket over there: https://ffmpeg.org/bugreports.html
