### ISSUE TITLE
incorrect checksum when reading file as IplImage_or Mat

### ISSUE THREAD

**Issue by fagossa** [bytedeco/javacv#551]
Hi,

I'm using your sbt plugin in order to show a PNG image.
```
addSbtPlugin("org.bytedeco" % "sbt-javacv" % "1.11")
```

The actual images are not stored locally but streamed from a remove server. The binary images seem to be well formed as I am able to open them in several image editors. I share you a reproducer that shows a similar behavior.

Basically, what I'm doing is just :
* reading the bytes from disk
* create an empty image with the desired width, height, depth
* fill the image with the bytes
* uses a canvas to show the image

It is something like this:
```
// reads data
val bis = new BufferedInputStream(new FileInputStream("src/test/resources/content.png"))
val data: Array[Byte] = Stream.continually(bis.read).takeWhile(-1 !=).map(_.toByte).toArray

// creates image
val imageData: IplImage = opencv_core.cvCreateImage(new CvSize(512, 288),    opencv_core.CV_8UC3, 3)
imageData.put(new BytePointer(data: _*))
```

However, I get this error every time:

```
java(50842,0x700001a0d000) malloc: *** error for object 0x7fd2a4352688: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
/usr/local/Cellar/sbt/0.13.9/libexec/sbt-launch-lib.bash: line
```

I tried a similar approach with a _Mat_, but got basically the same thing.

This is my environnement:
* MACOS 10.11.5
* Java(TM) SE Runtime Environment (build 1.8.0_66-b17), 64-Bit Server VM (build 25.66-b17, mixed mode)
* Scala code runner version 2.11.4 -- Copyright 2002-2013, LAMP/EPFL
* SBT 0.13

Any ideas? Do you have an example of this kind of scenario?

best regards

**Comment by fagossa** [comment]
I've made some progress.

I removed _put_ and I'm using _imageData(byte[])_ instead:

```scala
val image = opencv_core.cvCreateImage(new CvSize(512, 288), opencv_core.CV_8UC3, 3)
image.imageData(new BytePointer(bytes: _*))
image
```
and .... i get no exception, nor jvm crash

however, now I only get noise :(

<img width="505" alt="noise" src="https://cloud.githubusercontent.com/assets/6917738/20040464/63c077d4-a458-11e6-94bc-571cc5720a00.png">

**Comment by saudet** [comment]
Could you explain what you are trying to do?

2016/11/07 3:40 "Fabian Gutierrez" <notifications@github.com>:

**Comment by saudet** [comment]
Looks like what you're looking for is imdecode().

**Comment by fagossa** [comment]
u r right!! u rocks :D
