### ISSUE TITLE
FFmpegFrameGrabber returns Frame with only one channel instead of three when grabbing from rawvideo

### ISSUE THREAD

**Issue by hawk23** [bytedeco/javacv#557]
I extracted a raw video file from an h264 stream using following ffmpeg CLI command:
````
ffmpeg -i video.mp4 -f rawvideo -pixel_format yuv420p -r 25 -vframes 400 video.yuv
````

In my Java application I use following code to extract a frame from the `video.yuv` file:
````
Java2DFrameConverter converter = new Java2DFrameConverter();
FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(video);

grabber.setImageWidth(1920);
grabber.setImageHeight(960);
grabber.setFormat("rawvideo");
grabber.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
grabber.start()

Frame frame = grabber.grab()
BufferedImage grabbedImage = converter.convert(frame);
````

The resulting `grabbedImage` only has one channel (grayscale image when saved to disk and opened in a picture viewer). `frame.imageChannels` also returns only `1` instead of `3`.

**Comment by saudet** [comment]
Try to set the pixel format to something supported by Java 2D, such as `AV_PIX_FMT_BGR24`.

**Comment by hawk23** [comment]
The `frame` object returned by the grabber only has one channel  (`frame.imageChannels` is `1`) even before passing it to the Java 2D frame converter. So I think the problem is somewhere else. 

I'm now packing the raw video  into an avi container, which works fine for now. The following ffmpeg CLI command was used to generate the content:
````
ffmpeg -i video.mp4 -c:v rawvideo -pixel_format yuv420p -r 25 -vframes 400 video.avi
````

**Comment by saudet** [comment]
Raw video, so maybe `setOption("pixel_format", "yuv420p")` or `setVideoOption("pixel_format", "yuv420p")` would work?

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming that setting the above options solved this issue.
