### ISSUE TITLE
MEIZU Fatal signal 11

### ISSUE THREAD

**Issue by omg-lol** [bytedeco/javacv#558]
I ran the recordActivity at Meizu with Mediatek 6753 and Android 5.1 
the error appears: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid xxxx

I ran the same on other devices (Xaomi, ASUS with Android 5.x, 6), there is no error (but these devices have Snapdragon xxx, I didn't find any differences).
I use javacv 1.2, javacpp 1.2.2, I tried to use javacpp 1.2.1, 1.2.4 and same error appears

compileSdkVersion 23
targetSdkVersion 22

`D/Camera-JNI: Allocating callback buffer`
`W/art: Suspending all threads took: 28.618ms`
`I/art: Background partial concurrent mark sweep GC freed 5791(478KB) AllocSpace objects, 27(2MB) LOS objects, 9% free, 38MB/42MB, paused 7.056ms total 167.187ms`
`W/linker: libjniswscale.so: unused DT entry: type 0x1d arg 0x3cb4`
`W/linker: libjniswscale.so: unused DT entry: type 0x6ffffffe arg 0x618c`
`W/linker: libjniswscale.so: unused DT entry: type 0x6fffffff arg 0x2`
`W/art: Suspending all threads took: 12.051ms`
`W/art: Suspending all threads took: 5.866ms`
`I/art: Background partial concurrent mark sweep GC freed 13871(1808KB) AllocSpace objects, 139(2MB) LOS objects, 9% free, 39MB/43MB, paused 8.064ms total 91.638ms`
`W/linker: libpostproc.so: unused DT entry: type 0x6ffffffe arg 0x7a0`
`W/linker: libpostproc.so: unused DT entry: type 0x6fffffff arg 0x1`
`W/linker: libjnipostproc.so: unused DT entry: type 0x1d arg 0x2732`
`W/linker: libjnipostproc.so: unused DT entry: type 0x6ffffffe arg 0x456c`
`W/linker: libjnipostproc.so: unused DT entry: type 0x6fffffff arg 0x2`
`W/linker: libavfilter.so: unused DT entry: type 0x6ffffffe arg 0x4080`
`W/linker: libavfilter.so: unused DT entry: type 0x6fffffff arg 0x6`
`W/linker: libjniavfilter.so: unused DT entry: type 0x1d arg 0x9529`
`W/linker: libjniavfilter.so: unused DT entry: type 0x6ffffffe arg 0xd3b0`
`W/linker: libjniavfilter.so: unused DT entry: type 0x6fffffff arg 0x2`
`I/MyStreamActivity: recorder initialize success`
`I/art: Background partial concurrent mark sweep GC freed 25048(2MB) AllocSpace objects, 151(3MB) LOS objects, 9% free, 39MB/43MB, paused 2.088ms total 102.261ms`
`D/libc-netbsd: [getaddrinfo]: hostname=barabas.tv; servname=(null); cache_mode=(null), netid=0; mark=0`
`D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0`
`D/libc-netbsd: [getaddrinfo]: hostname=barabas.tv; servname=1935; cache_mode=(null), netid=0; mark=0`
`D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=0; ai_family=0`
`D/libc-netbsd: getaddrinfo: barabas.tv get result from proxy >>`
`D/libc-netbsd: [getaddrinfo]: hostname=barabas.tv; servname=(null); cache_mode=(null), netid=0; mark=0`
`D/libc-netbsd: [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0`
`W/MyStreamActivity: Start Button Pushed`
`I/Choreographer: Skipped 89 frames!  The application may be doing too much work on its main thread.`
`I/CameraFramework: handleMessage: 16`
`D/Camera-JNI: setHasPreviewCallback: installed:1, manualBuffer:0`
`D/android.media.AudioRecord: AudioRecord>>>`
`D/android.media.AudioRecord: AudioRecord<<<: user granted permission sub-permission.RECORD_MIC for uid 10129`
`D/AudioRecord: openRecord_l`
`D/MyStreamActivity: audioRecord.startRecording()`
`D/Camera-JNI: Allocating callback buffer`
`I/CameraFramework: handleMessage: 16`
`D/Camera-JNI: setHasPreviewCallback: installed:1, manualBuffer:0`
`D/AudioRecord: return status 0`
`V/MyStreamActivity: Writing Frame`
`W/art: Suspending all threads took: 5.707ms`
`D/Camera-JNI: Allocating callback buffer`
`E/chromium: ### WebView Version 1.0 (code 400002)`
`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12424 (tcentre.barabas)`
`V/MyStreamActivity: bufferReadResult: 2048`
`Application terminated.`

Can anyone help me?

**Comment by saudet** [comment]
Could you copy/paste the information about that SIGSEGV from your log?

**Comment by saudet** [comment]
Also, could you try with the just released version 1.3?

**Comment by omg-lol** [comment]
OK, I'll try use this version.

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming things work with JavaCV 1.3, but let me know if this is not the case! Thanks
