### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by danvallejo** [bytedeco/javacv#559]
I need a completely self contained java implementation using Gradle. I don't want to install anything on the machine.

I'm running a java Amazon EMR application.

```
        Mat mat = new Mat();  <-- blows up here
        String filename = "~/1024-avatar.jpg";

        IplImage image = cvLoadImage(filename); <-- blows up here if I comment out the Mat line above
        if (image != null) {
            cvSmooth(image, image);
            cvSaveImage("smoothed-" + filename, image);
            cvReleaseImage(image);
        }
```

Here's my gradle.
```
dependencies {
   compile   'commons-io:commons-io:2.4',
              'ch.qos.logback:logback-classic:1.1.7',
              'org.apache.httpcomponents:httpclient:4.3.4',
              'org.apache.httpcomponents:httpcore:4.3.2',
              'org.apache.httpcomponents:httpmime:4.3.4',
              'org.apache.hadoop:hadoop-common:2.7.3',
              'org.apache.hadoop:hadoop-client:2.7.3'

    compile 'org.bytedeco:javacv:1.2'
    compile 'org.bytedeco.javacpp-presets:opencv:3.1.0-1.2:linux-x86_64'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:2.7.1-1.2:linux-x86_64'

    compile files('src/opencv-3.1.0/build/bin/opencv-310.jar')

    testCompile group: 'junit', name: 'junit', version: '4.11'
}

```

**Comment by saudet** [comment]
I'm not sure how that is even supposed to build: ffmpeg-2.7.1-1.2 doesn't even exist. You could try to remove that and see?

**Comment by danvallejo** [comment]
I removed ffmpeg. Same error.

I tried a newer version of ffmpeg. Same error.

Download https://mvnrepo.xxxxxxx.net/nexus/content/groups/public/org/bytedeco/javacpp-presets/ffmpeg/3.1.2-1.2/ffmpeg-3.1.2-1.2-linux-x86_64.jar

**Comment by saudet** [comment]
Ok, so then it's probably a problem with your device, try this:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by danvallejo** [comment]
FYI.. I'm a pure java application not Android.

I was able to make this work by:
   compile 'org.bytedeco:javacv:1.2'
    compile 'org.bytedeco.javacpp-presets:opencv:3.1.0-1.2:macosx-x86_64'

**Comment by saudet** [comment]
Oops, got confused with another issue. Sure, if you're on Mac, that's what you need to do, as written in the README.md file.
