### ISSUE TITLE
cvLoadImage returns null

### ISSUE THREAD

**Issue by danvallejo** [bytedeco/javacv#560]
On a mac...
```
String filename = "1024-avatar.jpg";

File file = new File(filename);
        if (file.exists()){
            logger.error("File doesn't exist [{}]", file.toString());
        }

opencv_core.IplImage image = opencv_imgcodecs.cvLoadImage(filename, CV_LOAD_IMAGE_COLOR);

```
image is always null and it does exist in the working directory.

I also tried cvLoadImage with only the filename.

**Comment by danvallejo** [comment]
Hold on bug in the code.

**Comment by danvallejo** [comment]
close for now.

**Comment by Alertis** [comment]
Hi, I try at from Android Studio but I have same problem. 
` IplImage src= cvLoadImage("/sdcard/javacvtest/data/lena.png");`
Can you help me? Excuse, I am beginners in JavaCV.
Thanks
