### ISSUE TITLE
Example of Android for pulling H.264 over RTMP 

### ISSUE THREAD

**Issue by wcenGitHub** [bytedeco/javacv#563]
Hi as the title, could you please give me an example of android for pulling stream over rtmp and display as video and audio?

i'm stuck here,

FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("URL");
AndroidFrameConverter converterToBitmap = new AndroidFrameConverter();
OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();

opencv_core.Mat mat = converterToMat.convert(grabber.grab());

i don't know what to do with Frame and Mat objects for displaying video and audio on android

Thanks

**Comment by menna-ali** [comment]
Please check this thread on stackoverflow, it suggests that all you need to do is change the ffmpeg_link in the sample class RecordActivity.java:

http://stackoverflow.com/questions/29018606/android-stream-camera-as-rtmp-stream

I am trying to do the same thing. So, let me know if it works!

**Comment by wcenGitHub** [comment]
Hi Menna, I have read that post and I think that is for pushing camera frames to the server not pulling

**Comment by wcenGitHub** [comment]
any update on this? thanks

**Comment by saudet** [comment]
Thanks to @leaf918, we now have a sample project for that here:
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-video-extract
Enjoy!
