### ISSUE TITLE
Gradle DSL Method not found:

### ISSUE THREAD

**Issue by Narektov** [bytedeco/javacv#565]
Error:(10, 0) Gradle DSL method not found: 'compile()'
Possible causes:The project 'JavaCV' may be using a version of Gradle that does not contain the method.
The build file may be missing a Gradle plugin.
Apply Gradle plugin

**Comment by saudet** [comment]
Could you explain what you are trying to do?

**Comment by saudet** [comment]
If you are trying to build JavaCV from source, please use Maven, not Gradle.
