### ISSUE TITLE
How to record live stream delayed (programmatically)?

### ISSUE THREAD

**Issue by emresen** [bytedeco/javacv#566]
Hi,

i have a problem. My logic is finished and it works very well. But i can't implement the last important thing. My goal is to analyze a part of 45 seconds of a live stream and record it after this part is finished. Maybe i will record the frames 1,5-2 minutes delayed.

I have to analyze at first 45 seconds, because the process is not depending only on one frame. I have to know about, what is happening for example 30seconds later.

Here is my logic:

int i = 0;
List<Frame> grabbedImages = new ArrayList<Frame>();
while ((grabbedImage = grabber.grab()) != null) {
            // DO ANALYZE FRAMES HERE.
	    grabbedImages.add(grabbedImage);
            i++;
           if (i > 1000) {
                  // PROCESS FRAMES HERE, WHICH WILL BE RECORDED
		  recorder.record(grabbedImages.get(0));
		  grabbedImages.remove(0);
          }
}

The logic is working, but the result is like recorded in "slow motion" :) and the sound is not available after the first 4-5seconds.

What is the correct way to do that?

Thanks

**Comment by saudet** [comment]
We need to add/remove an equivalent amount of audio frames, in addition to
video frames.

**Comment by saudet** [comment]
To create a delay, add blank frames.
