### ISSUE TITLE
JavaCV in Android : Error libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 32697.

### ISSUE THREAD

**Issue by AnujaK1** [bytedeco/javacv#568]
#Hi, 
I am new to JavaCV. I want to use this library for edge detections in provided image in Android so I have started with small code.

I have written this code in onCreate() 
```
opencv_core.IplImage iplImage = opencv_imgcodecs.cvLoadImage(path + "trial.png", opencv_imgcodecs.CV_LOAD_IMAGE_GRAYSCALE);
opencv_imgproc.cvSmooth(iplImage, iplImage, opencv_imgproc.CV_BLUR, 9, 9, 2, 2);
opencv_imgproc.cvCanny(iplImage, iplImage, 0, 0);
opencv_core.cvSave(path + "img1.png", iplImage);
```
Expecting img1.png as grayscaled image of trial.png. 
But when first line is executed I am getting this error in logcat

`com.example.myapplication A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 32697 (x.myapplication)
`

These gradle dependencies I have added in build.gradle file
```
 configurations {
        all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
}
dependencies{
        compile group: 'org.bytedeco', name: 'javacpp', version: '1.2'
        compile group: 'org.bytedeco', name: 'javacv', version: '1.2'
        compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2'
}
```
Please help am I missing something? Why am I getting this error.

**Comment by saudet** [comment]
You'll need to add platform specific artifacts for Android as well.

**Comment by AnujaK1** [comment]
I tried with adding
`compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-x86'`
Now the issue has been resolved. Thanks!
