### ISSUE TITLE
FaceRecognizer Error: I think there may be some problems about OpenCV.

### ISSUE THREAD

**Issue by Shudeng** [bytedeco/javacv#569]
The error is like this :

CV_LOAD_IMAGE_GRAYSCALE cannot be resolved to a variable
CV_LOAD_IMAGE_GRAYSCALE cannot be resolved to a variable
 
I very be very appreciated if someone can give a help! Thank you very much!!

**Comment by saudet** [comment]
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_imgcodecs.html#CV_LOAD_IMAGE_GRAYSCALE
