### ISSUE TITLE
FFmpeg's scale filter is not working

### ISSUE THREAD

**Issue by Malthael** [bytedeco/javacv#570]
I'm trying to scale images which are recorded by `FFmpegFrameRecorder`. In fact, I want to scale images from 1024\*768 to 768\*1024.

The initialization code is:
```
int width = 1024;
int height = 768;

Frame yuvImage = new Frame(width, height, Frame.DEPTH_UBYTE, 2);

FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(liveUrl, height, width, 1);

FFmpegFrameFilter filter = new FFmpegFrameFilter("scale=ih:iw", width, height);
filter.setPixelFormat(avutil.AV_PIX_FMT_NV21);
```

And the filtering and recording code is:
```
filter.push(yuvImage);

while ((tmpFrame = filter.pull()) != null) {
    recorder.record(tmpFrame, avutil.AV_PIX_FMT_NV21);
}
```

The recorded images are still 1024\*768...

Besides, I'm confused with the meaning of the `imageWidth` and `imageHeight` in the constructor of `FFmpegFrameRecorder` and `FFmpegFrameFilter`. Do they represent the size of input image or the output? Thx

**Comment by saudet** [comment]
The size of the output, so you'll need to change them.
