### ISSUE TITLE
Cannot find lib libjniopencv_core.so

### ISSUE THREAD

**Issue by michalisKolozoff** [bytedeco/javacv#572]
Hello, I am trying to use openCV in a face recognition application. I have included openCV3.1 in my project following issue #5862, but my application still crashes. I get the exception:

>  java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-javacv_1114b309da76c7e9985fae878d9033bdea43b23e-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-javacpp_0ec04ba422642184c497d1aecd8910efc28f3205-classes.dex", dex file "/data/data/eu.upcom.recred.facerec/files/instant-run/dex/slice-javacpp-0.11_6c6800d74e6c59d3746abfb094d3ee9c2e02478f-classes.dex"],nativeLibraryDirectories=[/data/app/eu.upcom.recred.facerec-1/lib/arm, /data/app/eu.upcom.recred.facerec-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libjniopencv_core.so"

following issue #314 I changed my gradle to 

`dependencies {
    compile project(':openCVLibrary310')
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')

    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.11-0.11', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '2.4.11-0.11', classifier: 'android-x86'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.6.1-0.11', classifier: 'android-arm'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.6.1-0.11', classifier: 'android-x86'

}

`

**Comment by saudet** [comment]
Please try again with JavaCV 1.2.

**Comment by michalisKolozoff** [comment]
changed my gradle to 

`dependencies {
    compile files('libs/javacpp.jar')
    compile files('libs/javacv.jar')
    compile project(':openCVLibrary310')
    compile 'org.bytedeco:javacv:1.2'
    compile 'org.bytedeco.javacpp-presets:opencv:3.1.0-1.2'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:3.0.2-1.2'
}`

and still the same error

**Comment by michalisKolozoff** [comment]
I cannot use javaCV 1.2 because some classes have been changed. My problem still persists. How can I add libjniopencv_core.so

**Comment by saudet** [comment]
Please follow https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by michalisKolozoff** [comment]
I do not use System.loadLibrary in my project. Isn't linker responsible for fixing loadLibrary?

**Comment by michalisKolozoff** [comment]
My question is not answered however. I still get the UnsatisfiedLinkError exception when I am trying to execure `      faceRecognizer =  createLBPHFaceRecognizer(2,8,8,8,200);
`

**Comment by saudet** [comment]
Ok, try this workaround: https://github.com/bytedeco/javacv/issues/470#issuecomment-236154627

**Comment by michalisKolozoff** [comment]
I am already using openCV 2.4.1 and as I said I do not load any libraries dynamically, except for the 

```
import static com.googlecode.javacv.cpp.opencv_core.IPL_DEPTH_8U;
import static com.googlecode.javacv.cpp.opencv_highgui.cvLoadImage;
import static com.googlecode.javacv.cpp.opencv_imgproc.CV_BGR2GRAY;
import static com.googlecode.javacv.cpp.opencv_imgproc.cvCvtColor;
import static com.googlecode.javacv.cpp.opencv_contrib.*;
```

this workaround suggests that I should call

`Loader.load(opencv_objdetect.class);`

**Comment by saudet** [comment]
Well, if you would like to update to JavaCV 1.2, please tell me about what API changes you are having problems with and I could help you with that.

**Comment by libathos** [comment]
Ok thank you very much for your support. Right now, I do not know why, but without having changed anything, the code works.. sometimes. Let me explain. As I said I use in my project openCV 2.4.1 I use a javaCV and javacpp jars which I cannot accurately tell you their version as this is a legacy code handed onto me. And by downloading the openCV sdk for android I installed in my phone the openCV manager 2.4.10.0 rev1 for armv7a neon. When I start the application it prompts for a openCV manager to be installed, then I choose no as There already is an openCV manager. Then I go run openCV manager and switch the to app again, then It runs as it should. Can you guess why this bug appears? Thank you again for your support

**Comment by saudet** [comment]
Sounds like a bug with the OpenCV Manager. That's unrelated to JavaCV.

**Comment by libathos** [comment]
Cannot tell for sure, Is there any way to incorporate openCV manager dependant files into my application in order not to need to have openCV manager installed?

**Comment by saudet** [comment]
That's what JavaCV does, so use JavaCV instead of OpenCV Manager.

**Comment by libathos** [comment]
But there are some classes that are within the openCV and not in JavaCV like the 
`CvCameraViewListener2` etc...

**Comment by libathos** [comment]
I can post the imports that are in the openCV framework and not in the javaCV to check if we can resolve the conflicts.

**Comment by saudet** [comment]
Well, you'll need to do some refactoring if you want to get rid of CvCameraViewListener2. There isn't a drop in replacement for that.

**Comment by libathos** [comment]
Look as I said this is a legacy code and CVCameraViewListener2 is just an example there are other classes too, I do not believe it is worthwhile. So, In your opinion not finding the manager is a openCV issue rather that a javaCV?

**Comment by saudet** [comment]
Yes, JavaCV doesn't use the manager.

**Comment by libathos** [comment]
ok thanks :)
