### ISSUE TITLE
JavaCV master-version can not run in my eclipse!

### ISSUE THREAD

**Issue by lelehome** [bytedeco/javacv#573]
Hi,Samuel,  I ran into a problem during the building of JavaCV master-version.

I use eclipse, and I have import the project by:

eclipse->import->Projects from Git->Clone URI, then copy "https://github.com/bytedeco/javacv.git", and follow the prompts to complete the import of the project.

Then right-click the project->Configure->Convert to faceted form

but  I found some missing jars in the project,  
![image](https://cloud.githubusercontent.com/assets/23007606/20863693/eb13cb4e-ba0d-11e6-89c8-b3f24aae9488.png)

then I checked the repository as follows, and I found no corresponding jar in the snapshotRepository.
<snapshotRepository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
 </snapshotRepository>

Now, I can not run the samples in Javacv.
what should I do to fix the problem.
Thanks.

**Comment by saudet** [comment]
Build JavaCPP and the Presets from source as well.
