### ISSUE TITLE
Grabcut not working in JavaCV

### ISSUE THREAD

**Issue by akhatriST** [bytedeco/javacv#574]
I am following this example for Grabcut
https://github.com/bytedeco/javacv-examples/blob/master/OpenCV2_Cookbook/src/main/scala/opencv2_cookbook/chapter05/Ex5GrabCut.scala

```
        Mat result = new Mat();
        int iterCount = 5;
        int mode = opencv_imgproc.GC_INIT_WITH_RECT;

        // Need to allocate arrays for temporary data
        Mat bgdModel = new Mat();
        Mat fgdModel = new Mat();

        // GrabCut segmentation
        opencv_imgproc.grabCut(sourceImg, result, rect, bgdModel, fgdModel, iterCount, mode);

        // Prepare image for display: extract foreground
        opencv_imgproc.threshold(result, result, opencv_imgproc.GC_PR_FGD - 0.5,
                opencv_imgproc.GC_PR_FGD + 0.5, opencv_imgproc.THRESH_BINARY);
```

The problem I am facing is that the mask returned after Grabcut is always black, and the rect I am using is within the bounds of the source image
```Rect rect = new Rect(10, 100,  380, 180);```

Is GrabCut Api broken, or am I missing something. Because I've tried up all the possible ways of using the GrabCut Api but still unable to get it work.

Thanks

**Comment by saudet** [comment]
@jpsacha ideas?

**Comment by jpsacha** [comment]
I cannot reproduce the issue. Tested latest release of cookbook2-examples
grabcut works fine.

**Comment by jpsacha** [comment]
@akhatriST can you provide [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) of your problem?

**Comment by akhatriST** [comment]
@jpsacha I am running this on Windows 10 using Gradle
```compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0' + '-1.2', classifier: 'windows-x86_64'```
Reading the image as Mat from a file using `Mat imgMat = opencv_imgcodecs.imread(filePath);` and passing this Mat to my grabcut function below:

```
private Mat grabCut(Mat sourceImg, Rect rect) {
       Mat firstMask = new Mat();
        Mat foregroundModel = new Mat();
        Mat backgroundModel = new Mat();

        opencv_imgproc.grabCut(sourceImg, firstMask, rect, backgroundModel, foregroundModel, 1,
                opencv_imgproc.GC_INIT_WITH_RECT);

        Mat source = new Mat(firstMask.size(), firstMask.type(), new Scalar(opencv_imgproc.GC_FGD));
        opencv_core.compare(firstMask, source, firstMask, opencv_core.CMP_EQ);

        Mat foreground = new Mat(sourceImg.size(), opencv_core.CV_8UC4, new Scalar(255,255,255,255));
        sourceImg.copyTo(foreground, firstMask);

        firstMask.release();
        foregroundModel.release();
        backgroundModel.release();
        source.release();

        return foreground;
}
```
My intention of using Grabcut is to reduce the noise from an image, and to accomplish that I want to subtract the Grabcut mask from my `sourceImg` Mat and return it back for further processing. Also I've tried out various combinations of `rect`. 
The problem is that the mask returned from Grabcut is always black instead of black and white, therefore I am unable to get the desired result in my `foreground` Mat after subtracting the mask using the `opencv_core.compare` function. 

Hope I have explained it better this time :) and please do let me know if there are other ways to do this

Thanks

**Comment by jpsacha** [comment]
I can lokk at it at a moment. I am away from a computer for a couple of
days.

**Comment by akhatriST** [comment]
@jpsacha @saudet Any update on this? I am having the same issue or is there anything wrong in my code
Thanks

**Comment by akhatriST** [comment]
Sorry! pressed the wrong button :)

**Comment by akhatriST** [comment]
@saudet anything on this,

**Comment by jpsacha** [comment]
@akhatriST I tested grubcut one more time, with latest version of javacv (1.3). It works fine in new version too. You may have issues related to processing you do after grubcut. Did you check the content of your `firstMask`?

**Comment by akhatriST** [comment]
@jpsacha Yes I have checked it, its all black. I created an image from firstMask it was all black. Don't know why this is happening. 
BTW I am running this on Windows 10.

**Comment by akhatriST** [comment]
@jpsacha Can you share the code that you are running, so that I can try and see if it works for me
Thanks

**Comment by jpsacha** [comment]
@akhatriST I am testing using the [Ex5GrabCut.scala](https://github.com/bytedeco/javacv-examples/blob/master/OpenCV2_Cookbook/src/main/scala/opencv2_cookbook/chapter05/Ex5GrabCut.scala)

**Comment by akhatriST** [comment]
@jpsacha This is strange. I've tried that version too but don't get it right.
If possible can you post your java version for this. Also can you tell me which OS are you running on? so that we can strike out the possibility of this problem be an OS specific. Thanks

**Comment by jpsacha** [comment]
@akhatriST I am using code as published in the Cookbook-Examples `master` branch, running from SBT.  [Ex5GrabCut.scala](https://github.com/bytedeco/javacv-examples/blob/master/OpenCV2_Cookbook/src/main/scala/opencv2_cookbook/chapter05/Ex5GrabCut.scala) works fine on Windows 10 Java 8 112, Ubuntu, and Mac.

**Comment by akhatriST** [comment]
@jpsacha Thanks for your support, I've figured out the problem in my code and it is working as expected now.  
Closing this...

**Comment by ralienpp** [comment]
@akhatriST can you explain how exactly you solved the problem?

**Comment by akhatriST** [comment]
@ralienpp Its been 4 years since I worked on this. I am sorry I am unable to recall what I did to get around this issue. 
Hope you find something on this.
