### ISSUE TITLE
Exception in thread “main” java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil"

### ISSUE THREAD

**Issue by PRCV** [bytedeco/javacv#581]
I've tried to run a java application with an FFMmpegFrameGrabber while trying to run on windows. However same jar file runs on linux with no exceptions.

I have included javacpp and javacv jars .

However while running on windows I am getting this error main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil"
![capture](https://cloud.githubusercontent.com/assets/9638830/21099076/3b17ac0c-c092-11e6-842e-b75f9bb21279.PNG)

**Comment by PRCV** [comment]
this is where i am getting the error `public static class AVFormatContext extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public AVFormatContext() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public AVFormatContext(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public AVFormatContext(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public AVFormatContext position(long position) {
        return (AVFormatContext)super.position(position);
    }`

**Comment by saudet** [comment]
Please try again with version 1.3.

**Comment by PRCV** [comment]
Replaced with 1.3 but still getting same error .

**Comment by saudet** [comment]
Please use the `pom.xml` file provided in the README.md file:
https://github.com/bytedeco/javacv#sample-usage

**Comment by fjank** [comment]
I also had that same behavior (windows, 64-bit, ffmpegframegrabber),
Workaround that worked for me:

```java
// Preload the opencv_objdetect module to work around a known bug. 
Loader.load(opencv_objdetect.class);
```

**Comment by saudet** [comment]
Could you run Dependency Walker as explained on the page below and let me know what you get?
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows#using-dependency-walker
Replace `<module>` with `avutil` in this case. Thanks!

**Comment by saudet** [comment]
I see you've just included `javacv.jar` and `javacpp.jar`. This won't work. Please include **ALL** the JAR files.
