### ISSUE TITLE
What's the JavaCV Mat's equivalent of Mat.Put(int row, int col, double... data)

### ISSUE THREAD

**Issue by uditmukherjee** [bytedeco/javacv#587]
Newbie here, As the title says I am trying to do Mat.put(int row, int col, double... data) to build a lookup table to apply a curve filter.

The OpenCV code I had written was 

       `lookupImage = new Mat();

        UnivariateFunction valueInterpolator = interpolate(builder.getV_x(), builder.getV_y());
        UnivariateFunction redInterpolator = interpolate(builder.getR_x(), builder.getR_y());
        UnivariateFunction blueInterpolator = interpolate(builder.getB_x(), builder.getB_y());
        UnivariateFunction greenInterpolator = interpolate(builder.getG_x(), builder.getG_y());

        lookupImage.create(256, 1, CV_8UC4);

        for (int i = 0; i < 256; i++) {
            final double v = valueInterpolator.value(i);
            final double r = redInterpolator.value(v);
            final double g = greenInterpolator.value(v);
            final double b = blueInterpolator.value(v);

            lookupImage.put(i, 0, r, g, b, i);
        }`

but JavaCv's Mat.put seems to only have `Mat`, `MatExpr`, `Scalar` and `pointer`

**Comment by saudet** [comment]
Use an Indexer: http://bytedeco.org/news/2014/12/23/third-release/

**Comment by uditmukherjee** [comment]
I used the indexer but I'm getting ambiguous method call between `indexer.put(int, int...)` and `indexer.put(int, int, int...)`

This is my code:

`

        lookupImage.create(256, 1, CV_8UC4);
        UByteBufferIndexer indexer = lookupImage.createIndexer();

        for (int i = 0; i < 256; i++) {
            final double v = valueInterpolator.value(i);
            final Double r = redInterpolator.value(v);
            final Double g = greenInterpolator.value(v);
            final Double b = blueInterpolator.value(v);

            indexer.put(i, 0, r.intValue(), g.intValue(), b.intValue(), i);
        }
`

**Comment by saudet** [comment]
Just use `put(int, int, int)` as per the sample code this page:
http://bytedeco.org/news/2014/12/23/third-release/
