### ISSUE TITLE
ffmpeg frame sync, help pls

### ISSUE THREAD

**Issue by arliweng** [bytedeco/javacv#588]
when i sleep the 5 sec after grab the frame, got next frame not after 5 sec's frame.
if i try ip camera with RTSP, how can i sync to camera's  current frame(drop other frame).
should i need loop grab(drop) in that time? but if that time cpu busy not in my control, how do i known which time i need grab(drop)?
sorry, i don't known how to say, maybe somebody can help, pls
the code:
```java
final Java2DFrameConverter j2 = new Java2DFrameConverter();
final FFmpegFrameGrabber ffg = new FFmpegFrameGrabber("rtsp://192.168.0.77/11");
ffg.start();

Frame f = ffg.grabImage();
BufferedImage bi = j2.convert(f);
ImageIO.write(bi, "jpg", new File("/home/arli/1.jpg"));

 //cpu busy
Thread.sleep(5000);
//cpu free  after 5 sec

Frame f2 = ffg.grabImage(); //are next frame, not after 5 sec frame
BufferedImage bi2 = j2.convert(f2);
ImageIO.write(bi2, "jpg", new File("/home/arli/2.jpg"));

ffg.stop();
```

**Comment by saudet** [comment]
Yes, grab in a loop until 5 seconds has passed. `Thread.sleep()` will do no good.

**Comment by arliweng** [comment]
thank u for reply, but i say, that time are cpu busy not in my control.. i have known that time are 5 sec, how can i continue? loop grab 5 sec, so i have to loop again because that "loop grab" have time delay, i must loop again, and again?

**Comment by saudet** [comment]
You could use a new thread for the grab loop.

**Comment by arliweng** [comment]
that cpu busy out of my control(by other application or hardware), not block in current thread...

**Comment by saudet** [comment]
Ah, good luck, this will be hard to do :)

**Comment by arliweng** [comment]
or try this:
1.mp4 has 25 fps, but cpu too slow(maybe arm, maybe intel i5 but big resolution) only can process 20 fps/sec, so after 3 sec, the frame delay of 15 how do i drop?

**Comment by arliweng** [comment]
confirm can't doin FFmpegFrameGrabber, we must create an Grabber split the rtsp and decoder in differ process, do rtsp buff and drop(may before decode, so we have to keep last key frame in that time).
referer https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/rtsp.c

thank u for help

**Comment by saudet** [comment]
Ah, I see, if the only problem is the decoding speed, we could also enhance FFmpegFrameGrabber to support dropping packets.

**Comment by guijob** [comment]
@arliweng I'm actually facing this same problem. Did you find any new approaches to solve it? I wouldn't like to create a new thread with a while true loop dropping frames and keeping my cpu foverer busy. I've tried your link above but 2.5k lines of code to understand what is happening is too much.

**Comment by arliweng** [comment]
after close long time ago, somebody ask me for help.. i post here about this, FFmpegFrameGrabber just decoder not player, we need do it my self, may loop without draw until sync, may drop in the rtsp..

**Comment by saudet** [comment]
Thanks for the update @arliweng! FFmpeg now also supports MediaCodec on Android, so that's another option for those users.
