### ISSUE TITLE
create Facerecognition dataset

### ISSUE THREAD

**Issue by vicky9009** [bytedeco/javacv#589]
I have created facerecognition sample where i can detect and save images of faces real time. when i tried to recognize this faces again that time got this error:
OpenCV Error: Unsupported format or combination of formats (In the Eigenfaces method all input samples (training images) must be of equal size! Expected 26896 pixels, but was 26244 pixels.) in cv::face::Eigenfaces::train, file 

is there any way where i can use this images for recognition(or training)

how can i make all captured images with same size and pixel 
 Highgui.imwrite(String.valueOf(System.currentTimeMillis()) + ".jpg", faceImage);
am using above statment to save detectd faces.

**Comment by saudet** [comment]
Try to call resize() on the images beforehand to get images all of the same
size.
