### ISSUE TITLE
How to convert Mat to IplImage in Javacv ?

### ISSUE THREAD

**Issue by vicky9009** [bytedeco/javacv#592]
Is any one know how i can convert Mat to IplImage ? to achieve this i have converted Mat to BufferedImage but again not able to find conversion in BufferedImage to IplImage.

is there any way where i can convert Mat to IplImage?

Thanks

**Comment by saudet** [comment]
Yes, just call [new IplImage(Mat)](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.IplImage.html#opencv_core.IplImage(org.bytedeco.javacpp.opencv_core.Mat)).

**Comment by vicky9009** [comment]
Hi saudet,
thanks for your reply, but am getting compilation error while converting .
Error: No suitable constructor found for IplImage(org.opencv.core.Mat)  am using javacv 0.7 version

**Comment by saudet** [comment]
So, please upgrade.

**Comment by mistes32** [comment]
this method failed when using 
cvMorphologyEx(source, source, temp, kernel, operation, action.count) with 
Unknown array type in function 'cvarrToMat' at org.bytedeco.opencv.global.opencv_imgproc.cvMorphologyEx(Native Method)

**Comment by saudet** [comment]
@mistes32 Use morphologyEx() instead. The C API is deprecated and (new) bugs are no longer fixed by OpenCV.

**Comment by mistes32** [comment]
@saudet is there any method for CV_SHAPE_CUSTOM ?

**Comment by saudet** [comment]
That's just a constant, you should be able to continue using that.

**Comment by mistes32** [comment]
well i'm talking about method ```
cvCreateStructuringElementEx(
             int cols, int rows, int anchor_x, int anchor_y,
             int shape, int[]  values/*=NULL*/ );
```
where shape=CV_SHAPE_CUSTOM and user defined values passed

**Comment by saudet** [comment]
Again, the C API is deprecated. Don't use cvCreateStructuringElementEx(), use getStructuringElement() instead.

**Comment by mistes32** [comment]
there is no overloaded getStructuringElement method where i can pass my custom values for custom kernel

**Comment by mistes32** [comment]
I have found a workaround to convert IplMat to Mat using Java2DFrameUtils and it works fine.

**Comment by saudet** [comment]
We can use this function for that:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/opencv/global/opencv_core.html#cvarrToMat-org.bytedeco.opencv.opencv_core.CvArr-boolean-boolean-int-org.bytedeco.javacpp.Pointer-

**Comment by shiraJacobs** [comment]
Hi, 
After converting a Mat to IplImage as you told above,
I want to save this with the function cvSaveImage() like this:
       diff=opencv_imgcodecs.imread("./img.png");
        IplImage image=new IplImage(diff);
        cvSaveImage("./MyDiff.png", image);
but I'm getting this error:
error: (-5:Bad argument) Unknown array type in function 'cv::cvarrToMat'
