### ISSUE TITLE
FaceRecognizer predict and get multiple results

### ISSUE THREAD

**Issue by paradoxalan** [bytedeco/javacv#596]
I'm trying to implement code to get top 5, or top 10 predicted faces closest to the source image being compared. I can get the top most using the example provided with success.
I found nothing for multiple results in the examples. Can anyone help, or share code, or guide me on how to acomplish this!?

**Comment by saudet** [comment]
FYI, sounds like a question for http://answers.opencv.org/

**Comment by paradoxalan** [comment]
Oh ok, I'll go there, thanks for the reply!
Is solved then, thank you very much

**Comment by saudet** [comment]
And the answer is here:
http://answers.opencv.org/question/73045/is-it-possible-to-get-multiple-prediction-from-facerecognizer/
