### ISSUE TITLE
FFmpegFrameGrabber.processImage()

### ISSUE THREAD

**Issue by xiaos** [bytedeco/javacv#597]
inside FFmpegFrameGrabber.processImage(), I get the following error, I checked the source code:
        _this.frame.image[0].limit(this.frame.imageHeight * this.frame.imageStride);_
 **this.frame.image[0] is null.**
 but still don't know why got this error, can anyone help to explain? thanks.

Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.nio.Buffer java.nio.Buffer.limit(int)' on a null object reference

org.bytedeco.javacv.FFmpegFrameGrabber.processImage (FFmpegFrameGrabber.java:611)
org.bytedeco.javacv.FFmpegFrameGrabber.grabFrame (FFmpegFrameGrabber.java:683)
org.bytedeco.javacv.FFmpegFrameGrabber.grab (FFmpegFrameGrabber.java:616)
org.bytedeco.javacv.FrameGrabber.grabFrame (FrameGrabber.java:444)

**Comment by saudet** [comment]
Could you provide some code and data to reproduce that?

**Comment by xiaos** [comment]
Sorry, I cannot reproduce the error, but i found many cases from my users.

**Comment by saudet** [comment]
It seems to be a rather old version of JavaCV. Maybe you could try to upgrade to version 1.3?

**Comment by xiaos** [comment]
I am facing the linking error for java cv1.3

**Comment by saudet** [comment]
You're going to need to provide a bit more details if you want some help.

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming that you have been able to resolve this issue, but please reopen if this is not the case! Thank you
