### ISSUE TITLE
matchTemplate of identical images

### ISSUE THREAD

**Issue by anotherche** [bytedeco/javacv#600]
I apologize if my question is not  appropriate here, probably I should ask opencv project instead. But I'm using javacv in my project, so I ask here first.
Additionally to finding a template in an image I need a measure of similarity between the template and the corresponding similar area of the image. So I should analyze values of results returned by the matchTemplate. But the simplest test of matching identical images returns incorrect result as I think.
The code like:
```    
    Mat sourceMat = ... the Mat containing some crop from an image
    Size size = new Size(1, 1);
    Mat result = new Mat(size, CV_32FC1);
    matchTemplate(sourceMat, sourceMat, result, method);
    FloatBuffer fb = result.createBuffer();
    return fb.get(0);
```
should obviously return zero if method is CV_TM_SQDIFF, or it should return 1 if method is CV_TM_CCORR_NORMED. But it does not. OK _NORMED methods may return not exact 1 because of possible rounding errors. But CV_TM_SQDIFF should return exact zero on the identical images as it simply computes squared pixel-to-pixel difference. Sometimes it returns zero, sometimes not, depending on the selected part (crop) of the whole source image. What is the reason? Is this opencv issue?

**Comment by saudet** [comment]
Do something like this sample code and it will work:
https://github.com/bytedeco/javacv/blob/master/samples/TemplateMatching.java

**Comment by anotherche** [comment]
:) Thank you! The code in the question is similar to the sample code suggested. The code is working. Matching works perfect. But the question was different. Why matchTemplate returns non-zero result for 2 identical images in case of using square difference as the match method?

**Comment by saudet** [comment]
Do you get the same result when using the C++ API directly? If so, then I would say this is a bug in OpenCV...

**Comment by anotherche** [comment]
I did not try the original API yet. I will try.

**Comment by anotherche** [comment]
Yes, the result goes from OpenCV. I cannot understand if this is a bug or a feature.. OpenCl is used there, so the code is awesome for me. It seems that not direct squared difference is calculated but some other non-direct algorithm is used. Probably more effective but with some approximation side effect.

**Comment by repte** [comment]
I copied your code from here 
https://github.com/bytedeco/javacv/blob/master/samples/TemplateMatching.java
but I am too stupid to make it work. I managed to add all libaries but where should I put my String to the image paths?
