### ISSUE TITLE
avcodec.AV_CODEC_ID_MPEG4 consuming too much memory

### ISSUE THREAD

**Issue by danielnazareth** [bytedeco/javacv#601]
Hello!
I'm using your lib, and it works like a charm, but, when I use: 

 mVideoRecorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);

 instead of:

mVideoRecorder.setVideoCodec(recorderParameters.getVideoCodec()); 

the memory goes crazy!
I'm testing on a Motorola Moto G 2014, and with the first code, with ~30sec recording, the app uses 255MB of RAM (!), and with the second one, it keept stable at ~50MB during all time.

**Comment by saudet** [comment]
Well, don't use that codec! :) If you want to know why that codec uses so much memory, you should ask the authors of the codec.
