### ISSUE TITLE
No accelerated colorspace conversion found from yuv420p to bgr24

### ISSUE THREAD

**Issue by ArjunAchatz-MF** [bytedeco/javacv#604]
So I am using JavaCV + FFMPEG frame grabber in an android application, and although it is getting valid images per frame, it is terribly slow on the Nexus 6P. Also I keep getting this msg every frame.

[swscaler @ 0xa95f2000] deprecated pixel format used, make sure you did set range correctly
No accelerated colorspace conversion found from yuv420p to bgr24.

I'm thinking if I can figure this out and remove the reason why this could be happening, it would speed up the frame grabbing by some bit at least.

It should be noted that out of all the phones I tested, this is the slowest one and seems to be the only one that gives this msg.

My first thoughts are the Nexus 6P has done some more weirdness compared to every other phone out there, especially since its camera orientation is different then 90% of android phones out there.

**Comment by saudet** [comment]
You could do the conversion in RenderScript or OpenGL. That would speed up
things quite a bit.

**Comment by ArjunAchatz-MF** [comment]
Are you suggesting getting raw yuv data from the video, frame by frame, and assuming it's yuv420 convert it via RenderScript ? I.e rewriting some of the code in FFMpegFrameGrabber? Also I try not to make assumptions with Android devices .. does this really sound like a good idea for a wide variety of phone ? And I ask humbly as you're clearly quite experienced !

**Comment by saudet** [comment]
RenderScript and OpenGL are portable across devices yes. See this comment: https://github.com/bytedeco/javacv/issues/163#issuecomment-197988421
