### ISSUE TITLE
Unable to play video produced by JavaCV in JavaFX MediaView

### ISSUE THREAD

**Issue by Xzynos** [bytedeco/javacv#606]
Greetings,

I am a beginner coder and I would like some assistance. The video produced by the JavaCV recorder can be played with VLC, however, when I try to play it in JavaFX's MediaView, only audio plays while there is no video. I have tried using other .mp4 files that I downloaded from my phone's camera and it plays just fine with both audio and video. However, when I tried to play the file produced by JavaCV, only the audio plays. I have made sure that i have not altered anything when I tested it aside from the file path. I was wondering if it could be the output of JavaCV may be corrupted. `Assistance` would me greatly appreciated :)

Here is the code that I adapted for from WebcamAndMicrophoneCapture.java and used to record the video and audio: 

public class JVA {
	private boolean jVARunning;
	
	// Output File Path
	private String outputFilePath;
	
	// Webcam Device Index defaults to 0
	private int webCamDeviceIndex;
	
	// Frame Rate defaults to 30
    private int frameRate; 
	
	// GOP Length defaults to 60 (Frame Rate * 2)
    private int gopLength;
    
    // Capture Width defaults to 1280
    private int capWidth;
    
    // Capture Height defaults to 720
    private int capHeight;
    
    // Constant Rate Factor for Video defaults to 28
    private String constantRateFactorVideo;
    
    // Video Bit Rate defaults to 2000 * 1000
    private int videoBitRate;
	
    // Microphone Device Index defaults to 4
    private int audioDeviceIndex; 
    
    // Audio Channels defaults to 1
    private int audioChannels;
    
    // Constant Rate Factor for Audio defaults to 0
    private String constantRateFactorAudio;
    
    // Audio Quality defaults to 0
    // 0 -> Highest Quality
    private int audioQuality;
    
    // Audio Bit Rate defaults to 192 * 1000
    private int audioBitRate;
    
    // Interleaved defaults to true
    private boolean interleaved;
    
    // Encoding Speed defaults to UltraFast
    // Encoding Speeds:
    // 1. UltraFast,
    // 2. SuperFast, 
    // 3. VeryFast, 
    // 4. Faster, 
    // 5. Fast,
    // 6. Medium, 
    // 7. Slow, 
    // 8. Slower, 
    // 9. VerySlow
    private String encodingSpeed;
    
    // Sample Rate defaults to 44100
    private int sampleRate;
    
    private static long startTime;
    private static long videoTimeStamp;
    
    // Constant Variables
    // Video Format -> .mp4 
    final private String videoFormat = "mp4";
    
    // Components of JVA
    private OpenCVFrameGrabber frameGrabberOCV; 
    private FFmpegFrameRecorder frameRecorderFFmpeg;
    private AudioFormat audioFormat;
    private Mixer.Info[] mixerInfoArr;
    private Mixer mixer;
    private DataLine.Info dataLineInfo;
    private TargetDataLine targetDataLine;
    private byte[] audioBytes;
    private ScheduledThreadPoolExecutor exeThreadPool;
    private CanvasFrame canvasFrame;
    private Frame capturedFrame;
    
    private Thread recordThread = new Thread(new Runnable() {
    	@Override
    	public void run() {
    		try {
    			frameGrabberOCV.start();
    			frameRecorderFFmpeg.start();
    			
    			audioFormat =  new AudioFormat(44100.0F, 16, 2, true, false);
        		mixerInfoArr = AudioSystem.getMixerInfo();
        		mixer = AudioSystem.getMixer(mixerInfoArr[audioDeviceIndex]);
        		dataLineInfo = new DataLine.Info(TargetDataLine.class, audioFormat);
        		
        		try {
        			targetDataLine = (TargetDataLine)AudioSystem.getLine(dataLineInfo);
                    targetDataLine.open(audioFormat);
                    targetDataLine.start();
                    
                    int sampleRate = (int) audioFormat.getSampleRate();
                    int numChannels = audioFormat.getChannels();
                    int audioBufferSize = sampleRate * numChannels;
                    
                    audioBytes = new byte[audioBufferSize];
                    
                    exeThreadPool = new ScheduledThreadPoolExecutor(1);
                    exeThreadPool.scheduleAtFixedRate(new Runnable() {
                    	@Override
                        public void run() {
                    		if (!exeThreadPool.isTerminated()) {
    	                        try {
    	                            int nBytesRead = targetDataLine.read(audioBytes, 0, targetDataLine.available());
    	                            int nSamplesRead = nBytesRead / 2;
    	                            
    	                            short[] samples = new short[nSamplesRead];
    	
    	                            ByteBuffer.wrap(audioBytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(samples);
    	                            ShortBuffer sBuff = ShortBuffer.wrap(samples, 0, nSamplesRead);
    	                            
    	                            frameRecorderFFmpeg.recordSamples(sampleRate, numChannels, sBuff);	
    	                        } catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
    	                        	
    	                        }
                    		}
                        }
                    }, 0, (long) 1000 / frameRate, TimeUnit.MILLISECONDS);
                    
        		} catch (LineUnavailableException e1) {
        			e1.printStackTrace();
        		}
        		
        		canvasFrame = new CanvasFrame("Interview Preview", CanvasFrame.getDefaultGamma() / frameGrabberOCV.getGamma());
    			
    			capturedFrame = null;
    			
    			while (!exeThreadPool.isTerminated()) {
    				if ((capturedFrame = frameGrabberOCV.grab()) != null) {
    					if (canvasFrame.isVisible())
    		            {
    		                canvasFrame.showImage(capturedFrame);
    		            }
    					
    		            if (startTime == 0) {
    		                startTime = System.currentTimeMillis();
    		            }
    		            
    		            videoTimeStamp = 1000 * (System.currentTimeMillis() - startTime);
    		            
    		            if (videoTimeStamp > frameRecorderFFmpeg.getTimestamp()) {
    		               frameRecorderFFmpeg.setTimestamp(videoTimeStamp);
    		            }
    		            
    		            jVARunning = true;
    		            frameRecorderFFmpeg.record(capturedFrame);
    	            }
    	        }
    		} catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
    			
    		} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
    		}
    	}
    });
    
    public JVA(String outputFilePath) {
    	this.jVARunning = false;
    	this.outputFilePath = outputFilePath;
    	
    	this.webCamDeviceIndex = 0;
    	this.frameRate = 30;
    	this.gopLength = this.frameRate * 2;
    	this.capWidth = 1280;
    	this.capHeight = 720;
    	this.constantRateFactorVideo = "28";
    	this.videoBitRate = 2000 * 1000;
    	
    	this.audioDeviceIndex = 4;
    	this.audioChannels = 1;
    	this.constantRateFactorAudio = "0";
    	this.audioQuality = 0;
    	this.audioBitRate = 192 * 1000;
    	
    	this.interleaved = true;
    	this.encodingSpeed = "UltraFast";
    	
    	this.sampleRate = 44100;
    	
    	this.startTime = 0;
    	this.videoTimeStamp = 0;
    	
    	frameGrabberOCV = new OpenCVFrameGrabber(webCamDeviceIndex);
    	frameGrabberOCV.setImageWidth(capWidth);
        frameGrabberOCV.setImageHeight(capHeight);
		
		frameRecorderFFmpeg = new FFmpegFrameRecorder(
				this.outputFilePath,
				capWidth, 
				capHeight, 
				this.audioChannels
				);
        frameRecorderFFmpeg.setInterleaved(interleaved);
        frameRecorderFFmpeg.setVideoOption("TUNE".toLowerCase(), "ZEROLATENCY".toLowerCase());
        frameRecorderFFmpeg.setVideoOption("PRESET".toLowerCase(), this.encodingSpeed.toLowerCase());
        frameRecorderFFmpeg.setVideoOption("CRF".toLowerCase(), this.constantRateFactorVideo.toLowerCase());
        frameRecorderFFmpeg.setVideoBitrate(this.videoBitRate);
        frameRecorderFFmpeg.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
        frameRecorderFFmpeg.setFormat(this.videoFormat);
        frameRecorderFFmpeg.setFrameRate(this.frameRate);
        frameRecorderFFmpeg.setGopSize(this.gopLength);
        frameRecorderFFmpeg.setAudioOption("CRF".toLowerCase(), this.constantRateFactorAudio.toLowerCase());
        frameRecorderFFmpeg.setAudioQuality(this.audioQuality);
        frameRecorderFFmpeg.setAudioBitrate(this.audioBitRate);
        frameRecorderFFmpeg.setSampleRate(this.sampleRate);
        frameRecorderFFmpeg.setAudioChannels(this.audioChannels);
        frameRecorderFFmpeg.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
    }
    public JVA(
    		String outputFilePath,
    		
    		// Video
    		int webCamDeviceIndex, 
    		int frameRate, 
    		int gopLength, 
    		int capWidth, 
    		int capHeight,
    		String constantRateFactorVideo,
    		int videoBitRate,
    		
    		// Audio
    		int audioDeviceIndex, 
    		int audioChannels,
    		String constantRateFactorAudio,
    		int audioQuality,
    		int audioBitRate,
    		
    		boolean interleaved,
    		String encodingSpeed,
    		
    		int sampleRate
    		) 
    {
    	this.jVARunning = false;
    	this.outputFilePath = outputFilePath;
    	
    	this.webCamDeviceIndex = webCamDeviceIndex;
    	this.frameRate = frameRate;
    	this.gopLength = gopLength;
    	this.capWidth = capWidth;
    	this.capHeight = capHeight;
    	this.constantRateFactorVideo = constantRateFactorVideo;
    	this.videoBitRate = videoBitRate;

    	this.audioDeviceIndex = audioDeviceIndex;
    	this.audioChannels = audioChannels;
    	this.constantRateFactorAudio = constantRateFactorAudio;
    	this.audioQuality = audioQuality;
    	this.audioBitRate = audioBitRate;
    	
    	this.interleaved = interleaved;
    	this.encodingSpeed = encodingSpeed;
    	
    	this.sampleRate = sampleRate;
    	
    	this.startTime = 0;
    	this.videoTimeStamp = 0;
    	
    	frameGrabberOCV = new OpenCVFrameGrabber(webCamDeviceIndex);
    	frameGrabberOCV.setImageWidth(capWidth);
        frameGrabberOCV.setImageHeight(capHeight);
		
		frameRecorderFFmpeg = new FFmpegFrameRecorder(
				this.outputFilePath,
				capWidth, 
				capHeight, 
				this.audioChannels
				);
        frameRecorderFFmpeg.setInterleaved(interleaved);
        frameRecorderFFmpeg.setVideoOption("TUNE".toLowerCase(), "ZEROLATENCY".toLowerCase());
        frameRecorderFFmpeg.setVideoOption("PRESET".toLowerCase(), this.encodingSpeed.toLowerCase());
        frameRecorderFFmpeg.setVideoOption("CRF".toLowerCase(), this.constantRateFactorVideo.toLowerCase());
        frameRecorderFFmpeg.setVideoBitrate(this.videoBitRate);
        frameRecorderFFmpeg.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
        frameRecorderFFmpeg.setFormat(this.videoFormat);
        frameRecorderFFmpeg.setFrameRate(this.frameRate);
        frameRecorderFFmpeg.setGopSize(this.gopLength);
        frameRecorderFFmpeg.setAudioOption("CRF".toLowerCase(), this.constantRateFactorAudio.toLowerCase());
        frameRecorderFFmpeg.setAudioQuality(this.audioQuality);
        frameRecorderFFmpeg.setAudioBitrate(this.audioBitRate);
        frameRecorderFFmpeg.setSampleRate(this.sampleRate);
        frameRecorderFFmpeg.setAudioChannels(this.audioChannels);
        frameRecorderFFmpeg.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
    }
    
	public void start() {
    	recordThread.start();
    }
    
    public void stop() {
    	try {
    		canvasFrame.dispose();
    		frameRecorderFFmpeg.stop();
			frameGrabberOCV.stop();
			targetDataLine.close();
			exeThreadPool.shutdown();
			
			while (!exeThreadPool.isShutdown() && !recordThread.isAlive()) {
				Thread.sleep(10);
			}
			
			
    		
			jVARunning = false;
		} catch (InterruptedException e) {
			e.printStackTrace();
		} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
    
    
    
    
    
    
    // Getters and Setters
    public Frame getCapturedFrame() {
    	return capturedFrame;
	}
	public boolean isjVARunning() {
		return jVARunning;
	}
}

**Comment by saudet** [comment]
You'll need to use the `AV_CODEC_ID_H264` codec if you want to be able to do that:
https://docs.oracle.com/javase/8/javafx/media-tutorial/overview.htm
