### ISSUE TITLE
Video recorded with FFmpegFrameRecorder and FFmpegFrameFilter is blank

### ISSUE THREAD

**Issue by kdheerajc004** [bytedeco/javacv#608]
Hi

I am trying to use `FFmpeg` to apply some filters using `FFmpegFrameFilter` in video file But resultant video includes only sound and no video frame which results in blank video with sound only.

Please see my code below:-

                FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(videoFilePath);
                frameGrabber.start();

                int imageWidth = frameGrabber.getImageWidth();
                int imageHeight = frameGrabber.getImageHeight();
                int audioChannels = frameGrabber.getAudioChannels();

                FFmpegFrameRecorder recorder =
                        new FFmpegFrameRecorder(outputFileURL, imageWidth, imageHeight, audioChannels);

                recorder.setFrameRate(frameGrabber.getFrameRate());

                recorder.setVideoCodec(frameGrabber.getVideoCodec());
                recorder.setFormat(frameGrabber.getFormat());
                recorder.setVideoBitrate(frameGrabber.getVideoBitrate());
                recorder.setVideoQuality(0.8);

                recorder.setAudioCodec(frameGrabber.getAudioCodec());

                recorder.start();

                FFmpegFrameFilter filter =
                        new FFmpegFrameFilter("transpose=cclock_flip", imageWidth, imageHeight);
                filter.start();
                
                Frame frame;
                while (null != (frame = frameGrabber.grab())) {

                    if (null != frame.image) {
                        filter.push(frame,frameGrabber.getPixelFormat());

                        Frame filteredFrame;
                        while (null != (filteredFrame = filter.pull())) {
                            recorder.record(filteredFrame);
                        }
                    } else {
                        recorder.record(frame);
                    }

                }

                frameGrabber.flush();
                frameGrabber.release();

                filter.stop();
                filter.release();

                recorder.stop();
                recorder.release();`

**Comment by saudet** [comment]
Your code works fine here with JavaCV 1.3.1. Please try a different video codec.
