### ISSUE TITLE
[Android]Can record and input textview or animation of imageview to video?

### ISSUE THREAD

**Issue by kazixma** [bytedeco/javacv#611]
I want to make application like SNOW  or MSQRD app that it can write textview to video between record or input animation of imageview to video

like this https://www.youtube.com/watch?v=B7oIMjPd7J8

Thx sir

**Comment by saudet** [comment]
There is an example of that in the README.md file. Do something like the
Demo class.

**Comment by kazixma** [comment]
thank, in android can do it same demo class ?

**Comment by saudet** [comment]
Sure, just copy/paste the code in this project, for example:
https://github.com/bytedeco/sample-projects/tree/master/JavaCV-android-example

**Comment by kazixma** [comment]
Ok , Thank But now my problem can not find  CvHaarClassifierCascade class. How to fix it ?

**Comment by saudet** [comment]
It's right here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_objdetect.CvHaarClassifierCascade.html
