### ISSUE TITLE
 Recorded Video pixelating 

### ISSUE THREAD

**Issue by vishalghor** [bytedeco/javacv#612]
I'm using RecordActivity sample for recording video but the video which i get is pixelated and the clarity is lost.Is it something to do with the encoding bit rate?how can encoding bit rate be set for a 640*480 video being recorded.?also higher video resoltuions   such as  1280*720 and 1920*1080 the frame are getting skipped in between,so how to handle higher resolutions?

Thank You..

**Comment by saudet** [comment]
Yes, increase the video bitrate with `setVideoBitrate()` or set the video quality with `setVideoQuality()`.

To increase the resolution and still record in real time, you'll need to use hardware acceleration, which FFmpeg doesn't support, so you'll need to use Android's API, for example:
https://github.com/google/grafika/blob/master/src/com/android/grafika/ContinuousCaptureActivity.java
