### ISSUE TITLE
Problem with basic javacpp in Android. Class not found "opencv_core" 

### ISSUE THREAD

**Issue by kleiren** [bytedeco/javacv#614]
I am trying to load an image in android through "cvLoadImage()", but i'm getting:
`java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.opencv_core
`
I have tried both importing the libraries (javacv, javacpp and javacv-platform) with gradle and using directly the .jar. Also i've tried including all .so form opencv-android-arm.jar in "jniLinb/armeabi/"

Is there something I am missing? I am out of ideas...

Thanks in advance.

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
