### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by madie89** [bytedeco/javacv#616]
Hi I have seen all the issues similar to this and have tried updating all the dependencies to latest but still getting the same error.
`<dependency><groupId>org.bytedeco</groupId><artifactId>javacv-platform</artifactId><version>LATEST</version></dependency>`

I havealso added the below dependencies:
    org.bytedeco.javacpp-presets:ffmpeg:3.2.1-1.3
and
   org.bytedeco.javacpp-presets:opencv-platform:3.1.0-1.3
    
Below is my code:

         public static void main(String[] args) throws Exception {
         CanvasFrame frame = new CanvasFrame("ScreenCastingTest", 1.0);
         int x = 0, y = 0, w = 1024, h = 768; // specify the region of screen to grab
         FFmpegFrameGrabber grabber = //new FFmpegFrameGrabber(":0.0+" + x + "," + y);
        		 new FFmpegFrameGrabber("video=\"screen-capture-recorder\"");
         grabber	    .setFormat("dshow");
        // grabber.setFormat("x11grab");
         grabber.setImageWidth(1024);
         grabber.setImageHeight(768);
         grabber.setFrameRate(10);
         grabber.start();

         while (frame.isVisible()) {
             frame.showImage(grabber.grab());
         }
         grabber.stop();
         grabber.close();
         frame.dispose();
     }

But I am getting below error:
         Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:585)
	at org.bytedeco.javacpp.Loader.load(Loader.java:530)
	at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:468)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:462)
	at opencv.OpenCvTest.main(OpenCvTest.java:18)

**Comment by saudet** [comment]
Add the dependency for FFmpeg as well:
https://github.com/bytedeco/javacpp-presets/tree/master/ffmpeg#the-pomxml-build-file

**Comment by madie89** [comment]
Hi Saudet I have added the dependecy: still getting same error
             <dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>LATEST</version>
  </dependency>
  <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>ffmpeg-platform</artifactId>
            <version>3.2.1-1.3</version>
        </dependency>

**Comment by madie89** [comment]
@saudet 
Hi Saudet I have added the dependecy: still getting same error

org.bytedeco
javacv-platform
LATEST


org.bytedeco.javacpp-presets
ffmpeg-platform
3.2.1-1.3

**Comment by madie89** [comment]
@saudet 
As per the latest javacv dependency all the related dependencies gets downloaded as well. so when you asked to  ffmpeg-platform  I could see that the platform dependencies for ffmpeg were already in the classpath. Is there a possibility that a conflict between dependencies could cause this.

**Comment by saudet** [comment]
There can be conflicts, sure, so list only "javacv-platform" as dependency, that works for sure.

**Comment by saudet** [comment]
If you're on Windows, please follow these instructions and let me know what the output is:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows#using-dependency-walker

**Comment by madie89** [comment]
HI @saudet  

Based on the exception

                Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
                at java.lang.Class.forName0(Native Method)
                at java.lang.Class.forName(Class.java:348)
                at org.bytedeco.javacpp.Loader.load(Loader.java:585)

I  tried this:

                     try {
			    Loader.load(avutil.class);
			    } catch (UnsatisfiedLinkError e) {
			         String path = Loader.cacheResource(avutil.class, "windows-  x86_64/jniavutil.dll").getPath();
			         new ProcessBuilder("C:/dependency_walker_x64/depends.exe", path).start().waitFor();
			}

and now the exception is null pointer

                    Exception in thread "main" java.lang.NullPointerException
	            at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:331)
	            at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:315)
	            at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:311)
	            at opencv.OpenCvTest.main(OpenCvTest.java:12)

**Comment by saudet** [comment]
So, yes, the DLL isn't found on your class path. You'll need to figure out how to include the correct JAR file in your class path for the build system you are using. For typical build systems, the "javacv-platform" will include everything, but it looks like you have something strange.

**Comment by madie89** [comment]
@saudet 
I further checked all the dependencies I have the dependency jar 
\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3-windows-x86_64.jar which has the jniavutil.dll file. It is also present in maven classpath as it is part of javacv-playform.

I am not understanding why is it throwing null pointer then.

**Comment by madie89** [comment]
@saudet 
Thanks Saudet finally found the solution. I read the ffmpeg documentation as per the new release the working configuration would be this.
              FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("desktop");
         grabber.setFormat("gdigrab");

**Comment by saudet** [comment]
@madie89 Great! Please consider making a contribution: issue #31

**Comment by sumit33** [comment]
@mhmahmoodalam I am getting the same error..Also tried your solution..but still the problem occurs.
