### ISSUE TITLE
FFmpegFrameGrabber does not support rtmp?

### ISSUE THREAD

**Issue by pengliren** [bytedeco/javacv#62]
avformat_open_input() error -1313558101: Could not open input "rtmp://localhost:1935/live/12345". (Has setFormat() been called?)
    at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:390)

**Comment by MuthuEphron** [comment]
What  type of error in relationship with server? please give suggestion about it.

**Comment by saudet** [comment]
@MuthuEphron It's available here: https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java
