### ISSUE TITLE
Grab each frame from video and save as jpg in internal sd

### ISSUE THREAD

**Issue by rajkumarmishra** [bytedeco/javacv#620]
How can i grab each frame from a video, preferably on frame preview, as save each frame as jpg file.
with following code i am able to get one frame in log file, don't know to convert each into image file.

` FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(cVideoFilePath+ "/" + "VID_20170209_133918.mp4");
        try {

            OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
            AndroidFrameConverter convertToBitmap = new AndroidFrameConverter();
            grabber.start();
            Frame frame1 = grabber.grab();
            Bitmap bitmap = convertToBitmap.convert(frame1)
            FileOutputStream outputStream = null;
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyymmddhhss");
            String date = simpleDateFormat.format(new Date());
            File picfile = new File(cVideoFilePath);
            if (!picfile.exists()) {
                try {
                    picfile.createNewFile();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
            try {
                outputStream = new FileOutputStream(picfile);
                outputStream.write(bitmap);
                outputStream.close();
                Log.i("Byte", frame1.toString());
            } catch (IOException ex) {

            }

**Comment by saudet** [comment]
You'll need to call FrameGrabber.grab() in a loop.

**Comment by rajkumarmishra** [comment]
@saudet Thanks, modified my code, now i can save frame to jpeg. Still getting same frame every time.
Sorry for being so naive. wanted to extract atleast 20-30 frames per second.

`
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(cVideoFilePath+ "/" + "VID_20170211_132657.mp4");
        try {

            OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
            AndroidFrameConverter convertToBitmap = new AndroidFrameConverter();
            grabber.start();

            while (true ) {
                Frame frame1 = grabber.grabImage();
                bitmap = convertToBitmap.convert(frame1);

                SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyymmddhhss");
                String date = simpleDateFormat.format(new Date());
                photofile = "cam_demo" + date + ".jpg";
                String file_name = cVideoFilePath + "/" + photofile;
                File picfile = new File(file_name);
                if (!picfile.exists()) {
                    try {
                        picfile.createNewFile();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
                try {

                    FileOutputStream out = new FileOutputStream(picfile);
                    bitmap.compress(Bitmap.CompressFormat.JPEG, 100, out);
                    out.flush();
                    out.close();

                } catch (IOException ex) {

                } finally {


                }
            }
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }

    }
`

**Comment by rajkumarmishra** [comment]
Still getting the same frame:
`` FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(cVideoFilePath+ "/"  "VID_20170211_132657.mp4");


        try {

            OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
            AndroidFrameConverter convertToBitmap = new AndroidFrameConverter();
            grabber.start();
            for (int i= 0; i< grabber.getLengthInFrames();i++){

                 frame1 = grabber.grabImage();
                Bitmap bitmap = convertToBitmap.convert(frame1);}`

**Comment by saudet** [comment]
And you'll need to save the frames under different filenames. This isn't an issue with JavaCV. You'll need to learn how to code, first.

**Comment by rajkumarmishra** [comment]
Sorry Samuel, I think this is not the right place to ask this question. Thanks
