### ISSUE TITLE
Code runs fine on OS X but crashes on Ubuntu 14.04

### ISSUE THREAD

**Issue by alexhutnik** [bytedeco/javacv#621]
I've written some code to detect motion between frames.  It runs just fine on my MacBook Pro but on my server (Ubuntu 14.04) it is 3x-4x slower.  Certainly the hardware is not 100% identical but I wouldn't expect such a drastic change.  I'm only running single-threaded.  Also on the linux server it will crash after just 15-20 seconds with:

Exception in thread "main" java.lang.OutOfMemoryError: Physical memory usage is too high: physicalBytes = 501M > maxPhysicalBytes = 495M
        at org.bytedeco.javacpp.Pointer.deallocator(Pointer.java:562)
        at org.bytedeco.javacpp.Pointer.init(Pointer.java:121)
        at org.bytedeco.javacpp.opencv_core$MatVector.allocate(Native Method)
        at org.bytedeco.javacpp.opencv_core$MatVector.<init>(opencv_core.java:453)
        at FrameGrabberExperimentMotion.diffImageByContours(FrameGrabberExperimentMotion.java:84)
        at FrameGrabberExperimentMotion.main(FrameGrabberExperimentMotion.java:45)

I've enabled debugging and I can see that the linux x86_64 libs are loaded on the linux server.  I can see pointers being allocated and deallocated.

The code is here: https://gist.github.com/alexhutnik/d0e9f55bd4b1ac60ecde907f06ebef0d

Edit: Forgot to mention both Mac and Linux are running JDK 1.8.0.121

**Comment by saudet** [comment]
Increase this value: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html#maxPhysicalBytes

**Comment by alexhutnik** [comment]
Ok changing the value to something quite high (8gb) has fixed the issue but I believe there is a leak off-heap.  top is reporting ever increasing memory usage for the running process.  I set the maxPhysicalBytes value using the system property and set the heap size to 256m.  When top claimed I was using 2gb of memory I obtained a heap dump and the head dump file was only 5mb.

Further, while the memory issue is somewhat resolved how might I troubleshoot the radical difference in performance between OS X and Linux?

**Comment by saudet** [comment]
Are you saying the memory usage doesn't increase on Mac OS X?

**Comment by saudet** [comment]
You could set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more info printed on the console: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/Logger.html

**Comment by alexhutnik** [comment]
It does increase but then decreases periodically as one would expect when GC runs.

Also after debug logging I noticed this on my linux server:
Failed to load /home/user/.javacpp/cache/ffmpeg-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libavdevice.so.57: java.lang.UnsatisfiedLinkError: /home/user/.javacpp/cache/ffmpeg-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libavdevice.so.57: libasound.so.2: cannot open shared object file: No such file or directory

I do not get the same error logged on OS X.

**Comment by alexhutnik** [comment]
I think that leads to this error: Failed to load for jniavdevice: java.lang.UnsatisfiedLinkError: no jniavdevice in java.library.path

**Comment by alexhutnik** [comment]
Should I open a new issue on javacpp-presets for ffmpeg?

**Comment by saudet** [comment]
I said
> You could set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more info printed on the console: http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/tools/Logger.html

Please do that and make sure everything is getting deallocated.

**Comment by saudet** [comment]
Probably related to https://github.com/bytedeco/javacv/issues/607

**Comment by alexhutnik** [comment]
I've narrowed down the issue in my code to the following snippet:

```
frameGrabber.start();
i=0;
while (i<1000) {
    frameGrabber.setFrameNumber(i);
    Mat frame = matConverter.convert(frameGrabber.grabImage());
    cvtColor(frame, frame, CV_RGB2GRAY);
    blur(frame, frame, BLUR_KERNEL);
    i+=30;
}
frameGrabber.stop();
```

If I comment out the call `cvtColor`, my problem goes away.

**Comment by saudet** [comment]
I see, cvtColor() doesn't support in-place conversion for that mode, that's normal.

**Comment by alexhutnik** [comment]
Ok I created an empty Mat to pass in and I still have the problem:

```
Mat cvtMat = new Mat();
cvtColor(frame, cvtMat, CV_RGB2GRAY);
blur(cvtMat, cvtMat, BLUR_KERNEL);
```

Am I missing something?

**Comment by saudet** [comment]
Well, it's not a good idea to create so many temporary Mat objects, but it's probably just not having enough time to do garbage collection. Increase this value: 
http://bytedeco.org/javacpp/apidocs/org/bytedeco/javacpp/Pointer.html#maxRetries
