### ISSUE TITLE
Is there any tools to debug image?

### ISSUE THREAD

**Issue by xray1111** [bytedeco/javacv#622]
Hi guys!

I really want to involve JAVACV into my recent project which dealing with some kind of image recgnizing, but I found that it's difficult to debug in IDE such as intelij idea when I want to figure out the the image's matrix value. On the contrarory, when we using python or matlab, we always feel the debugging is easy and natural. Is there any tools I can use for idea/scala? Thanks!

**Comment by saudet** [comment]
Just add a watch for Mat.createIndexer().toString() and you'll get what you
want!

**Comment by xray1111** [comment]
Thanks a lot, that's really help! @saudet
