### ISSUE TITLE
Unable to runTemplateMatching

### ISSUE THREAD

**Issue by repte** [bytedeco/javacv#623]
I copied your code from here
https://github.com/bytedeco/javacv/blob/master/samples/TemplateMatching.java
but I am too stupid to make it work. I managed to add all libaries but where should I put my String to the image paths?

**Comment by saudet** [comment]
Specify them on the command line:
>  We need 2 default parameters like this (source image, image to find )
 "C:\Users\Waldema\Desktop\bg.jpg" "C:\Users\Waldema\Desktop\imageToFind.jpg"
