### ISSUE TITLE
Unable to seek audio mp3 file using setTimestamp() method.

### ISSUE THREAD

**Issue by john-us** [bytedeco/javacv#626]
Hi Samuel,

javacv-1.3.1 is working well when i record audio frames from start but when i seek it using setTimestamp() method, it fails to record audio. Please look  into this.

Thanks

**Comment by saudet** [comment]
I don't believe FFmpeg supports that for audio frames, but I may be
mistaken. If you have reference code for this, please let me know.

**Comment by john-us** [comment]
But in previous javacv version-0.7 you provided a workaround class for seeking audio files.

**Comment by john-us** [comment]
if (soundGrabber != null) {
                            try {
				soundGrabber.setTimestamp(musicPosition * 1000);//time in micro seconds
				audioTime = audioTime + soundGrabber.getTimestamp();
				Frame f = null;
				long duration = soundGrabber.getLengthInTime();

				while ((soundGrabber.getTimestamp() <= audioTime)
						&& (duration > soundGrabber.getTimestamp())) {
					try {
						if ((f = soundGrabber.grabFrame()).image == null) {
							recorder.record(f);
						}
					} catch (org.bytedeco.javacv.FrameRecorder.Exception e) {
						e.printStackTrace();
						break;
					} catch (org.bytedeco.javacv.FrameGrabber.Exception e) {
						e.printStackTrace();
						break;
					} catch (java.lang.Exception e) {
					}
				}
			} catch (java.lang.Exception e) {
			}
			}

**Comment by saudet** [comment]
Could you provide a small but complete and self-contained example?

**Comment by saudet** [comment]
It works fine here. I have an MP3 that is 4:48 minutes long, and using the following code, I get an AAC file that is 4:38 minutes long:
```java
        FrameGrabber grabber = new FFmpegFrameGrabber("file.mp3");
        grabber.start();

        FrameRecorder recorder = new FFmpegFrameRecorder("audio.aac", grabber.getAudioChannels());
        recorder.start();

        grabber.setTimestamp(10000000);
        Frame frame;
        while ((frame = grabber.grab()) != null) {
            recorder.record(frame);
        }
        grabber.stop();
        recorder.stop();
```
