### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by pritesh-patel-hs** [bytedeco/javacv#627]
I ran into a problem using SBT with javacv-platform-1.3.1.

The problem:
The application would run fine when running from my local however when publishing and dockerizing using sbt-native-packager, inside the container I would receive:

```
"java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil"
```

Solution:

To solve it i added this to my main method 
```
    System.setProperty("org.bytedeco.javacpp.cachedir", ".");
```

I turns out there was permission errors writing to the original place its meant to write too which was: "~/.javacpp/cache/"

I then amended my docker instructions to create this file and give it the necessary permissions.

This is not a problem that would need to be solved by code, but it would be useful in documentation as a tip as it was quite frustrating to debug!

**Comment by saudet** [comment]
That's been fixed in JavaCPP 1.3.1, so make sure to add that dependency as well.
