### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/asec/com.mallcong.emot.emotiontracker-2/base.apk"],nativeLibraryDirectories=[/mnt/asec/com.mallcong.emot.emotiontracker-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjniopencv_core.so"

### ISSUE THREAD

**Issue by pahdo** [bytedeco/javacv#629]
Hi,

I have an Android app using JavaCV that runs fine on my emulator but crashes when I run it on an Android phone.

I'm running the emulator on a MacBook Pro and the phone is an HTC Desire 816, which runs on a Qualcomm Snapdragon 400 processor.

Here's the error message:
`02-26 17:56:54.922 8454-8454/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.mallcong.emot.emotiontracker, PID: 8454
                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/asec/com.mallcong.emot.emotiontracker-2/base.apk"],nativeLibraryDirectories=[/mnt/asec/com.mallcong.emot.emotiontracker-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjniopencv_core.so"`

If there is any possibly relevant information that might be helpful, I'll try to provide it. What could be the cause of my crash?

Thanks!

**Comment by saudet** [comment]
The error message couldn't be more explicit: couldn't find
"libjniopencv_core.so"

So, that file is missing, add it to your application.
