### ISSUE TITLE
How to stick a transparent  png  into frame?

### ISSUE THREAD

**Issue by rainplus** [bytedeco/javacv#630]
I Use below:

 Mat logo = opencv_imgcodecs.imread("e://2.png",-1);
        double alpha = 0.5;// 图像透明权重值,0-1之间 ,1是完全不透明
        while (start&& (frame = grabber.grabFrame()) != null) {
            Mat mat = converter.convertToMat(frame);
            if(mat!=null){
                Mat ROI = mat.apply(new Rect(0, 0, logo.cols(), logo.rows())); 
                opencv_core.addWeighted(ROI, alpha, logo, 1.0 - alpha, 0.0, ROI);      
                frame = converter.convert(mat);
            }
            if(frame!=null){  
            	recorder.record(frame);  
            }  
            Thread.sleep(40);
        }

it crash,and show this:
OpenCV Error: Sizes of input arguments do not match (The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array') in cv::arithm_op, file C:\projects\bytedeco\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-3.1.0\modules\core\src\arithm.cpp, line 639

i use javacv1.3.1 versioin.

**Comment by saudet** [comment]
OpenCV doesn't support alpha channels, try some other tool...

**Comment by rainplus** [comment]
@saudet thanks you.

**Comment by rainplus** [comment]
I'm use a ffmpeg-cli-wrapper can do it, and  I read the javacv package ,they say that: javacv ont only invoke the openvc ,it also has the ffmpeg,do you wrap it?and it has any way to do that for a sample?

**Comment by saudet** [comment]
Yes, it's possible to do it with FFmpegFrameFilter. There is some sample code in here:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by IzabellaConigliaro** [comment]
The filter movie breaks my video...

**Comment by saudet** [comment]
@IzabellaConigliaro It's not currently possible to "mix" 2 movies together, see issue #389

**Comment by saudet** [comment]
FYI, this has been fixed, and we can now use the `movie` filter for that. It should work as expected with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/
