### ISSUE TITLE
write frame issue

### ISSUE THREAD

**Issue by surabhi1694** [bytedeco/javacv#631]
when i start to record video it shows me this
what should i do?

com.googlecode.javacv.FrameRecorder$Exception: av_interleaved_write_frame() error -32 while writing interleaved audio frame.
03-01 14:05:16.182 7716-8735/com.example.javacv.stream.test2 W/System.err:     at com.googlecode.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:747)
03-01 14:05:16.182 7716-8735/com.example.javacv.stream.test2 W/System.err:     at com.example.javacv.stream.test2.MainActivity$AudioRecordRunnable.run(MainActivity.java:255)
03-01 14:05:16.182 7716-8735/com.example.javacv.stream.test2 W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by saudet** [comment]
Please upgrade to a more recent version of JavaCV.
