### ISSUE TITLE
How to only import android platform?

### ISSUE THREAD

**Issue by kongqw** [bytedeco/javacv#633]
I use it
``` cradle
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'org.bytedeco:javacv-platform:1.3.1'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:3.2.1-1.3'
    compile 'org.bytedeco.javacpp-presets:opencv:3.1.0-1.3'
}
```

but it's import all platform.

like is
![11](https://cloud.githubusercontent.com/assets/9513240/23539519/dacd6ebc-0016-11e7-9fc8-8701e64de40d.png)

How to only import android platform? please:)

**Comment by saudet** [comment]
You can either exclude them, or include only the artifacts you need, the ones not suffixed with "-platform".

**Comment by kongqw** [comment]
Excuse me，can you write a sample？thx

**Comment by kongqw** [comment]
Excuse me，can you write a sample？thx @saudet

**Comment by saudet** [comment]
There's this:
https://github.com/bytedeco/sample-projects/blob/master/JavaCV-android-example/app/build.gradle
https://github.com/bytedeco/javacv/wiki/Configuring-Proguard-for-JavaCV#gradle-settings
But feel free to make a contribution! We need more documentation

**Comment by cjsky666** [comment]
I get the problem too，how to  exclusion other platform support   on maven pom.xml  . because it‘s  so fat when I compile my project

**Comment by akwolf** [comment]
@cjsky666 you can use maven-war-plugin and exclude other platform ,like this
>     <configuration>
        <packagingExcludes>
            WEB-INF/lib/*android-arm.jar,
            WEB-INF/lib/*android-arm64.jar,
            WEB-INF/lib/*android-x86.jar,
            WEB-INF/lib/*android-x86_64.jar,
            WEB-INF/lib/*ios-arm.jar,
            WEB-INF/lib/*ios-arm64.jar,
            WEB-INF/lib/*ios-x86_64.jar,
            WEB-INF/lib/*windows-x86.jar,
            WEB-INF/lib/*windows-x86_64.jar,
            WEB-INF/lib/*macosx-x86_64.jar,
            WEB-INF/lib/*linux-x86.jar
        </packagingExcludes>
    </configuration>
