### ISSUE TITLE
RecordActivity is not recording anything.

### ISSUE THREAD

**Issue by ghost** [bytedeco/javacv#635]

**Comment by saudet** [comment]
Try this instead:
https://github.com/bytedeco/sample-projects/tree/master/JavaCV-android-example

**Comment by mcxycross** [comment]
Hi, the video output from RecordActivity is only the last few seconds before stopRecording() happen eventhough it already ran for a few minutes. I've tried using the sample project you've provided, it still the same.

Is it the way it is or is it just my device? I ran it on Xperia M5 with Android M.

**Comment by mcxycross** [comment]
Hi, the video output from RecordActivity is only the last few seconds before stopRecording() happen, even though it already ran for a few minutes. I've tried using the sample project you've provided, it still the same.

Is it the way it is or is it just my device? I ran it on Xperia M5 with Android M.
I know the topic closed, but I hope I can get answer. I really appreciate it.

**Comment by saudet** [comment]
That's what it's supposed to do. Change this line if you wish to record all the video:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java#L147

**Comment by mcxycross** [comment]
Wow, it did. Thanks.
But can you explain what is RECORD_LENGTH for? I didn't really understand.
