### ISSUE TITLE
java.lang.UnsatisfiedLinkError when calling SVM.loadSVM()

### ISSUE THREAD

**Issue by yanhuixie** [bytedeco/javacv#638]
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.helper.opencv_ml$AbstractStatModel.loadSVM(Ljava/lang/String;Ljava/lang/String;)Lorg/bytedeco/javacpp/opencv_ml$SVM;
	at org.bytedeco.javacpp.helper.opencv_ml$AbstractStatModel.loadSVM(Native Method)

Just simply calling SVM.loadSVM("/path/to/trained/svm.xml", "svm");
Everything (SVM train etc.) works normally but SVM.loadSVM().
Any suggestion is appreciated, thanks!

```xml
<dependency>
    <groupId>org.bytedeco</groupId>
    <artifactId>javacv-platform</artifactId>
    <version>1.3.1</version>
</dependency>
```

**Comment by yanhuixie** [comment]
OK, it seems the problem is solved. You have to to call FileStorage.open() before SVM.loadSVM(). Is it true?
```java
final String path = "/path/to/trained/svm.xml";
FileStorage fs = new FileStorage();
fs.open(path, CV_STORAGE_READ);
SVM.loadSVM(path, "svm");
```

**Comment by saudet** [comment]
There are a few `Loader.load()` calls missing from the helper classes. Thanks for pointing this out! To work around the issue for now, we can actually just call this before `SVM.loadSVM()`:
```java
Loader.load(org.bytedeco.javacpp.opencv_ml.class);
```

**Comment by yanhuixie** [comment]
Wow~ Thanks for your precise reply, @saudet ! It works.

**Comment by saudet** [comment]
The fix is part of these binaries available on Maven:
http://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/opencv/3.2.0-1.3/
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#the-pomxml-build-file
Enjoy!
