### ISSUE TITLE
error: no suitable method found for predict(Mat)

### ISSUE THREAD

**Issue by hokage4** [bytedeco/javacv#642]
Hi,
i make project  face recogntion and build it by gradle but when  i build i have this error

home/project/hipi/examples/jcvhd/src/main/java/org/hipi/examples/HelloWorld.java:132: error: no suitable method found for predict(Mat)
        int predictedLabel = faceRecognizer.predict(testImage);
                                           ^
    method FaceRecognizer.predict(Mat,IntPointer,DoublePointer) is not applicable
      (actual and formal argument lists differ in length)
    method FaceRecognizer.predict(Mat,IntBuffer,DoubleBuffer) is not applicable
      (actual and formal argument lists differ in length)
    method FaceRecognizer.predict(UMat,int[],double[]) is not applicable
      (actual and formal argument lists differ in length)
    method FaceRecognizer.predict(UMat,IntPointer,DoublePointer) is not applicable
      (actual and formal argument lists differ in length)
1 error
:examples:jcvhd:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:jcvhd:compileJava'.
> Compilation failed; see the compiler error output for details.

can any one help me please.

**Comment by saudet** [comment]
It looks like that method was renamed to "predict_label" for some reason:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/javacpp/opencv_face.java#L435

**Comment by hokage4** [comment]
thank you i used  predict_label and work successfully but i want Get the prediction with confidence.
predict_label not return  confidence

**Comment by hokage4** [comment]
i want use this method to get confidence FaceRecognizer.predict(Mat,IntPointer,DoublePointer) if can.

**or advise me if you have another way to get confidence**

**Comment by saudet** [comment]
Yes, we can use that method. What is the issue?

**Comment by hokage4** [comment]
I used it in this way

```
Mat testImage = imread("//home//project//NetBeansProjects//newjavacv//aa.jpg"  , CV_LOAD_IMAGE_GRAYSCALE);
int po = 0;
double con = 0.0;
faceRecognizer.predict(testImage, po, con);
```
 and when build it by gradle i have  the same error above

**Comment by hokage4** [comment]
and the  build.gradle is  
```
jar {
  manifest {
    attributes("Main-Class": "org.hipi.examples.HelloWorld")
  }
dependencies{
compile project(':core')
compile group: 'org.bytedeco', name: 'javacv', version: '1.2'
compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.2'

}
from {
    configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
}
configurations {
    all*.exclude group: 'org.bytedeco', module: 'javacpp-presets'
    
}
}
```

**Comment by saudet** [comment]
As per the commit above, I've fixed the call in the samples. Just do it the same way.

Thanks for reporting!
