### ISSUE TITLE
Cannot send multicast packet via android wifi-direct

### ISSUE THREAD

**Issue by Huskera** [bytedeco/javacv#643]
Yes, it is strange ways... but I have to do, below are some codes:
        recorder = new LiveFFmpegFrameRecorder("rtp://224.1.2.3:2000", imageWidth, imageHeight, 0);
        recorder.setFormat("rtp");
It is working well with normal wifi, but got an error code -101 when run av_write_frame function with wifi-direct. If use unicast instead of multicast with wifi-direct, it works fine. 
After research the source codes of ffmpeg, looks like that it doesn't specify a interface when send multicast packet(upd.c line 866)
So, if I want to change the source codes of ffmpeg and compile them to so file, I just need to replace the so files ffmpeg-android-XXX.jar, right?

**Comment by saudet** [comment]
Yes, that's correct.

Please send the patch upstream so we can get that fixed in FFmpeg!

**Comment by Huskera** [comment]
OK, I will send after find solution.

**Comment by saudet** [comment]
Any updates on this? Is it fixed in FFmpeg 3.4.1?

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming this has been fixed, but if not and you'd like you could also submit the patch to be included in the presets: https://github.com/bytedeco/javacpp-presets/pulls This way, you'll get good binaries automatically for all snapshots and releases.
