### ISSUE TITLE
Unable to capture frames from  FFmpegFrameGrabber from javacv

### ISSUE THREAD

**Issue by dhakre** [bytedeco/javacv#644]
public class Getframes {
	public static void main(String[] args) {

	     @SuppressWarnings("resource")
		FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("C:/Users/user/Documents/Java gesture recognistion/MediaPlayer/Learn.avi");

	     try {
	    	 IplImage grabbedImage;
	    	 Frame frame;
	    	 OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();

	         //Start grabber to capture video
	         grabber.start(); 

	         //grab video frame to IplImage
	        
	         frame = grabber.grab();
	        //convert frame to image type
	         grabbedImage = converter.convert(frame);

	         if (grabbedImage != null) {         
	             //save video frame as a picture
	             cvSaveImage("/C:/Users/user/Documents/Java gesture recognistion/Frames_JavaCV/capture.jpg", grabbedImage);
	         }

	     }catch (Exception e) {      
	     }
	}

}

When I run this code i red this following error : 
Input #0, avi, from 'C:/Users/user/Documents/Java gesture recognistion/MediaPlayer/Learn.avi':
  Duration: 00:00:58.30, start: 0.000000, bitrate: 143 kb/s
    Stream #0:0: Video: mpeg4 (DX50 / 0x30355844), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 136 kb/s, 30 fps, 30 tbr, 30 tbn, 30k tbc
[mpeg4 @ 00000000001cc480] Video uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter without encoding but stream copy to fix it.

I am new to javacv can anyone please help me to resolve this error.

**Comment by saudet** [comment]
That's not an error, that's just a warning. You can ignore that if it's not causing you any problems.
