### ISSUE TITLE
Version 1.3.2, "No implementation found for opencv_core.CV_FP16_TYPE()". Works in 1.3.1

### ISSUE THREAD

**Issue by kleiren** [bytedeco/javacv#647]
Not sure if this belongs here, but I am getting:
```
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for int org.bytedeco.javacpp.opencv_core.CV_FP16_TYPE() (tried Java_org_bytedeco_javacpp_opencv_1core_CV_1FP16_1TYPE and Java_org_bytedeco_javacpp_opencv_1core_CV_1FP16_1TYPE__)
```

This happens using "cvLoadImage()" when using the latest version of javaCV in android (1.3.2). However this does not happen when using the previous 1.3.1 version. Is this deprecated or is it a bug?

My gradle file lookslike this:
```
compile group: 'org.bytedeco', name: 'javacv', version: '1.3.2'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.3'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3'
```
The problem dissapears when going back to 1.3.1.

**Comment by saudet** [comment]
Does this happen on other platforms? Or just Android?

**Comment by saudet** [comment]
JavaCV 1.3.2 depends on OpenCV 3.2.0. It won't work with OpenCV 3.1.0.

**Comment by kleiren** [comment]
I am getting the same error changing the gradle to:
```
compile group: 'org.bytedeco', name: 'javacv', version: '1.3.2'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.2.0-1.3'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3'
```
(Changed OCV version from **3.1.0** to **3.2.0**)
Is there anything more I have to do?

**Comment by saudet** [comment]
I don't see how you're including the .so files into your APK...

**Comment by kleiren** [comment]
Whoops sorry, forgot about that, the .so in the APK are from ocv 3.1

**Comment by waleeedahmed** [comment]
Where do we get the .so files for OpenCV 3.2.0 by the way? I tried searching but couldn't find them.

**Comment by waleeedahmed** [comment]
@saudet
