### ISSUE TITLE
Fail to obtain the list of points from a RotatedRect

### ISSUE THREAD

**Issue by rstancioiu** [bytedeco/javacv#649]
When I call the method points() inside the class RotatedRect we cannot get an array of Point2f (instead we can only get an instance of the class Point2f). 
Current behaviour:
`RotatedRect rect = minAreaRect(contours.get(i));` 
`rect.points(new Point2f())`
Desired behaviour:
`RotatedRect rect = minAreaRect(contours.get(i));` 
`Point2f[] points = new Point2f[4];`
`rect.points(points);`
Behaviour in C++
[http://www.swarthmore.edu/NatSci/mzucker1/opencv-2.4.10-docs/doc/tutorials/imgproc/shapedescriptors/bounding_rotated_ellipses/bounding_rotated_ellipses.html](url)
Is there any other way to get the array of Point2f from a RotatedRect ? 
Thank you in advance for your answer .

**Comment by saudet** [comment]
Point is a Pointer, which can access native arrays. Use the position() method.
