### ISSUE TITLE
WebcamAndMicrophoneCapture Error with RTMP-Url

### ISSUE THREAD

**Issue by MischaRo** [bytedeco/javacv#652]
I was trying to stream my webcam to ffserver using the WebcamAndMicrophoneCapture-example([https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java](url)).
Unfortunately, when I past my rtmp-url (rtmp://192.168.2.161:8090/feed1) to the FFmpegFrameRecorder I get a avio_open error() error -5:

`Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: avio_open error() error -5: Could not open 'rtmp://192.168.2.161:8090/feed1'
	at FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:701)
	at FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:295)
	at WebcamTest.main(WebcamTest.java:122)
`

Recording the webcam on file works normal.  Can someone help me?

**Comment by saudet** [comment]
Could you also provide the messages you get in the log?

**Comment by MischaRo** [comment]
Which log do you mean? Should i make a call to `FFmpegLogCallback.set()` or something?

**Comment by saudet** [comment]
If you don't see it on the console, yes, that should help.

**Comment by MischaRo** [comment]
Alright, i get a the folowing Log:

``
Output #0, flv, to 'rtmp://192.168.2.161:8090/feed1.ffm':
`` 
``
Output #0, flv, to 'rtmp://192.168.2.161:8090/feed1.ffm':
``
``
    Stream #0:0
    Stream #0:0
: Unknown: none (libx264)
: Unknown: none (libx264)
``


``
    Stream #0:1
    Stream #0:1
: Unknown: none (aac)
: Unknown: none (aac)
``
``
[libx264 @ 16cefca0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
``
``
[libx264 @ 16cefca0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
``
 ``
[libx264 @ 16cefca0] profile Constrained Baseline, level 3.0
`` 
``
[libx264 @ 16cefca0] profile Constrained Baseline, level 3.0
``
 ``
[libx264 @ 16cefca0] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=7 lookahead_threads=7 sliced_threads=1 slices=7 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=6 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
`` 
``
[libx264 @ 16cefca0] 264 - core 148 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=0 ref=1 deblock=0:0:0 analyse=0:0 me=dia subme=0 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=7 lookahead_threads=7 sliced_threads=1 slices=7 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=0 weightp=0 keyint=60 keyint_min=6 scenecut=0 intra_refresh=0 rc=crf mbtree=0 crf=28.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=0
`` 
``
Error: [rtmp @ 16cd7460] Cannot open connection tcp://192.168.2.161:8090
`` 

``
[aac @ 16cf0e60] Qavg: nan
`` ``
[aac @ 16cf0e60] Qavg: nan
``


Looks like it is a problem with the server, for not accepting the incomming stream.
Thank you very much, wouldn`t have found the problem without your log tip.
