### ISSUE TITLE
How to reduce size of apk file (android)

### ISSUE THREAD

**Issue by farzadnone** [bytedeco/javacv#653]
Hi Samuel Audet. thank you for useful project.
I use javacv in my android app.

I use [Manual Installation](https://github.com/bytedeco/javacpp-presets/#manual-installation) in my build.gradle project:

```
android {
        packagingOptions {
                exclude "lib/arm64-v8a/**"
                exclude 'META-INF/services/javax.annotation.processing.Processor'
                pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
                pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
                pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
                pickFirst 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
        }
}

dependencies {
        compile files('libs/ffmpeg-android-arm.jar')
        compile files('libs/ffmpeg-android-x86.jar')
        compile files('libs/ffmpeg.jar')
        compile files('libs/javacpp.jar')
        compile files('libs/javacv.jar')
        compile files('libs/opencv-android-arm.jar')
        compile files('libs/opencv-android-x86.jar')
        compile files('libs/opencv.jar')
}
```

and use [https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29](https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29) extract .so into jniLibs dir:

**jniLibs (178 MB) include :** 
        - armeabi
        - armeabi-v7a
        - x86

I need to use **javacv ffmpeg** only create video with one image. only this.

my import class in activity:
```
import org.bytedeco.javacpp.avcodec;
import org.bytedeco.javacpp.avutil;
import org.bytedeco.javacpp.opencv_core;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.OpenCVFrameConverter;
```

**So i do not need to other ffmpeg features.** (subtitle, filters, etc no need) 

now when i build APK (release) file is large size. ~80 MB. i read [issues 472](https://github.com/bytedeco/javacv/issues/472). (my project size without javacv ffmpeg is ~8MB).

what's the solution? (without using build split)
Is it possible customize ffmpeg javacv then only i need?
thanks

**Comment by saudet** [comment]
Yes, we can rebuild FFmpeg with the minimum amount of features we're
interested in.

**Comment by farzadnone** [comment]
@saudet how to rebuild customize?
- use proguard ?
- remove unnecessary *.so files ?
- remove *.so files from libs/*.jar ?
which one?

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/#build-instructions
