### ISSUE TITLE
Huge APK file size on Android

### ISSUE THREAD

**Issue by dwiprawira1989** [bytedeco/javacv#654]
I use gradle option to use javacv on my android apps.

`compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.2'`

After i generate APK file, my APK is 200MB. Is it normal? Or did i do something wrong?

**Comment by saudet** [comment]
Please read the README.md file:
> This downloads binaries for all platforms, but to get binaries for only one platform we can set the `javacpp.platform` system property (via the `-D` command line option) to something like `android-arm`, `linux-x86_64`, `macosx-x86_64`, `windows-x86_64`, etc. Please refer to the [README.md file of the JavaCPP Presets](https://github.com/bytedeco/javacpp-presets#downloads) for details. Another option available for Scala users is [sbt-javacv](https://github.com/bytedeco/sbt-javacv).

**Comment by SagiAny** [comment]
Hi,
I'm using :
`implementation group: 'org.bytedeco', name: 'javacv', version: '1.4.2'`

is there any way to reduce the size of it? - it's currently about 160MB

**Comment by SagiAny** [comment]
Thanks for the quick replay.
Is there any way to reduce the javacv size?
Curentellt I'm using:
`implementation group: 'org.bytedeco', name: 'javacv', version: '1.4.2'`

is there any way to split it into a smaller module?

**Comment by saudet** [comment]
Yes, add "exclude" statements, or use "javacv" instead of "javacv-platform", and only include what you need.

**Comment by saudet** [comment]
Thanks to @leaf918, @hnvn and @djalmaafilho, there is an example of the latter approach here, for example: https://github.com/bytedeco/sample-projects/blob/master/javacv-android-camera-preview/app/build.gradle#L42

**Comment by SagiAny** [comment]
Thanks. I've already used this approach, but still, the APK gained about 28MB.
Are there any other thoughts?

**Comment by saudet** [comment]
OpenCV and FFmpeg have a lot of modules, you could exclude the `.so` files you don't need...

**Comment by SagiAny** [comment]
I used it as the following: 
`implementation (group: 'org.bytedeco', name: 'javacv', version: '1.4.2' , {
        exclude group: 'org.bytedeco.javacpp-presets', module: 'flandmark'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'flycapture'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'leptonica'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'opencv'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'libdc1394'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'libfreenect2'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'libfreenect'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'librealsense'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'tesseract'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'videoinput'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'artoolkitplus'
    })
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-arm'
    implementation group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '4.0.1-1.4.2', classifier: 'android-x86'`

Can I do something more?

**Comment by saudet** [comment]
Yes, look inside the JAR files.

**Comment by SagiAny** [comment]
Do you mean to exclude an inner so file from a library jar?
I couldn't find useful documentation about it.
Can you please direct me to an example?

**Comment by saudet** [comment]
It's just a ZIP file. You can do whatever you want with it.

**Comment by saudet** [comment]
That means you need it. You could rebuild it from source with only the
codecs you are using.
