### ISSUE TITLE
I have some questions about the JavaCV 

### ISSUE THREAD

**Issue by Bahramudin** [bytedeco/javacv#656]
What is the main difference between the OpenCV Java and the JavaCV?
Because I saw there is a good Java wrapper in OpenCV which we can use in Java.
If JavaCV is better, then what are the main benefits of using JavaCV rather than OpenCV-Java?
Is there any performance difference between these two frameworks? If yes then why JavaCV is better (why JavaCV has good in performance)?
At the end is java language suitable to develop computer vision projects, I am asking this because I have developed one desktop application for windows and when open 3 or 4 camera at the same time, then application became hung, I have done my best optimization, but the performance was so good, so is Java suitable? Thanks!!

**Comment by saudet** [comment]
The answer to that is here: http://bytedeco.org/faq/ JavaCV is usually faster, yes. And yes Java is a fine language to do computer vision. You'll get the same kind of issues with C++ or Python.
