### ISSUE TITLE
Can't stream video AND audio, FFmpegFrameRecorder

### ISSUE THREAD

**Issue by apiatti** [bytedeco/javacv#657]
I am using a Maven Project, javacv version: 1.3.1, OSX Sierra, Java 1.8.

Basically I set up a video conference communication trough udp socket using FFmpegFrameRecorder/Grabber.
When I Introduced the audio I am unable to receive the whole stream to the receiver side!
With this codec, I am getting this exception (when calling recorder.recordSample())
```
av_interleaved_write_frame() error -22 while writing interleaved audio packet.
recorder.setVideoCodec(AV_CODEC_ID_H264);
        recorder.setFormat("H264");

```

And this seems fair, because as I understood h264 does not support interleaved frames(?)
Okay, let's change codec:
```
 recorder.setVideoCodec(AV_CODEC_ID_FLV1);
        recorder.setFormat("flv");
```

**This causes the receiver to not seeing the input stream!!** I really don't know why this is happening, I checked there are no firewall etc... issues...
With any other codec that I tried, **the receiver isn't able to get the input stream.**
Does anyone have an idea why this is happening?

**PS:** Interesting fact, streaming in local (127.0.0.1) everything work fine with the FLV1 codec, the receiver is able to play the input stream!

**Comment by saudet** [comment]
Check the log, what error message do you get there?

**Comment by apiatti** [comment]
I am not getting error messages, everything seems working fine. But the receiver is not able to receive the stream

**Comment by saudet** [comment]
If everything works fine locally, you're having issues with your network. You'll first need to get that working.

**Comment by apiatti** [comment]
The network I think it works fine! The video coded as h264 was going trough network smoothly, makes no sense that changing the codec the video isn't going trough network(?).
Do I need to set some settings when grabbing the received frame?? Thanks:)

**Comment by saudet** [comment]
The log will tell you that. If the log isn't working, please file a bug
upstream?

**Comment by apiatti** [comment]
I will do that after viewing the log :). By log do you mean a stacktrace or what? How to print the log if there are now exceptions?

**Comment by saudet** [comment]
If you don't see FFmpeg's log on the console, make sure to call `FFmpegLogCallback.set()` before.

**Comment by apiatti** [comment]
```
Output #0, flv, to 'udp://10.11.90.53:9000':
    Stream #0:0: Unknown: none (flv)
    Stream #0:1: Unknown: none (aac)
[flv @ 0x7fba46cea000] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[flv @ 0x7fba46cea000] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```

This is the log printed, having this codec:
```
recorder.setVideoCodec(AV_CODEC_ID_FLV1);
        recorder.setFormat("flv");
```
Receiver side, nothing received at all. Could be a bug? Or it is for sure a network issue?

**Comment by saudet** [comment]
Please try again with the latest version of JavaCV.

**Comment by apiatti** [comment]
Okay, I was having a difficult time changing the Maven dependency, but I'll let you know something! Thanks for now:)

**Comment by apiatti** [comment]
@saudet Thanks:) everything solved and now working, successfully implemented everything
