### ISSUE TITLE
Could not initialize class org.bytedeco.javacpp.avutil] with root cause  java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by kelvinsleonardo** [bytedeco/javacv#658]
I'm using the last dependency in maven:

```
<dependency>
<groupId>org.bytedeco</groupId>
<artifactId>javacv-platform</artifactId>
<version>1.3.2</version>
</dependency>
```

The code
![code](https://cloud.githubusercontent.com/assets/7854286/24407109/5c4607fa-13a0-11e7-835d-348c22718e56.png)

However, I get this following error in log "locahost" of the tomcat9:
![noclassdeffounderror](https://cloud.githubusercontent.com/assets/7854286/24407183/a9d05764-13a0-11e7-92e3-a09701ef5cad.png)

The .war is being generated in maven Intellij. Any idea, anyone?

**Comment by saudet** [comment]
For Tomcat, we need to use the shared classloader:
https://wiki.apache.org/tomcat/HowTo#I.27m_encountering_classloader_problems_when_using_JNI_under_Tomcat
