### ISSUE TITLE
Why all XXXVector Class has no push_back function?

### ISSUE THREAD

**Issue by xiaoyudannew** [bytedeco/javacv#659]
e.g MatVector, it has only 3 put function, but they can't work as push_back:

               MatVector v = new MatVector();
		
		for (int i = 0; i < 5; i++) {
			Mat m = new Mat();
//			v.put(m); // -11708416,1
//			v.put(new Mat[]{m}); // 1,1
//			v.put(i, m); // exception
		}
		
		System.out.println(v.size()+","+v.capacity());

**Comment by saudet** [comment]
It is something we could implement yes. It hasn't been a priority, but contributions are welcome!

**Comment by xiaoyudannew** [comment]
ok, thanks. I know it now.

**Comment by saudet** [comment]
I've added `pop_back()` and `push_back()` methods in the commit above. Let me know if you have any issues using those! Thanks for the feedback.

**Comment by saudet** [comment]
Included in newly released version 1.4! Thanks for the feedback.
