### ISSUE TITLE
Problem with Timeout RTSP in FrammeGrabber.Start() program not return

### ISSUE THREAD

**Issue by willagner** [bytedeco/javacv#661]
I have one program to get one image with one link rtsp.

But if the link are broken the program not return.

    public static void main(String[] args){

        FrameGrabber frameGrabber = new 

        FFmpegFrameGrabber("rtsp://ip:port/login&password");

        CanvasFrame canvasFrame = new CanvasFrame("Test");

        frameGrabber.start();

        for(int i = 0; i<frameGrabber.getLengthInFrames(); i++){
           canvasFrame.showImage(frameGrabber.grab());
        }
        frameGrabber.flush();

        canvasFrame.dispose();
    }

I try use frameGrabber.setTimeout(3); and not return.

I try use frameGrabber.setOption("timeout","3"); and the program return:
INFORMAÇÕES: avformat_open_input() error -10049: Could not open input "rtsp://ip:port/user=user&password=pass&channel=1&stream=0.sdp?". (Has setFormat() been called?)
[rtsp @ 000000001e6b6200] Unable to open RTSP for listening

I can not set timeout with use url rtsp.

Plz help me.

**Comment by saudet** [comment]
Error 10049 is "The requested address is not valid in its context": You're going to need to specify a valid IP address.

**Comment by willagner** [comment]
But i specify a valid IP the problem also occurs.

If i comment this frameGrabber.setOption("timeout","3"); the error not occurs.

But if a not use parameter timeout and i pass one incorret or broken link rtsp the program not return and enter in infinite listen.

**Comment by willagner** [comment]
@Saudet have you seen how set timeout to connect in link RTSP in frameGrabber ?

**Comment by saudet** [comment]
It's working fine for others, for example:
http://stackoverflow.com/questions/31034161/streaming-rtsp-with-javacv-library

**Comment by willagner** [comment]
In this case, he don't use the option timeout
frameGrabber.setOption("timeout", "3");

The problem occours when use timeout.

**Comment by saudet** [comment]
So, maybe it doesn't support a timeout. Have you asked the developers of FFmpeg?

**Comment by willagner** [comment]
I get this parameter in documentation by FFmpeg.

But, i will do this.

**Comment by saudet** [comment]
It also says on https://www.ffmpeg.org/ffmpeg-protocols.html#rtsp that "This option implies the rtsp_flags set to ‘listen’." Is this what you want?

**Comment by willagner** [comment]
Yes,
If i not use the parameter timeout, my program work normaly.

But when a use "frameGrabber.setOption("timeout", "3");" in my code return this:
INFORMAÇÕES: avformat_open_input() error -10049: Could not open input "rtsp://ip:port/user=user&password=pass&channel=1&stream=0.sdp?". (Has setFormat() been called?)
[rtsp @ 000000001e6b6200] Unable to open RTSP for listening

The problem occours only i try use timeout.

**Comment by willagner** [comment]
This is my code:
String httpCam;
    
    httpCam    =  "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov";
    FFmpegFrameGrabber frameGrabber;
    
    frameGrabber = new FFmpegFrameGrabber(httpCam);
        
    frameGrabber.setOption("timeout", "5");
    
    try{
        frameGrabber.start();
    }catch(FrameGrabber.Exception ex){
        geraLog();
        logger.info(ex.getMessage());
        return;
    }

if i not use this command ( frameGrabber.setOption("timeout", "5"); ) my program work normaly but not return when the link are broken and enter in infinite loop to listen the link.

If i use this command, the programa return this:
INFORMAÇÕES: avformat_open_input() error -10049: Could not open input "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov". (Has setFormat() been called?)
[rtsp @ 000000001f156480] Unable to open RTSP for listening
[rtsp @ 000000001f156c20] Unable to open RTSP for listening

I don't know how i solve this.

**Comment by saudet** [comment]
Your intention is not to set it in listening mode, so don't try to use that option! Try to use another one

**Comment by willagner** [comment]
I thing this is not possíble.

In documentation by ffmpeg have this:
"timeout
Set maximum timeout (in seconds) to wait for incoming connections.

A value of -1 means infinite (default). This option implies the rtsp_flags set to ‘listen’."

https://www.ffmpeg.org/ffmpeg-all.html

**Comment by willagner** [comment]
Look this:
https://trac.ffmpeg.org/ticket/2294
is the problem in ffmpeg
and this:
https://github.com/FFmpeg/FFmpeg/pull/91

How we can use this updated files ".c" in the library ?

The files ffmpeg are:
libavformat/rtsp.c
libavformat/rtsp.h
libavformat/rtspdec.c

**Comment by saudet** [comment]
Rebuild from source:
https://github.com/bytedeco/javacpp-presets/#build-instructions

**Comment by saudet** [comment]
It turns out that we need to set the "stimeout" option for RTSP. Thanks to @d-a-gerashenko we now have working sample code for this:
https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java

**Comment by LeeWiHong** [comment]
> Yes, If i not use the parameter timeout, my program work normaly.
> 
> But when a use "frameGrabber.setOption("timeout", "3");" in my code return this: INFORMAÇÕES: avformat_open_input() error -10049: Could not open input "rtsp://ip:port/user=user&password=pass&channel=1&stream=0.sdp?". (Has setFormat() been called?) [rtsp @ 000000001e6b6200] Unable to open RTSP for listening
> 
> The problem occours only i try use timeout.

it works for me
