### ISSUE TITLE
Android: How to convert Bitmap to Mat and Mat to Bitmap?

### ISSUE THREAD

**Issue by michaelDnguyen** [bytedeco/javacv#662]
I have some problem about JavaCV in Android:
- How to convert Bitmap to Mat and vice versa ?
- How to convert Image to grayscale, black-white binary in Android ?
- How to using function matchTemplate, normalize, threshold... in android ?
I didn't find documents or examples about used this library, can you provide?

Thanks & Best regard,

**Comment by saudet** [comment]
The answers to that are already on the site:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
https://github.com/bytedeco/javacv/tree/master/samples
https://github.com/bytedeco/sample-projects
http://bytedeco.org/javacpp-presets/opencv/apidocs/
Let me know if there is anything unclear from that material!

**Comment by michaelDnguyen** [comment]
Excuse me,
I don't understand sample code convert with FFmpegFrameGrabber.
Please help me review the code below is possible ?
If possible let me see the demo code converted directly from bitmap to mat, because I need to use bitmap type to process through many steps.

`public static Mat convertBitmap2Mat(Bitmap bitmap) throws Exception {

		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		bitmap.compress(CompressFormat.JPEG, 100, stream);
		InputStream is = new ByteArrayInputStream(stream.toByteArray());

		FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(is);
		grabber.setFormat("jpeg");
		OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();
		
		Frame frame = grabber.grabImage();
		// Perform a shallow copy to represent frame as a Mat
		Mat mat = converterToMat.convert(frame);		
		grabber.close();
		return mat;
	}`

Thanks & best regard,

**Comment by michaelDnguyen** [comment]
@saudet please review help me, thanks.

**Comment by saudet** [comment]
If you're trying to decode JPEG data, it's probably easier using imread() or imdecode() from OpenCV.

**Comment by saudet** [comment]
Why do you want to use FFmpegFrameGrabber?

**Comment by michaelDnguyen** [comment]
I'm trying to process images using javacv library, i also tried opencv, its functions are easy but it's annoying to have to setup jni, ndk instead of just importing jar files like javacv.

My processing flow: read image file from sdcard into bitmap, image processing with javacv eventually save bitmap into sdcard.

**Comment by saudet** [comment]
Then just use imread() and imwrite() to read and write your image files
directly.

**Comment by ankhafizov** [comment]
```
private fun matToBitmap(img: Mat): Bitmap {
        val frame = converterToMat.convert(img)
        val bm = frameConverter.convert(frame)
        return bm
    }

private fun bitmapToMat(bitmap: Bitmap): Mat {
        val frame = frameConverter.convert(bitmap)
        val mat = converterToMat.convert(frame)
        return mat
    }
```
