### ISSUE TITLE
Trying to load jar files that are not exists 

### ISSUE THREAD

**Issue by ytong3** [bytedeco/javacv#663]
I am implementing a spring boot web service using JavaCV and JavaCPP. I am using Maven 3.3. My mvn dependency looks like this:

		**<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv</artifactId>
			<version>1.3.2</version>
		</dependency>

		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacpp</artifactId>
			<version>1.3.2</version>
		</dependency>**

I am getting FileNotFoundException from classloader hierarchy. Looks like it's trying to load jars that are not in the directory. I got a total of 72 errors and here are some examples:

java.io.FileNotFoundException: /Users/user/.m2/org/bytedeco/javacv/1.3.2/javacpp-1.3.2.jar (No such file or directory)
java.io.FileNotFoundException: /Users/user/.m2/org/bytedeco/javacv/1.3.2/opencv-3.2.0-1.3.jar (No such file or directory)
java.io.FileNotFoundException: /Users/user/.m2/org/bytedeco/javacv/1.3.2/flycapture-2.9.3.43-1.3.jar
java.io.FileNotFoundException: /Users/user/.m2/org/bytedeco/javacpp-presets/flandmark/1.07-1.3/javacpp.jar
..

I am really new to javacv, javacpp and c++. Any help is appreciated.

**Comment by saudet** [comment]
Could you try again with Maven 3.3.9?

**Comment by ytong3** [comment]
It works now! thanks

**Comment by saudet** [comment]
Good!

**Comment by ytong3** [comment]
@saudet after more digging, I am still getting the above mentioned error, with the suggested dependency by Spring boot.

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
			<scope>provided</scope>
		</dependency>

Could you help please?

**Comment by saudet** [comment]
For Tomcat, we need to use the shared classloader:
https://wiki.apache.org/tomcat/HowTo#I.27m_encountering_classloader_problems_when_using_JNI_under_Tomcat
