### ISSUE TITLE
Javacv: Mat data becomes null after using methods

### ISSUE THREAD

**Issue by rarrouba** [bytedeco/javacv#666]
I'm working on an android application for object detection and counting. For the image processing I am using JavaCV (Java wrapper for OpenCV and FFmpeg). After importing the library, I'm able to successfully use the FFmpegFrameGrabber to get the frames of a video.

**My problem:** After I convert the Frame to a Mat object and perform some operation on that Mat object the data becomes null.

**Code:**

**MainActivity**

        public class MainActivity extends AppCompatActivity {
    
    
        
        OpenCVFrameConverter.ToMat converterToMat = new OpenCVFrameConverter.ToMat();
    
    
        private CountModule countModule;
        FFmpegFrameGrabber retriever;
    
        ArrayList<opencv_core.Mat> frames;
        boolean frameloaded = false;
    
        File folder = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_MOVIES);
        File video = new File(folder, "test.mp4");
    
        AndroidFrameConverter converterToBitmap = new AndroidFrameConverter();
    
        
    
        private static WebStreamer webStreamer;
    
        static {
            System.loadLibrary("native-lib");
        }
    
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);
    
            
            final Button button = (Button) findViewById(R.id.btnLdFrames);
            final ImageView img = (ImageView) findViewById(R.id.imageView);
    
            
            button.setOnClickListener(new View.OnClickListener() {
                public void onClick(View v) {
                    ((TextView) button).setText("Loading");
                    new Thread(new Runnable() {
                        public void run() {
    
                            try {
                                button.setClickable(false);
                                button.setAlpha((float) 0.3);
                                LoadFrames();
                                button.setAlpha((float) 1);
                                
                            } catch (FrameGrabber.Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }).start();
    
                }
            });
        }
        private void LoadFrames() throws FrameGrabber.Exception {
            if (!frameloaded){
    
    
    
                frameloaded = true;
    
                retriever = new FFmpegFrameGrabber(video);
                frames = new ArrayList<>();
                Log.d("Frame",": Start of loop");
    
                retriever.start();
                final ImageView img = (ImageView) findViewById(R.id.imageView);
                for (int i=0;i<50;i++){//155430
                    retriever.setFrameNumber(i*100);
                    Frame temp = new Frame();
                    temp = retriever.grab();
    
                    frames.add(converterToMat.convert(temp));
    
                    Log.d("Frame",": " + i*100);
                        
                    
    
                }
                retriever.stop();
    
                countModule = new CountModule(frames);
                Log.d("Frame","CountModule instantiated");
                
            }
        }
    }

**Constructor of Countmodule**

    public CountModule(ArrayList<Mat> frames){

        fgGBG = new Mat(frames.get(0).rows(),frames.get(0).cols(),frames.get(0).type());
        gbg = createBackgroundSubtractorMOG2();
        Mat maTemp = new Mat(frames.get(0).rows(),frames.get(0).cols(),frames.get(0).type());
        
        median = new Mat(frames.get(0).rows(),frames.get(0).cols(),frames.get(0).type());
        frames.get(0).copyTo(median);
        ;
        median = getMedian(frames);
        kernel2 = Mat.ones(11,11,CV_8U).asMat();
        kernel = Mat.ones(3,1,CV_8U).asMat();
        gbg.apply(median,fgGBG,0.001);

    }

**Variables (images):**

[After convert from Frame to Mat. Data has values.][1]

[Data=null when using the method frame.copyTo(median). Data of Mat also null when using method Mat.ones()][2]

------------------------------------------------

As you can see everytime I use a OpenCV specific method, the returned Mat is not what is expected. 

  [1]: https://i.stack.imgur.com/t7CSD.png
  [2]: https://i.stack.imgur.com/4F9d6.png

**Comment by saudet** [comment]
Could you try the following and let me know what you get?
```java
        Mat mat = new Mat(16, 16, CV_8UC1);
        Mat copy = new Mat();
        mat.copyTo(copy);
        System.out.println(copy);
```

**Comment by rarrouba** [comment]
This is what I get when I execute that code:

**org.bytedeco.javacpp.opencv_core$Mat[width=16,height=16,depth=8,channels=1]**

**Comment by saudet** [comment]
So, it's not `null`, and then that means `frames.get(0)` is empty. You'll need to copy a non-empty `Mat`.

**Comment by rarrouba** [comment]
But if I understand correctly frames.get(0) isn't empty as seen in this [picture][1]. The `data` field isn't empty.



  [1]: https://i.stack.imgur.com/t7CSD.png

**Comment by saudet** [comment]
Well, then there's a bug in OpenCV somewhere. Please report upstream.

**Comment by saudet** [comment]
Wait a minute, you're looking the private data field. That's not relevant, you have to ignore that. It's private for a reason.
