### ISSUE TITLE
[Q] Android: how to display modified image data in SurfaceView?

### ISSUE THREAD

**Issue by hnvn** [bytedeco/javacv#668]
I succeeded to record and save a video from the Camera of Android, but I want to use OpenCV (was packed with javacv) to detect object in image frame (such as faces) and I want to show result of detection progress for user in SurfaceView. How can I deliver modified image data to SurfaceView to draw in Canvas?

**Comment by saudet** [comment]
You convert them into Bitmap: http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by hnvn** [comment]
Please help me again, when I try to use AndroidFrameConverter to convert a Frame to a Bitmap, I encounter an error:  java.lang.RuntimeException: Buffer not large enough for pixels. I guess the reason is I am trying to convert from YUV frame to Bitmap. Could you tell me the right way to fix this problem?

**Comment by saudet** [comment]
Please provide more details.

**Comment by hnvn** [comment]
At first, Thank you so much for replying quickly. My problem doesn't come from converting YUV frame to Bitmap, I think so. I am trying implement a portrait CameraPreview, to rotate Frame I use FFmpegFrameFilter: 
```
private void processFrame(byte[] raw, Camera cam) {
        if (yuvImage != null && recording) {
            ((ByteBuffer) yuvImage.image[0].position(0)).put(raw);
            try {
                Log.v(LOG_TAG, "Writing Frame");
                filter.push(yuvImage);
                Frame frame;
                while ((frame = filter.pull()) != null) {
                    long t = 1000 * (System.currentTimeMillis() - startTime);
                    if (t > recorder.getTimestamp()) {
                         recorder.setTimestamp(t);
                    }
                    recorder.record(frame);
                }
            } catch (FFmpegFrameRecorder.Exception e) {
                Log.v(LOG_TAG, e.getMessage());
                e.printStackTrace();
            } catch (FrameFilter.Exception e) {
                e.printStackTrace();
            }
        }
    }
```
This code is ok to record a video, but when I try to use Frame get from filter to convert to Bitmap, it throw a exception: ` java.lang.RuntimeException: Buffer not large enough for pixels`. 

I just work in JavaCV in a few days  (I've worked in OpenCV (official SDK) before). But I am looking for a solution to stream video while processing with OpenCV, and I read about JavaCV and I am trying to implement my project with JavaCV. There're another way to go, I just use ffmpeg module to record video, and use official OpenCV for computer vision computing. But I see JavaCV contains complete OpenCV code, so I want to try JavaCV only, but example code about this topic is very poor.

**Comment by saudet** [comment]
`FFmpegFrameFilter` might be outputting YUV data yes, but `Bitmap` doesn't support that, so you could try to convert it to RGBA with the [format filter](https://ffmpeg.org/ffmpeg-filters.html#format-1).

Yes, we need more examples and documentation. If you are willing to make contributions they are always welcome! Please send pull requests.

**Comment by hnvn** [comment]
Great! I managed to implement a CameraPreview class with your helps and base on the source code of CameraBridgeViewBase.class of OpenCV4Android SDK [code](https://github.com/opencv/opencv/blob/master/modules/java/generator/src/java/android%2BCameraBridgeViewBase.java). 
It's may be nice to share my code as an example for everyone, but my Github experience is quite poor, please tell me how to do that?

**Comment by saudet** [comment]
Great! Please send a pull request to https://github.com/bytedeco/sample-projects

First you'll need to fork the repository by clicking on the "Fork" button at the top, then make your changes there, and then send a pull request, which is well explained here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by hnvn** [comment]
Ok, I am trying to complete an example with object detector by using OpenCV, then I'll create a pull request but I have a problem. In OpenCV4Android SDK, there is a method: `void cvtColor(Mat src, Mat dst, int code, int dstCn)` but in JavaCV, the same method is: `cvCvtColor( @Const CvArr src, CvArr dst, int code )`. My question is: how to convert Mat to CvArr?

**Comment by saudet** [comment]
The presets also have cvtColor()...

**Comment by hnvn** [comment]
I already created a pull request.

**Comment by saudet** [comment]
Wow, that was fast, thanks!

**Comment by hnvn** [comment]
Your library is awesome in Java world. It saves me a lot time when I implement a solution for processing and streaming video from Android devices.  But I am trying to look for a solution for iOS too. As an experienced developer, you could give me some advices?

**Comment by saudet** [comment]
It looks like http://gluonhq.com/products/mobile/ is going to be the
solution for iOS going forward. It shouldn't be too hard to get JavaCPP
working on that. If you could give it a try, it would be great!
