### ISSUE TITLE
Unable to record video with OpenCVFrameRecorder

### ISSUE THREAD

**Issue by mattdibi** [bytedeco/javacv#671]
Hi, this is the code I have used so far:

```java
try{
IplImage colorImage = null;
OpenCVFrameConverter.ToIplImage converterToIpl = new OpenCVFrameConverter.ToIplImage();

OpenCVFrameRecorder recorder = OpenCVFrameRecorder.createDefault("output.avi", imageWidth, imageHeight);
recorder.start();
...

while(!stop) {
   ...
   // Grab data from RealSense camera
   colorImage = grabColorImage();
   ...
   recorder.record(converterToIpl.convert(colorImage));
 }

recorder.stop();
colorImage.release();

} catch (Exception e) {
   System.out.println( e );
}
```
I used as a reference [this](https://github.com/bytedeco/javacv#sample-usage) example code.
I can display correctly the stream coming from the camera in a `CanvasFrame` but when I run the code above the output.avi file is nowhere to be found.
I tried with `FrameRecorder` without luck.

Am I doing something wrong?

**Comment by saudet** [comment]
Please use FFmpegFrameRecorder instead.

**Comment by mattdibi** [comment]
It works! Thanks!
