### ISSUE TITLE
FFmpegFrameGrabber not grabbing all frames

### ISSUE THREAD

**Issue by Brainicism** [bytedeco/javacv#675]
I've looked at [this issue](https://github.com/bytedeco/javacv/issues/116) and it does not appear to be the same. 

Using [this video ](https://www.youtube.com/watch?v=cMjtCyCSC3s) as a test (although I've been able to reproduce with others). According to VLC, the video has 439 image frames. I do a count of how many of the frames are image frames vs audio frames (based on whether frame.image is null), and also save the image frames my sd card. 

The log message in the `onPostExecute()` prints `Total Frames: 451 | Image Frames: 183 | Audio Frames: 268` which is less than half of what it should be. The last image saved on my phone is a "5" in the countdown video, which is only about half way through the video. 

I've checked that it is going through every iteration of the loop, and no exceptions are being thrown. Any clue why this is happening?
```
public class ProcessImages extends AsyncTask<Void, Integer, Void> {
        FrameGrabber frameGrabber;
        Exception exception;
        OpenCVFrameConverter.ToMat converterToMat;
        Frame currFrame;
        int imageFrames = 0;
        int audioFrames = 0;
        int frameLength;
        @Override
        protected void onPreExecute() {
            frameGrabber = new FFmpegFrameGrabber(path.toString());
            converterToMat = new OpenCVFrameConverter.ToMat();
        }

        @Override
        protected Void doInBackground(Void... params) {
            try {
                frameGrabber.start();
            } catch (FrameGrabber.Exception e) {
                exception = e;
            }
            frameLength = frameGrabber.getLengthInFrames();
            for (int i = 0; i < frameGrabber.getLengthInFrames(); i++) {
                try {
                    Frame frame = frameGrabber.grabFrame();
                    if (frame.image == null) {
                        audioFrames++;
                        Log.d(TAG, "EMPTY IMAGE: " + i);
                        continue;
                    }
                    opencv_core.Mat mat = converterToMat.convertToMat(frame);
                    imageFrames++;
                    saveImage(mat, i);
                } catch (Exception e) {
                    exception = e;
                }
            }
            try {
                frameGrabber.flush();
            } catch (FrameGrabber.Exception e) {
                exception = e;
            }
            return null;
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            Log.d(TAG, "Total Frames: " + frameLength + " | Image Frames: " + imageFrames + " | " + "Audio Frames: " + audioFrames);
            super.onPostExecute(aVoid);
        }
    }
```

**Comment by saudet** [comment]
There are no errors or warnings in the log? Could you copy and paste it
here?

**Comment by Brainicism** [comment]
There were no error messages, but I figured out the issue. I declared the grabber as the base class `FrameGrabber` instead of `FFmpegFrameGrabber,` I changed that, used `.grabImage()` instead and it worked perfectly.

**Comment by saudet** [comment]
Duplicate of #116
