### ISSUE TITLE
Couldn't find libjniavutil.so

### ISSUE THREAD

**Issue by xsobolx** [bytedeco/javacv#676]
I have got exception:

/UncaughtException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/.../base.apk"],nativeLibraryDirectories=[/data/app/.../lib/arm, /data/app/../base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libjniavutil.so"

https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
don't helped me

**Comment by saudet** [comment]
Please show me the content of your APK file.

**Comment by saudet** [comment]
I'm assuming that there were files missing from your APK and that you have since sorted out this issue. If not, please let me know!
