### ISSUE TITLE
Could not extract the classifier file from Java resource

### ISSUE THREAD

**Issue by dengyuhan** [bytedeco/javacv#679]
I use the following reference
```
    compile 'org.bytedeco:javacv:1.3.2'
    compile 'org.bytedeco.javacpp-presets:opencv:3.2.0-1.3.2:android-arm'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:3.2.1-1.3.2:android-arm'
```
When I started FacePreview,pop up 'Could not extract the classifier file from Java resource'.

**Comment by saudet** [comment]
You're trying to use versions that don't exist. Try this instead:
```groovy
    compile 'org.bytedeco:javacv:1.3.2'
    compile 'org.bytedeco.javacpp-presets:opencv:3.2.0-1.3:android-arm'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:3.2.1-1.3:android-arm'
```

**Comment by sara-khayyat** [comment]
I tried this solution and it didn't work
I also tried to install javacv manually using .jar files and the result was the same

**Comment by saudet** [comment]
Please try again with JavaCV 1.4.1.

**Comment by sara-khayyat** [comment]
`compile 'org.bytedeco:javacv:1.4.1'
    compile 'org.bytedeco.javacpp-presets:opencv:3.2.0-1.3:android-arm'
    compile 'org.bytedeco.javacpp-presets:ffmpeg:3.2.1-1.3:android-arm'`

I tried this and it also gives the same error

**Comment by saudet** [comment]
Update the versions of the dependencies as well:
https://github.com/bytedeco/javacv/blob/1.4.1/pom.xml#L74
