### ISSUE TITLE
 Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12134 (android_example)

### ISSUE THREAD

**Issue by MuthuEphron** [bytedeco/javacv#685]
When stop the recording  I got the error  Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12134 (android_example). How to resolve this error? Please Help me

**Comment by saudet** [comment]
I already told you: Use the latest version of JavaCV.

**Comment by MuthuEphron** [comment]
I use the latest version Java CV 1.3.2

**Comment by saudet** [comment]
Ok, so I'll need more information. Could you post your log?

**Comment by MuthuEphron** [comment]
Sometime i  got this error in  please tell how to solve the two problems. i need to finish the project tonignt

04-26 15:52:52.667 26916-26916/org.bytedeco.javacv_android_example W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -110: Could not open 'null'
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:784)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:351)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:236)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:315)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at android.view.View.performClick(View.java:4487)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at android.view.View$PerformClick.run(View.java:18746)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at android.os.Looper.loop(Looper.java:149)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5257)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
04-26 15:52:52.687 26916-26916/org.bytedeco.javacv_android_example W/System.err:     at dalvik.system.NativeStart.main(Native Method)
04-26 15:52:52.697 26916-26916/org.bytedeco.javacv_android_example W/RecordActivity: Start Button Pushed

**Comment by MuthuEphron** [comment]
sometimes its working fine  Now I got  this error  org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -1313558101: Could not open 'null'
 I gave the rtmp url rtmp://198.199.123.130:1935/livestream/myStream.mp4

**Comment by saudet** [comment]
Like I said, I can't tell anything without the log!

**Comment by MuthuEphron** [comment]
I posted the log values please check it above.

**Comment by MuthuEphron** [comment]
I can't record the streaming video . I got the error like org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -1313558101: Could not open 'null'. I got this error in all mobiles  First I need to fixed the issue. Please tell me.

**Comment by MuthuEphron** [comment]
Sir the apk file displayed 200 mb how to reduce the apk file size?

**Comment by MuthuEphron** [comment]
I used the project  following url
Are you developing this project
https://github.com/bytedeco/sample-projects/tree/master/JavaCV-android-example/app/src/main

**Comment by saudet** [comment]
It doesn't include FFmpeg's log...

**Comment by MuthuEphron** [comment]
First how to reduce the apk size ? Please tell me it displayed 200 mb

**Comment by MuthuEphron** [comment]
How to get FFmpeg logs. I am using windows 10

**Comment by saudet** [comment]
The same as before, please call FFmpegLogCallback.set().

**Comment by tonymcodes** [comment]
@MuthuEphron are you using a separate thread for camera ?

**Comment by MuthuEphron** [comment]
@tonymcodes  No
