### ISSUE TITLE
Java audio (latency) sucks (in general). Bindings for ASIO driver would be really cool.

### ISSUE THREAD

**Issue by jjYBdx4IL** [bytedeco/javacv#686]
Did you already look at this? Any ideas? Maybe existing bindings in some other package, not necessarily ASIO related but with low latency?

Boost has ASIO support. Are there bindings for boost hidden somewhere? :)

**Comment by saudet** [comment]
Sure, contributions welcome!

Although I would probably go with something like OpenAL or OpenSL ES instead since it has higher chances of working on Android as well...

**Comment by jjYBdx4IL** [comment]
https://github.com/jitsi/libjitsi <- this one uses WASAPI. Should be even better.
