### ISSUE TITLE
Exception: Buffer not large enough for pixels

### ISSUE THREAD

**Issue by anonym24** [bytedeco/javacv#688]
```
 org.bytedeco.javacv.AndroidFrameConverter converter = new AndroidFrameConverter();
 Bitmap frameBitmap = converter .convert(filteredFrame);
```

**Comment by saudet** [comment]
Please try to convert supported formats only.

**Comment by anonym24** [comment]
anyway I read that AndroidFrameConverter isn't efficient method 

> This class is not optimized for speed. For best performance, convert first your data to and from RGBA with optimized functions from FFmpeg or OpenCV. 

I'm trying to put text on frames while I record video. So before this line I want to put some text on a frame: 
`mFrameRecorder.record(filteredFrame);` https://github.com/CrazyOrr/FFmpegRecorder/blob/master/app/src/main/java/com/github/crazyorr/ffmpegrecorder/FFmpegRecordActivity.java#L707

also: https://github.com/CrazyOrr/FFmpegRecorder/blob/master/app/src/main/java/com/github/crazyorr/ffmpegrecorder/FFmpegRecordActivity.java#L668

What is the best way to add text using this example project for video recording?

**Comment by saudet** [comment]
On Android that would be with the graphics package.

**Comment by anonym24** [comment]
I also decided to try: https://github.com/bytedeco/javacv/issues/254
So in `RecordActivity `sample I set:

 /*Filter information, change boolean to true if adding a fitler*/
 private boolean addFilter = true;
 
 private void initRecorder() {

        ...
        filter = new FFmpegFrameFilter("drawtext=\"text='hello world'\"", imageWidth, imageHeight);

It records video ok, but when I watch output video file after recording there is no any text on the video

**Comment by saudet** [comment]
You'll need a build of FFmpeg with FreeType for this to work.

Anyway, here's an example you could use as reference that uses the graphics package though:
https://github.com/bytedeco/sample-projects/blob/master/javacv-android-camera-preview/app/src/main/java/org/bytedeco/javacv/android/example/CvCameraPreview.java
Thanks again @hnvn for your generous contribution! It is already being useful.

**Comment by anonym24** [comment]
@saudet I would like to not show any text on preview (surface) while recording video, so I could see it only after recording and watching it in some other video player.
So his example puts text on preview (surface view)?

**Comment by saudet** [comment]
We can convert the Bitmaps back to Frames...

**Comment by anonym24** [comment]
I succeeded with next solution:

```
opencv_imgproc.CvFont mSubtitleFont = new opencv_imgproc.CvFont();
opencv_imgproc.cvInitFont(mSubtitleFont, opencv_imgproc.CV_FONT_HERSHEY_SCRIPT_SIMPLEX, 2.0, 2.0, 2, 2, CV_AA);
...
@Override
    public Mat onCameraFrame(Mat mat) {
        if (recording && mat != null) {

            synchronized (semaphore) {
                try {
                    Mat mat1 = new Mat();
                    mat.copyTo(mat1);
                    opencv_imgproc.putText(mat1, "HARDSUB", new opencv_core.Point(25, 25), FONT_HERSHEY_PLAIN, 1.0, new opencv_core.Scalar(0, 255, 0, 2.0));
                    Frame frame = converterToMat.convert(mat1);
                    long t = 1000 * (System.currentTimeMillis() - startTime);
                    if (t > recorder.getTimestamp()) {
                        recorder.setTimestamp(t);
                    }
                    recorder.record(frame);
                } catch (FFmpegFrameRecorder.Exception e) {
                    Log.v(LOG_TAG, e.getMessage());
                    e.printStackTrace();
                }
            }
        }
        return mat;
    }
```
@saudet
also I have a question about opencv4android, I my project I already use it, and I don't have really time to convert all of my code to javacv opencv, so I want to use ffmpegframerecorder with opencv4android - convert `frame` to `mat` (opencv4android)
if it possible?

**Comment by saudet** [comment]
Great!

Yes, it's possible, it's already documented here:
https://github.com/bytedeco/javacpp/issues/38

**Comment by hnvn** [comment]
@anonym24 if you want to reduce your apk size, I recommend you use javacv and try to remove unused .so lib files. Because opencv4android packed all .a files in one file libopencv_java3.so make it too big. For example, if you only use opencv to detect object you don't need libjniopencv_text.so, libjniopencv_calib3d.so, ... If you don't know which lib you should remove, try to remove one by one and run project, if your app works well you found an unused .so ✌️

**Comment by anonym24** [comment]
thanks)
