### ISSUE TITLE
Finding a way to stream and record video at the same time.

### ISSUE THREAD

**Issue by MichaelReyes** [bytedeco/javacv#692]
Hello,

I need to stream and record a video at the same time. Need to upload recorded video of livestream to server. I've search the net and read issues about this but it seems there is no direct answer if this is possible or not. Please tell me if this is possible?

Thanks.

**Comment by saudet** [comment]
Sure, why not? Could you explain the issue that you are encountering?

**Comment by MichaelReyes** [comment]
I've tried using 2 FFmpegFrameRecorder. one for livestream and the other one for recording that sends the video to server every 10 seconds. The problem is that the recorded video result is broken, when you play the video sometimes it stop then skip a few seconds(at random) then continue.

**Comment by saudet** [comment]
Make sure to call FrameRecorder.setTimestamp() before record().

2017/05/09 14:16 "Michael Angelo Reyes" <notifications@github.com>:

**Comment by MichaelReyes** [comment]
Yes im setting that too.

Here's my full code. Hope you can help me with this. thanks.
`package com.vzx.android.vuzixandroid.livestream;

import android.app.Activity;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.ActivityInfo;
import android.hardware.Camera;
import android.location.Criteria;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.media.AudioFormat;
import android.media.AudioRecord;
import android.media.MediaRecorder;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.CountDownTimer;
import android.os.Environment;
import android.util.Log;
import android.view.Display;
import android.view.KeyEvent;
import android.view.LayoutInflater;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.crashlytics.android.Crashlytics;
import com.vzx.android.vuzixandroid.R;
import com.vzx.android.vuzixandroid.common.Constants;
import com.vzx.android.vuzixandroid.model.preference.LocationCoordinates;
import com.vzx.android.vuzixandroid.model.preference.User;
import com.vzx.android.vuzixandroid.receiver.LocationUpdateBroadcastReceiver;
import com.vzx.android.vuzixandroid.task.SendLocationToServerTask;
import com.vzx.android.vuzixandroid.task.SendStreamCommandToServerTask;
import com.vzx.android.vuzixandroid.task.UploadVideoTask;

import org.bytedeco.javacpp.avcodec;
import org.bytedeco.javacpp.avutil;
import org.bytedeco.javacv.FFmpegFrameFilter;
import org.bytedeco.javacv.FFmpegFrameRecorder;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameFilter;

import java.io.File;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ShortBuffer;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

import io.fabric.sdk.android.Fabric;

public class RecordActivity extends Activity implements View.OnClickListener {

    private final static String CLASS_LABEL = "RecordActivity";
    private final static String LOG_TAG = CLASS_LABEL;

    private String ffmpeg_streaming_link = "rtmp://54.214.201.246/live/";
    private File ffmpeg_recording_link = new File(Environment.getExternalStorageDirectory(), "archive.mp4");

    long startTime = 0;
    boolean recording = false;

    private FFmpegFrameRecorder recorderForStreaming;
    private FFmpegFrameRecorder recorderForArchive;

    private boolean isPreviewOn = false;

    /*Filter information, change boolean to true if adding a fitler*/
    private boolean addFilter = false;
    private String filterString = "";
    FFmpegFrameFilter filter;

    private int sampleAudioRateInHz = 44100;
    private int imageWidth = 320;
    private int imageHeight = 240;
    private int frameRate = 24;

    /* audio data getting thread */
    private AudioRecord audioRecord;
    private AudioRecordRunnable audioRecordRunnable;
    private Thread audioThread;
    volatile boolean runAudioThread = true;

    /* video data getting thread */
    private Camera cameraDevice;
    private CameraView cameraView;

    private String mVideoPath;

    private Frame yuvImage = null;

    /* layout setting */
    private final int bg_screen_bx = 232;
    private final int bg_screen_by = 128;
    private final int bg_screen_width = 1000; //700;
    private final int bg_screen_height = 500; //500;
    private final int bg_width = 1223;
    private final int bg_height = 715;
    private final int live_width = 1080; //640;
    private final int live_height = 720; //480;
    private int screenWidth, screenHeight;
    private Button btnRecorderControl;
    private TextView tvStreaming;

    private boolean archiveTimerStarted = false;

    /* The number of seconds in the continuous record loop (or 0 to disable loop). */
    final int RECORD_LENGTH = 0;
    Frame[] images;
    long[] timestamps;
    ShortBuffer[] samples;
    int imagesIndex, samplesIndex;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Fabric.with(this, new Crashlytics());

        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

        setContentView(R.layout.main);

        initLayout();
        //initializeBroadcastReceivers();

        //startService(new Intent(this, LocationUpdateService.class));

        LocationManager locManager = (LocationManager) getSystemService(Context.LOCATION_SERVICE);

        boolean isGPSProviderEnabled = locManager.isProviderEnabled(LocationManager.GPS_PROVIDER);

        boolean isNetworkProviderEnabled = locManager.isProviderEnabled(LocationManager.NETWORK_PROVIDER);

        Criteria crit = new Criteria();
        crit.setAccuracy(Criteria.ACCURACY_FINE);
        String provider = locManager.getBestProvider(crit, true);
        Location loc = locManager.getLastKnownLocation(provider);

        Log.d("MIKE", "provider: " + provider);

        if (loc != null)
            Log.d("MIKE", "loc: " + loc.getLatitude() + " ~ " + loc.getLongitude());

        Log.d("MIKE", "isGPSProviderEnabled: " + isGPSProviderEnabled);
        Log.d("MIKE", "isNetworkProviderEnabled: " + isNetworkProviderEnabled);

        locManager.requestLocationUpdates(provider /*LocationManager.GPS_PROVIDER*/, 0, 0, new LocationListener() {
            @Override
            public void onLocationChanged(Location location) {

                Log.d("MIKE", "onLocationChanged");

                LocationCoordinates locationCoordinates = LocationCoordinates.getLocationInfoFromSharedPreferences(RecordActivity.this);
                locationCoordinates.setLatitude(location.getLatitude());
                locationCoordinates.setLongitude(location.getLongitude());
                locationCoordinates.save(RecordActivity.this);

                SendLocationToServerTask sendLocationToServerTask = new SendLocationToServerTask(RecordActivity.this, new SendLocationToServerTask.SendLocationToServerListener() {
                    @Override
                    public void onSendSuccess() {
                        Log.d("MIKE", "success");
                    }

                    @Override
                    public void onSendFailed() {
                        Log.d("MIKE", "failed");
                    }
                });

                if (recording)
                    sendLocationToServerTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR,
                            new Double[]{
                                    location.getLatitude(),
                                    location.getLongitude()});
            }

            @Override
            public void onStatusChanged(String provider, int status, Bundle extras) {

            }

            @Override
            public void onProviderEnabled(String provider) {

            }

            @Override
            public void onProviderDisabled(String provider) {

            }
        });

        locManager.requestLocationUpdates(LocationManager.PASSIVE_PROVIDER, 0, 0, new LocationListener() {
            @Override
            public void onLocationChanged(Location location) {

                Log.d("MIKE", "passive onLocationChanged");

                /*SendLocationToServerTask sendLocationToServerTask = new SendLocationToServerTask(RecordActivity.this, new SendLocationToServerTask.SendLocationToServerListener() {
                    @Override
                    public void onSendSuccess() {
                        Log.d("MIKE", "success");
                    }

                    @Override
                    public void onSendFailed() {
                        Log.d("MIKE", "failed");
                    }
                });

                sendLocationToServerTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR,
                        new Double[]{
                                location.getLatitude(),
                                location.getLongitude()});*/
            }

            @Override
            public void onStatusChanged(String provider, int status, Bundle extras) {

            }

            @Override
            public void onProviderEnabled(String provider) {

            }

            @Override
            public void onProviderDisabled(String provider) {

            }
        });

        Location location = locManager.getLastKnownLocation(LocationManager.GPS_PROVIDER);

        double latitude = 0;
        double longitude = 0;
        if (location != null) {
            latitude = location.getLatitude();
            longitude = location.getLongitude();

            SendLocationToServerTask sendLocationToServerTask = new SendLocationToServerTask(RecordActivity.this, new SendLocationToServerTask.SendLocationToServerListener() {
                @Override
                public void onSendSuccess() {
                    Log.d("MIKE", "success");
                }

                @Override
                public void onSendFailed() {
                    Log.d("MIKE", "failed");
                }
            });

            sendLocationToServerTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR,
                    new Double[]{
                            location.getLatitude(),
                            location.getLongitude()});
        }

    }

    @Override
    protected void onResume() {
        super.onResume();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        //stopService(new Intent(this, LocationUpdateService.class));

        recording = false;

        if (cameraView != null) {
            cameraView.stopPreview();
        }

        if (cameraDevice != null) {
            cameraDevice.stopPreview();
            cameraDevice.release();
            cameraDevice = null;
        }

        if (locationUpdateBroadcastReceiver != null)
            unregisterReceiver(locationUpdateBroadcastReceiver);
    }

    private LocationUpdateBroadcastReceiver locationUpdateBroadcastReceiver;

    private void initializeBroadcastReceivers() {
        IntentFilter profileSyncFilter = new IntentFilter();
        profileSyncFilter.addAction(LocationUpdateBroadcastReceiver.ACTION_ON_LOCATION_UPDATE);
        profileSyncFilter.addCategory(Intent.CATEGORY_DEFAULT);
        locationUpdateBroadcastReceiver = new LocationUpdateBroadcastReceiver(locationUpdateListener);
        registerReceiver(locationUpdateBroadcastReceiver, profileSyncFilter);
    }

    private LocationUpdateBroadcastReceiver.EventListener locationUpdateListener = new LocationUpdateBroadcastReceiver.EventListener() {
        @Override
        public void onLocationUpdate() {
            SendLocationToServerTask sendLocationToServerTask = new SendLocationToServerTask(RecordActivity.this, new SendLocationToServerTask.SendLocationToServerListener() {
                @Override
                public void onSendSuccess() {
                    Log.d("MIKE", "success");
                }

                @Override
                public void onSendFailed() {
                    Log.d("MIKE", "failed");
                }
            });

            LocationCoordinates locationCoordinates = LocationCoordinates.getLocationInfoFromSharedPreferences(RecordActivity.this);

            sendLocationToServerTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR,
                    new Double[]{
                            locationCoordinates.getLatitude(),
                            locationCoordinates.getLongitude()});
        }
    };


    private void initLayout() {

        /* get size of screen */
        Display display = ((WindowManager) getSystemService(Context.WINDOW_SERVICE)).getDefaultDisplay();
        screenWidth = display.getWidth();
        screenHeight = display.getHeight();
        RelativeLayout.LayoutParams layoutParam = null;
        LayoutInflater myInflate = null;
        myInflate = (LayoutInflater) getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        RelativeLayout topLayout = new RelativeLayout(this);
        setContentView(topLayout);
        LinearLayout preViewLayout = (LinearLayout) myInflate.inflate(R.layout.main, null);
        layoutParam = new RelativeLayout.LayoutParams(screenWidth, screenHeight);
        topLayout.addView(preViewLayout, layoutParam);

        /* add control button: start and stop */
        btnRecorderControl = (Button) findViewById(R.id.recorder_control);
        btnRecorderControl.setText("Start");
        btnRecorderControl.setOnClickListener(this);

        tvStreaming = (TextView) findViewById(R.id.recorder_tvStreaming);

        /*
        Log.d("MIKE", "initLayout");

        Log.d("MIKE",bg_screen_width + " ~ " + screenWidth + " ~ " + bg_width);
        Log.d("MIKE",bg_screen_height + " ~ " + screenHeight + " ~ " + bg_height);

        *//* add camera view *//*
        int display_width_d = (int) 1.0 * screenWidth / 4 ; //(int) (1.0 * bg_screen_width * screenWidth / bg_width);
        Log.d("MIKE", "display_width_d: " + display_width_d);
        int display_height_d = (int) 1.0 *  screenHeight; //(int) (1.0 * bg_screen_height * screenHeight / bg_height);
        Log.d("MIKE", "display_height_d: " + display_height_d);
        int prev_rw, prev_rh;
        if (1.0 * display_width_d / display_height_d > 1.0 * live_width / live_height) {
            prev_rh = display_height_d;
            prev_rw = (int) (1.0 * display_height_d * live_width / live_height);
            Log.d("MIKE", "1: " + prev_rh + " ~ " + prev_rw );
        } else {
            prev_rw = display_width_d;
            prev_rh = (int) (1.0 * display_width_d * live_height / live_width);
            Log.d("MIKE", "2: " + prev_rh + " ~ " + prev_rw );
        }

        prev_rw = screenWidth;
        prev_rh = screenHeight;

        layoutParam = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, prev_rh);
        layoutParam.topMargin = (int) (1.0 * bg_screen_by * screenHeight / bg_height);
        //layoutParam.leftMargin = (int) (1.0 * bg_screen_bx * screenWidth / (bg_width * 5));
        Log.d("MIKE", "Left Margin: " + (int) (1.0 * bg_screen_bx * screenWidth / (bg_width * 5)));

        cameraDevice = Camera.open();
        Log.i(LOG_TAG, "cameara open");
        cameraView = new CameraView(this, cameraDevice);
        topLayout.addView(cameraView, layoutParam);
        */

        LinearLayout layoutCameraView = (LinearLayout) findViewById(R.id.recorder_layout_CameraView);
        cameraDevice = Camera.open();
        cameraView = new CameraView(this, cameraDevice);
        ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        layoutCameraView.setPadding(50, 10, 50, 10);
        layoutCameraView.addView(cameraView, layoutParams);

        Log.i(LOG_TAG, "cameara preview start: OK");
    }

    //---------------------------------------
    // initialize ffmpeg_recorder
    //---------------------------------------
    private void initRecorder() {

        Log.w(LOG_TAG, "init recorderForStreaming");

        if (RECORD_LENGTH > 0) {
            imagesIndex = 0;
            images = new Frame[RECORD_LENGTH * frameRate];
            timestamps = new long[images.length];
            for (int i = 0; i < images.length; i++) {
                images[i] = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 2);
                timestamps[i] = -1;
            }
        } else if (yuvImage == null) {
            yuvImage = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 2);
            Log.i(LOG_TAG, "create yuvImage");
        }

        User user = User.getUserFromSharedPreferences(this);
        //ffmpeg_streaming_link += user.getAccessCode();

        Log.i(LOG_TAG, "ffmpeg_url: " + ffmpeg_streaming_link + user.getAccessCode());
        recorderForStreaming = new FFmpegFrameRecorder(ffmpeg_streaming_link + user.getAccessCode(), imageWidth, imageHeight, 1);
        recorderForStreaming.setFormat("flv");
        recorderForStreaming.setSampleRate(sampleAudioRateInHz);
        // Set in the surface changed method
        recorderForStreaming.setFrameRate(frameRate);

        ffmpeg_recording_link = new File(Environment.getExternalStorageDirectory(), startRecordTimestamp + ".mp4");
        recorderForArchive = new FFmpegFrameRecorder(ffmpeg_recording_link, imageWidth, imageHeight, 1);
        recorderForArchive.setFormat("mp4");
        recorderForArchive.setSampleRate(sampleAudioRateInHz);
        // Set in the surface changed method
        recorderForArchive.setFrameRate(frameRate);
        recorderForArchive.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        //recorderForArchive.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
        recorderForArchive.setTimestamp(Calendar.getInstance().getTimeInMillis());

        // The filterString  is any ffmpeg filter.
        // Here is the link for a list: https://ffmpeg.org/ffmpeg-filters.html
        filterString = "transpose=0";
        filter = new FFmpegFrameFilter(filterString, imageWidth, imageHeight);

        //default format on android
        filter.setPixelFormat(avutil.AV_PIX_FMT_NV21);

        Log.i(LOG_TAG, "recorderForStreaming initialize success");

        audioRecordRunnable = new AudioRecordRunnable();
        Log.d(LOG_TAG, "a");
        audioThread = new Thread(audioRecordRunnable);
        Log.d(LOG_TAG, "b");
        runAudioThread = true;
        Log.d(LOG_TAG, "c");
    }


    private CountDownTimer archiveTimer = new CountDownTimer(20000, 1000) {
        @Override
        public void onTick(long millisUntilFinished) {
            archiveTimerStarted = true;
            Log.d(LOG_TAG, "Timer Tick");
        }

        @Override
        public void onFinish() {
            /*
            Uri archiveUri = Uri.fromFile(ffmpeg_recording_link);

            File archiveFile = new File(archiveUri.getPath());
            */

            Log.d(LOG_TAG, "Timer Finish");

            /*
            UploadVideoTask uploadVideoTask = new UploadVideoTask(RecordActivity.this, Constants.SERVER_URL, new UploadVideoTask.UploadVideoTaskEventListener() {
                @Override
                public void onUploadSuccess() {

                }

                @Override
                public void onUploadFailed(String errorMessage) {

                }
            });

            uploadVideoTask.executeOnExecutor(AsyncTask.SERIAL_EXECUTOR, new File[]{ffmpeg_recording_link});
            */

            if (recording)
                archiveTimer.start();

        }
    };

    private long startRecordTimestamp;

    public void startRecording() {

        Log.d(LOG_TAG, "1");

        startRecordTimestamp = Calendar.getInstance().getTimeInMillis();

        initRecorder();

        /*
        try {
            Log.d(LOG_TAG,"1");
            recorderForStreaming.start();
            recorderForArchive.start();
            Log.d(LOG_TAG,"2");
            startTime = System.currentTimeMillis();
            Log.d(LOG_TAG,"3");
            audioThread.start();
            Log.d(LOG_TAG,"4");
            recording = true;
            if (addFilter) {
                filter.start();
            }

        } catch (FFmpegFrameRecorder.Exception | FrameFilter.Exception e) {
            e.printStackTrace();
            recording = false;
        }
        */

        AsyncTask.execute(new Runnable() {
            @Override
            public void run() {
                //TODO your background code

                try {
                    Log.d(LOG_TAG, "1");
                    recorderForStreaming.start();
                    recorderForArchive.start();
                    Log.d(LOG_TAG, "2");
                    startTime = System.currentTimeMillis();
                    Log.d(LOG_TAG, "3");
                    audioThread.start();
                    Log.d(LOG_TAG, "4");
                    recording = true;
                    if (addFilter) {
                        filter.start();
                    }

                } catch (FFmpegFrameRecorder.Exception | FrameFilter.Exception e) {
                    e.printStackTrace();
                    recording = false;
                }

            }
        });


        //initMediaRecorder();
    }

    public void stopRecording() {

//        AsyncTask.execute(new Runnable() {
//
//            public void run() {

        Log.d(LOG_TAG, "stop recording");

        runAudioThread = false;
        try

        {
            audioThread.join();
            Log.d(LOG_TAG, "audioThread.join()");
        } catch (
                InterruptedException e
                )

        {
            // reset interrupt to be nice
            Thread.currentThread().interrupt();
            e.printStackTrace();
            Log.d(LOG_TAG, "InterruptedException");
            return;
        }

        audioRecordRunnable = null;
        audioThread = null;

        if (recorderForStreaming != null && recording) {
            AsyncTask.execute(new Runnable() {

                public void run() {
                    if (RECORD_LENGTH > 0) {
                        Log.v(LOG_TAG, "Writing frames");
                        try {
                            int firstIndex = imagesIndex % samples.length;
                            int lastIndex = (imagesIndex - 1) % images.length;
                            if (imagesIndex <= images.length) {
                                firstIndex = 0;
                                lastIndex = imagesIndex - 1;
                            }
                            if ((startTime = timestamps[lastIndex] - RECORD_LENGTH * 1000000L) < 0) {
                                startTime = 0;
                            }
                            if (lastIndex < firstIndex) {
                                lastIndex += images.length;
                            }
                            for (int i = firstIndex; i <= lastIndex; i++) {
                                long t = timestamps[i % timestamps.length] - startTime;
                                if (t >= 0) {
                                    if (t > recorderForStreaming.getTimestamp()) {
                                        recorderForStreaming.setTimestamp(t);
                                        recorderForArchive.setTimestamp(t);
                                    }
                                    recorderForStreaming.record(images[i % images.length]);
                                    recorderForArchive.record(images[i % images.length]);
                                }
                            }

                            firstIndex = samplesIndex % samples.length;
                            lastIndex = (samplesIndex - 1) % samples.length;
                            if (samplesIndex <= samples.length) {

                                firstIndex = 0;
                                lastIndex = samplesIndex - 1;
                            }
                            if (lastIndex < firstIndex) {
                                lastIndex += samples.length;
                            }
                            for (int i = firstIndex; i <= lastIndex; i++) {
                                recorderForStreaming.recordSamples(samples[i % samples.length]);
                                recorderForArchive.recordSamples(samples[i % samples.length]);
                            }
                        } catch (FFmpegFrameRecorder.Exception e) {
                            Log.v(LOG_TAG, e.getMessage());
                            e.printStackTrace();
                        }
                    }
                }
            });

            recording = false;
            Log.v(LOG_TAG, "Finishing recording, calling stop and release on recorderForStreaming");

            AsyncTask.execute(new Runnable() {

                public void run() {

                    try {
                        recorderForStreaming.stop();
                        recorderForStreaming.release();
                        recorderForArchive.stop();
                        recorderForArchive.release();
                        filter.stop();
                        filter.release();
                    } catch (Exception e /*FFmpegFrameRecorder.Exception | FrameFilter.Exception e*/) {
                        e.printStackTrace();
                    }

                    isClicked = false;
                    RecordActivity.this.runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            btnRecorderControl.setEnabled(true);

                            UploadVideoTask uploadVideoTask = new UploadVideoTask(RecordActivity.this, Constants.SERVER_URL, new UploadVideoTask.UploadVideoTaskEventListener() {
                                @Override
                                public void onUploadSuccess() {

                                }

                                @Override
                                public void onUploadFailed(String errorMessage) {

                                }
                            });

                            uploadVideoTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, new File[]{ffmpeg_recording_link});

                        }
                    });

                    recorderForStreaming = null;
                    recorderForArchive = null;

                }
            });


        }

//            }
//        });
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {

        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if (recording) {
                stopRecording();
            }

            finish();

            return true;
        }

        return super.onKeyDown(keyCode, event);
    }


    //---------------------------------------------
    // audio thread, gets and encodes audio data
    //---------------------------------------------
    class AudioRecordRunnable implements Runnable {

        @Override
        public void run() {
            android.os.Process.setThreadPriority(android.os.Process.THREAD_PRIORITY_URGENT_AUDIO);

            // Audio
            int bufferSize;
            ShortBuffer audioData;
            int bufferReadResult;

            bufferSize = AudioRecord.getMinBufferSize(sampleAudioRateInHz,
                    AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT);
            audioRecord = new AudioRecord(MediaRecorder.AudioSource.MIC, sampleAudioRateInHz,
                    AudioFormat.CHANNEL_IN_MONO, AudioFormat.ENCODING_PCM_16BIT, bufferSize);

            if (RECORD_LENGTH > 0) {
                samplesIndex = 0;
                samples = new ShortBuffer[RECORD_LENGTH * sampleAudioRateInHz * 2 / bufferSize + 1];
                for (int i = 0; i < samples.length; i++) {
                    samples[i] = ShortBuffer.allocate(bufferSize);
                }
            } else {
                audioData = ShortBuffer.allocate(bufferSize);
            }

            Log.d(LOG_TAG, "audioRecord.startRecording()");
            audioRecord.startRecording();

            /* ffmpeg_audio encoding loop */
            while (runAudioThread) {
                if (RECORD_LENGTH > 0) {
                    audioData = samples[samplesIndex++ % samples.length];
                    audioData.position(0).limit(0);
                }
                Log.v(LOG_TAG, "recording? " + recording);
                bufferReadResult = audioRecord.read(audioData.array(), 0, audioData.capacity());
                audioData.limit(bufferReadResult);
                if (bufferReadResult > 0) {
                    Log.v(LOG_TAG, "bufferReadResult: " + bufferReadResult);
                    // If "recording" isn't true when start this thread, it never get's set according to this if statement...!!!
                    // Why?  Good question...
                    if (recording) {
                        if (RECORD_LENGTH <= 0) try {
                            recorderForStreaming.recordSamples(audioData);
                            recorderForArchive.recordSamples(audioData);
                            //Log.v(LOG_TAG,"recording " + 1024*i + " to " + 1024*i+1024);
                        } catch (FFmpegFrameRecorder.Exception e) {
                            Log.v(LOG_TAG, e.getMessage());
                            e.printStackTrace();
                        }
                    }
                }
            }
            Log.v(LOG_TAG, "AudioThread Finished, release audioRecord");

            /* encoding finish, release recorderForStreaming */
            if (audioRecord != null) {
                audioRecord.stop();
                audioRecord.release();
                audioRecord = null;
                Log.v(LOG_TAG, "audioRecord released");
            }
        }
    }

    //---------------------------------------------
    // camera thread, gets and encodes video data
    //---------------------------------------------
    class CameraView extends SurfaceView implements SurfaceHolder.Callback, Camera.PreviewCallback {

        private SurfaceHolder mHolder;
        private Camera mCamera;

        public CameraView(Context context, Camera camera) {
            super(context);
            Log.w("camera", "camera view");
            mCamera = camera;
            mHolder = getHolder();
            mHolder.addCallback(CameraView.this);
            mHolder.setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS);
            mCamera.setPreviewCallback(CameraView.this);
        }

        @Override
        public void surfaceCreated(SurfaceHolder holder) {
            try {
                stopPreview();
                mCamera.setPreviewDisplay(holder);
            } catch (IOException exception) {
                mCamera.release();
                mCamera = null;
            }
        }

        public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
            stopPreview();

            Camera.Parameters camParams = mCamera.getParameters();
            List<Camera.Size> sizes = camParams.getSupportedPreviewSizes();
            // Sort the list in ascending order
            Collections.sort(sizes, new Comparator<Camera.Size>() {

                public int compare(final Camera.Size a, final Camera.Size b) {
                    return a.width * a.height - b.width * b.height;
                }
            });

            // Pick the first preview size that is equal or bigger, or pick the last (biggest) option if we cannot
            // reach the initial settings of imageWidth/imageHeight.
            /*
            for (int i = 0; i < sizes.size(); i++) {
                if ((sizes.get(i).width >= imageWidth && sizes.get(i).height >= imageHeight) || i == sizes.size() - 1) {
                    imageWidth = sizes.get(i).width;
                    imageHeight = sizes.get(i).height;
                    Log.v(LOG_TAG, "Changed to supported resolution: " + imageWidth + "x" + imageHeight);
                    break;
                }
            }
            */

            imageWidth = sizes.get(sizes.size() - 1).width;
            imageHeight = sizes.get(sizes.size() - 1).height;

            camParams.setPreviewSize(imageWidth, imageHeight);

            Log.v(LOG_TAG, "Setting imageWidth: " + imageWidth + " imageHeight: " + imageHeight + " frameRate: " + frameRate);

            camParams.setPreviewFrameRate(frameRate);
            Log.v(LOG_TAG, "Preview Framerate: " + camParams.getPreviewFrameRate());

            mCamera.setParameters(camParams);

            // Set the holder (which might have changed) again
            try {
                mCamera.setPreviewDisplay(holder);
                mCamera.setPreviewCallback(CameraView.this);
                startPreview();
            } catch (Exception e) {
                Log.e(LOG_TAG, "Could not set preview display in surfaceChanged");
            }
        }

        @Override
        public void surfaceDestroyed(SurfaceHolder holder) {
            try {
                mHolder.addCallback(null);
                mCamera.setPreviewCallback(null);
            } catch (RuntimeException e) {
                // The camera has probably just been released, ignore.
            }
        }

        public void startPreview() {
            if (!isPreviewOn && mCamera != null) {
                isPreviewOn = true;
                mCamera.startPreview();
            }
        }

        public void stopPreview() {
            if (isPreviewOn && mCamera != null) {
                isPreviewOn = false;
                mCamera.stopPreview();
            }
        }

        @Override
        public void onPreviewFrame(byte[] data, Camera camera) {
            if (audioRecord == null || audioRecord.getRecordingState() != AudioRecord.RECORDSTATE_RECORDING) {
                startTime = System.currentTimeMillis();
                return;
            }
            if (RECORD_LENGTH > 0) {
                int i = imagesIndex++ % images.length;
                yuvImage = images[i];
                timestamps[i] = 1000 * (System.currentTimeMillis() - startTime);
            }


            /* get video data */
            if (yuvImage != null && recording) {
                ((ByteBuffer) yuvImage.image[0].position(0)).put(data);

                if (RECORD_LENGTH <= 0)
                    try {

                        Log.d(LOG_TAG, "archiveTimerStarted: " + archiveTimerStarted);
                        if (!archiveTimerStarted) {
                            Log.d(LOG_TAG, "!archiveTimerStarted: ");
                            //initMediaRecorder();
                            archiveTimer.start();
                            archiveTimerStarted = true;
                        }

                        isClicked = false;
                        btnRecorderControl.setEnabled(true);

                        Log.v(LOG_TAG, "Writing Frame");
                        long t = 1000 * (System.currentTimeMillis() - startTime);
                        if (t > recorderForStreaming.getTimestamp()) {
                            recorderForStreaming.setTimestamp(t);
                            recorderForArchive.setTimestamp(t);
                        }

                        if (addFilter) {
                            filter.push(yuvImage);
                            Frame frame2;
                            while ((frame2 = filter.pull()) != null) {
                                recorderForStreaming.record(frame2);
                                recorderForArchive.record(frame2);
                            }
                        } else {
                            recorderForStreaming.record(yuvImage);
                            recorderForArchive.record(yuvImage);
                        }


                    } catch (FFmpegFrameRecorder.Exception | FrameFilter.Exception e) {
                        Log.v(LOG_TAG, e.getMessage());
                        e.printStackTrace();
                    }
            }
        }
    }

    private ProgressDialog progressDialog;

    private void showProgressDialog(String message) {

        if (progressDialog != null && progressDialog.isShowing())
            progressDialog.dismiss();

        progressDialog = new ProgressDialog(this);
        progressDialog.setMessage("Loading...");
        progressDialog.setIndeterminate(false);
        progressDialog.setCancelable(false);

    }

    private void hideProgressDialog() {
        if (progressDialog != null)
            if (progressDialog.isShowing())
                progressDialog.dismiss();
    }


    private boolean isClicked = false;

    @Override
    public void onClick(View v) {

        Log.d(LOG_TAG, "onClick: recording: " + recording);

        btnRecorderControl.setEnabled(false);

        SendStreamCommandToServerTask sendStreamCommandToServerTask =
                new SendStreamCommandToServerTask(RecordActivity.this, new SendStreamCommandToServerTask.SendStreamCommandToServerEventListener() {
                    @Override
                    public void onSendSuccess() {

                    }

                    @Override
                    public void onSendFailed() {

                    }
                });

        User user = User.getUserFromSharedPreferences(RecordActivity.this);

        if (!isClicked) {
            Log.d(LOG_TAG, "Clicked");
            isClicked = true;
            if (!recording) {
                sendStreamCommandToServerTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, new String[]{user.getAccessCode(), "start"});
                startRecording();
                btnRecorderControl.setText("Stop");
                tvStreaming.setVisibility(View.VISIBLE);
            } else {

                sendStreamCommandToServerTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR, new String[]{user.getAccessCode(), "stop"});

                // This will trigger the audio recording loop to stop and then set isRecorderStart = false;
                stopRecording();
                Log.w(LOG_TAG, "Stop Button Pushed");
                btnRecorderControl.setText("Start");
                tvStreaming.setVisibility(View.GONE);
            }
        }
    }
}`

**Comment by saudet** [comment]
Since you're recording in different formats, the following can't possibly work properly:
```java
                    if (t > recorderForStreaming.getTimestamp()) {
                        recorderForStreaming.setTimestamp(t);
                        recorderForArchive.setTimestamp(t);
                    }
```
Do those separately as well.
