### ISSUE TITLE
Clarification: FFmpegFrameRecorder & hardware acceleration

### ISSUE THREAD

**Issue by JAB0** [bytedeco/javacv#693]
Hi all,

I need some clarification about FFmpegFrameRecorder & hardware acceleration.
In some topics/blogs/forums I read that FFmpegFrameRecorder supported hardware acceleration.
And now I am little bit confused! Because in this  topic Mr. Samuel Audet said (2016)

"https://github.com/bytedeco/javacv/issues/340"

"Unfortunately, FFmpeg doesn't support hardware acceleration in any meaningful way, so try the "ultrafast"

Is this still the case?

Thank you very much in advance for your answer.
Jabo

**Comment by saudet** [comment]
Yes, this is still the case. There is already a discussion about this at https://github.com/bytedeco/javacpp-presets/issues/389 so marking this as a duplicate.
