### ISSUE TITLE
Serialize a Mat for network transport

### ISSUE THREAD

**Issue by DDDFan** [bytedeco/javacv#697]
Hey, i´ve got a question because there seems to no official and easy way. 

I want to serialize Frames or Mats to Bytes or however to transport them to another pc. I have an Akka-Application which gets the stream from the webcam and publishes it using the mediator (pub-sub). Now i want the send the video to multiple "clients" in the cluster.

Any idea for an easy way?

Thanks in advance!

**Comment by saudet** [comment]
If they are images, encode them as image files...

**Comment by linzuk** [comment]
but..  Mat maybe not an image. it could be image feature extract by sift and orb:

public static Mat extract(String src) {
        ORB orb = ORB.create();
        Mat img = imread(src);
        KeyPointVector kp = new KeyPointVector();
        orb.detect(img, kp);
        Mat des = new Mat();
        orb.compute(img, kp, des);
        return des;
    }

i wanna to storage many image features. than i can search image by match similar image feature:

public static float match(Mat des1, Mat des2) {
        BFMatcher bf = new BFMatcher();
        DMatchVector matches = new DMatchVector();
        bf.match(des1, des2, matches);
        float score = 0;
        for (long i = 0; i < matches.size(); i++) {
            DMatch match = matches.get(i);
            score += 500 - match.distance();
        }
        return score;
    }

so. how can i Serialize Mat for it ? in python, the des is not Mat, its 2D-array, It's easy to save feature.

**Comment by saudet** [comment]
OpenCV has `FileStorage` for that kind of thing:
http://docs.opencv.org/2.4/modules/core/doc/xml_yaml_persistence.html

**Comment by linzuk** [comment]
FileStorage seems that not support db?

**Comment by saudet** [comment]
You mean in memory serialization? Yes it does support that:
http://docs.opencv.org/2.4/modules/core/doc/xml_yaml_persistence.html#filestorage-filestorage

**Comment by linzuk** [comment]
thankyou, i got it, my english is pool  : )
