### ISSUE TITLE
How to understand JavaCV?

### ISSUE THREAD

**Issue by torrtuga** [bytedeco/javacv#699]
Since this library is built as a wrapper, so people use it for certain specific uses. So if I am working on this library then how should I read about the various APIs provided as there is no documentation.

Say, I want to implement Bilateral Filtering, then how to know the way it can be done using JavaCV, so the approach is what I am looking for?
Thanks in advance.

**Comment by saudet** [comment]
OpenCV does have an implementation of the bilateral filter and documentation is available here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_imgproc.html#bilateralFilter-org.bytedeco.javacpp.opencv_core.Mat-org.bytedeco.javacpp.opencv_core.Mat-int-double-double-int-
Does that answer your question?

**Comment by torrtuga** [comment]
I think I might not have been clear with my wording. I am not facing problem with openCV documentation but since I am using JavaCV I need to know which API of JAVACV to use. I know there is no documentation and whatever is there in openCV should be available in JavaCV also but how to find the connection.

Like as you provided the documentation for bilateral filtering in openCV then which API of JavaCV to use for this?
PS : My question is not about a particular type of filter etc but in general how to find a particular thing which can be done in openCV then what is the API for that thing in JavaCV.

**Comment by saudet** [comment]
I just gave you the API documentation for the wrapper of OpenCV here:
http://bytedeco.org/javacpp-presets/opencv/apidocs
And the one for JavaCPP itself to understand all the types:
http://bytedeco.org/javacpp/opencv/
What more are you looking for?

**Comment by torrtuga** [comment]
Okay, so JavaCV does have a documentation :: http://bytedeco.org/javacpp-presets/opencv/apidocs/
