### ISSUE TITLE
JavaCV - Can't manipulate camera resolution 

### ISSUE THREAD

**Issue by benjak135765** [bytedeco/javacv#709]
int captureWidth = 1280;
int captureHeight = 720;
	 
OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(WEBCAM_DEVICE_INDEX);
grabber.setImageWidth(captureWidth);
grabber.setImageHeight(captureHeight);
grabber.start();
System.out.println(grabber.getImageWidth()+"*"+grabber.getImageHeight());
//============================================
The resolution is always 640x480

**Comment by saudet** [comment]
Use FFmpegFrameGrabber (or VideoInputFrameGrabber on Windows).

**Comment by benjak135765** [comment]
thx
