### ISSUE TITLE
Obtain sdp file

### ISSUE THREAD

**Issue by salvo19881** [bytedeco/javacv#710]
Hello, 
I'm trying to send my webcam video (in real time) to upnp server. 
I need one link with sdp file, but , i don't know how i can make this one,
i try with this code
`recorder = new FFmpegFrameRecorder("rtp://192.168.88.241:5004/name.mpeg4", CAPTUREWIDTH, CAPTUREHRIGHT);
                        recorder.setInterleaved(false);
                        
                        // video options //
                        recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
                        recorder.setVideoBitrate(1024);
                        recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG2VIDEO);
                        recorder.setFormat("mpeg4");`
and vlc strem work fine, dlna client no.
I try to read (with dlna client) one strem made from app on my android phone, and with http://url.fil.sdp work.

**Comment by saudet** [comment]
Does it work with the ffmpeg command line program?

**Comment by salvo19881** [comment]
Honestly? no, i hoped to create sdp from code. 
anyway, i solved making sdp, file manualy.
Thanks

**Comment by saudet** [comment]
It looks like what you need is this function:
http://bytedeco.org/javacpp-presets/ffmpeg/apidocs/org/bytedeco/javacpp/avformat.html#av_sdp_create(org.bytedeco.javacpp.PointerPointer,%20int,%20org.bytedeco.javacpp.BytePointer,%20int)

If you could enhance FFmpegFrameRecorder with that, it would be great!

**Comment by salvo19881** [comment]
I've seen it but i don't know where find the parameters.
In this moment i'm ok with manual sdp, but i'll try this. 
Thanks for answer ;)

**Comment by salvo19881** [comment]
Nothing, the sdp that 2 days ago worked, now don't work.
So i think is time to learn how i can make this file.
I tried  with av_sdp_create but i don't kwon how i can convert my FFmpegrecorder to avformatcontex or Pointer.
Can somebody show my how i can made sdp file, it's ok too command line.
My recorder setting  are 
`recorder = new FFmpegFrameRecorder("rtp://localip:port/test.sdp", CAPTUREWIDTH, CAPTUREHRIGHT);
                        recorder.setInterleaved(true);
                        // video options //
                        recorder.setVideoOption("tune", "zerolatency");
                        recorder.setVideoOption("preset", "ultrafast");
                        recorder.setVideoOption("crf", "30");
                        recorder.setVideoBitrate(150000);
                        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
                        recorder.setFormat("rtp");
                        recorder.setFrameRate(FRAME_RATE);
                        recorder.setGopSize(GOP_LENGTH_IN_FRAMES);
                        //AudioOption
                        recorder.setAudioBitrate(8 * 1000);
//recorder.setAudioChannels(1);
                        recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
                        recorder.setSampleRate(44100)`

**Comment by saudet** [comment]
It's inside FFmpegFrameRecorder. We'll need to modify it.

**Comment by salvo19881** [comment]
O_O I'm stupid.
Solved with a getter for AVFormatContext.
Now i can't create url to send this file, but it's off topic.
Thank for all
I write code if somebody need it
`ByteBuffer bbuf = ByteBuffer.allocate(1000);
 File file = new File("test.sdp");
 AVFormatContext av=new AVFormatContext(); 
 avformat.av_sdp_create(recorder.getOc(),2, bbuf, 1000);
 FileChannel wChannel = new FileOutputStream(file, false).getChannel();
 wChannel.write(bbuf);
 wChannel.close();`

where recorder.getOc() is a getter in FFMpegFrameRecorder

**Comment by salvo19881** [comment]
I need more help.
I send sdp file in other pc, but don't work.
`v=0
o=- 0 0 IN IP4 192.168.88.241
s=No Name
t=0 0
a=tool:libavformat 57.56.100
m=video 5056 RTP/AVP 96
c=IN IP4 192.168.88.241
b=AS:150
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1`

this is my file.sdp. it works in my machine(where i record video from webcam) but not in other pc.
I change c=IN IP4 192.168.88.241 with  other pc's ip

**Comment by salvo19881** [comment]
ok i run this
`ffmpeg -f dshow -i video="HP Truevision HD":audio="Array microfono interno (IDT High Definition Audio CODEC)"  -vcodec libx264 -preset ultrafast -tune zerolatency -r 10 -async 1 -acodec libmp3lame -ab 24k -ar 22050 -bsf:v h264_mp4toannexb -maxrate 750k -bufsize 3000k -f mulaw -f rtp rtp://127.0.0.1:1234`

and i've the error 'Only one stream supported in the RTP muxer
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1'
if try without :audio="Array microfono interno (IDT High Definition Audio CODEC) it work.

**Comment by teocci** [comment]
@salvo19881 how did you inset the destination IP in the FFmpegFrameRecoder??
