### ISSUE TITLE
AndroidFrameConverter 

### ISSUE THREAD

**Issue by zhengbin1015** [bytedeco/javacv#713]
I am trying to convert a Frame of size 1280x720 into Bitmap using javacv AndroidFrameConverter and it takes long time to convert. Here is the sample code of converting.
FrameGrabber grabber = new FFmpegFrameGrabber(videoUrl);
frame = grabber.grab();
AndroidFrameConverter converter = new AndroidFrameConverter();
Bitmap originalBitmap = converter.convert(frame);
is there any other solution which is faster than this?

**Comment by saudet** [comment]
Try to use FFmpeg to convert to RGBA.

**Comment by saudet** [comment]
Duplicate of #214.
