### ISSUE TITLE
Segmentation fault in embedded libgomp

### ISSUE THREAD

**Issue by dalsh** [bytedeco/javacv#716]
Hi,

I had an issue similar to #436 after packaging my app, which was running fine on windows, into a docker image.

The Unsatisfied link error is now resolved but I am now encountering the following segmentation fault when running my app :
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe50a1538ee, pid=7, tid=0x00007fe56b1a4ae8
#
# JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.4.0
# Distribution: Custom build (Tue May 30 16:19:39 GMT 2017)
# Problematic frame:
# C  [libgomp.so.1+0x68ee]  omp_get_max_threads+0x1e
#
# Core dump written. Default location: //core or core.7
#
# An error report file with more information is saved as:
# //hs_err_pid7.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

What I've done is replace my `javacv:1.2` by `javacv-platform:1.3.2` in my pom. I'm building and running everything using the same jdk (docker image `maven:3.5-jdk-8-alpine`) I'm probably missing something here, please tell me if I can provide any more information

**Comment by saudet** [comment]
Try to use the libgomp.so that comes with your distro instead of the one
bundled.

**Comment by dalsh** [comment]
Thank you for your answer. We have switched from alpine to debian and it is now working.

**Comment by saudet** [comment]
Ah yes, the Alpine build of OpenJDK is known to be quite buggy.
