### ISSUE TITLE
FFmpegFrameFilter doesn't work for "fps" filter

### ISSUE THREAD

**Issue by d-a-gerashenko** [bytedeco/javacv#717]
I need constant output frame rate.

**In command line it looks like this:**

	"ffmpeg.exe" -i "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov" -r 5 "file.mp4"

Or this (https://ffmpeg.org/ffmpeg-filters.html#fps-1):

	"ffmpeg.exe" -i "rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov" -vf "fps=fps=5" "file.mp4"

In both cases it works fine.

**JavaCV**
Using of `recorder.setFrameRate(5)` makes output video slow. It doesn't convert FPS but uses the same frames for new FPS rate.
FFmpegFrameFilter with "fps=fps=25", "fps=fps=10", "fps=10" returns only null values.
For "transpose=0" FFmpegFrameFilter works fine.

	import org.bytedeco.javacv.FFmpegFrameFilter;
	import org.bytedeco.javacv.FFmpegFrameGrabber;
	import org.bytedeco.javacv.Frame;

	/**
	 *
	 * @author Dmitriy Gerashenko <d.a.gerashenko@gmail.com>
	 */
	public class Example {

		public static void main(String[] args) throws Exception {
			FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov");
			grabber.start();

	//        String filters = "transpose=0";
			String filters = "fps=fps=10";
			FFmpegFrameFilter filter = new FFmpegFrameFilter(filters, grabber.getImageWidth(), grabber.getImageHeight());
			filter.setPixelFormat(grabber.getPixelFormat());
			filter.setAspectRatio(grabber.getAspectRatio());
			filter.setFrameRate(grabber.getFrameRate());
			filter.start();

			Frame frame;
			while ((frame = grabber.grab()) != null) {
				if (frame.image != null) {
					filter.push(frame);
					if (filter.pull() != null) {
						System.out.println("It works!!!");
						System.exit(0);
					}
				}
				System.out.println("type: " + ((frame.image == null) ? "audio" : "video"));
				System.out.println("timestamp: " + grabber.getTimestamp());
				System.out.println("frameNumber: " + grabber.getFrameNumber());
				System.out.println("keyFrame: " + frame.keyFrame);
				System.out.println("************");
			}
			filter.stop();
			filter.release();
			grabber.stop();
			grabber.release();
		}
	}

**Comment by saudet** [comment]
That's kind of expected, the frames that we input into FFmpegFrameRecorder are the ones we want to save. Simply drop any that you do not want.

That the `fps` filter doesn't work is probably a bug though. We'll need to dig into the ffmpeg command line program to figure out how to handle this.

**Comment by d-a-gerashenko** [comment]
> Simply drop any that you do not want.

I started from this but then supposed that there is an easier way.

For dropping or duplication frames we need to know which of them to drop or duplicate. We should take more suitable frames according to timestamps but image frames are not (or not always) sorted by timestamps.

    private static void singleTest() throws Exception {
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov");
        grabber.start();
        FrameRecorder recorder = new FFmpegFrameRecorder("file.mp4", grabber.getImageWidth(), grabber.getImageHeight());
        recorder.setFormat("mp4");
        recorder.setAudioChannels(1);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
        recorder.setFrameRate(5);
        recorder.start();
        Frame frame;
        while ((frame = grabber.grabImage()) != null) {
            System.out.println("type: " + ((frame.image == null) ? "audio" : "video"));
            System.out.println("timestamp: " + grabber.getTimestamp());
            System.out.println("frameNumber: " + grabber.getFrameNumber());
            System.out.println("keyFrame: " + frame.keyFrame);
            System.out.println("************");
        }
    }

Output:

	type: video
	timestamp: 250333
	frameNumber: 6
	keyFrame: true
	************
	type: video
	timestamp: 42000
	frameNumber: 1
	keyFrame: false
	************
	type: video
	timestamp: 83000
	frameNumber: 1
	keyFrame: false
	************
	type: video
	timestamp: 125000
	frameNumber: 3
	keyFrame: false
	************
	type: video
	timestamp: 167000
	frameNumber: 4
	keyFrame: false
	************
	type: video
	timestamp: 208000
	frameNumber: 4
	keyFrame: false
	************

My simplest aproach was to:
1. Skip frames with outdated timestamps.
2. Filter frames by timestamp suitability if output FPS is lower.
3. Duplicate sutable frames if output FPS is grater.

Is works but of course not very well. Some video frames have visual defects.

**Comment by saudet** [comment]
Yes, I understand the use case. The `-r` option probably uses the `fps` filter. Like I said, someone will have to take a look at the source code and do something similar in JavaCV.

**Comment by SilenceMrWang** [comment]
//what I'm doing to control the number of frames per second is to add a counter of the frames . 
int framesPerSecond = (int)grabber.getFrameRate(); // my rtsp stream rate is 25 frames per second
int count = 0;
Frame frame;
while (!exit) {
            if (count++ % framesPerSecond != 0) {
                grabber.grabImage();  //this func must be used.
                continue;
            }
            frame = grabber.grabImage();

            //here I would like to use some function to process frames
        }

**Comment by d-a-gerashenko** [comment]
Does your code convert 25fps to 1fps? Am I wrong?

I use this:

    @Override
    public Frame grab() throws FrameGrabber.Exception {
        Frame grabbedFrame;
        Frame outFrame;
        while (true) {
            grabbedFrame = simplifiedGrabber.grab();
            if (grabbedFrame == null) {
                return null;
            }
            if (grabbedFrame.image != null) {
                if (grabbedFrame.timestamp >= timestamp) {
                    if (mat != null) {
                        mat.release();
                    }
                    mat = matConverter.convert(grabbedFrame);
                    outFrame = matConverter.convert(mat);
                    outFrame.timestamp = timestamp;
                    outFrame.keyFrame = true;
                    timestamp += Math.round(1000000 / fps);
                } else {
                    continue;
                }
            } else {
                outFrame = grabbedFrame;
            }
            return outFrame;
        }

    }

**Comment by d-a-gerashenko** [comment]
FFmpegFrameFilter doesn't do it. But it could be walked around with the code above.

**Comment by saudet** [comment]
No, not yet, but contributions welcome! Where do you feel we should put
that list?

**Comment by saudet** [comment]
BTW, this might be caused by a missing `setpts=N` filter in the graph. Please try with JavaCV 1.4.2-SNAPSHOT to see if it makes a difference with commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a.

**Comment by laosijikaichele** [comment]
I use following code to control the number of frames per second: @d-a-gerashenko @saudet 
```
// original input frame rate
double inputFrameRate = grabber.getFrameRate();  
// number of frames per second
double outputFrameRate = 10; 
double dropFrameStep = inputFrameRate / outputFrameRate;
double dropFrameStepInner = dropFrameStep;
int frameCounter = 0;
while(true) {
    // inputFrameRate > outputFrameRate
    if(dropFrameStep > 1) { 
        ++frameCounter;
        if (dropFrameStepInner - frameCounter >= 0 && dropFrameStepInner - frameCounter < 1) {
            double dropFrameStepInnerDecimal = dropFrameStepInner - (long) dropFrameStepInner;
            dropFrameStepInner = frameCounter + dropFrameStep + dropFrameStepInnerDecimal;
            // handle overflow
            if(dropFrameStepInner >= Integer.MAX_VALUE) {
                dropFrameStepInner = dropFrameStep + dropFrameStepInnerDecimal;
                frameCounter = 0;
            }
        } else {
            // drop frame
            continue;
        }
    }
}
```

**Comment by GeneralLHW** [comment]
> if(dropFrameStep > 1) { 
>         ++frameCounter;
>         if (dropFrameStepInner - frameCounter >= 0 && dropFrameStepInner - frameCounter < 1) {
>             double dropFrameStepInnerDecimal = dropFrameStepInner - (long) dropFrameStepInner;
>             dropFrameStepInner = frameCounter + dropFrameStep + dropFrameStepInnerDecimal;
>             // handle overflow
>             if(dropFrameStepInner >= Integer.MAX_VALUE) {
>                 dropFrameStepInner = dropFrameStep + dropFrameStepInnerDecimal;
>                 frameCounter = 0;
>             }
>             // process frames...
>         } else {
>             // drop frame
>             continue;
>         }
>     }

This does not solve the problem. First, the length of the video is compressed, and then the audio is played very fast, so this is not possible

**Comment by saudet** [comment]
@GeneralLHW confirmed that the `fps` filter now works just fine with recent versions of JavaCV, see https://github.com/bytedeco/javacv/issues/1398#issuecomment-613208633 for a working example. Thanks to all for reporting and testing this!
