### ISSUE TITLE
FFmpegFrameRecorder

### ISSUE THREAD

**Issue by zhengbin1015** [bytedeco/javacv#718]
There is a puzzling problem, FFmpegFrameRecorder in only send video to the RTMP service, will delay 10S, is 10S not push flow, such as OpenCVFrameGrabber crawl through each frame, push FFmpegFrameRecorder to the RTMP server through record method, through grasping the flow before the discovery of the 10S not to send

**Comment by saudet** [comment]
Does the same thing happen with the ffmpeg program on the command line? If so, then it is not an issue with JavaCV. Please report upstream.

**Comment by zhengbin1015** [comment]
It is OK to press the following command line
ffmpeg -f dshow -re -i video="USB2.0 PC CAMERA" -vcodec libx264 -preset:v ultrafast -tune:v zerolatency -f flv rtmp://localhost/oflaDemo/livestream

**Comment by saudet** [comment]
Ok, so have you tried to use the same parameters with FFmpegFrameRecorder?

**Comment by zhengbin1015** [comment]
The test code is as follows：      
OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(WEBCAM_DEVICE_INDEX);
            grabber.setImageWidth(captureWidth);
            grabber.setImageHeight(captureHeight);
            grabber.start();
FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(
                    "rtmp://172.18.1.107/oflaDemo/livestream",
                    captureWidth, captureHeight, 2);
recorder.setInterleaved(true);
recorder.setVideoOption("tune", "zerolatency");
recorder.setVideoOption("preset", "ultrafast");
recorder.setVideoOption("crf", "28");
recorder.setVideoBitrate(1000000);
recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
recorder.setVideoQuality(0);
recorder.setFormat("flv");
recorder.setFrameRate(FRAME_RATE);
 recorder.setGopSize(GOP_LENGTH_IN_FRAMES);
recorder.start();

CanvasFrame cFrame = new CanvasFrame("Capture Preview", CanvasFrame.getDefaultGamma() / grabber.getGamma());
 Frame capturedFrame;
while ((capturedFrame = grabber.grabFrame()) != null) {
                if (cFrame.isVisible()) {
                    cFrame.showImage(capturedFrame);
                }
                if (startTime == 0) {
                    startTime = System.currentTimeMillis();
                }
                videoTS = 1000 * (System.currentTimeMillis() - startTime);
                if (videoTS > recorder.getTimestamp()) {
                    recorder.setTimestamp(videoTS);
                }
                System.out.println(new Date());
                recorder.record(capturedFrame);
}

**Comment by saudet** [comment]
So, first try to use FFmpeg to capture from the camera instead of OpenCV,
and let's see what that gives.

**Comment by lsv12** [comment]
the same to you ,  the error info is avio_open2 error() error -5: Could not open 'null'

**Comment by saudet** [comment]
I'm assuming that, instead of OpenCV, using `FFmpegFrameGrabber` to capture from the camera fixed this issue, but if you are still having problems, please let me know.

**Comment by saudet** [comment]
FYI, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
