### ISSUE TITLE
get function of matrix not found

### ISSUE THREAD

**Issue by iberro** [bytedeco/javacv#720]
Mat.get not found in opencv_core.core, what is the alternative?

**Comment by saudet** [comment]
Please try to follow the instructions in the README.md file.

**Comment by saudet** [comment]
I think you want to access data of the Mat? If so, please try to use
indexers:
http://bytedeco.org/news/2014/12/23/third-release/

**Comment by iberro** [comment]
Thank you very much it was useful.
