### ISSUE TITLE
frame.timestamp always is 0

### ISSUE THREAD

**Issue by d-a-gerashenko** [bytedeco/javacv#722]
Is it bug? I have to use this:

    while ((frame = grabber.grab()) != null) {
        frame.timestamp = grabber.getTimestamp();
        System.out.println("frame timestamp is " + frame.timestamp);
    }

**Comment by saudet** [comment]
This is a camera? I think FFmpeg only gives timestamps for streams.

**Comment by d-a-gerashenko** [comment]
The same source as in #712: https://github.com/bytedeco/javacv/pull/712
And the same result for my RTSP cams.
frame.timestamp always is 0

**Comment by saudet** [comment]
Sounds like a limitation of FFmpeg...

**Comment by d-a-gerashenko** [comment]
frame.timestamp is updated if I use this code above. Otherwise it always equals zero. I mean grabber.getTimestamp() works fine.

**Comment by saudet** [comment]
Ah, I see. Someone added that field a while ago, I'm not sure why he didn't also update FFmpegFrameGrabber.

**Comment by nguyenquocchinhdev** [comment]
You can be using grabber.getTimeStamp.
`while ((frame = frameGrabber.grabFrame()) != null) {
                    long presentationTimeUs = frameGrabber.getTimestamp();
                    }
                }`

**Comment by saudet** [comment]
@nguyenquocchinhdev Yes, could you update FFmpegFrameGrabber and send a pull request? It would be much appreciated.

**Comment by saudet** [comment]
Included in newly released version 1.4. Thanks for the contribution!
