### ISSUE TITLE
Rtp error with audio/video stream

### ISSUE THREAD

**Issue by salvo19881** [bytedeco/javacv#724]
I'v other problem. I had open a topic #723 for question to rtsp stream,
Now i 've another problem.
I try to add audio in my videostream.
If i save stream audio/video in mp4 file, i've no problem but if i try to obtain an rtp strem i've this error 
` A fatal error has been detected by the Java Runtime Environment:
 EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffc29955da9, pid=6608, tid=0x0000000000001a20
 JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [avformat-57.dll+0xc5da9]
 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
`

the call of ffmpegframerecorder is the same of "only video" call with audiochannel set.
'recorder = new FFmpegFrameRecorder("rtp://192.168.1.107:5056/prova.mp4", CAPTUREWIDTH, CAPTUREHRIGHT,2);
                      '

**Comment by saudet** [comment]
Does the same thing happen with the `ffmpeg` program on the command line?

**Comment by salvo19881** [comment]
i don't know the command line for record webcam and microphone.

**Comment by salvo19881** [comment]
I try with example file "WebcamAndMicrophoneCapture.java" changing webcamindex and
DEstination output in ffmpegframerecorder with a rtp line
and format with rtp.
i've the same error.
How i can try in command line?

**Comment by saudet** [comment]
Read the docs, this for example:
https://trac.ffmpeg.org/wiki/StreamingGuide

**Comment by salvo19881** [comment]
Update,  
I correct myself. when i try to record to mp4 file, rec only video.
this is my audio thread, is the same of example
`public class Audio implements Runnable
 {
     
            @Override
            public void run()
            {   AudioFormat audioFormat = new AudioFormat(44100.0F, 16, 1, true, false);
                Mixer.Info[] mixerInfo =  AudioSystem.getMixerInfo();
                    System.out.println("Vediamo quanti dispositivi audio");
                    System.out.println(mixerInfo.length);
                for(int i = 0; i < mixerInfo.length; i++)
                {
                     System.out.println(mixerInfo[i].getName()+i);
                }
                Mixer.Info[] minfoSet = AudioSystem.getMixerInfo();
                Mixer mixer = AudioSystem.getMixer(minfoSet[4]);
                DataLine.Info dataLineInfo = new DataLine.Info(TargetDataLine.class, audioFormat);
                try
                {   
                    TargetDataLine line = (TargetDataLine)AudioSystem.getLine(dataLineInfo);
                    line.open(audioFormat);
                    line.start();int sampleRate = (int) audioFormat.getSampleRate();
                    int numChannels = audioFormat.getChannels();
                    int audioBufferSize = sampleRate * numChannels;
                    byte[] audioBytes = new byte[audioBufferSize];
                    ScheduledThreadPoolExecutor exec = new ScheduledThreadPoolExecutor(1);
                    exec.scheduleAtFixedRate(new Runnable() {
                        @Override
                        public void run()
                        {
                            try
                            {
                                int nBytesRead = line.read(audioBytes, 0, line.available());
                                int nSamplesRead = nBytesRead / 2;
                                short[] samples = new short[nSamplesRead];
                                ByteBuffer.wrap(audioBytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(samples);
                                ShortBuffer sBuff = ShortBuffer.wrap(samples, 0, nSamplesRead);
                                System.out.println("before");
                                System.out.println("Sample " + sampleRate);
                                System.out.println("Chanel"+ numChannels);
                                System.out.println("sbuff " + sBuff.toString());
                                recorder.recordSamples(sampleRate, numChannels, sBuff);
                                System.out.println("after");
                            } 
                            catch (org.bytedeco.javacv.FrameRecorder.Exception e)
                            {
                                e.printStackTrace();
                            }
                        }
                    }, 0, (long) 1000 / FRAME_RATE, TimeUnit.MILLISECONDS);
                } 
                catch (LineUnavailableException e1)
                {
                    e1.printStackTrace();
                }
            }
 }`

It never arrive in after system.out

**Comment by saudet** [comment]
Could you check for any error message in the log of FFmpeg? It should
display on the console by default.

**Comment by salvo19881** [comment]
No, nothing, only not work.
with a lot of println, i see buffersize=0; and i see that mixer, is never used;
Think the problem depends by this.

**Comment by saudet** [comment]
Did you call FFmpegLogCallback.set()?

**Comment by salvo19881** [comment]
Yes, but i don't understand the log
`
[log.txt](https://github.com/bytedeco/javacv/files/1082498/log.txt)
`

**Comment by saudet** [comment]
If you're trying to do RTP, you shouldn't try to use the MP4 format, you're going to need to use the RTP format, as per the command line you tried here:
https://github.com/bytedeco/javacv/issues/710#issuecomment-308999691

**Comment by saudet** [comment]
Call `FFmpegFrameRecorder.setFormat("rtp")`, it will do want you want.

**Comment by salvo19881** [comment]
Saudet, this format is my first setted format.
But not work, i 've the same error 
Error: [rtp @ 000000001a6d5460] Only one stream supported in the RTP muxer
I think need to create 2 streams, right?? but if i do this, how i can merge audio and video stream?

**Comment by saudet** [comment]
My guess is that you probably need to use another format.
