### ISSUE TITLE
Segmentation of the input stream like with "segment" option

### ISSUE THREAD

**Issue by d-a-gerashenko** [bytedeco/javacv#726]
Hello, saudet.
I finally finished my tool for splitting input stream to parts. Maybe it will be useful to someone else.
https://github.com/d-a-gerashenko/javacv/tree/master/samples/FFmpegStreamingChunker
I can add it to samples. It's not a one file but a small package.
What do you think about it?

**Comment by saudet** [comment]
Nice, that would go well here: https://github.com/bytedeco/sample-projects

**Comment by d-a-gerashenko** [comment]
https://github.com/bytedeco/sample-projects/pull/16

**Comment by gowridev** [comment]
@d-a-gerashenko  Can we use your code to record live feed and store in chunks. could you please share your thoughts.

**Comment by d-a-gerashenko** [comment]
I think it's possible. Did you try it?
