### ISSUE TITLE
Lean Fatjar using Gradle

### ISSUE THREAD

**Issue by csolorio** [bytedeco/javacv#728]
Hi, everyone.

I've been trying to generate a jar with all dependencies embedded though Gradle. The final JAR size is about 200MB if I use the this:
compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.2'
 
I can reduce it to 105-106 MB by using:
compile (group: 'org.bytedeco', name: 'javacv', version: '1.3.2')
compile (group: 'org.bytedeco.javacpp-presets', name: 'opencv-platform', version: '3.2.0-1.3')
or
compile (group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.2'){
        exclude module:'librealsense'
        exclude module:'artoolkitplus'
        exclude module:'ffmpeg'
        exclude module:'flandmark'
        exclude module:'flycapture'
        exclude module:'libdc1394'
        exclude module:'libfreenect'
        exclude module:'libfreenect2'
        exclude module:'videoinput'
 }

Is there any other way to reduce even more the size of the final jar? like excluding the other versions (linux, arm, etc.) of the opencv dependencies (if so, how?)? I'm using this libraries/packages/classes under Windows OS, if this helps
import org.bytedeco.javacpp.opencv_core;
import org.bytedeco.javacpp.opencv_videoio;
import org.bytedeco.javacpp.opencv_core;
import org.bytedeco.javacv.CanvasFrame;
import org.bytedeco.javacv.OpenCVFrameConverter;
import org.bytedeco.javacpp.opencv_objdetect;
import static org.bytedeco.javacpp.opencv_imgcodecs.imread;
import static org.bytedeco.javacpp.opencv_imgproc.CV_FONT_HERSHEY_PLAIN;
import static org.bytedeco.javacpp.opencv_imgproc.putText;
import static org.bytedeco.javacpp.opencv_imgproc.rectangle;

Regards

**Comment by saudet** [comment]
You could build from source and disable any features you do not need.

**Comment by csolorio** [comment]
Hi. What I finally did to exclude classes from the platforms I'm not using from the final jar to reduce its size to the 30% aprox was: 

shadowJar {
    exclude 'org/bytedeco/javacpp/linux-*/*.*'
    exclude 'org/bytedeco/javacpp/macosx-*/*.*'
    exclude 'lib/armeabi/*.*'
}
