### ISSUE TITLE
Is it possible or not add a method to the Grabber to return Mat object also 

### ISSUE THREAD

**Issue by Bahramudin** [bytedeco/javacv#733]
I mean that if it is possible to add a method to return the grabbed frame in Mat object, to avoid unnecessarily converting between Frame and Mat and IpImage ...etc to speed up the process time. For example in this  method `grab()` from the `OpenCVFrameGrabber ` here is something unnecessary checking and converting:

```
public Frame grab() throws Exception {
        if (!capture.retrieve(mat)) {
            // Point 1: this is no need because the end user will check this
            throw new Exception("retrieve() Error: Could not retrieve frame. (Has start() been called?)");
        }
        if (!triggerMode) {
            if (!capture.grab()) {
                throw new Exception("grab() Error: Could not grab frame. (Has start() been called?)");
            }
        }

        // Point 2:  it is really no need, because when the end user get the image, he/she will 
        // convert the mat to his/her needed mode, so here it is an extra process, 
       // in most cases all the user wants the data in the original mode
        if (imageMode == ImageMode.GRAY && mat.channels() > 1) {
            if (returnMatrix == null) {
                returnMatrix = new Mat(mat.rows(), mat.cols(), mat.depth(), 1);
            }

            cvtColor(mat, returnMatrix, CV_BGR2GRAY);
        } else if (imageMode == ImageMode.COLOR && mat.channels() == 1) {
            if (returnMatrix == null) {
                returnMatrix = new Mat(mat.rows(), mat.cols(), mat.depth(), 3);
            }
            cvtColor(mat, returnMatrix, CV_GRAY2BGR);
        } else {
            returnMatrix = mat;
        }
        // Point 3:  this converting is really no need, we can make a method to directly return the Mat
       // and one for directly return Frame with any converting.
        return converter.convert(returnMatrix);
    }
```
Because in the above code and the comment Point 1, for my program flow I must check the data that it is failed or succeeded, so in such case, the checking has done twice.
**Note:** it is better to let the end user to play with the data

**Comment by saudet** [comment]
FrameConverter is very efficient, there is no copy taking place:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/
Does that answer your question?

If either FrameGrabber or FrameConverter is a bottleneck of your application for some reason, could you post results from your profile here? Thank you

BTW, if all you care about is using the VideoCapture object of OpenCV, you should do that.
