### ISSUE TITLE
 av_usleep

### ISSUE THREAD

**Issue by zhengbin1015** [bytedeco/javacv#735]
Can you supply the av_usleep function?

**Comment by saudet** [comment]
Sure, we just need to add time.h to the list of header files here:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/src/main/java/org/bytedeco/javacpp/presets/avutil.java#L36

**Comment by zhengbin1015** [comment]
Do you need to pack NDK libjniavutil.so again?

**Comment by saudet** [comment]
For Android? Yes, but thanks to @vb216, we can let Travis CI do it for us.

**Comment by saudet** [comment]
Please send a pull request, and you will get new binaries automatically. No need to install the NDK.

**Comment by saudet** [comment]
Included in newly released version 1.4. Enjoy!
