### ISSUE TITLE
Java2DFrameConverter.cloneBufferedImage makes images black

### ISSUE THREAD

**Issue by d-a-gerashenko** [bytedeco/javacv#736]
What for is this condition "type == BufferedImage.TYPE_CUSTOM" used in the method Java2DFrameConverter.cloneBufferedImage?
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/Java2DFrameConverter.java#L75
It makes all my images black. Without this condition all work fine.

**Comment by saudet** [comment]
It just tries to create a BufferedImage of the same type, but in the case of TYPE_CUSTOM, we probably need to do more work to support all kinds of formats...

**Comment by d-a-gerashenko** [comment]
It returns new BufferedImage with the same type but without data.
	Java2DFrameConverter converter = new Java2DFrameConverter();
	Java2DFrameConverter.cloneBufferedImage(converter.convert(frame));

Maybe it's better to mark this condition with @todo and to put only this code in the method?
	return new BufferedImage(bi.getColorModel(), bi.copyData(null), bi.isAlphaPremultiplied(), null);

**Comment by saudet** [comment]
Well, that won't return an image of the right type. So let's get this fixed properly.

**Comment by saudet** [comment]
We could adopt this solution: https://stackoverflow.com/a/19327237/523744

Could you check that it works in your case? And please do send a PR! Thanks

**Comment by d-a-gerashenko** [comment]
Isn't it the same as my code above? Are you talking about this one:

	static BufferedImage deepCopy(BufferedImage bi) {
		ColorModel cm = bi.getColorModel();
		boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
		WritableRaster raster = bi.copyData(null);
		return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
	}

I just replaced this:

	ColorModel cm = bi.getColorModel();
	boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();

with this:

	bi.isAlphaPremultiplied();

**Comment by d-a-gerashenko** [comment]
And both of them work properly.

**Comment by saudet** [comment]
No, the one under, this one: https://stackoverflow.com/a/19327237/523744

**Comment by d-a-gerashenko** [comment]
Ok. I'll test it.

**Comment by d-a-gerashenko** [comment]
I also have found this method:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/Java2DFrameUtils.java#L47

Both of them passed the test.

**Comment by saudet** [comment]
Right, that's the same thing though. It doesn't copy the imageType when it's not equal to TYPE_CUSTOM.

**Comment by d-a-gerashenko** [comment]
Now what's the plan? Do I have to create PRs for both of this files or for the Java2DFrameConverter only?

**Comment by saudet** [comment]
Java2DFrameUtils should be using Java2DFrameConverter, so let's do that. Sounds good?

**Comment by d-a-gerashenko** [comment]
Yes. I was going to do it the same way.

**Comment by saudet** [comment]
Released in version 1.3.3. Thanks for your contribution!
