### ISSUE TITLE
FaceRecognizer failed to predict the face

### ISSUE THREAD

**Issue by Bahramudin** [bytedeco/javacv#737]
I have already trained images for almost three faces and saved the train data to HD, and then when loading the trained data, and predict the face, it throws the following the Exception:
```
java.lang.NullPointerException: Pointer address of argument 1 is NULL.
	at org.bytedeco.javacpp.opencv_face$FaceRecognizer.predict(Native Method)
```

The code:
```
BasicFaceRecognizer model = opencv_face.createEigenFaceRecognizer();
model.load("C:\\data\\eigen_faces.xml");
IntPointer label = new IntPointer();
DoublePointer confidence = new DoublePointer();
model.predict(face, label, confidence);
System.out.println(label.get());
```

**But** _the same code was working in OpenCV Java wrapper._

**Comment by saudet** [comment]
Ok, please post the code that works, thanks!

**Comment by saudet** [comment]
The issue is probably with the `DoublePointer` though. Try this:
```java
DoublePointer confidence = new DoublePointer(1);
```

**Comment by Bahramudin** [comment]
Thanks! The problem was exactly with both of them (IntPointer and DoublePointer) they both need to be initialized in the constructor. 

_The code that I used the OpenCV is the same as the JavaCV, and also in OpenCV 3.3.0 version the Face class is no longer present, it means that the initialization of the face the recognizers is done by their classes, and not by the Face class._ 

The code:

private static void train() {
    List<Mat> imgs = new ArrayList<>();
    List<Integer> labelList = new ArrayList<>();
    MatOfInt labels = new MatOfInt();
    String pathToImages = "C:\\faces";

    File dir = new File(pathToImages);
    File[] dirs = dir.listFiles();
    int personCount = 1;
    assert dirs != null;
    for (File file : dirs) {
        File[] faces = file.listFiles();
        assert faces != null;
        for (File face : faces) {
            Mat faceMat = Imgcodecs.imread(face.getAbsolutePath(), Imgcodecs.IMREAD_GRAYSCALE);
            Imgproc.equalizeHist(faceMat, faceMat);
            imgs.add(faceMat);
            labelList.add(personCount);
        }
        personCount++;
    }
    labels.fromList(labelList);
    System.out.println(labels.dump());
    
    // train 
    //FaceRecognizer recognizer = Face.createEigenFaceRecognizer(); //80, 200
    FaceRecognizer recognizer = Face.createEigenFaceRecognizer();//4000
    //FaceRecognizer recognizer = Face.createLBPHFaceRecognizer();//3, 8, 8, 8, 180

    // label info
    String[] names = {"W-S", "B-A", "T-Y"};
    for (Integer integer : labelList) {
        recognizer.setLabelInfo(integer, names[integer-1]);
    }
    recognizer.train(imgs, labels);
    recognizer.save("C:\\face-data\\eigen-faces_trained_data.xml");
    //recognizer.save("C:\\face-data\\fisher-faces_trained_data.xml");
    //recognizer.save("C:\\face-data\\lbph-faces_trained_data.xml");
}

private static void recognize() {
    FaceRecognizer recognizer = Face.createEigenFaceRecognizer();
    recognizer.load("C:\\face-data\\eigen-faces_trained_data.xml");
    
    //FaceRecognizer recognizer = Face.createFisherFaceRecognizer();
    //recognizer.load("C:\\face-data\\fisher-faces_trained_data.xml");
    
    //FaceRecognizer recognizer = Face.createLBPHFaceRecognizer();
    //recognizer.load("C:\\face-data\\lbph-faces_trained_data.xml");

    //String filename = "E:\\haarcascades\\haarcascade_frontalface_alt_tree.xml";
    String filename = "E:\\haarcascades\\haarcascade_frontalcatface.xml";
    //String filename = "E:\\lbpcascades\\lbpcascade_frontalface_improved.xml";
    CascadeClassifier classifier = new CascadeClassifier(filename);
    VideoCapture capture = new VideoCapture(0);
    
    Mat frame = new Mat();
    Mat gray = new Mat();
    
    OpenCVUtil.VideoWindow window = OpenCVUtil.createWindow();
    MatOfRect faces  = new MatOfRect();
    int[] labels = new int[1];
    double[] confidences = new double[1];
    Size size = new Size(92, 112);
    while (capture.read(frame)) {
        //Imgproc.pyrDown(frame, frame);
        Imgproc.pyrDown(frame, frame);
        Imgproc.cvtColor(frame, gray, Imgproc.COLOR_BGR2GRAY);

        classifier.detectMultiScale(gray, faces);

        Rect[] rects = faces.toArray();
        Mat submat = null;

        System.out.println("");
        for (Rect rect : rects) {
            Imgproc.rectangle(frame, rect.tl(), rect.br(), new Scalar(0, 0, 255), 2);
            submat = gray.submat(rect).clone();
            Imgproc.equalizeHist(submat, submat);
            Imgproc.resize(submat, submat, size, 1, 1, Imgproc.INTER_CUBIC);

            recognizer.predict(submat, labels, confidences);
            int label = labels[0];
            double confidence = confidences[0];
            String labelInfo = recognizer.getLabelInfo(label);
            System.out.println("labelInfo = " + labelInfo);
            System.out.println("label = " + label);
            System.out.println("confidence = " + confidence);
            System.out.println("threshold = "+((BasicFaceRecognizer)recognizer).getThreshold());

            int x = (int) Math.max(rect.tl().x - 10, 0);
            int y = (int) Math.max(rect.tl().y - 10, 0);
            Imgproc.putText(frame, String.format("Predict = %s", labelInfo), new Point(x, y), Core.FONT_HERSHEY_PLAIN, 1.0, new Scalar(0, 255, 0), 2);
        }
        if (submat != null) {
            window.showVideo(capture, frame, gray, submat);
        } else {
            window.showVideo(capture, frame, gray);
        }
    }
    capture.release();
}

**Comment by kshitijgarg2609** [comment]
I have been trying Face Recognition using bytedeco javacv opencv, I have been getting wrong results like random confidence value, Please can you tell me whether I am training and recognizing well, I am sharing my code here. Thank you

TestFR.java

import java.awt.event.*;
import java.io.*;
import java.util.*;

import org.opencv.core.*;
import org.opencv.videoio.*;
import org.opencv.highgui.*;
import org.opencv.imgcodecs.*;
import org.opencv.imgproc.*;
import org.opencv.objdetect.*;
import org.opencv.face.*;
class TestFR extends FaceRecognitionTester
{
VideoCapture vc = new VideoCapture();
FaceRecognizer fr = EigenFaceRecognizer.create();
static CascadeClassifier classifier;
LinkedList<Mat> faces = new LinkedList<Mat>();
LinkedList<Integer> labels = new LinkedList<Integer>();
TrainerLock tl = new TrainerLock();
TrainerLock test_lock = new TrainerLock();
Size r_size = new Size(250,250);
static
{
org.bytedeco.javacpp.Loader.load(org.bytedeco.opencv.opencv_java.class);
classifier = new CascadeClassifier("lbpcascade_frontalface.xml");
}
Thread loop = new Thread()
{
public void run()
{
while(true)
{
capture();
}
}
}
;
TestFR()
{
super();
addEvent();
vc.open(0);
loop.start();
}
public static void main(String args[])
{
TestFR obj = new TestFR();
}
void capture()
{
if(vc.grab())
{
try
{
Mat mat=new Mat();
vc.retrieve(mat);
detectFace(mat);
}
catch(Exception e)
{
System.out.println("FRAME CAPTURE EXCEPTION !!!");
}
}
}
void detectFace(Mat mat)
{
try
{
MatOfRect faceDetections = new MatOfRect();
classifier.detectMultiScale(mat, faceDetections);
boolean fd_flg=true;
for (Rect rect : faceDetections.toArray())
{
Mat fdd=new Mat(mat,rect);
if(fd_flg)
{
updateFaceDetectionScreen(fdd);
if(tl.getFlag() && !test_lock.getFlag())
{
trainModel(fdd,tl.getLabelValue());
tl.setFlag(false);
}
fd_flg=false;
}
if(test_lock.getFlag())
{
recognize(fdd);
}
Imgproc.rectangle(mat,new org.opencv.core.Point(rect.x, rect.y),new org.opencv.core.Point(rect.x + rect.width, rect.y + rect.height),new Scalar(0, 0, 255),3);
}
updateMainScreen(mat);
}
catch(Exception e)
{
}
}
void trainModel(Mat mat,Integer a)
{
if(a!=null)
{
Imgproc.resize(mat,mat,r_size);
Imgproc.cvtColor(mat,mat,Imgproc.COLOR_BGR2GRAY);
//Imgproc.equalizeHist(mat,mat);
faces.add(mat);
labels.add(a);
tl.setLabelValue(null);
System.out.println("Trained !!!");
}
}
void recognize(Mat mat)
{
try
{
Imgproc.resize(mat,mat,r_size);
Imgproc.cvtColor(mat,mat,Imgproc.COLOR_BGR2GRAY);
//Imgproc.equalizeHist(mat,mat);
int label[] = new int[1];
double confidence[] = new double[1];
fr.predict(mat,label,confidence);
System.out.println(Arrays.toString(label));
System.out.println(Arrays.toString(confidence));
}
catch(Exception e)
{
System.out.println("PREDICTION ERROR !!!");
}
}
void updateMainScreen(Mat mat)
{
updateMainScreen((java.awt.image.BufferedImage)HighGui.toBufferedImage(mat));
}
void updateFaceDetectionScreen(Mat mat)
{
updateFaceDetectionScreen((java.awt.image.BufferedImage)HighGui.toBufferedImage(mat));
}
void addEvent()
{
trainer.addActionListener(new ActionListener()
{
public void actionPerformed(ActionEvent e)
{
if(!tl.getFlag() && !test_lock.getFlag())
{
try
{
tl.setLabelValue(Integer.valueOf(fd_label.getText()));
tl.setFlag(true);
}
catch(Exception ee)
{
}
}
}
}
);
test.addActionListener(new ActionListener()
{
public void actionPerformed(ActionEvent e)
{
try
{
if(!test_lock.getFlag())
{
MatOfInt moi = new MatOfInt();
moi.fromList(labels);
fr.train(faces,moi);
fr.save("fr_test.xml");
test_lock.setFlag(true);
System.out.println("Exported !!!");
}
}
catch(Exception ee)
{
}
}
}
);
}
}

FaceRecognitionTester.java

import java.awt.*;
import java.awt.image.*;
import javax.swing.*;
class FaceRecognitionTester
{
Dimension dim;
static int w,h;
int width=800,height=400;

JFrame jf;
JPanel jp;
JLabel main_screen;
JLabel fd_screen;
JTextField fd_label;
JButton trainer;
JButton test;

FaceRecognitionTester()
{
dim=(Toolkit.getDefaultToolkit()).getScreenSize();
w=(int)(dim.getWidth());
h=(int)(dim.getHeight());

jf=new JFrame("Face Recognition Tester");
jf.setBounds(((w-width)/2),((h-height)/2),width,height);
jf.setResizable(false);
jf.getContentPane().setLayout(null);
jp = new JPanel();
jp.setBounds(10, 11, 774, 350);
jp.setLayout(null);
jf.getContentPane().add(jp);
main_screen = new JLabel();
main_screen.setBackground(Color.CYAN);
main_screen.setOpaque(true);
main_screen.setBounds(10, 11, 582, 328);
jp.add(main_screen);
fd_screen = new JLabel();
fd_screen.setBounds(602, 11, 162, 101);
fd_screen.setBackground(Color.CYAN);
fd_screen.setOpaque(true);
jp.add(fd_screen);
fd_label = new JTextField();
fd_label.setBounds(602, 123, 162, 22);
jp.add(fd_label);
trainer = new JButton("train");
trainer.setBounds(640, 156, 89, 23);
jp.add(trainer);
test = new JButton("test");
test.setBounds(640, 190, 89, 23);
jp.add(test);
jf.setDefaultCloseOperation(jf.EXIT_ON_CLOSE);
jf.setVisible(true);
jf.repaint();
jf.revalidate();
}
BufferedImage scaledImage(Image a,int w,int h)
{
BufferedImage b;
Graphics2D g2;
b=new BufferedImage(w,h,BufferedImage.TYPE_INT_ARGB);
g2=b.createGraphics();
g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION,RenderingHints.VALUE_INTERPOLATION_BILINEAR);
g2.drawImage(a,0,0,w,h,null);
g2.dispose();
return b;
}
void updateMainScreen(BufferedImage icon)
{
icon=scaledImage(icon,main_screen.getWidth(),main_screen.getHeight());
main_screen.setIcon(new ImageIcon(icon));
}
void updateFaceDetectionScreen(BufferedImage icon)
{
icon=scaledImage(icon,fd_screen.getWidth(),fd_screen.getHeight());
fd_screen.setIcon(new ImageIcon(icon));
}
}

TrainerLock.java

import java.util.concurrent.*;
class TrainerLock
{
boolean flg=false;
Semaphore ss = new Semaphore(1,true);
Integer val=null;
void setFlag(boolean a)
{
try
{
ss.acquire();
flg=a;
}
catch(Exception e)
{
}
ss.release();
}
boolean getFlag()
{
boolean f=false;
try
{
ss.acquire();
f=flg;
}
catch(Exception e)
{
}
ss.release();
return f;
}
void setLabelValue(Integer a)
{
val=a;
}
Integer getLabelValue()
{
return val;
}
}
