### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by tehseenmayar** [bytedeco/javacv#740]
hello!
i am a working on a project using opencv and javacv in java using netbeans to extract frames from a video but i am getting the above mentioned error. i have already added the required opencv and javacv jar files.
my code is something like this

FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("E:/background.mp4");
ImageIO.write((RenderedImage) frameGrabber.grabFrame(), "png", new File("E:/img" +frameNumber + ".png"));
kindly help me
thanks

**Comment by saudet** [comment]
Please put all the JAR files in your class path.

**Comment by tehseenmayar** [comment]
i have already added jar files in library tab in netbeans

**Comment by tehseenmayar** [comment]
already put all the jar files in class path but still same issue

**Comment by saudet** [comment]
Can you give me a list?

**Comment by tehseenmayar** [comment]
javacpp 1.2
javacv  1.2
opencv 3.1.0-1.2
ffmpeg windowsx86-x64
these jar files i am using

**Comment by saudet** [comment]
Try again with version JavaCV 1.3.

**Comment by tehseenmayar** [comment]
still the same error

**Comment by saudet** [comment]
Again, please provide the list of JAR files you're trying to use.

**Comment by tehseenmayar** [comment]
ffmpeg windowsx86-x64
opencv 3.1.0-1.2
javacv-1.3

**Comment by tehseenmayar** [comment]
import java.awt.image.BufferedImage;
import java.io.File;
import java.awt.image.RenderedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.bytedeco.javacv.FFmpegFrameGrabber;

public class mainClass {
    
    public static void main(String args[]) throws IOException, Exception{
int frameNumber = 0;
  FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("E:/background.mp4");
      
        frameGrabber.start();
        for(int i=0;i<10;i++)
        {
            frameNumber = i;
            try{
 ImageIO.write((RenderedImage) frameGrabber.grabFrame(), "png", new File("E:/img" +frameNumber + ".png"));
         } catch(Exception e){
                e.printStackTrace();
            }
        }
        frameGrabber.stop();
        System.out.println("Finished");
    }

}

this is the code

**Comment by saudet** [comment]
You're going to need to use the same version for all FFmpeg artifacts, and the same for OpenCV.

**Comment by tehseenmayar** [comment]
what does that mean.. please elaborate it

**Comment by tehseenmayar** [comment]
is there a problem with the version of jar files i am using? do i have to make changes in my jar files?

**Comment by saudet** [comment]
Yes, you're not using matching versions. JavaCV 1.3 will try to use OpenCV 3.2.0, but you're giving it 3.1.0. That won't work. The same kind of thing won't work for FFmpeg either.

**Comment by tehseenmayar** [comment]
so i need to use opencv1.3 with javacv 1.3? and also the same version of ffmpeg?

**Comment by saudet** [comment]
Like I said, just put *all* the JAR files in your class path.

**Comment by tehseenmayar** [comment]
means i have to try openCV 3.2.0 with javacv 1.3?

**Comment by tehseenmayar** [comment]
you mean i have to put all the versions of jar files in my class path?

**Comment by saudet** [comment]
No, all the JAR files of JavaCV 1.3, or 1.3.2 would be a better idea actually.

**Comment by tehseenmayar** [comment]
and same for openCV?

**Comment by tehseenmayar** [comment]
i will try these and will let you know

**Comment by tehseenmayar** [comment]
i have included all jar files of javaCV 1.3.2 but still the same problem

**Comment by saudet** [comment]
Since this is on Windows, please try to follow the instructions on the page below and let me know what it is says the problem is:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by tehseenmayar** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:764)
	at org.bytedeco.javacpp.Loader.load(Loader.java:671)
	at org.bytedeco.javacpp.avutil.<clinit>(avutil.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:726)
	at org.bytedeco.javacpp.Loader.load(Loader.java:687)
	at mainClass.main(mainClass.java:29)
Caused by: java.lang.UnsatisfiedLinkError: no avutil in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:963)
	at org.bytedeco.javacpp.Loader.load(Loader.java:752)

these are the exceptions thrown after running dependency walker

**Comment by saudet** [comment]
You're not calling Loader.load() manually. Please try to follow the
instructions.

**Comment by tehseenmayar** [comment]
`  try {
    Loader.load(org.bytedeco.javacv.FFmpegFrameGrabber.class);
} catch (UnsatisfiedLinkError e) {
    String path = Loader.cacheResource(org.bytedeco.javacv.FFmpegFrameGrabber.class, "windows-x86_64/jni org.bytedeco.javacv.FFmpegFrameGrabber.dll").getPath();
    new ProcessBuilder("c:/path/to/depends.exe", path).start().waitFor();
}`

i have called it like this now. is it correct now?

**Comment by tehseenmayar** [comment]
Exception in thread "main" java.lang.NullPointerException
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:364)
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:346)
	at org.bytedeco.javacpp.Loader.cacheResource(Loader.java:313)
	at mainClass.main(mainClass.java:31)

now the exception is like this

**Comment by saudet** [comment]
No, the problem is with avutil, not FFmpegFrameGrabber.

**Comment by tehseenmayar** [comment]
sir! kindly help me. i am waiting for your response

**Comment by tehseenmayar** [comment]
so i have to call avutil instead of FFmpegFrameGrabber?

**Comment by saudet** [comment]
Like I said, if you put all the JAR files found in the ZIP file in the
class path, it will work!

**Comment by tehseenmayar** [comment]
i have included all of the jar files but still the same java.lang.NoClassDefFoundError error
these are the jar files i have included in class path
artoolkitplus-2.3.1-1.3
ffmpeg-3.2.1-1.3
flandmark-1.07-1.3
flycapture-2.9.3.43-1.3
javacpp-1.3.2
javacv-1.3.2
libdc1394-2.2.4-1.3
libfreenect-0.5.3-1.3
libfreenect2-0.2.0-1.3
librealsense-1.9.6-1.3
opencv-3.2.0-1.3
videoinput-0.200-1.3

**Comment by tehseenmayar** [comment]
now the error is
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniavutil in java.library.path
i have just put this code in main
 Loader.load(org.bytedeco.javacpp.avutil.class);

**Comment by tehseenmayar** [comment]
is there any problem with my IDE or why is it showing these error now because first there was UnsatisfiedLinkError and now it NoClassDefFoundError ?

**Comment by saudet** [comment]
Because you did not include all the JAR files. You need to include all of
them.

**Comment by tehseenmayar** [comment]
but i have included all of them
i will share snapshot of my IDE with you

![fram](https://user-images.githubusercontent.com/29973339/27992911-b6c6e448-6453-11e7-9cd0-314d2f67599d.PNG)

**Comment by saudet** [comment]
You did not. You will need to add at least the ones for Windows. But just
put all of them and it will work. This is the last time I will repeat
myself.

**Comment by tehseenmayar** [comment]
okay i will try to find the suitable jar files
thanks

**Comment by saudet** [comment]
You don't need to "find" them--they come with the ZIP file!

**Comment by tehseenmayar** [comment]
i have downloaded and added all of the jar files in that ZIP file but i don't know what's the problem exactly is

**Comment by tehseenmayar** [comment]
now the exception is like this
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avcodec

**Comment by tehseenmayar** [comment]
i have followed issue 225 and there was a fixed ffmpeg jar so i added that and now the exception is
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avcodec

**Comment by saudet** [comment]
Which ZIP file? This one http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv-platform/1.3.2/javacv-platform-1.3.2-bin.zip ?

**Comment by tehseenmayar** [comment]
i have managed all that previous exceptions with maven but now it's throwing this exception

Exception in thread "main" java.lang.ClassCastException: sun.awt.image.ToolkitImage cannot be cast to java.awt.image.BufferedImage

**Comment by saudet** [comment]
What version of the JDK is that?

**Comment by tehseenmayar** [comment]
jdk1.8.0_121

**Comment by saudet** [comment]
Ok, please post a code snippet that causes that.

**Comment by tehseenmayar** [comment]
`       frameGrabber.start();
        IplImage i;
        OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
        for(int ii=0;ii<10;ii++){

            i= converter.convert(frameGrabber.grab());


 
            OpenCVFrameConverter.ToIplImage iplConverter = new OpenCVFrameConverter.ToIplImage();
            Java2DFrameConverter bimConverter = new Java2DFrameConverter();
            org.bytedeco.javacv.Frame frame = converter.convert(i);
            BufferedImage img = bimConverter. convert(frame);
            BufferedImage result = (BufferedImage)img.getScaledInstance(
                    img.getWidth(), img.getHeight(), java.awt.Image.SCALE_DEFAULT);
            img.flush();
            String path = "E:/Image"+ii+".png";
            ImageIO.write(result,"png", new File(path));

        }
        frameGrabber.stop();`
this is the code

**Comment by tehseenmayar** [comment]
BufferedImage result = (BufferedImage)img.getScaledInstance(
                img.getWidth(), img.getHeight(), java.awt.Image.SCALE_DEFAULT);
i think this is causing the exception

**Comment by saudet** [comment]
Right, we can't do that. You'll need to report that to Oracle if you don't
like it. :)

**Comment by tehseenmayar** [comment]
`  IplImage i;
        OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
        for(int ii=0;ii<10;ii++){


            i= converter.convert(frameGrabber.grab());
            Java2DFrameConverter bimConverter = new Java2DFrameConverter();
            org.bytedeco.javacv.Frame frame = converter.convert(i);
            BufferedImage img = bimConverter.convert(frame);
    img.flush();
            String path = "E:/Image"+ii+".png";
            ImageIO.write(img,"png", new File(path));

        }
        frameGrabber.stop();`

i have implemented like this and now it's working

**Comment by tehseenmayar** [comment]
i have directly saved it as an image and now it's working..
thanks a lot for your contribution

**Comment by tehseenmayar** [comment]
"java.awt.Image" doesn't have " SCALE_DEFAULT" method, i think
