### ISSUE TITLE
Thread is suspended on avcodec_encode_video2() after error -542398533

### ISSUE THREAD

**Issue by d-a-gerashenko** [bytedeco/javacv#745]
Windows7 x64
JavaCV 1.3

There are four independent threads. Each of them deals with only it's private data.
The purpose of each thread is to write video from rtsp cam to small files. Each file is about 1 minute long.
Each of threads has one pair of objects: FFmpegFrameGrabber and FFmpegFrameRecorder.
When an error occurs, the thread stops (ffmpeg's objects are released too) and is replaced with an another equal thread.

All works fine but after about 12 hours occurs this error:

	Caused by: org.bytedeco.javacv.FrameRecorder$Exception: avcodec_encode_video2() error -542398533: Could not encode video packet.
		at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:844)
		at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:756)
		at org.bytedeco.javacv.FFmpegFrameRecorder.record(FFmpegFrameRecorder.java:749)

I don't care about this error but after it the thread tries to stop FFmpegFrameRecorder and gets stuck on avcodec_encode_video2():

	at org.bytedeco.javacpp.avcodec.avcodec_encode_video2(avcodec.java)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:843)
	at org.bytedeco.javacv.FFmpegFrameRecorder.stop(FFmpegFrameRecorder.java:731)

I don't know what to do with this. It could be deadlock in Java or in cpp or something else.
I tried to use Netbeans for this problem but didn't get any alerts about deadlocks. Also I tried to interrupt suspended thread but nothing is changed.

Also I noticed that the error doesn't make thread suspended for the first time.

When one of threads is suspended, other threads continue execution.

**Comment by saudet** [comment]
Might be a bug in FFmpeg. Have you tried version 3.3.2?

**Comment by d-a-gerashenko** [comment]
Do you mean "JavaCV 1.3.2 binary archive javacv-platform-1.3.2-bin.zip (212 MB)"?

**Comment by saudet** [comment]
No, I mean JavaCV 1.3.3-SNAPSHOT

**Comment by d-a-gerashenko** [comment]
I am not sure I understand. Should I build it myself or could I download it somewhere?

**Comment by saudet** [comment]
Actually I forgot to update JavaCV, now it's done:
https://github.com/bytedeco/javacv/commit/53f66226108d054d941a14e7ec700d5a05fc9d41

We can also get binaries only for FFmpeg:
https://github.com/bytedeco/javacpp-presets/tree/master/ffmpeg#the-pomxml-build-file

If you're not into build tools, we can download the JAR files manually sure:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/

**Comment by d-a-gerashenko** [comment]
Thanks. I will try it.

**Comment by d-a-gerashenko** [comment]
I was confused with v1.3.3 because there is no v1.3.3 in central maven repository. Then I added this lines in my pom.xml:

	<repositories>
		<repository>
			<id>oss-sonatype</id>
			<name>oss-sonatype</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

and I tried this:

	<dependencies>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>1.3.3-SNAPSHOT</version>
		</dependency>
	</dependencies>

and got result (BUILD FAILURE):

	The POM for org.bytedeco.javacpp-presets:opencv:jar:android-arm:3.2.0-1.3.3-20170716.111105-388 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:opencv:jar:android-x86:3.2.0-1.3.3-20170716.104024-387 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:opencv:jar:linux-armhf:3.2.0-1.3.3-20170716.121054-390 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:opencv:jar:windows-x86:3.2.0-1.3.3-20170716.111221-389 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:ffmpeg:jar:android-arm:3.3.2-1.3.3-20170716.110639-130 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:ffmpeg:jar:android-x86:3.3.2-1.3.3-20170716.103336-129 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:ffmpeg:jar:linux-armhf:3.3.2-1.3.3-20170716.115524-132 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:ffmpeg:jar:windows-x86:3.3.2-1.3.3-20170716.114349-131 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:flycapture:jar:linux-armhf:2.11.3.121-1.3.3-20170716.114300-347 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:flycapture:jar:windows-x86:2.11.3.121-1.3.3-20170716.114642-348 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:libdc1394:jar:linux-armhf:2.2.5-1.3.3-20170716.114652-467 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:libdc1394:jar:windows-x86:2.2.5-1.3.3-20170716.114940-468 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:libfreenect:jar:linux-armhf:0.5.3-1.3.3-20170716.114948-474 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:libfreenect:jar:windows-x86:0.5.3-1.3.3-20170716.115208-475 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:videoinput:jar:windows-x86:0.200-1.3.3-20170716.115854-455 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:artoolkitplus:jar:android-arm:2.3.1-1.3.3-20170716.111410-475 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:artoolkitplus:jar:android-x86:2.3.1-1.3.3-20170716.103134-474 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:artoolkitplus:jar:linux-armhf:2.3.1-1.3.3-20170716.115608-476 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:artoolkitplus:jar:windows-x86:2.3.1-1.3.3-20170716.120118-477 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:flandmark:jar:android-arm:1.07-1.3.3-20170716.111102-375 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:flandmark:jar:android-x86:1.07-1.3.3-20170716.104028-374 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:flandmark:jar:linux-armhf:1.07-1.3.3-20170716.121056-377 is missing, no dependency information available
	The POM for org.bytedeco.javacpp-presets:flandmark:jar:windows-x86:1.07-1.3.3-20170716.111225-376 is missing, no dependency information available

What dependencies should I use in pom.xml?
I also tried to combine different versions with exclusions, but without success.

**Comment by saudet** [comment]
That should work, these JAR files are on the repository, right?

**Comment by saudet** [comment]
Ah, no they aren't. Artifacts get cleaned up automatically by the server and it doesn't leave much behind. Well, try to specify your platform with `-Djavacpp.platform=windows-x86_64` and see if that passes.

**Comment by d-a-gerashenko** [comment]
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil

**Comment by saudet** [comment]
So are the binaries working? They are there for your platform:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.3.2-1.3.3-SNAPSHOT/

**Comment by d-a-gerashenko** [comment]
**1.3.2**
There should be two files: ffmpeg-windows-x86.jar and ffmpeg-windows-x86_64.jar.
I get error `java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil` when I replace this files with this single file https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/ffmpeg/3.3.2-1.3.3-SNAPSHOT/ffmpeg-3.3.2-1.3.3-20170716.153200-136-windows-x86_64.jar

**Comment by saudet** [comment]
Need to update ffmpeg.jar as well.

**Comment by d-a-gerashenko** [comment]
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avutil
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at org.bytedeco.javacpp.Loader.load(Loader.java:721)
		at org.bytedeco.javacpp.Loader.load(Loader.java:666)
		at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2866)

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by d-a-gerashenko** [comment]
I think it tries to load ffmpeg-windows-x86.jar
v1.3.2 works even without ffmpeg-windows-x86_64.jar

**Comment by d-a-gerashenko** [comment]
Why there is no ffmpeg-3.3.2-1.3.3-20170716.153200-136-windows-x86.jar
There is only ffmpeg-3.3.2-1.3.3-20170716.153200-136-windows-x86_64.jar

**Comment by d-a-gerashenko** [comment]
Now it work but only with x64 JRE. So as I said above, it needs **ffmpeg-windows-x86.jar** file. x32 mode requires it.

**Comment by saudet** [comment]
Ah, you want the 32-bit binaries. Like I said, the SNAPSHOT server is overly aggressive and deletes stuff. I'll just restart the build here on AppVeyor and you'll get new binaries soon:
https://ci.appveyor.com/project/Bytedeco/javacpp-presets

**Comment by d-a-gerashenko** [comment]
I started new test with 3.3.2. Now it's working. But app should work at least 12 hours to find out whether the problem is fixed.

**Comment by d-a-gerashenko** [comment]
I got the same error on the last test. Now I'm going to try new 1.3.3 release.

**Comment by saudet** [comment]
It doesn't sound like an error related to multithreading. When we get an error like that, we probably shouldn't try to call stop(). Try to call release() instead.

**Comment by saudet** [comment]
I'm assuming calling release() did the trick, but please let me know if you still have issues with this! Thanks.

**Comment by d-a-gerashenko** [comment]
Hi. Sorry for long delay. I had to work on another project.
I tried to use release() in conjunction with stop(). We can't use only release() because in this way we will get unreadable files.
I tried to use release() in this way:
	final FrameRecorder localRecorder = recorder;
	new Thread(() -> {
		try {
			TimeUnit.SECONDS.sleep(20);
			localRecorder.release();
		} catch (Exception e) {
		}
		
	}, "Releasing thread").start();
	recorder.stop();

But I got the same problem after a few days.

Main thread got stuck on "org.bytedeco.javacpp.avcodec.avcodec_encode_video2(avcodec.java)":

"Thread-1436 / executor thread / javacv-ffmpeg"
	at org.bytedeco.javacpp.avcodec.avcodec_encode_video2(avcodec.java)
	at org.bytedeco.javacv.FFmpegFrameRecorder.recordImage(FFmpegFrameRecorder.java:942)
	at org.bytedeco.javacv.FFmpegFrameRecorder.stop(FFmpegFrameRecorder.java:829)
	at com.videoweber.lib.engines.javacv.streaming_chunker.StreamingChunker.stop(StreamingChunker.java:141)
	at com.videoweber.lib.engines.javacv.FfmpegSamplerEngine.run(FfmpegSamplerEngine.java:105)
	at com.videoweber.lib.common.Executor.lambda$start$0(Executor.java:77)
	at com.videoweber.lib.common.Executor$$Lambda$307.31171851.run
	at java.lang.Thread.run(Thread.java:745)

Closer got stuck on "org.bytedeco.javacpp.avcodec.avcodec_free_context(avcodec.java)":
	
"Closer"
	at org.bytedeco.javacpp.avcodec.avcodec_free_context(avcodec.java)
	at org.bytedeco.javacv.FFmpegFrameRecorder.releaseUnsafe(FFmpegFrameRecorder.java:180)
	at org.bytedeco.javacv.FFmpegFrameRecorder.release(FFmpegFrameRecorder.java:174)
	at com.videoweber.lib.engines.javacv.streaming_chunker.StreamingChunker.lambda$stop$0(StreamingChunker.java:137)
	at com.videoweber.lib.engines.javacv.streaming_chunker.StreamingChunker$$Lambda$376.19404296.run
	at java.lang.Thread.run(Thread.java:745)

**Comment by d-a-gerashenko** [comment]
Something similar: https://github.com/samleoqh/IssueTracker/issues/3

**Comment by saudet** [comment]
It says it's an issue with multithreading. Try to disable it?

**Comment by d-a-gerashenko** [comment]
Multithreading inside avcodec_encode_video2()? I'm trying to find parameter for FfmpegFrameRecorder.

**Comment by d-a-gerashenko** [comment]
`recorder.setVideoOption("threads", "1");`?
It's very annoying to wait a few days to find out was I right or not)))

**Comment by saudet** [comment]
Check the output of the log. It'll tell you if anything changes.

**Comment by d-a-gerashenko** [comment]
It seems this option solves the issue. But I've got on more problem. Now the thread exits with an exception after a few days:

    org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -542398533: Could not open video codec.
        at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:677)
        at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:357)

I have 4 rtsp cams and 4 recorders. After a few days two of them keep working but another two recorders exit with this exception.

I tried to restart recorders but I got the same result. Working records were keeping working after restarting. Unworking recorders exited with this exception.

It looks like my app accumulates unreleased resources. But I use `FFmpegFrameRecorder.stop()` and this method should release resources because it invokes `release()`: https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/FFmpegFrameRecorder.java#L843

**Comment by d-a-gerashenko** [comment]
May be it's better to open new issue for this problem?

**Comment by saudet** [comment]
Good to hear that helps! If memory or something else is leaking in FFmpeg, it won't help that we're calling all functions to release everything. Since you're getting the same error code (-542398533 is AVERROR_EXTERNAL) you're probably hitting other bugs in x264. You could try to use OpenH264 instead. It's a simpler, less sophisticated encoder, so it might have less bugs in it. If that doesn't help, then at least we'll know the problem isn't in the codec!

**Comment by d-a-gerashenko** [comment]
The cause may be the input data of recorder. I didn't analyze if there were an error for example in time value. Maybe one of my additional objects was broken with a time.

Hope, I will find out it soon.

**Comment by d-a-gerashenko** [comment]
Now I have some more information.

This option solves thread locking problem: `recorder.setVideoOption("threads", "1");`

Now after a few days 2 of 4 recorders still work. I found out the cause is java.lang.OutOfMemoryError. Broken records have higher resolution.

But I don't understand why they stop working after some time. RAM size of java.exe process isn't growing (at the begining of the test it is 524mb and at the end of the test it is 439mb).

May be there is memory leak in native libs? Is it possible that there is memory leak in native libs which I wont see in Windows Task Manager (for java.exe process in "Working Set" column)?

Also I have to say that I have not very good decision in my code:

    for (int pfn = 0, vfn = 0; pfn < 100 && vfn < 10; pfn++) {
            Frame frame = grab().clone();
            if (frame.image != null) {
                hasVideo = true;
                vfn++;
            }
            probeFrames.add(frame);
        }

It's not very good decision. But we need it for FPS calculation without loosing first frames. We have to collect frames because we can't record them before we will found out FPS.

Could it be the cause of the problem?

**Comment by saudet** [comment]
What's the stack trace of that OutOfMemoryError?

Preallocating a list of frames you could reuse over and over would be a better idea than continuously allocating them. It might eventually cause enough memory fragmentation that is preventing the native memory allocator from allocating large enough chunks, and could be what is happening here.

**Comment by d-a-gerashenko** [comment]
Caused by: java.lang.OutOfMemoryError
        at sun.misc.Unsafe.allocateMemory(Native Method)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at org.bytedeco.javacv.Frame.cloneBufferArray(Frame.java:252)
        at org.bytedeco.javacv.Frame.clone(Frame.java:195)

Yep, may be you are right. I didn't want to do preallocation because it's not easy. As I understood there is no functions for this except Frame.clone().

**Comment by d-a-gerashenko** [comment]
May be it's better to serialize these Frames to file?

**Comment by d-a-gerashenko** [comment]
Also I think it would be good not to store this grabbed frames in memory. I think it would be good to have something like grab(Frame toFrame) method. In this way it would be possible to use single frame for multiple operations: grabbing, serialization and etc.

**Comment by saudet** [comment]
There isn't a convenient method to copy a Frame, but we basically just need to copy all fields.

We can enhance FFmpegFrameGrabber in various ways as well, sure, but sometimes there is thread in the background writing asynchronously to the buffer, so it's not always that simple.
