### ISSUE TITLE
App crashes while creating FfmpegFrameRecorder object

### ISSUE THREAD

**Issue by samirk433** [bytedeco/javacv#746]
I manually integrated 'javacv' with Android Studio in my application for live streaming to Youtube.
When I create FFmpegRecorder object the app crashes without throughing any exception.  
`recorder = new FFmpegFrameRecorder(streamLink, imageWidth, imageHeight, 1);` 

I guess I only found this error log, but I don't what does it mean.
**E/dex2oat: Failed to create oat file**

Any help please?

**Comment by saudet** [comment]
No idea. Do the sample project files work?

**Comment by samirk433** [comment]
I haven't check that, although this works alright:
`recorder = new FFmpegFrameRecorder(new File("ff.mp4"), 1);`

I guess I might miss any jar file.
Any idea?

**Comment by saudet** [comment]
Ok, so find more details about the crash. FYI, the mp4 format doesn't
usually support streaming.

**Comment by saudet** [comment]
Please provide the messages that FFmpeg outputs to the log. It won't be possible to debug this without more information.

**Comment by saudet** [comment]
This is apparently caused by Instant Run (IR), so please disable it:
https://stackoverflow.com/questions/45064522/android-app-crashes-at-start-with-e-dex2oat-failed-to-create-oat-file-and-no
