### ISSUE TITLE
Fixed issue #650 persists when using JavaCV 1.3.3 jars

### ISSUE THREAD

**Issue by AmnonOwed** [bytedeco/javacv#747]
Issue #650 was fixed by pull #651.

I saw that JavaCV 1.3.3 was released yesterday, so after downloading it, I replaced the old jars by the new ones from the JavaCV 1.3.3 release. I expected that I would no longer need my CustomOpenCVFrameGrabber class, since the actual OpenCVFrameGrabber has now been changed according to the pull request.

Unfortunately when using the OpenCVFrameGrabber class from JavaCV 1.3.3 I still get the bad performance. When using the CustomOpenCVFrameGrabber I get good performance.

Thing I tried:
- I doublechecked the source of OpenCVFrameGrabber in 1.3.3. which seems ok.
- I doublechecked I was using the new jars (from 25-7-2017) and not the old ones.
- To ensure the latest version was used, I removed the folder: C:\Users\username\javacpp\cache

I'm a bit puzzled why this is occurring...

Any thoughts?

**Comment by saudet** [comment]
If it's the same code, it will do the same thing. There must be some
difference somewhere...

**Comment by AmnonOwed** [comment]
Yeah, indeed. So if it's not this piece of code itself, what could possibly explain this behavior? Are there any other places where files are cached for this library?

I am using the library via a [Processing](https://github.com/processing/processing) sketch. My custom class is inside the Processing class (but relying on other parts of the JavaCV library), whereas the OpenCVFrameGrabber is inside the JavaCV library itself. Would this matter in any way, perhaps for the order of things?

**Comment by saudet** [comment]
Maybe some other of your dependencies are using an older version of JavaCV and overriding your choice?

**Comment by AmnonOwed** [comment]
I've checked to ensure the latest and only the latest jars are used by the sketch (by renaming folders, dropping jars directly into the sketch folder etc.). This is definitely the case.

It's really strange! :) There shouldn't be a different outcome, but there is...

**Comment by saudet** [comment]
Any updates on this? Do you get the same issue with SNAPSHOT artifacts?

**Comment by AmnonOwed** [comment]
No updates. Issue persists with latest Processing 3.3.6 and JavaCV 1.3.3.

It seems that with the OpenCVFrameGrabber class from JavaCV 1.3.3 the format is indeed set to MJPG (unlike with 1.3.2), however without the desired performance improvement. The custom class does give a performance boost. From the initial problem analysis we already found out that the order of things mattered for the performance improvement to occur. Perhaps when using the library there is a another interaction with OpenCV that somehow discards the setting or distorts the working order or something? Or maybe there are static/shared variables that are using in the library, which are different when using a separate, custom instance of the OpenCVFrameGrabber class?

Not familiar with SNAPSHOT artifacts. How can I test this issue against them?

**Comment by saudet** [comment]
There are 1.3.4-SNAPSHOT artifacts available here:
https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/

**Comment by saudet** [comment]
I've just released JavaCV 1.4. Could you try again with that version and let me know if that still happens? Thanks!

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming this has been fixed, but please let me know if this isn't the case.
