### ISSUE TITLE
Strange video output from FFmpegFrameRecorder

### ISSUE THREAD

**Issue by ambikaverma** [bytedeco/javacv#749]
Hi
I'm trying to write an OpenCV mat to a video file.
I first convert the mat to a Bitmap.
Then convert the Bitmap to Frame using AndroidFrameConverter.

The output looks similar to issue #190, though I didn't understand what the exact fix for this problem is.

Thanks.

**Comment by saudet** [comment]
Convert the Mat to a Frame directly.

**Comment by ambikaverma** [comment]
Thanks for your reply.
Since, it is an opencv Mat I cannot directly convert it to frame.
Do you suggest to first convert it to java cv mat?

**Comment by saudet** [comment]
Yes, we can do that:
https://github.com/bytedeco/javacpp/issues/38
