### ISSUE TITLE
Does FFmepgFramRecorder take input files and rtmp publishing streams?

### ISSUE THREAD

**Issue by tuckerthomas** [bytedeco/javacv#751]
How would I be able to output say an mp4 to an rtmp stream using ffmpeg in javacv? I know how to do it with normal ffmpeg, kinda stuck though with this.

**Comment by saudet** [comment]
Sure, check this sample for an example:
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java
