### ISSUE TITLE
Didn't find class "org.bytedeco.javacpp.avutil"

### ISSUE THREAD

**Issue by Immotor** [bytedeco/javacv#753]
Hi. I'm using Javacv to develop a Android APP on macOS Sierra.  Android Studio 2.3.3.  
i added  

compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.3' 

to dependencies.  the opencv function and FFmpegFrameRecorder worked fine, but when i call the FFmpegFrameGrabber the APP crashed. Error:
dlopen("/data/app-lib/com.camm360-1/libjniavutil.so") failed: dlopen failed: cannot locate symbol "av_version_info" referenced by "libjniavutil.so"

**Comment by saudet** [comment]
Does the same thing happen with ffmpeg-3.3.2-1.3.3-SNAPSHOT?

**Comment by Immotor** [comment]
can you please tell me how to use ffmpeg-3.3.2-1.3.3-SNAPSHOT? i added this:
 compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.3.2-1.3.3-SNAPSHOT', classifier: 'android-arm'
to my project. but i got a error:failed to resolve:org.bytedeco.javacpp-presets:ffmpeg:3.3.2-1.3.3-SNAPSHOT.
Thanks

**Comment by saudet** [comment]
You'll need to make sure you have the SNAPSHOT repository set in your pom.xml or setting.xml file, something like: https://github.com/bytedeco/javacpp-presets/blob/master/pom.xml#L118-L130

**Comment by saudet** [comment]
FYI, commit bytedeco/javacpp@f1f21ae should take care of this issue.
