### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by KirilaMenski** [bytedeco/javacv#759]
Greatings! 
Can you guide me? I tried to run this [code](https://github.com/bytedeco/javacv/blob/master/samples/OpenCVFaceRecognizer.java) and all working fine but I don't understand what should I get in  `int predictedLabel = label.get(0);` ? I was always get same number for different persons (something like this 1634361199).

Regards!

**Comment by saudet** [comment]
Make sure to follow this tutorial:
http://docs.opencv.org/2.4/modules/contrib/doc/facerec/facerec_tutorial.html

If you have any problems reproducing the results, let me know!

**Comment by KirilaMenski** [comment]
@saudet Thanks a lot! Everything works great
