### ISSUE TITLE
update to 0.10 [libx264 @ 00000000001c80a0] AVFrame.format is not set

### ISSUE THREAD

**Issue by pengliren** [bytedeco/javacv#76]
transcode video

[libx264 @ 00000000001c80a0] AVFrame.format is not set
[libx264 @ 00000000001c80a0] AVFrame.width or height is not set

**Comment by saudet** [comment]
Fix included in latest version 0.11. Thanks for reporting!

**Comment by zapavtar** [comment]
i have updated ffmpeg but still facing same issue.

here my commad:-

cd hls_videos/;/usr/local/bin/ffmpeg -i rtmp://202.164.44.244/oflaDemo/1/live_video_at_2015_06_02_04_06_32_pm -y -c:v libx264 -b:v 400k -r 27 -vprofile baseline -preset medium -x264opts level=41 -threads 0 -s 360x240 -map 0:v -map 0:a:0 -c:a libfaac -b:a 128k -ac 1 -hls_time 3 -hls_list_size 5 -hls_wrap 6 -start_number 1 live_video_at_2015_06_02_04_06_32_pm.m3u8

Please let me know where i am doing wrong as its very urgent

**Comment by saudet** [comment]
@zapavtar JavaCV doesn't support ffmpeg commands like this, so this would be something to report to the developers of FFmpeg... ?

**Comment by zapavtar** [comment]
OK thanks for you response but it is working on linux and Mac operating system. Issue is on Window 7.

**Comment by saudet** [comment]
@zapavtar Ok, so you could provide the Java code that is working on Linux and Mac, but not on Windows? Thanks

**Comment by zapavtar** [comment]
We are using PHP and execution commands with PHP exec function.
