### ISSUE TITLE
av_write_frame() error -103 while writing audio packet.

### ISSUE THREAD

**Issue by johngag** [bytedeco/javacv#760]
I have an issue where a user go will out of WIFI range on Android while streaming and connect to Cell Data. The error `av_write_frame() error -103 while writing audio packet.` happens and I cant get the service to reliable start again. What is the best way to deal with service dropping and starting again within an Android application?

**Comment by saudet** [comment]
Why can't you restart the service?

**Comment by johngag** [comment]
Do I stop the service the first time this error happens and wait for connectivity again and start back up? I guess I don't know how to properly ensure the service runs if connectivity is lost with RTMP server or how to monitor it is connected with RTMP server.

**Comment by saudet** [comment]
Well, when you get the error, it means you lost the connection. What is
your question?

**Comment by saudet** [comment]
I'm assuming that your issue was resolved, but please let me know if this isn't the case.
