### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path

### ISSUE THREAD

**Issue by yizhongz** [bytedeco/javacv#761]
Hi,

I'm using javacv in aws ec2 instance and I get following errors:
java.lang.UnsatisfiedLinkError: no jniopencv_videoio in java.library.path
Is anybody know how to solve it?

Thanks,
Yizhong

**Comment by saudet** [comment]
Don't use opencv_videoio, you shouldn't need it.

**Comment by saudet** [comment]
AWS EC2 instances don't have any camera devices, so opencv_videoio is not something that is useful for that configuration.

**Comment by salilotr89** [comment]
@saudet 

This is the part where I am struggling with this error : FaceRecognizer faceRecognizer = createLBPHFaceRecognizer();

Can you suggest a workaround to this problem?

**Comment by saudet** [comment]
@salilotr89 If you're talking about #349, then simply install GTK2.
