### ISSUE TITLE
Record video which have face detection

### ISSUE THREAD

**Issue by Levi-ackerman** [bytedeco/javacv#774]
Hi guys,
Thank for great library. I have used javacv to implemented real-time face detection on Android. Now, I want to capture the image or record video which have face detection but I don't know how to do that. Someone please help me.

**Comment by saudet** [comment]
There's sample code and sample projects just for this:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java
https://github.com/bytedeco/sample-projects
