### ISSUE TITLE
FFmpegFrameGrabber hangs on .start() when dealing with InputStream

### ISSUE THREAD

**Issue by mastah84** [bytedeco/javacv#775]
Hello,

FFmpegFrameGrabber blocks in native code when dealing with InputStream.

Class EncodeAndDecode in attached IDEA project. Flow goes like that:

thread 1: grabber grabs frames from webcam and puts them on queue
thread 2: encoder pulls frames from queue and writes encoded/binary data in OutputStream
thread 3: another grabber takes binary from InputStream (OutputStream pushes data to InputStream like a pipe) and tries to read them, but cannot, gets stuck on .start(), specifically here (FFmpegFrameGrabber.java:570):

`        if ((ret = avformat_open_input(oc, filename, f, options)) < 0) {
            av_dict_set(options, "pixel_format", null, 0);
            if ((ret = avformat_open_input(oc, filename, f, options)) < 0) {
                throw new Exception("avformat_open_input() error " + ret + ": Could not open input \"" + filename + "\". (Has setFormat() been called?)");
            }
        }`

???

[webcammy.zip](https://github.com/bytedeco/javacv/files/1258561/webcammy.zip)

**Comment by saudet** [comment]
Have you tried other formats than MP4 and AVI? Those don't support
streaming well.

**Comment by mifritscher** [comment]
You could try https://github.com/bytedeco/javacv/pull/770, which avoids most locks on start() (there was a "big global lock" before on start())

**Comment by mastah84** [comment]
@mifritscher 

synchronized (org.bytedeco.javacpp.avcodec.class) {...} is not a problem here, this lock is acquired perfectly fine. Problem is in FFmpegFrameGrabber.java:570:

if ((ret = avformat_open_input(oc, filename, f, options)) < 0) {

It looks like native code (avformat_open_input) for some reason is unable to deal with PipedInputStream, ie: doesn`t see data (with FileInputStream it works fine).

@saudet 
What other formats may be suitable for my use case? Where can I find more information on that?

**Comment by mastah84** [comment]
I`ve found this:

https://ffmpeg.org/ffmpeg-formats.html#flv_002c-live_005fflv

But with live_flv:
`
        FrameRecorder recorder = new FFmpegFrameRecorder(pos, 1280, 720);
        recorder.setFrameRate(fps);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setFormat("live_flv");
        recorder.setVideoBitrate(800 * 1024);
        recorder.start();
`

I get:

Exception in thread "main" org.bytedeco.javacv.FrameRecorder$Exception: av_guess_format() error: Could not guess output format for "java.io.PipedOutputStream@1d057a39" and live_flv format.
	at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:385)
	at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:357)
	at tests.EncodeAndDecode.main(EncodeAndDecode.java:32)


:-(

**Comment by saudet** [comment]
Usually the Matroska (mkv) format works well for that kind of streaming...

**Comment by saudet** [comment]
I am assuming everything worked out well wit the "mkv" format, but if this isn't the case, please let me know.
