### ISSUE TITLE
Question:how can i play the video and audio synchronously using javacv?

### ISSUE THREAD

**Issue by luzengqi** [bytedeco/javacv#776]
hi,
I used javacv-ffmpeg lib to decode my files on android device, i got each audio and video of frame ,after the audio and video were processed , now, how can I show on the screen out **synchronously**.？
Can provide some clues or demo？

Forget my poor English

**Comment by saudet** [comment]
You'll need to dig into Android's API to figure that out.

**Comment by saudet** [comment]
Here is the answer:
https://developer.android.com/reference/android/media/MediaSync.html
