### ISSUE TITLE
RTMPS With FFMPEG New Version

### ISSUE THREAD

**Issue by webdeutschland** [bytedeco/javacv#779]
Hi @saudet 
How long will it take to get ffmpeg with Javacv V 1.3? I tried to compile by myself but there are some problems, some devices does not recognizes librtmp.so

https://github.com/bytedeco/javacv/issues/399

Maybe if you upload it on maven then it might work !

Regards
Atiq

**Comment by saudet** [comment]
SNAPSHOT artifacts will be available once a pull request gets merged. Please send a pull request.

Duplicate of #399
