### ISSUE TITLE
How to set minimum frame rate?

### ISSUE THREAD

**Issue by kkm** [bytedeco/javacv#790]
![Screenshot](http://capturei.tikatoy.com/r/e4d8.png)

thank you very much.

**Comment by saudet** [comment]
Good question, what does the ffmpeg program call in order to do set that?

**Comment by kkm** [comment]
what does mean? this screenshot is from https://mediaarea.net/

**Comment by saudet** [comment]
FYI, we can add new settings to FFmpegFrameRecorder as shown in pull #939.

**Comment by kkm** [comment]
+1

**Comment by saudet** [comment]
Actually, the "minimum frame rate" reported by that application isn't something we can set, it's just derived from the maximum amount time between 2 frames. In the case of JavaCV, we can insure, for example, 6 fps by never calling `setTimestamp()` with a difference greater than than 1/6 s = 166666 us from the previous call.
