### ISSUE TITLE
About java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.XXX problem

### ISSUE THREAD

**Issue by shiyulong** [bytedeco/javacv#791]
Many friends got such exception, include me! Now I will share my solution。
      Make sure all of the dependencies jar(javacv， javacpp， opencv, ffmpeg.. etc) in your libs, can solve most problems； 
     Otherwise， check -Xss，too small value could result in StackOverflowException which lead to not all of the .so file loaded,  and then got NoClassDefFoundError!  
     I encountered -Xss problem，default set -Xss256k; When modified -Xss1m, all work fine!

**Comment by saudet** [comment]
Thanks! Already documented here:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-and-StackOverflowError-on-Linux
