### ISSUE TITLE
when i try to convert BGRA2YUV_I420 using COLOR_BGRA2YUV_I420,the channels become 1 from 3

### ISSUE THREAD

**Issue by CarlosZhou** [bytedeco/javacv#793]
Mat clone = videoMat.clone();
  Mat cloneYUV = new Mat();
  cvtColor(clone, cloneYUV, COLOR_BGRA2YUV_I420);
  //cvtColor(clone, cloneYUV, CV_BGR2YUV_I420);
  System.out.println(clone.channels()+"==="+cloneYUV.channels());

for all i know,I420 has 3 channels,why become 1
this is my code.the result is :3===1

thank you .

**Comment by saudet** [comment]
That's just how OpenCV works. If you have problems with that, please report this issue upstream.
