### ISSUE TITLE
MatExpr to Mat

### ISSUE THREAD

**Issue by FiV0** [bytedeco/javacv#794]
Sorry if this has been documented somewhere, but I couldn't find it in the docs.

How for example do I convert the following to a normal matrix.
`Mat.eye(3, 3, CV_64F)`

The following compiled but gave me a Runtime error later on.
`Mat identity = new Mat(Mat.eye(3, 3, CV_64F));`

Also the [documentation](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Mat.html#eye-int-int-int-) is not very helpful in that case.

**Comment by saudet** [comment]
The answer is [`MatExpr.asMat()`](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.MatExpr.html#asMat--).

**Comment by saudet** [comment]
BTW, if you could make a contribution and document those things on the wiki, it would be very welcome!
