### ISSUE TITLE
Copying to a ROI.

### ISSUE THREAD

**Issue by FiV0** [bytedeco/javacv#795]
In Python you can copy an image to a ROI as follows.
`>>> img[273:333, 100:160] = img2`

What is the correct way to do this with the new API?

**Comment by saudet** [comment]
Should be the same thing:
```java
img.apply(new Range(273, 333), new Range(100, 160)).put(img);
```
Let me know if that doesn't work for some reason, and please consider making a contribution!

**Comment by FiV0** [comment]
I tried the following in a clean project. Not the desired result.

    Mat img1 = new Mat(500, 500, CV_8UC4, new Scalar(0,0,255,0));
    Mat img2 = new Mat(1000, 1000, CV_8UC4, new Scalar(0,255,0,0));

    imwrite("./test1.jpg", img1);
    imwrite("./test2.jpg", img2);

    img2.apply(new Range(250, 750), new Range(250, 750)).put(img1);
    imwrite("./test3.jpg", img2);

**Comment by saudet** [comment]
Would you have an example in C++? JavaCPP maps the C++ API...

**Comment by FiV0** [comment]
I don't think the problem is with OpenCv but rather with your mapping. If I understand your `@ByVal` correctly, the code [here](https://github.com/bytedeco/javacpp-presets/blob/90881898f1c7bcc51722a9c33e948fcf267b537a/opencv/src/main/java/org/bytedeco/javacpp/opencv_core.java#L16241-L16251) shoud be annotated `@ByRef`. 

Let me know if that is correct and I create a pull request.

**Comment by saudet** [comment]
We can't return new objects by reference in C++. In any case, the C++ API of OpenCV uses Mat values there, so that's not the problem.

**Comment by FiV0** [comment]
Ok. Nevermind my bad. 
The correct way to do the assignment is as follows:
`img1.copyTo(img2.apply(new Range(250, 750), new Range(250, 750)));`

**Comment by saudet** [comment]
Yes, I know that works. But if you know it's also supposed to work in C++ like it does in your Python code, let me know and I'll look into it. Thanks!

**Comment by FiV0** [comment]
Well I did what you said and tried it in C++ and thought it was a bug in OpenCV. So to no longer bother you I asked over [there](https://github.com/opencv/opencv/issues/9722), but apparently the `put` (= in C++) is a pointer assignment and therefore the correct way to do it is as above.

**Comment by saudet** [comment]
Great, thanks for checking this out!
