### ISSUE TITLE
capture audio from rtmp stream in javacv

### ISSUE THREAD

**Issue by zchacker** [bytedeco/javacv#797]
Hi i am using FFmpegFrameGrabber class but it show just the video and no audio , what the method should i use to get audio

**Comment by saudet** [comment]
We can use Java Sound for that, or AudioTrack on Android. It's also possible to use JavaFX. Here's a sample thanks to @d-a-gerashenko:
https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java

**Comment by saudet** [comment]
To capture sound on Android, we can use AudioRecord:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java
And in the case of Java SE, we can use Java Sound:
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java
