### ISSUE TITLE
JavaCV 0.5 SIGILL error with Android Studio ARM emulator

### ISSUE THREAD

**Issue by diedel** [bytedeco/javacv#799]
Hello there,

I have an strange problem with an Android APP using JavaCV 0.5 (using the arm-v7a jniLibs).

When executing the APP in a real Samsung Galaxy A5 (2016) with Android 7.0 it works as expected. But when running it in the Android ARM emulator it crashes with SIGILL error related to **libttb.so** library. You can see the logcat in the attached file.

I tried to run the APP in the Android Studio ARM emulator with different Android versions (from 4.4 to 7.0), and always crashes with a SIGILL (sometimes also on **libopencv_contrib.so**).

I need that old JavaCV 0.5 version because I need to reproduce a previous APP running environment.

[Github JavaCV issue.txt](https://github.com/bytedeco/javacv/files/1348450/Github.JavaCV.issue.txt)

**Comment by saudet** [comment]
It just means your CPU is too old. You could build (very slow) binaries for
that device though. Check the instructions in the README.md file in the
javacpp-presets repo.

**Comment by diedel** [comment]
Do you mean that the emulated CPU (e.g. Nexus 5) of the Android Studio emulator is old?

**Comment by saudet** [comment]
Yes, you're emulating an old CPU.

BTW, why not use the x86 emulator?

**Comment by diedel** [comment]
Sorry...
I just tested the APP with Nexus 5X Android 7.0 emulator and it doesn't crash!

I cannot use x86 emulator because I don't have the JavaCV 0.5, JavaCPP, etc. .so libs of the x86 architecture for Android.

**Comment by diedel** [comment]
I just tested the ARM emulator again.
With Nexus 5X Android 7.0 and Nexus 5X Android 6.0 the APP works successfully.

It returns SIGILL with Nexus 5X Android 5.0, so the problem doesn't seem to be a too old CPU...

**Comment by saudet** [comment]
I remember it working on old versions of the emulator, so you might want to try that as well...
