### ISSUE TITLE
skin color detection 

### ISSUE THREAD

**Issue by tehseenmayar** [bytedeco/javacv#801]
hey guys!
i am trying to detect skin color inside an image using opencv and i have detected that skin color area but that skin color area is filled with white color and i want that area to be filled with skin color.. actually i want to detect hand inside image.. here is my code.any help would be appreciated.
` Mat hsv=new Mat();
Mat skin=new Mat();
Imgproc.cvtColor(srcHSV,hsv,Imgproc.COLOR_BGR2HSV);
 Core.inRange(hsv,new Scalar(0,58,40),new Scalar(35,174,255),skin);`

i got the attached image from the above code but i want that white area to be filled with the detected skin color
![hand1](https://user-images.githubusercontent.com/29973339/31184262-ba632066-a8dd-11e7-86a6-8a679f2216e2.png)

**Comment by saudet** [comment]
You could use that image as mask with `Mat.copyTo()`.

**Comment by tehseenmayar** [comment]
thanks a lot.. that works pretty well..  i love this community.
