### ISSUE TITLE
JNI EXCEPTION : NoSuchMethodError: no static method "Lorg/bytedeco/javacpp/Loader;.putMemberOffset(Ljava/lang/String;Ljava/lang/String;I)V

### ISSUE THREAD

**Issue by fabiopires77** [bytedeco/javacv#802]
Hello,

I'm trying to upgrade my javacpp/javacv/opencv library for Android 7.1.2 and I'm getting this error: "JNI EXCEPTION : NoSuchMethodError: no static method "Lorg/bytedeco/javacpp/Loader;.putMemberOffset(Ljava/lang/String;Ljava/lang/String;I)V"

In my gradle dependencies section I have this:
compile group: 'org.bytedeco', name: 'javacv', version: '1.3.3'
compile group: 'org.bytedeco', name: 'javacpp', version: '1.3.3'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.1.0-1.2', classifier: 'android-x86'

Could you please tell me what's wrong?

**Comment by saudet** [comment]
We can't use binaries for JavaCPP 1.2 with JavaCPP 1.3. You'll need to use binaries for JavaCPP 1.3. But please just use JavaCPP and JavaCV 1.4.1 now that they have been released, something like this:
```groovy
compile group: 'org.bytedeco', name: 'javacv', version: '1.4.1'
compile group: 'org.bytedeco', name: 'javacpp', version: '1.4.1'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: 'android-x86'
```
