### ISSUE TITLE
Request: How to create standard mp4 with bitmaps and one audio mp3 with javacv 1.3.3

### ISSUE THREAD

**Issue by farzadnone** [bytedeco/javacv#803]
Hi,i use javacv 1.3.3 with android studio 2.2.2. i want create **_standard(play on all devices android,ios,desktop...)_** mp4 video with series of bitmaps(decoded from jpg) with mp3 audio. all post about this are old and not fix. i need new code with javacv 1.3.3. please suggest me method for this target. thanks

**Comment by saudet** [comment]
Try to use the settings given here:
https://trac.ffmpeg.org/wiki/Encode/H.264

**Comment by farzadnone** [comment]
hi samuel.
i use this command. but when send output video via telegram, telegram unknown format file. it send video via file. no video. after send from android to ios phone, on ios, video have not sound. only movie without sound. why?

`-framerate 1 -y -i /storage/emulated/0/ax%04d.jpg -i /storage/emulated/0/mp3.mp3 -s 600x600 -c:v libx264 -preset slow -crf 22 -x264-params keyint=123:min-keyint=20 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -b:a 128k -movflags +faststart -b 4M -acodec copy -f mp4 /storage/emulated/0/nmccjj.mp4`

**Comment by farzadnone** [comment]
i tested on this app:

[https://github.com/writingminds/ffmpeg-android-java/releases/download/v0.3.2/app-debug.apk](https://github.com/writingminds/ffmpeg-android-java/releases/download/v0.3.2/app-debug.apk)

from:

[https://github.com/WritingMinds/ffmpeg-android-java](https://github.com/WritingMinds/ffmpeg-android-java)

**Comment by farzadnone** [comment]
@saudet 
I want to make a video with 4 photos for the Android platform. 4 months ago but I have not been able to. Each method has a series of bugs and problems. Tired It's so snappy. Apps like [VideoShow](https://play.google.com/store/apps/details?id=com.xvideostudio.videoeditor&hl=en), how do they do that easily? What method?

**Comment by farzadnone** [comment]
Fixed.
[https://stackoverflow.com/a/40995407/4910154](https://stackoverflow.com/a/40995407/4910154)

**Comment by saudet** [comment]
FYI, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
