### ISSUE TITLE
OSX 1.3.3 using Maven, getting unable to find avutil class, works with 1.2

### ISSUE THREAD

**Issue by sqlboy** [bytedeco/javacv#804]
Trying to upgrade our dependency from 1.2 to 1.33, all 1.3 builds fail with unable to find the avutil class. This is in IDEA on OSX.

**Comment by saudet** [comment]
Please provide the full stack trace of the error.

**Comment by saudet** [comment]
You probably just forgot to change also the artifact name from `javacv` to `javacv-platform`. If you are still have issues after that, please let me know! Thanks
