### ISSUE TITLE
The method get(int, int, byte[]) is undefined for the type opencv_core.Mat

### ISSUE THREAD

**Issue by gengstah** [bytedeco/javacv#807]
Please excuse my noob question.

I can't find this method in Mat class: [org.opencv.core.Mat.get(int row, int col, byte\[\] data)](http://grepcode.com/file/repo1.maven.org/maven2/org.friendularity/org.friendularity.bundle.jvision/1.0.0/org/opencv/core/Mat.java#Mat.get%28int%2Cint%2Cbyte%5B%5D%29)

I get a compile time error: _The method get(int, int, byte[]) is undefined for the type opencv_core.Mat_
What am I missing?

My goal is to convert Mat to byte array.

**Comment by saudet** [comment]
It doesn't exist. Use [Mat(int rows, int cols, int type, Pointer data)](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Mat.html#Mat-int-int-int-org.bytedeco.javacpp.Pointer-) instead.

**Comment by saudet** [comment]
For completeness, we can call `new BytePointer(byte[])` to get a `Pointer` for that constructor and then use `CV_8UC()` for the type.
