### ISSUE TITLE
Missing jars on Linux deployment

### ISSUE THREAD

**Issue by phelgren** [bytedeco/javacv#809]
I have a servlet application that I build in Eclipse on Windows (10) did quite a bit of testing in Tomcat 8 on Windows and then deployed to Tomcat 8 on CentOS7.  As the servlet loads I see the following errors in the catalina.out log (This is just a partial list of the missing libs):
 java.io.FileNotFoundException: /opt/tomcat/lib/android-4.1.1.4.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-main-2.3.1.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-android-aarch64.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-android-armv6.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-linux-amd64.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-linux-armv6.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-linux-armv6hf.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-linux-i586.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-macosx-universal.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-solaris-amd64.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-solaris-i586.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-windows-amd64.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/gluegen-rt-2.3.1-natives-windows-i586.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-main-2.3.1.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-android-aarch64.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-android-armv6.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-linux-amd64.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-linux-armv6hf.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-linux-i586.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-macosx-universal.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-solaris-amd64.jar (No such file or directory)
 java.io.FileNotFoundException: /opt/tomcat/lib/jogl-all-2.3.1-natives-solaris-i586.jar (No such file or directory)

There are dozens of these missing files...so the question is:  Do I need to build differently when building on Windows and deploying to CentOS7 ? I used maven to build the servlet and put the required libs in the tomcat/lib folder....what did I miss?

**Comment by saudet** [comment]
You don't need them if you're not using GLCanvasFrame, and you're probably not using that on the server side, so you can ignore those.

**Comment by phelgren** [comment]
Thanks...looked with better eyes this morning and the file not found entries are warnings, not errors so, yes, I'll just ignore them.
