### ISSUE TITLE
Error loading class in FFmpegFrameRecorder

### ISSUE THREAD

**Issue by bakua** [bytedeco/javacv#81]
Dear guys,
I have a Android Studio project with:

````
compile 'org.bytedeco:javacv:0.10'
compile 'org.bytedeco:javacpp:0.10'
compile 'org.bytedeco.javacpp-presets:ffmpeg:2.5.1-0.10'
compile 'org.bytedeco.javacpp-presets:opencv:2.4.10-0.10'
````

And I'd like to instantiate FFmpegFrameRecorder. But as soon as I call:

    new FFmpegFrameRecorder(path, outputResolution.getWidth(), outputResolution.getHeight(), 1);

The app crashes. There is no exception stack trace or anything, only this error message in LogCat:
**E/javacpp﹕ Error loading class com/googlecode/javacpp/Loader.**

I have debugged it and it happens in tryLoad() method during the call of:

````
Loader.load(org.bytedeco.javacpp.avutil.class);
Loader.load(org.bytedeco.javacpp.swresample.class);
Loader.load(org.bytedeco.javacpp.avcodec.class);
Loader.load(org.bytedeco.javacpp.avformat.class);
Loader.load(org.bytedeco.javacpp.swscale.class);
````

Do you please have any idea what can be wrong? I was using some old version of JavaCV(with old package, same as is in error) and I need to update it.

Thank you,
bakua

**Comment by saudet** [comment]
Have you set the `platform.dependency` system property somewhere for Gradle and the Android platform? I don't know how to do it myself, and it might not work with Android anyway. So, if all else fails, please try the manual installation instructions here:
https://github.com/bytedeco/javacv#manual-installation
That works fine for me. Does any of that work for you?

**Comment by bakua** [comment]
Hello :) Thanks for your reply. I did some research on your answer and I didn't found any way hot to set platform.dependecy with Android Studio.

Also I've tried manual installation and downloaded all jars from maven repo. Or is it like I should download only JavaCV jars from maven repo and then download other libraries from somewhere else?

Though I think that it is not problem in opencv or ffmpeg because it says it can't find Loader class which is locaten in JavaCPP library.

Thank you

**Comment by saudet** [comment]
I guess what you're doing is fetching an old version of JavaCPP for some reason.

Anyway, what happens when you put all the JAR files manually in your project?

**Comment by bakua** [comment]
That is the first thing I tried. Do you think it can be possible that some
of .so libraries for ffmpeg or opencv require old javacv version?

Thanks

**Comment by saudet** [comment]
No, they were all built together and I verified that they do actually work. Please make sure to provide any information about what happens when you try to follow the instructions. Everything works fine here, so I can't fix what isn't broken! Thank you

**Comment by bakua** [comment]
Sorry, that is not what I meant. I wanted to know if I have to update .so files as well when I am updating to newer .jar libraries. For exaple everytime avutil.java is updated, do I usually need to update libavutil.so as well?

**Comment by saudet** [comment]
Yes, of course.

**Comment by bakua** [comment]
And is there any place where we can download latest .so files compiled for armeabi-v7a please? Or is the only possibility to build it ourselves.

Thank you

**Comment by saudet** [comment]
It's all given here:
https://github.com/bytedeco/javacv#downloads
For example inside this archive:
http://search.maven.org/remotecontent?filepath=org/bytedeco/javacv/0.10/javacv-0.10-bin.zip

**Comment by bakua** [comment]
Oh thank you very much, it is working now :) I've missed that important piece of information that .so files are in .jar files of according library. Your suggestions were very helpful :)

Also someone might find this interesting http://stackoverflow.com/questions/20890116/javacv-android-studio-gradle-possible

Have a nice day
