### ISSUE TITLE
calcHist returns Mat with hight, width == -1

### ISSUE THREAD

**Issue by Claus1** [bytedeco/javacv#812]
code for reproducing https://github.com/bytedeco/javacv-examples/blob/master/OpenCV2_Cookbook/src/main/scala/opencv2_cookbook/chapter04/ColorHistogram.scala

```
def getHistogram(image: Mat): Mat = {

    require(image != null)
    require(image.channels == 3, "Expecting 3 channel (color) image")

    // Compute histogram
    val hist = new Mat()

    // Since C++ `calcHist` is using arrays of arrays we need wrap to do some wrapping
    // in `IntPointer` and `PointerPointer` objects.
    val intPtrChannels = new IntPointer(0, 1, 2)
    val intPtrHistSize = new IntPointer(numberOfBins, numberOfBins, numberOfBins)
    val histRange = Array(_minRange, _maxRange)
    val ptrPtrHistRange = new PointerPointer[FloatPointer](histRange, histRange, histRange)
    calcHist(image,
      1, // histogram of 1 image only
      intPtrChannels, // the channel used
      new Mat(), // no mask is used
      hist, // the resulting histogram
      3, // it is a 3D histogram
      intPtrHistSize, // number of bins
      ptrPtrHistRange, // pixel value range
      true, // uniform
      false) // no accumulation
    hist
  }
```

**Comment by saudet** [comment]
Could you also provide the image you would like to process?

**Comment by Claus1** [comment]
Any image will produce wrong Mat.

**Comment by saudet** [comment]
Would you have by any chance working code in C++?

**Comment by Claus1** [comment]
Nope, I use Scala.

**Comment by Claus1** [comment]
May be debugger screenshot would help
![image 2](https://user-images.githubusercontent.com/1247062/31553723-989cfa26-b065-11e7-9f07-a56dee37cebd.png)

**Comment by saudet** [comment]
I know you are using Scala. I'm asking if you know of a way to make it work
in C++. Do you know of an example that does what you want in C++?

**Comment by Claus1** [comment]
Not sure C++ can help because I bet the issue in the wrapper, but ok  
```
 cv::SparseMat getSparseHistogram(const cv::Mat &image) {
      cv::Mat hist();
      // Compute histogram
      cv::calcHist(&image, 
         1,            // histogram of 1 image only
         channels,   // the channel used
         cv::Mat(),   // no mask is used
         hist,         // the resulting histogram
         3,            // it is a 3D histogram
         histSize,   // number of bins
         ranges      // pixel value range
      );
      return hist;
   }
```
Borrowed from OpenCV 2 Computer Vision Application Programming Cookbook page 107.
SparseMat was replaced to Mat because  SparseMat is not in javacv.

**Comment by saudet** [comment]
Thanks! What are the values of histSize and ranges?

**Comment by Claus1** [comment]
I checked with range = array(0.0f, 255.0f),  histSize = 256

**Comment by Claus1** [comment]
from Cookbook page 95 in printed one or 106 in pdf 
```
  the histogram will be three-dimensional. Therefore, we need to specify a range for 
each of the three dimensions. In the case of a BGR image, the three channels have the same 
[0,255] range. With the arguments thus prepared, the color histogram is computed by the 
following method:
   cv::MatND getHistogram(const cv::Mat &image) {
      cv::MatND hist;
      // Compute histogram
      cv::calcHist(&image, 
         1,            // histogram of 1 image only
         channels,   // the channel used
         cv::Mat(),   // no mask is used
         hist,         // the resulting histogram
         3,            // it is a 3D histogram Counting the Pixels with Histograms 96
         histSize,   // number of bins
         ranges      // pixel value range
      );
      return hist;
   }
A three-dimensional cv::Mat instance is returned. This matrix has (256)*3 elements which 
represents more than 16 million entries. 
```

**Comment by saudet** [comment]
Ok, so they don't give a working example. If you find one, let me know, it
will make things easier to debug.

**Comment by Claus1** [comment]
```
You can check for example Ex7ContentDetectionColor from  javacv-examples 
set breakpoint at line 40 and inspect hist object.
```
;)

**Comment by saudet** [comment]
Yes, but you say that doesn't work. There must be a working example that
exists somewhere in C++. I'll repeat one last time: If you could help me
help you it would be very much appreciated.

**Comment by Claus1** [comment]
No. The code works. Calculated pics are ok (possibly). But anyway the problem exists: 
`calcHist returns Mat with hight, width == -1` The error object is successfully (maybe not)  used in the code.
I wrote about it here https://groups.google.com/forum/#!topic/javacv/zHoLD2cZXMM .
The same C++ code from the book here https://github.com/vinjn/opencv-2-cookbook-src/blob/4ead39275a511101efdbd4ae958140aa8f39ca92/Chapter%2004/histograms.cpp
see Line 40 .

**Comment by saudet** [comment]
That helps, thank you! So histSize and hranges are defined like this
```cpp
int histSize[1];
float hranges[2];
```

**Comment by saudet** [comment]
I see what the issue is. We need to be able to pass in a `MatND`, not a `Mat`.

**Comment by saudet** [comment]
But `cv::MatND` is just a typedef of `cv::Mat`, and we get the same results in C++ (width and height == -1), so this is working normally. If you believe there is something wrong with OpenCV, please post an issue upstream. Thank you!

**Comment by LizzieOneDay** [comment]
> code for reproducing https://github.com/bytedeco/javacv-examples/blob/master/OpenCV2_Cookbook/src/main/scala/opencv2_cookbook/chapter04/ColorHistogram.scala
> 
> ```
> def getHistogram(image: Mat): Mat = {
> 
>     require(image != null)
>     require(image.channels == 3, "Expecting 3 channel (color) image")
> 
>     // Compute histogram
>     val hist = new Mat()
> 
>     // Since C++ `calcHist` is using arrays of arrays we need wrap to do some wrapping
>     // in `IntPointer` and `PointerPointer` objects.
>     val intPtrChannels = new IntPointer(0, 1, 2)
>     val intPtrHistSize = new IntPointer(numberOfBins, numberOfBins, numberOfBins)
>     val histRange = Array(_minRange, _maxRange)
>     val ptrPtrHistRange = new PointerPointer[FloatPointer](histRange, histRange, histRange)
>     calcHist(image,
>       1, // histogram of 1 image only
>       intPtrChannels, // the channel used
>       new Mat(), // no mask is used
>       hist, // the resulting histogram
>       3, // it is a 3D histogram
>       intPtrHistSize, // number of bins
>       ptrPtrHistRange, // pixel value range
>       true, // uniform
>       false) // no accumulation
>     hist
>   }
> ```

hello, how did you solve this problem?
