### ISSUE TITLE
send a video file as stream without recomression

### ISSUE THREAD

**Issue by samokhodkin** [bytedeco/javacv#814]
Hi,
I want to achieve with JavaCV something analogous to this ffmpeg command:

ffmpeg -re -i video.avi  rtmp://...

which just copies the file contents to the stream.

There are few code samples that perform similar task with FFmpegFrameGrabber + FFmpegFrameRecorder.
As far as I can see the data in these samples are decompressed by the grabber and compressed again by the recorder. How can I skip the decomression+compression steps and send the data as is?

**Comment by saudet** [comment]
Yes, https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by saudet** [comment]
It's also possible to pass on the packets directly:
https://github.com/bytedeco/javacv/blob/master/samples/PacketRecorderTest.java#L53
