### ISSUE TITLE
How to record two cameras at the same time?

### ISSUE THREAD

**Issue by rex19001** [bytedeco/javacv#816]
I used the thread to perform the method, but it can only open a camera

```
public static void main(String[] args) throws Exception, InterruptedException {
		start(0);
		new Thread(new Runnable() {
			@Override
			public void run() {
				try {
					start(1);
				} catch (Exception | InterruptedException e) {
					e.printStackTrace();
				}
			}
		}).start();
	}
	
	private static void start(int camera) throws Exception, InterruptedException {
		OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(camera);    
	    grabber.start();   
	    CanvasFrame canvas = new CanvasFrame("摄像头");
	    canvas.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
	    canvas.setAlwaysOnTop(true);  
	      
	    while(true)  
	    {  
	        if(!canvas.isDisplayable())  
	        {
	            grabber.stop();
	            System.exit(2); 
	        }  
	        canvas.showImage(grabber.grab());
	  
	        Thread.sleep(50);
	    }  
	}
```

**Comment by saudet** [comment]
What happens when you try to create a second instance of OpenCVFrameGrabber to grab from another camera?

**Comment by rex19001** [comment]
Nothing happens..And there is no error message.

**Comment by saudet** [comment]
So, everything is fine, then, right?

**Comment by rex19001** [comment]
No, it can only record a camera.I need it to record two cameras at the same time.

**Comment by saudet** [comment]
So, what happens when you call `grab()` on the second instance of `OpenCVFrameGrabber`?

**Comment by rex19001** [comment]
It does not execute the thread.
The implementation of the "start(0)", it stopped.

**Comment by saudet** [comment]
Well, you'll need to find an error message or I won't be able to debug this. FWIW, FFmpeg is better than OpenCV at capturing from cameras, so you should consider using that:
https://trac.ffmpeg.org/wiki/Capture/Webcam

**Comment by rex19001** [comment]
Execute this method in the thread, it prompts:
org.bytedeco.javacv.FrameGrabber$Exception: read() Error: Could not read frame in start().
	at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:212)
	at ha.start(ha.java:26)
	at ha.access$0(ha.java:24)
	at ha$1.run(ha.java:16)
	at java.lang.Thread.run(Thread.java:745)

**Comment by saudet** [comment]
Ok, so try to use FFmpegFrameGrabber instead...

**Comment by saudet** [comment]
I'm assuming this is working fine with FFmpegFrameGrabber, but let me know if you still have issues.
