### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.BytePointer.getInt(J)I

### ISSUE THREAD

**Issue by Radisvoik** [bytedeco/javacv#819]
I've been trying to figure out what I could be doing wrong to cause this -- I've done all kinds of things.. from grabbing all the jars with their natives, unjarring out the dynamic libs and putting them on an explicit System.lib.path -- and just about everything I can think of.. but I can't seem to get around this exception.   Here is the base case that reproduces the problem. (you'd need to supply your own avi file)..  and according to readme.MD file.. this should work just fine.. but it results in the same problem I'm having.  

I'd try to fix it myself -- but once we get into the realm of  building native code my skills don't match up so well.  

Here are the steps to reproduce..  

in ./src/main/java/Demo.java
```java

public class Demo {
    public static void main(String[] args) throws Exception {
        String filename = "d:/2016oct30-00-05.avi";
        final FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(filename);
        frameGrabber.start();
        org.bytedeco.javacv.Frame f =  frameGrabber.grab();
        OpenCVFrameConverter.ToIplImage toIplImage = new OpenCVFrameConverter.ToIplImage();
        IplImage convert = toIplImage.convert(f);
        BytePointer bytePointer = convert.imageData();
        /**
         * BOOOOME
         * Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.BytePointer.getInt(J)I
         */
        int anInt = bytePointer.getInt();
    }
}
```
along with this ./pom.xml
```xml
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.bytedeco.javacv</groupId>
    <artifactId>demo</artifactId>
    <version>1.3.3</version>
    <dependencies>
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.3.3</version>
        </dependency>
    </dependencies>
</project>
```
and then run with this mvn command from . 

```bash
mvn compile exec:java -Dexec.mainClass=Demo
```

Fails with the exception in the subject line.

**Comment by Radisvoik** [comment]
ahh.. I did just find something.  If I go back to 1.3.2... that getInt() method generates a compiler error!.  So is this a case where 1.3.3 is grabbing old dynamic libraries from 1.3.2?

**Comment by saudet** [comment]
Please try to follow the instructions here and let me know what you get:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by saudet** [comment]
`BytePointer.getInt()` requires binaries that were compiled for/with JavaCPP 1.3.3 or later, which isn't the case of the ones available on Maven right now. Just call `new IntPointer(bytePointer).getInt()`, it will do the same thing.
