### ISSUE TITLE
Unable to load haar classifier

### ISSUE THREAD

**Issue by Elie-kahwaji** [bytedeco/javacv#82]
Hello ,

I am trying to load the haarcascade_frontalface_alt.xml downloaded from https://github.com/Itseez/opencv/tree/master/data/haarcascades

i am getting the following error Unspecified error (The node does not represent a user object (unknown type?)) 

Code : cvLoadHaarClassifierCascade(haarcascade_frontalface_alt.xml, cvSize(0, 0));
Thank you

**Comment by saudet** [comment]
The ones in the `master` branch are not compatible with OpenCV 2.4.x. Try the ones from the 2.4 branch: https://github.com/Itseez/opencv/tree/2.4/data/haarcascades
