### ISSUE TITLE
Problem Class Utils in javacv

### ISSUE THREAD

**Issue by fazelit** [bytedeco/javacv#823]
Cannot Find Class Utils In javacv Bu exist in opencv !!!!
How use class Utils in javacv?
link:
https://docs.opencv.org/java/2.4.2/org/opencv/android/Utils.html

**Comment by saudet** [comment]
That's not part of the C++ API of OpenCV, so you'll to use that Java API
directly if you need it.

**Comment by fazelit** [comment]
Please write an example of how to use Utils code with java Api.
tanks
