### ISSUE TITLE
opencv_imgcodecs.cvLoadImage from BytePointer returning null

### ISSUE THREAD

**Issue by JavaMachine** [bytedeco/javacv#824]
Hello fellow developers,

Assume that image files are stored in database (postgresql bytea) and I have static method that returns byte[] from database.

Following code is used to load IplImage.

```
byte[] imgData = DB.getFile(id); //id is int type variable
if(imgData == null) {
    Logger.error("file not found");
    return;
}
if(imgData.length == 0) {
    Logger.error("file not found");
    return;
}

BytePointer bytePointer = new BytePointer(imgData);
opencv_core.IplImage image = opencv_imgcodecs.cvLoadImage(bytePointer);
if(image == null) {
    Logger.error("could not load file");
    return;
}
//processing image here
}
```

Condition "image == null" is always true.

I am using "javacv-platform-1.3.3"

Where and what am I doing wrong?

Thanks in advance.

**Comment by saudet** [comment]
You need to use 1cvDecodeImage()` for that, something like this:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/IPCameraFrameGrabber.java#L162-L165
