### ISSUE TITLE
Questions about using FFmpegFrameRecorder in Sample RecordActivity.java

### ISSUE THREAD

**Issue by JochimY** [bytedeco/javacv#829]
Hi,
May I ask two things that make me feel confused when using FFmpegFrameRecorder to generate a mp4 video file?
1. The first thing is what the maximum imageWidth and imageHeight I can put when create a new Frame instance? For when I put imageWidth to 1920 and imageHeight to 1080 which is the screen size, the code is just crashed and  output this error:
```  
JNI DETECTED ERROR IN APPLICATION: JNI NewStringUTF called with pending exception java.lang.OutOfMemoryError: Failed to allocate a 8294419 byte allocation with 7573048 free bytes and 7MB until OOM
```
    And when I scale the imageWidth and imageHeight below 1000, it works fine.
2. The another is what format of the byte[] data is FFmpegFrameRecorder.record() supported? When I putting RGBA byte[] data into Frame and calling record(Frame frame) to generate video, it just got nothing but black, I don't know what is wrong.  
Here is part of my code:
```  
  images = new Frame[RECORD_LENGTH * frameRate];
        timestamps = new long[images.length];
        for (int i = 0; i < images.length; i++) {
            images[i] = new Frame(imageWidth, imageHeight, Frame.DEPTH_UBYTE, 4);
            timestamps[i] = -1;
        }
// if imageWidth = 1920 and imageHeight=1080, it got OOM crash
 mRecorder = new FFmpegFrameRecorder(path, imageWidth, imageHeight, 1);
        
        mRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        mRecorder.setFormat("mp4");
        mRecorder.setSampleRate(sampleAudioRateInHz);
        mRecorder.setFrameRate(frameRate);
```  
Thanks for help!

**Comment by saudet** [comment]
1. Get a device with more memory... ?
2. We can specify whatever format needed with this the overloaded method [FFmpegFrameRecorder.record(Frame frame, int pixelFormat)](http://bytedeco.org/javacv/apidocs/org/bytedeco/javacv/FFmpegFrameRecorder.html#record-org.bytedeco.javacv.Frame-int-)
