### ISSUE TITLE
Problem changing profile

### ISSUE THREAD

**Issue by jkolobok** [bytedeco/javacv#83]
FFmpegFrameRecorder  has line which sets profile
```java
                video_c.profile(AVCodecContext.FF_PROFILE_H264_CONSTRAINED_BASELINE);
```
However result file when it works has 'High 4:4:4 Predictive'
```
  Metadata:
    encoder         : Lavf56.15.105
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv420p, 624x460, 1000 kb/s, 10 tbr, 1k tbn, 20 tbc
    Stream #0:1: Audio: mp3, 44100 Hz, mono, s16p, 352 kb/s
   5.17 A-V:  0.086 fd= 129 aq=    0KB vq=    0KB sq=    0B f=0/0
```

When I change it for example to main profile(same problem with other profiles) 
I get an error opening codec:
```
org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open video codec.
```
With the following output from ffmpeg:
```
Output #0, flv, to 'myfile.f4v':
    Stream #0:0: Video: h264 (libx264), yuv420p, 624x460, q=-1--1, 1000 kb/s, 10 tbn, 10 tbc
    Stream #0:1: Audio: mp3 (libmp3lame), 44100 Hz, mono, s16, 352 kb/s
x264 [error]: main profile doesn't support lossless
[libx264 @ 0000000000240140] Error setting profile main.
[libx264 @ 0000000000240140] Possible profiles: baseline main high high10 high422 high444
```

**Comment by saudet** [comment]
I'm pretty sure x264 doesn't use the `FF_PROFILE_H264_CONSTRAINED_BASELINE` flag, so I don't think that is related.

To change the profile, have you tried to call something like `setVideoOption("profile", "baseline")`? And if so, what error do you get?

**Comment by saudet** [comment]
Does the same error happen with version 1.0 as well?

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming that everything works fine with JavaCV 1.0, but let me know if this isn't the case! Thank you
