### ISSUE TITLE
How to connect DC1394 camera

### ISSUE THREAD

**Issue by SilviaDeng** [bytedeco/javacv#831]
Hi,

I am try to use javacv to detect and connect CMU 1394 Digital camera device. I use DC1394FrameGrabber to get the device. However, it show the issue as below:

run:
```
OpenCV Error: Input image depth is not supported by function (Unsupported format) in cvInitImageHeader, file src\array.cpp, line 2943
Exception in thread "main" java.lang.RuntimeException: src\array.cpp:2943: error: (-17) Unsupported format in function cvInitImageHeader

	at org.bytedeco.javacpp.opencv_core.cvCreateImage(Native Method)
	at org.bytedeco.javacpp.helper.opencv_core$AbstractIplImage.create(opencv_core.java:348)
	at org.bytedeco.javacpp.helper.opencv_core$AbstractIplImage.create(opencv_core.java:359)
	at org.bytedeco.javacv.DC1394FrameGrabber.grab(DC1394FrameGrabber.java:497)
	at JavaCvDriverExample.main(JavaCvDriverExample.java:59)
```

Could you kindly give me some suggestion about this issue.
------------------------------------------------------------------------------------------------------

This is my code:

```java
import javax.swing.JFrame;
import org.bytedeco.javacpp.helper.opencv_core;
import org.bytedeco.javacpp.opencv_core.CvMemStorage;
import static org.bytedeco.javacpp.opencv_core.IPL_DEPTH_32F;
import static org.bytedeco.javacpp.opencv_core.IPL_DEPTH_8U;
import org.bytedeco.javacpp.opencv_core.IplImage;

import org.bytedeco.javacv.CanvasFrame;
import org.bytedeco.javacv.DC1394FrameGrabber;
import org.bytedeco.javacv.Frame;
import org.bytedeco.javacv.FrameGrabber;
import org.bytedeco.javacv.OpenCVFrameConverter;
import org.bytedeco.javacv.FrameGrabber.Exception;
import org.bytedeco.javacv.FrameRecorder;
import org.bytedeco.javacv.OpenCVFrameGrabber;

public class JavaCvDriverExample {

    public static void main(String[] args) throws Exception, InterruptedException, FrameRecorder.Exception {
       DC1394FrameGrabber grabber = new DC1394FrameGrabber(0);
              
        grabber.start();

        CanvasFrame canvas = new CanvasFrame("Capture Preview", CanvasFrame.getDefaultGamma() / grabber.getGamma());
        Frame capturedFrame = null;
        canvas.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        canvas.setAlwaysOnTop(true);

        while ((capturedFrame = grabber.grab()) != null) {
            if (!canvas.isDisplayable()) {
                grabber.stop();
                System.exit(2);  
            }

            if (canvas.isVisible()) {
                canvas.showImage(capturedFrame);
            }
            Thread.sleep(30);
        }
        canvas.dispose();
        grabber.stop();
    }
}
```

**Comment by saudet** [comment]
Please try to set your camera in a different mode.

**Comment by SilviaDeng** [comment]
Could you kindly tell me how to set my camera in a different mode?

**Comment by saudet** [comment]
I don't know, that depends on your camera. Ask the manufacturer for the tools and SDK.

**Comment by SilviaDeng** [comment]
I reinstall the driver of camera and run the same code.
This time I get the following issue:

run:
Exception in thread "main" org.bytedeco.javacv.FrameGrabber$Exception: dc1394_capture_setup() Error -1: Could not setup camera-
make sure that the video mode and framerate are
supported by your camera.
	at org.bytedeco.javacv.DC1394FrameGrabber.start(DC1394FrameGrabber.java:306)
	at org.bytedeco.javacv.DC1394FrameGrabber.start(DC1394FrameGrabber.java:338)
	at org.bytedeco.javacv.DC1394FrameGrabber.start(DC1394FrameGrabber.java:181)
	at JavaCvDriverExample.main(JavaCvDriverExample.java:39)
libdc1394 error: Buffer validation failed for buffer 0

libdc1394 warning: Warning: Could not free ISO channel
libdc1394 error: Error: Failed to setup DMA capture
libdc1394 error: Buffer validation failed for buffer 0

libdc1394 warning: Warning: Could not free ISO channel
libdc1394 error: Error: Failed to setup DMA capture
H:\Documents and Settings\Administrator\Local Settings\Application Data\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1

Any idea about this issue?

**Comment by saudet** [comment]
Like I said, try to change the settings of your camera.

**Comment by saudet** [comment]
It is also possible to use DC1394FrameGrabber to set the mode. Try to call `setImageMode(ImageMode.COLOR)`, `setImageWidth(640)`, `setImageHeight(480)`, and `setFrameRate(30)` before calling start(). That should work with almost all cameras.
