### ISSUE TITLE
libfreenect2 for windows platform 

### ISSUE THREAD

**Issue by LauraMocanu** [bytedeco/javacv#837]
I tried running mvn with -Djavacpp.platform param. If I use 'linux-x86_64' all works fine, but with 'windows-x86_64' it tries to find library 'libfreenect2:jar:windows-x86_64' which does not exist. I suspect the same would happen for mac, because in the full distribution I only see specific libfreenect2 for linux, and 2 general ones, but which seem not to be taken into account by maven in the case when specific platform is used.

**Comment by saudet** [comment]
That's normal, Windows isn't supported, yet. Though, as usual, contributions are welcome! Thanks for your interest.

**Comment by LauraMocanu** [comment]
Thank you for your answer. I'm a little confused though. The ReadME said one could use windows. And I can see all the other jars do have windows versions.

**Comment by saudet** [comment]
I'm not seeing "Windows" written anywhere:
https://github.com/bytedeco/javacpp-presets/tree/master/libfreenect2

**Comment by LauraMocanu** [comment]
This readme: https://github.com/bytedeco/javacv.
In pom.xml I have
<dependency>
		<groupId>org.bytedeco</groupId>
		<artifactId>javacv-platform</artifactId>
		<version>1.3.2</version>
</dependency>

and I run maven with -Djavacpp.platform=windows-x86_64

**Comment by saudet** [comment]
I still see no mention of libfreenect2 support on Windows... Again, if you wish for more documentation, contributions are welcome! I cannot possibly do everything on my own. Please let me know if you have any questions though, and I will answer.

**Comment by LauraMocanu** [comment]
I will reformulate my question: how can I run -Djavacpp.platform=windows-x86_64 as it sais here
"This downloads binaries for all platforms, but to get binaries for only one platform we can set the javacpp.platform system property (via the -D command line option) to something like android-arm, linux-x86_64, macosx-x86_64, windows-x86_64, etc. "  
and make it work? Because it gives an error and does not download anything.  Thanks again!

**Comment by saudet** [comment]
Ah, yes, it's missing. But we can just exclude it as a dependency.

**Comment by saudet** [comment]
I added support for Mac OS X and Windows in the commit above.

They provide binaries for Windows, so it was easier than I thought!

**Comment by ibraimgm** [comment]
@saudet is this fix released yet? Just tried to download the binaries for windows-x86_64 and I had the same problem related by @LauraMocanu .

Note that using version 1.3 (not 1.3.3 or 1.3.2) works fine.

**Comment by saudet** [comment]
Please try 1.3.4-SNAPSHOT.

**Comment by saudet** [comment]
And now included in newly released version 1.4. Thanks for reporting!
