### ISSUE TITLE
FFmpegFrameFilter does not support lots of filters

### ISSUE THREAD

**Issue by SumitMarwha** [bytedeco/javacv#838]
I want to use eq ffmpeg filter
http://ffmpeg.org/ffmpeg-filters.html#eq
but not able to execute another filters like hue is also not working
http://ffmpeg.org/ffmpeg-filters.html#hue
does anyone knows how to execute it using ffmpegframefilter

**Comment by saudet** [comment]
Duplicate of #717.

BTW, contributions are welcome!

**Comment by saudet** [comment]
FYI, filters like "eq" and "hue" are now fixed with JavaCV 1.4.1. Please see issue #887 for details.
