### ISSUE TITLE
could not find class 'java.awt.image.BufferedImage' Android platform

### ISSUE THREAD

**Issue by bunnyblue** [bytedeco/javacv#84]
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to resolve virtual method 3445: Ljava/awt/image/BufferedImage;.getSampleModel ()Ljava/awt/image/SampleModel;
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to resolve instance field 975
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/image/BufferedImage;)
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/image/BufferedImage;)
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/image/BufferedImage;)
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/image/BufferedImage;)
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/color/ColorSpace;)
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/image/BufferedImage;)
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/image/BufferedImage;)
01-24 20:45:04.440: W/dalvikvm(27821): VFY: unable to find class referenced in signature (Ljava/awt/color/ColorSpace;)
01-24 20:45:04.440: E/dalvikvm(27821): Could not find class 'java.awt.image.BufferedImage', referenced from method org.bytedeco.javacpp.helper.opencv_core$AbstractArray.getBufferedImage

**Comment by saudet** [comment]
Those are only warnings, not errors, you can safely ignore those. BTW, please post any additional comments about there here:
https://github.com/bytedeco/javacpp-presets/issues/12
Thanks!
