### ISSUE TITLE
AMR_WB encoding support in javacv

### ISSUE THREAD

**Issue by canelzio** [bytedeco/javacv#840]
Hi All,
I'm trying to use javacv (1.3.3) with javacpp ffmpeg preset in order to decode/encode AMR audio files, both AMR-NB and AMR-WB formats.
For AMR-NB it works fine, but AMR-WB encoding does not.
I installed opencore-amr-0.1.5 and vo-amrwbenc-0.1.3 libraries and also ffmpeg v3.4 with the following configuration parameters: --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3.

If I try to encode AMR-WB files from commandline it works fine:
ffmpeg -i test.wav -c libvo_amrwbenc -f amr -ar 16000 test.amrwb

But if I try to do that using javacv, I got the following exception message: avcodec_find_encoder() error: Audio codec not found.
at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:580)

Also libvo-amrenc does not seem to appear in the list of encoders returned by av_codec_next(codec).

Could you please help me solving this issue?

Thank you.
Regards.

**Comment by saudet** [comment]
Please try with with JavaCV 1.3.4-SNAPSHOT and FFmpeg 3.4.

**Comment by canelzio** [comment]
I'm using maven in my project, but I'm not able to find/download JavaCV 1.3.4-SNAPSHOT.
Should I point to a different repository?

**Comment by saudet** [comment]
Yes, the SNAPSHOT repository: http://bytedeco.org/builds/

**Comment by canelzio** [comment]
Thanks Samuel for indication. Now I'm able to use JavaCV 1.3.4-SNAPSHOT. Unfortunately it behaves just like the 1.3.3: it seems to ignore the vo-amrwbenc encoder.

Just a note for 1.3.4-SNAPSHOT: in order to make my project works I had to remove few dependencies from ffmpeg-platform-3.4-1.3.4-SNAPSHOT.pom, since they were related to unavailable platforms in the snapshot repository (i.e. macosx).

**Comment by saudet** [comment]
I see, we would need to add the vo-amrwbenc codec. It's not built with it at the moment. We just need to add it to the cppbuild.sh file alongside opencore-amr:
https://github.com/bytedeco/javacpp-presets/blob/master/ffmpeg/cppbuild.sh
Contributions are welcome, so feel free to give it a try and let me know if you encounter any issues! I'll be able to help. Thanks!

**Comment by canelzio** [comment]
Hi Samuel,

I’m trying to build javacpp preset for ffmpeg, but I’m getting this error message:

 

--------

patching file configure

ERROR: libxcb requested but not found

--------

 

Package libxcb seems to be properly installed.

Could you please help me?

**Comment by saudet** [comment]
You'll need to install the development files for libxcb on Linux, yes. You shouldn't have any problems if you follow the instructions here though:
https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments#linux-x86-and-x86_64

You can also disable libxcb for your build, if you want, by removing the flag from cppbuild.sh.

**Comment by canelzio** [comment]
I was finally able to build ffmpeg .so libs, then I included them in the ffmpeg-3.4-1.3.4-SNAPSHOT-linux-x86_64.jar (keeping libjni*.so libs in their original version).
Then I used this new ffmpeg-3.4-1.3.4-SNAPSHOT-linux-x86_64.jar in my project and it worked: now both AMR-NB and AMR-WB encoders work as expected!

Here is the cppbuild.sh file I used:

[ffmpeg-cppbuild.zip](https://github.com/bytedeco/javacv/files/1513574/ffmpeg-cppbuild.zip)

Please consider the following:
- I added download, untar and installation commands for vo-amrwbenc
- Added --enable-libvo-amrwbenc in the ENABLED list
- I only built for linux-x86_64 platform
- I deleted these 2 options --enable-libxcb and --enable-w32threads
- Changed a couple of ftp sites (not working on my network) in http/https

Thank you very much for support!

**Comment by saudet** [comment]
Great! Could you send a pull request with only the changes related to vo-amrwbenc? Also could you try to add the build commands for the other platforms too? Don't worry if you don't get it right. The idea is to let the CI server do the builds for us, and we can check the errors and fix things that way. Thanks!

**Comment by canelzio** [comment]
I sent a pull request on javacpp-presets project.

**Comment by saudet** [comment]
Included in the newly released version 1.4. Thanks again for the contribution!
