### ISSUE TITLE
Please fix README.md to avoid java.lang.UnsatisfiedLinkError: no jniopencv_core

### ISSUE THREAD

**Issue by mixaal** [bytedeco/javacv#843]
Please include the following dependencies as an example in the:

https://github.com/bytedeco/javacv/blob/master/README.md

file. The one depicted on the page above leads the "famous" error: {{java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path}} as already described in the following issues:

https://github.com/bytedeco/javacv/issues/422
https://github.com/bytedeco/javacv/issues/49

If you include the following pom.xml, I assume most people won't be filing this issue anymore since the example provided on the page above starts to work "out-of-the box".

    

<dependencies>

    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacv</artifactId>
      <version>1.3.3</version>
    </dependency>

    
    <dependency>
      <groupId>org.bytedeco</groupId>
      <artifactId>javacpp</artifactId>
      <version>1.3.3</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>opencv</artifactId>
      <version>3.2.0-1.3</version>
    </dependency>
    <dependency>
      <groupId>org.bytedeco.javacpp-presets</groupId>
      <artifactId>opencv-platform</artifactId>
      <version>3.2.0-1.3</version>
    </dependency>
    
  </dependencies>

You can always say this is an example only, however it helps people to start off with javacv.

Thanks.

uname -a
Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
java -version
java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

**Comment by saudet** [comment]
Thanks, but the pom.xml file example provided in the README.md file already
works "out of the box".

**Comment by saudet** [comment]
FYI, you should be using "javacv-platform", not "javacv".

**Comment by mixaal** [comment]
Thanks for quick reaction. I didn't spot the difference. The way I got to wrong dep was I searched for the latest javacv in maven repo and once found I copy pasted the maven artifact. However I searched for javacv not for javacv-platform. Maybe putting a note before/inside the pom.xml snippet : "Make sure you are using javacv-platform" might help.

Thanks

**Comment by saudet** [comment]
Sounds good. Could you send a pull request? :)

**Comment by mixaal** [comment]
I just opened the request:
https://github.com/bytedeco/javacv/pull/844

Thanks :)
