### ISSUE TITLE
opencv_core.Mat - get pixels (integer array) with length width*height

### ISSUE THREAD

**Issue by anonym24** [bytedeco/javacv#849]
I need to get int array data (`int[]`) from `Mat`, length of such array should be == **(width * height)**

Using default image classes I can get such data using next methods

Java (win/ubuntu)
```
bufferedImage = ImageIO.read(new File(imageFile));

BufferedImage convertedImg = new BufferedImage(bufferedImage.getWidth(), bufferedImage.getHeight(), BufferedImage.TYPE_INT_RGB);
convertedImg.getGraphics().drawImage(bufferedImage, 0, 0, null);

 int[] ints = ((DataBufferInt) convertedImg.getRaster().getDataBuffer()).getData();
```
Java (android) 

```
int[] intValues = new int[width * height];
bitmap.getPixels(intValues, 0, bitmap.getWidth(), 0, 0, bitmap.getWidth(), bitmap.getHeight());
```

How can I get the same data from `Mat` ? (not BufferedImage or Bitmap, but Mat)

I have rgb Mat `opencv_imgproc.cvtColor(mat, mat, opencv_imgproc.COLOR_BGR2RGB);`

I found this https://stackoverflow.com/a/35857186
but it returns array of x3 bigger size - `mat.total * mat.channels` 

p.s. I need it because I want to use mat and such array for Tensorflow, it needs integer array with length equal _width * height_ (not _width * height * channels_) -
 https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java#L143

**Comment by saudet** [comment]
If you convert your image to RGBA, BGRA, or something like that, you'll get
what you need.

**Comment by anonym24** [comment]
but BufferdImage and Bitmap are RGB color type, so I thought Mat also should be this type (that's why I converted frames from camera to RGB from BGR)

anyway I tried converted it to many colors (to RGBA, BGRA and others):

```
            opencv_imgproc.cvtColor(mat, mat, opencv_imgproc.COLOR_RGB2BGRA); // or COLOR_RGB2RGBA and others
            mat.convertTo(mat, opencv_core.CV_32S);
            IntBuffer intBuffer = mat.createBuffer();
            int[] intArray = new int[intBuffer.capacity()];
            intBuffer.get(intArray);
            System.out.println("intArray length " + intArray.length);
```

and so on...

but still all of them have bigger size

only BGR2GRAY gave me the same length, but values in the array are not the same

**Comment by saudet** [comment]
An `int` is 4 bytes...

**Comment by anonym24** [comment]
still didn't solve it

in pure OpenCV it can be done this way:

```
static int[] matToIntArray(Mat mRgba) {
        MatOfInt rgb = new MatOfInt(CvType.CV_32S);
        mRgba.convertTo(rgb, CvType.CV_32S);
        int[] rgba = new int[(int)(rgb.total()*rgb.channels())];
        rgb.get(0,0,rgba);
        return rgba;
    }
```

but `MatOfInt` not available in `JavaCV` and it only can get byte[] array with  `mat.data().get(byte[] dstArray);`

**Comment by saudet** [comment]
Sure, if you want a Mat with type CV_32S, `new Mat(rows, cols, CV_32S)` is *exactly* the same thing in C++ and with JavaCPP.
