### ISSUE TITLE
Template Matching with transparent PNG

### ISSUE THREAD

**Issue by arianaa30** [bytedeco/javacv#856]
I was doing some tests with template matching example (`TemplateMatching.java`). In my tests, I crop a part of the source image as the template. If I make the template a transparent PNG, it doesn't detect the template (compare the two files below).

Is there any settings for that? Probably it fills the empty parts with white color, hence the error?!

![bouncelogo](https://user-images.githubusercontent.com/5509837/33739178-bc8f4278-db61-11e7-9b8d-ade406dccde7.png)
![bouncelogo3](https://user-images.githubusercontent.com/5509837/33739179-bcb71bcc-db61-11e7-8b7b-fbcf441d693f.png)

**Comment by saudet** [comment]
Not directly, but that's what a mask argument is for:
https://docs.opencv.org/3.2.0/de/da9/tutorial_template_matching.html
