### ISSUE TITLE
How to Crop a Video? (Question)

### ISSUE THREAD

**Issue by guikeller** [bytedeco/javacv#858]
Hi there,

I have a video (sample.mov) that contains 30secs of audio + video.
Now, imagine that the 5secs in the beginning and end of the video is just noise.

How can I crop the video starting at 5secs and ending on 25secs?
Generating then a new video file with only 20secs.

Should I use "FFmpegFrameGrabber" to grab the frames and send to a "FFmpegFrameRecorder"?
Is this the right approach? Any code samples would be greatly appreciated, thanks!

Also, thanks for the project. 👍

**Comment by saudet** [comment]
Yes, that sounds like the right approach. Depending on the original video, you might not need to reencode the frames: https://github.com/bytedeco/javacv/issues/818#issuecomment-349094435

**Comment by saudet** [comment]
And sample code is available here:
https://github.com/bytedeco/javacv/blob/master/samples/PacketRecorderTest.java

**Comment by guikeller** [comment]
Thank you very much for your help! 🌟

**Comment by guikeller** [comment]
Solution below - pretty straightforward:

```

            long fiveSecs = 5000000;
            long twentyFiveSecs = fiveSecs*5;
            String originalVideo = "/tmp/VIDEO.MOV";
            String outputVideo = "/tmp/CROPPED_VIDEO.MOV";

            FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber(originalVideo);
            frameGrabber.start();

            int width = frameGrabber.getImageWidth();
            int height = frameGrabber.getImageHeight();
            int channels = frameGrabber.getAudioChannels();

            FFmpegFrameRecorder frameRecorder = new FFmpegFrameRecorder(outputVideo, width, height, channels);
            frameRecorder.start();

            Frame frame;
            while ((frame = frameGrabber.grab()) != null) {
                Long timestamp = frameGrabber.getTimestamp();
                if (timestamp < fiveSecs) {
                    continue;
                }
                frameRecorder.record(frame);
                if (timestamp > twentyFiveSecs) {
                    break;
                }
            }

            frameRecorder.stop();
            frameGrabber.stop();
```

**Comment by guikeller** [comment]
Hey @saudet 

Quick question, how do I copy all metadata from "originalVideo" onto "outputVideo" ?
Thank you very much for your help so far!

Cheers

**Comment by saudet** [comment]
Great! As for the metadata, I guess we would have to enhance FFmpegFrameGrabber and FFmpegFrameRecorder a bit for this. Could you send a pull request? :)

**Comment by guikeller** [comment]
Thanks for the quick answer; as soon as I get some things out of the way I will try to contribute with a PR and adding this feature; cheers!

**Comment by saudet** [comment]
I've given access to the `Map` fields in the commit above. We can now do something like `recorder.setMetadata(grabber.getMetadata())` and it should work!

**Comment by guikeller** [comment]
That's great news! 

Thanks for doing that, looking forward to the next release! 👍

**Comment by saudet** [comment]
Please try the SNAPSHOT artifacts!

**Comment by guikeller** [comment]
Will do! If you don't hear back from me anymore is because all is going well.. 😆
