### ISSUE TITLE
FFmpegFrameFilter reduse the input video width and height

### ISSUE THREAD

**Issue by KishanThakar** [bytedeco/javacv#859]
I add FFmpeg for video recording, But my output video width and height is different than input video.After Video recording video display like a shrink video. My code is like this

          int degree = getRotationDegree();
            Camera.CameraInfo info = new Camera.CameraInfo();
            Camera.getCameraInfo(mCameraId, info);
            boolean isFrontFaceCamera = info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT;
            Log.i(LOG_TAG, "init filter with width = " + width + " and height = " + height + " and degree = "
                    + degree + " and isFrontFaceCamera = " + isFrontFaceCamera);
            String transposeCode;
            String formatCode = "format=pix_fmts=rgba";
        /*
         0 = 90CounterCLockwise and Vertical Flip (default)
         1 = 90Clockwise
         2 = 90CounterClockwise
         3 = 90Clockwise and Vertical Flip
         */
            switch (degree) {
                case 0:
                    transposeCode = isFrontFaceCamera ? "transpose=3,transpose=2" : "transpose=1,transpose=2";
                    break;
                case 90:
                    transposeCode = isFrontFaceCamera ? "transpose=3" : "transpose=1";
                    break;
                case 180:
                    transposeCode = isFrontFaceCamera ? "transpose=0,transpose=2" : "transpose=2,transpose=2";
                    break;
                case 270:
                    transposeCode = isFrontFaceCamera ? "transpose=0" : "transpose=2";
                    break;
                default:
                    transposeCode = isFrontFaceCamera ? "transpose=3,transpose=2" : "transpose=1,transpose=2";
            }

            FFmpegFrameFilter frameFilter = new FFmpegFrameFilter(transposeCode + "," + formatCode,
                    previewWidth, previewHeight);

            frameFilter.setPixelFormat(avutil.AV_PIX_FMT_NV21);

**Comment by saudet** [comment]
Make sure previewWidth and previewHeight make sense...

**Comment by KishanThakar** [comment]
yes its width = 640 and height = 480. Its based on input width and height.

**Comment by saudet** [comment]
Could also post what FFmpeg outputs to the log when you run this?

**Comment by saudet** [comment]
Do you have the same issue with this example activity?
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by saudet** [comment]
I've just released JavaCV 1.4.1, which uses FFmpeg 3.4.2. Maybe this is a bug that has been fixed upstream, so please try again with this new release!

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming this has been fixed, but please let me know if this isn't the case.
