### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by ayadiWael** [bytedeco/javacv#86]
Veuillez m'expliquer la différence entre JavaCV et OpenCV. Je suis en train de réaliser un projet sur le traitement de vidéos et je dois effectuer des modifications sur chaque frame de la vidéo. Est-ce que ça sera utile d'utiliser JavaCV.
Merci d'avance

**Comment by saudet** [comment]
Je crois que vous trouverez une réponse sur cette page : http://bytedeco.org/faq/

**Comment by ayadiWael** [comment]
merci beaucoup
