### ISSUE TITLE
minMaxLoc warning on MacOsX (program won't continue)

### ISSUE THREAD

**Issue by zero334** [bytedeco/javacv#863]
When calling minMaxLoc I get this warning:
"**WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.**"

The program won't continue after this warning. I am calling minMaxLoc like this:

    final Point minLoc = new Point();
    final Point maxLoc = new Point();
    minMaxLoc(result, new DoublePointer(), new DoublePointer(), minLoc, maxLoc, new Mat());
    // result is a Mat containing the result from a matchTemplate() call.

Of cause I am calling minMaxLoc from the main thread in my program.
With Windows 10, the same code it is working fine, I get no warnings.

My system:
MacOs: 10.13.2 (17C88)
Java version: 9.0.1

**Comment by saudet** [comment]
Does it do the same thing with Java 8?

**Comment by zero334** [comment]
Yes, same problem with Java 8 (1.8.0_121).

**Comment by saudet** [comment]
Sounds like a problem with OpenCV though. Do you get the same thing outside of Java in C++ only?

**Comment by zero334** [comment]
Honestly, I have never tried OpenCV in C++. Only using it with javacv.

**Comment by saudet** [comment]
Does it happen with version 3.3.1-1.3.4-SNAPSHOT of the opencv-platform artifact?

**Comment by zero334** [comment]
Sorry for the delay, was testing.
Yes, it still happens with version 3.3.1-1.3.4-SNAPSHOT of the opencv-platform artifact.

**Comment by saudet** [comment]
Ok, could you provide a code snippet to reproduce this?

**Comment by zero334** [comment]
Sure, I will provide you the whole code, I guess it is better to see then..

    package javaCv;

    import org.bytedeco.javacpp.DoublePointer;
    import org.bytedeco.javacpp.opencv_core.Point;
    import org.bytedeco.javacpp.indexer.FloatIndexer;

    import static org.bytedeco.javacpp.opencv_core.*;
    import static org.bytedeco.javacpp.opencv_imgproc.*;
    import static org.bytedeco.javacpp.opencv_highgui.*;

    import java.awt.Graphics2D;
    import java.awt.image.BufferedImage;
    import java.util.TreeMap;
    import java.util.concurrent.ThreadLocalRandom;

    public class JavaCvTest {

	public static java.awt.Point exec(final BufferedImage scene, final BufferedImage template) {

		// Input scene
		final Mat sourceColor = Java2DFrameUtils.toMat(convertIntRGBTo3ByteBGR(scene));
		final Mat sourceGrey = new Mat(sourceColor.size(), CV_8UC1);
		cvtColor(sourceColor, sourceGrey, COLOR_BGR2GRAY);

		// Input template
		final Mat templateColor = Java2DFrameUtils.toMat(convertIntRGBTo3ByteBGR(template));
		final Mat templateGrey = new Mat(templateColor.rows(), templateColor.cols(), templateColor.type());
		cvtColor(templateColor, templateGrey, COLOR_BGR2GRAY);

		// Result buffer
		final Size size = new Size(sourceGrey.cols() - templateGrey.cols() + 1, sourceGrey.rows() - templateGrey.rows() + 1);
		final Mat result = new Mat(size, CV_32FC1);

		// Template matching
		matchTemplate(sourceGrey, templateGrey, result, CV_TM_CCOEFF_NORMED);

		// Calculate all points over the threshold.
		final TreeMap<Float, java.awt.Point> detectedPoints = getProbabilityWithPointsFromMatAboveThreshold(result, .7f);

		if (detectedPoints.isEmpty()) {
			System.out.println("No elements found!");
		} else {
			System.out.println("Found!");
			System.out.println("Amount of matches: " + detectedPoints.size());

			final float highesMatch = detectedPoints.lastKey();
			System.out.println("Highest Match:" + highesMatch);
			System.out.println(detectedPoints.get(highesMatch));


			/* From here on debug */
			final Point minLoc = new Point();
			final Point maxLoc = new Point();

			minMaxLoc(result, new DoublePointer(), new DoublePointer(), minLoc, maxLoc, new Mat());

			final org.bytedeco.javacpp.opencv_core.Point matchLoc = maxLoc;
			rectangle(sourceColor, matchLoc, new Point(matchLoc.x() + templateGrey.cols() , matchLoc.y() + templateGrey.rows() ), randColor(), 2, 8, 0);

			final org.bytedeco.javacpp.opencv_core.Point ppPoint = new Point(matchLoc.x() + templateGrey.cols() , matchLoc.y() + templateGrey.rows());
			rectangle(sourceGrey, matchLoc, ppPoint, randColor(), 2, 0, 0);

			imshow("Original marked", sourceColor);
			// imshow("Ttemplate", templateGrey);
			// imshow("Results matrix", result);
			waitKey(0);
			destroyAllWindows();

			return detectedPoints.get(highesMatch);
		}
		return null;
	}

	public static Scalar randColor() {
		final int b = ThreadLocalRandom.current().nextInt(0, 255 + 1);
		final int g = ThreadLocalRandom.current().nextInt(0, 255 + 1);
		final int r = ThreadLocalRandom.current().nextInt(0, 255 + 1);
		return new Scalar(b, g, r, 0);
	}

	private static BufferedImage convertIntRGBTo3ByteBGR(final BufferedImage img) {
		final BufferedImage convertedImage = new BufferedImage(img.getWidth(), img.getHeight(), BufferedImage.TYPE_3BYTE_BGR);
		final Graphics2D graphics = convertedImage.createGraphics();
		graphics.drawImage(img, 0, 0, null);
		graphics.dispose();
		return convertedImage;
	}

	public static TreeMap<Float, java.awt.Point> getProbabilityWithPointsFromMatAboveThreshold(final Mat m, final float threshold) {
		final TreeMap<Float, java.awt.Point> matches = new TreeMap<Float, java.awt.Point>();
		final FloatIndexer indexer = m.createIndexer();
		for (int y = 0; y < m.rows(); y++) {
			for (int x = 0; x < m.cols(); x++) {
				if (indexer.get(y, x) > threshold) {
					matches.put(indexer.get(y, x), new java.awt.Point(x, y));
				}
			}
		}
		return matches;
	}
    }

**Comment by saudet** [comment]
opencv_highgui is known to cause these kinds of issues, you shouldn't be using it.
