### ISSUE TITLE
UnsatisfiedLinkError Can not find jnivideoInputLib.dll

### ISSUE THREAD

**Issue by zchacker** [bytedeco/javacv#864]
Hello, i have use FFmpeg in java to capture webcam and preview it, i use Dshow format.
when try to get webcams in FFmpeg, i did not find way to do that, but i use VideoInput library to get webcams name to pass it in this method.

```
int webcams = videoInput.listDevices();
String webcam_name[] =  new String[webcams];

int max = 0;	        
for (int i = 0; i < webcams ; i++) {
    	webcam_name[i] = videoInput.getDeviceName(i).getString();	        	
}
FFmpegFrameGrabber.createDefault("video="+webcam_name[0]);
```
the above code work very well in windows 8, but when i run it in windows 7 it show the he can not load "jnivideoInputLib.dll" file in this path 

C:\Users\Compunet\.javacpp\cache\room5.jar\org\bytedeco\javacpp\windows-x86_64\jnivideoInputLib.dll

and when i go the path i find the jnivideoInputLib.dll file
what is the problem and why javacv put dll files in this path instead of same jar resources 

thanks

**Comment by saudet** [comment]
Could you please tell me what Dependency Walker says?
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows

**Comment by zchacker** [comment]
it says the msvcp120.dll missing, and solve it, but is there a way to load webcams names using FFmpeg in javacv ?

**Comment by saudet** [comment]
Ah, yes, sorry about that. Fixed in the commit above.

It is possible to list devices with FFmpeg, yes, see issue https://github.com/bytedeco/javacv/issues/664#issuecomment-292134732, but we still need someone to integrate that functionality fo FFmpegFrameGrabber. If you would be interested in making a contribution, please let me know if you encounter any issues I can help with. Thank you for your interest!

**Comment by saudet** [comment]
Fix included in newly released version 1.4. Thanks for reporting!

**Comment by zchacker** [comment]
you are welcome , is there a new build ?

**Comment by saudet** [comment]
Yes, it's all here: http://bytedeco.org/download/
