### ISSUE TITLE
Why is there no a method allow us to customize the frame rate in class FFmpegFrameGrabber

### ISSUE THREAD

**Issue by Felix199404** [bytedeco/javacv#869]
I display a avi video by use FFmpegFrameGrabber to grabe Frame  and show on the canvas.  
and it  do the great job .
but now My customer want to speed the  video . so i have to speed up the frame rate .

**Comment by saudet** [comment]
It's not a video player, we can display the images at any rate we want.

**Comment by Felix199404** [comment]
i know that .  i just use FFmpegFrameGrabber to grab a frame and  to show on my video player which coded by swing Canvas . and how can i to speed the frame rate .

**Comment by Felix199404** [comment]
`ffmpegFrameGrabber = FFmpegFrameGrabber.createDefault(filePath);
	    		ffmpegFrameGrabber.start();
	    		fflength = ffmpegFrameGrabber.getLengthInFrames();
	    		maxStamp = (int) (ffmpegFrameGrabber.getLengthInTime()/1000000);
				int count = 0;
				while (count < fflength) {
					try {
						if (!videoIsPlaying) {
							semaphore.acquire();
						}
						if (videoIsPlaying) {
							nowFrame = ffmpegFrameGrabber.grabImage();
							if (nowFrame == null) {
								System.out.println("!!! Failed cvQueryFrame");
								break;
							}
							desktopPlayer.showImage(nowFrame);
							Thread.sleep(INTERVAL);
							count ++;
						} else {

						}
					} catch (InterruptedException e) {

					}
				}`

**Comment by Felix199404** [comment]
`
ffmpegFrameGrabber = FFmpegFrameGrabber.createDefault(filePath);
	    		ffmpegFrameGrabber.start();
	    		fflength = ffmpegFrameGrabber.getLengthInFrames();
	    		maxStamp = (int) (ffmpegFrameGrabber.getLengthInTime()/1000000);
				int count = 0;
				while (count < fflength) {
					try {
						if (!videoIsPlaying) {
							semaphore.acquire();
						}
						if (videoIsPlaying) {
							nowFrame = ffmpegFrameGrabber.grabImage();
							if (nowFrame == null) {
								System.out.println("!!! Failed cvQueryFrame");
								break;
							}
							desktopPlayer.showImage(nowFrame);
							Thread.sleep(INTERVAL);
							count ++;
						} else {

						}
					} catch (InterruptedException e) {

					}
				}
`

**Comment by saudet** [comment]
Just remove the call to `Thread.sleep()` and it will go faster.

**Comment by Felix199404** [comment]
the value of INTERVAL  is only 40 .a very small number .if  i want to speed up the frame rate more than 64 times . how could i do ? sorry . My English is not so good. and i very appricated for your patience

**Comment by saudet** [comment]
Something like this:
```java
long start = System.nanoTime();
// ...
while (System.nanoTime() - start < 40 * 1000 * 1000 / 64);
```
