### ISSUE TITLE
XOR ??

### ISSUE THREAD

**Issue by ayadiWael** [bytedeco/javacv#87]
Bjr,
je veux effectuer un Xor entre une image et les frames d'une vidéo 
j'ai utilisé img = grabber.grab(); pour extraire les frames 
j'ai pas compris comment effectuer l'xor

**Comment by saudet** [comment]
Il y a une fonction pour ça ici:
[public static void cvXor(CvArr src1, CvArr src2, CvArr dst)](
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.html#cvXor-org.bytedeco.javacpp.helper.opencv_core.CvArr-org.bytedeco.javacpp.helper.opencv_core.CvArr-org.bytedeco.javacpp.helper.opencv_core.CvArr-)
[public static void bitwise_xor(Mat src1, Mat src2, Mat dst, Mat mask)](
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.html#bitwise_xor-org.bytedeco.javacpp.opencv_core.Mat-org.bytedeco.javacpp.opencv_core.Mat-org.bytedeco.javacpp.opencv_core.Mat-org.bytedeco.javacpp.opencv_core.Mat-)

**Comment by ayadiWael** [comment]
merci bcp

**Comment by ayadiWael** [comment]
J'ai utilisé le code suivant et c pas marché (erreur d'exécution). Veuillez m'aider ??

IplImage im=cvLoadImage("C:\\Users\\Public\\Pictures\\Sample Pictures\\test2.jpg");
CvCapture capture=cvCreateFileCapture("C:\\Users\\Public\\Videos\\Sample Videos\\Wildlife.wmv");
Mat im1 = new Mat(im,true);

IplImage frame;
cvNamedWindow("Video",CV_WINDOW_AUTOSIZE);

for(;;)
{  frame=cvQueryFrame(capture);
    Mat im2 = new Mat(frame,true); 
Mat im3=new Mat();
bitwise_xor(im1,im2,im3);
IplImage  xorFrame=new IplImage(im3);
if (xorFrame==null)break;
cvShowImage("video", xorFrame);
    char c=(char)cvWaitKey(30); 
       System.out.println(c);
       if(c==97)break;
}

**Comment by saudet** [comment]
`new IplImage(im3)` n'est pas correct. Il faut au lieu appeler `im3.asIplImage()`.

**Comment by ayadiWael** [comment]
merci bcp
