### ISSUE TITLE
Is it possible to play videos backwards

### ISSUE THREAD

**Issue by erkan22789** [bytedeco/javacv#872]
Hi,

I need to playback forward and backward direction with speed like this.
[-10x][-8x][-4x][-2x][1/8x][1/4x][1/2x][1x][2x][4x][6x][8x][10x]

Does anyone know how to do this with javacv?

**Comment by saudet** [comment]
Most video formats were not designed for that, and I don't believe FFmpeg was either. IMO, the safest thing to do is just to reencode your video backwards, and then use that one when playing back in reverse.

**Comment by erkan22789** [comment]
I was doing this with setTime function in libvlc. Is there any function like this set time or set frame? If I get video duration or frame count, I can show frames at specified time.

**Comment by saudet** [comment]
setTimestamp() isn't working properly?

**Comment by erkan22789** [comment]
I tried but it is not working.
Here is my sample code:

File file = new File("C:\\Users\\Erkan\\Desktop\\kayıtDosya\\1514221572772_00000001.ts");
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(file);
        try {
            grabber.setImageHeight(480);
            grabber.setImageWidth(860);

            grabber.setTimestamp(new Long("2000000"));


            grabber.start();

            opencv_core.IplImage img;
            String filters = "fps=fps=10";
            FFmpegFrameFilter filter = new FFmpegFrameFilter(filters, grabber.getImageWidth(), grabber.getImageHeight());

            filter.start();
            //int count = 1;
            while (isPlaying) {
                Thread.sleep(getSleepTime());

                OpenCVFrameConverter.ToIplImage converter = new OpenCVFrameConverter.ToIplImage();
                Frame frame = grabber.grab();
                if (frame != null) {
                    filter.push(frame);
                    img = converter.convert(frame);

                    if (img != null) {
                        canvas.displayImage(IplImageToBufferedImage(img));
                    }
                    filter.restart();
                }
            }
            filter.stop();
            filter.release();
            grabber.stop();
            grabber.release();
            canvas.clear();
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by erkan22789** [comment]
I have a video file (1514221572772_00000001.ts).  It is playing properly with FFmpegFrameGrabber but i want it to play backward direction. I will set decreasing time in loop. If i get frames at specified time, i can show frames respectively. I think it will look like, the video will be played backward direction. Shortly, i want to get frame at specified time. I did it with libvlc but i do not know how can i do with javacv.

**Comment by saudet** [comment]
Like I said, what do you expect setTimestamp() to do?

**Comment by erkan22789** [comment]
When I use setTimestamp, the video starts playing at specified time isn't it?

**Comment by saudet** [comment]
Yes, so what is the issue?

**Comment by erkan22789** [comment]
I do not know how to use it or it is not working? Can you please help me?

**Comment by saudet** [comment]
Well, `grabber.setTimestamp(2000000)` will jump to 2 seconds after the start.

**Comment by erkan22789** [comment]
I have to use grabber.setTimestamp(2000000) after I work grabber.start(). It is working. Thank you.

**Comment by saudet** [comment]
Ah, I see, this would be the kind of thing that we should add to the API documentation, even though I think the usage is pretty clear from these two examples:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java

**Comment by saudet** [comment]
I'm assuming this is no longer an issue, but please let me know if this is not the case. Thanks!
