### ISSUE TITLE
java.lang.UnsatisfiedLinkError when using CMake in Android Studio

### ISSUE THREAD

**Issue by chxchen** [bytedeco/javacv#877]
I'm not good at English,sorry!
My project should use serial_port,so,I add "serial_port.so" by CMake,before this,the JavaCv works fine. But after using CMake, the JavaCv happens to crash:"java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil ".

I have read this link `https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-(a-real-experience)` ,but don`t know how to use ReLink in my project,after reading.
I think that my config of CMake just for serial_port is the cause of this issue,but this is my first time using CMake.
Any advice to a first-time-using-CMake newbie?
Or any advice to use Relink?
my project uses javaCV by :
 " compile group: 'org.bytedeco', name: 'javacv', version: '1.3.1'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv-platform', version: '3.1.0-1.3'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg-platform', version: '3.2.1-1.3'
"
What so should i write in "
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_core");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_core");
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_imgcodecs");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_imgcodecs");
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_imgproc");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_imgproc");
"?

**Comment by saudet** [comment]
You probably just forgot to do this:
> Also just make a plain copy of `armeabi` to `armeabi-v7a`.

https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by chxchen** [comment]
i will try this,but why does this problem  happen after adding CMake ?

**Comment by chxchen** [comment]
@saudet Hello! I’m sorry that In my case how to do with Relink,and  what 'jar' shoud I put in libs folder,
I guess 
'ffmpeg.jar',‘ffmpeg-android-arm.jar’,'ffmpeg-platform.jar','javacv.jar','javacv-platform.jar','opencv.jar','opencv-android-arm.jar' needed.
And where are the '*.so' files? Relink code is the same as example,it is enough?

**Comment by saudet** [comment]
They are in ffmpeg-android-arm.jar and opencv-android-arm.jar.

If you follow all the workarounds in https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29 it should work on all devices, yes.

**Comment by chxchen** [comment]
@saudet 
Ok,I copy "*.os" in ffmpeg-android-arm.jar to “jniLibs” folder ,It works fine again!
And after that,I try to remove Relink,it still works fine.Maybe I just make a mistake in "library version" problem.I will review this,after the project finished!
Thanks to you very much!!
