### ISSUE TITLE
javacv/javafx mat/image

### ISSUE THREAD

**Issue by har-y** [bytedeco/javacv#878]
hi, I have question about javacv.
I made the user interface in which I use imageview to display the camera image
and my question is ... is there anything I can convert Mat to Image? I thought about it to convert Mat -> IplImage / BufferedImage -> Image, but nowhere can I find a solution under javacv-platform-1.3.3.
in opencv 3.3 I saw something like that, but not here. could anyone help me?
I found something similar in JavaFxPlayVideoAndAudio.java, but unfortunately it has outgrown me

**Comment by saudet** [comment]
Sure, there's an example of that in this example:
https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java

**Comment by saudet** [comment]
What do you mean, JavaFxPlayVideoAndAudio doesn't work? What is issue?

**Comment by har-y** [comment]
so far I am looking for a solution..

> SEVERE: null
> java.nio.BufferUnderflowException
> 	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:628)
> 	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:261)
> 	at org.bytedeco.javacv.Java2DFrameConverter.flipCopyWithGamma(Java2DFrameConverter.java:177)
> 	at org.bytedeco.javacv.Java2DFrameConverter.copy(Java2DFrameConverter.java:474)
> 	at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:675)
> 	at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:588)
> 	at org.bytedeco.javacv.Java2DFrameConverter.getBufferedImage(Java2DFrameConverter.java:585)
> 	at org.bytedeco.javacv.Java2DFrameConverter.convert(Java2DFrameConverter.java:67)
> 	at facerecognizer.main.FaceConvert.lambda$frameToImage$1(FaceConvert.java:33)
> 	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by saudet** [comment]
Would you have a code snippet to reproduce that?
