### ISSUE TITLE
Precision and different sizes in template matching

### ISSUE THREAD

**Issue by waldemarnt** [bytedeco/javacv#88]
Hello guys, this is some doubts...
Have a way to get the presicion in template matching?
And another doubt , is about the different of sizes in a template matching, i have the image, inside the template but this one have a different size, in the most times does not match
I think that's is most a open cv doubts..
Tnx guys

**Comment by saudet** [comment]
By precision, if you mean how to get the score or something, that is usually returned by the template matching function.

As for the size of the template, some matching algorithms can support that, others don't. It depends on which one you use.

If you need to know more, you're going to have to ask clearer questions and provide more details! Thanks

**Comment by waldemarnt** [comment]
Sorry saudet, i guess you dont understand my douts, i needed know the best way to , but i know do it.
The first i use a point maxLoc and the second doubt i use CV_TM_CCORR.

Tnx

**Comment by saudet** [comment]
Which method gives better results depends on your images, so try them all, and pick the one that works best with your data.
