### ISSUE TITLE
More than one file was found with OS independent path 'org/bytedeco/javacpp/windows-x86_64/api-ms-win-crt-locale-l1-1-0.dll'

### ISSUE THREAD

**Issue by llakcs** [bytedeco/javacv#880]
And there's a new problem.
Javacv seems to be in conflict with OPENCV
i don't know how to fix?

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

More than one file was found with OS independent path 'org/bytedeco/javacpp/windows-x86_64/api-ms-win-crt-locale-l1-1-0.dll'
dependencies
compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.4'
compile group: 'org.bytedeco', name: 'javacpp', version: '1.4'
implementation project(':openCVLibrary340')

**Comment by saudet** [comment]
Just exclude the artifacts for Windows, you don't need them on Android.

**Comment by llakcs** [comment]
like this? 

compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.4'{
        exclude group:'org.bytedeco.javacpp.windows-x86_64'
    }
give me packageName

**Comment by saudet** [comment]
Yes, although it's probably easier to include only what you need like this:
https://github.com/bytedeco/sample-projects/blob/master/javacv-android-recognize/app/build.gradle#L46
