### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by llakcs** [bytedeco/javacv#881]
like this?   Can u give me the right package name? I'm a novice

 compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.4'
    compile group: 'org.bytedeco', name: 'javacpp', version: '1.4'{
       **wrong package name**
        exclude group:'org.bytedeco.javacpp.windows_x86_64'
    }

**Comment by llakcs** [comment]
please help me!

**Comment by saudet** [comment]
Why not start from a sample project then? https://github.com/bytedeco/sample-projects

**Comment by llakcs** [comment]
thank u very much!
