### ISSUE TITLE
How to take out the values inside the FaceRecognizer

### ISSUE THREAD

**Issue by llakcs** [bytedeco/javacv#883]
sample:

 opencv_core.MatVector photos = new opencv_core.MatVector(files.length);
        opencv_core.Mat labels = new opencv_core.Mat(files.length, 1, CV_32SC1);
        IntBuffer rotulosBuffer = labels.createBuffer();
        int counter = 0;
        for (File image: files) {
            opencv_core.Mat photo = imread(image.getAbsolutePath(), opencv_imgcodecs.CV_LOAD_IMAGE_GRAYSCALE);
            int classe = Integer.parseInt(image.getName().split("\\.")[1]);
            resize(photo, photo, new opencv_core.Size(IMG_SIZE,IMG_SIZE));
            photos.put(counter, photo);
           ##  //**i want to take out the values inside the FaceRecognizer. What should I do?**
            rotulosBuffer.put(counter, classe); 
            counter++;
        }
        opencv_face.FaceRecognizer eigenfaces = createEigenFaceRecognizer();
        **## //The meaning of this code is to save face information？**
        eigenfaces.train(photos, labels);

**Comment by saudet** [comment]
There's an example of this here:
https://github.com/bytedeco/javacv/blob/master/samples/OpenCVFaceRecognizer.java
If you have any specific code in C++ that you are having problems translating, please supply it.
