### ISSUE TITLE
Record Video is Green? Why?

### ISSUE THREAD

**Issue by Z-COL** [bytedeco/javacv#884]
![image](https://user-images.githubusercontent.com/6753155/35207528-7997308e-ff7e-11e7-9f1c-771e090b60f5.png)

**Comment by saudet** [comment]
Because you're not using the right pixel format. Please follow the examples here:
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-camera-preview
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-recognize

**Comment by Z-COL** [comment]
@saudet i'm just update lib，this code is useful for pre version
mFrameFilter.setPixelFormat(avutil.AV_PIX_FMT_NV21);

**Comment by saudet** [comment]
What do you mean? The examples do not work with JavaCV 1.4?

**Comment by Z-COL** [comment]
@saudet i set the config as sample，the issue is exist
#691 #509

**Comment by saudet** [comment]
Yes, but like I said, if you use JavaCV correctly, it does not happen:
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-camera-preview
https://github.com/bytedeco/sample-projects/tree/master/javacv-android-recognize

**Comment by saudet** [comment]
Specifying the pixel format on the recorder also helps, see issue #887.

**Comment by ritesh94** [comment]
@saudet 

None of the below is working:
record(filteredFrame,avutil.AV_PIX_FMT_YUV420P);
record(filteredFrame,avutil.AV_PIX_FMT_NV21);
record(filteredFrame,frameFilter.getPixelFormat());

**Comment by saudet** [comment]
Something like this: https://github.com/bytedeco/javacv/issues/945#issuecomment-376142199
