### ISSUE TITLE
How to convert between Mat and byte[]

### ISSUE THREAD

**Issue by blackredscarf** [bytedeco/javacv#888]
This is different from opencv's API. I'm not familiar with it.

**Comment by saudet** [comment]
new Mat(byte[]) works

**Comment by blackredscarf** [comment]
@saudet And Mat to byte[] ?

**Comment by saudet** [comment]
Mat.data().get(byte[]), pretty much the same as the C++ API.

**Comment by blackredscarf** [comment]
@saudet But `new Mat(byte[]) ` not available

**Comment by saudet** [comment]
Yes it is:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_core.Mat.html#Mat-byte...-

**Comment by blackredscarf** [comment]
@saudet I mean, the image of `new Mat(byte[])` is not the same as the original image. It's a long gray picture.

**Comment by saudet** [comment]
You never mentioned anything about an image. You'll need to clarify what
you want to do if you expect someone to help you.

**Comment by saudet** [comment]
An image has width, height, depth, and type so you'll also need to specify that, for example:
```java
Mat img2 = new Mat(rows, cols, CV_8UC(channels), new BytePointer(b));
```

**Comment by blackredscarf** [comment]
@saudet thanks very much

**Comment by tzolov** [comment]
Btw,  the `Mat.data().get(byte[])` seems to be skewing the image! So for the moment i'm using this workaround: 
```java
byte[] data = ((DataBufferByte) Java2DFrameUtils.toBufferedImage(mat).getRaster().getDataBuffer()).getData();
```
Maybe there are some additional image parameters i need to consider before transforming to bytes?

**Comment by saudet** [comment]
We need to consider the "step" or "stride", but just use an indexer, it will do that for you.

**Comment by tzolov** [comment]
Ok, got it
