### ISSUE TITLE
unable to load this jars? 

### ISSUE THREAD

**Issue by srajesh529** [bytedeco/javacv#89]
hi issue is not fixed,now i am using JavaCV 0.10,it is shows the errors in runtime and shutdown my app.below is my log.

01-30 09:59:56.730: I/System.out(21388): Step 2: call IOTC_Connect_ByUID(W6G9ST1FDWYH31CWUMZJ).......
01-30 09:59:57.000: I/System.out(21388): Step 2: call avClientStart(0).......
01-30 09:59:58.131: I/System.out(21388): [Video Thread] Start
01-30 09:59:58.131: E/ret value for video is(21388): <><>2607<><>0
01-30 09:59:58.131: E/videobuffer size ois(21388): <><>>2607
01-30 09:59:58.241: D/dalvikvm(21388): GC_FOR_ALLOC freed 218K, 3% free 9274K/9524K, paused 12ms, total 12ms
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libc.so 0x41e23f88, skipping init
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libm.so 0x41e23f88, skipping init
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libz.so 0x41e23f88, skipping init
01-30 09:59:58.371: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/libdl.so 0x41e23f88, skipping init
01-30 09:59:58.381: D/dalvikvm(21388): GC_FOR_ALLOC freed 348K, 4% free 9441K/9820K, paused 11ms, total 11ms
01-30 09:59:58.391: D/dalvikvm(21388): No JNI_OnLoad found in /system/lib/liblog.so 0x41e23f88, skipping init
01-30 09:59:58.391: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavutil.so 0x41e23f88
01-30 09:59:58.391: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavutil.so 0x41e23f88
01-30 09:59:58.391: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavutil.so 0x41e23f88, skipping init
01-30 09:59:58.391: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavutil.so 0x41e23f88
01-30 09:59:58.391: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavutil.so 0x41e23f88
01-30 09:59:58.411: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libswresample.so 0x41e23f88
01-30 09:59:58.411: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libswresample.so 0x41e23f88
01-30 09:59:58.411: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libswresample.so 0x41e23f88, skipping init
01-30 09:59:58.421: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswresample.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswresample.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavcodec.so 0x41e23f88
01-30 09:59:58.421: W/linker(21388): libavcodec.so has text relocations. This is wasting memory and is a security risk. Please fix.
01-30 09:59:58.421: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavcodec.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavcodec.so 0x41e23f88, skipping init
01-30 09:59:58.421: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavcodec.so 0x41e23f88
01-30 09:59:58.421: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavcodec.so 0x41e23f88
01-30 09:59:58.481: D/dalvikvm(21388): GC_FOR_ALLOC freed 426K, 5% free 9526K/9984K, paused 11ms, total 11ms
01-30 09:59:58.511: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavformat.so 0x41e23f88
01-30 09:59:58.511: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavformat.so 0x41e23f88
01-30 09:59:58.511: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavformat.so 0x41e23f88, skipping init
01-30 09:59:58.511: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavformat.so 0x41e23f88
01-30 09:59:58.511: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavformat.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libpostproc.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libpostproc.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libpostproc.so 0x41e23f88, skipping init
01-30 09:59:58.541: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjnipostproc.so 0x41e23f88
01-30 09:59:58.541: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjnipostproc.so 0x41e23f88
01-30 09:59:58.561: D/dalvikvm(21388): GC_FOR_ALLOC freed 457K, 5% free 9579K/10072K, paused 12ms, total 12ms
01-30 09:59:58.571: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libswscale.so 0x41e23f88
01-30 09:59:58.571: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libswscale.so 0x41e23f88
01-30 09:59:58.571: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libswscale.so 0x41e23f88, skipping init
01-30 09:59:58.571: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswscale.so 0x41e23f88
01-30 09:59:58.571: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniswscale.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavfilter.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavfilter.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavfilter.so 0x41e23f88, skipping init
01-30 09:59:58.591: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavfilter.so 0x41e23f88
01-30 09:59:58.591: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavfilter.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libavdevice.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libavdevice.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): No JNI_OnLoad found in /data/app-lib/com.tutk.sample.AVAPI-1/libavdevice.so 0x41e23f88, skipping init
01-30 09:59:58.611: D/dalvikvm(21388): Trying to load lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavdevice.so 0x41e23f88
01-30 09:59:58.611: D/dalvikvm(21388): Added shared lib /data/app-lib/com.tutk.sample.AVAPI-1/libjniavdevice.so 0x41e23f88
01-30 09:59:58.621: A/libc(21388): Fatal signal 11 (SIGSEGV) at 0x00000030 (code=1), thread 21511 (Video Thread)

**Comment by saudet** [comment]
Please don't create duplicates of your own issues.
