### ISSUE TITLE
JavaCV FFmpegFrameGrabber mp4?

### ISSUE THREAD

**Issue by Tatsukyo** [bytedeco/javacv#890]
Hi,

Honestly i'm not used to the video and javaCV but i need to work on it...
I'm currently trying to load some videos in a Java APP (.mp4, .mpg, etc... so i'm using your FFmpegFrameGrabber)

But i get an error

This is my code:
```
File test = new File("C:\\Users\\A874966\\Desktop\\TestFFmpeg\\test.mp4");
RandomAccessFile fileHdl = new RandomAccessFile(test, "r");
byte[] bufferA = new byte[(int) fileHdl.length() / 2];
byte[] bufferB = new byte[(int) fileHdl.length() / 2];

ArrayList<byte[]> arraylist = new ArrayList();
arraylist.add(bufferA);
arraylist.add(bufferB);


for (byte[] vbyte : arraylist)	
{
	fileHdl.read(vbyte);
	testVideo(vbyte);
}
fileHdl.close();
```

testVideo is:

```
public static void testVideo(byte[] pTest) throws FrameGrabber.Exception, IOException
{
	System.out.println("Hi");
	grabber = new FFmpegFrameGrabber(new ByteArrayInputStream(pTest));
	avutil.av_log_set_level(avutil.AV_LOG_QUIET);
	grabber.start();
	while (null != (img = grabber.grab()))
	{
		canvas.setSize(grabber.getImageWidth(), grabber.getImageHeight());
		canvas.showImage(img);
	}
	grabber.close();
}
```

and when i run, i get this error ... : 
```
Exception in thread "main" org.bytedeco.javacv.FrameGrabber$Exception: avformat_open_input() error -2: Could not open input "java.io.ByteArrayInputStream@47c62251". (Has setFormat() been called?)
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:572)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:508)
	at com.mycompany.testjavacv.test.testVideo(test.java:36)
	at com.mycompany.testjavacv.test.main(test.java:63)
```

The same code with a mpg file works could you explain where is my error ? 

As i said i'm not used to video so it would be nice if you could teach me :) 

PS: How do you play audio on the CanvasFrame ? i got the video but not the audio 
or maybe we can't get audio with the CanvasFrame 

Thanks you for ur help !

**Comment by saudet** [comment]
The error message says it all: You have an mp4 file, so call `setFormat("mp4")`.

**Comment by saudet** [comment]
And to render audio we can use Java Sound as demonstrated in this sample code:
https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java

**Comment by Tatsukyo** [comment]
thanks for ur answer but :x 

U know, i tried to add grabber.setFormat("mp4") but still got the error if it was so easily i would not post this to you x) 

It's probably because i split the byte array which is from the file in 2 parts 

with the MP4 i need all parts not like mpg  sadness


Anyway thanks for your help !

**Comment by saudet** [comment]
There was an issue with MP4 files that was fixed in recent versions of JavaCV, so please try again with the latest version, JavaCV 1.4.

**Comment by saudet** [comment]
And another problem with MP4 files is that they have a mandatory footer is at the end of the file. The way you are reading your files makes it impossible for FFmpeg to read the foot. Stop trying to do things in such a weird way and just stick with what is given in the examples!

**Comment by Tatsukyo** [comment]
I know right that's weird but at the ends the inputstream will be from camera and not a file so i just tried if i can split the data 

that's all,
