### ISSUE TITLE
avcodec_open2() error -22 (or -38) when encoding AMR-NB and AMR-WB audio files at the same time

### ISSUE THREAD

**Issue by canelzio** [bytedeco/javacv#891]
Hello,
during encoding test session I got the following exceptions when trying to encode AMR-NB and AMR-WB audio files at the same time:
`org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -22: Could not open audio codec.`

or 
`org.bytedeco.javacv.FrameRecorder$Exception: avcodec_open2() error -38: Could not open audio codec.`

I'm not able to go deeper in the analysis of the root cause.
Could you please help me debugging this?

Thank you.

**Comment by saudet** [comment]
It just sounds like the codecs are not thread-safe, doesn't it?

**Comment by canelzio** [comment]
Yes, you’re probably right.
Any idea for overcoming this?

**Comment by saudet** [comment]
You could use synchronize blocks in your application...

**Comment by canelzio** [comment]
Thanks for the tip, but I thought I should act at lower level in order to manage/enable the threadsafe feature on AMR codecs (i.e. at build time on Javacpp).

If it is not possible I will try to manage it at higher level in my code.

**Comment by saudet** [comment]
Thread safety is already enabled at the FFmpeg level and works with most
codecs:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameGrabberTest.java#L128
We should report this issue upstream...

**Comment by saudet** [comment]
This should be fixed with commit https://github.com/bytedeco/javacv/commit/cc39f610a1dcd9c8216f015c23fda454cd1573c7.
Please give it a try with the snapshots: http://bytedeco.org/builds/
I'll mark this as a duplicate of #1139, but please let me know if this doesn't fix it. Thanks!
