### ISSUE TITLE
Change captured image size without squeezing !!

### ISSUE THREAD

**Issue by ahmedaomda** [bytedeco/javacv#892]
I can't find any equivalent way to change the size of the captured image without squeezing as in OpenCV like this :
`Imgproc.resize(sourceMat,destMat,new Size(500,510));` 
and can't use `setAspectRatio()` in `FrameGrapper`

**Comment by saudet** [comment]
It's right [here](http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_imgproc.html#resize-org.bytedeco.javacpp.opencv_core.Mat-org.bytedeco.javacpp.opencv_core.Mat-org.bytedeco.javacpp.opencv_core.Size-).

**Comment by ahmedaomda** [comment]
thanks alot
