### ISSUE TITLE
FFmpegFrameFrabber(InputStream)

### ISSUE THREAD

**Issue by Tatsukyo** [bytedeco/javacv#894]
Hi @saudet 

I know what i'm trying to do is strange as always, and won't work probably but i just want to know one thing,

so can you confirm this to me?

Currently i'm working on a project and the video parts is pretty bad 

To explain easily, each 40ms we received 188o from a video streaming or file

i tried the Piped(Input/Output)Stream to try to not lose some frame but i got only the first package in the CanvasFrame

I'm still a student and i'm rly not used to video and FFmpeg but could u explain how, can we do, if we can to load the video ?

each 40ms we receive a package of 188bytes byte[] which is converted to ByteArrayInputStream but i don't get it how can i read all the video without losing frame

Obviously we are splinting sometimes on a frame parts so we probably lost each times 1 frame or maybe more ! ...

Thanks for ur help anyway JavaCV is powerfull but maybe i'm not using it like we should

**Comment by saudet** [comment]
That sounds like a network...

**Comment by Tatsukyo** [comment]
I don't know i'm trying many things but nothing works xD 

Maybe if we can update the inputStream without recreating the framegrabber 

it should work but i don't know how to do this, the piped sound good but nothing

**Comment by saudet** [comment]
If you're trying to load image data, try to use OpenCV and imdecode() instead.

**Comment by Tatsukyo** [comment]
Oh Thanks U i'm going to check right now 

but i need sound too ..

**Comment by saudet** [comment]
You'll have to explain what you're trying to do if you want someone to be able to help...

**Comment by Tatsukyo** [comment]
Currently i have a mpg file

i'm spliting it in 4 parts with 
```
RandomAccessFile fileHdl = new RandomAccessFile(Filetest, "r");
byte[] bufferA = new byte[(int) (fileHdl.length() / 4)];
byte[] bufferB = new byte[(int) (fileHdl.length() / 4)];
byte[] bufferC = new byte[(int) (fileHdl.length() / 4)];
byte[] bufferD = new byte[(int) (fileHdl.length() / 4)];
ArrayList<byte[]> arraylist = new ArrayList();
arraylist.add(bufferA);
arraylist.add(bufferB);
arraylist.add(bufferC);
arraylist.add(bufferD);
```

sending them to the FrameGrabber with
```
for (byte[] vbyte : arraylist)
{
	fileHdl.read(vbyte);
	testVideo(vbyte);
}
```

testVideo is:
```
ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
outputStream.write(oldByteArray);
outputStream.write(pTest);
oldByteArray=pTest;
Stream.setBuf(outputStream.toByteArray());
if (grabber == null)
{
	grabber = new FFmpegFrameGrabber(Stream);
	avutil.av_log_set_level(avutil.AV_LOG_QUIET);
	grabber.start();
}
else
{
	System.out.println("Hi, OLDTIMESTAMP="+grabberTimeStamp);
	grabber.start();
	grabber.setTimestamp(grabberTimeStamp);
	System.out.println("Hi, getTimeStamp="+grabber.getTimestamp());
}
AudioFormat audioFormat = new AudioFormat(grabber.getSampleRate(), 16, grabber.getAudioChannels(), true, true);
DataLine.Info info = new DataLine.Info(SourceDataLine.class, audioFormat);
soundLine = (SourceDataLine) AudioSystem.getLine(info);
soundLine.open(audioFormat);
soundLine.start();
while ((frame = grabber.grab()) != null)	
{
	TimeStampOld=System.nanoTime();
	if (frame.samples != null)
	{
		ShortBuffer channelSamplesShortBuffer = (ShortBuffer) frame.samples[0];
		channelSamplesShortBuffer.rewind();
		ByteBuffer outBuffer = ByteBuffer.allocate(channelSamplesShortBuffer.capacity() * 2);
		for (int i = 0; i < channelSamplesShortBuffer.capacity(); i++)
		{
			short val = channelSamplesShortBuffer.get(i);
			outBuffer.putShort(val);
		}
		soundLine.write(outBuffer.array(), 0, outBuffer.capacity());
		outBuffer.clear();
	}
	else
	{
		if (frame.image != null)
		{
			new Thread()
			{
		          	@Override
				public void run()
				{
			                canvas.showImage(frame);
					NbImage++;
				}
			}.start();
			Thread.sleep((long) ((1000 - ((System.nanoTime() - TimeStampOld) / 1000000)) / grabber.getFrameRate()));
		}
	}
	System.out.println(grabber.getTimestamp());
	grabberTimeStamp = grabber.getTimestamp();
}
grabber.close();
soundLine.close();
```

currently i'm trying to not lose frame when i split a video file cuz later it will be split for 188bytes parts ...

**Comment by saudet** [comment]
So you want to do some streaming? Try to use FFmpeg for that, for example:
https://trac.ffmpeg.org/wiki/StreamingGuide

**Comment by Tatsukyo** [comment]
but, it's necessary on a Java APP that's why i'm looking at JavaCV

**Comment by saudet** [comment]
So, use `FFmpegFrameRecorder` to stream video. There's sample code here that uses RTMP, for example, so start with that:
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java

**Comment by saudet** [comment]
You can also try the TCP protocol, that's probably what you want:
https://github.com/bytedeco/javacv/issues/598#issuecomment-271122140

**Comment by Tatsukyo** [comment]
Thanks you for your answer but, i need to show frame on a canvasFrame, that's why it's just strange 

i get data parts by parts and i need to decode them to show them on a canvasFrame ... and i don't get it how i can easily with BufferInputStream but i lose too much frame and this is not good

**Comment by saudet** [comment]
So don't use InputStream...

**Comment by Tatsukyo** [comment]
then what should i use? file ? no i don't get file, path? too i only get byte[] that's why it's ... a bit strange ?

**Comment by saudet** [comment]
Please at least read the page about streaming with FFmpeg.
