### ISSUE TITLE
Improper Camera Close

### ISSUE THREAD

**Issue by ahmedaomda** [bytedeco/javacv#897]
I'm making an app that open the camera in a page and close it after taking a shot and move to another page and get back again to the camera page it's a desktop app using javafx but when I get back to the camera page i get an exception:
`FrameGrabber$Exception: Failed to load class org.bytedeco.javacv.FlyCapture2FrameGrabber`
and an
`UnsatisfiedLinkError: no jniFlyCapture2 in java.library.path`
In the line that create the `FrameGrapper`
`frameGrabber = FrameGrabber.createDefault(0);`

I'm guessing it's a problem in closing the camera
I'm using
`frameGrabber.close();`

**Comment by saudet** [comment]
No, that just means you don't have FlyCapture 2 installed. You can ignore that message.

**Comment by saudet** [comment]
It's possible that something gets corrupted when trying to load the other grabbers though. If you only need to support OpenCVFrameGrabber, it's better to create an instance of that directly. If you are still having problems when using OpenCVFrameGrabber only, please let me know! Thanks
