### ISSUE TITLE
Cannot find Facemark class on Javacv-Opencv?

### ISSUE THREAD

**Issue by Luca96** [bytedeco/javacv#901]
Hi, i'm developing an android application based on facial landmark recognition and i have successfully configured javacv. The problem is that i cannot find the Opencv facemark classes like: _Facemark_, _FacemarkAAM_ and _FacemarkLBF_ (as described here -> [https://docs.opencv.org/trunk/db/dd8/classcv_1_1face_1_1Facemark.html] ).
Thanks in advance.

**Comment by saudet** [comment]
It's been added here: https://github.com/bytedeco/javacpp-presets/commit/53d78e39a27328ab8917f6a0c0d163b80a76ac0e

**Comment by Luca96** [comment]
Hi @saudet , thanks for the answer but things are getting strange because the opencv_java.class file hosted on Github has the classes that i need (has a size of 1875 line of code) instead the opencv_java.class file fetched from Gradle has only 776 lines and the classes are missing, How is it possible?

Here is a part of my build.gradle: 
`
dependencies {
    compile 'org.bytedeco:javacv:1.4'
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.0-1.4', classifier: 'android-x86'
}
`

**Comment by saudet** [comment]
Use the SNAPSHOT artifacts: http://bytedeco.org/builds/

**Comment by Luca96** [comment]
I added this to my build.gradle:
`repositories {
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}`

and then, i added SNAPSHOT to the javacpp-presets dependency: 
`compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.0-1.4.1-SNAPSHOT', classifier: 'android-x86', changing: true`

But it still download the code without the classes, in fact in the folder: gradle\caches\modules-2\files-2.1\org.bytedeco.javacpp-presets\opencv\ there is a folder named **3.4.0-1.4.1-SNAPSHOT** in which there is only the pom file and another folder named **3.4.0-1.4** which contains the jars.

I've tried to clean the gradle folders (*files* and *metadata*) and download everything again but nothing.

**Comment by saudet** [comment]
Gradle doesn't work well with SNAPSHOT artifacts. You'll need to use Maven or download the JAR files manually.

**Comment by saudet** [comment]
More precisely here: https://oss.sonatype.org/content/repositories/snapshots/org/bytedeco/javacpp-presets/opencv/3.4.0-1.4.1-SNAPSHOT/

**Comment by Luca96** [comment]
Thanks very much @saudet , now everything works well!!
