### ISSUE TITLE
Mat.data has zero capacity

### ISSUE THREAD

**Issue by 805447391** [bytedeco/javacv#902]
I want to resize my source Mat to a new Mat, so here is my code :
`
Mat dstMat = new Mat();
dstMat.create(imageSize, CV_8UC3);
System.out.println(dstMat.data());
resize(srcMat, dstMat, imageSize, 0, 0, CV_INTER_LINEAR);
`
but I find that dstMat.data.capacity is 0 ??? where is the problems ?

**Comment by 805447391** [comment]
here is the output, it show dstMat.data 's information.
`org.bytedeco.javacpp.BytePointer[address=0x1f3dd080,position=0,limit=0,capacity=0,deallocator=null]`

**Comment by saudet** [comment]
You should be looking at the public method `Mat.data()`, not the private field `Mat.data`.
