### ISSUE TITLE
FFmpegFrameRecorder object not taking IplImage object ?

### ISSUE THREAD

**Issue by KulwinderSinghRahal** [bytedeco/javacv#903]
I am using latest 1.4 version of javaCV  below is dependencies I am using  
`    compile group: 'org.bytedeco', name: 'javacv', version: '1.4' `
   ` compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.0-1.4', classifier: 'android-arm'`
    `compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.0-1.4', classifier: 'android-x86'`
    `compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.1-1.4', classifier: 'android-arm'`
    `compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.4.1-1.4', classifier: 'android-x86'`
but as I seen in some examples of java CV its ffmpegFrameRecorder object is not taking IplImage but examples that I have seen is working, below is my code  
`    public void create(final ArrayList<String> imgs, final String saveFileNamePath) {

        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(saveFileNamePath, 400, 400);

        try {
            recorder.start();
            for (int i = 0; i < imgs.size(); i++) {
                opencv_core.IplImage foto = cvLoadImage(imgs.get(i));

                long t = 3000 * (System.currentTimeMillis() - startTime);

                if (t > recorder.getTimestamp()) {
                    recorder.setTimestamp(t);
                    recorder.record(foto);//HERE IS PROBLEM,ITS NOT TAKING IplImage OBJECT AS PARAMETER
                }
            }
            System.out.println("Total Time:- " + recorder.getTimestamp());
            recorder.stop();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
`

**Comment by saudet** [comment]
That changed a bit, you'll need to use OpenCVFrameConverter:
http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by KulwinderSinghRahal** [comment]
so I need to do like this  
`OpenCVFrameConverter converter = new OpenCVFrameConverter.ToIplImage();` 
and then  
`recorder.record(converter.convert(foto));`
