### ISSUE TITLE
Unable to show each image for 1 second ?

### ISSUE THREAD

**Issue by KulwinderSinghRahal** [bytedeco/javacv#907]
I am creating video from number of images so I want to give 1 second for each image in video for that I am using below code  

      try {
            //recorder.setVideoCodec(5);
            recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
            recorder.setFormat("mp4");
            recorder.setFrameRate(30);
            recorder.setVideoBitrate(2500);
            long startTime = System.currentTimeMillis();

            recorder.start();

            long imageTime = 1000;
            for (int i = 0; i < imgs.size(); i++) {
                opencv_core.IplImage foto = cvLoadImage(imgs.get(i));
                long timestamp = (i + 1) * imageTime;
                if (timestamp > recorder.getTimestamp()) {
                    recorder.setTimestamp(timestamp);
                    recorder.record(converter.convert(foto));
                }
            }
            System.out.println("Total Time:- " + recorder.getTimestamp());
            recorder.stop();
        } catch (Exception e) {
            e.printStackTrace();
        }

but its creating very small video which does not even shows single image correctly,video length is only 1 second but I want to give 1 second for each image in video pls help how to achieve this ?

**Comment by saudet** [comment]
just setFrameRate(1)

**Comment by KulwinderSinghRahal** [comment]
I have changed to `recorder.setFrameRate(1);` but it is still not working

**Comment by saudet** [comment]
Try another codec or record multiple times the same image.

**Comment by KulwinderSinghRahal** [comment]
if I set to 1 lacks like `long imageTime = 100000`  it works but not accurate ,first Images shown for little longer than last images

**Comment by saudet** [comment]
So, try the second option: 
> record multiple times the same image.
