### ISSUE TITLE
Audio and Video Inconsistent after simple decoding and encoding

### ISSUE THREAD

**Issue by jiangyurong609** [bytedeco/javacv#909]
I'm trying to do a simple transcoding of mp4 video (resize from 1280x960 to 640x360) and change audio and video bitrate. The codec remains same. However, the process is finished, I found the output video's video and audio streams become inconsistent. Meanwhile, I compare the result with '''ffmpeg''' command, it turns out the code output has worse quality than command line output. Could you please help point me the issue? Thanks
```
        FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(inputFile);
        FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(outputFile, video_width, video_height, audioChannel);
        recorder.setAudioBitrate(audio_bitrate);
        recorder.setVideoBitrate(video_bitrate);

        recorder.start();
        grabber.start();
        Frame frame;
        //long t1 = System.currentTimeMillis();
        while ((frame = grabber.grabFrame(AUDIO_ENABLED, true, true, false)) != null) {
            recorder.record(frame);
        }
        recorder.stop();
        grabber.stop();
```

**Comment by saudet** [comment]
Well, you'll at least need to use the same options as used on the command line to expect the same results.

**Comment by jiangyurong609** [comment]
Thanks for your reply. My question is the inconsistency between the audio and video after the decoding and encoding. I'm not sure what I'm missing from the code. Really appreciate if you could point out the issue in my simple code. Regarding to 2nd question about the command line, I used "ffmpeg -i input.mp4 -s wxh -c:v vbitrate, -c:a abitrate output.mp4", I'm not sure which part I missed from the code against the command line. Thanks a lot.

**Comment by saudet** [comment]
You're probably not using the same codecs. You should at least specify what
you want.

**Comment by jiangyurong609** [comment]
Thanks again for the reply. However, even after I specify the exact same codecs, the output is still same (inconsistent audio and video). 
```
recorder.setVideoCodec(28);
recorder.setAudioCodecName("aac");
```
I'm not sure which part might still be wrong. 

Thanks

**Comment by saudet** [comment]
Could you please post the console output that you get for both JavaCV and
for the ffmpeg program from the command line?
