### ISSUE TITLE
FFmpegFrameRecorder Exception When Recording Video from FFmpegFrameGrabber

### ISSUE THREAD

**Issue by lessthanoptimal** [bytedeco/javacv#914]
I'm opening a mp4 video using FFmpegFrameGrabber distorting the images, then saving it to another mp4 using FFmpegFrameRecorder. Audio is left unmodified. This code worked until i upgraded to 1.4.  After inspecting the code it appears some fixes to FFmpegFrameGrabber's audio support are messing with FFmpegFrameRecorder. I've pasted the exception below:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/pja/Desktop/BreckBackSideTrees.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 537134592
    compatible_brands: mp42    
    creation_time   : 2017-02-05T18:41:07.000000Z
  Duration: 00:01:36.10, start: 0.000000, bitrate: 16149 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, smpte170m/bt709/smpte170m), 1920x1080 [SAR 1:1 DAR 16:9], 16005 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      creation_time   : 2017-02-05T18:41:07.000000Z
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 32000 Hz, mono, fltp, 46 kb/s (default)
    Metadata:
      creation_time   : 2017-02-05T18:41:07.000000Z
[aac @ 0x7f9298b63040] Specified sample format s16 is invalid or not supported
thirdparty.FrameRecorder$Exception: avcodec_open2() error -22: Could not open audio codec. aac
	at thirdparty.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:726)
	at thirdparty.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:348)
```
To cut down on the size of the application I'm not including all of JavaCV, just a few files I need. Which is why the path is a bit off. FFmpegFrameRecorder is a copy of what's in the git repo right now.

Theory:
Audio definitely works much better after recent changes to FFmpegFrameGrabber. However, the behavior of getSampleFormat() on line 403 has changed. Before it returned the result of:

`audio_c.sample_fmt();`

 and now it returns the result of 

` sampleMode == SampleMode.SHORT ? AV_SAMPLE_FMT_S16 : AV_SAMPLE_FMT_FLT`;

I think that FFmpegFrameRecorder needs to be updated to understand this new result and is probably a simple fix for someone that understands how the code works better. I hacked around it by detecting the grabber returning a value of 1 and then changing it to a value of 8, which is what it returned in the previous version. I checked the recorded file it audio works just fine.

**Comment by saudet** [comment]
That's just FFmpeg's AAC codec not supporting 16-bits samples anymore. We have to use float samples, but FFmpegFrameRecorder itself converts to that from any sample format. Simply leave the sample format to AV_SAMPLE_FMT_FLT and all will be fine.
