### ISSUE TITLE
FaceRecognizerInVideo.java:49: error: cannot find symbol 

### ISSUE THREAD

**Issue by mycharm06** [bytedeco/javacv#916]
FaceRecognizerInVideo.java:49: error: cannot find symbol
        FaceRecognizer lbphFaceRecognizer = createLBPHFaceRecognizer();

**Comment by saudet** [comment]
The API changed a bit:
https://github.com/bytedeco/javacv/commit/2836f78fd1656af83739b5e816fe6398fc78add9

**Comment by saudet** [comment]
Ok, I've updated the sample code in the latest commit above. Enjoy and thanks for reporting!
