### ISSUE TITLE
Crop frame then put it on photo background.

### ISSUE THREAD

**Issue by NHANNGUYEN92** [bytedeco/javacv#919]
Hi @saudet ,
-  I have a video file 960 x 540, I want to crop it to 477 x 540 then put to a photo background 960x540.

- I using code bellow, It works fine if I crop a video to 800 x 540 but I only get result background photo and sound without video if I crop a video to 477 x 540. I don't know why.

```
FFmpegFrameFilter  cropFilter  = new FFmpegFrameFilter("crop=w=477:h=540:x=0:y=0", 960, 540);
// FFmpegFrameFilter cropFilter  = new FFmpegFrameFilter("crop=w=800:h=540:x=0:y=0", 960, 540); // work fine

opencv_core.Mat backgroundMat = opencv_imgcodecs.imread(mediaPath + "bg.jpg");
       
cropFilter.push(frame);
opencv_core.Mat  input  =converterToMat.convert(cropFilter.pull());
opencv_core.Mat roi  = new opencv_core.Mat(backgroundMat, new opencv_core.Rect(0, 0, input.cols(), input.rows()));
input.copyTo(roi);
recorder.record(converterToMat.convert(backgroundMat));
```

                                
  Thank you so much!

**Comment by saudet** [comment]
Odd numbers like 477 are not image widths supported by most codecs. Try a
different codec.

**Comment by NHANNGUYEN92** [comment]
Thank @saudet  for your reply.
-  I can do 2 steps
 1. Only Crop a  video 960 x540 to 480 x 560 then save a cropped video 480 x 560 as a video file
 2. Put a cropped video into background 960 x 540. 
-> It works fine but It takes double process time.

- I hope I can do both it at one time like that but seem to it is not working

```
FFmpegFrameFilter  cropFilter  = new FFmpegFrameFilter("crop=w=480:h=540:x=0:y=0", 960, 540);

opencv_core.Mat backgroundMat = opencv_imgcodecs.imread(mediaPath + "bg.jpg");
       
cropFilter.push(frame);
opencv_core.Mat  input  =converterToMat.convert(cropFilter.pull());
opencv_core.Mat roi  = new opencv_core.Mat(backgroundMat, new opencv_core.Rect(0, 0, input.cols(), input.rows()));
input.copyTo(roi);
recorder.record(converterToMat.convert(backgroundMat));
```
- Do you have any suggestion?

**Comment by saudet** [comment]
There's probably a way to do that with only filters... https://ffmpeg.org/ffmpeg-filters.html
