### ISSUE TITLE
OSX 10.10: OpenCVFrameGrabber freezes the application

### ISSUE THREAD

**Issue by Golui** [bytedeco/javacv#92]
I wanted to play around with JavaCV and I tried to compile some sample code. After linking the native binaries, it did compile, however, it didn't work. After doing some research, I pinned down the problem might be the OpenCVFrameGrabber class.

To reproduce compile the following code:
```
public class Test 
{
    public static void main(String[] args) throws Exception 
    {
        OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(0);
        grabber.start();

        IplImage frame = grabber.grab();
        IplImage image = null;
        IplImage prevImage = null;
        IplImage diff = null;

        System.out.println("Before");
        CanvasFrame canvasFrame = new CanvasFrame("Test");
        System.out.println("After");
        canvasFrame.setCanvasSize(frame.width(), frame.height());

        grabber.stop();
        canvasFrame.dispose();
    }
}
```

The webcam will turn on and the app will freeze, with the console output 'Before'.

I've been unable to reproduce this issue on the python bindings, so I believe this is a JavaCV issue. Also, it runs fine on Windows.

I'm using JavaCV 0.10 with OpenCV 2.4.10 and Java 8. OS is OSX 10.10 Yosemite.

**Comment by saudet** [comment]
Does the same thing happen if you use the new C++ API of OpenCV directly?

**Comment by Golui** [comment]
No. Neither using the native C++ API (version 2.4.10) nor the Python bindings.

**Comment by saudet** [comment]
Are you saying there is no problem if you use the following `VideoCapture` class in Java?
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_highgui.VideoCapture.html

**Comment by Golui** [comment]
I have not tried this. I'm new to opencv in general, can you please give me a sample program?

**Comment by saudet** [comment]
Just do it the same way you would do it from C++ or Python.

**Comment by Golui** [comment]
Using the VideoCapture I am able to display the frames, so I suppose it works.

However, the FrameGrabber still hangs. I also forgot to mention that the code I was testing it with was a stripped down version of the MotionDetection sample.

**Comment by saudet** [comment]
So, maybe it's only the old C API of OpenCV that doesn't work well anymore. What happens when if you call the following?
```java
CvCapture capture = cvCreateCameraCapture(0);
IplImage image = cvQueryFrame(capture);
```

**Comment by Golui** [comment]
It does work, however, the canvas is blank about every second frame.

**Comment by saudet** [comment]
Right, so it works with `VideoCapture`. I'll be sure to use that, but first I need to redesign `FrameGrabber` so it doesn't rely on `IplImage` or `Mat`, to remove the dependency on OpenCV for users of FFmpeg only. But I haven't figured out yet what we should use. Any ideas?

**Comment by Golui** [comment]
Don't ask me. I'm new to this.

**Comment by saudet** [comment]
Does this still happen with JavaCV 0.11 and OpenCV 2.4.11?

**Comment by saudet** [comment]
OpenCV still doesn't support AVFoundation, but FFmpeg does, so I would say the fix to this issue is simply to use FFmpegFrameGrabber with the AVFoundation device: https://github.com/bytedeco/javacpp-presets/issues/39
