### ISSUE TITLE
Error in predicting image

### ISSUE THREAD

**Issue by mycharm06** [bytedeco/javacv#923]
In OpenCVFaceRecognizer.java , I have successfully ran the program but when it goes for predicting it predicts or gives the output even if there is no one in the **TestImage** and sometimes it also predicts wrong faces pls see the problem.

Thanks

**Comment by saudet** [comment]
You'll need to understand how the algorithms work to improve this. Here is a good tutorial for that:
https://docs.opencv.org/3.4.0/da/d60/tutorial_face_main.html
