### ISSUE TITLE
trying to set up a service in Java and netbeans

### ISSUE THREAD

**Issue by behrouz2000** [bytedeco/javacv#924]
I am setting up a method as a service but when I deploy and test the service I get the error;
java.lang.UnsatisfiedLinkError: no opencv_java340 in java.library.path

I have set up the vm options to -Djava.library.path="C:\Users\bheda\Desktop\opencv\build\java\x64"
the path to my .dll file and even put this path to the PATH of my environment variables in windows but still does not work.  What can I do?

**Comment by saudet** [comment]
That's not JavaCV, you'll find that DLL at https://opencv.org/releases.html
