### ISSUE TITLE
Issue in OpenCVFaceRecognizer

### ISSUE THREAD

**Issue by mycharm06** [bytedeco/javacv#925]
I just want to have **FaceRecognizer.class** to see the methods of the class.
If you can guide me how to get the .class file.

Thanks

**Comment by Luca96** [comment]
Well, if you're using an IDE (like intelliJ IDEA) you can type the class name usually an hint appear, so select the right class and hit **ENTER**, this will import the class and finally use **CTRL + CLICK** on the class name to see the file .class of the classes you're looking for.

**Comment by saudet** [comment]
API docs is available here:
http://bytedeco.org/javacpp-presets/opencv/apidocs/org/bytedeco/javacpp/opencv_face.FaceRecognizer.html
