### ISSUE TITLE
createLBPHFaceRecognizer()

### ISSUE THREAD

**Issue by ivdrmyns** [bytedeco/javacv#926]
I have a problem with te sample code of FaceRecognizerInVideo.  My IDE ( I've tried Netbeans and ItelliJ) doesn't recognize the createLBPHFaceRecognizer() and the load() function on the Facerecognizer. I don't know what is wrong, there are no problems with imports. Does anyone know what the problem is? # #

**Comment by saudet** [comment]
It's been renamed to `LBPHFaceRecognizer.create()`. See issue #916.
