### ISSUE TITLE
Problem on using FFmpegFrameFilter to apply Fade In Fade Out effect on video.

### ISSUE THREAD

**Issue by wa4663039** [bytedeco/javacv#928]
Hello,

I am trying to apply the fade in and fade out effect on a video useing FFmpegFrameFilter, however, the FFmpegFrameFilter seems to process individual frame, and I got a totally black video.

Here is a part of my code, would you please advise how to apply a fade in effect correctly? Thanks a lot
```java
FrameRecorder recorder = new FFmpegFrameRecorder(ENV_PATH + "/output" + time + ".mp4", frameGrabbers.get(0).getImageWidth(), frameGrabbers.get(0).getImageHeight());
recorder.setFrameRate(frameGrabbers.get(0).getFrameRate());
recorder.setSampleFormat(frameGrabbers.get(0).getSampleFormat());
recorder.setSampleRate(frameGrabbers.get(0).getSampleRate());
recorder.start();

FFmpegFrameFilter fFmpegFrameFilter = new FFmpegFrameFilter("fade=t=in:st=5.5:d=1",frameGrabbers.get(0).getImageWidth(),frameGrabbers.get(0).getImageHeight());

            fFmpegFrameFilter.start();
            int frameNum = 0;
            for (FrameGrabber fg : frameGrabbers) {

                while ((frame = fg.grabFrame()) != null) {
                    if(frame.image != null) {

                            fFmpegFrameFilter.push(frame);
                            frame = fFmpegFrameFilter.pull();

                        recorder.record(frame);
                        frameNum++;
                    }

                }

                if (k == frameGrabbers.size()) {
                    fg.stop();
                    Log.i(LOG_TAG, "STOP");
                }
            }

fFmpegFrameFilter.stop();
recorder.stop();
recorder.release();
```

**Comment by saudet** [comment]
This has already been answered on the mailing list at 
https://groups.google.com/forum/#!topic/javacv/4UDKpdaMHSM :

> Ok, then according to the source code of the ffmpeg program at
> https://github.com/FFmpeg/FFmpeg/blob/n2.8.4/ffmpeg_filter.c#L773
> that command automatically appends a "setpts=N" filter to the graph. So, we can do that with FFmpegFrameFilter as well this way:
> 
> filter = new FFmpegFrameFilter("setpts=N,fade=t=in:st=2.5:d=1", ...);
> 
> And that works as expected.

**Comment by saudet** [comment]
FYI, with the changes in commit https://github.com/bytedeco/javacv/commit/35dd7f8134ff4b31e6ff94ab6049f2a13418cc5a it's no longer necessary to add the `setpts=N` filter manually, so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/
