### ISSUE TITLE
Support AVPacket to efficiently segment, trim, encode with hardware, stream multiple times, etc

### ISSUE THREAD

**Issue by dheerajbhaskar** [bytedeco/javacv#93]
I'm referring to the `-segment_time` in the command below

    ffmpeg -i fff.avi -acodec copy -f segment -segment_time 10 -vcodec copy -reset_timestamps 1 -map 0 -an fff%d.avi

Above code grabbed from http://unix.stackexchange.com/questions/148602/ffmpeg-split-video-multiple-parts

I'm also aware of this feature being requested earlier https://groups.google.com/forum/#!topic/javacv/4wO6gODaq4w

**Comment by saudet** [comment]
It's possible to do it manually by grabbing the frames and recording only the ones we're interested in. But, to be more efficient, we would need to provide a way to bypass the decoding and encoding process, and pass the packets directly:
https://code.google.com/p/javacv/issues/detail?id=456
Is this a project you would like to work on?

**Comment by alicanalbayrak** [comment]
Hi samuel,
I tried to bypass decode and encode process, and it seems works so far. 

[https://github.com/alicanalbayrak/java-ffmpeg-experiments/blob/master/src/main/java/org/gilmour/ffmpeg/examples/Remuxer.java](url)

**Comment by saudet** [comment]
@alicanalbayrak Cool! Could you include the necessary logic in `FFmpegFrameGrabber` and `FFmpegFrameRecorder`? I'm thinking we could provide additional `grabPacket()` and `recordPacket()` methods for that.

**Comment by alicanalbayrak** [comment]
Sure, I'll work on that. I'm planning to send you pull request in a few days.
.

**Comment by saudet** [comment]
The implementation from @alicanalbayrak is part of the just released version 1.2! Thanks for the contribution :)

**Comment by saudet** [comment]
FYI, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.
