### ISSUE TITLE
Gradle android-arm64 and android-x86_64

### ISSUE THREAD

**Issue by wbish** [bytedeco/javacv#930]
Hey @saudet 

Thanks for making the android-arm64 and android-x86_64 jars available. I've tried doing the manual installation for it and it all works great now.

Any chance you could publish these to gradle?

**Comment by saudet** [comment]
Artifacts are available, see http://bytedeco.org/builds/ , but Gradle doesn't work too well with snapshot versions and the Gradle team don't seem to care too much at the moment, see: gradle/gradle#2882
https://discuss.gradle.org/t/maven-metadata-with-classifiers-fails-to-resolve-for-snapshots/20071

If you could let them know you need better Maven compatibility, that would be great!

**Comment by saudet** [comment]
Released with JavaCV 1.4.1! Enjoy

**Comment by wbish** [comment]
@saudet Awesome. Thank you!
