### ISSUE TITLE
How to use javacv to record windows Desktop?

### ISSUE THREAD

**Issue by jliu666** [bytedeco/javacv#934]
I want to record screen by java, not only on windows, but also Mac OS and Linux.

**Comment by jliu666** [comment]
I want a example.

**Comment by saudet** [comment]
There are instructions for this here: https://trac.ffmpeg.org/wiki/Capture/Desktop

But examples using FFmpegFrameGrabber would be great, so please consider making a contribution.

I'll mark this as a duplicate of issue #31. Please post comments/questions there! Thanks
