### ISSUE TITLE
Mat mat = new Mat(HEIGHT, WIDTH, CvType.CV_8UC3, byte[] data);

### ISSUE THREAD

**Issue by clplaneguy** [bytedeco/javacv#935]
Please excuse my noob question.

I am trying to import/read a video/frame from my webcam and process in Opencv.  The data comes in as byte[] and I must convert to Mat.  That could be done in one of two ways:

1)
```
byte[] Image;
Image = Camera.createFrame();
mymat.put(HEIGHT, WIDTH, Image);
```
But, I get a compile time error: 

2)
`public Mat(int rows, int cols, int type, ByteBuffer data)`
When executing the code

```
byte[] Image;
Image = Camera.createFrame();
Mat mymat = new Mat(HEIGHT, WIDTH, CvType.CV_8UC3, Image);
```
But, I get the error message:

`The constructor Mat(int, int, int, ByteBuffer) is undefined`

What am I missing?

**Comment by saudet** [comment]
Do something like in the RecordActivity sample and it will work:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java

**Comment by clplaneguy** [comment]
THANK YOU

But, is there something more simple(smaller) that addresses the issue?

**Comment by saudet** [comment]
It sounds like what you are looking for is `new Mat(height, width, type, new BytePointer(byte[]))`.
