### ISSUE TITLE
Too many jar files to package

### ISSUE THREAD

**Issue by jliu666** [bytedeco/javacv#937]
I only use javacv on macos. but linux and andriod also here. Maybe the maven artifactId could be improved.
![2018-03-12 11 03 52](https://user-images.githubusercontent.com/14869749/37263857-15c00990-25e5-11e8-89df-c6d34813a430.png)

**Comment by saudet** [comment]
Set the javacpp.platform system property to macosx-x86_64, and you'll get
only those!

**Comment by jliu666** [comment]
maybe `${os.name}` is useful for this problem.

**Comment by jliu666** [comment]
Like this?
![2018-03-12 11 13 23](https://user-images.githubusercontent.com/14869749/37264073-679b5188-25e6-11e8-94a3-9eb79b0a601b.png)

**Comment by saudet** [comment]
No, like this on the command line: "mvn -Djavacpp.platform=macosx-x86_64 ..."

**Comment by jliu666** [comment]
I try it. But error like this:
![2018-03-12 11 29 18](https://user-images.githubusercontent.com/14869749/37264507-a0d1f7e8-25e8-11e8-991d-8b6881932ee1.png)

**Comment by jliu666** [comment]
OK. I resolve it. Must run `mvn -Djavacpp.platform=macosx-x86_64 install` first.

**Comment by jliu666** [comment]
Thank you very much!
