### ISSUE TITLE
extraction d'audio à partir d'un vidéo

### ISSUE THREAD

**Issue by ayadiWael** [bytedeco/javacv#94]
Bjr, 
j'ai deux questions:
1/ Comment extraire le son à partir d'un vidéo et quelles sont les fonctions de manipulation du son
2/ Comment je peux envoyer des frames (iplImage) en utilisant les sockets 
Merci d'avance

**Comment by saudet** [comment]
`FrameGrabber.grab()` retourne l'audio via `Frame.samples` et à partir de là on peut en faire ce qu'on en veut, avant de le refiler à `FrameRecorder.record()`. Le module `avfilter` de `FFmpeg` offre des fonctions pour manipuler le son, mais il faudrait rendre leur utilisation plus conviviale:
https://code.google.com/p/javacv/issues/detail?id=397
Est-ce que ça vous intéresserait de travailler sur ce projet?

FFmpeg support l'envoie d'images et de son par les sockets. Souvent, il ne suffit que de fournir le URL au constructeur de `FFmpegFrameGrabber` ou `FFmpegFrameRecorder`. Si vous avez des problèmes, veuillez S.V.P. poser des questions plus spécifiques! Merci
