### ISSUE TITLE
How to obtain yuv byte array from grabber

### ISSUE THREAD

**Issue by palak18j** [bytedeco/javacv#940]
I am extracting frames from mp4 file, but ultimately I want those frames to be converted in yuv420 format byte array. There is no way to know what is the pixel format or change it during extraction.This is what I am doing currently, unsure of whether it is in correct pixel format-

            Frame f=grabber.grabImage();
            img=converter1.convert(f);      //converter1=androidFrameConverter

            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            img.compress(Bitmap.CompressFormat.PNG, 100, stream);
            byte[] byteArray = stream.toByteArray();
            

 what is the default format used by FFmpegFramegrabber?And how to get the yuv420 format?

**Comment by saudet** [comment]
Just call `setPixelFormat(AV_PIX_FMT_YUV420P)` before `start()` and it will return frames in that format.

**Comment by palak18j** [comment]
But then it is returning black and white frames, I need colored ones

**Comment by saudet** [comment]
The first channel of YUV420P is a monochrome image. You probably want something else then. Once you figure out what that is, pass it to `setPixelFormat()`.

**Comment by palak18j** [comment]
Actually I need it the same format as we get from camera preview frames(byte[]), at most places it is mentioned as YUV420SP, is it a matter of mentioning pixel format or grabbing all channels in the given format?

**Comment by saudet** [comment]
Then what you're looking for is probably `AV_PIX_FMT_NV21`.
