### ISSUE TITLE
FrameRecoder， tune the  voice volume

### ISSUE THREAD

**Issue by linghushaoxia** [bytedeco/javacv#941]
Help!Help!
I want to use FrameRecoder to tume the volume of the voice，what params should I set?

**Comment by saudet** [comment]
We could use a filter for that, but unfortunately, FFmpegFrameFilter doesn't support audio frames yet... 

Marking this as a duplicate of issue #492. Contributions are welcome!

**Comment by linghushaoxia** [comment]
thanks!I see...

**Comment by saudet** [comment]
Support for audio frames has been added so please give it a try with JavaCV 1.4.2-SNAPSHOT: http://bytedeco.org/builds/ 

We can use the [volume](https://ffmpeg.org/ffmpeg-filters.html#volume) filter to change the volume as shown in the unit test: https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L78
