### ISSUE TITLE
faster way to get bitmap from grabbed frame

### ISSUE THREAD

**Issue by palak18j** [bytedeco/javacv#942]
Is there a faster way to convert the grabbed frame from FFmpegframegrabber because AndroidFrameConverter is taking long and does not let my task to be executed in realtime therefore. Is there anyy ffmpef filter that does so to enable it faster? I tried few ways but all of them returned null(probably because format is not recognised) such as one below-
            ByteBuffer byteBuffer=(ByteBuffer)frame.image[0];
            byte bytearray[]=new byte[byteBuffer.remaining()];
            byteBuffer.get(bytearray);
            Bitmap bmp= BitmapFactory.decodeByteArray(bytearray,0,bytearray.length); 
returned bitmap is null

**Comment by saudet** [comment]
We can use FFmpeg itself by calling FFmpegFrameGrabber.setPixelFormat()
before start().

**Comment by palak18j** [comment]
I need to obtain bitmap, what could be the pixel format to set for that as I am unable to figure it out from the available list- https://ffmpeg.org/pipermail/ffmpeg-devel/2007-May/035617.html

**Comment by saudet** [comment]
AV_PIX_FMT_RGBA

**Comment by saudet** [comment]
Once you have a Frame in the right format, AndroidFrameConverter will be fast:
https://github.com/bytedeco/javacv/blob/master/src/main/java/org/bytedeco/javacv/AndroidFrameConverter.java#L35-L38
