### ISSUE TITLE
displaying a frame object

### ISSUE THREAD

**Issue by sjaiswal25** [bytedeco/javacv#951]
Hi,
I want to display a javacv Frame object directly into a gui container without converting into a buffered image or any of the jpeg/bmp as mentioned in https://docs.oracle.com/javase/8/javafx/api/javafx/scene/image/Image.html. Is there any way in which it can be achieved?

Regards,
Shubham Jaiswal

**Comment by saudet** [comment]
The easiest thing is to create a `CanvasFrame` and call `showImage()` as shown in the README.md file: https://github.com/bytedeco/javacv#sample-usage

And there's an example using JavaFX here:
https://github.com/bytedeco/javacv/blob/master/samples/JavaFxPlayVideoAndAudio.java

We can't access the pixels of `Image`, so I'm afraid that the only option is to convert it to `BufferedImage`.

**Comment by sjaiswal25** [comment]
One final question? Is there a way to return an inputstream from the framegrabber class

**Comment by saudet** [comment]
We can give an InputStream to FFmpegFrameGrabber, and an OutputStream to
FFmpegFrameRecorder, if that's you mean?

**Comment by sjaiswal25** [comment]
I wanted to access the output of the ffmpegframegrabber as a bytestream rather than a frame object, so that I need not convert to a byte stream for displaying in the java. Also, could you please tell if glcanvasframe uses the canvas frame to display an image or has a separate method for image display.

**Comment by saudet** [comment]
GLCanvasFrame uses JogAmp, you probably don't want to use that with JavaFX.
But we can get an InputStream using their helper class on Frame.image[0]:
https://jogamp.org/deployment/v2.3.0/javadoc/gluegen/javadoc/com/jogamp/common/nio/ByteBufferInputStream.html

**Comment by sjaiswal25** [comment]
By InputStream using their helper class on Frame.image[0] you mean that the output frame object returned from Framegrabber.grab can be accessed as a byte stream right?

**Comment by sjaiswal25** [comment]
Thank you

**Comment by sjaiswal25** [comment]
I tried converting the frame buffer directly to a byte array and using pixelwriter to convert it to a writeable image but the frame.image[0].hasarray() statement always returns false. What am i doing wrong?

**Comment by saudet** [comment]
A direct buffer doesn't have an array. You'll need to copy it to an array if you need one.

**Comment by saudet** [comment]
FYI, thanks to @johanvos we now have `JavaFXFrameConverter` for this, see commit https://github.com/bytedeco/javacv/commit/1529ed8da24c65bc80b9362c92077d74aef12ff5.
Please give it a try by using the snapshots: http://bytedeco.org/builds/
