### ISSUE TITLE
App Size is so big

### ISSUE THREAD

**Issue by Mohammad-Tabbara** [bytedeco/javacv#953]
My app size is around 369MB in size is this logical or there is something wrong? I just added the dependency and wrote one java class.  After that some errors popped up regarding the  following packaging options so I added:
```
    packagingOptions {
        exclude 'org/bytedeco/javacpp/windows-x86/*'
        exclude 'org/bytedeco/javacpp/windows-x86_64/*'
        exclude 'org/bytedeco/javacpp/macosx-x86_64/*'
    } 
```
to the gradle file.
Note: This is my first writing an issue.

**Comment by saudet** [comment]
Start by excluding packages you don't need...
