### ISSUE TITLE
How to stitch/merge two video in javacv?

### ISSUE THREAD

**Issue by gowridev** [bytedeco/javacv#955]
I would like to merge two videos of equal time duration(stitch side by side). 

merging of two videos in  ffmpeg command line is given below.
ffmpeg -i left.mp4 -i right.mp4 -filter_complex "[0:v][1:v]hstack=inputs=2[v]; [0:a][1:a]amerge[a]" -map "[v]" -map "[a]" -ac 2 output.mp4 

Could please guide me how to achieve this in Javacv?

**Comment by saudet** [comment]
I'm assuming that you want to have the ability to input more than 1 frame for each output frame, so I will mark this as "enhancement". On the other hand, if you merely want the ability to read multiple files, we can use the `movie` filter for that. Either way, contributions are always welcome, so if you decide to update `FFmpegFrameFilter` and run into any issues, please let me know and I will help! Thanks

**Comment by saudet** [comment]
I've implemented support for multiple inputs, refer to this sample code that does exactly what you need:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L136
Please give it a try with the snapshots: http://bytedeco.org/builds/  Thanks!

**Comment by saudet** [comment]
Support now included in JavaCV 1.4.4! Enjoy
