### ISSUE TITLE
High FPS and resolution webcam recording.

### ISSUE THREAD

**Issue by santelos** [bytedeco/javacv#957]
Hi, i'm working on a project that records a webcam output to a file.
I'm using OpenCVFrameGrabber and FFmpegFrameRecorder.
I have a Logitech C920 Webcam.

I need to get a video in FullHD resolution with at least 30 FPS.
But with this piece of code gives me 30FPS only with 480p resolution and lower.

How could i improve my code to get what i want?

`import org.bytedeco.javacpp.avcodec;
import org.bytedeco.javacpp.avutil;
import org.bytedeco.javacv.*;

import javax.imageio.ImageIO;
import java.io.File;
import java.io.IOException;

public class VideoRecorder {

    OpenCVFrameGrabber grabber;
    FFmpegFrameRecorder recorder;
    private Double FRAMERATE = 30D;
    private Integer BITRATE = 3 * 1024 * 1024;
    private Integer WIDTH = 854;
    private Integer HEIGHT = 480;
    private String FORMAT = "mp4";
    private Boolean isRecording = false;

    public void open() {

        grabber = new OpenCVFrameGrabber(0);
        grabber.setFrameRate(FRAMERATE);
        grabber.setOption("input_format", "h264");
        grabber.setVideoBitrate(BITRATE);
        grabber.setAudioChannels(0);
        grabber.setImageWidth(WIDTH);
        grabber.setImageHeight(HEIGHT);

        try {
            grabber.start();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }
    }

    public void start(String fileName) {
        if (grabber == null) throw new NullPointerException("Grabber not initialized (has open() been invoked?)");

        recorder = new FFmpegFrameRecorder(fileName + ".mp4", grabber.getImageWidth(), grabber.getImageHeight());
        recorder.setInterleaved(false);
        recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        recorder.setVideoOption("preset", "ultrafast");
        recorder.setFormat(FORMAT);
        recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
        recorder.setFrameRate(FRAMERATE);
        recorder.setVideoBitrate(BITRATE);

        try {
            recorder.start();
        } catch (FrameRecorder.Exception e) {
            e.printStackTrace();
        }
        setRecording(true);

        //this thread runs until close() method will be invoked
        new Thread(() -> {
            Frame grabbedImage;
            try {
                //when stop() is called, this cycle stops and it creates a new .mp4 file
                while (((grabbedImage = grabber.grab()) != null) && isRecording()) {
                    recorder.record(grabbedImage);
                    System.out.println(recorder.getFrameNumber());
                    //optional, it saves the 20th frame to a jpg
                    if (recorder.getFrameNumber() == 20) {
                        Frame finalGrabbedImage = grabbedImage;
                        new Thread(() -> {
                            Java2DFrameConverter java2DFrameConverter = new Java2DFrameConverter();
                            try {
                                ImageIO.write(java2DFrameConverter.convert(finalGrabbedImage), "jpg", new File(fileName + ".jpg"));
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                        }).start();
                    }
                }
            } catch (FrameRecorder.Exception | FrameGrabber.Exception e) {
                e.printStackTrace();
            }

            try {
                recorder.stop();
                recorder.release();
            } catch (FrameRecorder.Exception e) {
                e.printStackTrace();
            }

        }).start();

    }

    public void stop() {
        if (!isRecording()) return;
        setRecording(false);
    }

    public void close() {
        stop();
        try {
            grabber.stop();
            grabber.release();
            recorder.stop();
            recorder.release();
        } catch (FrameRecorder.Exception | FrameGrabber.Exception e) {
            e.printStackTrace();
        }
    }

    synchronized public void setRecording(Boolean recording) {
        isRecording = recording;
    }

    synchronized public Boolean isRecording() {
        return isRecording;
    }
}
`

**Comment by santelos** [comment]
Thanks for the answer.
I have a few questions then...

How do i check if it's enabled or not?
Where can i read about it? How exactly does it parallel the frames grabbing?

Another one question about the framerate
My camera gives me a 30 fps stream, so when i grab the frame and procces of it takes >1000ms/framerate, it means that i don't match the input stream framerate. As a result, i miss some frames. If i will grab 10 frames per second and record it as 30 frames the video will be faster. What should i do to fix it?

Thanks a lot, i hope i don't bother you

**Comment by saudet** [comment]
Like I said, make sure to use threads. All the info is in FFmpeg's docs:
https://ffmpeg.org/ffmpeg-codecs.html#libx264_002c-libx264rgb
Use setVideoOption() to set the options. It will also display by default on
the console the number of threads it's using, so check there to make sure
it's some number greater than 1 like 4.

**Comment by santelos** [comment]
I did like you said and that's what i've got
with the following code:

> FFmpegLogCallback.set();
recorder = new FFmpegFrameRecorder(fileName+".mp4",grabber.getImageWidth(),grabber.getImageHeight());
recorder.setInterleaved(false);
recorder.setVideoOption("threads","10");
recorder.setVideoCodec(avcodec.AV_CODEC_ID_MPEG4);
recorder.setVideoOption("preset", "ultrafast");
recorder.setFormat(FORMAT);
recorder.setPixelFormat(avutil.AV_PIX_FMT_YUV420P);
recorder.setFrameRate(FRAMERATE);
recorder.start();


I see no info about the Theads or something like that

> Output #0, mp4, to '.\videos\default[0].mp4':
Output #0, mp4, to '.\videos\default[0].mp4':
Metadata:
Metadata:
encoder         : 
encoder         : 
Lavf57.83.100
Lavf57.83.100
Stream #0:0
Stream #0:0
: Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 1920x1080, q=2-31, 4194 kb/s
: Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 1920x1080, q=2-31, 4194 kb/s
,
,
12800 tbn
12800 tbn

**Comment by saudet** [comment]
Use H264 as codec, not MPEG4.
