### ISSUE TITLE
Generate Saliency Map

### ISSUE THREAD

**Issue by Skazza94** [bytedeco/javacv#958]
Hello,
OpenCV 3.0 allows the user to generate Saliency map from a given Mat ([here](https://github.com/opencv/opencv_contrib/blob/master/modules/saliency/samples/computeSaliency.cpp)).

I was wondering if this is also possible in JavaCV because I can't figure out how to do it.

Thanks in advance.

**Comment by saudet** [comment]
It shouldn't be too hard to add. We probably just need to enable it in cppbuild.sh and add a small file in the "presets" subdirectory like in commit https://github.com/bytedeco/javacpp-presets/commit/fdc7008402da3a985cad23993986fd17fc0370dd

Let me know if you encounter any issues and I will help! Thanks

**Comment by LuigiDonofrio** [comment]
I have the same issue, but I can't figure out which "small file" should I add to the "presets" subdirectory.

**Comment by Skazzino** [comment]
Hi, I'm using JavaCV as a Maven dependency in a shared project. So it'll be too risky to compile/import the JARs manually since my other colleagues will still have the old version and won't be able to compile/use the Saliency library correctly. Is there any chance to have a quick commit on the repo to make it works?

**Comment by saudet** [comment]
Sure, if you submit a pull request, the CI servers will build and deploy a
new set of JAR files automatically. We just need to add an
opencv_saliency.java file, if that's the name of the module.

**Comment by saudet** [comment]
@LuigiDonofrio It will be very similar to other presets file, such as this one that we can use as template, among others in the same directory:
https://github.com/bytedeco/javacpp-presets/blob/master/opencv/src/main/java/org/bytedeco/javacpp/presets/opencv_bgsegm.java

**Comment by saudet** [comment]
Thanks for the contribution @Skazzino! Once the CI servers are done building and deploying everything, in a few hours, you will be able to download updated snapshot artifacts: http://bytedeco.org/builds/

**Comment by Skazzino** [comment]
Hi, after 1 week I'm still not able to use Saliency classes into my project. I've imported the snapshot following your tutorial on bytedeco.org but even if I've got the 1.4.2-SNAPSHOT in my project, I can't instantiate any Saliency class. Can you help me? Thanks :D

**Comment by saudet** [comment]
What's the error message?

**Comment by Skazzino** [comment]
As you can see on Eclipse: 

![this screenshot](https://user-images.githubusercontent.com/10586339/39272043-14ae1042-48db-11e8-8ae7-8d73d7a3fb27.png)

When I type "Saliency" and i try to show suggestions, nothing is showed. Any of [those classes](https://docs.opencv.org/3.3.0/d9/dcd/classcv_1_1saliency_1_1Saliency.html) is showed.

**Comment by saudet** [comment]
It's "opencv_saliency"

**Comment by saudet** [comment]
```
import static org.bytedeco.javacpp.opencv_saliency.*;
```
builds fine here. Eclipse doesn't have very good support for Maven. Try again on the command line, with 1.4.2-SNAPSHOT, *not* 1.4. Version 1.4 is definitely now going to work! You need to use 1.4.2-SNAPSHOT.

**Comment by Skazzino** [comment]
Okay, I've replaced the 1.4 version of javacv-platform with 1.4.2-SNAPSHOT, updated dependencies using command line with "mvn package" and now i can import that package. Thanks.

I'll see if it works without any problems and then we can close this issue :grinning:
