### ISSUE TITLE
how do I enable the darknet module in JavaCV to use gpu (CUDA)?

### ISSUE THREAD

**Issue by wureka** [bytedeco/javacv#959]
I am trying to use Yolo darknet in javacv 1.4.1.
So my code looks as below:
```
import org.bytedeco.javacpp.opencv_dnn;
import static org.bytedeco.javacpp.opencv_dnn.readNetFromDarknet;

public class HelloOpenCv {
    public static void main(String[] args) {
        String cfgFile = "yolo-v2.cfg";
        String weightFile = "yolo-v2.weights";
        opencv_dnn.Net net = readNetFromDarknet(cfgFile, weightFile);
        ....
        ....
    }
}
```

Well, my question is, how do I enable the darknet module in JavaCV to use gpu (CUDA), instead of cpu ?

**Comment by saudet** [comment]
Simply include all the dependencies listed here:
https://github.com/bytedeco/javacpp-presets/tree/master/opencv#sample-usage
