### ISSUE TITLE
FFmpegFrameGrabber processing delay

### ISSUE THREAD

**Issue by JacobT** [bytedeco/javacv#960]
Hello,

I am trying to analyze video in near real time, and to get started I aim to simply connect to a multicast udp stream (h.264 encoded video).  The end result will only need to process approximately one frame per second, but for now I am just trying to receive and play the video.  I was able to do this quickly and effectively with the following python script:

```python
import cv2

cap = cv2.VideoCapture("udp://@239.0.0.5:1234")
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    else:
        cv2.imshow('frame', frame)
    if cv2.waitKey(20) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
```

Adapting this to Java, it seemed the best option was to use FFmpegFrameGrabber as it has a constructor that takes an input stream.  After creating a udp input stream (using the code found here: http://www.java2s.com/Code/Java/Network-Protocol/UDPInputStream.htm), I created the following java script:

```java

import org.bytedeco.javacv.CanvasFrame;
import org.bytedeco.javacv.FFmpegFrameGrabber;
import org.bytedeco.javacv.Frame;

import javax.swing.*;
import java.io.IOException;
import java.util.LinkedList;
import java.util.Queue;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;


public class FaceDetection {

  private static final CanvasFrame window = new CanvasFrame( "video stuff", 1.0 );
  private static final Queue<Frame> frames = new LinkedList<>();

  public static void main( String[] args ) {
    try( final UdpInputStream is = new UdpInputStream( "239.0.0.5", 1234 ) ) {
      final FFmpegFrameGrabber fg = new FFmpegFrameGrabber( is );
      fg.start();
      window.setCanvasSize( fg.getImageWidth(), fg.getImageHeight() );
      window.setDefaultCloseOperation( WindowConstants.EXIT_ON_CLOSE );

      new ScheduledThreadPoolExecutor( 1 ).scheduleAtFixedRate(
        () -> {
          synchronized( frames ) {
            if( !frames.isEmpty() ) {
              window.showImage( frames.remove() );
            }
          }
        }, 10L, 1000 / (long) fg.getVideoFrameRate(), TimeUnit.MILLISECONDS
      );

      Frame frame;
      while( ( frame = fg.grabImage() ) != null ) {
        synchronized( frames ) {
          frames.add( frame.clone() );
        }
      }
      fg.release();
    } catch( IOException e ) {
      e.printStackTrace();
    }
  }
}
```

When playing the video, it frequently pauses.  Each pause is longer than the previous, and upon inspection the ```grabber.grabImage()``` function is blocking for longer and longer periods of time.  I've tried many combinations of options found https://ffmpeg.org/ffmpeg-formats.html and https://ffmpeg.org/ffmpeg-codecs.html with no change.  

The data comes in bursts, approximately one half to one second apart.  I assume that the problem is either a weird interaction between the ```UdpInputStream`` and the ```FFmpegFrameGrabber``` or a bottleneck somewhere in the FFmpegFrameGrabber class.  This works well when taking the input directly from a file, but that will not work for my application - I must process live streaming data.  Any ideas of how to fix this problem?

Thanks

P.S. This problem should be easily reproducible via streaming a video out with VLC using h.264 + MP4 encoding and udp.

**Comment by saudet** [comment]
Don't use an InputStream if you don't need it.
Just do `new FFmpegFrameGrabber("udp://@239.0.0.5:1234")`.

**Comment by Antoniossss** [comment]
Does that mean that input stream causes the delay?

**Comment by saudet** [comment]
If the format that your camera uses needs some sort of support for seeking for some reason, it will not work well with InputStream, yes. Make sure that this is not the case.
