### ISSUE TITLE
How can I only use special platform jar with maven？

### ISSUE THREAD

**Issue by zhuanqizhirou** [bytedeco/javacv#961]
my pom:
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacv-platform</artifactId>
            <version>1.4.1</version>
        </dependency>

I spent too many time on this, I'm new to maven. I only want use windows platform jars, how can I do that?

**Comment by saudet** [comment]
It's in the README.md file. Execute Maven this way:
mvn -Djavacpp.platform=windows-x86_64 ...

**Comment by zhuanqizhirou** [comment]
Thank you very much！
mvn -Djavacpp.platform=windows-x86_64 clean package
