### ISSUE TITLE
Video surveillance with client that allows to downloading remote archive

### ISSUE THREAD

**Issue by d-a-gerashenko** [bytedeco/javacv#964]
I have a project which became opensource. It's a remote video surveillance system which includes 3 applications: video server, internet server and client. The purpose of this project is access to a remote video-archive. It's not a remote streaming or cloud. Client downloads videos and photos from remote video-server through internet server. Project works unstable and to solve this problem it needs to change fundamental decisions. Now I have no more time for this so I decided to open it. At least there are some interesting parts of code in this project that could be useful for someone.
https://github.com/d-a-gerashenko/com.videoweber
https://github.com/d-a-gerashenko/com.videoweber/tree/master/server/src/com/videoweber/lib/engines/javacv
And of course it works on JavaCV.

**Comment by saudet** [comment]
That's cool! Could you add a link on the following page?
https://github.com/bytedeco/javacv/wiki/Other-Resources
