### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path

### ISSUE THREAD

**Issue by SnehaJagtap** [bytedeco/javacv#965]
I am using the Deeplerning4j library and IntelliJ IDE and also git on windows 10. I want to run a program which is present in this library but I am facing this problem/ Exceptions. Could anyone help to solve this problem??
![untitled](https://user-images.githubusercontent.com/11499262/38915107-208cbff2-4300-11e8-9367-32e9887ea225.png)

**Comment by saudet** [comment]
Is it the same as https://github.com/bytedeco/javacv/issues/48#issuecomment-382275816? If so, for some reason `opencv-3.4.1-1.4.1-windows-x86_64.jar` is missing from your class path, so please add it manually.

**Comment by SnehaJagtap** [comment]
Ok. Thank you, sir. 
Could you please provide me the steps for manually adding this jar file?. Actually, I am new user for a dl4j library as well as IntelliJ.

**Comment by saudet** [comment]
Please try to follow the instructions here: https://deeplearning4j.org/quickstart
