### ISSUE TITLE
using av_interleaved_write_frame() is hang when the connection to server is down.

### ISSUE THREAD

**Issue by alexnth** [bytedeco/javacv#967]
Hi All,
I use the ffmpeg to stream the encoded video. when the video is streaming, it plug out the internet cable, it means connection to the serve is lost. the video is hangs, i can not handle after that. i see the reason that it is hang at av_interleaved_write_frame(), this function doesn't return result or any error, it hangs forever at there.
How can i exit this case ?
Anyone see that issue, and Can you help me to fix that bug. Thanks.

**Comment by saudet** [comment]
Try to set a timeout:
https://github.com/bytedeco/javacv/blob/master/samples/FFmpegStreamingTimeout.java

**Comment by alexnth** [comment]
Hi saudet,
how i cancel av_interleaved_write_frame when it hangs.

**Comment by saudet** [comment]
We might be able to do that with an interrupt callback: https://github.com/bytedeco/javacv/issues/463

**Comment by alexnth** [comment]
Thanks saudet.
But i am working in c not java, can you help me this issue?

**Comment by techupper** [comment]
I think I am experiencing the same. 
I am trying to grabbing video from a webcam (using  OpenCVFrameGrabber) and record it to a local file and streaming it by using two recorders at the same time (FFmpegFrameRecorder). I try to use the same grabbed frame, but when server connection is down, the code seems to hang on my invocation to the method record of the streaming recorder, which results in my local file missing frames. If I am unable to establish a connection to the streaming server at the beginning, I am able to catch an exception, but not in this case I just described.
Any suggestion on how to go around this issue?
