### ISSUE TITLE
OutOfMemoryError in tomcat and deallocate() did not worked

### ISSUE THREAD

**Issue by blackredscarf** [bytedeco/javacv#976]
I use javacv to detect face in spring boot.
Each time a image is processed, the memory is increased and the memory is not released after processing. I have tried to release it actively, but it has no effect.

My code like this:

the service bean:
```java
@Service
public class FaceDetecor {
    public List<Mat> detect(Mat img) throws IOException {
        RectVector faces = new RectVector();
        CascadeClassifier faceDetector  = new CascadeClassifier("/haarcascade_frontalface_alt.xml");
        faceDetector.detectMultiScale(img, faces);
        faceDetector.deallocate();	// deallocate

        List<Mat> faceList = new ArrayList<>();
        for(int i = 0; i < faces.size(); i++){
            Rect face = faces.get(i);
            faceList.add(new Mat(img, face));
            face.deallocate();	// deallocate
        }
        System.gc();	// gc
        faces.deallocate();	// deallocate
        return faceList;
    }
}
```

in another bean:
```java
@Autowired
FaceDetecor faceDetecor;

public Result handle(Mat img) {
	List<Mat> faces = faceDetecor.detect(img);
	img._deallocate();
	for(Mat face: faces){
	    // to do
            face.release();
            face._deallocate();
        }
        System.gc();
	return Result
}
```

javacv: 1.4
spring boot: 1.5.2
tomcat: 7.0.82

**Comment by saudet** [comment]
You'll need to call Pointer.deallocate() on the images too.

**Comment by blackredscarf** [comment]
@saudet 
I try to `img.deallocate()`, but no effect. Memory usage continues to rise.

**Comment by saudet** [comment]
There's also RectVector...

**Comment by blackredscarf** [comment]
@saudet 
Sure, I deallocated it.

**Comment by saudet** [comment]
We probably need to deallocate each Rect returned by get() as well...

**Comment by saudet** [comment]
Ok, that's there too. Well, if you set the "org.bytedeco.javacpp.logger.debug" system property to true, it will show what gets deallocated manually, and what doesn't. Anything that it shows as getting "collected" is something we forgot to deallocate.

**Comment by blackredscarf** [comment]
@saudet 
I do not quite understand the meaning of the log.
the log: https://gist.github.com/blackredscarf/93de8e897c24a1eab3756109d3809cdd

**Comment by saudet** [comment]
There's a bunch of "Collecting" messages in there. Those are objects that were not deallocated manually. Find out what they are.

**Comment by blackredscarf** [comment]
@saudet 
I tried to debug my program and found that NativeDeallocator, FloatPointer, IntPointer, etc. were generated by Nd4j. For example, `loader.asMatrix(mat)`, `Nd4j.create()`.
I have no way to actively release these memory.

**Comment by saudet** [comment]
Deeplearning4j has a page for that: https://deeplearning4j.org/memory

**Comment by saudet** [comment]
It's now possible to have control over all these Pointer objects, even nested ones, with a PointerScope: https://github.com/bytedeco/javacpp/commit/d98d323778c4b73865d19c7fc15c8380b130f5e0

Simply put all your calls in a block like this:
```java
try (PointerScope scope = new PointerScope()) {
    // ...
}
```
