### ISSUE TITLE
rotate video *.mp4 

### ISSUE THREAD

**Issue by vah13** [bytedeco/javacv#98]
Hi everybody.
Sorry for question but I long time want to know how I can use javacv in android application for rotate mp4video? 
I don't can find API.
Thank you.

**Comment by cangelis** [comment]
This is the method I use for rotating:

    public IplImage rotate(IplImage src, int angle) {
        IplImage img = IplImage.create(src.height(), src.width(), src.depth(), src.nChannels());
        opencv_core.cvTranspose(src, img);
        opencv_core.cvFlip(img, img, angle);
        return img;
    }

Remember to `cvReleaseImage` after you're done with rotated `IplImage`.

**Comment by vah13** [comment]
here you rotate only image or video too?

**Comment by alicanalbayrak** [comment]
You can use Can's method for rotation of a video too. To show a video you
can use cvQueryFrame (returns IplImage) method in a loop.
Then rotate returned IplImage and show rotated IplImage.


2015-03-02 15:57 GMT+02:00 vah13 <notifications@github.com>:

> here you rotate only image or video too?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bytedeco/javacv/issues/98#issuecomment-76715277>.
>



-- 
*-Ali Can*

**Comment by vah13** [comment]
:( 
please can help me http://stackoverflow.com/questions/28796071/how-to-rotate-surfaceview-surfaceholder-for-play-video

**Comment by cangelis** [comment]
You need to iterate over the `Frame`s (`IplImage`) and record each rotated frame. Look at the readme file for a sample usage: https://github.com/bytedeco/javacv/blob/master/README.md

**Comment by vah13** [comment]
thank you.

I use Eclipse, I downloaded jars file and import it with use this instruction 

Eclipse (Java SE 6 or newer):

Navigate to Project > Properties > Java Build Path > Libraries and click "Add External JARs...".
Locate the JAR files, select them, and click OK.


after try import 

import static org.bytedeco.javacpp.opencv_core.*;
import static org.bytedeco.javacpp.opencv_imgproc.*;
import static org.bytedeco.javacpp.opencv_highgui.*;

all finished success.

but where I compile and run write exception

FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: org.bytedeco.javacpp.opencv_highgui
	at preview_pack.PlayerActivity.smooth(PlayerActivity.java:99)

**Comment by vah13** [comment]
and try make this steps but don't help 

Go to File > New > Folder, select your project as parent folder, type "libs/armeabi" as Folder name, and click Finish.
Copy javacpp.jar, javacv.jar, opencv.jar, and ffmpeg.jar into the newly created "libs" folder.
Extract all the *.so files from opencv-android-arm.jar and ffmpeg-android-arm.jar directly into the newly created "libs/armeabi" folder, without creating any of the subdirectories found in the JAR files.
Navigate to Project > Properties > Java Build Path > Libraries and click "Add JARs...".
Select all of javacpp.jar, javacv.jar, opencv.jar, and ffmpeg.jar from the newly created "libs" folder.

**Comment by vah13** [comment]
![javacv_class_notfound](https://cloud.githubusercontent.com/assets/7976421/6469640/4b070cb4-c1ef-11e4-85c1-cdd2f5fac612.png)

**Comment by alicanalbayrak** [comment]
What is that screenshot for? Are you asking for how to bind JavaDoc? Also,
I guess, you have to use some grabber method instead of cvLoadImage.
(Someone please correct me if I'm wrong) But, If I were you, I would try
something like the following:

1- Initialize and start frame grabber before your thread

OpenCVFrameGrabber frameGrabber = new
OpenCVFrameGrabber("/sdcard/Octopus/video/111.mp4");
frameGrabber.setFormat("mp4");
frameGrabber.start();

2- grab image in somewhere in the thread (In this case, call it exactly
where your smooth method has been called)

frameGrabber.grab(); // Returns IPLImage. Take a look (grab method
<https://code.google.com/p/javacv/source/browse/src/main/java/com/googlecode/javacv/OpenCVFrameGrabber.java#233>
)


2015-03-03 20:50 GMT+02:00 vah13 <notifications@github.com>:

> [image: javacv_class_notfound]
> <https://cloud.githubusercontent.com/assets/7976421/6469640/4b070cb4-c1ef-11e4-85c1-cdd2f5fac612.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bytedeco/javacv/issues/98#issuecomment-77008619>.
>



-- 
*-Ali Can*

**Comment by vah13** [comment]
03-03 23:27:07.380: E/AndroidRuntime(12142): FATAL EXCEPTION: main
03-03 23:27:07.380: E/AndroidRuntime(12142): java.lang.NoClassDefFoundError: org.bytedeco.javacv.OpenCVFrameGrabber

**Comment by vah13** [comment]
I Don't  understand why ???

**Comment by saudet** [comment]
@vah13 The Eclipse ADT plugin is buggy and isn't supported by Google anymore. Please switch to Android Studio and follow the instructions here:
https://github.com/bytedeco/javacv/#manual-installation

**Comment by vah13** [comment]
@saudet now I start use Adnroid Studio. All ok, I can install javacv, opencv and ffmpeg :)
but where use 

  public static void smooth(String filename) {
        OpenCVFrameGrabber frameGrabber = new OpenCVFrameGrabber("/sdcard/Octopus/video/111.mp4");
        frameGrabber.setFormat("mp4");
       //.. frameGrabber.
        try {
            frameGrabber.start();
        } catch (FrameGrabber.Exception e) {
            e.printStackTrace();
        }
    }


in start metod get org.bytedeco.javacv.FrameGrabber$Exception: cvCreateFileCapture() Error: Could not create camera capture.
 at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:171)
 at com.octopus.google.camera.MainActivity.smooth(MainActivity.java:109)
exception

**Comment by saudet** [comment]
Try to use `FFmpegFrameGrabber` instead of `OpenCVFrameGrabber`.

**Comment by vah13** [comment]
Cool!!! I think what with opencv need use only Android Studio!

Thank you very much for help me

**Comment by vah13** [comment]
my final code

 public static void video_c(String filename) {
      FFmpegFrameGrabber frameGrabber = new FFmpegFrameGrabber("/sdcard/Octopus/video/112.mp4");
        frameGrabber.setFormat("mp4");
        try {
            frameGrabber.start();
            IplImage i = null;
            FrameRecorder recorder = new FFmpegFrameRecorder("/sdcard/Octopus/video/111.mp4",frameGrabber.getImageHeight() ,
                    frameGrabber.getImageWidth() , frameGrabber.getAudioChannels());
            recorder.setVideoCodec(frameGrabber.getVideoCodec());
            recorder.setFrameRate(frameGrabber.getFrameRate()<30.0?frameGrabber.getFrameRate():30.0);
            recorder.setSampleFormat(frameGrabber.getSampleFormat());
            recorder.setSampleRate(frameGrabber.getSampleRate());
            try {
                recorder.start();
                while ( (i = frameGrabber.grab())!=null)
                {
                    i = rotate(i, 90);

                    try {
                        recorder.record(i);
                        opencv_core.cvReleaseImage(i);
                    } catch (FrameRecorder.Exception e1) {
                        e1.printStackTrace();
                    }

                }
            } catch (FrameGrabber.Exception e1) {
                e1.printStackTrace();
            }
            recorder.stop();
            frameGrabber.stop();

        } catch (FrameRecorder.Exception e1) {
            e1.printStackTrace();
        } catch (FrameGrabber.Exception e1) {
            e1.printStackTrace();
        }

        Log.d("myTag","hhhhhhhhhhhh/");


    }

    public static IplImage rotate(IplImage src, int angle) {
        IplImage img = IplImage.create(src.height(), src.width(), src.depth(), src.nChannels());
        opencv_core.cvTranspose(src, img);
        opencv_core.cvFlip(img, img, angle);
        return img;
    }


but have now problem with audio :-(
no sound in the resulting video

**Comment by saudet** [comment]
For audio, just do something as shown in this sample:
https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java
Actually, we could modify that sample to include rotation, to help others with the same issue. Anyone interested in contributing?

In any case, everyone, thanks for helping out!

**Comment by vah13** [comment]
I use it, but where rotate video with use

public IplImage rotate(IplImage src, int angle) {
    IplImage img = IplImage.create(src.height(), src.width(), src.depth(), src.nChannels());
    opencv_core.cvTranspose(src, img);
    opencv_core.cvFlip(img, img, angle);
    return img;
}android write don't have audio

**Comment by saudet** [comment]
Rotating images and outputting audio are two unrelated tasks, so I'm sorry, but I don't understand what the question is. Please explain more clearly, thank you!

**Comment by vah13** [comment]
all right, no questions :)

**Comment by vah13** [comment]
Now I can capture video from camera (with use RecordActivity from samples).
I understand what this function

       public void stopRecording() {
        runAudioThread = false;
        try {
            audioThread.join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        audioRecordRunnable = null;
        audioThread = null;


        if (recorder != null && recording) {
            if (RECORD_LENGTH > 0) {
                Log.v(LOG_TAG,"Writing frames");
                try {
                    int firstIndex = imagesIndex % samples.length;
                    int lastIndex = (imagesIndex - 1) % images.length;
                    if (imagesIndex <= images.length) {
                        firstIndex = 0;
                        lastIndex = imagesIndex - 1;
                    }
                    if ((startTime = timestamps[lastIndex] - RECORD_LENGTH * 1000000L) < 0) {
                        startTime = 0;
                    }
                    if (lastIndex < firstIndex) {
                        lastIndex += images.length;
                    }
                    for (int i = firstIndex; i <= lastIndex; i++) {
                        long t = timestamps[i % timestamps.length] - startTime;
                        if (t >= 0) {
                            if (t > recorder.getTimestamp()) {
                                recorder.setTimestamp(t);
                            }
                            recorder.record(images[i % images.length]);
                        }
                    }

                    firstIndex = samplesIndex % samples.length;
                    lastIndex = (samplesIndex - 1) % samples.length;
                    if (samplesIndex <= samples.length) {
                        firstIndex = 0;
                        lastIndex = samplesIndex - 1;
                    }
                    if (lastIndex < firstIndex) {
                        lastIndex += samples.length;
                    }
                    for (int i = firstIndex; i <= lastIndex; i++) {
                        recorder.recordSamples(samples[i % samples.length]);
                    }
                } catch (FFmpegFrameRecorder.Exception e) {
                    Log.v(LOG_TAG,e.getMessage());
                    e.printStackTrace();
                }
            }

            recording = false;
            Log.v(LOG_TAG,"Finishing recording, calling stop and release on recorder");
            try {
                recorder.stop();
                recorder.release();
            } catch (FFmpegFrameRecorder.Exception e) {
                e.printStackTrace();
            }
            recorder = null;

        }
    }


write recorded frame to file. Can help me, how I can get IplImage from Frame for use in 


   public static opencv_core.IplImage rotate( opencv_core.IplImage src, int angle) {
           opencv_core.IplImage img = opencv_core.IplImage.create(src.height(), src.width(), src.depth(), src.nChannels());
           opencv_core.cvTranspose(src, img);
           opencv_core.cvFlip(img, img, angle);
           return img;
       }


function for rotate video

**Comment by vah13** [comment]
I found OpenCVFrameConverter.ToIplImage converter2 = new OpenCVFrameConverter.ToIplImage(); and change stopRecording function 

********************************
![green](https://cloud.githubusercontent.com/assets/7976421/6946926/3f0f76c0-d8ac-11e4-8f5e-e6f6c56f04cf.png)


for (int i = firstIndex; i <= lastIndex; i++) {
                        long t = timestamps[i % timestamps.length] - startTime;
                        if (t >= 0) {
                            if (t > recorder.getTimestamp()) {
                                recorder.setTimestamp(t);
                            }
                            Frame g = converter2.convert(rotate(converter2.convertToIplImage(images[i % images.length]),90));
                            recorder.record(g);
                        }
                    }
*************************************

but video have green line :(

**Comment by tomorrowbetter** [comment]
Though there are so many MP4 rotators available, I like iDealshare VideoGo best, for it can helps to rotate MP4 video without re-encoding.

Now i like to share the step by step guide here  http://www.idealshare.net/how-to-rotate-mp4-video.html

Hope it also helps for you.

It even can rotate MOV, MKV, AVI, WMV, WTV, AVCHD, TOD, MOD, DV, FLV and more video files

**Comment by saudet** [comment]
@vah13 Version 0.11 will come with `AndroidFrameConverter.convert(byte[] data, int width, int height)` and `OpenCVFrameConverter.ToIplImage` to convert YUV data from the camera to an `IplImage` that we can use with that rotate function.

**Comment by vah13** [comment]
cool, thank you. :-)

**Comment by saudet** [comment]
@vah13 It's been released! Check out the details here: http://bytedeco.org/news/2015/04/04/javacv-frame-converters/

**Comment by aimkeepachieve** [comment]
You may also follow this guide to rotate MP4 videos at http://www.idealshare.net/how-to-rotate-mp4-video.html

**Comment by mahajandhiraj** [comment]
public static IplImage rotate(IplImage src, int angle) {
    IplImage img = IplImage.create(src.height(), src.width(), src.depth(), src.nChannels());
    opencv_core.cvTranspose(src, img);
    opencv_core.cvFlip(img, img, angle);
    return img;
}

using this method it only flip img by 90 and 270 not by 180 degrees
suggest me solution
