### ISSUE TITLE
rtsp connection gets lost after a while

### ISSUE THREAD

**Issue by guijob** [bytedeco/javacv#980]
I'm trying to grab frames in a RTSP connection streaming in specified periods. But, depending on that period I'm getting `frame == null` from `grabber.grabImage()`. I'm writting this post to get some help to know if it is a bug or an expected behavior and if so, how to change it.

I had written a code to test this behavior:

	Java2DFrameConverter converter = new Java2DFrameConverter();
	FFmpegFrameGrabber grabber = new FFmpegFrameGrabber("rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen02.stream");

	try {
		grabber.setVideoCodec(avcodec.AV_CODEC_ID_H264);
		grabber.setOption("rtsp_transport", "tcp");
		grabber.setImageWidth(1280);
		grabber.setImageHeight(720);
		grabber.start();

		int i = 0;
		while (true) {
			System.out.println("Testing connection for " + i + " seconds...");
			Frame frame = grabber.grabImage();
			if (frame != null) {
				converter.convert(frame);
			} else {
				System.out.println("this lasts for " + i + " seconds");
				throw new Exception();
			}
		
			Thread.sleep(i * 1000);
			i++;
		}
	} catch (Exception e) {
		e.printStackTrace();
	}

And its output:

> Testing connection for 0 seconds...
> Testing connection for 1 seconds...
> ...
> Testing connection for 28 seconds...
> Testing connection for 29 seconds...
> this lasts for 29 seconds
> java.lang.Exception
> 	at streams.StreamThread.run(StreamThread.java:48)
> 	at java.lang.Thread.run(Thread.java:748)
> Input #0, rtsp, from 'rtsp://freja.hiof.no:1935/rtplive/_definst_/hessdalen02.stream':
>   Metadata:
>     title           : hessdalen02.stream
>   Duration: N/A, start: 0.128000, bitrate: N/A
>     Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp
>     Stream #0:1: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 59.94 fps, 59.94 tbr, 90k tbn, 119.88 tbc
> [NULL @ 000000000031e720] missing picture in access unit with size 48
> [h264 @ 000000001bdfc8a0] no frame!

Any advices?

**Comment by saudet** [comment]
If the same thing happens with other applications, it's probably a problem
with your network.

**Comment by saudet** [comment]
But this happens only with JavaCV, please post the debug log of FFmpeg and let's take a look! Thanks
