### ISSUE TITLE
Audio Filter in javacv

### ISSUE THREAD

**Issue by zchacker** [bytedeco/javacv#982]
Hi, i tried to use ffmpeg audio filters but it dose not works
i want to apply this filter 

-af highpass=f=800,lowpass=f=150,agate=range=1

and this is the code that i add

```
String filters = "highpass=f=800,lowpass=f=150,agate=range=1`";
FFmpegFrameFilter filter = new FFmpegFrameFilter( filters , 1 , 1 );
filter.start();
```

it give me this error

Media type mismatch between the 'in' filter output pad 0 (video) and the 'Parsed_highpass_0' filter input pad 0 (audio)
Cannot create the link buffer:0 -> highpass:0

what the right way to make this filter , you have to know that is used the class in your samples ( WebcamAndMicrophoneCapture.java)

**Comment by saudet** [comment]
You'll need to set the number of audio channels to a value larger than 0...

**Comment by saudet** [comment]
There's an example in the tests here:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L78
But in your case, since you don't need video filters, we can skip that and you could use something like 
```
String filters = "highpass=f=800,lowpass=f=150,agate=range=1";
FFmpegFrameFilter filter = new FFmpegFrameFilter(filters , numAudioChannels);
filter.start();
```

**Comment by zchacker** [comment]
when i do the code it's not working, how can the filter apply to audio?
i used java sound api .

**Comment by saudet** [comment]
What isn't working? What's your code?

**Comment by zchacker** [comment]
i used the class WebcamAndMicrophoneCapture.java examples and just add this lines after recoder 


String filters = "highpass=f=300,lowpass=f=150,agate=range=1";
FFmpegFrameFilter filter = new FFmpegFrameFilter(filters , numAudioChannels);
filter.start();

the sound did not change after recording and no error messages appear.
would you mind to explain how can i apply the audio filter to sound

**Comment by saudet** [comment]
You'll have to call `push()` and `pull()` as shown in this test:
https://github.com/bytedeco/javacv/blob/master/platform/src/test/java/org/bytedeco/javacv/FrameFilterTest.java#L78

**Comment by zchacker** [comment]
Ok, pull just the frame that i got from grabber? 
the grabber is get video from webcam, is that will work?

**Comment by zchacker** [comment]
and in case i record just an audio , how can i push sound samples and pull it

**Comment by saudet** [comment]
Put the samples in a Buffer;
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java#L174
And then put that in a Frame.

**Comment by zchacker** [comment]
OK, it work with me very well.

i will put my code to help others to solve their problem if they want to add audio filter to recorder.

this is and a filter initialization


String filters = "agate=ratio=9000,highpass=f=300,lowpass=f=1000,treble=g=0,volume=1";
final FFmpegFrameFilter audioFilter = new FFmpegFrameFilter( filters , AUDIO_CHANNEL);		
try {
    audioFilter.start();
} catch (org.bytedeco.javacv.FrameFilter.Exception e2) {
    e2.printStackTrace();
}

and this were i put samples in a buffer

i modified from this lines
https://github.com/bytedeco/javacv/blob/master/samples/WebcamAndMicrophoneCapture.java#L164

```
int nSamplesRead = nBytesRead / 2;
short[] samples = new short[nSamplesRead];
		                        		                        
// Let's wrap our short[] into a ShortBuffer and
 // pass it to recordSamples
		                        ByteBuffer.wrap(audioBytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(samples);                                		                        				                                                      
ShortBuffer sBuff = ShortBuffer.wrap(samples, 0, nSamplesRead);
                    
// here create a frame to add a samples to it
                                            
Frame audioFrame 			= new Frame();
audioFrame.sampleRate 	= sampleRate;
audioFrame.audioChannels	= AUDIO_CHANNEL;

//here add buffer to frame
audioFrame.samples 		= new ShortBuffer[] {sBuff};

// apply a filter                                
audioFilter.push(audioFrame);
audioFrame = audioFilter.pull();
                                                                
// recorder is instance of
// org.bytedeco.javacv.FFmpegFrameRecorder 
// audioFrame.samples this is samples                 
recorder.recordSamples(sampleRate, numChannels, audioFrame.samples);
```
 thanks Samuel Audet for help

**Comment by saudet** [comment]
Awesome! If you have a bit of time, please send the updated WebcamAndMicrophoneCapture.java as a pull request! Thanks

**Comment by zchacker** [comment]
OK, i will do soon

**Comment by saudet** [comment]
BTW, if the `ffmpeg` program is sufficient, with commit https://github.com/bytedeco/javacpp-presets/commit/13ffffd191fa48d9d9d1d8a64e0c4d64c9da1134 it now gets bundled and can be used easily from Java.

Please give it a try with 1.5-SNAPSHOT before the release: http://bytedeco.org/builds/
