### ISSUE TITLE
Using FFmpeg transpose property outputs a video with green vertical line

### ISSUE THREAD

**Issue by ritesh94** [bytedeco/javacv#984]
I want to rotate a video, so when I use transpose property in FFmpegFrameFilter, it outputs a video which is correctly rotated but with green vertical bars. 

> If I only use **crop** property there are no green bars.
> If I only use **transpose** property without crop property then also I see green bars in the output video.

```
ArrayList<String> filters = new ArrayList<String>();
filters.add("transpose=2");  // 0,1,2,3
filters.add(String.format(Locale.getDefault(), "crop=w=%d:h=%d:x=0:y=0", imageWidth, imageWidth));

String filtersString = TextUtils.join(",", filters); 
System.out.println("FFMPEG LIST COMMANDS : "+filtersString);
mFrameFilter = new FFmpegFrameFilter(filtersString, imageWidth, imageWidth);
mFrameFilter.setPixelFormat(avutil.AV_PIX_FMT_NV21); //default format on android
```

**Comment by saudet** [comment]
I've replaced `"transpose=0"` with `"transpose=2,crop=w=200:h=200:x=0:y=0"` in https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java and it works just fine, so just do it that way!
