### ISSUE TITLE
Cropping issue with front camera using FFmpegFramerecorder and FFmpegFrameFilter

### ISSUE THREAD

**Issue by ritesh94** [bytedeco/javacv#988]
**Issue**
Recording video using front camera and cropping it gives output as a video cropped from the top. It should be cropped from the bottom.

**Version**
```
compile(group: 'org.bytedeco', name: 'javacv-platform', version: '1.4.1') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: 3.4.1-1.4
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: 3.4.1-1.4, classifier: 'android-arm'
```

**Code where recorder and filter is being initialised:**

        int frameRate = 30;
        int frameDepth = Frame.DEPTH_UBYTE;
        int frameChannels = 2;
        Log.w(LOG_TAG, "init recorder");
        String ffmpeg_link = Environment.getExternalStorageDirectory() + "/videoCv.mp4";

        int imageWidth = mImageSize.getHeight();
        int imageHeight = mImageSize.getWidth();

        if (yuvImage == null) 
            yuvImage = new Frame(imageHeight, imageWidth, frameDepth, frameChannels);

        Log.i(LOG_TAG, "ffmpeg_url: " + ffmpeg_link + " Size: -->" + imageWidth + " " + imageHeight);

        mFrameRecorder = new FFmpegFrameRecorder(ffmpeg_link, imageWidth, imageWidth, 1);
        mFrameRecorder.setFormat("mp4");
        mFrameRecorder.setSampleRate(sampleAudioRateInHz);
        mFrameRecorder.setFrameRate(frameRate);
        mFrameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        mFrameRecorder.setVideoOption("crf", "28");
        mFrameRecorder.setVideoOption("preset", "superfast");
        mFrameRecorder.setVideoOption("tune", "zerolatency");
        mFrameRecorder.setVideoQuality(1);

        //  90 for back  camera;
        // 270 for front camera;
        mIsFacingFront = true;
        if (mIsFacingFront)
            mFrameRecorder.setVideoMetadata("rotate", "270");
        else
            mFrameRecorder.setVideoMetadata("rotate", "90");

        String filtersString = "crop=w=720:h=720:x=0:y=0"

        System.out.println("FFMPEG LIST COMMANDS : " + filtersString);
        mFrameFilter = new FFmpegFrameFilter(filtersString, imageWidth, imageWidth);
        mFrameFilter.setPixelFormat(avutil.AV_PIX_FMT_NV21); //default format on android

[https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java](https://github.com/bytedeco/javacv/blob/master/samples/RecordActivity.java) looked at this file too but no luck.

**1. Preview and the desired output only visible region is to be processed and cropped**
![Preview and the desired output only visible region is to be processed and cropped](https://user-images.githubusercontent.com/13624902/39747090-ec79da68-52c9-11e8-835d-542f98208a0e.jpeg)

**2. Cropped output upto bottom of preview (Issue !!)**
![cropped output upto bottom of preview](https://user-images.githubusercontent.com/13624902/39747091-eca615e2-52c9-11e8-992e-19c92bb06ce0.jpeg)

tried changing the value of `x` and `y` from this : `crop=w=720:h=720:x=0:y=0` but no luck.!!

**Comment by saudet** [comment]
That's an issue with FFmpeg, at best. Please post upstream!

**Comment by ritesh94** [comment]
@saudet what do you mean by posting upstream?

**Comment by saudet** [comment]
https://www.ffmpeg.org/contact.html

**Comment by saudet** [comment]
Well, actually, try with the `ffmpeg` program on the command line, and if you get different results, please let me know.

**Comment by ritesh94** [comment]
@saudet what I am doing is processing the frames of the video at the time of live recording. (not using an existing video file).

If I take an existing video file and process through command line ` crop=w=720:h=720:x=0:y=0 ; ` outputs the video correctly as seen in the visible region of the preview.

**Comment by ritesh94** [comment]
@saudet 

Following is the code inside imageReader:
```
mFrameFilter.push(yuvImage);

System.out.println("IMAGE mFrameFilter wh : "+mFrameFilter.getImageWidth()+" "+mFrameFilter.getImageHeight());
System.out.println("IMAGE mFrameRecorder wh : "+mFrameRecorder.getImageWidth()+" "+mFrameRecorder.getImageHeight());
System.out.println("IMAGE yuvImage wh : "+yuvImage.imageWidth+" "+yuvImage.imageHeight);

Frame frame2;
while ((frame2 = mFrameFilter.pull()) != null) {
        mFrameRecorder.record(frame2, mFrameFilter.getPixelFormat());
        System.out.println("IMAGE frame2 wh : "+frame2.imageWidth+" "+frame2.imageHeight);
}
```

Below are the logs:
IMAGE mFrameFilter wh : 720 720
IMAGE mFrameRecorder wh : 720 720
IMAGE yuvImage wh : 960 720
IMAGE frame2 wh : 720 720

I guess there might be some issue with FFmpegFrameFilter..!!

**Comment by saudet** [comment]
Try to replace
```java
    mFrameFilter = new FFmpegFrameFilter(filtersString, imageWidth, imageWidth);
```
with
```java
    mFrameFilter = new FFmpegFrameFilter(filtersString, imageWidth, imageHeight);
```

**Comment by ritesh94** [comment]
@saudet 
After replacing with  `mFrameFilter = new FFmpegFrameFilter(filtersString, imageWidth, imageHeight);`
The video scales to 720 * 720.. but its not getting cropped.!

**Comment by saudet** [comment]
Check the log for any warnings...
