### ISSUE TITLE
1920 x 1080 crop to 1080 x 1080 taking too long

### ISSUE THREAD

**Issue by tchandok** [bytedeco/javacv#990]
Hi - I simply want to take the native resolution of the video file (upload from video gallery) and then crop it to a square video with the dimensions of the smaller between the height & width. Example 1920x1080 becomes 1080x1080. Frame rate, bitrate, audio properties should all remain the same. Largest video length I am dealing with is 15-secs.

After doing research, it looks like ffmpeg is decoding -> processing -> encoding the video file. Is this correct? In this case, the encoding and decoding would take a lot of time. When we use JavaCV for cropping while a video is being recorded, the crop is instant (no time delay).

Analyzing the original and cropped video files, what we find is that the output resolution is correct (1080x1080), but the framerate has gone from 30fps to 7fps, and the Bitrate is only 10% of the original (when using crf 23). Manipulating the crf number alters the bitrate, but is there a way to simply preserve the original bitrate so that ffmpeg doesn't have to alter it, thus avoiding time delays? I am not sure why the framerate is changing to 7fps when we are specifically mentioning that fps should be 30 (see code below). Another issue we are finding is that the audio is not being saved in the cropped video.

Any help on this is greatly appreciated! 

`private void setUpRecorder(FFmpegFrameRecorder recorder) {
   //    recorder.setInterleaved(true);
       recorder.setFormat("mp4");

       recorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
       recorder.setFrameRate(30);
       recorder.setGopSize(30 * 2);
       recorder.setVideoBitrate(3_000_000);
       recorder.setVideoOption("tune", "zerolatency");
       recorder.setVideoOption("preset", "ultrafast");
       recorder.setVideoOption("crf", "17");

       recorder.setVideoMetadata("rotate", "90");

       recorder.setAudioCodec(avcodec.AV_CODEC_ID_AAC);
       recorder.setSampleRate(44_100);
       recorder.setAudioQuality(0);
       recorder.setAudioChannels(2);
       recorder.setAudioBitrate(128_000);
       recorder.setAudioOption("crf", "0");
   }`

**Comment by saudet** [comment]
You'll have to decode and reencode the video file, and that is slow. There is no working around that.

**Comment by saudet** [comment]
And for `FFmpegFrameRecorder` to work properly, you'll need to call at least `start()` at the beginning and `stop()` at the end.

**Comment by tchandok** [comment]
The code I posted is just the settings, start() and stop() are being used correctly when the settings are used in the actual function. Using crf 5 gives a bitrate close to the original file (but ffmpeg is still working = time consuming). Trying to solve the framerate issue (30fps -> 7fps). Attached is the full block of code FYI.

`public void run() {
       try {
           long processingTime = System.currentTimeMillis();
           System.out.println("TIMETEST start ------------- > "+processingTime);
           Log.d(LOG_TAG, "Setting hardware");
           File video = new File(Environment.getExternalStorageDirectory()+"/instavideo.mp4");
           String output = Environment.getExternalStorageDirectory()+"/instavideo_crop.mp4";

           String filterString = "crop=w=1080:h=1080:x=0:y=0"; // "crop=w=720:h=720"; :x=0:y=0

           FFmpegFrameGrabber grabber = new FFmpegFrameGrabber(video);
           grabber.start();

           FFmpegFrameFilter filter = new FFmpegFrameFilter(filterString, 1920, 1080);
           FFmpegFrameRecorder recorder = new FFmpegFrameRecorder(output, grabber.getImageHeight(), grabber.getImageHeight(), 2);
           setUpRecorder(recorder);

           recorder.start();
           filter.start();

           Log.d(LOG_TAG, "Starting recording >>>>>>  "+grabber.getImageWidth()+" "+grabber.getImageHeight()+" -- "+Utils.getScreenWidth());

           long startTime = System.currentTimeMillis();
           Frame grabbedFrame;
           Frame filteredFrame;

           Log.d(LOG_TAG, "Recording started");
           while ((grabbedFrame = grabber.grab()) != null) {
               Log.v(LOG_TAG, "New grabbed frame");
               filter.push(grabbedFrame);

               while ((filteredFrame = filter.pull()) != null) {
                   Log.v(LOG_TAG, "New filtered frame");
                   long t = 1000 * (System.currentTimeMillis() - startTime);
                   if (t > recorder.getTimestamp())
                       recorder.setTimestamp(t);
                   recorder.record(filteredFrame, filter.getPixelFormat());
               }
           }

           int elapsedSeconds = (int) (System.currentTimeMillis() - startTime) / 1000;
           Log.d(LOG_TAG, "Finishing recording in " + elapsedSeconds / 60 + "m " + elapsedSeconds % 60 + "s");
           grabber.stop();
           filter.stop();
           recorder.stop();
           Log.d(LOG_TAG, "Recording finished");

           System.out.println("TIMETEST end ------------- > "+System.currentTimeMillis());

       } catch (Exception e) {
           e.printStackTrace();
       }
   }`

**Comment by ritesh94** [comment]
Yes removing recorder.setTimestamp(t); works fine. But doesn't make any difference.

**Comment by saudet** [comment]
So try to call `recorder.setTimestamp(grabber.getTimestamp())` instead.

**Comment by saudet** [comment]
If that still doesn't work, please show me the debug log of FFmpeg and let's look for anything suspicious there. Thanks!

**Comment by tchandok** [comment]
Thanks Samuel! FFMPEG on Android is taking too long in general. We’ve tried to optimize it but it isn’t where we need it to be. We are now working on using FFMPEG server side. The eventual plan is to build our own functionality using MediaCodec, this will help avoid the media encode/decode lag. Thank you for your assistance and advice.

—
 Tanveer Chandok
 Co-Founder | WonUpIt, Inc.
 Phone: +1 (404) 731-7776 | +91 900-8163-900
 Email: tanveer@wonup.it | tanveersc@gmail.com
 www.wonup.it

WonUp Your Friends. WonUp The World.

**Comment by saudet** [comment]
BTW, FFmpeg 6.0 now supports hardware accelerated encoding using MediaCodec, so we don't need to use its API directly anymore. Please give it a try with the snapshots: http://bytedeco.org/builds/
