### ISSUE TITLE
how to segment the frame recodrer output file in javacv

### ISSUE THREAD

**Issue by gowridev** [bytedeco/javacv#992]
I would like to break output video file(camera recorder) into segments based on time(like 30 minutes) . We can do this  in ffmpeg command line by using the below command.

ffmpeg -i rtsp://<user>:<password>@xxx.xxx.xxx.xxx:xxx/play1.sdp -c copy -map 0 -f segment -strftime 1 -segment_time 1800 -segment_format mp4 out-%d_%m_%Y-%H_%M_%S.mp4

Could you please tell me how to do it in javacv in frame recorder module(FrameRecorder.java ).

**Comment by saudet** [comment]
See https://github.com/bytedeco/javacv/blob/master/samples/PacketRecorderTest.java for an example of that, but there are known issues, see #818.

BTW, @alicanalbayrak any updates on this?
