### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path in Windows 10

### ISSUE THREAD

**Issue by xxxxvelocityxxxx** [bytedeco/javacv#993]
I have successfully run a java program that utilizes openCV and other associated libraries using Eclipse on Windows 7 but when I try to run the same program, using the same library files, with the same installation of Eclipse on Windows 10 I get an UnsatifiedLinkError. I have tried using the Dependency Walker and it tells me I am missing a bunch of API-MS-WIN-CORE-XXX.DLL's and EXT-MS-WIN-XXXX.DLL's. See here for an explanation that says this is actually ok: https://stackoverflow.com/questions/36240215/dependency-walker-missing-dlls
These are the only DLL's my dependency walker says are missing. Is there something else going on that I'm missing? Something to note, I am using a non-admin account on the windows 10 computer (the same is true for windows 7). Could that be causing the issue?

**Comment by saudet** [comment]
Please try again with JavaCV 1.4.1.

**Comment by xxxxvelocityxxxx** [comment]
Saudet, thank you for your response. One of the first things I tried was using JavaCV 1.4.1 from 1.4. I'm still getting the same error though.

**Comment by saudet** [comment]
Eclipse's support for Maven is pretty buggy. What happens if you try on the
command line with the "mvn" command?

**Comment by saudet** [comment]
I'm assuming all works well with Maven, and in that case I'm afraid you'll need to figure out why your installation of Eclipse isn't working properly! Please let me know if it does not work better with Maven though. Thanks

**Comment by xxxxvelocityxxxx** [comment]
Hey. Sorry about that. The project was at work and I was at home, so I haven't had a chance to try this.  I looked through the Qindows 10 computer and noticed it only had a 32 bit JRE. I got the 64 bit version installed and the problem went away. Thanks for your quick reply.
