### ISSUE TITLE
Trimming video -  pixel format yuv420p is invalid or not supported

### ISSUE THREAD

**Issue by ritesh94** [bytedeco/javacv#995]
W/System.err: Error: [jpegls @ 0xb823f630] Specified pixel format yuv420p is invalid or not supported    
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 26061 (id.camera2basic)

```
            File inputFile = new File(Environment.getExternalStorageDirectory() + "/instavideo.mp4");
            File outputFile = new File(Environment.getExternalStorageDirectory() + "/instavideo_crop.mp4");

            FrameGrabber grabber = new FFmpegFrameGrabber(inputFile);
            grabber.start();
            grabber.setTimestamp(5  * 1000000);


            FrameRecorder recorder = new FFmpegFrameRecorder(outputFile,grabber.getImageHeight(), grabber.getImageHeight(),2);
            recorder.setFrameRate(grabber.getFrameRate());
            recorder.setSampleRate(grabber.getSampleRate());
            recorder.start();

            Frame frame;

            while ((frame = grabber.grab()) != null && recorder.getTimestamp() < 10 * 1000000) {
                recorder.record(frame);
            }

            grabber.stop();
            recorder.stop();
```

The video length is 14 seconds

**Comment by saudet** [comment]
You'll need to set another pixel format for the jpegls codec.

**Comment by ritesh94** [comment]
@saudet 

```
 grabber.setTimestamp(5  * 1000000);
while ((frame = grabber.grab()) != null && recorder.getTimestamp() < 10 * 1000000)
```
Why is this 1000000  number used for while setting the time-stamp?

If I want a video to trim from 5 sec I can use (5 * 1000) = 5000 millis, right ?

**Comment by ritesh94** [comment]
@saudet 
Adding below code worked:
**recorder.setVideoCodec(AV_CODEC_ID_H264);
recorder.setAudioCodec(AV_CODEC_ID_AAC);**

But for 14 sec video when I trim from (5 * 1000000) to (10 * 1000000) then final output video duration is 
**9 sec.**  It should be 5secs,  how can I fix that?

**Comment by saudet** [comment]
Units are microseconds, so if you want 5 seconds, you'll need to give it 5000000.
