### ISSUE TITLE
Can the video be piecewise merged

### ISSUE THREAD

**Issue by umeitime** [bytedeco/javacv#997]
Can the video be piecewise merged?

**Comment by saudet** [comment]
We can do whatever you want with each frame returned!

**Comment by saudet** [comment]
If you have more specific questions, let me know and I will help.

**Comment by umeitime** [comment]
@saudet I need to pause when I shoot videos, so I can generate multiple videos. How do I combine multiple videos into one?

**Comment by saudet** [comment]
Something like https://ffmpeg.org/ffmpeg-filters.html#hstack ?
