### ISSUE TITLE
Is it possible to extract subtitles using current JavaCV FFmpeg Builds?

### ISSUE THREAD

**Issue by anonym24** [bytedeco/javacv#999]
Is it possible to extract subtitles using current JavaCV FFmpeg Builds?

And what about interface (JNI) do I need to create a new one?

when using binary we usually do `ffmpeg -i Movie.mkv -map 0:s:0 subs.srt`
how can we achieve the same using JavaCV FFmpeg shared libs (.so files)?

**Comment by anonym24** [comment]
found out that there are many Java wrappers for FFmpeg in JavaCPP
seems I need to use `avformat`

**Comment by saudet** [comment]
Yes, we'd need to add support for that to FFmpegFrameGrabber and FFmpegFrameRecorder, see https://github.com/bytedeco/javacv/issues/503. 
Contributions are welcome! Please let me know if you encounter any problems using `avformat`.
